"use strict";
const q=(id,question,answers,correct,explanation,hint)=>({id,type:"single",question,answers,correct,explanation,hint});
window.quizQuestions=[
q("ac9s7h02-t01","Two groups classify the same animal differently. One uses genetic relationships; the other groups it with animals that appear in the same season and have related roles on Country. What is the best interpretation?",["The systems use different criteria because they serve different contexts and purposes","One system must be wrong because classifications can never differ","Seasonal knowledge cannot be based on observation","Genetic classification is the only useful system"],0,"Classification systems can use different evidence and criteria because they are designed for different purposes.","Ask why each system exists and what it helps people understand."),
q("ac9s7h02-t02","A community harvest rule protects a species during breeding season. Population surveys over many years show stable adult numbers and regular recruitment of young. What does this evidence most strongly support?",["The timing rule is consistent with sustainable population management","The population can never decline in future","Breeding season has no effect on populations","Long-term observations are irrelevant"],0,"Stable adult numbers and recruitment are evidence consistent with a practice that allows reproduction and renewal.","Do not overclaim beyond the evidence."),
q("ac9s7h02-t03","A researcher studies pollution in low-income communities because they believe environmental harms should be distributed fairly. Which part of the research is most clearly influenced by values?",["The choice of research question","The measured concentration of a pollutant","The chemical formula of the pollutant","The calibration marks on a correct instrument"],0,"Values can influence research priorities without legitimately changing measured data.","Separate choosing the problem from measuring it."),
q("ac9s7h02-t04","Scientists find that a proposed biological control has an 80% chance of suppressing an invasive species but uncertain effects on native food webs. What is the strongest decision-making approach?",["Combine scientific evidence with uncertainty and perspectives of affected communities before deciding","Release it immediately because 80% exceeds 50%","Reject it because no study can be certain","Ask only the group gaining most financially"],0,"A responsible decision weighs evidence, uncertainty, ecological consequences and affected perspectives.","Good decisions consider evidence quality and consequences."),
q("ac9s7h02-t05","A public seasonal calendar identifies plant flowering, animal movement and weather cues for one Country. A student wants to use it to predict events 2,000 km away. What is the main problem?",["The ecological relationships may be place-specific and should not be assumed to transfer unchanged","Seasonal calendars never use observations","Distance has no ecological significance","All Australian environments have identical seasons"],0,"Place-based knowledge should not be generalised beyond the conditions and community context that support it.","Local evidence needs local context."),
q("ac9s7h02-t06","A research team wants to study a plant using knowledge shared by a community knowledge holder. Which plan is strongest?",["Agree on consent, attribution, data use and benefits before collecting or publishing the knowledge","Publish first because science overrides cultural protocols","Remove the knowledge holder's name and use the information freely","Treat online access as automatic permission for commercial use"],0,"Respectful research requires governance and permission, not just scientific interest.","Think consent plus agreed use."),
q("ac9s7h02-t07","Satellite imagery suggests wetland area declined by 12%. Local rangers report that the remaining wetland now dries earlier each year. What is the strongest interpretation?",["The two sources provide complementary evidence about extent and seasonal change","The ranger observations should be ignored because they are not satellites","The satellite result proves why drying occurs","Using two sources makes error impossible"],0,"Different evidence sources can contribute different scales and types of information.","Ask what each source adds."),
q("ac9s7h02-t08","A student writes, 'Because scientific claims need evidence, culture cannot influence science.' Which evaluation is best?",["The claim is incomplete: evidence tests claims, while culture and values can influence questions, priorities, communication and applications","The claim is fully correct because scientists have no social context","The claim is wrong because evidence does not matter","The claim is correct only in astronomy"],0,"Science is evidence-based and also a human endeavour shaped by social context.","Both evidence and context can matter at once."),
q("ac9s7h02-t09","An outside organisation wants to apply a cultural burning practice described for one ecosystem to a very different landscape. What should happen first?",["Check local ecological conditions and seek appropriate local cultural authority before transfer","Assume the practice works identically everywhere","Use the same burn timing because tradition is universal","Ignore local weather, species and fuel patterns"],0,"Land-management practices can be both ecologically and culturally place-specific.","Transfer requires evidence and permission."),
q("ac9s7h02-t10","A pharmaceutical company develops a product after learning about a culturally significant medicinal plant. Which response best addresses the science-as-human-endeavour issue?",["Test safety and effectiveness while also addressing consent, attribution and fair benefit-sharing","Only test whether the product makes money","Assume the knowledge is ownerless because a plant is natural","Avoid naming any community so permission is unnecessary"],0,"Scientific development and ethical knowledge governance must be considered together.","Science quality and knowledge rights are separate but both relevant."),
q("ac9s7h02-t11","Two knowledge systems use different names and categories for the same organisms. Which evidence would best help compare the systems fairly?",["Document the purpose and criteria used by each system, then compare the distinctions each makes","Count which system has more words","Assume the older system is less useful","Translate every term into one English category even when meanings differ"],0,"Fair comparison asks what each classification is designed to do and which observations it encodes.","Purpose and criteria come first."),
q("ac9s7h02-t12","A community observes an insect usually appears before a major seasonal rain. Which investigation best respects and tests the claim?",["With permission, compare dated insect observations with long-term rainfall records and report the local context","Declare the insect causes rain without measurement","Test the claim somewhere unrelated and generalise back","Ignore the observation because it was not generated in a laboratory"],0,"A good investigation turns an observation into a measurable local relationship without overclaiming causation.","Test the pattern in its context."),
q("ac9s7h02-t13","A researcher reports only the scientific measurements from a joint community project and removes the community contribution from the publication. What is the strongest criticism?",["It can misrepresent how the knowledge developed and fail appropriate attribution","It improves accuracy because culture should never be named","It is required whenever instruments are used","It proves the measurements are wrong"],0,"Accurate science communication should represent relevant contributions and agreed attribution.","Who contributed can matter to both accuracy and ethics."),
q("ac9s7h02-t14","Which example best shows a world view shaping scientific development without changing the underlying data?",["A research group prioritises whole-ecosystem relationships rather than studying one commercially valuable species alone","A thermometer changes from 20°C to 40°C because of belief","A DNA sequence changes when translated into another language","A balance gives different mass because the user prefers another result"],0,"World views can influence what relationships and outcomes are considered important to investigate.","Framing can change; measured evidence should not be altered by preference."),
q("ac9s7h02-t15","A cross-cultural project finds that community observations and instrument data disagree. What is the most scientific and respectful next step?",["Check methods, timing, definitions and context for both sources before deciding what the disagreement means","Discard the community observations automatically","Discard the instruments automatically","Average the two results without investigating"],0,"Disagreement should trigger method and context checking rather than automatic ranking.","Investigate why the evidence differs."),
q("ac9s7h02-t16","Which conclusion best fits AC9S7H02 after examining several case studies?",["Scientific knowledge is evidence-based, but the questions pursued, observations emphasised and applications chosen can be shaped by cultural perspectives and world views","Scientific results are whatever a culture prefers","Culture has no role anywhere in science","All knowledge systems use identical methods and purposes"],0,"The curriculum focus is the interaction between evidence-based science and human cultural context.","Keep both evidence and perspective in the conclusion.")
];
