"use strict";
window.skillrPracticeQuestions = [
  {
    "id": "ac9e1ly10-er5-p-001",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Mat. Replace initial /k/ with /m/ and keep /a/ /t/. The child should produce the new spoken word without seeing its spelling.",
    "acceptanceNote": "Mat. Replace initial /k/ with /m/ and keep /a/ /t/. The child should produce the new spoken word without seeing its spelling.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'cat'. Ask the child to change its first sound to the first sound in 'moon' and say the new word.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'cat'. Ask the child to change its first sound to the first sound in 'moon' and say the new word.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 1,
    "correct": "Mat. Replace initial /k/ with /m/ and keep /a/ /t/. The child should produce the new spoken word without seeing its spelling.",
    "explanation": "Mat. Replace initial /k/ with /m/ and keep /a/ /t/. The child should produce the new spoken word without seeing its spelling.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Mat. Replace initial /k/ with /m/ and keep /a/ /t/. The child should produce the new spoken word without seeing its spelling.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-002",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Tin. Change /p/ to /t/ while retaining the vowel and final /n/.",
    "acceptanceNote": "Tin. Change /p/ to /t/ while retaining the vowel and final /n/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'pin'. Ask the child to replace the first sound with the first sound in 'tap'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'pin'. Ask the child to replace the first sound with the first sound in 'tap'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 2,
    "correct": "Tin. Change /p/ to /t/ while retaining the vowel and final /n/.",
    "explanation": "Tin. Change /p/ to /t/ while retaining the vowel and final /n/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Tin. Change /p/ to /t/ while retaining the vowel and final /n/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-003",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Fun. Substitute /f/ for /s/ and preserve the remaining sounds.",
    "acceptanceNote": "Fun. Substitute /f/ for /s/ and preserve the remaining sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'sun'. Ask the child to replace the first sound with the first sound in 'fish'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'sun'. Ask the child to replace the first sound with the first sound in 'fish'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 3,
    "correct": "Fun. Substitute /f/ for /s/ and preserve the remaining sounds.",
    "explanation": "Fun. Substitute /f/ for /s/ and preserve the remaining sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Fun. Substitute /f/ for /s/ and preserve the remaining sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-004",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Dog. Replace /l/ with /d/ while keeping /o/ /g/.",
    "acceptanceNote": "Dog. Replace /l/ with /d/ while keeping /o/ /g/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'log'. Ask the child to change its first sound to the first sound in 'duck'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'log'. Ask the child to change its first sound to the first sound in 'duck'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 4,
    "correct": "Dog. Replace /l/ with /d/ while keeping /o/ /g/.",
    "explanation": "Dog. Replace /l/ with /d/ while keeping /o/ /g/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Dog. Replace /l/ with /d/ while keeping /o/ /g/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-005",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Cat. Replace final /p/ with /t/ and keep the first two sounds.",
    "acceptanceNote": "Cat. Replace final /p/ with /t/ and keep the first two sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'cap'. Ask the child to change the last sound to the last sound in 'wet'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'cap'. Ask the child to change the last sound to the last sound in 'wet'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 5,
    "correct": "Cat. Replace final /p/ with /t/ and keep the first two sounds.",
    "explanation": "Cat. Replace final /p/ with /t/ and keep the first two sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Cat. Replace final /p/ with /t/ and keep the first two sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-006",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Ham. Replace final /t/ with /m/ and retain /h/ /a/.",
    "acceptanceNote": "Ham. Replace final /t/ with /m/ and retain /h/ /a/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'hat'. Ask the child to change the last sound to the last sound in 'sum'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'hat'. Ask the child to change the last sound to the last sound in 'sum'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 6,
    "correct": "Ham. Replace final /t/ with /m/ and retain /h/ /a/.",
    "explanation": "Ham. Replace final /t/ with /m/ and retain /h/ /a/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Ham. Replace final /t/ with /m/ and retain /h/ /a/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-007",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Mat. Replace final /p/ with /t/ and keep /m/ /a/.",
    "acceptanceNote": "Mat. Replace final /p/ with /t/ and keep /m/ /a/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'map'. Ask the child to change the last sound to the last sound in 'wet'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'map'. Ask the child to change the last sound to the last sound in 'wet'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 7,
    "correct": "Mat. Replace final /p/ with /t/ and keep /m/ /a/.",
    "explanation": "Mat. Replace final /p/ with /t/ and keep /m/ /a/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Mat. Replace final /p/ with /t/ and keep /m/ /a/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-008",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Sip. Replace /t/ with /p/ while preserving /s/ /i/.",
    "acceptanceNote": "Sip. Replace /t/ with /p/ while preserving /s/ /i/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'sit'. Ask the child to replace the last sound with the last sound in 'map'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'sit'. Ask the child to replace the last sound with the last sound in 'map'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 1,
    "difficultyTier": "recognise",
    "sequencePriority": 8,
    "correct": "Sip. Replace /t/ with /p/ while preserving /s/ /i/.",
    "explanation": "Sip. Replace /t/ with /p/ while preserving /s/ /i/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Sip. Replace /t/ with /p/ while preserving /s/ /i/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-009",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Big. Change short /a/ to short /i/ while keeping /b/ and /g/.",
    "acceptanceNote": "Big. Change short /a/ to short /i/ while keeping /b/ and /g/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'bag'. Ask the child to replace its middle vowel with the middle vowel in 'sit'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'bag'. Ask the child to replace its middle vowel with the middle vowel in 'sit'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 9,
    "correct": "Big. Change short /a/ to short /i/ while keeping /b/ and /g/.",
    "explanation": "Big. Change short /a/ to short /i/ while keeping /b/ and /g/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Big. Change short /a/ to short /i/ while keeping /b/ and /g/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-010",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Pan. Change short /e/ to short /a/ and keep the consonants.",
    "acceptanceNote": "Pan. Change short /e/ to short /a/ and keep the consonants.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'pen'. Ask the child to replace its middle vowel with the middle vowel in 'cat'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'pen'. Ask the child to replace its middle vowel with the middle vowel in 'cat'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 10,
    "correct": "Pan. Change short /e/ to short /a/ and keep the consonants.",
    "explanation": "Pan. Change short /e/ to short /a/ and keep the consonants.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Pan. Change short /e/ to short /a/ and keep the consonants.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-011",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Hat. Change short /o/ to short /a/, keeping /h/ and /t/.",
    "acceptanceNote": "Hat. Change short /o/ to short /a/, keeping /h/ and /t/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'hot'. Ask the child to replace the middle vowel with the middle vowel in 'bag'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'hot'. Ask the child to replace the middle vowel with the middle vowel in 'bag'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 11,
    "correct": "Hat. Change short /o/ to short /a/, keeping /h/ and /t/.",
    "explanation": "Hat. Change short /o/ to short /a/, keeping /h/ and /t/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Hat. Change short /o/ to short /a/, keeping /h/ and /t/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-012",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Cot. Change short /u/ to short /o/ while preserving the first and last sounds.",
    "acceptanceNote": "Cot. Change short /u/ to short /o/ while preserving the first and last sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'cut'. Ask the child to replace the middle vowel with the middle vowel in 'hot'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'cut'. Ask the child to replace the middle vowel with the middle vowel in 'hot'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 12,
    "correct": "Cot. Change short /u/ to short /o/ while preserving the first and last sounds.",
    "explanation": "Cot. Change short /u/ to short /o/ while preserving the first and last sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Cot. Change short /u/ to short /o/ while preserving the first and last sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-013",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Slip. Insert /l/ after /s/; the other sounds stay in order.",
    "acceptanceNote": "Slip. Insert /l/ after /s/; the other sounds stay in order.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'sip'. Ask the child to add the first sound in 'lip' straight after the first sound in sip.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'sip'. Ask the child to add the first sound in 'lip' straight after the first sound in sip.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 13,
    "correct": "Slip. Insert /l/ after /s/; the other sounds stay in order.",
    "explanation": "Slip. Insert /l/ after /s/; the other sounds stay in order.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Slip. Insert /l/ after /s/; the other sounds stay in order.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-014",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Spot. Add /s/ before /p/ /o/ /t/, without deleting an existing sound.",
    "acceptanceNote": "Spot. Add /s/ before /p/ /o/ /t/, without deleting an existing sound.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'pot'. Ask the child to add the first sound in 'sun' at the very beginning.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'pot'. Ask the child to add the first sound in 'sun' at the very beginning.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 14,
    "correct": "Spot. Add /s/ before /p/ /o/ /t/, without deleting an existing sound.",
    "explanation": "Spot. Add /s/ before /p/ /o/ /t/, without deleting an existing sound.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Spot. Add /s/ before /p/ /o/ /t/, without deleting an existing sound.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-015",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Tent. Add final /t/ after /t/ /e/ /n/; keep the original beginning /t/ too.",
    "acceptanceNote": "Tent. Add final /t/ after /t/ /e/ /n/; keep the original beginning /t/ too.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'ten'. Ask the child to add the first sound in 'top' at the end.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'ten'. Ask the child to add the first sound in 'top' at the end.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 15,
    "correct": "Tent. Add final /t/ after /t/ /e/ /n/; keep the original beginning /t/ too.",
    "explanation": "Tent. Add final /t/ after /t/ /e/ /n/; keep the original beginning /t/ too.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Tent. Add final /t/ after /t/ /e/ /n/; keep the original beginning /t/ too.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-016",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Ramp. Add final /p/ after /r/ /a/ /m/ without changing the earlier sounds.",
    "acceptanceNote": "Ramp. Add final /p/ after /r/ /a/ /m/ without changing the earlier sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'ram'. Ask the child to add the first sound in 'pig' at the end.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'ram'. Ask the child to add the first sound in 'pig' at the end.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 2,
    "difficultyTier": "apply",
    "sequencePriority": 16,
    "correct": "Ramp. Add final /p/ after /r/ /a/ /m/ without changing the earlier sounds.",
    "explanation": "Ramp. Add final /p/ after /r/ /a/ /m/ without changing the earlier sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Ramp. Add final /p/ after /r/ /a/ /m/ without changing the earlier sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-017",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Top. Delete /s/ and blend the remaining /t/ /o/ /p/.",
    "acceptanceNote": "Top. Delete /s/ and blend the remaining /t/ /o/ /p/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'stop'. Ask the child to remove only the first sound and say what remains.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'stop'. Ask the child to remove only the first sound and say what remains.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 17,
    "correct": "Top. Delete /s/ and blend the remaining /t/ /o/ /p/.",
    "explanation": "Top. Delete /s/ and blend the remaining /t/ /o/ /p/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Top. Delete /s/ and blend the remaining /t/ /o/ /p/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-018",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Cap. Remove /l/ from /k/ /l/ /a/ /p/, keeping the other sounds in order.",
    "acceptanceNote": "Cap. Remove /l/ from /k/ /l/ /a/ /p/, keeping the other sounds in order.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'clap'. Ask the child to remove the sound immediately after its first sound.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'clap'. Ask the child to remove the sound immediately after its first sound.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 18,
    "correct": "Cap. Remove /l/ from /k/ /l/ /a/ /p/, keeping the other sounds in order.",
    "explanation": "Cap. Remove /l/ from /k/ /l/ /a/ /p/, keeping the other sounds in order.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Cap. Remove /l/ from /k/ /l/ /a/ /p/, keeping the other sounds in order.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-019",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Sad. Delete /n/ from /s/ /a/ /n/ /d/ and retain the final /d/.",
    "acceptanceNote": "Sad. Delete /n/ from /s/ /a/ /n/ /d/ and retain the final /d/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'sand'. Ask the child to remove the sound immediately before its last sound.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'sand'. Ask the child to remove the sound immediately before its last sound.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 19,
    "correct": "Sad. Delete /n/ from /s/ /a/ /n/ /d/ and retain the final /d/.",
    "explanation": "Sad. Delete /n/ from /s/ /a/ /n/ /d/ and retain the final /d/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Sad. Delete /n/ from /s/ /a/ /n/ /d/ and retain the final /d/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-020",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Ten. Delete the last /t/, not the first /t/, and blend the remaining sounds.",
    "acceptanceNote": "Ten. Delete the last /t/, not the first /t/, and blend the remaining sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'tent'. Ask the child to remove only the final sound.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'tent'. Ask the child to remove only the final sound.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 20,
    "correct": "Ten. Delete the last /t/, not the first /t/, and blend the remaining sounds.",
    "explanation": "Ten. Delete the last /t/, not the first /t/, and blend the remaining sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Ten. Delete the last /t/, not the first /t/, and blend the remaining sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-021",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Crack. Replace /b/ with /k/ while preserving the initial cluster and vowel. The target has four phonemes.",
    "acceptanceNote": "Crack. Replace /b/ with /k/ while preserving the initial cluster and vowel. The target has four phonemes.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'crab'. Ask the child to change the last sound to the last sound in 'sock'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'crab'. Ask the child to change the last sound to the last sound in 'sock'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 21,
    "correct": "Crack. Replace /b/ with /k/ while preserving the initial cluster and vowel. The target has four phonemes.",
    "explanation": "Crack. Replace /b/ with /k/ while preserving the initial cluster and vowel. The target has four phonemes.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Crack. Replace /b/ with /k/ while preserving the initial cluster and vowel. The target has four phonemes.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-022",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Bet. Delete /s/ from /b/ /e/ /s/ /t/ while preserving the other three sounds.",
    "acceptanceNote": "Bet. Delete /s/ from /b/ /e/ /s/ /t/ while preserving the other three sounds.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'best'. Ask the child to remove the third sound and say the remaining word.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'best'. Ask the child to remove the third sound and say the remaining word.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 22,
    "correct": "Bet. Delete /s/ from /b/ /e/ /s/ /t/ while preserving the other three sounds.",
    "explanation": "Bet. Delete /s/ from /b/ /e/ /s/ /t/ while preserving the other three sounds.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Bet. Delete /s/ from /b/ /e/ /s/ /t/ while preserving the other three sounds.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-023",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Fish. Replace /n/ with the single /sh/ phoneme. This is one sound substitution even though spelling uses two letters for sh.",
    "acceptanceNote": "Fish. Replace /n/ with the single /sh/ phoneme. This is one sound substitution even though spelling uses two letters for sh.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'fin'. Ask the child to change the last sound to the last sound in 'wish'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'fin'. Ask the child to change the last sound to the last sound in 'wish'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 23,
    "correct": "Fish. Replace /n/ with the single /sh/ phoneme. This is one sound substitution even though spelling uses two letters for sh.",
    "explanation": "Fish. Replace /n/ with the single /sh/ phoneme. This is one sound substitution even though spelling uses two letters for sh.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Fish. Replace /n/ with the single /sh/ phoneme. This is one sound substitution even though spelling uses two letters for sh.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly10-er5-p-024",
    "curriculumCode": "AC9E1LY10",
    "bank": "practice",
    "skill": "adding, deleting and substituting spoken phonemes",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Ship. Replace the single /ch/ phoneme with /sh/, keeping /i/ /p/.",
    "acceptanceNote": "Ship. Replace the single /ch/ phoneme with /sh/, keeping /i/ /p/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'chip'. Ask the child to change its first sound to the first sound in 'shell'.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'chip'. Ask the child to change its first sound to the first sound in 'shell'.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "reason",
    "sequencePriority": 24,
    "correct": "Ship. Replace the single /ch/ phoneme with /sh/, keeping /i/ /p/.",
    "explanation": "Ship. Replace the single /ch/ phoneme with /sh/, keeping /i/ /p/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Ship. Replace the single /ch/ phoneme with /sh/, keeping /i/ /p/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  }
];
window.quizQuestions = window.skillrPracticeQuestions;
