"use strict";
const Q=(id,n,q,a,c,e)=>({id,curriculumCode:"AC9M10ST03",bank:"test",section:"Scatterplots and association",sourceNumber:n,skill:"construct and interpret scatterplots",printable:true,type:"single",question:q,answers:a,correct:c,explanation:e,structuredExplanation:{summary:e,hint:"Sketch the points if useful and judge the overall pattern, not just one pair."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q("ac9m10st03-t-001",25,"A medicine concentration is measured over time as (1,100), (2,50), (3,25), (4,12). Which description best fits the scatterplot?",["Positive linear","Negative non-linear","No association","Positive non-linear"],1,"The concentration decreases as time increases and the decrease follows a curved decay pattern."),
Q("ac9m10st03-t-002",26,"A bacteria culture is measured at times 1, 2, 3 and 4, giving populations 2, 4, 8 and 16. Which form best describes the association?",["Linear","Non-linear increasing","No association","Negative linear"],1,"The values double each step, producing an increasing exponential curve rather than a straight line."),
Q("ac9m10st03-t-003",27,"A new app records advertising spend and downloads as (1,10), (2,20), (3,30), (4,31), (5,32). Which description is most appropriate?",["Perfect positive linear","Increasing but clearly flattening/non-linear","Negative association","No association"],1,"Downloads rise strongly at first, then level off, so one straight line does not describe the pattern well."),
Q("ac9m10st03-t-004",28,"A savings account balance is represented by (1,5), (2,10), (3,20), (4,40). What is the direction and form?",["Positive non-linear","Negative linear","No association","Positive linear"],0,"The values increase by a constant multiplicative factor, producing an increasing curved pattern."),
Q("ac9m10st03-t-005",29,"A cooling experiment records (1,100), (2,90), (3,80), (4,70), (5,200). Which observation is the clearest outlier?",["(4,70)","(3,80)","(5,200)","There is no outlier"],2,"The first four points follow a steady decrease, while (5,200) is far from that trend."),
Q("ac9m10st03-t-006",30,"A shop records advertising spend and sales as (1,10), (2,12), (3,14), (4,50). Which point most strongly disrupts the linear trend formed by the first three?",["(1,10)","(2,12)","(3,14)","(4,50)"],3,"The first three points lie on y=2x+8; the final point is far above that line."),
Q("ac9m10st03-t-007",31,"A sequence number x is paired with values 2, 3, 5, 7 and 11, giving points (1,2), (2,3), (3,5), (4,7), (5,11). What direction of association is evident?",["Positive","Negative","None","Perfectly horizontal"],0,"The y-values generally increase as x increases."),
Q("ac9m10st03-t-008",32,"A battery test records time and remaining charge as (1,20), (2,18), (3,16), (4,14), (5,13). Which description best fits?",["Strong negative approximately linear","Strong positive","No association","Positive non-linear"],0,"The points remain close to a decreasing straight-line trend."),
Q("ac9m10st03-t-009",33,"Online views after successive shares are (1,10), (2,30), (3,90), (4,270). Which description is best?",["Positive non-linear","Negative linear","No association","Positive linear"],0,"The values multiply by 3 each step, producing exponential growth."),
Q("ac9m10st03-t-010",34,"A machine test gives (1,5), (2,6), (3,7), (4,8), (5,100). Which point is the clearest outlier from the main trend?",["(1,5)","(4,8)","(5,100)","No outlier"],2,"The first four points follow y=x+4, whereas (5,100) is far from that line."),
Q("ac9m10st03-t-011",35,"A retailer records advertising spend and sales as (1,10), (2,20), (3,30), (4,40), (5,41). Which statement is most accurate?",["There is a strong positive association, but the final point falls below the earlier linear trend","There is a strong negative association","There is no association","The pattern is perfectly linear"],0,"Sales generally increase with spend, although the last point is much lower than the value suggested by the first four."),
Q("ac9m10st03-t-012",36,"A radioactive sample is measured at equal time intervals: (1,100), (2,50), (3,25), (4,12), (5,6). Which form best describes the relationship?",["Negative non-linear","Positive linear","No association","Negative linear"],0,"The values approximately halve each step, giving exponential decay."),
Q("ac9m10st03-t-013",37,"A scatterplot of practice time and score contains (1,2), (2,4), (3,6), (4,8), (5,50). Which point is the clearest outlier?",["(1,2)","(4,8)","(5,50)","No outlier"],2,"The first four points lie on y=2x, while (5,50) lies far above that line."),
Q("ac9m10st03-t-014",38,"A device records time and remaining battery as (1,10), (2,9), (3,8), (4,7), (5,6). What is the direction of association?",["Positive","Negative","None","Random"],1,"Battery level decreases consistently as time increases."),
Q("ac9m10st03-t-015",39,"A store records advertising spend and sales as (1,10), (2,20), (3,30), (4,40), (5,200). What effect does the final point have on a straight-line summary of the first four points?",["It makes the data perfectly linear","It acts as an influential outlier and reduces how well the original line describes all points","It creates a negative association","It has no effect"],1,"The first four points lie on a straight line, while the final point is far above it and would strongly affect a fitted line."),
Q("ac9m10st03-t-016",40,"A cyclist's training hours and distance completed are (1,5), (2,10), (3,15), (4,20), (5,25). Which association is shown?",["Strong positive linear","Moderate positive","Weak positive","None"],0,"All points lie exactly on an increasing straight line.")];
window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
