"use strict";
const Q=[
["statistics","Two groups have results A: 9,10,10,11,10 and B: 6,8,10,12,14. Both means are 10. Which statement is best?",["The groups have the same mean but Group B has much greater spread","The groups are statistically identical","Group B is more accurate","Group A must contain an anomaly"],0,"Equal means do not imply equal distributions; Group B is much more variable.","Compare centre and spread."],
["mean median","Data are 4,5,5,6,30. Which pair is correct?",["Mean = 10, median = 5","Mean = 5, median = 10","Mean = 6, median = 5","Mean = 10, median = 6"],0,"The sum is 50, so mean = 10; the ordered middle value is 5.","The outlier pulls the mean."],
["outlier effect","A single very high value is added to a dataset. Which statement is generally most defensible?",["The mean and range may increase substantially while the median may change little","Mean and median must increase equally","The range cannot change","The outlier should automatically be deleted"],0,"Extreme values can strongly affect the mean and range, while the median is comparatively resistant.","Different statistics respond differently to extremes."],
["formula audit","A spreadsheet column of means is wrong because a copied formula shifted from B2:B6 to C2:C6. What does this demonstrate?",["Automated calculations require formula and reference checking","Spreadsheets cannot calculate means","The raw data must be false","Digital tools remove human error"],0,"Automation can propagate a reference mistake consistently across many results.","Audit formulas, not just outputs."],
["scatter interpretation","A scatter plot shows a strong upward association between study time and test score. Which conclusion is justified from the plot alone?",["Higher study time is associated with higher scores in this dataset, but the graph alone does not prove causation","Extra study time is proven to cause every score increase","No other variables could matter","The relationship must continue indefinitely"],0,"Scatter plots can reveal association; causal claims require additional evidence and design considerations.","Correlation ≠ causation."],
["trend model","A straight trend line fits the middle of a dataset but systematically misses both ends. What is the best interpretation?",["A linear model may be inappropriate and another relationship should be considered","The end points should be deleted","The line is correct because software produced it","The axes must start at zero"],0,"A patterned residual/misfit suggests the chosen mathematical model may not represent the relationship well.","Systematic misfit challenges the model."],
["scale comparison","Two websites plot the same temperature data. One uses 0–100 °C; the other 19–21 °C. Why can the graphs look very different?",["Axis range changes the visual prominence of the same numerical variation","One website must have changed the measurements","A narrow scale increases measurement precision","A wide scale creates random error"],0,"The data can be identical while scaling changes how large the variation appears visually.","Same data, different visual emphasis."],
["misleading bars","Company A has 51% and Company B 49%. A bar chart begins at 48%. What is the main risk?",["The 2 percentage-point difference can appear proportionally enormous because bar lengths are truncated","The percentages become mathematically incorrect","The chart cannot display categories","Starting at 48% removes uncertainty"],0,"Truncating a bar-chart baseline can exaggerate relative visual differences.","Bar lengths should support honest magnitude comparison."],
["axis break","When can an axis break be acceptable?",["When it is clearly marked, justified by the data and does not conceal relevant patterns","Whenever it makes the preferred result look larger","Only when all data are deleted below the break","Never in any scientific representation"],0,"Axis breaks can be legitimate but must be transparent and used carefully to avoid distortion.","Transparency and justification matter."],
["representation choice","Researchers need to show both where bushfire extent changed and the exact area burned each year. Which communication is strongest?",["A mapped/time-lapse spatial representation plus a quantitative time-series graph","A pie chart only","A single photograph","A table with no dates or locations"],0,"Combining spatial and quantitative representations communicates complementary aspects of the evidence.","Match representations to different questions."],
["uncertainty display","Two treatment means differ slightly, but their measurements vary widely. What addition to the graph would most help interpretation?",["A suitable display of variability or uncertainty, such as error bars with a defined meaning","A 3D effect","A narrower y-axis only","Removal of all individual observations"],0,"Showing variability helps readers judge how well the mean difference is resolved by the data.","Means alone can hide spread."],
["anomaly reasoning","A periodic-property graph has a point that departs from a simple trend. What is the strongest scientific response?",["Check data quality, then consider whether atomic structure or bonding provides a real explanation for the departure","Delete it because periodic trends cannot have exceptions","Conclude the periodic table is wrong","Move the point onto the trend line"],0,"Anomalies may be genuine and informative after measurement or data errors are ruled out.","Investigate before explaining or excluding."],
["model limits","An interactive climate model lets users vary CO₂ but holds every other factor fixed. What should accompany conclusions from it?",["A statement that the model isolates selected relationships and does not represent every interacting climate process","A claim that it predicts the exact future climate","A statement that models replace observations","No explanation because interactive models have no assumptions"],0,"Models simplify systems; communicating assumptions and limitations prevents overinterpretation.","Every model has a scope."],
["data transformation","A student changes raw values to percentages before graphing. What is essential?",["Explain the calculation and retain the original data so the transformation is transparent and checkable","Delete the raw values to avoid confusion","Choose percentages that make the pattern clearer","Round every percentage to the nearest 10%"],0,"Processed data should remain traceable to the original measurements and method.","Keep transformations transparent."],
["representation distortion","Which practice most directly violates the goal of representing data without distortion?",["Selecting an axis range solely to make a small preferred effect appear dramatic while hiding relevant context","Using a scatter plot for paired quantitative data","Reporting median for a skewed dataset","Providing a table alongside a graph"],0,"Representation choices should clarify evidence, not manipulate visual perception toward a preferred conclusion.","Ask whether the choice informs or persuades unfairly."],
["combined evidence","A time-lapse appears to show shrinking ice, while measured area data show large year-to-year fluctuations around a long-term decline. Which conclusion best uses both?",["The images illustrate spatial change, while the quantitative series shows variability plus an overall declining trend","The images prove every year has less ice than the previous year","The fluctuations mean no long-term trend can exist","Only one representation should be reported"],0,"Multiple representations can reveal both an overall pattern and short-term variability without forcing either to replace the other.","Integrate, don't oversimplify, representations."]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s10i04-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I04",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));