"use strict";
const Q=(id,n,section,question,answers,correct,explanation)=>({id:`ac9s10u04-t-${String(id).padStart(3,"0")}`,curriculumCode:"AC9S10U04",bank:"test",section,sourceNumber:n,skill:section,printable:true,type:"single",question,answers,correct,explanation,structuredExplanation:{summary:explanation,hint:"Use the evidence and mechanism in the scenario; eliminate options that overstate what the evidence proves."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q(1,25,"Evidence","A climate record shows atmospheric CO₂ rising while outgoing infrared radiation decreases specifically at CO₂ absorption wavelengths. What mechanism does this support?",["A reduction in Earth's gravity","Enhanced greenhouse absorption of infrared radiation","Plate tectonics as the direct cause","A complete shutdown of ocean circulation"],1,"Spectral changes at greenhouse-gas absorption bands are consistent with enhanced trapping/re-emission of infrared radiation."),
Q(2,26,"Sea level","A glacier on land loses 100 km³ of ice, while an equal volume of floating sea ice melts. Which has the larger direct effect on sea level?",["The melting sea ice","They have exactly the same direct effect","The melting land ice","Neither can affect sea level"],2,"Land ice adds new water to the ocean; floating ice already displaces approximately its own mass of seawater."),
Q(3,27,"Volcanic forcing","After a volcanic eruption, global temperature falls slightly for two years and then recovers. Which observation would best explain the temporary cooling?",["A short-lived increase in reflective stratospheric sulfate aerosols","A permanent drop in solar luminosity","Rapid removal of all greenhouse gases","Formation of a new mountain range"],0,"Stratospheric sulfate aerosols have a temporary negative radiative forcing."),
Q(4,28,"Feedbacks","A model predicts that Arctic warming melts permafrost, releasing CO₂ and methane. Why is this a positive feedback?",["The gases reflect sunlight and cool the surface","Permafrost thaw removes greenhouse gases","The process automatically reverses the initial warming","The released greenhouse gases can cause additional warming, promoting further thaw"],3,"Permafrost-carbon feedback can amplify warming by releasing greenhouse gases."),
Q(5,29,"Feedbacks","Which is the best example of a stabilising negative climate feedback?",["Ice melts and lowers albedo","A warmer Earth emits more infrared energy to space, opposing part of the initial warming","Permafrost thaws and releases methane","Warmer air increases water-vapour greenhouse effects"],1,"The Planck response—greater thermal emission from a warmer body—is a fundamental negative feedback."),
Q(6,30,"Hydrosphere climate regulation","Two cities receive similar sunlight. City A is coastal and City B is far inland. City A has smaller seasonal temperature swings. Which explanation is best?",["Coastal rocks create extra sunlight","Ocean water has no temperature changes","The ocean's high heat capacity stores and releases heat slowly","Inland air contains no greenhouse gases"],2,"Ocean heat storage moderates nearby temperatures."),
Q(7,31,"Climate evidence","A climate graph shows one exceptionally cold year during a 50-year warming trend. What is the best interpretation?",["A single year does not overturn a long-term climate trend","The cold year proves global warming stopped","Climate and weather are identical","Long-term averages are scientifically irrelevant"],0,"Climate trends are evaluated over long periods; short-term variability can occur around a long-term trend."),
Q(8,32,"Sphere interactions","If atmospheric CO₂ rises, which linked sphere response is most directly expected?",["The geosphere immediately stops weathering","The biosphere can no longer photosynthesise at all","Ocean pH must increase","More CO₂ dissolves into the hydrosphere, altering ocean carbonate chemistry"],3,"Atmospheric CO₂ exchanges with ocean water, contributing to acidification."),
Q(9,33,"Climate modelling","A climate model includes atmosphere and land but omits ocean heat transport. What major limitation is most likely?",["It will model ocean currents more accurately","It may poorly represent regional and long-term climate because oceans store and redistribute heat","It will automatically predict sea level exactly","Oceans do not influence climate, so there is no limitation"],1,"Ocean heat storage and circulation are central components of the climate system."),
Q(10,34,"Albedo","Which change would most directly reduce Earth's albedo?",["Increasing bright low cloud cover","Expanding highly reflective ice","Replacing snow-covered ground with dark exposed land","Adding light-coloured roof surfaces"],2,"Darker surfaces absorb more and reflect less incoming solar radiation."),
Q(11,35,"Greenhouse effect","A student says, 'Greenhouse gases trap heat because they form a solid blanket around Earth.' What is the best correction?",["They are gases that absorb and re-emit infrared radiation; no solid layer is involved","They reflect all sunlight before it reaches Earth","They produce heat by nuclear fusion","They only warm Earth by increasing air pressure"],0,"The greenhouse effect arises from molecular interactions with infrared radiation, not a physical blanket."),
Q(12,36,"Sea level","Why can warming oceans contribute to sea-level rise even without ice melt?",["Warm water becomes denser and shrinks","Evaporation permanently removes ocean water","Ocean currents lift the entire ocean mechanically","Water expands as its temperature rises"],3,"Thermal expansion increases seawater volume as it warms."),
Q(13,37,"Biosphere evidence","Which evidence would best support the claim that species are responding to climate change?",["One animal moves on one day","Many species shift their geographic ranges or seasonal timing consistently with changing temperature patterns","Every species remains in exactly the same location","A volcanic rock changes colour"],1,"Repeated, directional range or phenology shifts across species can provide biological evidence of climate responses."),
Q(14,38,"Feedbacks","Bushfires release CO₂, and warming can increase fire weather in some regions. What type of system behaviour can this create?",["A guaranteed negative feedback everywhere","No connection between spheres","A reinforcing feedback under suitable conditions","A process that removes atmospheric carbon"],2,"Fire can release stored carbon, potentially reinforcing warming, though the strength and sign depend on ecosystem recovery and conditions."),
Q(15,39,"Climate impacts","Why is 'the atmosphere holds more moisture' not enough by itself to predict rainfall at a particular place?",["Rainfall also depends on circulation, uplift, condensation and regional weather patterns","Water vapour cannot move horizontally","Humidity never affects precipitation","Rainfall is controlled only by ocean salinity"],0,"Moisture availability matters, but atmospheric dynamics determine where and when precipitation occurs."),
Q(16,40,"Systems thinking","Which statement best captures interactions among Earth's spheres under climate change?",["Each sphere operates independently","Only the atmosphere changes climate","Energy can move between spheres but matter cannot","A change in one sphere can propagate through energy and matter exchanges to several other spheres"],3,"Earth's climate is a coupled system: atmosphere, hydrosphere, biosphere and geosphere exchange energy and matter.")
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
