"use strict";
const skillrRawQuestions = [
["validity vs reliability","A student repeats an experiment 30 times using a miscalibrated sensor. What is the most likely outcome?",["Results may be very consistent but still systematically inaccurate","The calibration error disappears because of the repeats","The investigation becomes valid automatically","The independent variable is removed"],0,"Repeats can improve reliability but do not remove systematic bias.","Consistency is not the same as accuracy."],
["confounding","A study compares plant growth under red and blue light, but blue-light plants also receive more water. What is the main problem?",["Water is a confounding variable that could explain the growth difference","Light colour is no longer an independent variable","Plant growth cannot be measured","The sample is automatically too large"],0,"Because water also affects growth and differs between groups, the effect of light colour cannot be isolated.","Look for another changing cause."],
["equipment suitability","Two thermometers have ranges of −10–110 °C and 0–50 °C. A reaction is expected near 95 °C. Which is the better choice?",["The −10–110 °C thermometer because its range includes the expected temperature","The 0–50 °C thermometer because its scale is shorter","Either, because range does not matter","Neither, because thermometers cannot measure reactions"],0,"Equipment must have an appropriate range as well as suitable resolution and calibration.","Check whether the instrument can measure the expected value."],
["sampling bias","Students estimate insect abundance by sampling only beside a bright lamp. What is the strongest criticism?",["The sampling location may bias the estimate because the lamp can influence insect distribution","The sample is invalid only because it is outdoors","More repeats at the same lamp completely solve the problem","Insect abundance cannot be estimated scientifically"],0,"Biased site selection can make a sample unrepresentative of the wider area.","Representative sampling matters."],
["reproducibility","Another class cannot reproduce an experiment because the original method says only “heat gently.” What information is most needed?",["A defined heating condition such as temperature, duration and equipment setup","The names of the students","The colour of the flame","A longer conclusion"],0,"Ambiguous method descriptions prevent others from recreating the relevant conditions.","Replace vague instructions with measurable details."],
["risk control","A volatile solvent produces harmful vapour. Which control best targets inhalation risk?",["Use it in appropriate local exhaust ventilation such as a fume cupboard and minimise the amount used","Wear thicker shoes only","Repeat the experiment fewer times","Use a larger measuring cylinder"],0,"Engineering controls that remove vapour at the source are more effective than unrelated precautions.","Control the exposure pathway."],
["risk matrix","A hazard has low probability but potentially severe consequences. What should a risk assessment do?",["Consider both likelihood and consequence when deciding controls","Ignore it because the probability is low","Treat it as harmless if it has never happened before","Remove it from the written method"],0,"Risk depends on both likelihood and severity, not likelihood alone.","Rare does not always mean acceptable."],
["biological hazard","Why is reopening an incubated microbial plate generally inappropriate in a school investigation?",["Growth may contain unknown microorganisms and opening the plate can increase exposure risk","The colonies will immediately disappear","The plate becomes chemically corrosive","It makes the agar heavier"],0,"Incubated cultures can contain organisms that should remain contained under approved procedures.","Contain biological material after growth."],
["animal ethics","An investigation can answer its question with 12 animals, but a student proposes using 40 “to be safe.” What is the best evaluation?",["Use should be scientifically justified; unnecessary extra animals conflict with minimising animal use","More animals are always ethically better","Sample size never affects ethics","Animal numbers should be chosen randomly"],0,"Animal numbers should be sufficient for valid science but not unnecessarily high.","Balance scientific validity with reduction."],
["animal welfare","An animal study records the scientific measurements but has no criteria for stopping if an animal becomes distressed. What is missing?",["A welfare monitoring and humane-endpoint plan","A larger independent variable","A second hypothesis","More complicated equipment"],0,"Ethical planning should specify how welfare will be monitored and when intervention or stopping is required.","Plan for distress before it occurs."],
["heritage protocols","A field team has permission from a land manager but not from relevant Traditional Owners to investigate a culturally sensitive site. What is the strongest response?",["Do not proceed until the required cultural authority and protocols are addressed","Proceed because land-manager permission overrides cultural responsibilities","Collect samples first and ask later","Proceed only if no artefacts are visible"],0,"Administrative access does not automatically satisfy cultural authority or heritage responsibilities.","Different permissions can be required."],
["traditional knowledge","A company wants to patent a product derived from knowledge shared by a First Nations community during collaboration. Which issue is central?",["Consent, Indigenous Cultural and Intellectual Property, attribution and agreed benefit-sharing","Whether the product packaging is recyclable","Whether the laboratory uses metric units","Whether the company publishes before competitors"],0,"Commercialisation must respect rights, governance and agreements concerning traditional knowledge.","Scientific usefulness does not erase knowledge ownership."],
["heritage disturbance","During sampling, a student accidentally disturbs material that may be culturally significant. What should happen?",["Stop work, preserve the area as far as possible and follow required reporting and Traditional Owner/heritage procedures","Hide the disturbance to protect the project","Move the material somewhere safer","Continue because the disturbance was accidental"],0,"Accidental disturbance still requires responsible action and appropriate reporting.","Stop and report; do not conceal or relocate."],
["analysis validity","A student excludes three measurements solely because they weaken the expected trend. What is the best criticism?",["Exclusion criteria should be scientifically justified and applied consistently, not chosen to support a preferred result","Any result that disagrees with a hypothesis should be removed","The measurements become valid if averaged first","Data selection does not affect validity"],0,"Selective removal can bias analysis unless there is a defensible, pre-established reason for exclusion.","Do not cherry-pick data."],
["method redesign","A method has good controls but exposes students to an unnecessary high concentration of corrosive acid. What is the best redesign?",["Use a lower concentration that can still answer the question and adjust the method appropriately","Keep the concentration because validity always overrides safety","Add more repeats instead","Remove the risk assessment from the report"],0,"A valid investigation should also minimise risk; safer conditions should be used when they can still answer the question.","Safety can and should shape method design."],
["integrated design","Which plan best represents a strong Year 10 investigation?",["A method aligned to the question, with relevant controls, suitable equipment, adequate sampling/repeats, transparent analysis, and required risk, ethical and cultural checks","A highly detailed method with no controls","A safe method that cannot answer the question","A reproducible method that ignores heritage and animal-welfare responsibilities"],0,"Strong investigations integrate scientific validity, reproducibility and responsibility requirements.","Good design is scientific and responsible at the same time."]
];
window.skillrTestQuestions = skillrRawQuestions.map((q,i)=>({id:`ac9s10i02-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I02",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));