"use strict";
const skillrRawQuestions = [
["genetic ethics","A health insurer proposes a discount for customers who disclose genetic risk results. Which question is most important before adopting the policy?",["Could the policy unfairly discriminate against people based on inherited risk?","Will the test change customers' DNA?","Can genetic risk predict every future illness?","Will all customers receive identical results?"],0,"A policy using genetic information should be evaluated for privacy, consent and potential discrimination.","Consider how sensitive information could affect fair access."],
["genetic testing","A genetic test has high accuracy but only predicts increased risk, not certainty. Which public message is best?",["A positive result means you will develop the disease","The result estimates risk and should be interpreted with clinical context","The test replaces medical advice","The result has no medical value"],1,"Risk tests should be communicated as probabilities and interpreted alongside family history, environment and clinical advice.","Do not turn probability into certainty."],
["genetic decisions","A couple decline embryo screening despite a known inherited-disease risk. Which conclusion is most appropriate?",["Scientific information can inform decisions, but personal values may lead people to different choices","They have disproved the genetic evidence","Screening has no medical value","Society should force one scientifically correct decision"],0,"Science provides evidence about risk, while ethical and personal values can influence how individuals act on that evidence.","Evidence informs decisions; values also matter."],
["history and society","A historical policy cited 'scientific' claims about human groups that were based on weak evidence and social prejudice. What is the strongest lesson for modern science?",["Claims should be tested rigorously and separated from value-laden assumptions used to justify discrimination","All research on human variation should stop","Social context never affects interpretation","Old scientific claims should be accepted because they were once influential"],0,"Rigorous evidence, ethical scrutiny and awareness of assumptions are essential when science affects people and policy.","Ask how evidence and social assumptions became mixed."],
["history and society","Why is consultation with First Nations communities important when discussing historical scientific research that affected them?",["Affected communities hold relevant perspectives, rights and knowledge that should inform ethical interpretation","Consultation makes scientific evidence unnecessary","Only community views determine historical facts","It guarantees agreement about every issue"],0,"Ethical interpretation should include the rights, experiences and knowledge of communities affected by research and policy.","Think ethics, rights and affected stakeholders."],
["funding","A government has $20 million and must choose between two scientifically sound projects: one addresses a rare disease and one a widespread disease. What does the choice illustrate?",["Research priorities involve value judgements and opportunity costs as well as scientific merit","The unfunded project becomes scientifically invalid","The larger patient group always makes the decision ethically simple","Funding determines which hypothesis is true"],0,"Limited resources mean choices can depend on need, equity, expected benefit and other societal values, not only scientific quality.","Both projects can be valid while only one is funded."],
["funding","A company funds a trial of its own new material. What practice best protects scientific credibility?",["Disclose the funding and use transparent methods, independent review and appropriate controls","Hide the funding source so reviewers are not biased","Assume commercial funding invalidates the study","Let the company choose which results are reported"],0,"Conflicts of interest should be disclosed and managed through transparent methods, controls and independent scrutiny.","Manage potential bias rather than assuming it."],
["funding","A research field receives little funding because its benefits are long-term and not commercially profitable. Which outcome is most plausible?",["Important questions may remain understudied despite scientific value","The field must lack valid scientific questions","Commercially profitable fields always have stronger evidence","Scientists can complete the same work without resources"],0,"Funding priorities can leave worthwhile questions under-investigated when expected benefits are diffuse or long-term.","Scientific value and funding attractiveness are not identical."],
["funding","After a major pandemic, governments rapidly expand vaccine and epidemiology funding. Which causal chain best explains this?",["Societal need increases political priority, which redirects funding and research capacity","Scientific laws change after the pandemic","Funding guarantees successful vaccines","Public concern directly determines experimental results"],0,"Urgent societal needs can change policy priorities and redirect resources toward relevant research.","Trace need → priority → resources → research."],
["research design","A city funds air-pollution research only in wealthy suburbs because monitoring stations already exist there. What concern does this raise?",["Existing infrastructure can bias which communities and questions receive research attention","Air pollution is scientifically different in wealthy suburbs","Funding location cannot affect evidence collection","More monitoring automatically removes social inequity"],0,"Infrastructure and capacity can shape what gets studied, potentially leaving some communities under-represented.","Capacity can influence research coverage."],
["research applications","Scientists develop a heat-resistant ceramic for spacecraft; engineers later adapt it for industrial furnaces. What does this example show?",["Research aimed at one problem can generate applications in other contexts","Space research always produces consumer products","Engineering applications make original research unnecessary","Applied use proves the material has no limitations"],0,"Knowledge and materials developed for one purpose can later support different technologies.","Applications can extend beyond the original research goal."],
["research applications","A new battery chemistry improves electric vehicles, but large-scale production requires scarce minerals. What should guide further research priority?",["Performance benefits together with cost, supply, environmental and social trade-offs","Performance alone","Public popularity alone","The assumption that all new technology is beneficial"],0,"Real-world research priorities often require balancing technical performance with environmental, economic and social constraints.","Evaluate multiple consequences, not one metric."],
["materials science","Why might society invest in research on stronger, lighter alloys for transport?",["They may improve safety and efficiency while reducing energy use","All lighter materials are automatically safer","New alloys eliminate engineering testing","Material research has no environmental trade-offs"],0,"Practical needs such as safety, efficiency and lower energy use can motivate materials research.","Connect societal need to desired properties."],
["science and society","Which scenario best demonstrates that society shapes research questions but not scientific conclusions?",["A government funds drought research, but the results still depend on collected evidence","A government chooses the result it wants before funding a study","Public opinion determines which hypothesis is correct","Researchers change measurements to match policy goals"],0,"Society can prioritise a topic, but conclusions must still follow evidence and scientific methods.","Funding can choose the question, not the answer."],
["research priorities","A community strongly values biodiversity, while a company values short-term resource extraction. Why might they support different research priorities?",["Different groups can hold different values and perceive different benefits and risks","One group must be anti-science","Scientific evidence changes depending on who pays","Society always has one shared priority"],0,"Different stakeholders can reasonably prioritise different questions because society is not a single group with one value set.","Different values can shape priorities without changing evidence."],
["evaluation","Which statement provides the best evaluation of how values and needs influence science?",["They help determine which questions receive resources and attention, while scientific methods are still needed to evaluate evidence","They determine which scientific conclusions are true","They make peer review unnecessary","They only affect applied research, never basic research"],0,"Societal factors shape research focus and capacity, but scientific standards remain necessary for judging evidence.","Separate research priority from scientific validity." ]
];
window.skillrTestQuestions = skillrRawQuestions.map((q,i)=>({id:`ac9s10h04-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10H04",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:`${q[4]}\nHint: ${q[5]}`,structuredExplanation:{summary:q[4],hint:q[5]},qualitySchema:"production-v1"}));
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
