"use strict";
const q=(id,question,answers,correct,explanation,hint)=>({id,type:"single",question,answers,correct,explanation,hint});
window.quizQuestions=[
q("ac9s7h01-t01","A research team proposes moving an organism to a new classification group after DNA evidence, body structure and fossil evidence all support the change. What is the best conclusion?",["The change is scientifically reasonable because several evidence types support it","The change should be rejected because classifications must stay fixed","Only the fossil evidence should count, so the other evidence should be ignored","The organism should be removed from all classification systems"],0,"A classification change is stronger when multiple independent lines of evidence support the same relationship.","Look for the answer that weighs the quality and range of evidence."),
q("ac9s7h01-t02","An old astronomy model predicts an eclipse on the wrong date, but a newer model using more precise observations predicts it accurately. What should this lead scientists to do?",["Keep the old model because it came first","Use the evidence to revise or replace the weaker model","Reject all eclipse predictions as unscientific","Assume the eclipse changed to match the newer model"],1,"Scientific models are revised when better evidence and predictions show that a model is more accurate.","A useful model should match observations."),
q("ac9s7h01-t03","A single online video claims a new animal species exists, but no specimen, clear image, DNA sample or repeated observation is available. Why should scientists be cautious?",["New species can never be discovered now","Videos are never evidence in science","The evidence is not yet reliable or independently checked","Classification is based only on popularity online"],2,"Major scientific claims need reliable, checkable evidence before they change accepted knowledge.","Ask whether the evidence can be verified."),
q("ac9s7h01-t04","A community has long observed that a bird arrives after a certain plant flowers. Scientists use this observation to design a migration study. What does this best show?",["Community knowledge should replace all scientific measurement","Only satellite tracking can produce scientific knowledge","Migration studies should ignore seasonal observations","Traditional observations can suggest scientific questions that are tested with evidence"],3,"Different perspectives can contribute useful observations that guide scientific investigation.","The strongest option combines respect for knowledge with testing."),
q("ac9s7h01-t05","Which sentence best explains why scientific knowledge changes?",["Scientific knowledge changes when better evidence or stronger explanations show that older ideas need revision","Scientific knowledge changes whenever students find the old idea difficult","Scientific knowledge changes because scientists are not allowed to repeat old experiments","Scientific knowledge changes randomly with no connection to evidence"],0,"Evidence-based change is central to science; ideas are revised when evidence supports revision.","Look for evidence-driven change."),
q("ac9s7h01-t06","Two scientists disagree about whether a fossil belongs in Group A or Group B. Which evidence would be most useful for resolving the disagreement?",["Which scientist has worked longer","A comparison of fossil features with features that define each group","Which group has the shorter name","The opinion of students who like one group more"],1,"Classification disagreements should be resolved by evidence relevant to relationships and group features.","Choose evidence that directly tests the classification."),
q("ac9s7h01-t07","A new telescope detects moons around a distant planet that older telescopes could not see. What is the best implication?",["Older astronomers were careless","Moons only exist after telescopes detect them","New tools can extend observations and change scientific knowledge","Telescopes make scientific evidence less reliable"],2,"Improved technology can reveal evidence that was previously unavailable.","Think about how instruments affect what scientists can observe."),
q("ac9s7h01-t08","A student writes: 'The newest scientific idea is always correct.' What is the best correction?",["New ideas are always wrong until they become old","Science should only use ideas from famous scientists","The oldest idea is always most reliable","A new idea is accepted only if evidence and reasoning support it"],3,"Scientific ideas are judged by evidence and reasoning, not by age or novelty alone.","New does not automatically mean better."),
q("ac9s7h01-t09","Which example best shows a different perspective contributing to science?",["Local seasonal observations help scientists choose when to survey animal behaviour","A student chooses a favourite planet based on colour","A science poster uses a decorative border","A class picks an answer without evidence"],0,"Local or cultural observations can help shape scientific questions when they are investigated with evidence.","Choose the example that can guide investigation."),
q("ac9s7h01-t10","A classification based on outward appearance is later changed after genetic evidence shows a different relationship. Which statement is most accurate?",["Appearance should never be observed again","Genetic evidence can add information that changes understanding of relationships","The earlier scientists were pretending to do science","All organisms with similar genes must look identical"],1,"Genetic evidence can reveal relationships that are not obvious from appearance alone.","Think about different evidence types."),
q("ac9s7h01-t11","Why is replication important before changing an accepted scientific explanation?",["It makes the explanation harder to understand","It proves that every scientist will agree immediately","It lets scientists check whether results are reliable and not a one-off error","It prevents any scientific explanation from changing"],2,"Replication helps confirm that evidence is reliable enough to support a change in knowledge.","A repeated result is stronger than a one-off result."),
q("ac9s7h01-t12","A new explanation accounts for old observations and also explains a pattern that the old explanation could not. What should scientists do next?",["Ignore the new explanation because it is different","Accept it instantly without testing","Delete all old observations","Test and compare it carefully against the evidence"],3,"A promising explanation should be tested and compared with evidence before being accepted.","A better explanation still needs testing."),
q("ac9s7h01-t13","Which report title best matches AC9S7H01?",["How DNA evidence changed scientists' ideas about the relationships between two species","How to label a microscope diagram","How to calculate average speed in a trolley experiment","How to make a title page for a science folder"],0,"The selected title focuses on evidence changing scientific understanding.","Choose the title about evidence changing knowledge."),
q("ac9s7h01-t14","A science article includes fossil evidence, DNA evidence and Indigenous seasonal observations to explain how understanding of a species has developed. Why is this strong?",["It avoids scientific evidence by using stories only","It combines different evidence and perspectives to build a more complete explanation","It proves that every perspective gives the same answer","It shows that classification is a matter of personal preference"],1,"A stronger account can combine different lines of evidence and perspectives while still using evidence-based reasoning.","Look for the answer that values both evidence and perspective."),
q("ac9s7h01-t15","A student says, 'If science changes, the old evidence was useless.' Which response is best?",["Yes, old evidence should always be thrown away","Yes, scientists should only use evidence from the current year","No, older evidence can still be useful, but new evidence may change how it is interpreted","No, because scientific ideas never really change"],2,"Old evidence can remain useful even when new evidence changes the explanation.","Changing an explanation does not erase all earlier observations."),
q("ac9s7h01-t16","Which action shows the most scientific response to a surprising new result?",["Announce the result as a fact before checking it","Hide it because it does not match the textbook","Vote on whether the result feels believable","Repeat the investigation and compare the result with other evidence"],3,"Unexpected results should be checked and compared with other evidence before changing scientific knowledge.","Scientific caution means testing, not ignoring.")
];
