"use strict";
const Q=[
["validity diagnosis","A student tests whether light intensity affects plant growth, but higher-light plants also receive more water. Which conclusion is strongest?",["The investigation has reduced validity because water amount is confounded with light intensity","The results are automatically reproducible","The hypothesis is proven if high-light plants grow more","Water becomes the dependent variable"],0,"Because water changes systematically with light, any growth difference cannot be attributed confidently to light alone.","A confound changes alongside the IV."],
["reproducibility evidence","Two schools follow the same detailed traffic-count method on similar weekdays. Their rates are 14.8 and 15.3 vehicles/min. What does this most reasonably suggest?",["The method shows reasonable reproducibility despite normal measurement variation","The method is invalid because the values are not identical","One school must have counted incorrectly","The difference proves systematic bias"],0,"Reproducibility concerns obtaining a similar pattern/result under comparable conditions, not exact numerical identity.","Similar, not identical."],
["systematic vs random","A thermometer reads 1.5°C too high, while repeated timing measurements also vary by about ±0.2 s. What errors are present?",["Both systematic and random error","Systematic error only","Random error only","No error because both are small"],0,"The calibration offset is systematic; timing scatter is random.","One shifts values; one creates scatter."],
["mean limitation","A student repeats a mass measurement 20 times using a balance that is always 3 g too high. What will averaging mainly do?",["Reduce random scatter but leave the 3 g systematic bias","Remove the 3 g bias completely","Make the method valid automatically","Increase the systematic error to 60 g"],0,"Repeats can stabilise random variation but cannot correct a consistent calibration offset.","A biased mean is still biased."],
["method comparison","Method A records traffic for 5 min at 8:00 am; Method B records for 30 min at 2:00 pm. Which change is most important before using the data to compare locations?",["Standardise or justify the observation period and time because traffic varies with time of day","Use different vehicle definitions","Remove all buses from one dataset","Round both counts to the nearest 100"],0,"Unequal durations can be converted to rates, but different time-of-day conditions may still confound a location comparison.","Rate fixes duration; context can still differ."],
["percentage variation","Three repeat measurements are 48, 51 and 50 units. Their mean is about 49.7. Which statement is best?",["The small spread gives information about random variation but says nothing by itself about systematic bias","The instrument is definitely accurate","The method is invalid because values differ","The mean proves there is no error"],0,"Closely grouped repeats indicate precision/repeatability, but all values could still be shifted by calibration bias.","Precision ≠ accuracy."],
["operational definition","Researchers compare 'high noise' and 'low noise' workplaces but never define the sound-level ranges. What is the main problem?",["The variable is not operationally defined clearly enough for consistent classification and reproduction","The study has too many participants","Sound cannot be measured quantitatively","The dependent variable must be removed"],0,"Operational definitions specify how categories or variables are measured and assigned.","Define exactly how a label is decided."],
["risk control","A procedure uses a concentrated corrosive acid only to create a mild pH change. Which redesign most effectively reduces risk while preserving the investigation?",["Substitute a suitably dilute solution that still produces the required pH range","Keep the concentrated acid and add a warning sign only","Use no eye protection","Increase the volume so measurement is easier"],0,"Substitution reduces the hazard at source and is generally stronger than relying only on warnings or PPE.","Prefer eliminating/reducing the hazard."],
["residual risk","After goggles, splash trays and a dilute chemical are introduced, some risk remains. What should students do?",["Assess whether the remaining risk is acceptable under the approved procedure and supervision","Assume PPE makes risk zero","Ignore the remaining risk because controls were added","Remove all controls if no accident occurs"],0,"Risk controls reduce rather than necessarily eliminate risk; residual risk still needs evaluation.","Controlled risk is not zero risk."],
["animal ethics design","An investigation could use either 30 live animals or a validated computer simulation that answers the same question. Which choice is ethically preferable, all else equal?",["Use the simulation because a suitable replacement avoids unnecessary animal use","Use the animals because live data are always superior","Use both because more data always justifies harm","Use 60 animals to improve reproducibility"],0,"Where a suitable alternative can answer the question, replacement supports ethical minimisation of animal use.","Use animals only when justified and necessary."],
["human data ethics","Students collect identifiable health data, then decide after collection to share it publicly. What is the main ethical problem?",["Participants did not necessarily consent to that use or level of disclosure","Public sharing always improves validity","Health data are not personal information","Consent is needed only for medical professionals"],0,"Consent should cover how personal data will be collected, used, stored and shared.","Consent must match the intended use."],
["heritage fieldwork","A field site is scientifically ideal but Traditional Owners advise that sampling there is culturally inappropriate. What should the research team do?",["Respect the advice and redesign the sampling plan with appropriate consultation","Sample secretly because scientific value overrides cultural protocols","Take only small samples without telling anyone","Publish the location to justify access"],0,"Scientific investigation must operate within ethical, cultural and legal responsibilities, including appropriate authority on Country/Place.","Scientific value does not cancel cultural responsibility."],
["artefact handling","A student finds a possible artefact during a transect survey. Which action best protects both evidence and heritage value?",["Leave it in place, record only permitted observations, and seek guidance through the relevant authority or protocol","Wash it to reveal markings","Move it to a safer place without permission","Take it home so it is not lost"],0,"Context can be scientifically and culturally important; disturbance may damage evidence and breach responsibilities.","Location/context are part of the evidence."],
["error improvement","A pendulum experiment shows large scatter because a person times one swing with a handheld stopwatch. Which redesign best targets random timing error?",["Time many swings per trial and divide by the number of swings, with repeats","Use the same one-swing timing but round more heavily","Change the string length each trial","Calibrate the ruler only"],0,"Timing a longer interval reduces the relative effect of human start/stop reaction time; repeats then quantify variation.","Make the measured interval larger relative to reaction time."],
["validity tradeoff","A highly precise digital sensor measures the wrong quantity for the hypothesis. Which statement is correct?",["High precision cannot rescue poor validity if the measured variable does not address the question","Precision automatically makes the experiment valid","Digital equipment removes the need for controls","The hypothesis should be changed to match the sensor"],0,"Validity depends on whether the design and measurements test the intended relationship, not merely on instrument precision.","Right question + right measurement first."],
["final synthesis","Which investigation is strongest overall?",["One with a question-linked design, controlled confounders, documented method, suitable repeats, calibrated equipment, proportionate risk controls and appropriate ethical/cultural permissions","One with the largest sample but no method record","One with exact repeat values from an uncalibrated instrument","One that avoids all uncertainty by deleting unusual data"],0,"Strong investigations integrate validity, reproducibility, error control, safety, ethics and context rather than optimising one feature alone.","Quality is multi-dimensional." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s9i02-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S9I02",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));