"use strict";
const Q=[
["accuracy precision","Instrument A gives 10.01, 10.00 and 10.01 g for a 12.00 g reference. Instrument B gives 11.96, 12.02 and 12.01 g. Which statement is strongest?",["A is more precise but less accurate; B is less precise but more accurate overall","A is both more accurate and more precise","B is more precise because its values are closer to 12.00","Accuracy and precision mean the same thing"],0,"A's readings cluster tightly but are far from the reference. B's readings vary more but centre near the reference value.","Precision = closeness to each other; accuracy = closeness to accepted value."],
["systematic error","A balance is not zeroed and reads +0.20 g when empty. Five sample measurements are averaged. What happens to the +0.20 g offset?",["It remains as a systematic bias in the mean","It disappears because averaging removes all errors","It becomes random error","It doubles to +0.40 g"],0,"Averaging can reduce random variation but does not remove a consistent zero offset.","Repeated biased measurements stay biased."],
["instrument choice","A pipette has a stated uncertainty of ±0.02 mL and a measuring cylinder ±1 mL. Which conclusion is justified from this information alone?",["The pipette has smaller stated uncertainty for volume measurement, but this alone does not prove greater accuracy in every use","The pipette is exactly 50 times more accurate","The cylinder is more precise because it is larger","Both instruments must give identical readings"],0,"1/0.02 = 50, so the stated uncertainty is 50 times smaller, but accuracy also depends on calibration and correct use.","Smaller uncertainty ≠ guaranteed accuracy."],
["percentage uncertainty","A pipette delivers 10.00 mL with uncertainty ±0.02 mL. What is the percentage uncertainty?",["0.2%","2%","0.02%","20%"],0,"(0.02/10.00)×100 = 0.2%.","Uncertainty ÷ value × 100."],
["sample size","A student increases a sample from n=5 to n=20 while keeping the method unbiased and consistent. What is the most defensible benefit?",["The estimate is generally less sensitive to unusual individual observations and random sampling variation","The result becomes automatically accurate","Systematic error is eliminated","Every repeated dataset must have the same mean"],0,"Larger samples can improve the stability of estimates, but they do not fix bias or systematic error.","More data mainly helps random variation."],
["small sample","Why is it weak to say 'n=3 is useless' without further context?",["A sample of 3 may still provide preliminary information, but usually gives limited evidence about variability and general patterns","Any sample below 10 is scientifically invalid","Three measurements are always enough for strong conclusions","Sample size has no effect on evidence"],0,"Usefulness depends on purpose and variability; n=3 is often limited, not automatically worthless.","Avoid absolute rules about sample size."],
["standard deviation","Ten repeated readings have SD = 0.02 units. What does this directly indicate?",["The readings are tightly clustered around their mean","The mean is accurate to ±0.02 units","The instrument has no systematic error","The sample size is large enough for every conclusion"],0,"A small standard deviation describes low spread/strong repeatability, not necessarily accuracy.","SD describes spread, not truth."],
["large dataset","A dataset has n=100, mean 25.4 and SD 0.3. Which conclusion is safest?",["The data show relatively small spread around the mean, but reliability also depends on sampling and measurement quality","The dataset is automatically highly reliable because n=100","The mean must equal the true population value","Systematic bias is impossible with 100 readings"],0,"Large n and low spread can be encouraging, but biased sampling or measurement can still undermine conclusions.","Size + precision do not guarantee validity."],
["digital tools","A logger records 500 readings while manual collection could manage 50. What is a genuine advantage?",["It can increase temporal resolution and sample size efficiently, provided the sensor is suitable and calibrated","It guarantees all 500 readings are independent and accurate","It eliminates the need to inspect anomalies","It makes controls unnecessary"],0,"Digital tools can collect frequent consistent measurements efficiently, but measurement quality still matters.","Automation improves capacity, not validity automatically."],
["sampling rate","A sensor records 200 readings each minute for 15 minutes. How many readings are collected?",["3000","215","300","12000"],0,"200×15 = 3000 readings.","Rate × time."],
["sampling design","A temperature changes rapidly during the first 30 s of a reaction. Which sampling plan is most likely to capture the shape of that change?",["Use a short sampling interval during the rapid-change period","Take one reading at the start and one at the end only","Use the widest possible graph scale","Round all readings to whole degrees before recording"],0,"Frequent measurements are needed when the variable changes quickly.","Sampling interval should match how fast the phenomenon changes."],
["data volume","A logger stores 1200 readings per hour for 8 hours. How many readings are stored?",["9600","150","1200","10400"],0,"1200×8 = 9600.","Multiply hourly rate by hours."],
["growth rate","Plant height is 12.3 cm on Day 1 and 13.4 cm on Day 3. What is the average growth per day across the two day-to-day intervals?",["0.55 cm/day","1.10 cm/day","0.37 cm/day","0.45 cm/day"],0,"Growth = 13.4−12.3 = 1.1 cm over 2 intervals, so 1.1/2 = 0.55 cm/day.","Count time intervals, not number of readings."],
["calibration","Two sensors give very similar repeated values, but both are 5 units above a certified reference. What is the main issue?",["High precision with a likely systematic calibration bias","Low precision only","Random error only","Too small a sample size is the only possible cause"],0,"Agreement between repeated readings indicates precision, while a consistent offset from a reference suggests systematic error.","Clustered but shifted = precise, not accurate."],
["measurement range","A sensor has two modes: 0–1000 lx with 1 lx resolution, or 0–100,000 lx with 100 lx resolution. Expected light levels are 350–500 lx. Which mode is preferable?",["0–1000 lx, because it covers the expected range with finer resolution","0–100,000 lx, because the largest range is always best","Either mode gives identical resolution","Neither can measure light"],0,"The narrower mode comfortably covers the expected values and resolves smaller changes.","Choose enough range with useful resolution."],
["final synthesis","Which plan best meets AC9S9I03 when measuring a slowly changing temperature over 2 hours?",["Select a calibrated sensor with suitable range/resolution, choose a justified sampling interval, record enough data, and preserve units/precision","Use the most expensive sensor and assume its data are correct","Collect as many readings as possible without considering relevance","Round every value heavily so the table is shorter"],0,"Good data collection matches equipment, precision, sample size and digital-tool use to the investigation purpose.","Equipment and sampling choices should be justified." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s9i03-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S9I03",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));