"use strict";
function coord(points){const xs=points.map(p=>p[1]).concat(0),ys=points.map(p=>p[2]).concat(0),minX=Math.min(...xs)-1,maxX=Math.max(...xs)+1,minY=Math.min(...ys)-1,maxY=Math.max(...ys)+1,w=420,h=300,m=36,sx=x=>m+(x-minX)/(maxX-minX)*(w-2*m),sy=y=>h-m-(y-minY)/(maxY-minY)*(h-2*m);let g=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Coordinate diagram"><rect width="${w}" height="${h}" rx="14" fill="#fff"/><text x="16" y="22" font-size="13" font-weight="700" fill="#334155">Use scratchpad/notebook: average coordinates or identify rise/run.</text>`;for(let x=Math.ceil(minX);x<=Math.floor(maxX);x++){g+=`<line x1="${sx(x)}" y1="${m}" x2="${sx(x)}" y2="${h-m}" stroke="${x===0?'#64748b':'#dbe4ef'}" stroke-width="${x===0?2:1}"/>`}for(let y=Math.ceil(minY);y<=Math.floor(maxY);y++){g+=`<line x1="${m}" y1="${sy(y)}" x2="${w-m}" y2="${sy(y)}" stroke="${y===0?'#64748b':'#dbe4ef'}" stroke-width="${y===0?2:1}"/>`}if(points.length>=2){const a=points[0],b=points[1];g+=`<line x1="${sx(a[1])}" y1="${sy(a[2])}" x2="${sx(b[1])}" y2="${sy(b[2])}" stroke="#2563eb" stroke-width="3" stroke-linecap="round"/>`}points.forEach(p=>{g+=`<circle cx="${sx(p[1])}" cy="${sy(p[2])}" r="5" fill="#dc2626"/><text x="${sx(p[1])+8}" y="${sy(p[2])-7}" font-size="13" font-weight="700" fill="#111827">${p[0]}(${p[1]},${p[2]})</text>`});return g+`</svg>`}
function ramp(rise,run,label){return `<svg viewBox="0 0 420 220" role="img" aria-label="${label}"><rect width="420" height="220" rx="14" fill="#fff"/><text x="20" y="24" font-size="13" font-weight="700" fill="#334155">Use scratchpad/notebook: gradient = rise ÷ horizontal run.</text><line x1="60" y1="160" x2="360" y2="160" stroke="#94a3b8" stroke-width="2"/><line x1="360" y1="160" x2="360" y2="65" stroke="#f97316" stroke-width="3"/><line x1="60" y1="160" x2="360" y2="65" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/><text x="210" y="184" text-anchor="middle" font-size="14" fill="#475569">${run}</text><text x="370" y="115" font-size="14" fill="#9a3412">${rise}</text><text x="60" y="204" font-size="12" fill="#64748b">${label}</text></svg>`}
const raw=[
[25,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(2, 6) to B(10, 14). Use the scratchpad or notebook to find the midpoint.",["(6, 10)","(8, 12)","(12, 20)","(4, 8)"],0,"Midpoint = ((2+10)/2, (6+14)/2) = (6, 10).","Average the x-values and average the y-values.",[["A",2,6],["B",10,14]]],
[26,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(−3, 4) to B(5, −2). Use the scratchpad or notebook to find the midpoint.",["(1, 1)","(2, 2)","(−1, 2)","(0, 1)"],0,"Midpoint = ((−3+5)/2, (4+−2)/2) = (1, 1).","Average each coordinate pair.",[["A",-3,4],["B",5,-2]]],
[27,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(0, 0) to B(8, 0). Use the scratchpad or notebook to find the midpoint.",["(4, 0)","(0, 4)","(8, 4)","(4, 4)"],0,"Midpoint = ((0+8)/2, (0+0)/2) = (4, 0).","A horizontal segment keeps the same y-value.",[["A",0,0],["B",8,0]]],
[28,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(−6, −2) to B(2, 10). Use the scratchpad or notebook to find the midpoint.",["(−2, 4)","(−4, 8)","(2, 8)","(−2, 8)"],0,"Midpoint = ((−6+2)/2, (−2+10)/2) = (−2, 4).","Average x-values and y-values separately.",[["A",-6,-2],["B",2,10]]],
[29,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows a vertical segment from A(3, 7) to B(3, −1). What is the midpoint?",["(3, 3)","(3, 4)","(3, 2)","(3, 0)"],0,"The x-value stays 3 and the y-value average is (7+−1)/2 = 3, so the midpoint is (3, 3).","Vertical midpoint keeps the same x-value.",[["A",3,7],["B",3,-1]]],
[30,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows a horizontal segment from A(−5, 9) to B(5, 9). What is the midpoint?",["(0, 9)","(5, 0)","(−5, 0)","(0, 0)"],0,"The x-value average is 0 and the y-value stays 9, so the midpoint is (0, 9).","Horizontal midpoint keeps the same y-value.",[["A",-5,9],["B",5,9]]],
[31,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(1, 2) to B(7, 8). Use the scratchpad or notebook to find the midpoint.",["(4, 5)","(3, 4)","(5, 6)","(6, 7)"],0,"Midpoint = ((1+7)/2, (2+8)/2) = (4, 5).","Average the coordinates.",[["A",1,2],["B",7,8]]],
[32,"Section D — Midpoint of a line segment","Midpoint from a diagram","The diagram shows segment AB from A(−4, −4) to B(4, 4). Use the scratchpad or notebook to find the midpoint.",["(0, 0)","(4, −4)","(−4, 4)","(2, 2)"],0,"Midpoint = ((−4+4)/2, (−4+4)/2) = (0, 0).","Opposite coordinates average to zero.",[["A",-4,-4],["B",4,4]]],
[33,"Section E — Gradient in context and linear modelling","Gradient in context","The diagram shows a ramp that rises 1.2 m over a horizontal distance of 6 m. What is the gradient?",["0.2","0.5","2","5"],0,"Gradient = rise/run = 1.2/6 = 0.2.","Divide vertical rise by horizontal run.","ramp","rise 1.2 m","run 6 m","Ramp"],
[34,"Section E — Gradient in context and linear modelling","Gradient in context","The diagram shows an escalator rising 9 m over 15 m horizontally. What is the gradient?",["0.6","1.6","0.9","0.4"],0,"Gradient = 9/15 = 0.6.","Simplify rise/run.","ramp","rise 9 m","run 15 m","Escalator"],
[35,"Section E — Gradient in context and linear modelling","Gradient in context","A water-level graph increases by 3 cm every hour. What is the gradient of the graph?",["3","1/3","−3","0"],0,"The gradient is the rate of change: 3 cm per hour.","On a graph, gradient can represent a rate."],
[36,"Section E — Gradient in context and linear modelling","Gradient in context","A distance–time graph shows a car travels 120 km in 2 h. What is the gradient in km/h?",["60","120","2","1/60"],0,"Gradient = distance/time = 120/2 = 60 km/h.","For distance–time graphs, gradient is speed."],
[37,"Section E — Gradient in context and linear modelling","Gradient in context","The diagram shows a cyclist climbing 50 m vertically over 400 m horizontally. What is the gradient?",["0.125","0.5","8","4"],0,"Gradient = 50/400 = 0.125.","Keep units consistent.","ramp","rise 50 m","run 400 m","Cyclist climb"],
[38,"Section E — Gradient in context and linear modelling","Gradient in context","A line on a graph has gradient 0.75. What does this mean?",["y increases 0.75 for every 1 increase in x","y decreases 0.75 for every 1 increase in x","y increases 1 for every 0.75 increase in x","y stays constant"],0,"A gradient of 0.75 means rise/run = 0.75/1.","Positive gradient means y increases as x increases."],
[39,"Section E — Gradient in context and linear modelling","Gradient in context","The diagram shows a conveyor belt rising 2 m for every 10 m horizontally. What is the gradient?",["0.2","2","5","0.5"],0,"Gradient = 2/10 = 0.2.","Use rise divided by horizontal distance.","ramp","rise 2 m","run 10 m","Conveyor belt"],
[40,"Section E — Gradient in context and linear modelling","Gradient in context","A robot path diagram shows the robot moves 4 m right and 3 m up. What is the gradient of its path?",["0.75","1.33","4","3"],0,"Gradient = rise/run = 3/4 = 0.75.","Right movement is run; upward movement is rise.","ramp","up 3 m","right 4 m","Robot path"]
];
window.skillrTestQuestions=raw.map((q,i)=>({id:`ac9m9a03-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9M9A03",bank:"test",section:q[1],sourceNumber:q[0],skill:q[2],printable:true,type:"single",question:q[3],audioPrompt:q[3],visual:"",visualHtml:Array.isArray(q[8])?coord(q[8]):q[8]==="ramp"?ramp(q[9],q[10],q[11]):"",visualMeta:{type:q[8]?"coordinate-or-context-diagram":"none",alt_text:q[8]?"Diagram supporting the coordinate geometry question.":""},answers:q[4],correct:q[5],explanation:`${q[6]}\nHint: ${q[7]}`,structuredExplanation:{summary:q[6],hint:q[7]},qualitySchema:"production-v1"}));
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
