"use strict";
const Q=[
["shape comparison","Dataset A is 40,42,45,48,50,52,200. Dataset B is 40,42,45,48,50,52,55. Which statement is best?",["A is much more positively skewed because of the high outlier","B is more positively skewed","Both have identical shape","A is negatively skewed"],0,"The value 200 creates a long right tail in A; B is much more balanced.","Compare the tails."],
["centre and outlier","A class has scores 62,65,68,70,72,74,96. Which pair best describes the effect of 96?",["It raises the mean more than the median","It raises the median more than the mean","It lowers both equally","It has no effect on centre"],0,"An extreme high value pulls the mean upward, while the median depends mainly on position.","Mean is more sensitive to extremes."],
["same median","Two distributions have the same median and IQR, but one has a much larger range caused by one extreme value. What does this show?",["The distributions are similar in central 50% spread but differ in extremes","They are identical distributions","The larger range proves the median is wrong","IQR and range always rank spread identically"],0,"IQR ignores extremes while range depends entirely on the minimum and maximum.","Different spread measures capture different features."],
["quartile comparison","Girls' heights have Q1=150.5 and Q3=164. Boys' heights have Q1=156.5 and Q3=173.5. Which group has the larger IQR?",["Boys: 17 cm versus girls: 13.5 cm","Girls: 17 cm versus boys: 13.5 cm","Both 13.5 cm","Both 17 cm"],0,"Girls IQR=164−150.5=13.5; boys IQR=173.5−156.5=17.","IQR = Q3−Q1."],
["centre spread synthesis","Using the supplied height data, which comparison is strongest?",["Boys have a higher median and greater spread by both range and IQR","Girls have a higher median and greater spread","Boys have a higher median but smaller spread","The groups have the same centre and spread"],0,"Boys median 167>157, range 31>23 and IQR 17>13.5.","Compare centre and more than one spread measure."],
["histogram limitation","A grouped histogram shows counts in age intervals but not individual ages. Which statistic may be impossible to determine exactly from the graph alone?",["The exact median age","The modal interval","Which interval has the highest frequency","Whether frequencies generally rise"],0,"Grouping loses within-bin detail, so an exact individual median may not be recoverable.","Grouped data hide exact values."],
["rate vs count","Health data are reported as cases per 100,000. Why is this better than raw case counts for comparing age groups of different population sizes?",["Rates standardise for population size","Rates remove all sampling error","Rates make every distribution symmetric","Raw counts cannot be graphed"],0,"A per-100,000 rate allows fairer comparison when group population sizes differ.","Standardise by exposure/population size."],
["trend comparison","Lung-cancer rates are 5,12,25,40,55,70; diabetes rates 15,25,40,60,80,85. Which statement is best?",["Both rise with age, but the size of the increases differs across intervals","Both increase at exactly the same rate","Only diabetes shows an age relationship","Only lung cancer shows an age relationship"],0,"Each series increases, but their interval-to-interval changes are not identical.","Compare the whole pattern, not just endpoints."],
["linearity caution","Why is it risky to say one six-point age-group series is 'more linear' by inspection alone?",["Linearity should be judged against a defined model or deviations from a fitted line, not vague visual impression","Any increasing sequence is perfectly linear","Grouped age data cannot be graphed","Linear patterns require equal frequencies"],0,"A claim about linearity needs a criterion or model rather than an unsupported visual label.","Define what 'linear' means."],
["median rate","For lung rates 5,12,25,40,55,70, what is the median of the six listed rates?",["32.5","40","25","35"],0,"With six values, median=(25+40)/2=32.5.","Average the 3rd and 4th values."],
["median comparison","Diabetes rates are 15,25,40,60,80,85. Compared with lung-cancer rates 5,12,25,40,55,70, which has the higher median listed rate?",["Diabetes: 50 versus lung cancer: 32.5","Lung cancer: 50 versus diabetes: 32.5","Both 40","Both 50"],0,"Diabetes median=(40+60)/2=50; lung median=(25+40)/2=32.5.","Compute both middle-pair averages."],
["percentage points vs relative","An indicator rises from 46% to 70%. Which statements are correct?",["The increase is 24 percentage points and about 52.2% relative to 46%","The increase is 24% only","The increase is 52.2 percentage points","Percentage-point and relative increases are identical"],0,"Difference=24 points; relative increase=24/46≈52.2%.","Absolute percentage difference and relative percent change differ."],
["gap comparison","Indicators have gaps of 26,27,15,22,23 and24 percentage points. What is the median gap?",["23.5 percentage points","23 percentage points","24 percentage points","22.5 percentage points"],0,"Ordered gaps:15,22,23,24,26,27; median=(23+24)/2=23.5.","Order first, then average middle two."],
["context limits","Two groups differ by 27 percentage points on an outcome. What additional information is needed before inferring why the gap exists?",["Relevant explanatory variables and context; the descriptive gap alone does not establish causes","Nothing; the gap itself proves a cause","Only the group labels","Only the larger percentage"],0,"Comparative descriptive data reveal a difference, not its causal explanation.","Difference ≠ cause."],
["representation choice","To compare the full distributions of two numerical datasets while preserving individual values for modest sample sizes, which representation is particularly useful?",["Back-to-back stem-and-leaf plot","Single pie chart","One percentage only","Unscaled pictograph"],0,"A back-to-back stem-and-leaf plot preserves values while enabling comparison of shape, centre and spread.","Use a comparative distribution display."],
["overall judgement","Which statement best matches AC9M9ST03 reasoning?",["Compare multiple datasets using centre, spread, shape and outliers rather than relying on one statistic","The group with the higher mean is always better","Range alone fully describes a distribution","Any outlier should be removed before comparison"],0,"Sound comparison synthesises several distribution features and treats outliers as information to investigate.","Use the whole distribution." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9m9st03-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9M9ST03",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));