#!/usr/bin/env python3
"""Build authored Year 1 Science Pass 1 question banks."""

from __future__ import annotations

from year1_bank_builder import write_banks


def bank(code: str, description: str, quick_read: list[tuple[str, str]], items: list[tuple[str, str, str, str]]) -> dict[str, object]:
    return {
        "code": code,
        "subject": "Science",
        "description": description,
        "quick_read": quick_read,
        "items": items,
    }


SPECS = {
    "AC9S1U01": bank(
        "AC9S1U01",
        "identify the basic needs of plants and animals, including air, water, food or shelter, and describe how the places they live meet those needs",
        [
            ("Concept answer", "Living things survive only when their basic needs are met. Animals need air, water, food and a suitable shelter; plants need air, water, light and a suitable place to grow."),
            ("Key vocabulary", "A habitat is the place where a living thing lives. A need is something required for survival, not just something preferred."),
            ("Observable example", "A pond gives a frog water, insects for food, air at the surface and plants or mud for shelter."),
            ("Visual model", "Use labelled habitat scenes and movable need cards with tap, keyboard and paper matching alternatives."),
            ("Common misconception", "A habitat is not merely a home shape; it includes the resources and conditions the living thing needs."),
        ],
        [
            ("Name an animal need", "State one basic need shared by a dog, a bird and a person.", "Any one of air, water or food (1 mark).", "Identifying a basic need shared by animals."),
            ("Match needs and habitat features", "Match water, food and shelter to pond water, insects and reeds in a frog habitat.", "Water ↔ pond water; food ↔ insects; shelter ↔ reeds (1 mark each).", "Connecting habitat features with animal needs."),
            ("Build a plant-care set", "From picture cards showing water, sunlight, a sealed dark box and space, select what a healthy classroom plant needs.", "Selects water, light and suitable space; rejects the sealed dark box (3 marks).", "Recognising basic plant needs."),
            ("Explain a bird nest", "A nest protects chicks, but it does not provide every need. Name two other things adult birds must find.", "Any two of food, water and air; food and water expected as resources outside the nest (2 marks).", "Distinguishing shelter from other animal needs."),
            ("Order a pet-care check", "Order: refill clean water; notice the water bowl is empty; check the animal can reach it; tell the responsible adult.", "Notice empty bowl → tell responsible adult → refill as directed → check access (2 marks).", "Sequencing responsible care for a basic need."),
            ("Draw a useful habitat", "Draw a habitat for a small fish and label water, food and a safe place to shelter.", "Labels all three relevant habitat features and keeps the fish in suitable water (3 marks).", "Representing how a habitat meets needs."),
            ("Compare two plant places", "One seedling is beside a bright window and watered; another is sealed in a dark cupboard without water. Predict which is more likely to survive and explain.", "Window seedling; it has light, water and air, while the cupboard seedling lacks key needs (3 marks).", "Using needs to compare plant environments."),
            ("Design a habitat checklist", "Create a four-part checklist for deciding whether a place can meet a rabbit's basic needs.", "Checks air, water, suitable food and safe shelter/space, with one relevant habitat feature for each (4 marks).", "Applying animal needs to habitat evaluation."),
            ("Identify need or want", "A cat has water, food and shelter but no blue toy. Is the blue toy a basic survival need? Explain.", "No; it may support play/enrichment, but colour-specific toy is not required for survival (2 marks).", "Distinguishing needs from preferences."),
            ("Match living things to resources", "Match a tree, bee and lizard to sunlight and water; nectar and air; insects and a warm shelter.", "Tree ↔ sunlight/water; bee ↔ nectar/air; lizard ↔ insects/warm shelter (1 mark each).", "Relating varied living things to suitable resources."),
            ("Sequence habitat use", "Order a possum's evening actions: leave tree hollow; eat leaves or fruit; return to shelter; breathe air throughout.", "A sensible sequence begins at shelter, includes feeding, and returns to shelter; air is needed throughout (2 marks).", "Describing how an animal uses habitat resources."),
            ("Find the missing resource", "A garden enclosure has shade, air and water for guinea pigs but no food. State the missing need and one suitable action.", "Food; provide suitable guinea-pig food under responsible adult care (2 marks).", "Diagnosing an unmet animal need."),
            ("Demonstrate a habitat sort", "Sort cards for water, light, seeds, insects, nest and soil into plant needs, animal needs or useful habitat features. Explain two placements.", "Sort recognises plant light/water and animal food/water/air; explanations connect resources to survival (4 marks).", "Classifying needs and habitat features."),
            ("Draw a needs comparison", "Draw or diagram one need both a tomato plant and a chicken share, and one need that is met differently.", "Shared need such as water/air; difference such as plant light versus chicken food/shelter, accurately labelled (3 marks).", "Comparing plant and animal needs."),
            ("Correct a single-need claim", "A student says, ‘A pond gives a duck water, so it meets every need.’ Explain why that conclusion is incomplete.", "The duck also needs air, food and safe shelter/space; one resource alone does not prove all needs are met (3 marks).", "Evaluating a habitat claim using multiple needs."),
            ("Evaluate two habitats", "Compare a bare dry cage and a planted enclosure with clean water, suitable food, air and shelter for a small animal. Choose the more suitable habitat and support the choice with four needs.", "Chooses planted enclosure and links air, water, food and shelter/space to visible features; notes any feature still needing adult checking (5 marks).", "Using evidence to evaluate habitat suitability."),
        ],
    ),
    "AC9S1U02": bank(
        "AC9S1U02",
        "describe daily and seasonal changes in the environment and explore how these changes affect everyday life",
        [
            ("Concept answer", "Light, temperature, weather and living things can change through a day and across seasons. These patterns affect clothing, activities and care for plants or animals."),
            ("Key vocabulary", "Daily means within or from one day to another. Seasonal means connected with a season over months; weather is the condition at a particular time."),
            ("Observable example", "Morning may be cool and dim, midday brighter and warmer, and evening cooler again, so clothing or activities may change."),
            ("Visual model", "Use labelled day timelines, weather tables and seasonal photo sequences; never rely on colour alone."),
            ("Common misconception", "A season does not make every day identical. A cool day can occur in summer and weather varies by place."),
        ],
        [
            ("Name a daily change", "Give one environmental change that can be observed from morning to night.", "One valid change such as daylight, temperature, shadow position or animal activity (1 mark).", "Identifying an observable daily environmental change."),
            ("Match change and response", "Match rain, strong sunshine and cold air to umbrella, shade/hat and warm layer.", "Rain ↔ umbrella; sunshine ↔ shade/hat; cold ↔ warm layer (1 mark each).", "Relating conditions to everyday choices."),
            ("Build a day timeline", "Arrange sunrise, midday, sunset and night in order and describe the light at two points.", "Correct order and two accurate light observations (3 marks).", "Sequencing daily light changes."),
            ("Weather or season", "A single rainy Tuesday occurs in summer. Does that one day prove the season changed? Explain.", "No; rain is daily weather, while a season is a longer pattern over months (2 marks).", "Distinguishing short-term weather from seasonal patterns."),
            ("Order plant observations", "Order these records through one day: long morning shadow, short midday shadow, long afternoon shadow.", "Morning long → midday short → afternoon long (2 marks).", "Sequencing a daily shadow pattern."),
            ("Draw clothing choices", "Draw suitable clothing for a hot sunny day and a cool wet day. Label the condition each item responds to.", "Shows sensible sun/heat and rain/cool choices with accurate labels (3 marks).", "Representing how conditions affect everyday life."),
            ("Use a weekly pattern", "A week records 5 cool mornings and 2 warm mornings. What can be said about that week without claiming every morning was cool?", "Cool mornings were more frequent in the recorded week; two mornings were warm, so not all were cool (2 marks).", "Describing a pattern without overgeneralising."),
            ("Explain an activity change", "Choose an outdoor activity and explain how heat, rain or daylight could change its time, clothing or location.", "Connects one environmental condition to a sensible change in at least two aspects (3 marks).", "Applying environmental changes to everyday planning."),
            ("Compare day and night", "State one difference in light and one possible difference in animal activity between day and night.", "Day has sunlight and night is dark; gives a plausible activity contrast while allowing different animals have different patterns (2 marks).", "Comparing daily environmental conditions."),
            ("Match seasonal evidence", "Match flowering, leaf fall and repeated colder days to possible seasonal observations, noting that patterns vary by plant and place.", "Matches each observation plausibly and acknowledges local variation (3 marks).", "Interpreting seasonal indicators cautiously."),
            ("Sequence a weather response", "Order: check the forecast/sky; notice rain is likely; choose rain protection; review conditions before leaving.", "Check conditions → notice rain likely → choose protection → review before leaving (2 marks).", "Using observations or predictions in daily planning."),
            ("Read a temperature pattern", "Morning is 12°C, midday 21°C and evening 15°C. When is it warmest, and how does evening compare with morning?", "Midday warmest; evening is 3°C warmer than morning (2 marks).", "Interpreting a simple daily temperature record."),
            ("Demonstrate shadow change", "Use a torch and object model to show how changing light direction changes a shadow. State what stayed the same.", "Changes light direction and observes shadow direction/length change while object remains the same (3 marks).", "Modelling a daily light-and-shadow relationship."),
            ("Draw a seasonal care plan", "Draw two panels showing how care for a garden might differ during a hot dry period and a cool wet period.", "Shows evidence-based changes such as watering/shade versus reduced watering/drainage, with condition labels (3 marks).", "Representing seasonal effects on daily care."),
            ("Correct a climate overclaim", "A child says, ‘Winter is always snowy everywhere.’ Explain why this is inaccurate.", "Winter conditions depend on location; many places have cool or wet winters without snow, and daily weather varies (3 marks).", "Recognising geographic and daily variation within seasons."),
            ("Analyse a month record", "A four-week record shows daylight becoming slightly longer and afternoon temperatures usually rising, with several cool days. Describe the pattern and two possible everyday effects without claiming certainty.", "States the overall longer/warmer tendency, notes cool exceptions, and gives two plausible effects such as later outdoor time or lighter clothing (5 marks).", "Using repeated observations to discuss seasonal change and daily life."),
        ],
    ),
    "AC9S1U03": bank(
        "AC9S1U03",
        "describe pushes and pulls in terms of strength and direction and predict the effect of these forces on objects’ motion and shape",
        [
            ("Concept answer", "A push moves an object away from the source and a pull draws it closer. Force strength and direction can start, stop, speed up, slow, turn or change shape."),
            ("Key vocabulary", "Force means a push or pull. Strength describes how strong the force is; direction describes where it acts."),
            ("Observable example", "A gentle push moves a toy car a short distance; under the same conditions, a stronger push usually changes its speed or distance more."),
            ("Visual model", "Use arrows for direction and different arrow lengths or labels for strength, plus safe toy and playdough demonstrations."),
            ("Common misconception", "Moving objects do not always need a continuing push, and a stronger force does not guarantee the same result on different objects or surfaces."),
        ],
        [
            ("Name the force", "A child draws a wagon toward their body. Is this a push or a pull?", "Pull (1 mark).", "Identifying a pull from movement relative to the source."),
            ("Match force effects", "Match push a ball, pull a drawer and squeeze playdough to move away, move closer/open and change shape.", "Ball push ↔ away; drawer pull ↔ closer/open; squeeze ↔ shape change (1 mark each).", "Connecting pushes and pulls with effects."),
            ("Compare safe pushes", "Using the same toy car and surface, give one gentle and one stronger push. Describe the observed motion without overclaiming.", "Records a relevant difference in speed/distance and notes the car/surface were kept the same (3 marks).", "Observing effects of force strength."),
            ("Predict a direction", "A stationary ball is pushed to the left. Predict its first direction of movement and give the reason.", "Left; the applied push acts left (2 marks).", "Predicting motion from force direction."),
            ("Order a stopping action", "Order: ball rolls; hand applies a safe opposite push; ball slows; ball stops.", "Ball rolls → opposite push → slows → stops (2 marks).", "Sequencing an effect of an opposing force."),
            ("Draw force arrows", "Draw a box with one arrow showing a strong push right and one showing a gentle pull left. Label both.", "Correct opposite directions and clear strong/gentle labels or arrow convention (3 marks).", "Representing force direction and strength."),
            ("Explain a shape change", "Why can pressing soft clay change its shape while the same safe press may not visibly change a wooden block?", "Materials respond differently; soft clay deforms more easily while wood is more rigid under that force (3 marks).", "Relating a force effect to material properties."),
            ("Plan a fair push test", "Plan how to compare a gentle and strong push on one toy car fairly. State what changes, what stays the same and what is observed.", "Changes push strength; keeps car, start and surface the same; observes distance/speed using a consistent method (4 marks).", "Designing a fair investigation of force strength."),
            ("Identify two force features", "A labelled arrow points down and is marked strong. State the force's direction and strength.", "Downward and strong (2 marks).", "Reading a force representation."),
            ("Match actions and force types", "Match close a cupboard door, open a zipped bag and stretch a spring gently to push, pull and pull.", "Door close ↔ push; zip open ↔ pull; stretch spring ↔ opposing pulls/pull (1 mark each).", "Classifying familiar force actions."),
            ("Sequence a direction change", "Order: rolling ball approaches; side push is applied; path bends; ball moves in a new direction.", "Approaches → side push → path bends → new direction (2 marks).", "Sequencing a force-caused direction change."),
            ("Compare surfaces carefully", "The same car travels farther on tile than carpet after similar pushes. What observation is supported and what should be kept the same for a fair comparison?", "Supported: farther on tile in this test; same car, start and push method/strength should be controlled (3 marks).", "Describing a motion result and fair-test controls."),
            ("Demonstrate push and pull", "Use a safe object to show one push and one pull in different directions. Describe each effect.", "Shows and labels both force types, directions and observed motion (3 marks).", "Demonstrating forces and their effects."),
            ("Draw before and after", "Draw a sponge before and after a squeeze. Add arrows to show where the forces act.", "Shows a plausible compressed shape and inward force arrows (3 marks).", "Representing force-caused deformation."),
            ("Correct a strength conclusion", "Two different balls receive pushes, and the lighter ball goes farther. A student says the push on it must have been stronger. Explain why the conclusion is not certain.", "Balls may differ in mass, material or rolling; push strength was not isolated, so a fair same-object comparison is needed (3 marks).", "Evaluating evidence about force strength."),
            ("Predict a combined effect", "A toy car rolls east. A safe push acts west, then a second push acts north. Predict possible changes after each push and explain why actual results should be observed.", "West push may slow/stop/reverse; north push may turn the path; size/timing of forces and motion affect the result, so test evidence is needed (5 marks).", "Reasoning about sequential force direction effects."),
        ],
    ),
    "AC9S1H01": bank(
        "AC9S1H01",
        "describe how people use science in their daily lives, including using patterns to make scientific predictions",
        [
            ("Concept answer", "People observe, measure, test and use patterns to make practical decisions about health, food, weather, materials, plants and machines."),
            ("Key vocabulary", "A pattern is something that repeats or changes in a regular way. A scientific prediction states what may happen and is supported by observations or experience."),
            ("Observable example", "If wet clothes dried faster on several warm breezy days, a person may predict similar conditions will help another load dry."),
            ("Visual model", "Use daily-life photo sequences, simple records and prediction/evidence cards with text alternatives."),
            ("Common misconception", "A prediction is not a promise or guess without a reason; new evidence can show it was wrong."),
        ],
        [
            ("Find science in daily life", "Give one way a cook uses observation or measurement.", "Example such as measuring ingredients, timing heating or observing colour/texture change (1 mark).", "Identifying science practices in cooking."),
            ("Match jobs and science use", "Match gardener, nurse and builder to observing plant needs, measuring temperature and testing material strength.", "Gardener ↔ plant needs; nurse ↔ temperature; builder ↔ material strength (1 mark each).", "Connecting daily work with science practices."),
            ("Use a weather pattern", "A three-day record shows dark clouds followed by rain each day. Make a cautious prediction for a fourth dark-cloud day.", "Rain may follow, with the repeated observation as reason; does not claim certainty (2 marks).", "Making a pattern-based prediction."),
            ("Observation or prediction", "Classify: ‘The soup is steaming now’ and ‘It may cool if left on the table.’", "Steaming now is an observation; may cool is a prediction (2 marks).", "Distinguishing present evidence from a prediction."),
            ("Order a practical science process", "Order: notice slippery floor; place warning/avoid area; identify water as possible cause; dry safely with adult procedure.", "Notice → identify possible cause → warn/avoid → follow safe drying procedure (2 marks).", "Sequencing science-informed safety action."),
            ("Draw pattern evidence", "Draw a four-day record in which a plant bends toward the window each day. Add one supported prediction.", "Shows repeated bending toward light and predicts continued bending/growth toward the window cautiously (3 marks).", "Representing evidence for a daily-life prediction."),
            ("Explain a material choice", "Why might a raincoat maker choose a water-resistant material rather than absorbent paper?", "Water-resistant material limits water passing through; paper absorbs/weakens, based on material evidence (2 marks).", "Using science knowledge in product choice."),
            ("Compare evidence and guessing", "One child predicts a puddle will dry because yesterday's puddle dried in sun. Another predicts it because 7 is lucky. Which is scientific and why?", "First prediction; it uses relevant past observation, while lucky number is not evidence about drying (3 marks).", "Evaluating reasons for predictions."),
            ("Identify a household use", "Describe how a fridge uses science knowledge to help keep food safe.", "Keeps food cooler, slowing spoilage; response connects temperature with storage (2 marks).", "Describing science used in food storage."),
            ("Match patterns and decisions", "Match repeated hot afternoons, soil drying quickly and a torch battery fading to carry water, check plant moisture and replace/recharge battery.", "Each pattern matches the sensible decision (1 mark each).", "Using observed patterns for practical decisions."),
            ("Sequence a prediction check", "Order: record what happened; notice a pattern; make a prediction; observe the next event.", "Notice pattern → make prediction → observe next event → record result (2 marks).", "Following a prediction-and-check cycle."),
            ("Use a cooking observation", "Bread is browning quickly before the timer ends. State one safe science-informed action an adult could take and the evidence used.", "Adult lowers heat/checks/removes as appropriate; evidence is rapid browning, not timer alone (2 marks).", "Using observation to adjust a daily process safely."),
            ("Demonstrate tool choice", "Choose a timer, thermometer or ruler for checking baking duration, body temperature and shelf length. Explain each choice.", "Timer ↔ duration; thermometer ↔ temperature; ruler ↔ length, with correct reasons (3 marks).", "Selecting measurement tools for daily questions."),
            ("Draw a decision record", "Draw a simple table showing three days of pet-water checks and one action based on a repeated low-water pattern.", "Records three observations and a responsible action such as more frequent checks/refills with adult oversight (3 marks).", "Communicating pattern-based care decisions."),
            ("Correct a certainty claim", "A forecast was correct twice, so a child says it can never be wrong. Explain why science predictions can change.", "Predictions use available patterns/evidence but conditions vary; new observations improve or revise them (3 marks).", "Understanding uncertainty in scientific predictions."),
            ("Analyse a daily-life problem", "Wet towels stayed damp indoors for two days but dried outside on a warm breezy day. Propose a prediction, identify evidence, and name one factor to test fairly next time.", "Predicts warm/breezy outdoor conditions may speed drying; cites records; tests one factor such as airflow while keeping towel size/wetness/location consistent (5 marks).", "Applying patterns and fair comparison to a practical problem."),
        ],
    ),
    "AC9S1I01": bank(
        "AC9S1I01",
        "pose questions to explore observed simple patterns and relationships and make predictions based on experiences",
        [
            ("Concept answer", "A useful science question can be explored by observing or testing. A prediction answers the question before the test and gives an evidence-based reason."),
            ("Key vocabulary", "A relationship is a way two things may be connected. A prediction is an expected result; evidence is an observation that supports a reason."),
            ("Observable example", "Question: Does a toy car travel farther on tile or carpet? Prediction: tile, because I observed less slowing there before."),
            ("Visual model", "Use question/prediction/evidence cards and picture comparisons with speech-to-text, tap and paper alternatives."),
            ("Common misconception", "‘I like tile’ is a preference, not evidence that predicts motion."),
        ],
        [
            ("Choose an explorable question", "Turn ‘The plant is taller’ into a question that could be explored with observations.", "Example: Does this plant grow taller each week? or Does more light affect its growth? (1 mark).", "Posing a question from an observation."),
            ("Match questions and predictions", "Match ‘Which ramp is faster?’, ‘Which towel absorbs more?’ and ‘Where does ice melt sooner?’ to relevant predicted outcomes.", "Each question is matched to an outcome addressing ramp, absorbency or melting place (1 mark each).", "Connecting predictions directly to questions."),
            ("Make a rolling prediction", "Before rolling the same ball on tile and carpet, state a prediction and one relevant experience-based reason.", "Predicts one surface and cites relevant prior rolling/friction observation (2 marks).", "Forming an evidence-based prediction."),
            ("Question or statement", "Is ‘Do larger shadows form when the torch is closer?’ a question that can be explored? Explain.", "Yes; torch distance and shadow size can be changed/observed safely (2 marks).", "Recognising a testable relationship question."),
            ("Order inquiry thinking", "Order: notice repeated wilting; ask whether watering time matters; predict based on experience; plan observations.", "Notice pattern → pose question → predict with reason → plan observations (2 marks).", "Sequencing question and prediction development."),
            ("Draw question evidence", "Draw two paper planes with different wing shapes and add a question comparing their flight distance.", "Shows two wing forms and a clear comparative question about distance under same conditions (3 marks).", "Representing a relationship question visually."),
            ("Improve a vague question", "Change ‘What happens?’ into a clear question about how ramp height may affect toy-car distance.", "Example: Does the same car travel farther from a higher or lower ramp? (2 marks).", "Refining a question to name variables and observation."),
            ("Compare two prediction reasons", "Prediction A uses results from three earlier trials. Prediction B uses a favourite colour. Explain which is better supported and why.", "A; repeated relevant observations are evidence, while colour preference is unrelated (3 marks).", "Evaluating evidence used for predictions."),
            ("Pose a sound question", "Two containers make different sounds when tapped safely. Write a question about one feature that might affect the sound.", "Valid example compares material, fill level or size while observing sound (2 marks).", "Posing a question about an observed relationship."),
            ("Match observations to questions", "Match fast melting near a window, taller shaded seedlings and longer throws with questions about warmth, light and force strength.", "Each observation matches its relevant relationship question (1 mark each).", "Linking patterns with explorable questions."),
            ("Sequence prediction parts", "Order: expected outcome; question; evidence-based reason; words such as ‘I predict’.", "Question → ‘I predict’/expected outcome → evidence-based reason (2 marks; wording order may combine final two).", "Structuring a prediction that answers a question."),
            ("Predict from a simple pattern", "A shadow was shortest near midday on three clear days. Predict its likely size near midday on another clear day and state the evidence.", "Likely short; cites the three repeated clear-day observations without claiming certainty (2 marks).", "Using a repeated pattern to predict."),
            ("Demonstrate question sorting", "Sort cards into explorable questions, preferences and statements. Explain one card in each group.", "Sort is defensible and explanations distinguish observable tests from likes and factual statements (3 marks).", "Classifying inquiry language."),
            ("Draw a before-test prediction", "Draw the expected result of dropping equal water drops on paper and plastic, and label the reason for your prediction.", "Shows a plausible absorb/spread contrast and gives a relevant material-experience reason (3 marks).", "Communicating a prediction visually."),
            ("Correct an after-test prediction", "A student watches the result and then writes, ‘I predict the result I just saw.’ Explain what must happen instead.", "Prediction must be recorded before observing the result; after the test, write an observation and comparison (3 marks).", "Distinguishing predictions from post-test observations."),
            ("Develop an inquiry pair", "From the pattern ‘larger pushes often moved the same car farther’, write a fair question and cautious prediction with a relevant reason.", "Question compares push strength for the same car/surface; prediction expects stronger push may move farther; reason cites observed pattern (5 marks).", "Creating a connected question, prediction and evidence chain."),
        ],
    ),
    "AC9S1I02": bank(
        "AC9S1I02",
        "suggest and follow safe procedures to investigate questions and test predictions",
        [
            ("Concept answer", "A safe procedure lists actions in order, controls hazards and says when adult help or protective equipment is needed."),
            ("Key vocabulary", "A hazard is something that can cause harm. A procedure is an ordered set of steps; a fair test changes one planned factor."),
            ("Observable example", "For a ramp test, clear the floor, use a light toy, release rather than throw, keep hands away from the path and measure after it stops."),
            ("Visual model", "Use hazard/safe-action cards, step strips and teacher-approved equipment diagrams with text labels."),
            ("Common misconception", "Being careful is not a complete procedure; safe instructions must name what to do and avoid."),
        ],
        [
            ("Identify a safe action", "Before testing toy cars on a ramp, state one action that keeps the path safe.", "Clear the path, keep people out of it or use a stable ramp under supervision (1 mark).", "Identifying a relevant safety control."),
            ("Match hazards and controls", "Match spilled water, unknown substance and moving toy to wipe/mark area with adult help, do not touch/taste, and keep clear of path.", "Each hazard matches its specific control (1 mark each).", "Connecting hazards with preventive actions."),
            ("Follow a safe water test", "Demonstrate transferring small amounts of clean water between stable plastic cups on a tray.", "Uses small amount, stable cups and tray, carries carefully and responds to spills safely (3 marks).", "Following a teacher-approved procedure."),
            ("Explain no tasting", "Why must an unknown liquid never be tasted during an investigation?", "Appearance does not prove identity or safety; only approved observation under adult direction is allowed (2 marks).", "Explaining a fundamental investigation safety rule."),
            ("Order ramp-test steps", "Order: record distance; clear path; release car from mark; wait until car stops.", "Clear path → release from mark → wait for stop → record distance (2 marks).", "Sequencing a safe investigation procedure."),
            ("Draw a safe setup", "Draw a safe seed investigation with labelled cups, small water amount, stable tray and adult-approved location.", "Includes all named controls and no unsafe access or spills (3 marks).", "Representing a safe investigation setup."),
            ("Improve an unsafe plan", "A plan says, ‘Run while carrying a glass jar of hot water.’ Replace it with a safe Year 1 investigation approach.", "Do not use/carry hot water or run; use teacher-approved safe-temperature water, stable plastic container and adult handling as required (3 marks).", "Revising unsafe equipment and behaviour."),
            ("Plan a fair safe test", "Plan how to compare two paper towels using equal water drops. Include two safety steps and two fair-test controls.", "Safety includes tray/wipe spills/no tasting; fairness includes equal towel size and water amount/application (4 marks).", "Combining safety and fairness in a procedure."),
            ("Choose protective behaviour", "During a soil observation, what should a student do before and after handling teacher-approved samples?", "Follow teacher instructions, avoid face/mouth contact and wash hands afterwards (2 marks).", "Applying hygiene controls."),
            ("Match procedure purposes", "Match wear eye protection if directed, label cups and repeat the same release to protect eyes, avoid mix-ups and improve consistency.", "Each action matches the stated safety/data purpose (1 mark each).", "Understanding why procedure steps matter."),
            ("Sequence a spill response", "Order: move away; tell teacher; notice spill; follow teacher cleanup instruction.", "Notice spill → move/keep others away → tell teacher → follow cleanup instruction (2 marks).", "Responding safely to an incident."),
            ("Select suitable equipment", "For measuring toy-car distance, choose between a paper strip/ruler and standing in front of the moving car. Explain.", "Choose paper strip/ruler from beside/after motion; standing in path is unsafe and unnecessary (2 marks).", "Selecting safe measurement methods."),
            ("Demonstrate equipment check", "Inspect a simple ramp setup before use and point out stability, clear path and start mark.", "Correctly checks all three features and reports/fixes issues before release (3 marks).", "Conducting a pre-investigation safety check."),
            ("Draw safe and unsafe panels", "Draw one unsafe and one corrected safe way to use scissors for cutting test strips, following class rules.", "Unsafe risk is clear; safe panel shows seated controlled cutting, correct grip/carrying and adult/class procedure (3 marks).", "Contrasting risky and controlled procedures."),
            ("Audit an incomplete procedure", "A procedure says only ‘Test both balls.’ Name three missing details needed for safety and reliable comparison.", "Examples: safe area, same release/start/surface, observation method, equipment check or adult instruction; any three explained (3 marks).", "Evaluating completeness of procedures."),
            ("Write a complete mini-procedure", "Write ordered steps to test whether ice melts faster in shade or indirect sunlight without touching unknown liquids or leaving a spill hazard.", "Uses equal ice/containers, stable tray, teacher-approved locations, observation timing, safe cleanup and one changed location factor (5 marks).", "Designing a safe, fair and ordered investigation."),
        ],
    ),
    "AC9S1I03": bank(
        "AC9S1I03",
        "make and record observations, including informal measurements, using digital tools as appropriate",
        [
            ("Concept answer", "An observation records what is noticed or measured. Good records use specific words, units, labels, dates or images so another person can understand them."),
            ("Key vocabulary", "An observation is evidence gathered with senses or tools. An inference is an idea that might explain evidence; an informal measurement uses units such as cubes or hand spans."),
            ("Observable example", "‘The shoot is 5 cubes tall on Tuesday’ is stronger evidence than ‘The plant looks good’."),
            ("Visual model", "Use labelled observation tables, photo sequences and identical informal units; offer drawing and written alternatives."),
            ("Common misconception", "A guess about cause is not the same as an observation of what happened."),
        ],
        [
            ("Observation or idea", "Classify ‘The leaf has three brown spots’ as an observation or an explanation.", "Observation; it describes visible evidence without giving a cause (1 mark).", "Distinguishing observation from inference."),
            ("Match records and tools", "Match plant height, sound and colour change to cube measure, audio recording and labelled photo/drawing.", "Height ↔ cubes; sound ↔ audio; colour change ↔ photo/drawing (1 mark each).", "Selecting appropriate observation records."),
            ("Measure informally", "Use equal cubes to measure the height of a model plant and record number, unit and date.", "Accurate end-to-end cube count with ‘cubes’ and date/time label (3 marks).", "Making and recording an informal measurement."),
            ("Improve a vague record", "Rewrite ‘The rock is nice’ as a specific observation using at least two visible or touch-safe properties.", "Example: The teacher-approved rock is grey, rough and has a curved edge (2 marks).", "Using precise observable language."),
            ("Order photo recording", "Order: photograph from marked place; label date; place object at mark; compare images.", "Place object → photograph consistently → label date → compare images (2 marks).", "Sequencing consistent digital observation."),
            ("Draw a change record", "Draw a seed before sprouting and after sprouting. Label two observed differences.", "Two time points and two valid visible changes such as root/shoot/size (3 marks).", "Recording change through labelled drawings."),
            ("Separate evidence and cause", "A puddle is smaller at 2 pm. State the observation, then one possible explanation using ‘might’.", "Observation: puddle smaller; inference: water might have evaporated/drained, clearly marked as possible (2 marks).", "Separating observation from tentative explanation."),
            ("Plan repeatable records", "Describe how to record a classroom plant once a day so four records can be compared fairly.", "Same time/view/measurement unit, dated table or photos, and specific features measured/observed (4 marks).", "Planning consistent longitudinal observations."),
            ("Read an informal measure", "A worm model spans 7 identical paperclips placed end-to-end. Record the result correctly.", "7 paperclips long (1 mark).", "Reporting an informal measurement with units."),
            ("Match detail to usefulness", "Match ‘warm’, ‘18 cubes long’ and ‘three loud taps’ to qualitative temperature, informal length and counted sound observation.", "Each record matches the relevant observation kind (1 mark each).", "Recognising different forms of observation data."),
            ("Sequence table entries", "Order the entries for one observation: object name; date/time; measured or seen result; unit/label.", "A sensible record includes all four, with result and unit together (2 marks).", "Structuring a complete observation record."),
            ("Compare two digital images", "Image 1 shows 2 open flowers; Image 2 a week later shows 5. State the recorded change without claiming a cause.", "Open flowers increased from 2 to 5, a change of 3 (2 marks).", "Extracting evidence from dated digital records."),
            ("Demonstrate sound recording", "Tap a teacher-approved object three times and record the sound with words or audio, including number of taps.", "Record identifies object, three taps and a sound quality such as high/low or loud/soft (3 marks).", "Making a repeatable sound observation."),
            ("Draw a labelled table", "Create a three-row table for date, weather description and puddle width in equal blocks.", "Clear headings, three dated rows and values with block units (3 marks).", "Designing a table for mixed observations."),
            ("Audit changing units", "A plant is measured with large blocks on Monday and small blocks on Friday. Explain why the numbers cannot be compared directly.", "Different unit sizes change the count; remeasure/use identical units and consistent endpoints (3 marks).", "Evaluating consistency of informal measurements."),
            ("Create a complete evidence record", "For a toy car trial, record start mark, surface, informal distance, movement description and one photo label. Explain which parts are observations.", "All five details recorded; identifies distance/motion/photo as evidence and avoids unsupported cause claims (5 marks).", "Integrating measurement, description and digital evidence."),
        ],
    ),
    "AC9S1I04": bank(
        "AC9S1I04",
        "sort and order data and information and represent patterns, including with provided tables and visual or physical models",
        [
            ("Concept answer", "Sorting groups data by a clear rule; ordering arranges it along a scale or sequence. Tables and models make patterns easier to see."),
            ("Key vocabulary", "A category is a named group. A pattern is a repeated or regular feature; a model represents something so it can be examined."),
            ("Observable example", "Leaf lengths 3, 5, 4 and 5 cubes can be ordered 3, 4, 5, 5, revealing that 5 occurs most often."),
            ("Visual model", "Use labelled sorting hoops, movable rows, provided tables and physical block models with text and paper alternatives."),
            ("Common misconception", "A pattern must come from the data; arranging objects to look pretty does not prove a scientific pattern."),
        ],
        [
            ("Name a sorting rule", "Red, blue and green counters are grouped by colour. State the sorting rule.", "Colour (1 mark).", "Identifying the rule used to categorise data."),
            ("Match representations", "Match table, ordered line and physical model to rows/columns, least-to-greatest sequence and objects showing data.", "Each representation matches its defining format (1 mark each).", "Recognising common data representations."),
            ("Sort material samples", "Sort teacher-approved cards into flexible and rigid using the recorded bend observations.", "Uses evidence to place every card once and explains the rule (3 marks).", "Sorting observations by a material property."),
            ("Order measurements", "Order plant heights 6, 3, 8 and 5 cubes from shortest to tallest.", "3, 5, 6, 8 cubes (1 mark).", "Ordering informal measurement data."),
            ("Sequence a table process", "Order: enter each observation; read headings; check every item appears once; look for a pattern.", "Read headings → enter observations → check completeness → look for pattern (2 marks).", "Sequencing data organisation and analysis."),
            ("Draw a physical model", "Draw towers representing 2, 4 and 6 rainy-day observations for three months. Label each tower.", "Accurate tower heights and three clear labels (3 marks).", "Representing frequency data with a physical-style model."),
            ("Describe a growing pattern", "A model has towers 2, 4, 6 and 8 blocks high. Describe the pattern without inventing a cause.", "Tower height increases by 2 blocks each step; no unsupported cause stated (2 marks).", "Identifying a numerical pattern in a model."),
            ("Choose a useful organisation", "For ten animal observations, choose sorting by body covering or ordering by observed length. Explain which answers a question about similarity.", "Sorting by body covering best shows similarity categories; reasoning connects organisation to the question (3 marks).", "Selecting data organisation for a purpose."),
            ("Read a provided table", "A table records paper absorbs 5 drops, cloth 9 and plastic 0. Order materials from least to most absorbed.", "Plastic 0, paper 5, cloth 9 (2 marks).", "Ordering data from a table."),
            ("Match categories and entries", "Match floats, sinks and unsure to cork/button, coin/stone and untested object.", "Cork/button ↔ floats; coin/stone ↔ sinks; untested ↔ unsure, based on supplied observations (1 mark each).", "Placing information into evidence-based categories."),
            ("Sequence life-stage cards", "Order seed, sprout, flowering plant and seed-producing plant.", "Seed → sprout → flowering plant → seed-producing plant (2 marks).", "Ordering information in a biological sequence."),
            ("Complete a pattern table", "Trial numbers 1,2,3,4 have distances 2,4,6,__ blocks. Complete the shown pattern and state it.", "8 blocks; increases by 2 each trial (2 marks).", "Extending a simple data pattern."),
            ("Demonstrate a two-way sort", "Sort cards first into living/non-living, then sort living cards into plant/animal. Explain both rules.", "All cards placed appropriately and both hierarchical rules stated (3 marks).", "Using nested categories in a physical model."),
            ("Draw a labelled table", "Create a table for object, observed surface and roll/slide result for ball, block and tube.", "Clear headings and plausible supplied/observed entries for all three objects (3 marks).", "Representing linked observations in a table."),
            ("Correct an unsupported pattern", "A child sees two red objects float and says all red objects float. Explain why colour is not yet supported as the cause.", "Only two cases and other properties differ; test more objects while comparing relevant material/shape evidence (3 marks).", "Evaluating a claimed relationship from limited data."),
            ("Analyse two representations", "A table and block model both show daily bird counts 3,5,5,7. Describe the pattern, identify the repeated value and explain one advantage of each representation.", "Overall increase with 5 repeated; table gives exact values, model makes comparisons/pattern visible (5 marks).", "Comparing representations and interpreting patterns."),
        ],
    ),
    "AC9S1I05": bank(
        "AC9S1I05",
        "compare observations with predictions and others’ observations, consider if investigations are fair and identify further questions with guidance",
        [
            ("Concept answer", "After a test, compare the result with the prediction and other records. A fair investigation changes one planned factor and keeps relevant conditions the same."),
            ("Key vocabulary", "Fair means the comparison is not confused by extra changes. A repeat is another trial; a further question follows from what the evidence reveals."),
            ("Observable example", "If two towels differ in size and material, absorbency cannot be linked to material alone; equal-sized pieces make a fairer comparison."),
            ("Visual model", "Use prediction/result cards, same/different checklists and side-by-side observation tables."),
            ("Common misconception", "A prediction that does not match is not a failed investigation; honest unexpected results are useful evidence."),
        ],
        [
            ("Compare result and prediction", "Prediction: the red car will travel farther. Result: the blue car travels farther. Did they match?", "No; the observed result was the opposite of the prediction (1 mark).", "Comparing a prediction with an observation."),
            ("Match fairness controls", "Match car, surface and start line to use same car, same surface and same start when testing push strength.", "Each factor matches its keep-the-same control (1 mark each).", "Identifying controlled conditions in a fair test."),
            ("Repeat an observation", "Perform or inspect three same-condition ramp trials and record whether the distances are similar or varied.", "Records all three trials and gives an accurate comparison rather than selecting only one (3 marks).", "Using repeat observations to assess consistency."),
            ("Find the unfair change", "One ice cube is large in shade and one is small in sun. Why can the test not show the effect of location alone?", "Both size and location changed, so size may also affect melting (2 marks).", "Recognising multiple changed factors."),
            ("Order post-test thinking", "Order: record result; compare with prediction; compare classmates' observations; ask a new question.", "Record → compare with prediction → compare others → pose further question (2 marks).", "Sequencing evaluation after investigation."),
            ("Draw a fair comparison", "Draw two identical toy cars at the same start line on two labelled surfaces. Mark the one factor being compared.", "Cars/start are same and only surface differs, clearly labelled (3 marks).", "Representing a fair surface investigation."),
            ("Explain different observations", "Two groups record 9 blocks and 11 blocks for similar trials. Give one sensible reason to check without saying either group lied.", "Check release, start, unit placement, surface or recording; difference may come from procedure/measurement variation (2 marks).", "Considering reasons for variation between observers."),
            ("Suggest a further question", "A plant near the window grew taller than one farther away. Write a next question that investigates light more fairly.", "Example: With same plant type, water and pot, does distance from the same window affect growth? (3 marks).", "Developing a guided follow-up question."),
            ("State an honest conclusion", "The prediction said paper would absorb most, but cloth absorbed more in all three trials. Write the conclusion.", "Cloth absorbed more than paper in these trials; prediction was not supported (2 marks).", "Reporting evidence that contradicts a prediction."),
            ("Match problems and improvements", "Match different water amounts, one trial and unlabelled samples to equal amounts, repeat trials and add labels.", "Each problem matches its direct improvement (1 mark each).", "Selecting improvements to reliability and fairness."),
            ("Sequence a fair retest", "Order: choose equal pieces; add equal drops; label materials; compare absorption after same time.", "Choose/label equal pieces → add equal drops → wait same time → compare (2 marks).", "Sequencing controls in an absorbency retest."),
            ("Compare class records", "Group A observes 4 sprouts; Group B observes 5; Group C observes 4. State the shared pattern and variation.", "Most records are near 4–5; A/C agree at 4 and B is one higher (2 marks).", "Comparing others' observations quantitatively."),
            ("Demonstrate a fairness check", "Use a checklist to inspect a paper-plane test for same paper, start, throw method and measuring unit.", "Checks all four, identifies any difference and proposes a specific fix (3 marks).", "Applying a fair-test checklist."),
            ("Draw prediction versus result", "Draw two labelled panels: a predicted floating object and an observed sinking result. Add one comparison sentence.", "Panels clearly differ and sentence states prediction was not supported by the observation (3 marks).", "Communicating a prediction-result comparison."),
            ("Audit a one-trial claim", "One seed sprouted first, so a child says its pot type always makes seeds sprout faster. Explain why the claim is too strong.", "One trial may vary; other factors must be controlled, more seeds/trials are needed, and conclusion should be limited to this observation (3 marks).", "Evaluating evidence strength and overgeneralisation."),
            ("Evaluate and extend an investigation", "Two cars of different mass are pushed by different people on different floors. Explain why the comparison is unfair, redesign it and write one useful further question.", "Identifies multiple confounds; keeps car/push/start/surface same while changing one factor; proposes a connected testable question (5 marks).", "Redesigning a fair investigation and extending inquiry."),
        ],
    ),
    "AC9S1I06": bank(
        "AC9S1I06",
        "write and create texts to communicate observations, findings and ideas, using everyday and scientific vocabulary",
        [
            ("Concept answer", "A science communication tells what was investigated, what was observed and what the evidence supports. Labels, tables, drawings and precise words help the audience understand."),
            ("Key vocabulary", "A finding is what the evidence shows. Scientific vocabulary names ideas precisely, such as habitat, force, absorb and observation."),
            ("Observable example", "‘The cloth absorbed 8 drops, 3 more than paper’ is clearer than ‘Cloth was best’ because it includes evidence."),
            ("Visual model", "Use title-result-conclusion organisers, labelled diagrams and caption cards with oral, typed and paper options."),
            ("Common misconception", "A colourful poster is not automatically accurate; every claim must match the observations."),
        ],
        [
            ("Choose a precise word", "Which scientific word means a push or pull?", "Force (1 mark).", "Using topic-specific science vocabulary."),
            ("Match text parts", "Match title, labelled diagram and finding to names topic, shows parts and states what evidence revealed.", "Title ↔ topic; diagram ↔ parts; finding ↔ evidence result (1 mark each).", "Recognising features of a science communication."),
            ("Tell an observation", "Using a shown leaf, say or write one precise observation and label it observation.", "States a visible measurable feature without unsupported cause and labels it (2 marks).", "Communicating an observation precisely."),
            ("Improve a finding", "Rewrite ‘The car went good’ using the evidence that it travelled 12 blocks on tile.", "Example: The car travelled 12 blocks on the tile in this trial (2 marks).", "Replacing vague language with measured evidence."),
            ("Order a mini-report", "Order: method; title/question; finding; observations/results.", "Title/question → method → observations/results → finding (2 marks).", "Sequencing a simple science report."),
            ("Draw and label a force", "Draw a person pushing a box. Add a direction arrow and labels ‘push’ and ‘force’.", "Accurate scene, direction arrow and both scientific labels (3 marks).", "Using a labelled diagram to communicate a force."),
            ("Separate observation and idea", "Write one observation about a melting ice cube and one idea that might explain it. Label each.", "Observation describes visible melting/size/time; idea is tentative and uses evidence-related reasoning (2 marks).", "Structuring evidence and interpretation separately."),
            ("Select a format for data", "For plant heights over four weeks, choose a table, labelled drawing or oral story as the main record. Justify your choice.", "Table is well justified for exact repeated values, or another format is justified with an accurate comparison method (3 marks).", "Choosing a communication form suited to evidence."),
            ("Write a supported sentence", "Data show paper 4 drops, cloth 9 and plastic 0. Write one finding using a number and comparison word.", "Example: Cloth absorbed 9 drops, 5 more than paper and 9 more than plastic (2 marks).", "Writing a quantitative evidence-based finding."),
            ("Match everyday and scientific words", "Match home/place to live, soaks up and careful looking to habitat, absorbs and observation.", "Home/place ↔ habitat; soaks up ↔ absorbs; careful looking ↔ observation (1 mark each).", "Connecting familiar language with scientific vocabulary."),
            ("Sequence presentation parts", "Order: explain finding; introduce question; show labelled evidence; invite a question.", "Introduce question → show evidence → explain finding → invite question (2 marks).", "Organising a short oral science presentation."),
            ("Caption a digital image", "Write a caption for a dated photo showing a seedling with two leaves and a height of 6 cubes.", "Includes date/time context, two leaves and 6-cube height without unsupported cause (2 marks).", "Creating an informative digital-image caption."),
            ("Demonstrate vocabulary use", "Give a 20-second explanation using the words prediction, observation and result correctly.", "Defines or uses prediction before test, observation as evidence and result as what happened (3 marks).", "Using linked inquiry vocabulary orally."),
            ("Draw a result display", "Create a labelled three-column picture or block display for roll distances 3, 5 and 4 blocks.", "Accurate labelled values, common scale/unit and readable arrangement (3 marks).", "Representing findings visually."),
            ("Correct an exaggerated conclusion", "A poster says, ‘Tile always makes every car fastest’ after one car travelled farther on tile once. Rewrite the conclusion.", "Limits claim to the tested car/trial and measured outcome; avoids ‘always/every’ (3 marks).", "Aligning conclusion strength with evidence."),
            ("Create a complete science message", "Using results—sun: ice melted in 12 minutes; shade: 20 minutes—write a title/question, brief method, results, finding and one next question.", "All five parts present; same-size/same-container fairness noted; finding says ice melted sooner in sun in this test; next question is relevant (6 marks).", "Communicating a complete investigation accurately."),
        ],
    ),
}


def main() -> None:
    written = write_banks(SPECS)
    print(f"Wrote {len(written)} Year 1 Science banks")


if __name__ == "__main__":
    main()
