#!/usr/bin/env python3
"""Build Year 1 English Literacy handwriting and code Pass 1 banks (LY08–LY15)."""

from __future__ import annotations

from year1_bank_builder import write_banks


def bank(code: str, description: str, quick_read: list[tuple[str, str]], items: list[tuple[str, str, str, str]]) -> dict[str, object]:
    return {
        "code": code,
        "subject": "English",
        "description": description,
        "quick_read": quick_read,
        "items": items,
    }


SPECS = {
    "AC9E1LY08": bank(
        "AC9E1LY08",
        "write words using unjoined lower-case and upper-case letters",
        [
            ("Rule", "Unjoined letters are formed separately, in the correct direction, with consistent size and spacing so each word is easy to read."),
            ("Worked example", "In ‘Mia’, capital M begins the name, lower-case i and a sit on the line, and a small space follows before the next word."),
            ("Formation check", "Use a comfortable functional grip, steady paper, correct starting points, clear capitals and lower-case letters, and spaces between words."),
            ("Visual interaction", "Show animated stroke direction with pause/replay, keyboard-labelled alternatives and printable tracing/start-dot models."),
            ("Common trap", "A capital is not just an oversized lower-case letter; many capital and lower-case forms differ."),
        ],
        [
            ("Choose the capital", "Which letter should begin the name maya when written correctly?", "Upper-case M (1 mark).", "Using an upper-case letter for a familiar proper name."),
            ("Match upper and lower case", "Match A, G and T to a, g and t.", "A ↔ a; G ↔ g; T ↔ t (1 mark each).", "Connecting upper-case and lower-case letter forms."),
            ("Write a clear word", "Write the word map using separate lower-case letters on the line.", "Letters m-a-p are unjoined, correctly ordered, recognisable and placed consistently (3 marks).", "Forming a short lower-case word."),
            ("Add word spacing", "Rewrite thereddog as three readable words.", "the red dog, with clear spaces and recognisable letters (2 marks).", "Using spacing to separate handwritten words."),
            ("Order letter formation checks", "Order: check spacing; choose correct case; form each letter separately; reread the word.", "Choose case → form separate letters → check spacing → reread (2 marks).", "Sequencing a handwriting self-check."),
            ("Copy with case", "Copy ‘Ben has a kite’ using a capital at the start/name, lower-case letters elsewhere and spaces.", "Accurate case, unjoined legible forms and three word spaces (4 marks).", "Copying a sentence with case and spacing."),
            ("Find a case error", "A student writes aPPle in the middle of a sentence. Explain and correct the case.", "apple; ordinary word uses lower-case letters unless at sentence start, not internal capitals (2 marks).", "Editing inconsistent letter case."),
            ("Compare readability", "Explain why equal spacing inside letters, clear word spaces and consistent size help a reader.", "They distinguish letters/words, prevent crowding or splitting and make recognition easier (3 marks).", "Reasoning about legibility features."),
            ("Write an upper-case word", "Write ACT in separate upper-case letters.", "A-C-T, all recognisable and unjoined with consistent size (2 marks).", "Forming a short upper-case abbreviation."),
            ("Match case uses", "Match capital letter, lower-case letter and word space to name/sentence start, most other letters and boundary between words.", "All three matched correctly (1 mark each).", "Connecting handwriting features with functions."),
            ("Sequence a short sentence", "Order and handwrite: swims / Ava / fast.", "Ava swims fast. with capital A, separate legible letters, spaces and end mark (3 marks).", "Combining ordering with readable handwriting."),
            ("Repair crowded writing", "The words blue boat touch each other. State and show the one change needed.", "Adds a visible word space: blue boat (2 marks).", "Correcting missing inter-word spacing."),
            ("Demonstrate grip and posture", "Show a comfortable functional pencil grasp and paper position, then write sun without joining the letters.", "Grip allows controlled movement without strain; paper is stable; s-u-n forms are legible and separate (3 marks).", "Applying functional handwriting setup."),
            ("Write paired forms", "Write the pairs Bb, Dd, Rr and circle the upper-case form in each.", "All six forms recognisable and correct upper-case letters circled (4 marks).", "Comparing distinct upper/lower-case forms."),
            ("Edit a handwritten label", "A map label reads canBerra. Rewrite it correctly and explain two changes.", "Canberra; capital C and lower-case b, with legible unjoined formation (3 marks).", "Editing case within a proper noun."),
            ("Produce a legible mini-text", "Handwrite two short sentences about a pet or imagined animal. Use at least one proper name and then self-check case, formation, size, spacing and line placement.", "Two complete legible sentences; correct name capital; five handwriting checks applied and one improvement identified (7 marks).", "Sustaining readable unjoined handwriting across sentences."),
        ],
    ),
    "AC9E1LY09": bank(
        "AC9E1LY09",
        "segment words into separate phonemes (sounds) including consonant blends or clusters at the beginnings and ends of words (phonological awareness)",
        [
            ("Rule", "Segmenting means stretching a spoken word and saying every phoneme in order. In a consonant blend, each sound remains separate."),
            ("Worked example", "stop has four phonemes: /s/ /t/ /o/ /p/. The letters s and t form a blend because both sounds are heard."),
            ("Sound strategy", "Say the word normally, stretch it slowly, move one counter for each sound, then blend the sounds back to check."),
            ("Visual interaction", "Use sound boxes and counters with audio, tap, keyboard and paper-token alternatives; assess sounds, not letter names."),
            ("Common trap", "Count phonemes, not letters: ship has three sounds /sh/ /i/ /p/ because sh represents one sound."),
        ],
        [
            ("Segment a CVC word", "Say every phoneme in map.", "/m/ /a/ /p/ — 3 phonemes (1 mark).", "Segmenting a three-phoneme word."),
            ("Match words and sound counts", "Match sun, stop and fish to 3, 4 and 3 phonemes.", "Sun ↔ 3; stop ↔ 4; fish ↔ 3 (1 mark each).", "Counting phonemes in words with a blend or digraph."),
            ("Move sound counters", "Say frog slowly and move one counter for each phoneme.", "/f/ /r/ /o/ /g/ with 4 counters in order (2 marks).", "Segmenting an initial consonant blend."),
            ("Hear a final cluster", "Segment tent and state the final two sounds.", "/t/ /e/ /n/ /t/; final sounds /n/ /t/ (2 marks).", "Segmenting a final consonant cluster."),
            ("Order spoken sounds", "Order the sounds /l/ /k/ /m/ /i/ to make milk.", "/m/ /i/ /l/ /k/ (1 mark).", "Sequencing phonemes in a word with final blend."),
            ("Draw sound boxes", "Draw one box per sound in clap and place a dot in each.", "Four boxes/dots for /k/ /l/ /a/ /p/ (2 marks).", "Representing an initial blend with phoneme boxes."),
            ("Explain letters versus sounds", "Why does wish have three phonemes even though it has four letters?", "sh works together to represent one /sh/ sound: /w/ /i/ /sh/ (2 marks).", "Distinguishing grapheme count from phoneme count."),
            ("Compare two blends", "Segment slip and list. Identify the blend at the beginning of one and the end of the other.", "Slip /s/ /l/ /i/ /p/ starts /s//l/; list /l/ /i/ /s/ /t/ ends /s//t/ (4 marks).", "Comparing initial and final consonant clusters."),
            ("Segment a digraph word", "Say every phoneme in chop.", "/ch/ /o/ /p/ — 3 phonemes (1 mark).", "Segmenting a word containing a consonant digraph."),
            ("Match clusters and words", "Match /b/ /l/, /s/ /t/ and /n/ /d/ to blue, star and hand.", "/b//l/ ↔ blue; /s//t/ ↔ star; /n//d/ ↔ hand (1 mark each).", "Recognising consonant clusters in spoken words."),
            ("Sequence brush sounds", "Order /sh/ /r/ /b/ /u/ to segment brush.", "/b/ /r/ /u/ /sh/ (2 marks).", "Sequencing a blend and digraph in one word."),
            ("Count sounds in spoon", "Segment spoon and count the phonemes.", "/s/ /p/ /oo/ /n/ — 4 phonemes (2 marks).", "Segmenting an initial cluster with a vowel digraph sound."),
            ("Demonstrate continuous segmenting", "Say best, stretching each sound without inserting extra ‘uh’ sounds.", "/b/ /e/ /s/ /t/ cleanly, 4 phonemes (3 marks including no added vowels).", "Producing accurate phoneme segments in a final cluster."),
            ("Draw two sound maps", "Draw sound boxes for flag and ship, then compare the number of letters and sounds.", "Flag: 4 sounds/4 letters; ship: 3 sounds/4 letters; boxes accurately represent /f l a g/ and /sh i p/ (4 marks).", "Comparing blend and digraph sound structures."),
            ("Correct an inserted sound", "A student segments frog as /f/ /uh/ /r/ /o/ /g/. Explain the error.", "The blend has adjacent /f/ and /r/ sounds; no vowel phoneme occurs between them (3 marks).", "Detecting schwa insertion in consonant blends."),
            ("Segment a mixed set", "Segment sprint, milk and chest. Give each sound in order, count phonemes and identify one initial or final cluster/digraph in each.", "Sprint /s p r i n t/ 6; milk /m i l k/ 4; chest /ch e s t/ 4; features correctly identified (8 marks).", "Applying phoneme segmentation to varied clusters and digraphs."),
        ],
    ),
    "AC9E1LY10": bank(
        "AC9E1LY10",
        "orally manipulate phonemes in spoken words by addition, deletion and substitution of initial, medial and final phonemes to generate new words (phonological awareness)",
        [
            ("Rule", "Phoneme manipulation changes one spoken sound: add a sound, delete a sound or substitute one sound while keeping the others in order."),
            ("Worked example", "Change the middle /i/ in pin to /e/: /p/ /e/ /n/ makes pen. Only the medial phoneme changes."),
            ("Sound strategy", "Say the word, map one token per sound, change the named token, then blend the new sounds and check the word."),
            ("Visual interaction", "Use oral audio and sound tokens without requiring spelling, with tap, keyboard and paper-counter alternatives."),
            ("Common trap", "Change only the named phoneme; replacing or reordering extra sounds creates a different task."),
        ],
        [
            ("Add an initial sound", "Add /k/ to the beginning of at. What word is made?", "Cat (1 mark).", "Adding an initial phoneme."),
            ("Match changes and words", "Match delete /s/ from stop, change /m/ in map to /t/, and add /s/ before pin to top, tap and spin.", "Stop minus /s/ ↔ top; map /m/→/t/ ↔ tap; /s/+pin ↔ spin (1 mark each).", "Connecting addition, deletion and substitution outcomes."),
            ("Move a middle-sound token", "Use tokens for cat. Replace /a/ with /o/ and say the new word.", "Cot; /k/ /o/ /t/ (2 marks).", "Substituting a medial vowel phoneme."),
            ("Change a final sound", "Replace the final /p/ in map with /t/. What word is made?", "Mat (1 mark).", "Substituting a final phoneme."),
            ("Order a deletion", "Order: say stop; identify /s/; remove first sound; blend /t/ /o/ /p/.", "Say stop → identify/remove /s/ → blend /t o p/ → top (2 marks).", "Sequencing initial-phoneme deletion."),
            ("Draw sound-change boxes", "Draw three sound boxes for pin, cross out /i/, add /a/ and label the new spoken word.", "Shows /p/ /i/ /n/ changing only middle to /a/; pan (3 marks).", "Representing medial substitution."),
            ("Identify changed position", "Sun changes to sum. Which sound position changed and what are the two sounds?", "Final position; /n/ changed to /m/ (2 marks).", "Locating a final phoneme substitution."),
            ("Make three new words", "Start with pan. Make one new word by changing the first sound, one by changing the middle sound and one by changing the final sound.", "Three valid examples such as can, pin and pat, with only named position changed each time (4 marks).", "Generating words through substitutions in all positions."),
            ("Delete a final sound", "Say farm without the final /m/. What spoken word remains?", "Far (1 mark).", "Deleting a final phoneme."),
            ("Match medial substitutions", "Match pin with /e/, /a/ and /o/ in the middle to pen, pan and pon/nonword. State which two are familiar words.", "/e/ ↔ pen; /a/ ↔ pan; /o/ ↔ pon; pen and pan are familiar words (3 marks).", "Exploring medial phoneme changes including a possible nonword."),
            ("Sequence sound addition", "Order: blend plant; say lant; add /p/ at the beginning; identify new first sound.", "Say lant → add/identify initial /p/ → blend plant (2 marks).", "Sequencing addition to an initial cluster."),
            ("Substitute in a cluster word", "Change the /l/ in slip to /k/. Say the new word.", "Skip, using /s/ /k/ /i/ /p/ (2 marks).", "Substituting one phoneme within an initial blend."),
            ("Demonstrate a sound chain", "Say cat, then change one phoneme each step to make cot, dot and dog. Name each change.", "Cat→cot middle /a/ to /o/; cot→dot first /k/ to /d/; dot→dog final /t/ to /g/ (4 marks).", "Performing sequential single-phoneme substitutions."),
            ("Draw addition and deletion", "Use sound boxes to show adding /s/ to lip to make slip, then deleting /s/ to return to lip.", "Accurate 3-to-4 and 4-to-3 phoneme representations, with only /s/ changed (4 marks).", "Representing reversible phoneme manipulation."),
            ("Correct a two-sound change", "The task says change one sound from pet to peg, but a student says pig. Explain the error.", "Pet→peg changes only final /t/ to /g/; pig also changes medial /e/ to /i/ (3 marks).", "Checking that only one phoneme was substituted."),
            ("Solve a manipulation set", "Starting with best: delete /s/; then change final /t/ to /d/; then change medial /e/ to /a/. Say each result and describe each change.", "Best→bet (delete /s/)→bed (/t/→/d/)→bad (/e/→/a/), with each operation named (7 marks).", "Applying deletion and substitutions in a controlled word chain."),
        ],
    ),
    "AC9E1LY11": bank(
        "AC9E1LY11",
        "use short vowels, common long vowels, consonant blends and digraphs to write words, and blend these to read one- and two-syllable words",
        [
            ("Rule", "Short and long vowel patterns help read and spell words. Blends keep each consonant sound; digraphs use two letters for one sound, such as sh, ch and th."),
            ("Worked example", "man has short /a/. time has long /i/ with silent e. wish ends in the /sh/ digraph, while rest begins and ends with separate consonant sounds."),
            ("Reading strategy", "Spot the vowel pattern and any digraph, say sounds through the word, blend, then split a two-syllable word into spoken beats if needed."),
            ("Visual interaction", "Use grapheme tiles, sound buttons and syllable arcs with audio, tap, keyboard and paper alternatives."),
            ("Common trap", "A blend is not one sound: in stop, /s/ and /t/ are both heard; in shop, sh is one /sh/ sound."),
        ],
        [
            ("Read a short vowel word", "Blend /m/ /a/ /n/ and write the word.", "Man (1 mark).", "Reading and spelling a short-a CVC word."),
            ("Match patterns", "Match time, wish and frog to long vowel, consonant digraph and consonant blend.", "Time ↔ long vowel; wish ↔ digraph; frog ↔ blend (1 mark each).", "Recognising common Year 1 phonic patterns."),
            ("Build a digraph word", "Use letter tiles to build shop and say each phoneme.", "s-h-o-p in spelling; /sh/ /o/ /p/ in sounds (3 marks).", "Encoding a word with initial consonant digraph."),
            ("Change short to long", "Add final e to kit. Read and explain the new word.", "Kite; final e changes the vowel from short /i/ to long /i/ (2 marks).", "Using a common split-digraph long-vowel pattern."),
            ("Order blend sounds", "Order /r/ /f/ /o/ /g/ to read frog.", "/f/ /r/ /o/ /g/ → frog (2 marks).", "Blending an initial consonant cluster."),
            ("Draw sound buttons", "Write fish and draw one sound button for /f/, /i/ and /sh/.", "Correct spelling and 3 sound markers, with sh grouped (3 marks).", "Mapping a final digraph to one phoneme."),
            ("Compare blend and digraph", "Explain why br in brush is a blend but sh is a digraph.", "Both /b/ and /r/ are heard separately; sh letters work together for one /sh/ sound (3 marks).", "Distinguishing consonant blends from digraphs."),
            ("Read a two-syllable word", "Split sunset into spoken syllables, read each part and blend the whole word.", "Sun/set; reads sun + set → sunset (3 marks).", "Decoding a two-syllable compound with known patterns."),
            ("Spell a long-a word", "Write the word made by /k/ /ā/ /k/ using the common a_e pattern.", "Cake (1 mark).", "Encoding a common long-a split digraph."),
            ("Match digraphs and words", "Match sh, ch and th to ship, chop and thin.", "sh ↔ ship; ch ↔ chop; th ↔ thin (1 mark each).", "Connecting consonant digraphs with example words."),
            ("Sequence a two-syllable read", "Order: blend each part; find a syllable break; read whole word; inspect letter patterns in picnic.", "Inspect patterns → find pic/nic → blend parts → read picnic (2 marks).", "Sequencing two-syllable decoding."),
            ("Choose the vowel pattern", "Which word has a long-o pattern: hop or hope? Explain.", "Hope; o_e commonly signals long /o/, while hop has short /o/ (2 marks).", "Comparing short and long vowel spellings."),
            ("Demonstrate continuous blending", "Blend the sounds in rest without adding extra vowel sounds between /s/ and /t/.", "/r/ /e/ /s/ /t/ blended as rest, with both final blend sounds retained (3 marks).", "Reading a word with final consonant blend."),
            ("Draw a two-syllable map", "Write rabbit, mark rab/bit and underline the short vowel in each syllable.", "Rabbit split rab/bit; a and i identified as short vowel sounds (4 marks).", "Representing vowel patterns across two syllables."),
            ("Correct a digraph split", "A reader sounds ship as /s/ /h/ /i/ /p/. Explain and correct.", "Sh represents one /sh/ phoneme; correct segmentation /sh/ /i/ /p/ (3 marks).", "Correcting misuse of a consonant digraph."),
            ("Decode and encode a mixed set", "Read and then spell from memory: flag, chin, home and sunset. Name the blend, digraph, long-vowel pattern or syllable split used in each.", "All four words accurate; fl blend, ch digraph, o_e long /o/, sun/set syllables, with explanations (8 marks).", "Applying varied phonic knowledge to reading and spelling."),
        ],
    ),
    "AC9E1LY12": bank(
        "AC9E1LY12",
        "understand that a letter can represent more than one sound and that a syllable must contain a vowel sound",
        [
            ("Rule", "A letter can represent different sounds in different words. Every spoken syllable contains one vowel sound, even when the spelling uses y for that vowel sound."),
            ("Worked example", "c is /k/ in cat and /s/ in city. The two syllables in robot are ro/bot, and each has a vowel sound."),
            ("Word strategy", "Use the whole word and known pattern to choose a letter's sound; clap or tap the spoken beats to find syllables and listen for a vowel sound in each."),
            ("Visual interaction", "Use sound-choice cards and syllable arcs with audio, tap, keyboard and paper marking alternatives."),
            ("Common trap", "Count spoken syllables, not separate vowel letters; boat has two vowel letters but one vowel sound and one syllable."),
        ],
        [
            ("Compare c sounds", "What sounds does c represent in cat and city?", "Cat begins /k/; city begins /s/ (2 marks).", "Recognising two sounds represented by one letter."),
            ("Match words and syllables", "Match cat, sunset and banana to 1, 2 and 3 syllables.", "Cat ↔ 1; sunset ↔ 2; banana ↔ 3 (1 mark each, allowing standard Australian pronunciation).", "Counting syllables in spoken words."),
            ("Tap vowel beats", "Say robot, tap its syllables and identify the vowel sound in each spoken beat.", "Ro/bot, 2 syllables; long /o/ in ro and short /o/ in bot (3 marks).", "Locating vowel sounds in syllables."),
            ("Choose the s sound", "In sat and rose, does s represent the same final/initial sound? State both.", "Sat has /s/; the s in rose commonly represents /z/ (2 marks).", "Recognising differing sounds for letter s."),
            ("Order syllable checking", "Order: say word; tap beats; listen for vowel sound in each; check whole word.", "Say → tap → identify vowel sound per beat → check (2 marks).", "Sequencing a syllable-analysis routine."),
            ("Draw syllable arcs", "Write picnic and draw one arc under each syllable. Circle one vowel letter in each syllable.", "Pic/nic with two arcs; i in each syllable circled (3 marks).", "Representing syllables and vowel letters."),
            ("Explain boat", "Why is boat one syllable even though it contains o and a?", "Oa works together to represent one vowel sound in one spoken beat (2 marks).", "Separating letter count from vowel-sound/syllable count."),
            ("Compare letter a", "Say the vowel sound represented by a in cat and apron. Explain that the surrounding word pattern helps.", "Cat has short /a/; apron begins long /ā/ in standard pronunciation; whole-word pattern/context selects sound (3 marks).", "Recognising multiple sounds for letter a."),
            ("Find the vowel sound", "How many syllables are in fish, and what vowel sound must the syllable contain?", "One syllable containing short /i/ (2 marks).", "Identifying the vowel nucleus of a syllable."),
            ("Match letter sounds", "Match g in goat, g in giant and y in happy to /g/, /j/ and final /ee/.", "Goat g ↔ /g/; giant g ↔ /j/; happy y ↔ /ee/ (1 mark each).", "Connecting letters with context-dependent sounds."),
            ("Sequence spoken syllables", "Order the syllables ket, bas to make basket, then state the vowel sound in each.", "Bas/ket; short /a/ then short /e/ (3 marks).", "Ordering syllables and identifying their vowel sounds."),
            ("Check a vowelless claim", "A student says the spoken word stop has no vowel sound because it begins and ends with consonants. Correct them.", "Stop has one syllable with short /o/ between the consonants (2 marks).", "Recognising the required vowel sound inside a cluster word."),
            ("Demonstrate letter u sounds", "Say cut, put and use, listening to the sound represented by u in each.", "Identifies different common u sounds in the three words without requiring technical symbols (3 marks).", "Exploring multiple sounds for one vowel letter."),
            ("Draw sound and syllable maps", "Map music and cup. Mark syllable arcs and highlight the letter u in both, then describe the sound difference.", "Music has two syllables and initial long /yoo/ or /oo/ by accent; cup one syllable short /u/; difference stated (4 marks).", "Comparing letter sound across word contexts."),
            ("Correct vowel-letter counting", "A child counts three syllables in rain because r-a-i-n has several letters. Explain and give the correct count.", "Rain is one spoken beat/syllable; ai represents one vowel sound, so letter count does not equal syllable count (3 marks).", "Correcting a letter-based syllable misconception."),
            ("Analyse a varied set", "For city, cake and happy, identify one letter that represents a less basic sound, count syllables and state a vowel sound in each syllable.", "City: c=/s/, 2 syllables; cake: a_e long /ā/, 1; happy: y=/ee/, 2; vowel sounds identified appropriately (7 marks).", "Integrating flexible letter-sound and syllable knowledge."),
        ],
    ),
    "AC9E1LY13": bank(
        "AC9E1LY13",
        "spell one- and two-syllable words with common letter patterns",
        [
            ("Rule", "Spell by saying the word, segmenting sounds or syllables, choosing known patterns, writing, then rereading to check."),
            ("Worked example", "sunset splits sun/set. Each syllable uses a familiar short-vowel pattern, so the parts can be spelled and joined."),
            ("Pattern clue", "Word families share chunks such as -at, -ake or -ight; blends such as bl and st keep both consonants."),
            ("Visual interaction", "Use sound tiles, word-family chunks and syllable cards with audio, keyboard and paper alternatives."),
            ("Common trap", "A word that rhymes may use a different spelling, so check the known pattern and visual word memory."),
        ],
        [
            ("Spell a word family member", "Write the word made by adding m to the beginning of -at.", "Mat (1 mark).", "Using a common rime pattern to spell."),
            ("Match patterns and words", "Match -ake, -ight and -ain to cake, light and rain.", "Each pattern matched correctly (1 mark each).", "Recognising common letter patterns."),
            ("Build a blend word", "Use letter tiles to spell stop, keeping both beginning sounds.", "s-t-o-p in correct order, with st blend retained (2 marks).", "Spelling a one-syllable word with initial blend."),
            ("Split a two-syllable word", "Split and spell picnic by its two spoken syllables.", "Pic/nic → picnic (2 marks).", "Using syllable chunks to spell a two-syllable word."),
            ("Order spelling checks", "Order: segment word; say word; write patterns; reread/check.", "Say → segment → write → reread/check (2 marks).", "Sequencing a spelling strategy."),
            ("Draw a word-family house", "Create a -op word-family house containing hop, mop and stop. Highlight the shared chunk.", "All three words spelled correctly and -op highlighted (3 marks).", "Organising spellings by shared pattern."),
            ("Explain a missing blend letter", "A student spells black as back. Which sound/letter from the blend is missing?", "/l/ and letter l are missing from bl (2 marks).", "Detecting an omitted consonant in a blend."),
            ("Spell from two chunks", "Spell bedroom by joining two familiar one-syllable words. State both parts.", "Bed + room = bedroom (3 marks).", "Building a two-syllable compound from known words."),
            ("Use a long-vowel pattern", "Write the word cake from the sounds /k/ /ā/ /k/ using a common pattern.", "Cake (1 mark).", "Applying the a_e letter pattern."),
            ("Match blends and words", "Match bl, st and cr to blue, nest and crab, identifying where each blend occurs.", "Bl ↔ blue beginning; st ↔ nest ending; cr ↔ crab beginning (1 mark each).", "Recognising initial and final blend spellings."),
            ("Sequence syllable cards", "Order bow, rain to spell rainbow and write the whole word.", "Rain + bow = rainbow (2 marks).", "Ordering syllables in a compound word."),
            ("Choose between patterns", "Which spelling fits the long /ī/ word: tim or time? Explain.", "Time; i_e represents the long /ī/ sound here (2 marks).", "Selecting a common long-vowel spelling pattern."),
            ("Demonstrate say-segment-write", "Use the routine to spell frog aloud and in writing.", "Says frog, segments /f r o g/, writes f-r-o-g and rereads (3 marks).", "Applying a full spelling routine to a blend word."),
            ("Draw syllable boxes", "Write rabbit in two boxes for rab and bit. Underline the vowel pattern in each.", "Rab | bit, complete spelling with a and i identified (3 marks).", "Representing two-syllable spelling structure."),
            ("Correct a pattern error", "A student writes nite for night in a taught -ight word family. Explain how the known family helps correct it.", "Recognises shared -ight chunk from light/right; correct spelling night (3 marks).", "Using visual pattern knowledge to edit spelling."),
            ("Spell and justify a mixed list", "Spell plant, wish, sunset and boat. For each, name the blend, digraph, syllable split or vowel pattern that helped.", "All four correct; pl blend, sh digraph, sun/set, oa pattern, each explanation accurate (8 marks).", "Applying common patterns across one- and two-syllable words."),
        ],
    ),
    "AC9E1LY14": bank(
        "AC9E1LY14",
        "read and write an increasing number of high-frequency words",
        [
            ("Rule", "High-frequency words appear often, so readers learn to recognise and write them quickly. Some are fully decodable; others include a less expected part that must be remembered."),
            ("Worked example", "In have, h and v are regular, while the final e does not make a long-a sound. Say, spell, cover, write and check."),
            ("Practice strategy", "Read the word in a sentence, notice the tricky part, write it from memory, then compare and correct."),
            ("Visual interaction", "Use uncluttered word cards, audio, sentence contexts and keyboard/paper recall rather than speed-only competition."),
            ("Common trap", "Fast guessing is not mastery; the word must be read accurately and spelled correctly in meaningful text."),
        ],
        [
            ("Read a common word", "Read the word one in ‘I have one bag.’", "One, read accurately (1 mark).", "Recognising a high-frequency word in context."),
            ("Match words and sentences", "Match have, said and pretty to ‘I __ a hat’, ‘Mia __ hello’ and ‘a __ shell’.", "Have ↔ possess hat; said ↔ spoke hello; pretty ↔ describes shell (1 mark each).", "Reading high-frequency words through sentence context."),
            ("Write from memory", "Look at have, cover it, write it and check each letter.", "h-a-v-e in correct order, with self-check (2 marks).", "Encoding a high-frequency word from memory."),
            ("Find the tricky part", "In one, which spelling part does not match the most expected sounds for a beginning reader?", "The whole pronunciation is less predictable from o-n-e; response may identify initial o sounding /w/+/u/ or the unusual pattern (2 marks).", "Noticing an irregular high-frequency spelling."),
            ("Order word practice", "Order: read in sentence; notice tricky part; cover and write; check/correct.", "Read → notice → cover/write → check/correct (2 marks).", "Sequencing an effective high-frequency-word routine."),
            ("Draw a word memory card", "Create a card for said with the word, one sentence and a mark around the less expected ai spelling.", "Said spelled correctly, sentence meaningful and ai highlighted as remembered spelling (3 marks).", "Building orthographic memory for a common word."),
            ("Choose the correct word", "Complete ‘They __ coming with us’ using are or our.", "Are (1 mark).", "Selecting a high-frequency word by grammar and meaning."),
            ("Edit a common-word sentence", "Correct: ‘I hav one littel bag.’", "‘I have one little bag.’ (3 corrections/marks).", "Applying remembered high-frequency spellings in context."),
            ("Read without picture guessing", "The sentence says ‘Come here, please.’ Read the two high-frequency location/action words.", "Come and here (2 marks).", "Recognising high-frequency words in connected text."),
            ("Match commonly confused words", "Match where, were and we're to a place question, past form of are and we are.", "Where ↔ place question; were ↔ past are; we're ↔ we are (1 mark each).", "Distinguishing visually similar frequent words."),
            ("Sequence a sentence", "Order: some / We / have / apples.", "We have some apples. (2 marks).", "Reading and arranging high-frequency words in syntax."),
            ("Recall a taught set", "Write one, have and pretty from memory, then circle any corrected letter.", "All three final spellings accurate; correction process shown if needed (3 marks).", "Writing an increasing bank of high-frequency words."),
            ("Demonstrate rapid accurate reading", "Read a mixed row—said, the, have, come, one—twice, aiming for smooth accuracy rather than racing.", "All five read accurately with improved or steady smoothness (3 marks).", "Developing automatic recognition."),
            ("Draw meaning contrasts", "Create small context pictures or labels for there, their and they're and write one sentence for each.", "Three meanings distinguished and spellings used correctly in age-supported sentences (5 marks).", "Connecting frequent homophones with meaning and spelling."),
            ("Correct visual similarity error", "A reader says have for here because both begin with h. Explain a better checking method.", "Look through all letters, blend/recognise the whole word and check sentence meaning; first letter alone is insufficient (3 marks).", "Monitoring high-frequency word recognition."),
            ("Use a high-frequency word bank", "Write a four-sentence mini-text using at least eight taught high-frequency words, then underline them and check spelling.", "Four coherent sentences; eight appropriate frequent words underlined and accurately spelled after checking (8 marks).", "Applying automatic words in connected writing."),
        ],
    ),
    "AC9E1LY15": bank(
        "AC9E1LY15",
        "recognise and know how to use grammatical morphemes to create word families",
        [
            ("Rule", "A morpheme is a meaningful word part. A base such as play can combine with -s, -ed or -ing to show who, time or ongoing action and build a word family."),
            ("Worked example", "play, plays, played and playing share the base play. -s can mark one person/thing acting, -ed past action and -ing ongoing action."),
            ("Word strategy", "Find the base, cover or separate the added part, read both meanings, then choose the form that fits the sentence."),
            ("Visual interaction", "Use base-and-ending tiles, family trees and sentence slots with tap, keyboard and paper alternatives."),
            ("Common trap", "Words that merely start alike are not always one grammatical family; the shared base and added part must carry related meaning."),
        ],
        [
            ("Find the base", "What base word is inside played?", "Play (1 mark).", "Recognising a base within an inflected word."),
            ("Match endings and meanings", "Match -s, -ed and -ing in plays, played and playing to one actor/present form, past and ongoing action.", "-s ↔ plays/present one actor; -ed ↔ past; -ing ↔ ongoing (1 mark each).", "Connecting grammatical morphemes with meanings."),
            ("Build a word family", "Use tiles to make jump, jumps, jumped and jumping. Read each word.", "All four forms constructed/read accurately with base jump retained (4 marks).", "Creating an inflectional word family."),
            ("Choose the time form", "Complete ‘Yesterday we __ in puddles’ using jump, jumped or jumping.", "Jumped (1 mark).", "Selecting past-tense morphology from context."),
            ("Order a family", "Order these from base to added endings: looking, look, looked, looks.", "Look first; looks/looked/looking follow as derived forms, with any logical ending order accepted after base (2 marks).", "Recognising base and family members."),
            ("Draw a family tree", "Draw read at the trunk and add reads, reading and reader as branches. Label the added parts.", "Base read and related branches -s, -ing, -er accurately shown; reader accepted as related agent noun (4 marks).", "Representing derivational and inflectional family links."),
            ("Explain shared meaning", "How are walk and walked related, and what new meaning does -ed add?", "Both name walking action; -ed places it in the past/completed time (2 marks).", "Explaining morpheme contribution."),
            ("Create sentence contrasts", "Use plays and played in two sentences that make their time meanings clear.", "Two grammatical sentences showing present/habitual versus past action (3 marks).", "Applying family forms in context."),
            ("Recognise an ongoing form", "Which word fits ‘The dog is __ now’: bark, barked or barking?", "Barking (1 mark).", "Using -ing with an auxiliary for ongoing action."),
            ("Match bases and families", "Match help, paint and kick to helper/helped/helping; painter/painted/painting; kicker/kicked/kicking.", "Each family matches its base (1 mark each).", "Grouping words by meaningful base."),
            ("Sequence word building", "Order: read whole word; find base; choose -ing; join play + ing.", "Find/read base play → choose -ing → join playing → read whole word (2 marks).", "Sequencing morphological word construction."),
            ("Choose subject agreement", "Complete ‘The bird __’ and ‘The birds __’ using sings and sing.", "The bird sings; the birds sing (2 marks).", "Using -s according to singular subject."),
            ("Demonstrate morpheme removal", "Say playing, remove the -ing part and state the base and meaning change.", "Playing → play; ongoing form returns to base action (3 marks).", "Using morpheme removal to decode meaning."),
            ("Draw base and compound", "Show how play and ground join to make playground. Explain how the two meaningful parts help.", "Play + ground = playground; combined meaning is a ground/place for play (3 marks).", "Recognising meaningful parts in a compound family."),
            ("Correct a false family", "A student groups play, plate and played because they begin pla. Explain which belong and why.", "Play and played share base/meaning; plate only shares letters and is unrelated (3 marks).", "Distinguishing morphemic family from visual similarity."),
            ("Analyse a family in text", "Sentence: ‘The painter painted while her helper was helping.’ Identify the bases, added morphemes and meaning each form contributes.", "Paint base + -er person, paint + -ed past; help + -er person, help + -ing ongoing with was; relationships explained (7 marks).", "Analysing grammatical and derivational morphemes in context."),
        ],
    ),
}


def main() -> None:
    written = write_banks(SPECS)
    print(f"Wrote {len(written)} Year 1 English Literacy code banks")


if __name__ == "__main__":
    main()
