#!/usr/bin/env python3
"""Build the authored Year 1 Mathematics Pass 1 banks after AC9M1N01."""

from __future__ import annotations

from year1_bank_builder import write_banks


def bank(code: str, description: str, quick_read: list[tuple[str, str]], items: list[tuple[str, str, str, str]]) -> dict[str, object]:
    return {
        "code": code,
        "subject": "Mathematics",
        "description": description,
        "quick_read": quick_read,
        "items": items,
    }


SPECS = {
    "AC9M1N02": bank(
        "AC9M1N02",
        "partition one- and two-digit numbers in different ways using physical and virtual materials, including partitioning two-digit numbers into tens and ones",
        [
            ("Key idea", "A whole number can be split into parts in more than one correct way."),
            ("Method", "Use tens and ones first, then exchange one ten for 10 ones to make another partition."),
            ("Worked example", "35 is 3 tens and 5 ones. It is also 2 tens and 15 ones because both totals are 35."),
            ("Visual model", "Build numbers with base-ten sticks, ten-frames or bundled popsticks. Online, move tens and ones with tap and keyboard alternatives."),
            ("Common trap", "The parts must recombine to the original whole; 3 tens and 4 ones make 34, not 43."),
        ],
        [
            ("Name the tens and ones", "Partition 47 into tens and ones.", "4 tens and 7 ones, or 40 + 7 (1 mark).", "Reading a standard tens-and-ones partition."),
            ("Match numbers and parts", "Match 23, 40 and 56 to 2 tens 3 ones, 4 tens 0 ones and 5 tens 6 ones.", "23 ↔ 2 tens 3 ones; 40 ↔ 4 tens 0 ones; 56 ↔ 5 tens 6 ones (1 mark each).", "Connecting numerals with base-ten partitions."),
            ("Build eighteen two ways", "Use counters or ten-frames to show 18 as 10 and 8, then as two different parts.", "Shows 10 + 8 and another valid partition such as 9 + 9 or 12 + 6 (1 mark each).", "Representing one number with multiple partitions."),
            ("Find the missing part", "Complete 10 = 6 + __ and explain how you know.", "4; 6 and 4 fill a ten-frame or count on from 6 to 10 (2 marks).", "Using part-part-whole facts to 10."),
            ("Regroup thirty-four", "Order these steps to show 34 as 2 tens and 14 ones: count the whole; exchange one ten for 10 ones; begin with 3 tens and 4 ones.", "Begin with 3 tens and 4 ones → exchange one ten for 10 ones → count the whole (2 marks).", "Sequencing a base-ten regrouping."),
            ("Draw two partitions", "Draw 26 as tens and ones, then draw a different partition of 26.", "Shows 2 tens + 6 ones and a valid alternative such as 1 ten + 16 ones (2 marks).", "Recording equivalent partitions visually."),
            ("Check a regrouped number", "Noah says 2 tens and 14 ones make 34. Is he correct? Explain.", "Yes; 20 + 14 = 34, or 14 ones can become 1 ten and 4 ones, giving 3 tens and 4 ones (2 marks).", "Reasoning about non-standard partitions."),
            ("Challenge one-only thinking", "A student says 42 can only be split as 40 + 2. Give two other partitions and prove each totals 42.", "Two valid examples such as 30 + 12 and 20 + 22, with an addition or materials check for each (4 marks).", "Generating and verifying multiple partitions."),
            ("Read a fresh model", "A model has 6 tens sticks and 3 single cubes. Write the numeral and expanded form.", "63 and 60 + 3 (2 marks).", "Interpreting a base-ten representation."),
            ("Match equivalent forms", "Match 17, 29 and 50 to 10 + 7, 20 + 9 and 5 tens.", "17 ↔ 10 + 7; 29 ↔ 20 + 9; 50 ↔ 5 tens (1 mark each).", "Recognising equivalent numerical representations."),
            ("Exchange within thirty-two", "Put these actions in order to change 32 into 1 ten and 22 ones: verify the total; exchange one of 3 tens; count 1 ten and 22 ones.", "Exchange one of 3 tens → count 1 ten and 22 ones → verify the total remains 32 (2 marks).", "Following an exchange while preserving value."),
            ("Create an alternate partition", "Write the number made by 5 tens and 8 ones, then partition it without using 5 tens.", "58; a valid alternative such as 4 tens and 18 ones (2 marks).", "Moving between standard and non-standard partitions."),
            ("Show twenty-four after exchange", "Build 24 with tens and ones. Exchange one ten and state the new partition.", "Begins with 2 tens and 4 ones; after exchange shows 1 ten and 14 ones (2 marks).", "Demonstrating a base-ten exchange."),
            ("Part-part-whole diagram", "Draw two part-part-whole diagrams for 37: one using 30 and one using 20.", "Whole 37 with parts 30 and 7; whole 37 with parts 20 and 17 (2 marks).", "Using diagrams to record equivalent partitions."),
            ("Compare two claims", "Ava writes 3 tens and 12 ones. Eli writes 4 tens and 2 ones. Explain whether their totals are equal.", "They are equal: 30 + 12 = 42 and 40 + 2 = 42; exchanging 10 ones explains the equivalence (3 marks).", "Comparing partitions through regrouping."),
            ("Find the tens pattern", "List the partitions of 46 made by using 4, 3, 2, 1 and 0 tens. Describe what changes each time.", "40+6, 30+16, 20+26, 10+36, 0+46; each lost ten adds 10 ones while the whole stays 46 (6 marks).", "Generalising the relationship between tens and ones."),
        ],
    ),
    "AC9M1N03": bank(
        "AC9M1N03",
        "quantify sets of objects, to at least 120, by partitioning collections into equal groups using number knowledge and skip counting",
        [
            ("Key idea", "Equal groups have the same number in every group. Skip counting counts those groups efficiently."),
            ("Method", "Choose a useful group size, make equal groups, skip count the full groups, then add any leftovers."),
            ("Worked example", "Six bags with 5 shells in each contain 5, 10, 15, 20, 25, 30 shells."),
            ("Visual model", "Use grouped counters, bundles, arrays or labelled hoops. Online grouping must also work by tap and keyboard."),
            ("Common trap", "Do not skip count unequal groups as if they were equal; count leftovers separately."),
        ],
        [
            ("Count groups of two", "Four equal pairs of socks are shown. How many socks are there? Show the skip count.", "2, 4, 6, 8; there are 8 socks (2 marks).", "Quantifying equal groups of 2."),
            ("Match groups and totals", "Match 3 groups of 5, 6 groups of 2 and 2 groups of 10 to 15, 12 and 20.", "3 groups of 5 ↔ 15; 6 groups of 2 ↔ 12; 2 groups of 10 ↔ 20 (1 mark each).", "Connecting equal-group descriptions to totals."),
            ("Group twenty-five", "Arrange 25 counters into equal groups of 5 and skip count to find the total.", "Makes 5 groups of 5 and counts 5, 10, 15, 20, 25 (2 marks).", "Using materials and skip counting by 5."),
            ("Tens and leftovers", "A jar holds 36 buttons. Explain how groups of 10 help count them.", "3 full groups of 10 give 30, with 6 leftover; 30 + 6 = 36 (2 marks).", "Partitioning a collection into tens and ones."),
            ("Order a five-count", "Put these number cards in the counting order used for 7 groups of 5: 25, 5, 35, 15, 30, 10, 20.", "5, 10, 15, 20, 25, 30, 35 (1 mark for full order).", "Sequencing skip counts by 5."),
            ("Draw pairs to eighteen", "Draw 18 dots in equal groups of 2 and label the skip count.", "Shows 9 pairs and labels 2 through 18 by twos (2 marks).", "Representing a collection as equal pairs."),
            ("Count full groups and extras", "Twenty-two beads are placed in groups of 5. How many full groups and leftovers are there, and what is the total check?", "4 full groups and 2 leftovers; 5, 10, 15, 20, then 21, 22 (3 marks).", "Combining skip counting with leftovers."),
            ("Choose an efficient grouping", "Explain an efficient way to count 47 loose counters and why it is reliable.", "Makes 4 groups of 10 and 7 singles, counts 10, 20, 30, 40, then 7 more, and checks groups are complete (3 marks).", "Selecting and justifying an efficient grouping strategy."),
            ("Count six groups", "There are 6 trays with 10 seedlings on each tray. State the total and the count used.", "10, 20, 30, 40, 50, 60; 60 seedlings (2 marks).", "Skip counting groups of 10."),
            ("Match fresh collections", "Match 8 pairs, 4 groups of 5 and 7 groups of 10 to 16, 20 and 70.", "8 pairs ↔ 16; 4 groups of 5 ↔ 20; 7 groups of 10 ↔ 70 (1 mark each).", "Relating group structures to totals."),
            ("Order the bundle count", "A class bundles 53 straws. Order the counting steps: count 3 singles; make 5 bundles of 10; skip count 10 to 50.", "Make 5 bundles of 10 → skip count 10 to 50 → count 3 singles (2 marks).", "Sequencing a tens-and-ones count."),
            ("Find the hidden total", "Five equal bowls each contain 2 apples, and 3 apples remain on the table. How many apples are there?", "5 groups of 2 = 10, then 10 + 3 = 13 apples (2 marks).", "Adding leftovers after equal-group counting."),
            ("Demonstrate two group sizes", "Show 20 counters first in groups of 5 and then in groups of 2. State the number of groups each time.", "4 groups of 5 and 10 groups of 2, both totalling 20 (3 marks).", "Repartitioning one collection into different equal groups."),
            ("Draw a grouped collection", "Draw 42 marks using groups of 10 and leftovers. Label every group and the total.", "Shows 4 groups of 10 and 2 singles, labelled 42 (2 marks).", "Recording a large collection with grouped marks."),
            ("Audit an unequal count", "Sam counts bags containing 5, 5, 4 and 5 marbles as 5, 10, 15, 20. Explain the error and find the actual total.", "The third bag is not a full group of 5; actual total is 5 + 5 + 4 + 5 = 19 (3 marks).", "Detecting misuse of skip counting with unequal groups."),
            ("Compare two counting plans", "For 68 craft sticks, compare counting every stick with making groups of 10. Give a grouped count and explain which plan is easier to check.", "6 groups of 10 and 8 singles make 68; grouping by 10 is easier to track/check because fewer count steps are needed (3 marks).", "Evaluating counting strategies for a large collection."),
        ],
    ),
    "AC9M1N04": bank(
        "AC9M1N04",
        "add and subtract numbers within 20, using physical and virtual materials, part-part-whole knowledge to 10 and a variety of calculation strategies",
        [
            ("Key idea", "Addition combines or increases; subtraction removes, compares or finds a missing part."),
            ("Method", "Use known parts to 10, doubles, count-on or make-10. Check subtraction by adding the answer back."),
            ("Worked example", "8 + 7 becomes 10 + 5: move 2 from the 7 to the 8, so the total is 15."),
            ("Visual model", "Use counters, ten-frames, part-part-whole diagrams and number lines with draggable, tappable and keyboard choices."),
            ("Common trap", "Read what changes in the story; a larger starting number does not always mean add."),
        ],
        [
            ("Complete ten", "What part joins 6 to make 10? Write the related addition fact.", "4; 6 + 4 = 10 (2 marks).", "Using a part-part-whole fact to 10."),
            ("Match related facts", "Match 7 + 3, 10 − 3 and 10 − 7 to 10, 7 and 3.", "7 + 3 ↔ 10; 10 − 3 ↔ 7; 10 − 7 ↔ 3 (1 mark each).", "Connecting fact-family addition and subtraction."),
            ("Remove five counters", "Show 13 counters, remove 5 and state how many remain.", "8 remain; demonstration starts at 13 and removes exactly 5 (2 marks).", "Modelling subtraction as removal."),
            ("Make ten to add", "Solve 9 + 6 by making 10. Show the split you used.", "Split 6 into 1 and 5; 9 + 1 + 5 = 15 (3 marks).", "Applying the make-10 addition strategy."),
            ("Count on a number line", "Order the jumps for 7 + 5 using a make-10 route: land on 12; jump 3 to 10; start at 7; jump 2 more.", "Start at 7 → jump 3 to 10 → jump 2 more → land on 12 (2 marks).", "Sequencing number-line addition steps."),
            ("Draw a fact family", "Draw a part-part-whole diagram with whole 14 and parts 8 and 6. Write one addition and one subtraction fact.", "Diagram shows 14, 8 and 6; examples 8 + 6 = 14 and 14 − 8 = 6 (3 marks).", "Representing related facts with a diagram."),
            ("Find the missing amount", "Solve 17 − __ = 9 and explain an addition check.", "8; because 9 + 8 = 17 (2 marks).", "Finding a missing part and checking by addition."),
            ("Compare two strategies", "Solve 8 + 8 using a doubles fact and a make-10 strategy. Explain why both agree.", "Double 8 is 16; 8 + 2 + 6 is also 16; both rearrange the same two parts without changing the total (4 marks).", "Comparing valid addition strategies."),
            ("Use a near double", "Find 7 + 8 using a doubles fact.", "Double 7 is 14, then add 1 to get 15, or double 8 minus 1 (2 marks).", "Using a near-double strategy."),
            ("Match equations and answers", "Match 16 − 7, 6 + 9 and 18 − 8 to 9, 15 and 10.", "16 − 7 ↔ 9; 6 + 9 ↔ 15; 18 − 8 ↔ 10 (1 mark each).", "Calculating mixed facts within 20."),
            ("Order a subtraction strategy", "Order the steps for 15 − 6: subtract 5 to reach 10; start at 15; subtract 1 more; state 9.", "Start at 15 → subtract 5 to reach 10 → subtract 1 more → state 9 (2 marks).", "Sequencing subtraction through 10."),
            ("Compare two towers", "A red tower has 12 cubes and a blue tower has 7. How many more cubes are in the red tower? Write an equation.", "5 more; 12 − 7 = 5 (2 marks).", "Modelling subtraction as comparison."),
            ("Show an unknown start", "Use counters to solve __ + 6 = 18 and describe the missing part.", "12 counters are the missing part because 12 + 6 = 18 (2 marks).", "Solving an addition equation with an unknown part."),
            ("Draw an addition route", "Draw a number-line strategy for 6 + 7 that touches 10 and ends at the answer.", "Shows 6 → 10 with +4, then → 13 with +3; answer 13 (3 marks).", "Recording make-10 addition on a number line."),
            ("Correct a sign error", "Lina has 14 stickers and gives away 5. She writes 14 + 5 = 19. Explain the error and solve the story.", "Giving away decreases the collection, so subtraction is required; 14 − 5 = 9 stickers (3 marks).", "Selecting the operation from story meaning."),
            ("Prove a calculation", "Choose a strategy for 19 − 8, solve it, then check your result using addition.", "A valid strategy gives 11, such as 19 − 9 + 1; check 11 + 8 = 19 (4 marks).", "Solving and independently checking subtraction."),
        ],
    ),
    "AC9M1N05": bank(
        "AC9M1N05",
        "use mathematical modelling to solve practical problems involving additive situations including simple money transactions; represent the situations with diagrams, physical and virtual materials, and use calculation strategies to solve the problem",
        [
            ("Key idea", "A mathematical model turns a real situation into objects, a drawing or an equation that can be solved and checked."),
            ("Method", "Ask what is known and unknown, choose addition or subtraction, represent the story, calculate, then answer with a label."),
            ("Worked example", "A bookmark costs $3 and a pencil costs $4. A bar model shows 3 + 4, so the total is $7."),
            ("Visual model", "Use counters, Australian play coins, bar models and part-part-whole diagrams with accessible move-and-place controls."),
            ("Common trap", "Do not choose an operation from one word alone; decide whether the amount joins, leaves or is compared."),
        ],
        [
            ("Join two collections", "There are 7 red apples and 5 green apples. Draw or write a model and find the total.", "Model shows 7 + 5; total 12 apples (2 marks).", "Modelling an additive joining situation."),
            ("Match stories and equations", "Match these stories to 9 + 4, 13 − 4 and 13 − 9: 9 birds joined by 4; 4 of 13 birds fly away; compare 13 birds with 9 birds.", "Joined ↔ 9 + 4; flew away ↔ 13 − 4; comparison ↔ 13 − 9 (1 mark each).", "Selecting operations from three additive structures."),
            ("Pay with play coins", "Show one way to pay exactly $8 using $1 and $2 play coins, then count the value.", "Any exact combination, such as four $2 coins, with correct count to $8 (2 marks).", "Representing a simple money amount."),
            ("Find what remains", "A basket holds 16 oranges. Six are used. Represent and solve the situation.", "A removal model or 16 − 6 = 10; 10 oranges remain (2 marks).", "Modelling subtraction as removal."),
            ("Order the modelling cycle", "Put these actions in order: answer with units; choose an operation and model; read what changes; calculate and check.", "Read what changes → choose an operation and model → calculate and check → answer with units (2 marks).", "Sequencing a mathematical-modelling process."),
            ("Draw a money model", "A card costs $6 and a ribbon costs $3. Draw coins or a bar model and show the total cost.", "Represents 6 and 3, combines them, and labels $9 (3 marks).", "Representing and solving a purchase total."),
            ("Work out the hidden start", "After 5 shells are added, a collection has 14 shells. How many were there at first? Show an equation.", "9 shells; 9 + 5 = 14 or 14 − 5 = 9 (2 marks).", "Modelling a change problem with an unknown start."),
            ("Choose and justify a model", "A child has $15 and spends $7. Choose counters, coins, a bar model or a number line, solve the problem and explain why the model fits.", "$8 remains; representation shows 15 − 7 and explanation connects spending with a decrease (4 marks).", "Selecting, using and justifying a mathematical model."),
            ("Find a combined cost", "A fruit cup costs $5 and water costs $2. What is the total cost? Include a model or equation.", "$7; 5 + 2 = 7 with an appropriate representation (2 marks).", "Solving a simple transaction total."),
            ("Match fresh models", "Match 11 + 6, 17 − 6 and 17 − 11 to: joining 6 with 11; taking 6 from 17; finding how many more 17 is than 11.", "Joining ↔ 11 + 6; taking ↔ 17 − 6; comparing ↔ 17 − 11 (1 mark each).", "Distinguishing additive situation types."),
            ("Plan before calculating", "Order the steps for a story about 18 balloons with 9 popping: state what is unknown; represent 18 − 9; note that balloons leave; solve and label.", "Note balloons leave → state remaining is unknown → represent 18 − 9 → solve 9 balloons and label (2 marks).", "Planning a subtraction model from context."),
            ("Compare pocket money", "Ravi has $12 and Mei has $8. How much more does Ravi have? Show the comparison.", "$4 more; 12 − 8 = 4 or a comparison bar model (2 marks).", "Modelling an additive comparison involving money."),
            ("Act out a missing change", "Start with an unknown number of counters. Add 7 to finish with 19. Demonstrate how to find the start.", "Removes 7 from 19 or counts back to 12; starting amount 12 (2 marks).", "Using materials for an unknown-start problem."),
            ("Draw two-step evidence", "Mia buys a $4 notebook and a $5 pen and pays with $10. Draw a model showing the total and money left.", "Total $9, then $10 − $9 = $1 left; drawing clearly shows both steps (4 marks).", "Representing a two-step money situation."),
            ("Check an unreasonable answer", "For 13 toy cars with 4 given away, a student answers 17. Explain why it is unreasonable and correct it.", "The amount must decrease; 13 − 4 = 9 cars, and 9 + 4 checks to 13 (3 marks).", "Evaluating reasonableness in a subtraction model."),
            ("Model two possible stories", "Create one joining story and one comparison story that both use the numbers 8 and 6. Write and solve an equation for each.", "Valid joining story uses 8 + 6 = 14; valid comparison uses 8 − 6 = 2, with quantities and labels (5 marks).", "Creating and solving different additive models from the same numbers."),
        ],
    ),
    "AC9M1N06": bank(
        "AC9M1N06",
        "use mathematical modelling to solve practical problems involving equal sharing and grouping; represent the situations with diagrams, physical and virtual materials, and use calculation strategies to solve the problem",
        [
            ("Key idea", "Equal sharing asks how many each person receives; grouping asks how many equal groups can be made."),
            ("Method", "Represent every object, make equal groups, count the result and check that no object was lost or counted twice."),
            ("Worked example", "Share 12 counters among 3 plates one at a time. Each plate gets 4, and 3 groups of 4 return to 12."),
            ("Visual model", "Use counters and hoops, plates, equal rows or grouping boxes with drag, tap and keyboard placement."),
            ("Common trap", "Equal means every full group has the same amount; leftovers must be reported, not hidden."),
        ],
        [
            ("Share eight equally", "Eight strawberries are shared equally between 2 children. How many does each child receive?", "4 each; a model shows 2 equal groups of 4 (2 marks).", "Modelling equal sharing between 2 recipients."),
            ("Match sharing models", "Match 12 shared among 3, 10 shared among 2 and 15 shared among 5 to 4 each, 5 each and 3 each.", "12 among 3 ↔ 4 each; 10 among 2 ↔ 5 each; 15 among 5 ↔ 3 each (1 mark each).", "Connecting sharing situations to equal shares."),
            ("Make groups of three", "Use 15 counters to make groups of 3. State the number of groups.", "Makes 5 equal groups of 3 (2 marks).", "Modelling grouping with a fixed group size."),
            ("Identify a leftover", "Fourteen pencils are placed into groups of 4. How many full groups and leftovers are there?", "3 full groups of 4 and 2 pencils left over (2 marks).", "Reporting full groups and remainders informally."),
            ("Order fair sharing", "Order these steps for sharing 9 beads among 3 bowls: check all bowls are equal; place one bead in each bowl repeatedly; count 9 beads; state 3 in each.", "Count 9 → deal one to each bowl repeatedly → check equal → state 3 each (2 marks).", "Sequencing a fair-sharing method."),
            ("Draw equal rows", "Draw 16 dots in 4 equal rows and label the number in each row.", "Shows 4 rows of 4 and labels 4 in each row (2 marks).", "Representing equal sharing as an array."),
            ("Decide share or group", "A coach has 18 markers and puts 3 in each bag. Is this sharing or grouping, and how many bags are filled?", "Grouping because the bag size is known; 6 bags of 3 (3 marks).", "Distinguishing grouping from sharing."),
            ("Repair an unfair model", "A student shares 11 counters among 3 plates as 4, 4 and 3 and says it is equal. Explain what is wrong and describe the result accurately.", "The shares are not equal; 3 each can be shared equally with 2 left over, or the task needs a rule for leftovers (3 marks).", "Evaluating equality and reporting leftovers."),
            ("Share a new collection", "Twenty shells are shared equally among 5 students. Find each share and show a check.", "4 each; 5 equal groups of 4 total 20 (2 marks).", "Solving an equal-sharing situation."),
            ("Match groups to counts", "Match 18 objects in groups of 2, 20 objects in groups of 5 and 12 objects in groups of 4 to 9, 4 and 3 groups.", "18 in twos ↔ 9 groups; 20 in fives ↔ 4 groups; 12 in fours ↔ 3 groups (1 mark each).", "Finding the number of equal groups."),
            ("Sequence a grouping check", "Order the steps for putting 24 blocks into groups of 6: form equal groups of 6; count all 24; count 4 groups; check 4 groups contain 24.", "Count 24 → form groups of 6 → count 4 groups → check the grouped total is 24 (2 marks).", "Sequencing grouping and verification."),
            ("Solve with one leftover", "Thirteen biscuits are placed 3 on each plate. How many full plates and biscuits left over?", "4 full plates and 1 biscuit left over (2 marks).", "Solving a grouping problem with a leftover."),
            ("Demonstrate two interpretations", "Use 12 counters to show ‘shared among 4’ and then ‘groups of 4’. State both answers.", "Shared among 4 gives 3 each; groups of 4 gives 3 groups (3 marks).", "Comparing sharing and grouping language."),
            ("Draw a fair plan", "Draw how 18 stickers can be shared equally among 6 children. Label each share and the total.", "Shows 6 equal groups of 3, labelled 3 each and total 18 (3 marks).", "Recording an equal-sharing model."),
            ("Explain two correct models", "Luca shows 4 groups of 5 counters. Zoe shows 5 groups of 4 counters. Explain what is the same and different.", "Both total 20; one has 4 groups with 5 in each, the other 5 groups with 4 in each (3 marks).", "Comparing equal-group arrangements with the same total."),
            ("Design a fair distribution", "There are 22 craft items for 5 tables. Give the greatest equal whole-number share, report leftovers and explain how you checked.", "4 per table with 2 left; 5 groups of 4 make 20 and 20 + 2 = 22 (4 marks).", "Modelling and verifying sharing with leftovers."),
        ],
    ),
    "AC9M1A01": bank(
        "AC9M1A01",
        "recognise, continue and create pattern sequences, with numbers, symbols, shapes and objects, formed by skip counting, initially by twos, fives and tens",
        [
            ("Key idea", "A skip-counting pattern changes by the same amount each step, often +2, +5 or +10."),
            ("Method", "Compare neighbouring terms to find the rule, apply it to continue, and check every step follows the same rule."),
            ("Worked example", "15, 20, 25, 30 follows +5. The next two terms are 35 and 40."),
            ("Visual model", "Use a number line, hundreds chart, bead string or repeating groups with movable number cards."),
            ("Common trap", "The starting number does not have to equal the step; 3, 5, 7 still counts by 2."),
        ],
        [
            ("Name the rule", "What is the rule for 6, 8, 10, 12? State the next number.", "Add 2; next is 14 (2 marks).", "Recognising a skip-counting rule by 2."),
            ("Match patterns and steps", "Match 5,10,15; 12,22,32; and 7,9,11 to +5, +10 and +2.", "5,10,15 ↔ +5; 12,22,32 ↔ +10; 7,9,11 ↔ +2 (1 mark each).", "Connecting sequences with their constant steps."),
            ("Build a five-pattern", "Use counters in groups of 5 to show 10, 15, 20 and the next term.", "Shows groups representing 10, 15, 20, 25 and states 25 (2 marks).", "Representing a +5 sequence concretely."),
            ("Fill two missing terms", "Complete 30, 40, __, __, 70 and explain the rule.", "50 and 60; add 10 each time (2 marks).", "Continuing a skip-counting sequence by 10."),
            ("Order a two-pattern", "Order the cards 18, 12, 16, 10, 14 to make an increasing +2 pattern.", "10, 12, 14, 16, 18 (1 mark).", "Sequencing numbers by twos."),
            ("Draw shape groups", "Draw a pattern with 2 shapes in the first group, 4 in the second and 6 in the third. Add the next group.", "Shows groups of 2, 4, 6 and 8 shapes (2 marks).", "Representing a growing +2 pattern visually."),
            ("Find an incorrect term", "The sequence is 20, 25, 30, 36, 40. Which term breaks the rule and what should it be?", "36 breaks +5; it should be 35 (2 marks).", "Checking consistency of a number pattern."),
            ("Create from an unusual start", "Create six terms of a +10 pattern starting at 7 and explain how the ones digit helps check it.", "7, 17, 27, 37, 47, 57; the ones digit remains 7 when 10 is added (3 marks).", "Creating and explaining a +10 sequence."),
            ("Continue from twenty-three", "Write the next three terms in 23, 25, 27, __, __, __.", "29, 31, 33 (1 mark).", "Continuing a +2 sequence from an odd start."),
            ("Match representations", "Match 8,13,18; 40,50,60; and 14,16,18 to groups growing by 5, 10 and 2.", "8,13,18 ↔ +5; 40,50,60 ↔ +10; 14,16,18 ↔ +2 (1 mark each).", "Interpreting varied skip-counting patterns."),
            ("Rebuild a mixed-up pattern", "Order 55, 35, 50, 40, 45 into a +5 sequence.", "35, 40, 45, 50, 55 (1 mark).", "Ordering terms according to a +5 rule."),
            ("Use a chart clue", "On a hundreds chart, a path goes 26, 36, 46, 56. State the movement and next two numbers.", "Move down one row/add 10; 66, 76 (3 marks).", "Connecting chart movement with skip counting by 10."),
            ("Demonstrate equal jumps", "Show the pattern 4, 9, 14, 19 on a number line and state the jump size.", "Marks equal +5 jumps and states 5 (2 marks).", "Demonstrating a constant difference on a number line."),
            ("Draw a symbol growth", "Draw four groups in which the number of stars grows 10, 20, 30, 40. Label the rule.", "Shows and labels four totals with rule +10 (2 marks).", "Creating a visual skip-counting pattern."),
            ("Compare two sequences", "Sequence A is 2,4,6,8. Sequence B is 2,7,12,17. Explain one similarity and one difference.", "Both increase by a constant amount; A adds 2 while B adds 5 (3 marks).", "Comparing constant-step sequences."),
            ("Find the hidden start", "A +5 sequence ends 31, 36, 41. Write the three terms before 31 and explain your backward rule.", "16, 21, 26; subtract 5 to work backwards, then +5 verifies all terms (4 marks).", "Extending a sequence backwards and justifying it."),
        ],
    ),
    "AC9M1A02": bank(
        "AC9M1A02",
        "recognise, continue and create repeating patterns with numbers, symbols, shapes and objects, identifying the repeating unit",
        [
            ("Key idea", "A repeating pattern cycles through the same smallest unit again and again."),
            ("Method", "Find where the sequence begins to repeat, circle the smallest complete unit, then copy that unit in order."),
            ("Worked example", "red, blue, blue, red, blue, blue has the unit red–blue–blue; the next item is red."),
            ("Visual model", "Use colour, shape, sound and movement cards. Every colour pattern must also use labels or shapes."),
            ("Common trap", "Name the smallest repeating unit, not the whole strip that happens to be shown."),
        ],
        [
            ("Find the next symbol", "Continue: circle, square, circle, square, __. Name the repeating unit.", "Circle; unit is circle–square (2 marks).", "Continuing an AB repeating pattern."),
            ("Match patterns and units", "Match red-blue-red-blue; clap-stamp-stamp-clap-stamp-stamp; and 1-2-3-1-2-3 to units red-blue, clap-stamp-stamp and 1-2-3.", "Each pattern matches the stated smallest cycle (1 mark each).", "Identifying units in varied representations."),
            ("Build three repeats", "Use shape cards to make three repeats of triangle, triangle, star.", "Shows triangle-triangle-star three times in the same order (2 marks).", "Constructing a repeated unit with materials."),
            ("Repair a broken pattern", "The pattern is A, B, B, A, B, A. Which final item should change, and to what?", "The final A should be B to repeat A-B-B (2 marks).", "Detecting an error in an ABB pattern."),
            ("Order one cycle", "A pattern strip shows moon, sun, star repeated. Order the loose cards sun, moon, star to form the unit from its beginning.", "Moon, sun, star (1 mark).", "Sequencing the repeating unit."),
            ("Draw the continuation", "Draw the next four items after square, circle, circle, square, circle, circle.", "Square, circle, circle, square (2 marks).", "Extending an A-B-B visual pattern."),
            ("Test a claimed unit", "Mila says the unit in 2,4,2,4,2,4 is 2,4,2,4. Give the smallest unit and explain.", "Smallest unit is 2,4 because it alone repeats to make the full sequence (2 marks).", "Distinguishing a smallest unit from multiple repeats."),
            ("Create with two features", "Create a repeating pattern that changes both shape and size, show three repeats and mark the unit.", "A valid consistent unit uses both features, repeats three times and is clearly marked (3 marks).", "Designing and identifying a multi-feature pattern."),
            ("Continue a movement pattern", "A movement cycle is jump, clap, turn, jump, clap, turn. State the next two movements and the unit.", "Jump, clap; unit jump-clap-turn (2 marks).", "Interpreting a repeating movement pattern."),
            ("Match new cycles", "Match X-Y-Y-X-Y-Y; tap-tap-pause-tap-tap-pause; and 3-1-3-1 to X-Y-Y, tap-tap-pause and 3-1.", "All three are matched to their smallest repeating units (1 mark each).", "Recognising repeating units across symbols and sounds."),
            ("Sequence scattered cards", "Order these cards to continue cat-dog-bird: bird, dog, cat, cat, bird, dog.", "Cat, dog, bird, cat, dog, bird (2 marks).", "Reconstructing repeated cycles from unordered elements."),
            ("Locate a missing term", "Complete red, red, blue, red, __, blue, and state the unit.", "Red; unit red-red-blue (2 marks).", "Using the repeating unit to fill a gap."),
            ("Demonstrate two full cycles", "Invent a three-action pattern and perform exactly two full repeats without changing its order.", "Uses a clear 3-action unit and performs it twice in identical order (2 marks).", "Creating and demonstrating a movement pattern."),
            ("Draw and label a unit", "Draw a pattern with the unit small star–large star–circle repeated twice. Box one complete unit.", "Accurate two repeats with one small-star/large-star/circle unit boxed (3 marks).", "Recording and labelling a specified pattern unit."),
            ("Compare same-length units", "Pattern A repeats red-blue-green. Pattern B repeats red-green-blue. Explain why they are different even though they use the same items.", "Order is part of the unit; A and B arrange the colours differently, so their repeats differ (3 marks).", "Reasoning about order within repeating units."),
            ("Prove whether it repeats", "The strip is circle-square-circle-triangle-circle-square-circle-triangle. Decide whether it repeats, identify the smallest unit and use it to predict item 10.", "It repeats circle-square-circle-triangle; positions 9 and 10 begin the unit again, so item 10 is square (4 marks).", "Analysing a longer pattern and predicting by position."),
        ],
    ),
    "AC9M1M01": bank(
        "AC9M1M01",
        "compare directly and indirectly and order objects and events using attributes of length, mass, capacity and duration, communicating reasoning",
        [
            ("Key idea", "Compare one matching attribute at a time: length, mass, capacity or duration."),
            ("Method", "Compare directly when objects can meet; use the same intermediary, such as one string or container, when they cannot."),
            ("Worked example", "A string matching Shelf A is longer than Shelf B. If the same string is used, Shelf A is longer."),
            ("Visual model", "Use aligned objects, balance scales, equal containers, timelines and comparison cards with non-colour labels."),
            ("Common trap", "Tall does not always mean heavy, and a wider container does not always hold more."),
        ],
        [
            ("Choose the attribute", "Which attribute tells how much a bottle can hold: length, mass, capacity or duration?", "Capacity (1 mark).", "Naming the attribute used for container volume."),
            ("Match tools and comparisons", "Match balance scale, piece of string and sand timer to mass, length and duration.", "Balance ↔ mass; string ↔ length; timer ↔ duration (1 mark each).", "Selecting an intermediary or tool for an attribute."),
            ("Compare two masses", "Place a book and pencil on a balance or use the shown balance image. State which is heavier and the evidence.", "Names the lower/heavier side and cites the balance position (2 marks).", "Making a direct mass comparison from evidence."),
            ("Order three lengths", "Ribbon A is longer than B. Ribbon C is shorter than B. Order A, B and C from shortest to longest.", "C, B, A (2 marks).", "Using comparison statements to order length."),
            ("Sequence events by duration", "Order from shortest to longest: blink, eat lunch, school day.", "Blink → eat lunch → school day (1 mark).", "Ordering familiar event durations."),
            ("Draw a capacity comparison", "Draw the same cup being used to compare two jugs. Label the jug needing more cupfuls.", "Shows equal cup units and labels the jug with more cupfuls as greater capacity (2 marks).", "Representing an indirect capacity comparison."),
            ("Use one intermediary", "Two desks are in different rooms. Explain how one piece of string can compare their lengths fairly.", "Match/mark the same string against each desk without stretching it, then compare the marks (3 marks).", "Explaining a fair indirect length comparison."),
            ("Separate two attributes", "A large empty box and a small box of books are shown. Explain why size alone cannot decide which is heavier and name a fair test.", "Mass and outside size are different; use a balance or lift under safe supervision to compare mass (3 marks).", "Distinguishing mass from visible size."),
            ("Read a balance", "A balance shows a toy car side lower than a foam ball. Which has greater mass and how do you know?", "Toy car; its side is lower on the balance (2 marks).", "Interpreting a direct mass comparison."),
            ("Match comparative language", "Match longer, lighter and holds less to length, mass and capacity.", "Longer ↔ length; lighter ↔ mass; holds less ↔ capacity (1 mark each).", "Connecting comparison words to attributes."),
            ("Order by capacity evidence", "Cup counts are Jug P: 4, Jug Q: 7, Jug R: 5 using the same cup. Order least to greatest capacity.", "P, R, Q (2 marks).", "Ordering capacity using a common informal unit."),
            ("Compare journey times", "One walk takes 12 minutes and another takes 8 minutes. Which duration is longer and by how much?", "12-minute walk; 4 minutes longer (2 marks).", "Comparing measured durations."),
            ("Demonstrate direct length", "Show how to compare two pencils directly and state the alignment rule.", "Aligns the same starting ends on a straight baseline and compares finishing ends (2 marks).", "Demonstrating a fair direct length comparison."),
            ("Draw an event timeline", "Draw and label breakfast, school and bedtime in daily order, then circle the event that usually lasts longest.", "Correct daily order; school circled as the longest of the named events (2 marks).", "Sequencing events and reasoning about duration."),
            ("Correct an unfair capacity test", "One child uses a small cup for Jug A and a large cup for Jug B, then compares cup counts. Explain why this is unfair and fix it.", "Different units make counts incomparable; use the same cup, filled the same way, for both jugs (3 marks).", "Evaluating fairness in indirect capacity comparison."),
            ("Plan four comparisons", "For two lunchboxes, describe a fair way to compare length, mass, capacity and time taken to open them. Keep each attribute separate.", "Length: align or same string; mass: balance; capacity: same filler/cup; duration: same timer and start/end rule (4 marks).", "Selecting appropriate methods across four attributes."),
        ],
    ),
    "AC9M1M02": bank(
        "AC9M1M02",
        "measure the length of shapes and objects using informal units, recognising that units need to be uniform and used end-to-end",
        [
            ("Key idea", "A length measurement counts equal-sized units covering a distance from one end to the other."),
            ("Method", "Choose identical units, begin at the object's end, place units end-to-end with no gaps or overlaps, then count."),
            ("Worked example", "Six equal cubes fit along a pencil with no gaps, so the pencil is 6 cubes long."),
            ("Visual model", "Use cubes, paperclips or hand spans shown along a baseline; online units snap end-to-end with keyboard placement."),
            ("Common trap", "A mixed row of large and small units does not give a fair single-unit measurement."),
        ],
        [
            ("State a measured length", "Eight equal tiles fit end-to-end along a book. What is the book's length in tiles?", "8 tiles (1 mark).", "Reading a length in uniform informal units."),
            ("Match errors and fixes", "Match gap, overlap and mixed unit sizes to: move units together, separate units, and use one unit size.", "Gap ↔ move together; overlap ↔ separate; mixed sizes ↔ use one size (1 mark each).", "Recognising and correcting measurement errors."),
            ("Measure with cubes", "Measure the provided strip using equal cubes placed end-to-end and report the count.", "Uses identical cubes from one end with no gaps/overlaps and reports the correct count (3 marks).", "Demonstrating accurate informal-unit measurement."),
            ("Explain different counts", "The same desk is 9 hand spans for a child and 6 for an adult. Explain why.", "Adult hand spans are larger, so fewer cover the same length; the desk did not change (2 marks).", "Explaining how unit size affects the count."),
            ("Order the measuring steps", "Order: count the units; choose equal units; place them with no gaps from the start; state the unit name.", "Choose equal units → place from start with no gaps → count → state unit name (2 marks).", "Sequencing an accurate measuring process."),
            ("Draw a fair measurement", "Draw five equal paperclips end-to-end along a line. Mark the start and finish.", "Five uniform units touch end-to-end and align with both endpoints (2 marks).", "Representing a valid informal measurement."),
            ("Find the measuring mistake", "A student says a ribbon is 7 cubes long, but the first cube starts 2 cm before the ribbon. Explain and fix the error.", "Units must start at the ribbon endpoint; realign and recount (2 marks).", "Identifying endpoint misalignment."),
            ("Choose the better unit", "Would identical popsticks or mixed classroom objects better measure a long shelf? Choose and justify.", "Identical popsticks; they are uniform and can repeat end-to-end, giving a comparable count (3 marks).", "Selecting a practical uniform informal unit."),
            ("Read a fresh unit row", "A crayon is covered by 4 equal blocks with no gaps. Write the measurement correctly with a number and unit.", "4 blocks (1 mark).", "Reporting a measurement with its informal unit."),
            ("Match setups to validity", "Match these setups to fair or unfair: identical tiles touching; paperclips with gaps; large and small blocks mixed.", "Identical touching tiles ↔ fair; gaps ↔ unfair; mixed sizes ↔ unfair (1 mark each).", "Judging measurement setups."),
            ("Sequence a remeasurement", "A row overlaps. Order the repair: remove the row; align first unit; place equal units touching; recount.", "Remove row → align first unit → place equal touching units → recount (2 marks).", "Correcting overlap through a complete remeasurement."),
            ("Compare using one unit", "A marker is 5 cubes long and a glue stick is 7 cubes long using the same cubes. Which is longer and by how many units?", "Glue stick; 2 cubes longer (2 marks).", "Comparing measurements made with a common unit."),
            ("Demonstrate two unit choices", "Measure one object with equal cubes and then equal paperclips. Report both counts and explain why they may differ.", "Both methods are accurate; counts and units are reported; differing unit sizes explain different counts (3 marks).", "Comparing measurements made with different informal units."),
            ("Draw and diagnose", "Draw an unfair six-unit measurement containing one gap, then redraw it fairly.", "First drawing visibly has a gap; corrected row begins at the endpoint with six equal touching units (3 marks).", "Representing and repairing a measurement error."),
            ("Evaluate two answers", "Zac reports a mat is 10 units long but does not name the unit. Priya reports 14 equal blocks. Explain which answer is more useful and what Zac must add.", "Priya's answer identifies the unit; Zac must name and describe a uniform unit and valid placement (3 marks).", "Evaluating completeness of measurement reports."),
            ("Plan a fair class comparison", "Two groups will measure different tables. Write rules that let their results be compared fairly without rulers.", "Use the same-sized informal unit, align at endpoints, place end-to-end without gaps/overlaps, count and record unit name (4 marks).", "Planning consistent informal measurement across groups."),
        ],
    ),
    "AC9M1M03": bank(
        "AC9M1M03",
        "describe the duration and sequence of events using years, months, weeks, days and hours",
        [
            ("Key idea", "Sequence tells what happens first, next and last; duration tells how long an event lasts."),
            ("Method", "Choose a sensible unit: hours for part of a day, days for a week, weeks for longer plans, months and years for long periods."),
            ("Worked example", "A lesson from 9 am to 10 am lasts 1 hour. Monday to the next Monday is 1 week."),
            ("Visual model", "Use calendars, day strips, month wheels and simple timelines with movable event cards."),
            ("Common trap", "A start or finish time is not the duration; duration is the amount of time between them."),
        ],
        [
            ("Choose a time unit", "Would the length of a school day be best described in hours, months or years?", "Hours (1 mark).", "Selecting a sensible duration unit."),
            ("Match events and units", "Match a birthday-to-birthday, a school term and a night's sleep to year, months and hours.", "Birthday-to-birthday ↔ year; school term ↔ months; sleep ↔ hours (1 mark each).", "Connecting familiar durations with units."),
            ("Build a week", "Arrange day cards from Monday through Sunday and state how many days make the week.", "Correct Monday–Sunday order and 7 days (2 marks).", "Sequencing days and naming week length."),
            ("Find a one-hour duration", "Art begins at 1 pm and ends at 2 pm. How long does it last?", "1 hour (1 mark).", "Calculating a whole-hour duration."),
            ("Order a morning routine", "Order: arrive at school, wake up, eat breakfast, begin class.", "Wake up → eat breakfast → arrive at school → begin class (1 mark).", "Sequencing familiar daily events."),
            ("Draw a three-day plan", "Draw three boxes labelled Tuesday, Wednesday and Thursday. Place library on Wednesday and show the day before and after.", "Tuesday before, Wednesday library, Thursday after (2 marks).", "Representing neighbouring days on a timeline."),
            ("Distinguish date and duration", "A camp starts on Monday and lasts 3 days. Explain why ‘Monday’ is not its duration.", "Monday names the start day; 3 days tells how long the camp lasts (2 marks).", "Separating temporal position from duration."),
            ("Choose units for four events", "Choose hours, days, months or years for a movie, a cold, a season and time at primary school. Explain each choice briefly.", "Movie-hours; cold-days; season-months; primary school-years, with sensible reasoning (4 marks).", "Applying time units across different scales."),
            ("Name the next month", "What month comes after September, and what month comes before it?", "October comes after; August comes before (2 marks).", "Using the sequence of months."),
            ("Match calendar intervals", "Match 14 days, 12 months and 24 hours to 2 weeks, 1 year and 1 day.", "14 days ↔ 2 weeks; 12 months ↔ 1 year; 24 hours ↔ 1 day (1 mark each).", "Relating common calendar units."),
            ("Order a year sequence", "Put March, January, April and February in calendar order.", "January, February, March, April (1 mark).", "Sequencing named months."),
            ("Work out elapsed hours", "A visit begins at 10 am and ends at 1 pm. Count the whole hours of duration.", "3 hours: 10–11, 11–12 and 12–1 (2 marks).", "Counting whole-hour intervals."),
            ("Demonstrate calendar movement", "On a calendar, start at Thursday and move forward 5 days. Name the landing day.", "Tuesday, counting Friday 1 through Tuesday 5 (2 marks).", "Moving forward through the repeating week."),
            ("Draw a simple timeline", "Draw a timeline for planting a seed, seeing a sprout one week later and seeing a taller plant one month later.", "Events are in chronological order with one week and one month intervals labelled (3 marks).", "Representing event sequence and duration."),
            ("Correct a duration claim", "A student says a weekend lasts 2 months because Saturday and Sunday are two names. Explain the error.", "Names do not determine units; Saturday and Sunday are 2 days, not months (3 marks).", "Reasoning about quantity and time units."),
            ("Plan and justify a time record", "Choose a suitable unit and simple recording method for a one-hour sport lesson, a two-week reading challenge and a year of birthdays.", "Hours/timeline for lesson; days or weeks/calendar for challenge; months/year calendar for birthdays, with reasons (4 marks).", "Selecting units and representations for varied durations."),
        ],
    ),
    "AC9M1SP01": bank(
        "AC9M1SP01",
        "make, compare and classify familiar shapes; recognise familiar shapes and objects in the environment, identifying the similarities and differences between them",
        [
            ("Key idea", "Shapes are classified by features such as straight or curved edges, corners, flat faces and curved surfaces."),
            ("Method", "Look at the features, not colour, size or which way the shape is turned; use the same feature to compare."),
            ("Worked example", "A small tilted square and a large upright square are both squares because each has 4 equal sides and 4 corners."),
            ("Visual model", "Use sortable shape cards and solid objects with written labels, outlines and touch-friendly rotation."),
            ("Common trap", "Turning a shape does not change its name or features."),
        ],
        [
            ("Name by features", "A flat shape has 3 straight sides and 3 corners. Name it.", "Triangle (1 mark).", "Recognising a triangle from defining features."),
            ("Match objects and shapes", "Match clock face, book cover and party hat to circle, rectangle and cone.", "Clock face ↔ circle; book cover ↔ rectangle; party hat ↔ cone (1 mark each).", "Recognising shapes in familiar objects."),
            ("Sort shape cards", "Sort the provided circles, triangles, squares and rectangles by shape, ignoring colour and size.", "All cards are grouped by defining shape, including rotated examples (3 marks).", "Classifying familiar 2D shapes."),
            ("Compare square and rectangle", "State one similarity and one difference between a square and a non-square rectangle.", "Both have 4 straight sides/4 corners; a square has all sides equal while the shown rectangle does not (2 marks).", "Comparing features of quadrilaterals informally."),
            ("Order a construction", "Order the steps to make a triangle from sticks: join final ends; choose 3 sticks; place them so each touches two others; check 3 corners.", "Choose 3 sticks → arrange contacts → join final ends → check 3 corners (2 marks).", "Sequencing construction of a familiar shape."),
            ("Draw rotated shapes", "Draw two triangles pointing in different directions and label the shared features.", "Both drawings have 3 straight sides and 3 corners, regardless of orientation (3 marks).", "Recognising shape invariance under rotation."),
            ("Find the odd object", "A ball, an orange and a box are grouped together as objects that roll easily. Which object does not fit best, and why?", "Box; its flat faces make it slide/stack rather than roll easily like the curved ball/orange (2 marks).", "Classifying objects by surface features."),
            ("Create a two-rule sort", "Sort a set of familiar shapes first by curved/straight boundaries and then by number of corners. Explain where one shape belongs.", "Applies both stated rules accurately and justifies one placement using visible features (4 marks).", "Creating and explaining classifications."),
            ("Identify a solid", "An object has two flat circular faces and one curved surface. Name the familiar solid.", "Cylinder (1 mark).", "Recognising a cylinder from surface features."),
            ("Match solids and properties", "Match cube, sphere and cylinder to only flat faces; only a curved surface; flat circular faces plus a curved surface.", "Cube ↔ only flat faces; sphere ↔ only curved surface; cylinder ↔ flat circles plus curved surface (1 mark each).", "Connecting familiar solids with properties."),
            ("Sequence shape clues", "Order these clues from least to most specific for a square: flat shape; has straight sides; has 4 sides; has 4 equal sides.", "Flat → straight sides → 4 sides → 4 equal sides (2 marks).", "Using increasingly specific classification features."),
            ("Classify an environment object", "A window is tall and rectangular. Explain why its size does not affect its shape classification.", "Classification uses side/corner features; being tall or large does not change the rectangle's 4 straight sides and corners (2 marks).", "Separating defining from non-defining attributes."),
            ("Build and compare solids", "Use modelling material to make a ball-like object and a box-like object. Demonstrate one movement difference.", "Makes curved and flat-faced forms; shows curved form rolls while flat-faced form can slide/stack (3 marks).", "Comparing solid objects through construction and movement."),
            ("Draw a shape hunt", "Draw and label one circle, rectangle and cylinder found in a classroom or home.", "Three reasonable objects are drawn and correctly linked to the named shapes (3 marks).", "Recognising familiar shapes in the environment."),
            ("Audit a colour sort", "A student puts all red shapes together and calls the group ‘triangles’. Explain why the rule is unreliable and give a better rule.", "Colour does not prove shape; sort by 3 sides and 3 corners to identify triangles (3 marks).", "Evaluating a non-defining classification rule."),
            ("Compare four objects", "Compare a can, ball, cereal box and coin. Group them in two useful ways and state the feature used each time.", "Two valid classifications, such as rolls/does not roll and circular face/no circular face, with every placement justified (4 marks).", "Applying multiple classification rules to familiar objects."),
        ],
    ),
    "AC9M1SP02": bank(
        "AC9M1SP02",
        "give and follow directions to move people and objects to different locations within a space",
        [
            ("Key idea", "Directions describe movement using a clear start, distance or steps, turn and destination."),
            ("Method", "Face the stated direction, follow one instruction at a time, and use landmarks to check position."),
            ("Worked example", "From the door, move 3 steps forward, turn right and move 2 steps to reach the bookshelf."),
            ("Visual model", "Use floor grids, arrows, maps and movable character tokens with spoken and keyboard alternatives."),
            ("Common trap", "Left and right depend on the mover's facing direction, so always state or show which way they face."),
        ],
        [
            ("Follow one move", "A robot faces north. It moves 2 squares forward. Describe its movement and final relative position.", "Moves 2 squares north/forward from its start (1 mark).", "Following a simple directional instruction."),
            ("Match direction words", "Match forward, turn left and behind to straight ahead, rotate to the left side and at the back of.", "Each term matches its stated spatial meaning (1 mark each).", "Understanding common direction and location language."),
            ("Walk a route", "From a marked start, take 3 steps forward, turn left and take 1 step. State the landmark reached.", "Follows the route accurately and names the marked destination (2 marks).", "Demonstrating a multi-step route."),
            ("Complete an instruction", "A toy is one square right of the start. Write one clear direction to reach it.", "Move 1 square right, with the starting facing direction clear if needed (1 mark).", "Giving a direct movement instruction."),
            ("Order route cards", "Order these cards: reach the tree; move 2 steps; face the tree; stop and check.", "Face tree → move 2 steps → reach tree → stop/check (2 marks).", "Sequencing route instructions."),
            ("Draw arrows to a goal", "On a 4-by-4 grid, draw a route from the bottom-left square to the square 2 up and 1 right.", "Route has two upward moves and one right move in any valid order and reaches the target (2 marks).", "Representing movement on a grid."),
            ("Explain a left-right change", "Kai faces the board, then turns around. Explain why the window that was on his left is now on his right.", "Turning changes Kai's facing direction, so his body-relative left/right reverse (2 marks).", "Reasoning about orientation and relative direction."),
            ("Write an unambiguous route", "Write directions from the classroom door to a desk using a start, at least one turn, a step count and a landmark check.", "Includes all four features in a route that can be followed without guessing (4 marks).", "Creating precise multi-step directions."),
            ("Locate from clues", "The lunchbox is under the table and to the left of the chair. Describe its position using both clues.", "Under the table and left of the chair (2 marks).", "Combining relative-location descriptions."),
            ("Match arrows and words", "Match ↑, → and ↶ to forward/up, right and turn left.", "↑ ↔ forward/up on the map; → ↔ right; ↶ ↔ turn left (1 mark each).", "Connecting direction symbols and words."),
            ("Sequence a map journey", "Order: turn right at the gate; start at the house; walk to the gate; finish at the pond.", "Start at house → walk to gate → turn right → finish at pond (2 marks).", "Ordering directions from a stated start."),
            ("Find a missing move", "A token moves 2 squares up from the start. The goal is the square immediately to its right. State the missing move.", "Move 1 square right (1 mark).", "Completing a route from relative-location information."),
            ("Demonstrate opposite turns", "Face forward, turn left, return to the start direction, then turn right. Show the two final facing directions.", "Accurately demonstrates left and right as opposite quarter-turn directions (2 marks).", "Demonstrating turns from a common orientation."),
            ("Draw two valid paths", "Draw two different routes from the top-left to bottom-right of a 3-by-3 grid without leaving the grid.", "Both routes begin/end correctly, remain inside the grid and use clear arrows (3 marks).", "Creating alternative routes to one destination."),
            ("Repair vague directions", "A note says ‘Go over there, then turn.’ Explain two details it needs before someone can follow it.", "Needs a clear start/facing direction and destination, distance/step count, turn direction or landmark; any two explained (3 marks).", "Evaluating clarity of movement instructions."),
            ("Compare two routes", "Route A uses 3 steps right then 2 down. Route B uses 2 down then 3 right. Explain when they reach the same place and what could make one safer.", "On an open grid they have the same displacement/end; obstacles or crossings can make one route safer, with a relevant example (4 marks).", "Comparing routes using destination and constraints."),
        ],
    ),
    "AC9M1ST01": bank(
        "AC9M1ST01",
        "acquire and record data for categorical variables in various ways including using digital tools, objects, images, drawings, lists, tally marks and symbols",
        [
            ("Key idea", "Categorical data sorts answers into named groups, such as favourite fruit or travel-to-school type."),
            ("Method", "Ask one clear question, use categories that do not overlap, record one response per person, then check the total."),
            ("Worked example", "For pet type, three dog responses are recorded as |||. Each tally stands for one response."),
            ("Visual model", "Use labelled sorting hoops, picture cards, lists and tally tables with text labels as well as images."),
            ("Common trap", "Do not record the same response twice or leave a response between unclear categories."),
        ],
        [
            ("Name the category variable", "In the question ‘How do you travel to school?’, what is being sorted into categories?", "Method of travel to school (1 mark).", "Identifying a categorical variable."),
            ("Match recording methods", "Match tally table, picture sort and list to marks in columns, objects under labels and written category names.", "Tally ↔ marks in columns; picture sort ↔ objects under labels; list ↔ written names (1 mark each).", "Recognising data-recording formats."),
            ("Collect a small set", "Ask 5 people to choose apple or banana and record exactly one response for each person.", "Clear question, 5 single responses and total record count of 5 (3 marks).", "Acquiring and recording categorical data."),
            ("Read tally marks", "A tally table shows cats |||| and dogs |||. State both frequencies and the total responses.", "Cats 4, dogs 3, total 7 (3 marks).", "Interpreting simple tally records."),
            ("Order a data collection", "Order: check total responses; ask the question; record one mark; choose clear categories.", "Choose categories → ask question → record one mark → check total (2 marks).", "Sequencing a reliable data-collection process."),
            ("Draw a sorting record", "Draw labelled groups for red, blue and green counters and record 2 red, 3 blue and 1 green.", "Correct labels and one visible record for each of the 6 counters (3 marks).", "Representing categorical data with objects or drawings."),
            ("Fix overlapping categories", "A lunch survey uses ‘fruit’, ‘apple’ and ‘sandwich’. Explain the problem and suggest clearer categories.", "Apple overlaps fruit; proposes non-overlapping groups such as apple/banana/other fruit/sandwich (3 marks).", "Evaluating category clarity."),
            ("Plan an inclusive class question", "Write a question with 3 or 4 clear categories about a class topic and explain how every student gets recorded once.", "Question is answerable, categories are mutually exclusive or include other, and method records one mark per student (4 marks).", "Designing a categorical data collection."),
            ("Record weather categories", "For five days the weather is sunny, cloudy, sunny, rainy, cloudy. Write a tally or frequency list.", "Sunny 2, cloudy 2, rainy 1 (3 marks).", "Converting observations to categorical frequencies."),
            ("Match data to labels", "Match bus, walk and car responses—bus, car, walk, walk, car—to frequencies 1, 2 and 2.", "Bus ↔ 1; walk ↔ 2; car ↔ 2 (1 mark each).", "Counting categorical responses accurately."),
            ("Sequence digital entry", "Order: select the correct category; submit one response; read the survey question; check confirmation.", "Read question → select category → submit once → check confirmation (2 marks).", "Following a digital categorical-data process."),
            ("Check a missing record", "Eight students answered, but a tally table contains only 7 marks. What does this tell you and what should happen next?", "One response is missing or count is wrong; recount records and check the respondent list without guessing an answer (2 marks).", "Auditing completeness of collected data."),
            ("Demonstrate a picture sort", "Sort 10 provided animal cards into bird, mammal and insect and record category totals.", "Each card appears once in a suitable labelled category and totals sum to 10 (3 marks).", "Sorting and recording categorical observations."),
            ("Draw a tally table", "Create a tally table for book choices: story 4, facts 3, poetry 2. Include headings and totals.", "Three labelled rows with accurate tallies/frequencies and total 9 (4 marks).", "Constructing a categorical tally record."),
            ("Detect double counting", "A student places one scooter picture under both ‘wheels’ and ‘ride to school’ in a single-choice survey. Explain why the total becomes unreliable.", "One response is counted twice and categories use different rules; use one variable and one placement per item (3 marks).", "Reasoning about one-response-per-case rules."),
            ("Compare two recording plans", "For 25 lunch choices, compare remembering answers, writing a list and using tally marks. Choose the most reliable plan and justify.", "Tally/list creates a permanent one-per-response record; memory alone is unreliable; choice is justified with counting/checking benefits (4 marks).", "Evaluating data-recording methods."),
        ],
    ),
    "AC9M1ST02": bank(
        "AC9M1ST02",
        "represent collected data for a categorical variable using one-to-one displays and digital tools where appropriate; compare the data using frequencies and discuss the findings",
        [
            ("Key idea", "In a one-to-one display, each picture, object or mark represents exactly one response."),
            ("Method", "Label categories, place one symbol per response, align symbols so counts are easy, then compare frequencies."),
            ("Worked example", "If dog has 4 paw symbols and cat has 2, dog has 2 more responses because 4 − 2 = 2."),
            ("Visual model", "Use aligned object graphs and picture graphs with a clear key stating one symbol = one response."),
            ("Common trap", "Count symbols, not their size; every category must use the same one-to-one rule."),
        ],
        [
            ("Read one-to-one symbols", "A display has 5 apple pictures in the apple row. If one picture means one vote, how many votes are there?", "5 votes (1 mark).", "Reading a one-to-one frequency."),
            ("Match comparisons", "Match cat 3/dog 6, red 4/blue 4 and bus 2/walk 5 to dog has 3 more, equal, and walk has 3 more.", "Cat/dog ↔ dog 3 more; red/blue ↔ equal; bus/walk ↔ walk 3 more (1 mark each).", "Comparing frequencies in one-to-one displays."),
            ("Build an object graph", "Use counters to show juice choices: orange 4, apple 2, water 5. Align one counter per vote.", "Correct labelled rows/columns with 4, 2 and 5 counters, one per response (3 marks).", "Constructing a one-to-one data display."),
            ("Find most and least", "A picture graph shows soccer 7, swimming 3 and cycling 5. Name the most and least frequent choices.", "Soccer most; swimming least (2 marks).", "Identifying extremes in categorical frequencies."),
            ("Order display steps", "Order: compare rows; label categories; place one symbol per response; check symbol total.", "Label → place symbols → check total → compare (2 marks).", "Sequencing construction and interpretation of a display."),
            ("Draw a one-to-one graph", "Draw a display for pets: none 2, dog 4, cat 3. Include a key.", "Accurate labelled categories, 2/4/3 symbols, key one symbol = one response (4 marks).", "Representing collected data visually."),
            ("Calculate a difference", "There are 8 sun symbols and 5 cloud symbols. How many more sunny days are shown?", "3 more sunny days; 8 − 5 = 3 (2 marks).", "Comparing category frequencies by difference."),
            ("Discuss what data supports", "A class graph shows blue 9 and green 6. Write one supported finding and one claim the graph cannot prove.", "Supported: blue has 3 more votes; unsupported example: everyone outside the class prefers blue (3 marks).", "Distinguishing evidence-based findings from overclaims."),
            ("Read a digital chart", "A digital one-to-one chart lists library visits: Monday 4, Tuesday 6, Wednesday 6. State the highest frequency and any tie.", "Highest is 6; Tuesday and Wednesday tie (2 marks).", "Interpreting frequencies and ties."),
            ("Match displays to totals", "Match rows with 2, 5 and 7 symbols to frequencies two, five and seven.", "Each row matches its symbol count (1 mark each).", "Connecting displayed symbols with numeric frequency."),
            ("Sequence categories by frequency", "Order book choices from least to greatest: adventure 6, humour 3, animals 5.", "Humour 3, animals 5, adventure 6 (2 marks).", "Ordering categories using frequencies."),
            ("Compare combined responses", "A display has 4 train, 3 bus and 2 walk choices. How many responses altogether, and how many more train than walk?", "9 total; train has 2 more than walk (3 marks).", "Finding totals and differences from a display."),
            ("Demonstrate a corrected graph", "A graph row has overlapping tokens that hide one vote. Rebuild it so every token can be counted.", "Places one visible token per response in an aligned row and preserves the original total (2 marks).", "Improving readability without changing data."),
            ("Draw from a tally table", "Tallies show mango 3, pear 1 and berry 4. Draw a one-to-one picture graph with a clear key.", "Correct 3/1/4 symbols, category labels and one-symbol-equals-one key (4 marks).", "Converting tally data to a one-to-one display."),
            ("Audit a misleading key", "One row uses each star as one vote, but another uses each star as two votes without saying so. Explain why the comparison is unfair and fix it.", "Rows use inconsistent meanings; choose one shared key and redraw/recalculate all categories (3 marks).", "Evaluating consistency of a display key."),
            ("Write a findings report", "For playground choices—slide 8, swings 5, climbing 5—state the total, most popular choice, tie and two valid comparisons.", "Total 18; slide most; swings/climbing tie; two accurate comparisons such as slide 3 more than either (5 marks).", "Summarising several evidence-based findings."),
        ],
    ),
}


def main() -> None:
    written = write_banks(SPECS)
    print(f"Wrote {len(written)} Year 1 Mathematics banks")


if __name__ == "__main__":
    main()
