"use strict";
const Q=(id,n,s,q,a,c,e)=>({id,curriculumCode:"AC9M10P02",bank:"test",section:s,sourceNumber:n,skill:s,printable:true,type:"single",question:q,answers:a,correct:c,explanation:e,structuredExplanation:{summary:e,hint:"Check whether the simulation matches the real experiment and whether conditioning changes the denominator."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q("ac9m10p02-t-001",25,"Conditional simulation","A simulation records 800 occasions where a previous spin was blue. The next spin is red on 248 of those occasions. Estimate P(red next | blue previous).",["0.248","0.31","0.40","0.62"],1,"248/800=0.31."),
Q("ac9m10p02-t-002",26,"Testing independence","A die simulation gives P(even)=0.50 and P(next even | current even)=0.498. What conclusion is most reasonable?",["No meaningful evidence of dependence","Strong positive dependence","Even rolls cause even rolls","The die cannot be fair"],0,"The conditional and overall probabilities are essentially the same."),
Q("ac9m10p02-t-003",27,"Testing independence","For a coin simulation, P(H)=0.50 and P(next H | current H)=0.49. Which interpretation is best?",["The results are consistent with independence","There is strong dependence","Heads causes tails","The simulation must be wrong"],0,"A difference of 0.01 is small and compatible with random variation."),
Q("ac9m10p02-t-004",28,"Replacement","A bag is sampled with replacement. A simulation gives P(red)=0.30 and P(next red | current red)=0.301. This most strongly suggests:",["The draws are behaving independently","The draws are dependent","Red causes red","Replacement makes red impossible"],0,"Replacement keeps probabilities unchanged between draws."),
Q("ac9m10p02-t-005",29,"Without replacement","A bag is sampled without replacement. P(red on first)=0.30 but P(red second | red first)=0.25. This indicates:",["Dependence","Independence","A guaranteed red second draw","No valid comparison"],0,"The first draw changes the composition of the bag."),
Q("ac9m10p02-t-006",30,"Simulation design","A student wants to compare sampling with and without replacement from a population of 1000 when taking samples of size 2. What is the best expectation?",["The difference between methods will usually be very small","The methods must give completely different results","Without replacement is impossible","With replacement always doubles probabilities"],0,"Removing one item from a population of 1000 changes probabilities only slightly."),
Q("ac9m10p02-t-007",31,"Simulation design","Which simulation best represents drawing two cards without replacement from a standard deck?",["Choose a random card, remove it, then choose from the remaining 51","Choose one random card twice from all 52 cards","Roll two dice","Generate two independent numbers from 1 to 52 and allow repeats"],0,"Without replacement, the second choice must exclude the first card."),
Q("ac9m10p02-t-008",32,"Simulation reliability","Two simulations estimate the same probability: 0.42 from 100 trials and 0.397 from 50,000 trials. Which should generally be trusted more as a long-run estimate?",["0.42 because it is larger","0.397 because it uses many more trials","Both are guaranteed exact","Neither can estimate probability"],1,"A much larger number of trials generally gives a more stable estimate."),
Q("ac9m10p02-t-009",33,"Counter-intuitive probability","A student simulates the three-door problem 20,000 times. Staying wins about 33% and switching wins about 67%. Which conclusion is justified?",["Switching has a higher long-run success rate in the model","Each individual switch is guaranteed to win","The result proves all game-show hosts behave identically","Staying and switching are equally likely"],0,"The simulation supports switching as the better strategy under the model assumptions."),
Q("ac9m10p02-t-010",34,"Birthday simulation","A birthday simulation gives a shared-birthday rate of about 0.51 for groups of 23. What does 0.51 mean?",["About 51% of simulated 23-person groups had at least one matching birthday","51% of people share one specific birthday","Exactly 51 pairs match in every class","The chance of a birthday is 0.51"],0,"The event is at least one shared birthday within the whole group."),
Q("ac9m10p02-t-011",35,"Model validation","A spinner actually has sectors covering 50%, 30% and 20% of its area. A student simulates the three colours as equally likely. What is the main problem?",["The digital model does not match the spinner probabilities","The trial count is automatically too large","Equal probabilities always improve accuracy","A spinner cannot be simulated digitally"],0,"A valid simulation must reproduce the chance mechanism's probabilities."),
Q("ac9m10p02-t-012",36,"Conditional probability","A simulation records 600 trials where event B occurred, and A occurred in 270 of those trials. Which value estimates P(A|B)?",["0.27","0.45","0.60","0.90"],1,"270/600=0.45."),
Q("ac9m10p02-t-013",37,"Decision-making","A retailer simulates daily demand 100,000 times for different stock levels. Which output is most useful for choosing stock?",["The estimated probability of running out and the cost of excess stock","One randomly selected simulated day","The largest random number generated","Only the average customer age"],0,"Decision simulations should compare relevant risks and costs across choices."),
Q("ac9m10p02-t-014",38,"Risk simulation","An insurance simulation predicts losses using historical claim rates, but climate conditions have changed substantially. What is the best evaluation?",["The model assumptions may be outdated, so results need review","The simulation remains exact because it uses many trials","More trials automatically fix outdated probabilities","Historical probabilities can never change"],0,"More simulation runs cannot correct unrealistic input assumptions."),
Q("ac9m10p02-t-015",39,"Comparing methods","From a bag of 100 marbles, 30 are red. Compare P(red second | red first) with and without replacement.",["With replacement: 0.30; without replacement: 29/99","With replacement: 29/99; without replacement: 0.30","Both are exactly 0.30","Both are 29/99"],0,"Replacement restores 30/100; without replacement leaves 29 red among 99."),
Q("ac9m10p02-t-016",40,"Simulation conclusions","A simulation estimate changes from 0.61 after 100 trials to 0.58 after 10,000 trials. Which statement is best?",["Simulation estimates can fluctuate; the larger run is usually more stable","The probability definitely decreased over time","The first result must have been fraudulent","A simulation should always give the same proportion"],0,"Random variation causes estimates to fluctuate, especially with fewer trials.")];
window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
