export const test=[
['Wet sand holds a castle shape better than dry sand. Which question best follows?',['Does water amount affect how well sand holds shape?','Which castle is prettiest?','Why is the beach fun?','Are buckets useful?'],0,'It tests the observed relationship.','Make it measurable.'],
['Grass was wet after four dewy mornings. Which prediction is careful?',['It may be wet after another dewy morning.','It must be wet forever.','Dew makes all grass identical.','Exactly four patches will be wet.'],0,'The pattern supports “may”, not certainty.','Avoid must.'],
['Which question is most measurable?',['Does string length affect pendulum swing time?','Which pendulum looks best?','Is swinging exciting?','Why is string useful?'],0,'Both variables can be measured.','Choose measurable factors.'],
['More-layer paper towels absorbed more water in three trials. Which prediction follows?',['A towel with more layers may absorb more in another similar test.','More layers always absorb every drop.','The thickest is best for every job.','Paper towels choose water.'],0,'It extends the pattern cautiously.','May, not always.'],
['Why is “Which bridge is best?” weak?',['“Best” does not name a measurable property.','Bridges cannot be tested.','Questions cannot use which.','Bridge is too technical.'],0,'A criterion such as load held must be defined.','Best at what?'],
['A magnet attracted steel clips before. What supports predicting it will attract another steel clip?',['Relevant previous observations','Liking magnets','The clip being shiny','Writing the prediction first'],0,'Past relevant evidence supports the expectation.','Use evidence.'],
['One shaded plant grew slowly. Which claim is too strong?',['Plants in shade always grow slowly.','This plant grew slowly in shade.','We could test more plants.','This suggests a light-growth question.'],0,'One observation cannot justify a universal claim.','One result ≠ always.'],
['Which statement reports a measured result rather than a prediction?',['Water cooled from 50°C to 38°C.','Water may cool faster outside.','Metal may cool it faster.','The next test should differ.'],0,'The temperature change reports measured evidence.','Choose what has already been measured.'],
['Snails are often found in damp spots. Which question is strongest?',['Does soil moisture affect where snails are found?','Which snail is cutest?','Why is mud messy?','Are gardens fun?'],0,'It tests the observed moisture-location relationship.','Turn pattern into question.'],
['A ball bounced higher on tile than carpet in several trials. Which prediction fits?',['It may bounce higher on tile again.','Tile always makes every object bounce highest.','Carpet stops all motion.','The next bounce must be identical.'],0,'The prediction uses the pattern cautiously.','Use may.'],
['Four rocks are being compared. Which question asks for an opinion rather than measurable evidence?',['Which rock is nicest?','Which rock has greatest mass?','Which is longest?','Which absorbs most water?'],0,'“Nicest” is personal preference.','Can it be measured objectively?'],
['A prediction is not supported. What should happen?',['Keep the evidence and revise the idea if needed.','Erase the result.','Change the prediction after seeing data and pretend it was original.','Stop doing science.'],0,'Unexpected evidence helps improve thinking.','Evidence first.'],
['Three darker surfaces warmed more than lighter ones. Which new question is useful?',['Does surface colour affect temperature increase in sunlight?','Which colour is most fashionable?','Why is light pretty?','Who likes black?'],0,'It tests the observed colour-temperature relationship.','Ask about the pattern.'],
['Which statement is most cautious?',['Our results suggest the rough surface may slow the car.','The rough surface always stops every car.','Roughness is the only factor that matters.','The result can never change.'],0,'“Suggest” and “may” match limited evidence.','Match certainty to evidence.'],
['What makes a relationship question useful?',['It links factors that can be observed or measured.','It guarantees a cause.','It must have one-word answers.','It should ask for a favourite.'],0,'Measurable relationships can be investigated scientifically.','Observable factors.'],
['Which sequence is best?',['Observe → question → predict → test → compare evidence','Predict → change data → conclude','Vote → guess → stop','Choose answer → ignore results'],0,'Inquiry builds from observations to evidence.','Follow the scientific process.']
];