"use strict";
window.skillrTestQuestions = [
  {
    "id": "ac9m8m03-t-001",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 25,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A circle has diameter 12 cm. What is its circumference?",
    "audioPrompt": "A circle has diameter 12 cm. What is its circumference?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["6π cm","12π cm","24π cm","36π cm"],
    "correct": 1,
    "explanation": "Circumference can be found from diameter using C = πd = 12π cm.",
    "structuredExplanation": {"summary":"Circumference can be found from diameter using C = πd = 12π cm.","hint":"Use C = πd or C = 2πr."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-002",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 26,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A circle has diameter 16 cm. What is its area?",
    "audioPrompt": "A circle has diameter 16 cm. What is its area?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["64π cm²","32π cm²","16π cm²","8π cm²"],
    "correct": 0,
    "explanation": "The radius is 8 cm, so A = π × 8² = 64π cm².",
    "structuredExplanation": {"summary":"The radius is 8 cm, so A = π × 8² = 64π cm².","hint":"Halve the diameter first."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-003",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 27,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "Area = 49π cm². What is the radius?",
    "audioPrompt": "Area = 49π cm². What is the radius?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["7 cm","14 cm","49 cm","3.5 cm"],
    "correct": 0,
    "explanation": "Since A = πr², r² = 49 and r = 7 cm.",
    "structuredExplanation": {"summary":"Since A = πr², r² = 49 and r = 7 cm.","hint":"Remove π, then square-root."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-004",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 28,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "Area = 100π cm². What is the diameter?",
    "audioPrompt": "Area = 100π cm². What is the diameter?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["10 cm","20 cm","25 cm","50 cm"],
    "correct": 1,
    "explanation": "r² = 100, so r = 10 cm and diameter = 20 cm.",
    "structuredExplanation": {"summary":"r² = 100, so r = 10 cm and diameter = 20 cm.","hint":"Find radius first, then double it."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-005",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 29,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "Area = 25π cm². What is the circumference?",
    "audioPrompt": "Area = 25π cm². What is the circumference?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["5π cm","10π cm","15π cm","20π cm"],
    "correct": 1,
    "explanation": "r² = 25, so r = 5. Then C = 2πr = 10π cm.",
    "structuredExplanation": {"summary":"r² = 25, so r = 5. Then C = 2πr = 10π cm.","hint":"Use area to find radius before circumference."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-006",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 30,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A round table has radius 0.8 m. How much material is needed to edge it?",
    "audioPrompt": "A round table has radius 0.8 m. How much material is needed to edge it?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["0.8π m","1.6π m","3.2π m","6.4π m"],
    "correct": 1,
    "explanation": "Edging means circumference: C = 2πr = 2π × 0.8 = 1.6π m.",
    "structuredExplanation": {"summary":"Edging means circumference: C = 2πr = 2π × 0.8 = 1.6π m.","hint":"Edging uses circumference, not area."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-007",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 31,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A circular garden has diameter 4 m. What is its area?",
    "audioPrompt": "A circular garden has diameter 4 m. What is its area?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["4π m²","8π m²","16π m²","2π m²"],
    "correct": 0,
    "explanation": "Radius is 2 m, so A = π × 2² = 4π m².",
    "structuredExplanation": {"summary":"Radius is 2 m, so A = π × 2² = 4π m².","hint":"Use radius in the area formula."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-008",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 32,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A wheel has radius 0.3 m. What is its circumference?",
    "audioPrompt": "A wheel has radius 0.3 m. What is its circumference?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["0.3π m","0.6π m","1.2π m","3π m"],
    "correct": 1,
    "explanation": "C = 2πr = 2π × 0.3 = 0.6π m.",
    "structuredExplanation": {"summary":"C = 2πr = 2π × 0.3 = 0.6π m.","hint":"Circumference is distance around the wheel."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-009",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 33,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "Circumference = 40π cm. What is the radius?",
    "audioPrompt": "Circumference = 40π cm. What is the radius?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["20 cm","40 cm","10 cm","5 cm"],
    "correct": 0,
    "explanation": "C = 2πr, so 40π = 2πr and r = 20 cm.",
    "structuredExplanation": {"summary":"C = 2πr, so 40π = 2πr and r = 20 cm.","hint":"Divide circumference by 2π."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-010",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 34,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "Circumference = 18π cm. What is the diameter?",
    "audioPrompt": "Circumference = 18π cm. What is the diameter?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["9 cm","18 cm","27 cm","36 cm"],
    "correct": 1,
    "explanation": "C = πd, so 18π = πd and d = 18 cm.",
    "structuredExplanation": {"summary":"C = πd, so 18π = πd and d = 18 cm.","hint":"Use C = πd."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-011",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E3 — applying circle formulas",
    "sourceNumber": 35,
    "skill": "E3 — applying circle formulas",
    "printable": true,
    "type": "single",
    "question": "A circular mat has radius 1.2 m. What is its area?",
    "audioPrompt": "A circular mat has radius 1.2 m. What is its area?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["1.44π m²","2.88π m²","3.6π m²","5π m²"],
    "correct": 0,
    "explanation": "A = πr² = π × 1.2² = 1.44π m².",
    "structuredExplanation": {"summary":"A = πr² = π × 1.2² = 1.44π m².","hint":"Square 1.2 before multiplying by π."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-012",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E4 — First Nations weaving and circles",
    "sourceNumber": 36,
    "skill": "E4 — First Nations weaving and circles",
    "printable": true,
    "type": "single",
    "question": "In many First Nations weaving traditions, circles can represent:",
    "audioPrompt": "In many First Nations weaving traditions, circles can represent:",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["Random decoration","Cycles of life and connection","Only mathematical puzzles","Weather patterns only"],
    "correct": 1,
    "explanation": "Circles are often connected with cycles, continuity, gathering and relationship. This should be taught respectfully and locally, not as a single meaning for all groups.",
    "structuredExplanation": {"summary":"Circles are often connected with cycles, continuity, gathering and relationship. This should be taught respectfully and locally, not as a single meaning for all groups.","hint":"Avoid treating one meaning as universal across all First Nations groups."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-013",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E4 — First Nations weaving and circles",
    "sourceNumber": 37,
    "skill": "E4 — First Nations weaving and circles",
    "printable": true,
    "type": "single",
    "question": "Circular weaving patterns often rely on understanding:",
    "audioPrompt": "Circular weaving patterns often rely on understanding:",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["Triangles only","Squares only","Radial symmetry","Cubes"],
    "correct": 2,
    "explanation": "Circular designs often repeat around a centre, which is radial symmetry.",
    "structuredExplanation": {"summary":"Circular designs often repeat around a centre, which is radial symmetry.","hint":"Look for repeating structure around a centre point."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-014",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E4 — First Nations weaving and circles",
    "sourceNumber": 38,
    "skill": "E4 — First Nations weaving and circles",
    "printable": true,
    "type": "single",
    "question": "To plan a circular woven mat, which measurement is most important for circle calculations?",
    "audioPrompt": "To plan a circular woven mat, which measurement is most important for circle calculations?",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["Radius","Height","Weight","Temperature"],
    "correct": 0,
    "explanation": "Radius helps calculate both circumference and area.",
    "structuredExplanation": {"summary":"Radius helps calculate both circumference and area.","hint":"Radius is used in A = πr² and C = 2πr."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-015",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E4 — First Nations weaving and circles",
    "sourceNumber": 39,
    "skill": "E4 — First Nations weaving and circles",
    "printable": true,
    "type": "single",
    "question": "Knowing the area of a circular mat can help estimate:",
    "audioPrompt": "Knowing the area of a circular mat can help estimate:",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["Colour","Amount of weaving material","Temperature","Time of day"],
    "correct": 1,
    "explanation": "Area is linked to how much surface must be covered, so it can help estimate material needed.",
    "structuredExplanation": {"summary":"Area is linked to how much surface must be covered, so it can help estimate material needed.","hint":"Area measures the surface covered."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m8m03-t-016",
    "curriculumCode": "AC9M8M03",
    "bank": "test",
    "section": "E4 — First Nations weaving and circles",
    "sourceNumber": 40,
    "skill": "E4 — First Nations weaving and circles",
    "printable": true,
    "type": "single",
    "question": "Circular weaving designs are often discussed in relation to:",
    "audioPrompt": "Circular weaving designs are often discussed in relation to:",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {"type":"none","alt_text":""},
    "answers": ["Isolation and disconnection","Community, continuity and connection","Competition only","Randomness only"],
    "correct": 1,
    "explanation": "Circle motifs can be discussed in relation to community, continuity and connection while recognising that meanings vary across First Nations groups.",
    "structuredExplanation": {"summary":"Circle motifs can be discussed in relation to community, continuity and connection while recognising that meanings vary across First Nations groups.","hint":"Keep cultural interpretation respectful and non-universal."},
    "qualitySchema": "production-v1"
  }
];
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
