"use strict";
const rawTest = [
  [25,"difference one probability","What is P(|D1−D2|=1) for two fair six-sided dice?",["4/36","6/36","8/36","10/36"],3,"There are 10 ordered pairs with absolute difference 1."],
  [26,"difference two probability","What is P(|D1−D2|=2) for two fair six-sided dice?",["4/36","6/36","8/36","10/36"],2,"There are 8 ordered pairs with absolute difference 2."],
  [27,"difference three probability","What is P(|D1−D2|=3) for two fair six-sided dice?",["2/36","4/36","6/36","8/36"],2,"There are 6 ordered pairs with absolute difference 3."],
  [28,"difference four probability","What is P(|D1−D2|=4) for two fair six-sided dice?",["2/36","4/36","6/36","8/36"],1,"There are 4 ordered pairs with absolute difference 4."],
  [29,"complement long run","For an event A and its complement not A, what should their theoretical probabilities do?",["Sum to 0","Sum to 1","Be equal","Depend on sample size"],1,"Complementary events partition the sample space, so P(A)+P(not A)=1."],
  [30,"complement calculation","A simulation estimates P(A)=0.37. Using the complement rule, what estimate corresponds to not A?",["0.37","0.63","0.73","1.37"],1,"1−0.37=0.63."],
  [31,"rounded complement estimates","A report gives rounded simulation estimates P(A)=0.48 and P(not A)=0.51. What is the best response?",["Accept them as exact complements","Check rounding or calculation because they should total about 1","Conclude A and not A overlap","Conclude the events are independent"],1,"Complementary categories should account for the full sample space; a small discrepancy may arise from separate rounding or reporting and should be checked."],
  [32,"binary classification","Which situation is naturally represented by complementary categories?",["Spam vs not spam","Cat vs dog vs bird","Height prediction","Temperature measurement"],0,"Spam and not spam form two exhaustive, mutually exclusive categories."],
  [33,"die complement","For a fair six-sided die, P(6)=1/6. What is P(not 6)?",["1/6","1/3","1/2","5/6"],3,"The complement is 1−1/6=5/6≈0.833."],
  [34,"weather complement","A model assigns probability 0.28 to rain. If rain and no rain are the only outcomes, what probability must it assign to no rain?",["0.18","0.28","0.72","0.82"],2,"1−0.28=0.72."],
  [35,"simulation validation","A binary simulation records 3,742 successes and 6,258 failures in 10,000 trials. What check confirms the categories are complementary?",["The counts add to 10,000","The counts are equal","The success count is larger","Both probabilities are below 0.5"],0,"Complementary outcomes must partition all trials, so the two counts should total the number of trials."],
  [36,"invalid complement report","A report states P(A)=0.61 and P(not A)=0.33 as exact probabilities. What is wrong?",["Nothing","They sum to 0.94 instead of 1","Both are below 1","A complement must equal A"],1,"Exact complementary probabilities must sum to 1."],
  [37,"distribution categories","How do complementary events appear in a two-category frequency table?",["As overlapping categories","As two disjoint categories covering all outcomes","As identical categories","As categories that can both occur in one trial"],1,"A and not A are mutually exclusive and exhaustive."],
  [38,"binary probability sum","A normalized binary classifier reports P(spam)=0.64. What should P(not spam) be?",["0.36","0.64","1.64","Cannot be determined"],0,"For normalized complementary binary outputs, the probabilities sum to 1."],
  [39,"binary decision use","What can complementary probability estimates help a binary decision system do?",["Compare support for the two exhaustive outcomes","Guarantee the prediction is correct","Remove all uncertainty","Make the theoretical probabilities change"],0,"The estimates can inform a decision rule, but they do not guarantee correctness."],
  [40,"finite simulation variation","A 200-trial simulation gives an experimental P(A) different from the theoretical P(A). What is the most likely explanation if the simulation model is valid?",["Random sampling variation","Complementary events stopped summing to 1","Theoretical probability changes each run","Probability no longer applies"],0,"Finite simulations naturally vary around the theoretical probability."]
];
window.skillrTestQuestions = rawTest.map(([n,skill,question,answers,correct,explanation]) => ({
  id:`ac9m8p03-t-${String(n-24).padStart(3,"0")}`, curriculumCode:"AC9M8P03", bank:"test", section:n<=28?"E2":"E3", sourceNumber:n, skill, printable:true, type:"single", question, audioPrompt:question, visual:"", visualHtml:"", visualMeta:{type:"none",alt_text:""}, answers, correct, explanation, structuredExplanation:{summary:explanation,hint:"Use the full sample space, count favourable outcomes, and check complements sum to 1."}, qualitySchema:"production-v1"
}));
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
