"use strict";
const T=(id,skill,q,a,c,e,h)=>({id:`ac9e5le02-t-${String(id).padStart(3,"0")}`,curriculumCode:"AC9E5LE02",bank:"test",skill,printable:true,type:"single",question:q,audioPrompt:q,visual:"",visualHtml:"",answers:a,correct:c,explanation:`${e}\nHint: ${h}`,structuredExplanation:{summary:e,hint:h},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
T(1,"terminology","‘The river was a ribbon of glass’ is a…",["metaphor","simile","fact"],0,"The river is directly compared with a ribbon of glass.","No like/as."),
T(2,"terminology","‘The rain tapped impatiently on the roof’ uses…",["personification","literal measurement","plot"],0,"Rain is given a human-like manner.","Non-human + human quality."),
T(3,"effect","What does ‘His grin stretched a kilometre wide’ mainly do?",["Exaggerates happiness or excitement","Gives an exact measurement","Shows setting"],0,"The hyperbole intensifies emotion.","Do not read exaggeration literally."),
T(4,"effect","‘The hallway was a tunnel of whispers’ most likely creates…",["a secretive uneasy atmosphere","an exact engineering description","a cheerful crowd scene"],0,"The metaphor and sound image shape mood.","Translate the image into an effect."),
T(5,"point of view","Why can first-person narration affect reader response?",["Readers receive events through one character’s knowledge and attitudes.","It always makes the narrator correct.","It removes character perspective."],0,"Point of view filters information.","Ask what the narrator can know and notice."),
T(6,"opinion","Which is the strongest literary opinion?",["‘The ending is effective because the repeated image of the open gate shows the character’s new freedom.’","‘The ending is good.’","‘I liked it.’"],0,"It combines judgement, evidence and effect.","Opinion + evidence + explanation."),
T(7,"viewpoint reflection","Which response best reflects on another reader’s view?",["‘I understand why you read the silence as fear; I read it as relief because the character finally unclenches her hands.’","‘You are wrong.’","‘There is only one view.’"],0,"It acknowledges another reading and uses evidence for a response.","Respect + evidence."),
T(8,"evidence","Which evidence best supports the claim that a character is anxious?",["‘He checked the locked door three times and rubbed his palms together.’","‘He wore a blue shirt.’","‘The room had two chairs.’"],0,"Repeated checking and nervous movement support anxiety.","Choose behaviour tied to the claim."),
T(9,"analysis","Why is ‘There is a simile’ incomplete analysis?",["It names a device but does not explain meaning or effect.","Similes do not exist.","It is too long."],0,"Literary terminology should lead to interpretation.","Ask what it does."),
T(10,"structure","Which comment evaluates structure rather than merely summarising?",["‘Delaying the reveal until the final paragraph builds suspense.’","‘At the end we learn the truth.’","‘The story has paragraphs.’"],0,"It explains how organisation affects the reader.","Connect arrangement to effect."),
T(11,"tone","Which evidence best supports a humorous tone?",["A narrator uses playful exaggeration and unexpected comparisons.","The text has a title.","There are five paragraphs."],0,"Playful language can create humour.","Use actual language features."),
T(12,"viewpoint","Can two different literary interpretations both be reasonable?",["Yes, when each is supported by relevant textual evidence.","No, only one reader can ever be right.","Yes, even with no connection to the text."],0,"Interpretations can differ while remaining evidence-based.","Evidence constrains interpretation."),
T(13,"preference versus analysis","Which sentence separates preference from analysis?",["‘I prefer faster stories, but the detailed opening effectively builds an uneasy mood.’","‘Slow stories are bad.’","‘I dislike it, so it has no techniques.’"],0,"Personal taste and craft judgement can be distinguished.","Evaluate the text even when preference differs."),
T(14,"reflection","Why might hearing another reader’s viewpoint improve your response?",["It can make you notice evidence or interpretations you had overlooked.","It means you must abandon your own view.","It removes the need for evidence."],0,"Reflection can refine or qualify an interpretation.","Consider, then decide."),
T(15,"transfer","Which paragraph structure is strongest?",["Opinion → evidence/term → effect → other view → reasoned response","Plot summary → plot summary → plot summary","Device names with no explanation"],0,"It addresses the full descriptor.","Plan for analysis and reflection."),
T(16,"concept","Which statement best describes a strong literary response?",["It uses accurate literary terms, specific evidence and explanation, while considering other viewpoints.","It only says whether the reader liked the text.","It lists techniques without effects."],0,"Strong response combines terminology, evidence, effect and reflection.","Go beyond naming."),
];window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;