"use strict";
window.skillrTestQuestions = [
  {"id":"ac9m10a01-t-001","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":3,"skill":"Index laws and powers","printable":true,"type":"single","question":"Evaluate (2^3)^4.","answers":["2^7","2^12","8^3","2^1"],"correct":1,"explanation":"Use the power-of-a-power rule: multiply the indices, 3×4=12.","structuredExplanation":{"summary":"(2^3)^4 = 2^12.","hint":"Use (a^m)^n = a^(mn)."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-002","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":7,"skill":"Index laws and powers","printable":true,"type":"single","question":"Evaluate (2/3)^-2.","answers":["-4/9","9/4","4/9","-9/4"],"correct":1,"explanation":"A negative index takes the reciprocal, then square: (3/2)^2=9/4.","structuredExplanation":{"summary":"The value is 9/4.","hint":"Invert the fraction before applying the power."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-003","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":10,"skill":"Index laws and powers","printable":true,"type":"single","question":"Simplify x^(1/2) × x^(1/4).","answers":["x^(1/8)","x^(3/4)","x^(2/6)","x^2"],"correct":1,"explanation":"Add indices with the same base: 1/2 + 1/4 = 3/4.","structuredExplanation":{"summary":"The result is x^(3/4).","hint":"Use a common denominator before adding the fractional indices."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-004","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":14,"skill":"Index laws and powers","printable":true,"type":"single","question":"Which expression is equivalent to the 40th root of x^25?","answers":["x^(5/8)","x^(8/5)","x^5","x^8"],"correct":0,"explanation":"The expression is x^(25/40), which simplifies to x^(5/8).","structuredExplanation":{"summary":"The equivalent expression is x^(5/8).","hint":"Write the root as a fractional index and simplify the fraction."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-005","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":18,"skill":"Index laws and powers","printable":true,"type":"single","question":"Find x if 2^x = 1/16.","answers":["4","-4","8","-8"],"correct":1,"explanation":"Since 16=2^4, we have 1/16=2^-4, so x=-4.","structuredExplanation":{"summary":"x = -4.","hint":"Rewrite 1/16 as a power of 2."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-006","curriculumCode":"AC9M10A01","bank":"test","section":"Index laws and powers","sourceNumber":20,"skill":"Index laws and powers","printable":true,"type":"single","question":"Evaluate 25^(1/2) × 8^(1/3).","answers":["200","10","13","33"],"correct":1,"explanation":"√25=5 and the cube root of 8 is 2, so the product is 10.","structuredExplanation":{"summary":"The value is 10.","hint":"Interpret each fractional index as a root."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-007","curriculumCode":"AC9M10A01","bank":"test","section":"Expanding and simplifying","sourceNumber":24,"skill":"Expanding and simplifying","printable":true,"type":"single","question":"Expand (2x + 3)(2x − 3).","answers":["4x^2 − 9","4x^2 + 9","4x^2 − 12x − 9","2x^2 − 3"],"correct":0,"explanation":"This is a difference of squares: (2x)^2 − 3^2 = 4x^2 − 9.","structuredExplanation":{"summary":"The result is 4x^2 − 9.","hint":"Use (a+b)(a−b)=a^2−b^2."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-008","curriculumCode":"AC9M10A01","bank":"test","section":"Factorising","sourceNumber":27,"skill":"Factorising","printable":true,"type":"single","question":"Factorise x^2 − 49.","answers":["(x − 7)^2","(x + 7)(x − 7)","(x + 49)(x − 1)","Cannot be factorised"],"correct":1,"explanation":"49=7^2, so use the difference-of-squares rule.","structuredExplanation":{"summary":"x^2 − 49 = (x + 7)(x − 7).","hint":"Recognise a^2−b^2."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-009","curriculumCode":"AC9M10A01","bank":"test","section":"Algebraic fractions","sourceNumber":30,"skill":"Algebraic fractions","printable":true,"type":"single","question":"Simplify (x^2 − 9)/(x − 3), for x ≠ 3.","answers":["x − 3","x + 3","x + 9","3"],"correct":1,"explanation":"Factor the numerator as (x−3)(x+3), then cancel the common factor x−3.","structuredExplanation":{"summary":"The simplified expression is x + 3, with x ≠ 3.","hint":"Factorise the numerator first."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-010","curriculumCode":"AC9M10A01","bank":"test","section":"Factorising","sourceNumber":33,"skill":"Factorising","printable":true,"type":"single","question":"Factorise 3x^2 − 12 completely.","answers":["3(x^2 − 4)","3(x − 2)(x + 2)","(3x − 2)(x + 6)","3(x − 2)^2"],"correct":1,"explanation":"First factor out 3, then factor the difference of squares x^2−4.","structuredExplanation":{"summary":"The complete factorisation is 3(x − 2)(x + 2).","hint":"Use the HCF first, then difference of squares."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-011","curriculumCode":"AC9M10A01","bank":"test","section":"Algebraic fractions","sourceNumber":34,"skill":"Algebraic fractions","printable":true,"type":"single","question":"Simplify (36bq − 36b/q)/q, given q > 0.","answers":["36b(q − 1)/q","36b(q^2 − 1)/q^2","72b","72bq"],"correct":1,"explanation":"Combine the numerator over q, then divide by the outside q to obtain 36b(q^2−1)/q^2.","structuredExplanation":{"summary":"The simplified form is 36b(q^2 − 1)/q^2.","hint":"Write the numerator as a single fraction before dividing by q."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-012","curriculumCode":"AC9M10A01","bank":"test","section":"Expanding and simplifying","sourceNumber":38,"skill":"Expanding and simplifying","printable":true,"type":"single","question":"Expand and simplify (3x + 2)^2.","answers":["9x^2 + 4","9x^2 + 12x + 4","9x^2 + 6x + 4","6x^2 + 12x + 4"],"correct":1,"explanation":"Use (a+b)^2 = a^2+2ab+b^2 to get 9x^2+12x+4.","structuredExplanation":{"summary":"The result is 9x^2 + 12x + 4.","hint":"Include the middle term 2ab."},"qualitySchema":"production-v1"},
  {"id":"ac9m10a01-t-013","curriculumCode":"AC9M10A01","bank":"test","section":"Expanding and simplifying","sourceNumber":40,"skill":"Expanding and simplifying","printable":true,"type":"single","question":"Expand and simplify (x + 5)(x − 5) + 25.","answers":["x^2 + 50","x^2","x^2 − 50","x^2 + 10x"],"correct":1,"explanation":"(x+5)(x−5)=x^2−25, and adding 25 leaves x^2.","structuredExplanation":{"summary":"The result is x^2.","hint":"Use difference of squares first."},"qualitySchema":"production-v1"}
];
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
