"use strict";
const Q=[
["validity vs precision","An experiment gives nearly identical results on every repeat, but a faulty sensor is later found to read 8% high. Which evaluation is best?",["The measurements were repeatable but systematically biased, so consistency alone did not establish validity or accuracy","The results were valid because they were consistent","The sensor fault is random error","The 8% bias disappears when results are averaged"],0,"Repeatability can coexist with systematic error; consistent results are not necessarily accurate or valid.","Consistently wrong is possible."],
["unchecked variable","Light intensity is assumed constant, but the lamp flickers unpredictably during trials. What is the most defensible classification?",["An uncontrolled variable that can introduce additional variation and potentially confound the result","Automatically a fixed systematic error","Proof the hypothesis is false","A sampling bias only"],0,"A flickering lamp varies unpredictably; its effect is an uncontrolled source of variability rather than necessarily a constant directional bias.","Do not label every uncontrolled variable systematic."],
["parallax","A student reads an analogue scale from the same incorrect angle on every trial. What is the likely effect?",["A systematic viewing bias if the angle shifts readings consistently","Only random error because a human made it","No measurement effect","Larger sample size"],0,"A consistent viewing geometry can bias readings in one direction, making the error systematic.","Consistent parallax can create bias."],
["evidence conflict","Nine well-controlled studies find a small effect; one similarly strong study finds none. Which response is strongest?",["Evaluate all studies together, including effect sizes, uncertainty and methodological differences","Discard the one conflicting study","Conclude the effect is definitely false","Treat all ten studies as proving the same result"],0,"Conflicting evidence should be integrated and investigated rather than ignored or allowed to erase the full evidence base automatically.","Weigh the whole evidence base."],
["generalisation","A medicine trial includes only healthy adults aged 18–30. Which claim is least justified?",["The medicine has the same effectiveness and safety for children, older adults and people with major illnesses","The observed effect applies to the participants studied","Further demographic groups should be studied","The sample limits generalisation"],0,"Evidence from one demographic does not automatically generalise to populations with different physiology or health conditions.","Population scope matters."],
["strong trend faulty tool","A graph shows a strong linear trend, but the instrument calibration changed halfway through data collection. What should happen?",["Investigate the calibration change because part or all of the apparent trend may be measurement artefact","Accept the trend because it is visually strong","Average all values to remove the calibration problem","Delete only points that weaken the trend"],0,"A systematic change in measurement can create or distort a trend, so instrument history must be evaluated.","Strong-looking data can still be biased."],
["media causation","A news article reports 'Phone use causes condition X' from an observational study showing an association. What key question should be asked?",["Did the study design address confounding and provide evidence capable of supporting causation?","Was the headline written confidently?","Did most participants own phones?","Was the association positive rather than negative?"],0,"Observational association may reflect confounding or reverse causation; causal claims require appropriate evidence.","Check whether the design supports causation."],
["mean typicality","Values are 5, 6, 7, 8 and 74. The mean is 20. Which evaluation is best?",["The mean is mathematically correct but is a poor description of a typical observation because of the extreme value","The mean must be recalculated until it lies between 5 and 8","The dataset has no variation","The extreme value should automatically be deleted"],0,"An extreme value can pull the mean away from where most observations lie; another statistic plus spread may communicate the data better.","Correct statistic can still be misleading as a summary."],
["subset paradox","A treatment appears beneficial in each of two age groups separately, but the combined dataset appears worse for the treatment group. What is the best response?",["Investigate group sizes and confounding before interpreting the aggregate pattern","Ignore the subgroup results","Choose whichever result supports the hypothesis","Conclude arithmetic cannot be trusted"],0,"Aggregated data can obscure subgroup structure; differences in group composition can reverse apparent patterns.","Aggregation can hide confounding."],
["reproducibility","Two labs use nominally the same method but obtain different results. Which comparison is most useful?",["Calibration, sample characteristics, operational definitions, environmental conditions and analysis choices","Which laboratory has more followers","Which result is larger","Which team wrote the shorter report"],0,"Reproducibility failures can arise from hidden methodological differences that need systematic comparison.","Compare conditions and procedures."],
["uncertainty claim","A result estimate is 12% with a very wide uncertainty interval spanning effects close to zero. Which wording is strongest?",["The estimate suggests an effect, but its size is poorly constrained and weak/no effect may remain compatible with the data","The effect is exactly 12%","The uncertainty can be ignored because the estimate is positive","The study proves there is no effect"],0,"Wide uncertainty limits confidence in effect size and may leave multiple interpretations compatible with the evidence.","Use the uncertainty, not just the point estimate."],
["method validity","A method precisely measures solution colour, but the research question asks for nitrate concentration and colour is not reliably related to nitrate. What is the main problem?",["The method may be precise but lacks validity for the intended variable","The method has random error only","More repeats will automatically make colour a valid nitrate measure","The research question must be changed to match the instrument"],0,"Validity concerns whether the method actually measures what is needed to answer the question.","Precision cannot rescue the wrong measure."],
["assumption sensitivity","A model's conclusion changes completely when one uncertain assumption is changed slightly. What does this indicate?",["The conclusion is sensitive to that assumption and should be reported with caution","The assumption is proven correct","The model is automatically useless","Sensitivity removes uncertainty"],0,"Strong sensitivity means uncertainty in the assumption materially affects the conclusion and should be disclosed or tested.","Ask how dependent the conclusion is on assumptions."],
["selective reporting","Researchers run 20 analyses but publish only the one that gives the desired pattern. Why is this a validity concern?",["Selective reporting can exaggerate evidence by hiding how many alternative analyses did not support the claim","More analyses always increase accuracy","Publishing one graph removes random error","The unpublished analyses are irrelevant by definition"],0,"Cherry-picking favourable analyses distorts the apparent strength and consistency of evidence.","Selection after seeing results can bias claims."],
["evidence hierarchy","Which action best evaluates a dramatic scientific claim encountered online?",["Trace it to the original evidence, examine method and sample, compare with independent evidence, and check limitations","Count likes and shares","Accept it if the claim uses technical vocabulary","Reject it automatically because it is online"],0,"Credible evaluation depends on evidence quality and independent support rather than popularity or presentation.","Trace → inspect → compare."],
["final evaluation","A claim is supported by a clear trend, but the sample is biased, a key assumption is untested and another lab failed to reproduce it. What is the best overall judgement?",["The trend is insufficient for a strong claim until the bias, assumption and reproducibility concerns are addressed","The clear trend overrides every other concern","The failed replication alone proves the claim false","The claim is valid because at least one dataset supports it"],0,"Validity is judged across the whole evidence chain: patterns matter, but so do sampling, assumptions and reproducibility.","Evaluate the whole chain, not one attractive result."]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s10i06-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I06",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));