export default [
['A Tasmanian travel review says a walking track is “wonderfully unspoilt”. What is the clearest value judgement?',['The reviewer explicitly values the track’s lack of development','The reviewer criticises the track as unsafe','The phrase is entirely neutral','The reviewer proves nobody has altered the track'],0,'“Wonderfully” openly approves the quality described as “unspoilt”.','Identify the word that directly signals approval.'],
['A report calls a delayed rail project “the government’s latest headache”. What does “headache” imply?',['The project is framed as a troublesome problem','The minister has a medical condition','The delay is praised','The phrase gives the exact cost of the project'],0,'The metaphor casts the project as an ongoing source of difficulty.','Think about the associations created by the metaphor.'],
['A review says, “The café’s tiny menu is focused rather than limited.” What value shift occurs?',['A possible weakness is reframed as deliberate selectivity','The menu becomes physically larger','The sentence removes all evaluation','The reviewer criticises variety more strongly'],0,'“Focused” gives positive value to the same small range that “limited” could frame negatively.','Compare the connotations of the two near-synonyms.'],
['A columnist writes, “Commuters endured another week of replacement buses.” Which word carries the strongest implied judgement?',['endured','commuters','week','buses'],0,'“Endured” suggests the experience was difficult or unpleasant.','Look for the verb that goes beyond simply reporting what happened.'],
['A Melbourne arts article calls an exhibition “accessible”. Which interpretation is most careful?',['It may praise clarity and openness, though the surrounding article is needed to know the exact value','It must mean wheelchair access only','It is always an insult meaning simplistic','It contains no evaluation'],0,'“Accessible” can carry different positive meanings depending on context, so the wider text matters.','Avoid forcing one narrow meaning onto a context-sensitive word.'],
['Which sentence reports a school canteen price rise most neutrally?',['“Prices increased by an average of 8% this term.”','“The canteen gouged students with an 8% rise.”','“The canteen bravely raised prices by 8%.”','“Students were hit with another outrageous increase.”'],0,'The first sentence reports the measured change without praise or blame.','Strip away words that tell the audience how to feel.'],
['A newspaper refers to people opposing a wind farm as “local residents” and supporters as “campaigners”. What should a careful reader notice?',['The different labels may give one group a more ordinary local identity and the other a more political identity','The labels prove residents are correct','Campaigner is always a slur','The wording has no possible evaluative effect'],0,'Labels can subtly distribute normality, legitimacy or ideological identity between groups.','Compare how each group is named.'],
['A book review states, “The author mercifully avoids a final chapter of explanations.” What does “mercifully” reveal?',['The reviewer explicitly approves the omission','The reviewer wants an extra chapter','The sentence is factual only','The reviewer is describing a religious theme'],0,'“Mercifully” directly signals relief and approval.','Small adverbs can carry the writer’s judgement.'],
['A coastal development article says luxury houses are “marching up the headland”. What is implied?',['The development is framed as advancing forcefully across the landscape','The houses are literally moving','The development is praised as elegant','The sentence is neutral because it gives no adjective'],0,'The metaphor “marching” suggests forceful, organised encroachment.','Look at the associations of the verb, not just its grammar.'],
['A critic writes, “The series is polished, perhaps too polished.” What makes this evaluation nuanced?',['The repeated word shifts from praise toward criticism through qualification','The critic gives no opinion','The second phrase simply repeats the first with identical value','The sentence only describes editing software'],0,'The first “polished” can praise craft, while “too polished” questions whether that polish has become sterile or excessive.','Notice how a qualifier can reverse or complicate a value.'],
['A youth council article needs to describe opposing views on a curfew without favouring either side. Which wording is strongest?',['“Supporters cite safety concerns; opponents argue the rule would restrict young people unfairly.”','“Responsible adults support the curfew, while teenagers complain.”','“Sensible residents back the only realistic option.”','“Freedom-loving students reject an authoritarian rule.”'],0,'The first sentence attributes each side’s reasoning without loading the group labels.','Neutral reporting can still present disagreement clearly.'],
['A reviewer wants to imply that a smartphone app is confusing without directly saying “confusing”. Which sentence works best?',['“Three menus later, the basic settings are still nowhere in sight.”','“The app is confusing and badly designed.”','“The app has a settings menu.”','“The app was updated in June.”'],0,'The concrete navigation problem invites the reader to infer confusion.','Show the problem through experience rather than naming the judgement.'],
['A sports article describes a veteran player as “still useful”. Why might the phrase sound faintly dismissive?',['“Still” can imply usefulness was not expected to continue','“Useful” is always an insult','The phrase directly calls the player useless','It contains no evaluation'],0,'The adverb “still” can suggest surprise that the player retains value, which may diminish the praise.','Pay attention to modifiers that change the force of praise.'],
['A housing editorial calls renters “families seeking stability” rather than “tenants”. What effect is most plausible?',['The wording humanises the group and foregrounds a valued goal','It provides a legal definition','It makes the group less sympathetic','Both labels are identical in effect'],0,'The phrase foregrounds family and stability, encouraging readers to view the issue through human needs.','Ask what identity and value the label makes salient.'],
['Which revision makes an environmental claim more appropriately qualified?',['“The evidence indicates the restoration is helping some native species recover.”','“The restoration has completely fixed the ecosystem.”','“The project proves every intervention succeeds.”','“Obviously, nobody can dispute the restoration’s perfection.”'],0,'The first sentence evaluates the result positively while limiting the claim to what the evidence supports.','Strong evaluation should not exceed the evidence.'],
['A reviewer says a comedy is “unafraid to be silly”. Which analysis best captures the value?',['The wording frames silliness as confidence rather than embarrassment','The reviewer is definitely criticising immaturity','The sentence is value-free','“Unafraid” describes the actors’ physical safety'],0,'“Unafraid” positively reframes silliness as deliberate creative confidence.','Notice how one evaluative word changes the meaning of the quality that follows.']
];
