export default [
['t',null,'A Perth radio host says, “As anyone who catches the 7:10 knows, one cancelled train changes the whole morning.” Which analysis is most precise?',['The phrase assumes commuters share the experience and recruits them into the complaint','The time makes the statement scientifically proven','“Anyone” excludes all commuters','The sentence avoids positioning listeners'],0,'The host invokes presumed shared commuter knowledge to create solidarity around the disruption.','Ask what experience the audience is expected to recognise.'],
['t',null,'A school fundraising page reads, “Our community has never walked past a family that needs help.” What persuasive risk comes with this wording?',['It may pressure readers by making generosity part of authentic community membership','It is ineffective because “our” cannot persuade','It gives no sense of shared identity','It is purely factual because it refers to the past'],0,'The line builds solidarity, but it also turns a claimed tradition into pressure to behave consistently with group identity.','Consider both connection and obligation.'],
['t',null,'Which line would best invite young people into a discussion about public transport without assuming their conclusion?',['“If you use buses, bikes, lifts or trains, your experience can help shape what comes next.”','“Obviously every young person wants free buses.”','“Real students reject car dependence.”','“We all know there is only one sensible transport policy.”'],0,'The first line recognises varied experiences and gives the audience a role without prescribing what they must believe.','Choose inclusion that leaves room for different views.'],
['t',null,'A newspaper column states, “No serious voter could support a policy this vague.” What is the strongest analysis?',['It ties one political judgement to the desirable identity of being a “serious voter”','It neutrally describes the policy','It proves opponents have not read the policy','It uses second person to create friendship'],0,'The sentence pressures readers by implying that supporting the policy disqualifies them from a valued identity.','Look for identity being used as a gate.'],
['t',null,'A volunteer campaign says, “Together, we can make the creek safer before summer.” Why is this more inclusive than “Good neighbours will clean the creek”?',['It frames action as shared capacity rather than a test of moral identity','It contains more syllables','It removes the audience from the task','It guarantees everyone will volunteer'],0,'“Together, we can” invites collective agency, whereas “good neighbours” judges belonging and character through compliance.','Compare invitation with identity pressure.'],
['t',null,'A documentary narrator says, “You might recognise this street: thousands of suburbs were designed around the same idea.” What does “You might recognise” achieve?',['It invites personal connection while allowing that the experience is not universal','It claims every viewer lives on that street','It makes the narration fully objective','It excludes viewers unfamiliar with suburbs'],0,'The modal “might” softens direct address, inviting recognition without pretending all viewers share the same experience.','Notice how qualification changes the pressure of “you”.'],
['t',null,'A sports commentary says, “We Australians love an underdog.” Which response shows the most sophisticated reading?',['It invokes a national identity and familiar value, but not every audience member must accept that identity or preference','It proves Australians always support weaker teams','The pronoun has no effect in sport','The statement is neutral because “love” is positive'],0,'The line seeks alignment through national identity and a cultural stereotype; careful analysis does not treat the claim as universally true.','Distinguish rhetorical positioning from factual proof.'],
['t',null,'A youth mental-health poster needs direct address without implying blame. Which line is best?',['“If things feel heavy, you can tell someone you trust or contact support.”','“You should have asked for help sooner.”','“Strong people always speak up immediately.”','“Everyone knows hiding problems makes them worse.”'],0,'The first addresses the reader directly while offering agency and options rather than attaching blame or identity judgement.','Direct address can support rather than accuse.'],
['t',null,'An opinion piece begins, “As we all remember, last year’s floods exposed gaps in the warning system.” What should a careful reader question first?',['Whether the event and interpretation are genuinely shared by the whole implied “we”','Whether floods can occur in Australia','Whether “warning” is a noun','Whether the sentence contains a quotation'],0,'“As we all remember” constructs collective memory, so readers should examine who is included and whether the interpretation is truly shared.','Shared memory is still a rhetorical construction.'],
['t',null,'A café ad says, “For people who know what real coffee tastes like.” How does the line position potential customers?',['It offers membership in a discerning in-group while implying outsiders lack taste','It gives an objective definition of coffee','It includes every customer equally','It avoids evaluation'],0,'The ad flatters those who identify with the in-group and marginalises different preferences as less knowledgeable.','Ask what status comes with joining the implied group.'],
['t',null,'Which revision best removes an exclusionary appeal from “True fans stay until the final siren”?',['“Staying until the final siren can be one way fans show support.”','“Obviously true fans never leave early.”','“Only loyal people stay to the end.”','“We all know leaving early is betrayal.”'],0,'The revision keeps the connection between staying and support but no longer makes one behaviour the test of authentic fandom.','Keep the idea without policing membership.'],
['t',null,'A speech says, “You and I may disagree on the route, but we both want safer streets.” What does the pronoun pattern accomplish?',['It acknowledges difference before constructing a narrower area of shared purpose','It pretends no disagreement exists','It excludes the speaker from the issue','It makes the claim impersonal'],0,'“You and I” recognises separate positions, while “we both” creates alignment around a specific common goal.','Notice the movement from difference to common ground.'],
['t',null,'A campaign slogan reads, “This is our river. Its future is our choice.” Which feature carries most of the alignment work?',['Repeated inclusive possessive “our”','The full stop','The word “future” alone','The absence of statistics'],0,'Repeated “our” constructs shared ownership and responsibility, positioning the audience as part of the decision-making community.','Track who is made to own both the place and the decision.'],
['t',null,'A student article says, “Clearly, no one wants assessment to be unfair.” What is the best next analytical step?',['Separate the broadly agreeable value of fairness from whatever policy claim the writer attaches to it next','Accept every later claim because fairness is good','Ignore “clearly” because it is only an adverb','Assume all readers define fairness identically'],0,'Writers can establish easy shared ground and then use it to support a more contestable proposal; readers should test that connection.','Agreement with a value does not automatically prove the next claim.']
];