export default [
['A regional news site places a drone photo of a dry reservoir above a paragraph reporting water-storage percentages. Which analysis is strongest?',['The image establishes visible scale while the paragraph quantifies the situation; together they provide different forms of evidence','The image proves the percentages are accurate','The paragraph is unnecessary because the image shows everything','The image guarantees readers will support restrictions'],0,'The visual and numerical modes complement one another without proving more than either source supports.','Identify what each mode contributes and what it cannot prove.'],
['A memoir chapter uses a long reflective paragraph followed by the isolated sentence “I never went back.” What does the structural contrast most likely do?',['It gives the final decision abrupt weight after extended reflection','It makes the final sentence less important','It turns the sentence into dialogue','It proves the narrator regrets the decision'],0,'The short isolated sentence interrupts the reflective flow and foregrounds finality.','Compare the rhythm before and after the break.'],
['A public-transport webpage places route maps at the bottom after several screens of explanatory text. What is the clearest design problem?',['Readers must separate the explanation from the visual information needed to use it','Maps cannot be used on webpages','The text becomes grammatically incorrect','The maps make the page too factual'],0,'Distance between related modes makes it harder to connect instructions with routes.','Consider proximity between linked information.'],
['In a graphic novel, a character’s face is shown in four increasingly tight close-ups across consecutive panels. What is the best interpretation?',['The narrowing framing intensifies attention on the character’s reaction','Close-ups prove the character is guilty','The panels show four different characters','The sequence removes any sense of time'],0,'Progressively tighter framing can heighten focus without fixing one specific emotion.','Analyse the visual progression, not an unsupported motive.'],
['An online article about rental stress uses a full-width photo between two paragraphs: first causes, then personal stories. What role can the image play structurally?',['It can act as a transition from abstract explanation to lived experience','It proves every renter has the same experience','It makes the first paragraph fictional','It removes the need for the second paragraph'],0,'Placed between sections, an image can bridge different kinds of content.','Look at what changes across the image.'],
['A reviewer claims that short paragraphs always make a text easier to read. Which response is most accurate?',['Short paragraphs can aid scanning, but too many arbitrary breaks can fragment complex ideas','Short paragraphs are always clearer','Paragraph length never affects reading','Long paragraphs are always more academic'],0,'Effectiveness depends on whether paragraph breaks match the logic and reading context.','Avoid universal rules about structure.'],
['A wildlife website pairs a photo of one injured bird with a paragraph about national population decline. Which caution is most important?',['The individual image can personalise the issue but does not by itself demonstrate the national trend','The photograph cannot be evidence of anything','The paragraph must be false because it is broader','Images and statistics should never appear together'],0,'A single case and a population claim operate at different scales.','Distinguish illustration from proof of a trend.'],
['A graphic memoir uses a page with no panel borders during a traumatic memory, then returns to regular panels. What is a defensible reading?',['The temporary loss of boundaries may reflect disruption or instability in the memory','Borderless pages always represent trauma','The artist forgot the layout rules','The regular panels prove the memory is false'],0,'Breaking the established layout can suggest disturbance, but meaning still comes from context.','Compare the exceptional page with the normal pattern.'],
['A council webpage about recycling repeats the same sentence in text, infographic and caption. What is the main weakness?',['The modes duplicate information instead of contributing complementary detail','Repeated information is always misleading','Infographics should never contain words','Captions must be longer than paragraphs'],0,'Multimodal design is stronger when each mode adds something useful.','Ask whether the modes add or merely repeat.'],
['A feature writer wants the final paragraph to feel contemplative rather than forceful. Which choice best fits?',['Use a slightly longer paragraph that returns to an earlier image and leaves the implication open','End with a one-word command in capitals','Add five exclamation marks','List unrelated statistics'],0,'A reflective return and open implication support a contemplative ending.','Match structure and tone to the intended effect.'],
['A mobile news story places a video before any headline or context. What is the strongest evaluation?',['The video may capture attention, but without framing readers may not know what to notice or how it relates to the story','Video is always more effective than text','The headline becomes irrelevant','Readers will all interpret the video identically'],0,'Multimodal elements need clear relationships, not just prominence.','Evaluate both attention and clarity.'],
['In a graphic narrative, narration describes a family dinner as “ordinary” while the image shows everyone avoiding eye contact. What does the text–image relationship create?',['A tension between the narrator’s label and visual evidence that invites readers to question “ordinary”','The image simply repeats the narration','The narration proves the image is wrong','The modes cannot contradict each other'],0,'Contradiction between modes can create irony or uncertainty.','Look for agreement, extension or contradiction.'],
['A student adapts a printed review into a webpage. Which change best suits online reading while preserving depth?',['Use clear subheadings and expandable evidence sections without deleting the reasoning','Reduce every paragraph to one sentence','Replace all analysis with star ratings','Put the conclusion first and remove evidence'],0,'Digital adaptation can improve navigation without sacrificing analysis.','Adapt access, not intellectual depth.'],
['A long-form article alternates two-line paragraphs with full-page photographs throughout. Which judgement is most useful?',['The repeated pattern may create a slow visual rhythm, but its effectiveness depends on whether each photograph advances the article','Full-page photographs are automatically persuasive','Two-line paragraphs are always weak','The pattern proves the article is unbiased'],0,'A structural pattern should be judged by how well it supports meaning, not by size alone.','Evaluate contribution, not just appearance.'],
['A graphic novel wants readers to notice a character excluded from a group conversation. Which layout is most effective?',['Place the group across connected panels while isolating the character in a separate narrow panel','Give every character identical framing','Remove all spatial relationships','Put the excluded character in the centre of every group panel'],0,'Visual separation can make social exclusion legible through layout.','Use spatial organisation to reinforce relationships.'],
['An emergency-information page combines a paragraph, icon set and map. Which design best supports rapid use?',['Place each icon beside its matching instruction and keep the map close to location-specific directions','Put all icons in a decorative footer','Separate the map from the directions by several unrelated sections','Use the same icon for every instruction'],0,'Rapid-use pages need clear proximity and consistent relationships between modes.','Design for the reader’s task and likely urgency.']
];