export default [
['explain','A sports column uses a long paragraph describing a tense final minute, followed by “Missed.” as a one-word paragraph. Why is this effective?',['The long build-up creates anticipation and the isolated word delivers an abrupt outcome','The one-word paragraph adds more factual detail than the long paragraph','The structure proves the writer dislikes the player','The short paragraph removes suspense'],0,'The contrast in paragraph length shapes pacing: extended suspense is followed by a sharp release.','Explain the contrast, not just the short paragraph.'],
['explain','An online museum page puts a portrait beside a paragraph about the subject’s public achievements, then a caption notes the portrait was commissioned by the subject. Why does the caption matter?',['It adds context that may make readers question how neutral the portrait is','It proves the achievements are false','It turns the portrait into a graph','It has no relationship to the image'],0,'The caption changes how readers interpret the visual by adding information about its production.','Ask whether the caption changes the image’s meaning or credibility.'],
['explain','A graphic novel shows a protest crowd in a wide panel, then cuts to a close-up of one frightened face. What does the shift achieve?',['It moves from collective scale to individual experience','It proves only one person attended','It makes the event less emotional','It changes the genre into a biography'],0,'The wide shot establishes the crowd; the close-up personalises the event through one person.','Track how framing changes viewpoint.'],
['explain','A webpage begins with a large statistic, then follows with three short paragraphs explaining where it came from. Why might this order work?',['It captures attention first, then supplies context and evidence','It makes the statistic true because it appears first','It prevents readers questioning the number','It removes the need for a source'],0,'The structure foregrounds the headline figure before unpacking its basis.','Separate attention-grabbing structure from evidence quality.'],
['explain','A travel article alternates a paragraph of description with a photo from the same location. What is the strongest explanation of the pattern?',['The repeated text–image pairing lets readers compare verbal description with visual representation as they move through the journey','The photos make every description objective','The pattern guarantees readers will like the destination','The paragraphs are unnecessary because images always communicate more'],0,'Alternation can create a rhythm in which each location is represented in two modes.','Explain how the sequence guides reading.'],
['explain','A graphic memoir places narration in rectangular boxes while speech appears in balloons. Why is this distinction useful?',['It helps readers separate reflective narration from words spoken in the scene','It shows narration is always more truthful','It means speech balloons are optional decoration','It proves the narrator is not a character'],0,'Different containers signal different kinds of language and help readers track layers of the story.','Focus on how visual conventions organise meaning.'],
['explain','An editorial groups three objections in separate paragraphs before a final paragraph answering them together. What is the effect?',['Readers can consider each objection separately before seeing the writer’s overall rebuttal','The objections become the writer’s own position','Paragraph breaks remove the need for evidence','The final paragraph must be correct because it comes last'],0,'The paragraph structure stages opposition before synthesis.','Describe the reasoning sequence created by the paragraphs.'],
['explain','A climate webpage places before-and-after satellite images above a paragraph describing coastline change. Why is this more effective than using the paragraph alone?',['The images make the change visible while the paragraph can explain scale, timing and significance','Images are always more trustworthy than words','The paragraph becomes redundant','The images prove the cause of the change by themselves'],0,'The visual evidence and explanation perform different but complementary roles.','State what each mode contributes.'],
['explain','A graphic novel repeats the same street corner across four panels while only the light changes. What can that repetition do?',['Show time passing while keeping location constant','Show four different streets','Prove no action occurs between panels','Make the setting irrelevant'],0,'Repeating the composition helps readers notice the changing light as the key sign of time.','Ask what stays constant and what changes.'],
['explain','A feature article inserts a short paragraph containing only a question between two sections. Why might the writer do this?',['To pivot the discussion and prompt readers to reconsider what follows','To provide a source citation','To remove ambiguity from the argument','To replace the need for a conclusion'],0,'An isolated question can act as a structural hinge between sections.','Look at what comes before and after the question.']
];