export default [
['p','discriminate','A reviewer writes, “We all know sequels are usually disappointing.” What is the weakness in saying this simply “creates community”?',['It also suppresses difference by presenting a debatable opinion as shared knowledge','Community language can never persuade','The sentence contains no pronouns','The claim becomes objective through “we”'],0,'The inclusive pronoun may create solidarity, but “all know” also pressures readers to accept a contestable judgement.','Strong analysis can identify connection and pressure together.'],
['p','discriminate','What best explains the difference between “Some residents oppose the change” and “Even our neighbours oppose the change”?',['The second invokes closeness and shared identity, making opposition feel more socially significant','The second is more accurate because it says “our”','The first is emotional and the second neutral','Both position readers identically'],0,'“Our neighbours” creates relationship and “even” marks their opposition as noteworthy, adding positioning absent from the neutral description.','Look beyond what happened to how people are framed.'],
['p','apply','You are editing a speech arguing for shaded bus stops. Which opening builds shared concern without claiming everyone already agrees?',['“Many of us have waited through a 35-degree afternoon; let’s look at what shade could change.”','“Obviously, every sensible person supports shaded stops.”','“Real Canberrans demand shade immediately.”','“You would have to be careless to oppose this plan.”'],0,'The first uses a plausible shared experience and inclusive invitation while leaving the proposal open to consideration.','Aim for connection without turning disagreement into a character flaw.'],
['p','apply','A housing forum wants renters and homeowners to feel equally included. Which line is most suitable?',['“Whether you rent, own or live with family, your experience of housing belongs in this conversation.”','“Homeowners like us know what the suburb needs.”','“Responsible residents protect property values first.”','“Obviously, renters understand the problem best.”'],0,'The first explicitly names different housing situations and gives each a legitimate place in the discussion.','Choose language that widens rather than narrows membership.'],
['p','apply','A health campaign wants teenagers to question risky driving without shaming them. Which wording best fits?',['“Before you get in, ask whether the driver is ready to get everyone home safely.”','“Only idiots get into a car with a tired driver.”','“Good teenagers never make risky choices.”','“Everyone knows smart people refuse every late-night lift.”'],0,'The first uses direct address and a practical question to create agency without defining people by a mistake.','Look for responsibility without insult or identity policing.'],
['p','apply','A student is revising “We all know phones destroy concentration” for a balanced persuasive article. Which revision is strongest?',['“Many students report distraction from phones, although the effect varies with how they are used.”','“Obviously phones destroy everyone’s concentration.”','“Real students know phones are the problem.”','“You cannot deny that phones ruin learning.”'],0,'The revision keeps the issue while replacing assumed consensus with a qualified claim that allows complexity.','Preserve the argument without pretending every reader shares it.'],
['p','apply','A coastal clean-up group wants a closing line that creates solidarity through shared action. Which is best?',['“If we each take one section of beach, together we can clear the whole stretch.”','“Anyone who leaves now clearly does not care.”','“Good locals never need to be asked twice.”','“Obviously you owe the beach your afternoon.”'],0,'Inclusive “we” and “together” frame the task as cooperative rather than using shame to force compliance.','Look for shared agency rather than social punishment.'],
['p','apply','An editorial wants to challenge readers about food waste while avoiding an exclusionary identity claim. Which sentence works best?',['“Before we throw food out, we can ask whether someone else could use it.”','“Decent Australians never waste food.”','“People like us would never bin leftovers.”','“Only selfish households waste edible food.”'],0,'The first uses inclusive language to invite a behaviour without defining dissenters as morally inferior outsiders.','Choose a shared action, not a test of who belongs.'],
['p','apply','A student podcast is introducing two opposing views on school uniforms. Which wording positions listeners most fairly?',['“You may recognise parts of both arguments, so listen for the values each speaker prioritises.”','“We all know uniforms are outdated, but here is the other side.”','“Any sensible student supports choice.”','“Real school pride means backing uniforms.”'],0,'The first directly involves listeners while leaving room for different responses and encouraging comparison.','Fair positioning allows listeners to evaluate rather than tells them who they must be.'],
['p','apply','A community newsletter wants to encourage attendance at a bushfire-preparation meeting. Which line uses shared local experience responsibly?',['“After the summers our district has faced, many of us know why preparation matters; the meeting will explain the new plan.”','“Every real local knows attendance is compulsory in spirit.”','“Obviously nobody responsible would stay home.”','“If you care about your neighbours, you will attend.”'],0,'The first acknowledges a plausible shared context without making attendance a test of identity or morality.','Use common experience as context, not as a threat to belonging.'],
['p','apply','A debate speaker wants to replace “Only fools think the old oval should stay” with language that still signals a clear position. Which is best?',['“Keeping the old oval would ignore the stronger evidence for a multi-use space.”','“Obviously the old oval has to go.”','“People like us know the oval is useless.”','“Any intelligent voter supports redevelopment.”'],0,'The revision attacks the reasoning rather than the identity or intelligence of people who disagree.','Make the evidence carry the pressure, not a label for opponents.'],
['p','apply','A museum youth panel wants visitors to feel invited into a question about local history. Which prompt best does this?',['“What stories do we inherit when a town remembers one group more loudly than another?”','“We all know the official history is wrong.”','“Good visitors understand which story matters.”','“Obviously you should reject the old display.”'],0,'The inclusive question invites visitors to investigate shared memory without dictating a compulsory conclusion.','Use inclusion to open inquiry rather than close it.'],
['t',null,'A Tasmanian conservation ad says, “Surely none of us wants silence where the swift parrots used to call.” What is the main effect of “Surely none of us”?',['It presents concern as expected shared ground','It supplies evidence of population size','It distances the speaker from viewers','It introduces a neutral definition'],0,'The phrase combines assumed agreement with inclusive reference, making concern appear to be the normal group position.','Identify both the assumption and the group created.'],
['t',null,'At a council meeting, a resident says, “You will decide tonight whether our children cross four lanes without lights.” How does the pronoun choice position councillors?',['It assigns them direct responsibility for the consequence','It treats them as detached observers','It hides who makes the decision','It creates a casual friendship'],0,'“You” places responsibility on the decision-makers while “our children” frames the consequence as a community concern.','Track who must act and who is affected.']
];