"use strict";
window.skillrTestQuestions = [
  {
    "id": "ac9e1ly11-er6-t-001",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check accurate short-vowel blending and identification of e, i and u. The grown-up should not pre-read the target words.",
    "acceptanceNote": "Check accurate short-vowel blending and identification of e, i and u. The grown-up should not pre-read the target words.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'hen, pig, bus' aloud to a grown-up and point to each vowel letter.",
    "audioPrompt": "Read 'hen, pig, bus' aloud to a grown-up and point to each vowel letter.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 1,
    "correct": "Check accurate short-vowel blending and identification of e, i and u. The grown-up should not pre-read the target words.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check accurate short-vowel blending and identification of e, i and u. The grown-up should not pre-read the target words.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-002",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check /sh/ in shop and /ch/ in chop, with the remaining sounds retained. These two digraphs represent different phonemes.",
    "acceptanceNote": "Check /sh/ in shop and /ch/ in chop, with the remaining sounds retained. These two digraphs represent different phonemes.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'shop' and 'chop' aloud, keeping their beginnings different.",
    "audioPrompt": "Read 'shop' and 'chop' aloud, keeping their beginnings different.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 2,
    "correct": "Check /sh/ in shop and /ch/ in chop, with the remaining sounds retained. These two digraphs represent different phonemes.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check /sh/ in shop and /ch/ in chop, with the remaining sounds retained. These two digraphs represent different phonemes.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-003",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check the initial /k/ /l/ blend and spelling clap, with no omitted l.",
    "acceptanceNote": "Check the initial /k/ /l/ blend and spelling clap, with no omitted l.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'clap' and write it after covering the model.",
    "audioPrompt": "Read 'clap' and write it after covering the model.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 3,
    "correct": "Check the initial /k/ /l/ blend and spelling clap, with no omitted l.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check the initial /k/ /l/ blend and spelling clap, with no omitted l.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-004",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check the final /n/ /d/ sequence and the spelling hand, retaining both ending consonants.",
    "acceptanceNote": "Check the final /n/ /d/ sequence and the spelling hand, retaining both ending consonants.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'hand'. Say the two ending sounds, then write the word.",
    "audioPrompt": "Read 'hand'. Say the two ending sounds, then write the word.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 4,
    "correct": "Check the final /n/ /d/ sequence and the spelling hand, retaining both ending consonants.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check the final /n/ /d/ sequence and the spelling hand, retaining both ending consonants.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-005",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check correct reading and oa identified in both words. Their shared vowel pattern does not mean their beginning sounds are the same.",
    "acceptanceNote": "Check correct reading and oa identified in both words. Their shared vowel pattern does not mean their beginning sounds are the same.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'boat' and 'goat' aloud. Point to their shared long-vowel spelling.",
    "audioPrompt": "Read 'boat' and 'goat' aloud. Point to their shared long-vowel spelling.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 5,
    "correct": "Check correct reading and oa identified in both words. Their shared vowel pattern does not mean their beginning sounds are the same.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check correct reading and oa identified in both words. Their shared vowel pattern does not mean their beginning sounds are the same.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-006",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check accurate reading of both and the spelling beach. Ea represents long e and ch the final sound in this word.",
    "acceptanceNote": "Check accurate reading of both and the spelling beach. Ea represents long e and ch the final sound in this word.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'seed' and 'beach'. Write the word that names a place by the sea.",
    "audioPrompt": "Read 'seed' and 'beach'. Write the word that names a place by the sea.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 6,
    "correct": "Check accurate reading of both and the spelling beach. Ea represents long e and ch the final sound in this word.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check accurate reading of both and the spelling beach. Ea represents long e and ch the final sound in this word.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-007",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check short a in mad, long a in made and the final e included only in made.",
    "acceptanceNote": "Check short a in mad, long a in made and the final e included only in made.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'mad' and 'made'. Write both and re-read them with different vowel sounds.",
    "audioPrompt": "Read 'mad' and 'made'. Write both and re-read them with different vowel sounds.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 7,
    "correct": "Check short a in mad, long a in made and the final e included only in made.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check short a in mad, long a in made and the final e included only in made.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-008",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check ride, with the final e and long i, after accurate reading of both words.",
    "acceptanceNote": "Check ride, with the final e and long i, after accurate reading of both words.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'rid' and 'ride'. Write the word for travelling on a bike.",
    "audioPrompt": "Read 'rid' and 'ride'. Write the word for travelling on a bike.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 8,
    "correct": "Check ride, with the final e and long i, after accurate reading of both words.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check ride, with the final e and long i, after accurate reading of both words.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-009",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check note with long o and final e, distinguished from the short-vowel word not.",
    "acceptanceNote": "Check note with long o and final e, distinguished from the short-vowel word not.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'not' and 'note'. Write the word for a short written message.",
    "audioPrompt": "Read 'not' and 'note'. Write the word for a short written message.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 9,
    "correct": "Check note with long o and final e, distinguished from the short-vowel word not.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check note with long o and final e, distinguished from the short-vowel word not.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-010",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check fl, long a and the final-e spelling flame. No sound in the initial cluster should be omitted.",
    "acceptanceNote": "Check fl, long a and the final-e spelling flame. No sound in the initial cluster should be omitted.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'flame'. Point to its beginning blend, then read and write the whole word.",
    "audioPrompt": "Read 'flame'. Point to its beginning blend, then read and write the whole word.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 10,
    "correct": "Check fl, long a and the final-e spelling flame. No sound in the initial cluster should be omitted.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check fl, long a and the final-e spelling flame. No sound in the initial cluster should be omitted.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-011",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check pic-nic, preserving both short i vowels and both syllables in order.",
    "acceptanceNote": "Check pic-nic, preserving both short i vowels and both syllables in order.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'picnic' aloud by blending its two parts, then say the whole word naturally.",
    "audioPrompt": "Read 'picnic' aloud by blending its two parts, then say the whole word naturally.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 11,
    "correct": "Check pic-nic, preserving both short i vowels and both syllables in order.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check pic-nic, preserving both short i vowels and both syllables in order.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-012",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check lunch, including the n before the final ch digraph. Judge reading and spelling, not decorative handwriting.",
    "acceptanceNote": "Check lunch, including the n before the final ch digraph. Judge reading and spelling, not decorative handwriting.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Grown-up: hide the screen. Say 'lunch'. Ask the child to write it and read it back.",
    "audioPrompt": "Grown-up: hide the screen. Say 'lunch'. Ask the child to write it and read it back.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 12,
    "correct": "Check lunch, including the n before the final ch digraph. Judge reading and spelling, not decorative handwriting.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check lunch, including the n before the final ch digraph. Judge reading and spelling, not decorative handwriting.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-013",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check green, with the gr blend and ee representing long e. The spoken output should match the word written.",
    "acceptanceNote": "Check green, with the gr blend and ee representing long e. The spoken output should match the word written.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Grown-up: hide the screen. Say 'green'. Ask the child to write it and read it aloud.",
    "audioPrompt": "Grown-up: hide the screen. Say 'green'. Ask the child to write it and read it aloud.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 13,
    "correct": "Check green, with the gr blend and ee representing long e. The spoken output should match the word written.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check green, with the gr blend and ee representing long e. The spoken output should match the word written.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-014",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check laptop, retaining lap and top in order. The middle p and t belong to different parts and both need to appear.",
    "acceptanceNote": "Check laptop, retaining lap and top in order. The middle p and t belong to different parts and both need to appear.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'laptop'. Cover it, write it and check that both spoken parts are represented.",
    "audioPrompt": "Read 'laptop'. Cover it, write it and check that both spoken parts are represented.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 14,
    "correct": "Check laptop, retaining lap and top in order. The middle p and t belong to different parts and both need to appear.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check laptop, retaining lap and top in order. The middle p and t belong to different parts and both need to appear.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-015",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check ai and oa, accurate blending of sail-boat and the complete spelling sailboat.",
    "acceptanceNote": "Check ai and oa, accurate blending of sail-boat and the complete spelling sailboat.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Read 'sailboat'. Point to the two different long-vowel spellings, then write the word.",
    "audioPrompt": "Read 'sailboat'. Point to the two different long-vowel spellings, then write the word.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 15,
    "correct": "Check ai and oa, accurate blending of sail-boat and the complete spelling sailboat.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check ai and oa, accurate blending of sail-boat and the complete spelling sailboat.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly11-er6-t-016",
    "curriculumCode": "AC9E1LY11",
    "bank": "test",
    "skill": "reading and writing words using vowel and consonant patterns",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Check tooth-brush, with oo, th, br and sh all represented. Allow thinking time and a self-correction; do not supply the spelling first.",
    "acceptanceNote": "Check tooth-brush, with oo, th, br and sh all represented. Allow thinking time and a self-correction; do not supply the spelling first.",
    "responseInstructions": "Try reading the target words yourself before using Read aloud. Complete the writing on paper; a grown-up checks both parts.",
    "completionLabel": "I have completed the reading and writing task.",
    "question": "Grown-up: hide the screen. Say 'toothbrush'. Ask the child to write the word and read it back in two parts.",
    "audioPrompt": "Grown-up: hide the screen. Say 'toothbrush'. Ask the child to write the word and read it back in two parts.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 16,
    "correct": "Check tooth-brush, with oo, th, br and sh all represented. Allow thinking time and a self-correction; do not supply the spelling first.",
    "explanation": "Check the completed work against this guidance before marking the response.",
    "structuredExplanation": {
      "summary": "Check tooth-brush, with oo, th, br and sh all represented. Allow thinking time and a self-correction; do not supply the spelling first.",
      "hint": "Complete the task before comparing with the model. A grown-up checks reading and writing."
    },
    "qualitySchema": "production-v1"
  }
];
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
