"use strict";
const NOTE="Draw/sketch the diagram in your notes, then answer. ";
const Q=(id,n,s,q,a,c,e)=>({id,curriculumCode:"AC9M10SP03",bank:"test",section:s,sourceNumber:n,skill:s,printable:true,type:"single",question:q,answers:a,correct:c,explanation:e,structuredExplanation:{summary:e,hint:"Construct or imagine the diagram, then test the spatial rule or algorithm."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q("ac9m10sp03-t-001",25,"Spatial properties",NOTE+"Sketch a convex pentagon. Which statement must be true?",["Every interior angle is less than 180°","Every interior angle is greater than 180°","The polygon must have a line of symmetry","All sides must be equal"],0,"A convex polygon has every interior angle less than 180°."),
Q("ac9m10sp03-t-002",26,"Pathfinding",NOTE+"Draw two routes between the same points. Path A has 8 steps totalling 12 units; Path B has 6 steps totalling 15 units. Which is the shortest?",["Path B because it has fewer steps","Path A because it has smaller total distance","Path B because it has more distance","They are equally short"],1,"Shortest path is determined by total distance or weight."),
Q("ac9m10sp03-t-003",27,"Transformations",NOTE+"Plot a point (x,y) and rotate it 270° clockwise about the origin. Which mapping is correct?",["(x,y)→(y,-x)","(x,y)→(-y,x)","(x,y)→(-x,-y)","(x,y)→(-x,y)"],1,"A 270° clockwise rotation is equivalent to 90° anticlockwise, giving (-y,x)."),
Q("ac9m10sp03-t-004",28,"Algorithms",NOTE+"Sketch a robot loop: move one cell toward target → check target reached? → if No repeat; if Yes stop. Which structure is used?",["Repeat-until","Single if statement only","Switch statement","Immediate stop"],0,"The movement repeats until the target condition is satisfied."),
Q("ac9m10sp03-t-005",29,"Transformations",NOTE+"Plot a point (x,y) and reflect it in the y-axis. Which mapping applies?",["(x,y)→(-x,y)","(x,y)→(x,-y)","(x,y)→(-x,-y)","(x,y)→(y,x)"],0,"Reflection in the y-axis changes only the sign of x."),
Q("ac9m10sp03-t-006",30,"Connectedness",NOTE+"Draw a grid with open cells and blocked cells. A cell is reachable from S if:",["There is a connected path of open cells from S to it","It is blocked","It lies diagonally from S","It is on the border"],0,"Reachability requires a valid connected path through allowed cells."),
Q("ac9m10sp03-t-007",31,"Spatial algorithms",NOTE+"Draw a triangle with side lengths a, b and c, with c the longest side. Which test checks whether it is right-angled?",["a²+b²=c²","a+b=c","a²-b²=c²","ab=c"],0,"Pythagoras' theorem gives the right-angle condition."),
Q("ac9m10sp03-t-008",32,"Transformations",NOTE+"Plot P(2,1) and its image P′(-2,-1). What rotation about the origin maps P to P′?",["90°","180°","270°","360°"],1,"A 180° rotation maps (x,y) to (-x,-y)."),
Q("ac9m10sp03-t-009",33,"Scaling",NOTE+"Draw a square and scale every length by factor 1/2. Which property changes?",["Size","Angle measures","Orientation","Number of sides"],0,"Scaling by 1/2 changes size but preserves angles and shape."),
Q("ac9m10sp03-t-010",34,"Movement algorithms",NOTE+"Draw a start point and the instruction sequence ↑ ↑ → ↑. To execute the algorithm correctly, the robot should:",["Follow the arrows in order","Skip alternate arrows","Reverse the order","Move diagonally instead"],0,"Algorithms are followed in the specified sequence unless a branch or loop changes control flow."),
Q("ac9m10sp03-t-011",35,"Spatial algorithms",NOTE+"Draw a directed line from A to B and a point P. Which computational test can determine whether P lies to the left or right of the directed line?",["Sign of a 2D cross product/determinant","Triangle angle sum","Area of a circle","Reflection rule"],0,"The sign of the 2D cross product or determinant indicates which side of a directed line a point lies on."),
Q("ac9m10sp03-t-012",36,"Transformations",NOTE+"Plot a point (x,y) and rotate it 90° clockwise about the origin. Which mapping is correct?",["(x,y)→(y,-x)","(x,y)→(-y,x)","(x,y)→(x,y)","(x,y)→(-x,-y)"],0,"A 90° clockwise rotation maps (x,y) to (y,-x)."),
Q("ac9m10sp03-t-013",37,"Pathfinding",NOTE+"Draw a route from S to G and block one edge on that route. Which algorithm can recompute an alternative minimum-cost route?",["Dijkstra's algorithm","Sorting","Reflection","Scaling"],0,"A shortest-path algorithm such as Dijkstra can find an alternative route using the remaining connections."),
Q("ac9m10sp03-t-014",38,"Transformations",NOTE+"Draw a point and translate it 6 units down. Which vector describes the movement?",["(0,-6)","(0,6)","(6,0)","(-6,0)"],0,"Moving down 6 changes y by -6 and x by 0."),
Q("ac9m10sp03-t-015",39,"Spatial properties",NOTE+"Sketch a regular pentagon. Which condition defines it as regular?",["All sides and all interior angles are equal","All sides are equal only","All angles are equal only","No sides are equal"],0,"A regular polygon is both equilateral and equiangular."),
Q("ac9m10sp03-t-016",40,"Pathfinding",NOTE+"Draw a weighted network with several routes from S to G. A shortest-path algorithm selects the route with:",["Minimum total weight","Maximum number of turns","A random sequence of edges","No edges at all"],0,"Shortest-path algorithms minimise the total chosen weight, such as distance, time or cost.")];
window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
