"use strict";
function coord(points,tri){const xs=points.map(p=>p[1]).concat(0),ys=points.map(p=>p[2]).concat(0),minX=Math.min(...xs)-1,maxX=Math.max(...xs)+1,minY=Math.min(...ys)-1,maxY=Math.max(...ys)+1,w=420,h=300,m=36,sx=x=>m+(x-minX)/(maxX-minX)*(w-2*m),sy=y=>h-m-(y-minY)/(maxY-minY)*(h-2*m);let g=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Coordinate diagram"><rect width="${w}" height="${h}" rx="14" fill="#fff"/><text x="16" y="22" font-size="13" font-weight="700" fill="#334155">Use scratchpad/notebook: mark rise, run, distance or midpoint.</text>`;for(let x=Math.ceil(minX);x<=Math.floor(maxX);x++){g+=`<line x1="${sx(x)}" y1="${m}" x2="${sx(x)}" y2="${h-m}" stroke="${x===0?'#64748b':'#dbe4ef'}" stroke-width="${x===0?2:1}"/>`}for(let y=Math.ceil(minY);y<=Math.floor(maxY);y++){g+=`<line x1="${m}" y1="${sy(y)}" x2="${w-m}" y2="${sy(y)}" stroke="${y===0?'#64748b':'#dbe4ef'}" stroke-width="${y===0?2:1}"/>`}if(points.length>=2){const a=points[0],b=points[1];g+=`<line x1="${sx(a[1])}" y1="${sy(a[2])}" x2="${sx(b[1])}" y2="${sy(b[2])}" stroke="#2563eb" stroke-width="3" stroke-linecap="round"/>`;if(tri&&a[1]!==b[1]&&a[2]!==b[2])g+=`<polyline points="${sx(a[1])},${sy(a[2])} ${sx(b[1])},${sy(a[2])} ${sx(b[1])},${sy(b[2])}" fill="none" stroke="#f97316" stroke-width="2" stroke-dasharray="5 4"/>`}points.forEach(p=>{g+=`<circle cx="${sx(p[1])}" cy="${sy(p[2])}" r="5" fill="#dc2626"/><text x="${sx(p[1])+8}" y="${sy(p[2])-7}" font-size="13" font-weight="700" fill="#111827">${p[0]}(${p[1]},${p[2]})</text>`});return g+`</svg>`}
const raw=[
[1,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows line segment AB from A(2, 5) to B(6, 9). Use the scratchpad or notebook to find the gradient.",["1","2","4","0.5"],0,"Gradient = (9 − 5)/(6 − 2) = 1.","Gradient is rise divided by run.",[["A",2,5],["B",6,9]],true],
[2,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows line segment AB from A(−3, 4) to B(1, 12). Use the scratchpad or notebook to find the gradient.",["2","4","−2","8"],0,"Gradient = (12 − 4)/(1 − (−3)) = 8/4 = 2.","Subtract y-values and x-values in the same order.",[["A",-3,4],["B",1,12]],true],
[3,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows line segment AB from A(0, 0) to B(5, −10). Use the scratchpad or notebook to find the gradient.",["−2","2","−0.5","10"],0,"Gradient = (−10 − 0)/(5 − 0) = −2.","A downward line from left to right has negative gradient.",[["A",0,0],["B",5,-10]],true],
[4,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows line segment AB from A(7, 3) to B(9, 9). Use the scratchpad or notebook to find the gradient.",["3","2","6","1"],0,"Gradient = (9 − 3)/(9 − 7) = 6/2 = 3.","Mark the rise and run on the diagram.",[["A",7,3],["B",9,9]],true],
[5,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows a horizontal segment from A(−2, −1) to B(4, −1). What is its gradient?",["0","1","−1","Undefined"],0,"The y-value does not change, so the rise is 0 and the gradient is 0.","Horizontal lines have gradient 0.",[["A",-2,-1],["B",4,-1]],false],
[6,"Section A — Gradient of a line segment","Gradient from a diagram","The diagram shows a vertical segment from A(3, 8) to B(3, −4). What is its gradient?",["Undefined","0","4","−4"],0,"The x-value does not change, so the run is 0 and the gradient is undefined.","Vertical lines have undefined gradient.",[["A",3,8],["B",3,-4]],false],
[7,"Section A — Gradient of a line segment","Gradient concept","A straight line is shown on a coordinate grid. Which statement about its gradient is true?",["Gradient is the same no matter which two points you choose on the line","Gradient changes depending on which two points you choose","Gradient only works for horizontal lines","Gradient only works for vertical lines"],0,"A straight line has a constant gradient.","Any two points on the same straight line give the same rise/run.",[["P",0,1],["Q",5,6]],true],
[8,"Section A — Gradient of a line segment","Gradient concept","If a line has gradient 5, then any two points on it must satisfy:",["rise/run = 5","rise/run = −5","rise/run = 1/5","rise/run = 0"],0,"Gradient means rise divided by run.","Use rise/run."],
[9,"Section B — Parallel and perpendicular lines","Parallel gradients","A line on a coordinate grid has gradient 3. A parallel line must have gradient:",["3","−3","1/3","−1/3"],0,"Parallel non-vertical lines have the same gradient.","Parallel means same steepness.",[["L",0,0],["M",3,9]],true],
[10,"Section B — Parallel and perpendicular lines","Perpendicular gradients","A line has gradient −4. A perpendicular line must have gradient:",["1/4","−1/4","4","−4"],0,"Perpendicular gradients are negative reciprocals, and −4 × 1/4 = −1.","The product must be −1."],
[11,"Section B — Parallel and perpendicular lines","Perpendicular gradients","Which pair of gradients represents perpendicular lines?",["2 and −1/2","2 and 2","2 and 1/2","−2 and −1/2"],0,"2 × (−1/2) = −1, so the lines are perpendicular.","Check the product."],
[12,"Section B — Parallel and perpendicular lines","Parallel gradients","Which pair of gradients represents parallel lines?",["5 and 5","5 and −5","5 and 1/5","5 and −1/5"],0,"Parallel lines have equal gradients.","Same gradient means same direction."],
[13,"Section B — Parallel and perpendicular lines","Perpendicular gradients","If two non-vertical line gradients satisfy m₁ × m₂ = −1, the lines are:",["Perpendicular","Parallel","Horizontal","Vertical"],0,"This is the perpendicular gradient rule.","Negative reciprocal gradients multiply to −1."],
[14,"Section B — Parallel and perpendicular lines","Special gradients","A horizontal line is drawn across a grid with gradient 0. A perpendicular line must be:",["Vertical","Horizontal","Parallel","Diagonal"],0,"Horizontal and vertical lines meet at right angles.","A vertical line is perpendicular to a horizontal line."],
[15,"Section B — Parallel and perpendicular lines","Special gradients","A vertical line is drawn on a coordinate grid. Its gradient is:",["Undefined","0","1","−1"],0,"Vertical lines have zero run, so their gradient is undefined.","Division by zero is undefined."],
[16,"Section B — Parallel and perpendicular lines","Special gradients","A horizontal line is drawn on a coordinate grid. Its gradient is:",["0","Undefined","1","−1"],0,"Horizontal lines have zero rise, so their gradient is 0.","No rise means gradient 0."],
[17,"Section C — Distance between two points","Distance from a diagram","The diagram shows points A(0, 0) and B(3, 4). Use the scratchpad or notebook to find the distance AB.",["5","7","1","√7"],0,"Distance = √(3² + 4²) = 5.","Use Pythagoras.",[["A",0,0],["B",3,4]],true],
[18,"Section C — Distance between two points","Distance from a diagram","The diagram shows points A(2, 5) and B(6, 12). Use the scratchpad or notebook to find the distance AB.",["√65","√49","7","13"],0,"Distance = √(4² + 7²) = √65.","Build the right triangle first.",[["A",2,5],["B",6,12]],true],
[19,"Section C — Distance between two points","Distance from a diagram","The diagram shows points A(−1, −1) and B(2, 3). Use the scratchpad or notebook to find the distance AB.",["5","√10","√20","4"],0,"Distance = √(3² + 4²) = 5.","Find horizontal and vertical changes.",[["A",-1,-1],["B",2,3]],true],
[20,"Section C — Distance between two points","Distance from a diagram","The diagram shows a vertical segment from A(4, 7) to B(4, −1). What is the distance AB?",["8","7","4","√8"],0,"The distance is |7 − (−1)| = 8.","Same x-coordinate means vertical distance.",[["A",4,7],["B",4,-1]],false],
[21,"Section C — Distance between two points","Distance from a diagram","The diagram shows a horizontal segment from A(−3, 2) to B(5, 2). What is the distance AB?",["8","√8","6","4"],0,"The distance is |5 − (−3)| = 8.","Same y-coordinate means horizontal distance.",[["A",-3,2],["B",5,2]],false],
[22,"Section C — Distance between two points","Distance from a diagram","The diagram shows points A(1, 1) and B(4, 5). Use the scratchpad or notebook to find the distance AB.",["5","√16","√20","4"],0,"Distance = √(3² + 4²) = 5.","Use Pythagoras.",[["A",1,1],["B",4,5]],true],
[23,"Section C — Distance between two points","Distance from a diagram","The diagram shows a vertical segment from A(−2, −3) to B(−2, 5). What is the distance AB?",["8","5","√8","3"],0,"The distance is |5 − (−3)| = 8.","Same x-coordinate means vertical distance.",[["A",-2,-3],["B",-2,5]],false],
[24,"Section C — Distance between two points","Distance from a diagram","The diagram shows a horizontal segment from A(0, 10) to B(−6, 10). What is the distance AB?",["6","10","√36","√10"],0,"The distance is |0 − (−6)| = 6.","Same y-coordinate means horizontal distance.",[["A",0,10],["B",-6,10]],false]
];
window.skillrPracticeQuestions=raw.map((q,i)=>({id:`ac9m9a03-p-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9M9A03",bank:"practice",section:q[1],sourceNumber:q[0],skill:q[2],printable:true,type:"single",question:q[3],audioPrompt:q[3],visual:"",visualHtml:Array.isArray(q[8])?coord(q[8],q[9]):"",visualMeta:{type:Array.isArray(q[8])?"coordinate-diagram":"none",alt_text:Array.isArray(q[8])?"Coordinate diagram for gradient or distance question.":""},answers:q[4],correct:q[5],explanation:`${q[6]}\nHint: ${q[7]}`,structuredExplanation:{summary:q[6],hint:q[7]},qualitySchema:"production-v1"}));
window.quizQuestions=window.skillrPracticeQuestions;
