"use strict";
const q=(id,skill,question,answers,correct,summary,hint)=>({id,curriculumCode:"AC9M7A06",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation:`${summary}\nHint: ${hint}`,structuredExplanation:{summary,hint},qualitySchema:"production-v2"});
window.skillrTestQuestions=[
q("ac9m7a06-t-001","substitution","For V=lwh, find V when l=9 cm, w=4 cm and h=6 cm.",["216 cm³","108 cm³","54 cm³","19 cm³"],0,"V=9×4×6=216 cm³.","Multiply all three dimensions."),
q("ac9m7a06-t-002","systematic variation","For V=lwh, l=5 and w=8 are fixed. If h changes from 3 to 7, by how much does V increase?",["160","40","280","4"],0,"V=40h, so ΔV=40(7−3)=160.","Use change in h rather than calculating from scratch twice."),
q("ac9m7a06-t-003","reverse formula","A prism has V=420 cm³, l=10 cm and w=7 cm. Find h.",["6 cm","5 cm","30 cm","60 cm"],0,"h=420÷(10×7)=6 cm.","Divide by the fixed product lw."),
q("ac9m7a06-t-004","spreadsheet reasoning","A spreadsheet uses =2*A1-3*B1. If A1=9 and B1=4, what is the result?",["6","30","−6","42"],0,"2(9)−3(4)=18−12=6.","Substitute carefully with multiplication first."),
q("ac9m7a06-t-005","change analysis","For P=2a+5b−c, a and c stay fixed. If b increases by 4, how does P change?",["It increases by 20","It increases by 9","It decreases by 20","It increases by 4"],0,"ΔP=5×4=20.","Only the changing variable contributes to ΔP."),
q("ac9m7a06-t-006","distance model","A vehicle travels 75 km/h for 2.5 h. What distance does d=st predict?",["187.5 km","150 km","77.5 km","300 km"],0,"d=75×2.5=187.5 km.","Multiply speed by time."),
q("ac9m7a06-t-007","two-variable scaling","In d=st, speed is multiplied by 1.5 and time by 2. What happens to distance?",["It becomes 3 times as large","It becomes 2.5 times as large","It becomes 1.5 times as large","It is unchanged"],0,"New d=(1.5s)(2t)=3st.","Multiply scale factors."),
q("ac9m7a06-t-008","table interpretation","At fixed time 4 h, distances are 120, 200 and 280 km. Which speeds produced them?",["30, 50, 70 km/h","40, 60, 80 km/h","30, 40, 50 km/h","120, 200, 280 km/h"],0,"s=d÷4, giving 30, 50 and 70 km/h.","Reverse d=st."),
q("ac9m7a06-t-009","sensitivity","For y=7x−2z+5, x increases by 3 and z stays fixed. What is Δy?",["21","7","6","−6"],0,"Δy=7×3=21.","Coefficient times change."),
q("ac9m7a06-t-010","negative sensitivity","For y=7x−2z+5, z increases by 4 and x stays fixed. What is Δy?",["−8","+8","−2","+4"],0,"Δy=−2×4=−8.","Keep the negative sign."),
q("ac9m7a06-t-011","coefficient interpretation","Which statement is valid for y=6a+b when a and b are measured on comparable scales?",["A one-unit change in a has a larger direct effect than a one-unit change in b","a is always more important in every context","b has no effect","The model proves a causes y"],0,"The coefficients give per-unit direct effects; they do not by themselves prove universal importance or causation.","Interpret coefficients narrowly."),
q("ac9m7a06-t-012","one-variable-at-a-time","Why hold other variables constant during a sensitivity test?",["To isolate the effect of the variable being changed","To make all outputs equal","To remove the need for a formula","To guarantee a correct model"],0,"Holding other inputs fixed lets you attribute output changes to the selected input.","Think controlled comparison."),
q("ac9m7a06-t-013","multi-variable change","For F=4x+3y−2z, x rises by 1, y rises by 2 and z falls by 3. What is ΔF?",["16","4","10","−2"],0,"ΔF=4(1)+3(2)−2(−3)=4+6+6=16.","Use signed changes."),
q("ac9m7a06-t-014","error analysis","A student says doubling both l and w in V=lwh doubles V when h is fixed. What is correct?",["V becomes 4 times as large","V doubles","V becomes 8 times as large","V is unchanged"],0,"(2l)(2w)h=4lwh, so volume quadruples.","Multiply both scale factors."),
q("ac9m7a06-t-015","model interpretation","A sensitivity table shows output changes of +2, +5 and −7 for one-unit increases in x, y and z respectively. Which input has greatest absolute one-unit effect?",["z","y","x","All equal"],0,"The absolute changes are 2, 5 and 7, so z has the greatest magnitude of effect in this comparison.","Compare absolute values when direction is not the question."),
q("ac9m7a06-t-016","reasoning","For F=3x+2y−4z+15, which change leaves F unchanged?",["x+2, y−1, z+1","x+1, y+1, z+1","x+2, y+2, z unchanged","x unchanged, y+2, z+1"],0,"For the first change, ΔF=6−2−4=0.","Test the net change, not the new full value.")];
window.quizQuestions=window.skillrTestQuestions;