"use strict";
// 20260906-y1-original-v1 - generated from the canonical Year 1 bank.
window.skillrTestQuestions = [
  {
    "id": "AC9M1N04-T01",
    "questionId": "T01",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Start at 9. Jump forward 1 to 10, then forward 6. What is 9 + 7?",
    "explanation": "Seven is one and six. The jumps finish at sixteen.",
    "skill": "Read split number-line jumps",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "15",
      "16",
      "17"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-T02",
    "questionId": "T02",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "8 + 8 = 16. Which fact has a total one more than 16?",
    "explanation": "Only one of the two eights increases by one. The total increases from 16 to 17.",
    "skill": "Identify a near-double fact",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "9 + 9 = 18",
      "8 + 9 = 17",
      "8 + 7 = 15"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-T03",
    "questionId": "T03",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Use 6 + 9 = 15. What is 15 − 6?",
    "explanation": "Removing one part from the whole leaves the other part, nine.",
    "skill": "Use a related addition fact",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "9",
      "15",
      "6"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-T04",
    "questionId": "T04",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "7 + 7 = 14. Work out 7 + 8 and tell how the double helps.",
    "explanation": "Eight is one more than seven, so the total is one more than fourteen.",
    "skill": "Explain a near-double strategy",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "Accept 15 with an explanation or model showing one extra added to the known double.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "15; one more than 14.",
    "modelAnswer": "15; one more than 14."
  },
  {
    "id": "AC9M1N04-T05",
    "questionId": "T05",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "To work out 16 − 7, take away 6 first. What is the next step?",
    "explanation": "Sixteen minus six reaches ten. Seven is six and one, so take away one more.",
    "skill": "Complete a bridge-through-ten strategy",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "10 − 1",
      "10 + 1",
      "10 − 7"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-T06",
    "questionId": "T06",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "The whole is 17. One part is 8. Find the other part.",
    "explanation": "Eight and nine make seventeen. The missing part is nine.",
    "skill": "Find a missing part",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "10",
      "8",
      "9"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-T07",
    "questionId": "T07",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "A row has 11 counters. Five are crossed out. Which equation matches?",
    "explanation": "The model starts with eleven and removes five. Six remain.",
    "skill": "Match a crossed-out model",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": {
      "type": "grid",
      "rows": [
        [
          "×",
          "×",
          "×",
          "×",
          "×",
          "●",
          "●",
          "●",
          "●",
          "●",
          "●"
        ]
      ],
      "caption": "× crossed-out counter; ● remaining counter."
    },
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "11 + 5 = 16",
      "11 − 5 = 6",
      "6 − 5 = 1"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-T08",
    "questionId": "T08",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "The parts are 5 and 8. The whole is 13. Write one addition equation and one subtraction equation.",
    "explanation": "The addition joins the two parts. The subtraction removes one part from the whole.",
    "skill": "Create a related fact pair",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "create",
    "visualModel": null,
    "acceptanceNote": "Accept either order of 5 + 8 = 13 and either 13 − 5 = 8 or 13 − 8 = 5; reversed equality forms are valid.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "5 + 8 = 13; 13 − 5 = 8",
    "modelAnswer": "5 + 8 = 13; 13 − 5 = 8"
  },
  {
    "id": "AC9M1N04-T09",
    "questionId": "T09",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Lee works out 13 + 4 by saying “13, 14, 15, 16”. What answer should Lee get?",
    "explanation": "Do not count the starting number as a step. Four steps after 13 are 14, 15, 16, 17.",
    "skill": "Correct a count-on result",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "18",
      "16",
      "17"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-T10",
    "questionId": "T10",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Compare 5 + 9 and 6 + 8. Which is true?",
    "explanation": "Both totals are fourteen. One part gains one while the other loses one.",
    "skill": "Compare two decompositions",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "6 + 8 is greater.",
      "They are equal.",
      "5 + 9 is greater."
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-T11",
    "questionId": "T11",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "__ − 4 = 12\nWhat was the starting number?",
    "explanation": "Add the removed four back to twelve. The starting number was sixteen.",
    "skill": "Find a missing starting amount",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "18",
      "8",
      "16"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-T12",
    "questionId": "T12",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Work out 18 − 9. Show a way to check your answer.",
    "explanation": "Nine and nine make eighteen. Removing one nine leaves the other nine.",
    "skill": "Check subtraction with addition",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "Accept 9 with a valid check, including 9 + 9 = 18, a counter model, or counting nine steps from 9 to 18.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "9; 9 + 9 = 18",
    "modelAnswer": "9; 9 + 9 = 18"
  },
  {
    "id": "AC9M1N04-T13",
    "questionId": "T13",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "A ten-frame is full. A second ten-frame has 4 counters. Remove those 4 counters. How many remain?",
    "explanation": "The full ten-frame stays unchanged. Removing the four extra counters leaves ten.",
    "skill": "Interpret two ten-frames",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": {
      "type": "grid",
      "rows": [
        [
          "●",
          "●",
          "●",
          "●",
          "●"
        ],
        [
          "●",
          "●",
          "●",
          "●",
          "●"
        ],
        [
          "×",
          "×",
          "×",
          "×",
          "○"
        ],
        [
          "○",
          "○",
          "○",
          "○",
          "○"
        ]
      ],
      "caption": "First two rows: full frame. Last two rows: second frame. × removed; ○ empty."
    },
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "10",
      "4",
      "14"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-T14",
    "questionId": "T14",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Which addition has the greatest total?",
    "explanation": "The totals are 15, 18 and 17. Eighteen is the greatest.",
    "skill": "Compare calculated totals",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "9 + 9",
      "7 + 8",
      "10 + 7"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-T15",
    "questionId": "T15",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Start at 15. Move back 5, then back 3. Where do you finish?",
    "explanation": "Fifteen minus five reaches ten. Three more steps back reaches seven.",
    "skill": "Read split backward jumps",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "8",
      "10",
      "7"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-T16",
    "questionId": "T16",
    "curriculumCode": "AC9M1N04",
    "bank": "test",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Write a subtraction equation with an answer of 6. Start with a number greater than 10 and no greater than 20.",
    "explanation": "Choose a starting number and remove enough to leave six. Fourteen minus eight is one example.",
    "skill": "Create a constrained subtraction",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "create",
    "visualModel": null,
    "acceptanceNote": "Accept n − (n−6) = 6 for any whole-number n from 11 to 20, with both numbers shown correctly.",
    "printable": true,
    "type": "text",
    "correct": "14 − 8 = 6",
    "acceptedAnswers": [
      "11-5=6",
      "12-6=6",
      "13-7=6",
      "14-8=6",
      "15-9=6",
      "16-10=6",
      "17-11=6",
      "18-12=6",
      "19-13=6",
      "20-14=6",
      "6=11-5",
      "6=12-6",
      "6=13-7",
      "6=14-8",
      "6=15-9",
      "6=16-10",
      "6=17-11",
      "6=18-12",
      "6=19-13",
      "6=20-14"
    ],
    "answerFormat": "equation"
  }
];
