"use strict";
const T=(id,skill,q,a,c,e,h)=>({id:`ac9e5la08-t-${String(id).padStart(3,"0")}`,curriculumCode:"AC9E5LA08",bank:"test",skill,printable:true,type:"single",question:q,audioPrompt:q,visual:"",visualHtml:"",answers:a,correct:c,explanation:`${e}\nHint: ${h}`,structuredExplanation:{summary:e,hint:h},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
T(1,"roots","The root ‘aud’ means hear. Which word is most likely connected to hearing?",["auditory","visible","thermal"],0,"‘Auditory’ is connected with hearing.","Use the root as a meaning clue."),
T(2,"roots","The root ‘geo’ means earth. Which word belongs to this meaning family?",["geothermal","telephone","biography"],0,"‘Geothermal’ combines earth and heat.","Identify the root before using context."),
T(3,"roots","If ‘port’ means carry, what does ‘portable’ most likely mean?",["able to be carried","able to be heard","able to be frozen"],0,"The root contributes the carrying meaning.","Combine root and suffix meaning."),
T(4,"technical vocabulary","Which term is most precise for water changing from gas to liquid?",["condensation","water changing","weather"],0,"‘Condensation’ names the scientific process exactly.","Choose the field-specific term."),
T(5,"technical vocabulary","Which term precisely describes the place where an organism lives?",["habitat","area thing","position"],0,"‘Habitat’ is the ecological term.","Prefer exact domain vocabulary."),
T(6,"precision","Which is the most precise sentence?",["The bird moved.","The peregrine falcon dived toward its prey.","The animal did something."],1,"Specific nouns and verbs create precise meaning.","Replace broad wording with exact choices."),
T(7,"precision","Which phrase best suits a formal science explanation?",["really bad heat","a rapid increase in temperature","super-hot stuff"],1,"The second phrase is precise and formal.","Match vocabulary to audience and purpose."),
T(8,"precision","Why might ‘hazardous’ be better than ‘bad’ in a safety report?",["It specifies that something presents danger.","It is longer.","It makes the report fictional."],0,"The word narrows the type of problem.","Ask what exact meaning the word adds."),
T(9,"word building","If ‘micro’ means small and ‘bio’ means life, what does ‘microbiology’ most likely study?",["very small living things","large rocks","distant sounds"],0,"The word parts point to small-scale life.","Combine known morphemes."),
T(10,"word building","If ‘tele’ means distant and ‘phon’ means sound, what does ‘telephone’ suggest?",["sound over distance","heat measurement","earth writing"],0,"The parts combine to indicate distant sound communication.","Use both roots."),
T(11,"context","An unfamiliar word contains a known root, but the root clue seems incomplete. What should you do?",["Use the whole word and sentence context as well.","Ignore context.","Assume the root gives the full definition."],0,"Roots are useful clues, not always complete modern definitions.","Cross-check morphology with context."),
T(12,"word history","What can studying Greek and Latin roots reveal?",["Relationships among words and clues about how meanings developed.","That every English word is Latin.","A guaranteed pronunciation rule."],0,"Roots support meaning inference and word-history exploration.","Keep claims about origins cautious."),
T(13,"audience","When is it helpful to explain a technical term?",["When the audience may not know it and understanding depends on it.","Never.","Only when the word has four letters."],0,"Precision should remain accessible to the intended reader.","Think audience needs."),
T(14,"transfer","Which revision improves precision most? ‘The machine moved the water.’",["The pump circulated water through the filter.","The thing did water.","The nice machine moved it."],0,"The revision names the device, action and destination precisely.","Specify who/what did what."),
T(15,"misconception","Which statement is false?",["A longer word is automatically more precise.","A specialist term can be more precise in its field.","Context helps confirm root-based inferences."],0,"Word length alone does not create precision.","Judge fit and meaning, not length."),
T(16,"concept","Which statement best explains precise vocabulary?",["Writers choose words that express the intended meaning accurately for the topic, audience and purpose.","Writers always choose the longest available word.","Technical terms should replace all everyday words."],0,"Precision is about exact fit, not difficulty.","Match word choice to meaning and context.")
];window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;