from common import *
def tiles(n,y=120,w=55):return ''.join(rect(80+i*w,y,w,55,'#bde0f5') for i in range(n))
def balance(n):
    s=line(135,95,505,95)+polybase()+line(170,95,170,165)+line(470,95,470,165)+line(115,165,225,165)+line(385,165,555,165)+rect(142,115,56,45,'#f2c96e')
    for i in range(n):s+=rect(393+(i%5)*31,140-(i//5)*27,27,25,'#bde0f5')
    return s+txt(320,255,'Level balance; all counters have equal mass',18)
def polybase():return '<path d="M320 95L280 220H360Z" fill="#dce5ec" stroke="#17324d" stroke-width="2"/>'
V={'strips':(rect(80,60,350,55,'#83c6ee')+txt(55,95,'A')+rect(80,170,250,55,'#f2c96e')+txt(55,205,'B'),'Two strips share a left endpoint; A extends farther right than B.'),'six':(tiles(6)+line(80,85,410,85)+txt(245,60,'Ribbon'),'Ribbon aligned with six equal touching tiles.'),'towers':(''.join(rect(170,230-i*40,60,40,'#83c6ee') for i in range(1,4))+''.join(rect(400,230-i*40,60,40,'#f2c96e') for i in range(1,6))+txt(200,270,'A')+txt(430,270,'B'),'Tower A is three equal blocks high; B is five of the same blocks high, with bases aligned.'),'five':(balance(5),'Level balance with one parcel on the left and five equal-mass counters on the right.'),'seven':(balance(7),'Level balance with one stone on the left and seven equal-mass counters on the right.'),'units':(tiles(4,75,110)+tiles(8,180,55)+txt(45,110,'A')+txt(45,215,'B'),'The same total length is covered by four large tiles in row A and eight smaller tiles in row B.'),'testlength':(tiles(5)+line(80,85,355,85)+txt(217,60,'Cord'),'Cord aligned with five equal touching tiles.')}
P=[
q('length_compare','Which strip is longer?','A','B','They have equal length','Their left ends line up; A extends farther at the other end.','strips'),
q('measure_length','How long is the ribbon in these tile units?','6 tiles','5 tiles','7 tiles','Six equal tiles touch end to end and cover the ribbon.','six'),
q('height_difference','How many blocks taller is tower B than tower A?','2 blocks','3 blocks','5 blocks','B has 5 blocks and A has 3; the difference is 2.','towers'),
q('capacity_measure','Four full cups fill an empty pot exactly. Every cup holds the same amount. What is the pot’s capacity?','4 cupfuls','1 cupful','5 cupfuls','The pot holds four of the chosen full-cup units.'),
q('mass_measure','What mass does the level balance show for the parcel?','5 counter units','4 counter units','6 counter units','A level balance shows equal masses on its two sides.','five'),
q('length_conservation','Two cords each measure 8 identical sticks long. One cord is moved to another table without stretching. What happens to its length?','It stays 8 sticks long','It becomes longer','It becomes shorter','Moving an object does not change its length.'),
q('gaps','A child leaves gaps between five measuring tiles. How should the measurement be repaired?','Slide the tiles together and measure again','Count the gaps as extra tiles','Keep the gaps and use the same count','Tiles must touch without gaps to measure length in tile units.'),
q('overlaps','Which row gives a fair measurement from one end of a strip to the other?','Equal tiles touching without overlap','Equal tiles overlapping','Mixed-size tiles with gaps','A row of uniform units must cover the length without missing or double-counting parts.'),
q('capacity_unit','Which is a useful way to measure a jug’s capacity with a small cup?','Count equal full cupfuls that fill it','Count cups filled to different levels','Count how tall the cup looks','Each unit must contain the same amount.'),
q('mass_unit','Which set is suitable for measuring mass on a balance?','Counters all of the same mass','A mixture of heavy and light counters','Counters chosen only for their colour','Uniform mass units are needed for the count to be meaningful.'),
q('capacity_difference','A teapot holds 6 cupfuls and a saucepan 9 of the same cupfuls. How much more does the saucepan hold?','3 cupfuls','15 cupfuls','2 cupfuls','Nine minus six is three equal cup units.'),
q('order_mass','A shell balances 4 cubes, a toy 6 cubes and a stone 7 cubes. All cubes have equal mass. Which order is lightest to heaviest?','Shell, toy, stone','Stone, toy, shell','Toy, shell, stone','With the same mass unit, compare counts: 4, then 6, then 7.'),
q('length_difference','A bookmark is 9 small sticks long and an envelope 6 of the same sticks long. What is the difference?','3 sticks','15 sticks','2 sticks','Subtract six equal units from nine.'),
q('unit_size','Both rows cover the same length. Which row uses smaller tiles?','B','A','Both use the same tile size','Eight tiles fit where only four larger tiles fit.','units'),
q('unfair_comparison','A mat measures 7 large tiles long. A shelf measures 9 small tiles long. Can the counts alone tell which is longer?','No; the units differ','Yes; the shelf must be longer','Yes; the mat must be longer','Compare using the same-sized units before comparing the counts.'),
q('smaller_length_unit','A strip is a little longer than 3 large tiles. How can you measure it more closely using whole units?','Use smaller equal tiles','Round up without measuring','Mix large and small tiles and count them all alike','Smaller uniform units can measure the remaining length more closely.'),
q('smaller_capacity_unit','A bottle holds 2 full cupfuls and part of another. How could you measure its capacity more closely in whole units?','Remeasure with equal full spoonfuls','Count the partly filled cup as a full cup','Use a different-sized cup for each pour','A smaller uniform unit can describe the amount more precisely.'),
q('smaller_mass_unit','A toy is heavier than 3 large blocks but lighter than 4. How could its mass be measured more closely?','Use smaller equal-mass counters','Use larger blocks','Use any mixture of counters and count them equally','Smaller mass units make a finer comparison on the balance.'),
q('capacity_not_height','A tall narrow bottle and a short wide bottle each hold 5 of the same cupfuls. Which has greater capacity?','Neither; their capacities are equal','The taller bottle','The wider bottle','Their measured capacities are equal despite different shapes.'),
q('mass_not_size','A large empty box balances 2 cubes. A small metal toy balances 8 identical cubes. Which is heavier?','The metal toy','The empty box','They have equal mass','The toy balances more of the same mass units, regardless of its size.'),
q('same_units','Two children use different-sized footsteps to measure a path and get different counts. How can they compare fairly?','Both measure with the same stick length','Use their original counts as if the units match','Choose the larger count automatically','Using one common length unit makes the counts comparable.'),
q('spill','Seven cupfuls are poured towards a bowl, but some water spills outside. Does this reliably measure the bowl’s capacity?','No; repeat without spilling','Yes; count every pour regardless of spills','Yes; add one extra cup to the count','Some of the counted water did not enter the bowl.'),
q('mixed_mass','A balance holds six counters: three light and three heavy. Can its mass be described as six equal counter units?','No; the counters are not uniform mass units','Yes; any six counters are equal units','Yes; only the number matters','Counting unlike masses as equal units gives a misleading measurement.'),
task('measure_compare','Measure two safe objects using the same small informal length unit. Record both counts and compare the lengths.','Two actual measurements made with a uniform unit, with a comparison consistent with the counts.','Check alignment, no gaps/overlaps and a stated unit. If a unit does not fit closely, use a smaller uniform unit or describe the remainder.')]
T=[
q('read_length','What is the cord’s length in the tile units shown?','5 tiles','4 tiles','6 tiles','Five equal touching tiles cover the cord from end to end.','testlength'),
q('order_height','Three plants are 8, 5 and 7 identical blocks tall. Which measurement belongs to the shortest?','5 blocks','8 blocks','7 blocks','Using one common unit, the smallest count gives the shortest height.'),
q('capacity_sum','An empty tub is filled exactly by 4 scoopfuls and then 2 more. The scoops are all equally full. What is its capacity?','6 scoopfuls','2 scoopfuls','8 scoopfuls','Four plus two equals six uniform scoop units.'),
q('read_mass','What mass is shown for the stone on the level balance?','7 counter units','6 counter units','8 counter units','The stone balances seven identical mass units.','seven'),
q('start_alignment','The first measuring tile starts after the left end of a strip. What is the problem?','Part of the strip has not been measured','The strip becomes shorter','The tiles are automatically too small','Measurement must begin at the object’s endpoint.'),
q('full_units','Which measurement uses uniform capacity units?','Five full cupfuls from the same cup','Three full cups and two half-filled cups counted as five','Five cups of different sizes counted equally','Each full use of the same cup measures the same amount.'),
q('capacity_compare','A can holds 8 spoonfuls and a mug 11 of the same spoonfuls. How much less does the can hold?','3 spoonfuls','19 spoonfuls','2 spoonfuls','Eleven minus eight is three.'),
q('mass_compare','A ball balances 9 counters and a toy car 6 of the same counters. How much heavier is the ball?','3 counter units','15 counter units','6 counter units','Compare the masses with subtraction: 9 minus 6.'),
q('unit_relation','A table measures 12 short sticks or 6 long sticks. Both measurements are careful. Can both be correct?','Yes; the sticks have different lengths','No; a table can have only one numerical measure','No; the larger count must be wrong','The count depends on the size of the chosen unit.'),
q('different_mass_units','A toy balances 4 heavy blocks and a book balances 10 light counters. Can you compare their masses using those counts alone?','No; the mass units are different','Yes; the book must be heavier','Yes; the toy must be heavier','The units must be comparable before their counts can be compared.'),
q('precision_length','A card extends beyond the last whole measuring block. What would improve the measurement?','Remeasure with smaller equal units','Ignore the part sticking out','Overlap the last two blocks','Smaller uniform units can represent the remaining length more closely.'),
q('precision_capacity','A tiny container holds less than one cupful. Which informal unit would be more useful?','A small spoonful','A bucketful','A large jugful','A smaller unit gives a useful count for a small capacity.'),
q('precision_mass','A shell is between 2 and 3 large blocks in mass. Which change helps?','Use smaller equal-mass units','Choose larger blocks','Count different masses as identical','Finer units allow a closer measurement.'),
q('capacity_vs_contents','Two identical bottles are empty and half full. Do they have the same capacity?','Yes; each can hold the same total amount','No; the half-full bottle has greater capacity','No; an empty bottle has no capacity','Capacity is how much a container can hold, not how much is currently inside.'),
q('repair_units','A child measures with a row mixing long and short tiles. What should be changed?','Use tiles of equal length','Count the tiles twice','Remove only the last tile','A length count needs uniform units.'),
task('practical_measure','With an adult, choose a safe container and measure its capacity using equal full small cups or spoonfuls. Record your method and result.','A real count in a stated uniform capacity unit, with any partial final unit described or remeasured using smaller units.','Use safe materials such as water over a tray. Check equal fills and no spills; accept any valid measured result.')]
write('AC9M2M01',P,T,V)
