"use strict";
window.skillrTestQuestions=[
["t-001","source triangulation","Three sources make the same battery claim: manufacturer advertising, an independent controlled comparison, and a customer review. Which should carry greatest weight?",["The independent controlled comparison, while still checking its method and sample","The manufacturer because it knows its product best","The customer review because personal experience is primary evidence"],0,"Independent systematic evidence is generally stronger for comparative performance claims than advertising or anecdotes."],
["t-002","claim scope","A study tests one bamboo design at one shaking intensity and concludes 'bamboo is the safest earthquake material'. What is the strongest evaluation?",["The conclusion is broader than the evidence; more designs, materials and loading conditions are needed","The conclusion is valid because a shake-table test was used","The conclusion should be rejected because bamboo cannot be tested scientifically"],0,"Claim scope must match the range of evidence collected."],
["t-003","conflicting studies","Two credible studies report different battery lifetimes. One uses a high continuous load and one a low intermittent load. What is the best interpretation?",["The results may differ because battery performance depends on operating conditions","One study must be fabricated because credible studies cannot disagree","Average the two lifetimes without considering methods"],0,"Method and context can explain apparently conflicting evidence."],
["t-004","bias evaluation","A manufacturer-funded battery study uses transparent methods and publishes raw data. How should it be treated?",["Consider the potential conflict of interest but evaluate the methods and seek independent replication","Reject it automatically because funding makes data invalid","Accept it automatically because raw data remove all bias"],0,"Potential bias is a reason for scrutiny, not automatic acceptance or rejection."],
["t-005","cultural governance","A publicly accessible report includes First Nations ecological knowledge that the report says should not be reproduced without community permission. What should a student do?",["Respect the stated restriction and seek appropriate permission before reproducing the knowledge","Copy it because public access cancels cultural protocols","Remove the community name and reproduce it anonymously"],0,"Public accessibility does not necessarily remove cultural governance or permission requirements."],
["t-006","ethical secondary data","A student finds precise locations of a threatened species in an open dataset. Which use is most responsible?",["Check guidance on sensitivity and use a less precise location if publication could increase harm","Publish exact coordinates because open data must be repeated exactly","Exclude the species from all scientific arguments"],0,"Ethical use balances evidence needs with foreseeable risks from sensitive data."],
["t-007","accurate representation","A student paraphrases community-shared ecological knowledge but changes its meaning to fit a preferred argument. What is the main problem?",["The evidence has been misrepresented and cultural context has not been respected","Paraphrasing removes the need for attribution","Scientific arguments should always replace cultural knowledge with laboratory data"],0,"Evidence must be represented accurately, regardless of its source."],
["t-008","evidence hierarchy","Which evidence most strongly supports the claim that one building design reduces earthquake damage?",["Comparable damage measurements across matched structures or controlled structural tests","A builder's confidence in the design","A photograph selected because it shows little damage"],0,"Direct comparative evidence is stronger than confidence or selectively chosen examples."],
["t-009","causal claim","A region with more bamboo houses reports fewer earthquake injuries. Why does this correlation alone not prove bamboo caused the difference?",["Other factors such as earthquake intensity, building quality and population exposure may differ","Injury data cannot be used in scientific arguments","Correlations are never useful evidence"],0,"Potential confounding factors must be considered before making causal claims."],
["t-010","lifecycle claim","Two materials have similar earthquake performance. A student claims bamboo is more sustainable because it grows quickly. What is missing?",["Lifecycle evidence about processing, transport, durability, replacement and environmental impacts","A photograph showing bamboo plants","The market price of concrete"],0,"A sustainability claim requires evidence across the relevant lifecycle, not one favourable property."],
["t-011","battery fair test","Brand A is tested at 1.0 A and Brand B at 0.5 A. Brand B lasts longer. Which conclusion is justified?",["The test does not isolate brand because electrical load differs","Brand B is proven superior because its measured time is longer","Brand A would always win if both loads were increased"],0,"A fair comparison requires important operating conditions such as load to be controlled."],
["t-012","battery endpoint","Two teams compare battery life. One stops timing at 1.0 V and the other when a device turns off. Why can their values differ?",["They use different operational definitions of 'battery life'","Voltage thresholds do not affect measured battery life","Only battery age can cause different results"],0,"Evidence must use clearly defined and comparable measurement criteria."],
["t-013","argument construction","Which sequence best describes an evidence-based scientific argument?",["Make a specific claim, present relevant evidence, explain how it supports the claim, and acknowledge limitations","Choose a conclusion first, then include only evidence that agrees","List several sources without explaining their relevance"],0,"An argument connects evidence to a claim through reasoning and evaluates limitations."],
["t-014","citation and traceability","Why is a complete citation important when secondary data are central to an argument?",["Readers can locate the original evidence, examine context and judge whether it was represented accurately","A citation guarantees that the source is scientifically correct","Citation is mainly a formatting requirement with no effect on evaluation"],0,"Traceability allows evidence and interpretation to be checked."],
["t-015","competing evidence","A controlled experiment supports a claim, while a larger observational dataset shows no clear relationship. What is the best response?",["Examine the strengths, conditions and limitations of both sources before forming a qualified conclusion","Ignore the observational data because experiments are always perfect","Reject the experiment because larger datasets are always superior"],0,"Different evidence types have different strengths and limitations and should be evaluated rather than ranked mechanically."],
["t-016","synthesis","Which response best demonstrates AC9S8I07?",["Use credible and appropriately cited evidence to build a reasoned claim, compare competing evidence and follow ethical and cultural protocols","Select the source that most strongly agrees with the student's opinion","Use as many secondary sources as possible without evaluating their quality"],0,"The code integrates evidence-based argument, claim evaluation and responsible use of secondary information."]
].map(([id,skill,question,answers,correct,explanation])=>({id:`ac9s8i07-${id}`,curriculumCode:"AC9S8I07",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation,structuredExplanation:{summary:explanation,hint:"Ask whether the evidence is relevant, sufficient, credible and fairly compared, then check attribution, sensitivity and cultural permissions."},qualitySchema:"production-v2"}));