"use strict";
const q=(id,skill,question,answers,correct,summary,hint)=>({id,curriculumCode:"AC9M7M01",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation:`${summary}\nHint: ${hint}`,structuredExplanation:{summary,hint},qualitySchema:"production-v2"});
window.skillrTestQuestions=[
q("ac9m7m01-t-001","formula reasoning","Which statement best explains A=1/2 bh for a triangle?",["Two matching triangles can form a parallelogram of area bh","A triangle has half the perimeter of a rectangle","The sloping sides average to h","Every triangle fits inside a square"],0,"Duplicating the triangle forms a parallelogram with area bh, so one triangle has half that area.","Use a doubling argument."),
q("ac9m7m01-t-002","perpendicular height","A parallelogram has base 18 cm, slanted side 11 cm and perpendicular height 7 cm. What is its area?",["126 cm²","198 cm²","63 cm²","77 cm²"],0,"Area=18×7=126 cm².","Use perpendicular height, not slanted side."),
q("ac9m7m01-t-003","triangle area","A triangle has base 16 cm and perpendicular height 13 cm. Find its area.",["104 cm²","208 cm²","58 cm²","29 cm²"],0,"A=1/2×16×13=104 cm².","Halve bh."),
q("ac9m7m01-t-004","reverse triangle","A triangle has area 63 m² and base 14 m. Find its height.",["9 m","4.5 m","7 m","18 m"],0,"63=7h, so h=9 m.","Use h=2A/b."),
q("ac9m7m01-t-005","reverse parallelogram","A parallelogram has area 132 cm² and height 11 cm. Find its base.",["12 cm","6 cm","11 cm","22 cm"],0,"b=132÷11=12 cm.","Rearrange A=bh."),
q("ac9m7m01-t-006","invariance","A triangle keeps base 20 cm and height 9 cm while its top vertex slides sideways. Which statement is correct?",["Its area remains 90 cm²","Its area changes with the sloping sides","Its area becomes 180 cm²","Its area cannot be known"],0,"A=1/2×20×9=90 cm² and b,h are unchanged.","Track only base and perpendicular height."),
q("ac9m7m01-t-007","comparison","A triangle and parallelogram share base 10 cm and height 12 cm. What is the difference between their areas?",["60 cm²","120 cm²","30 cm²","0 cm²"],0,"Parallelogram=120; triangle=60; difference=60 cm².","Compute both using their own formulas."),
q("ac9m7m01-t-008","scale reasoning","A triangle's base is tripled while its height is reduced to one third. What happens to area?",["It stays the same","It triples","It becomes one third","It becomes 9 times as large"],0,"The scale factors 3 and 1/3 cancel.","Multiply the scale factors."),
q("ac9m7m01-t-009","cost application","A triangular shade sail has base 14 m and height 8 m. Fabric costs $18 per m². What is the cost?",["$1008","$2016","$504","$252"],0,"Area=56 m²; cost=56×18=$1008.","Area first, then cost."),
q("ac9m7m01-t-010","coverage application","A parallelogram lawn has base 20 m and height 12 m. One bag treats 40 m². How many bags are needed?",["6","3","5","12"],0,"Area=240 m²; 240÷40=6.","Use area then coverage rate."),
q("ac9m7m01-t-011","error analysis","A student calculates a parallelogram's area using base × slanted side. What should they use instead?",["Base × perpendicular height","Half base × slanted side","Perimeter × height","Base + height"],0,"Parallelogram area requires the perpendicular height.","Look for the distance between the parallel sides."),
q("ac9m7m01-t-012","equal area","Which triangle has the same area as a parallelogram with base 6 cm and height 10 cm?",["b=12,h=10","b=6,h=10","b=10,h=6","b=15,h=4"],0,"Parallelogram area=60; triangle b=12,h=10 has area 60.","Set 1/2 bh equal to 60."),
q("ac9m7m01-t-013","dynamic geometry","Which change can alter a triangle's shape without altering its area?",["Slide the top vertex parallel to the base while base and height stay fixed","Double the base","Halve the height","Increase both base and height"],0,"Sliding parallel to the base changes sloping sides but preserves base and height.","Area depends only on b and h."),
q("ac9m7m01-t-014","multi-step","A triangular garden has area 96 m² and height 12 m. Fencing is not relevant; what base length gives this area?",["16 m","8 m","12 m","24 m"],0,"96=1/2×b×12=6b, so b=16 m.","Use b=2A/h."),
q("ac9m7m01-t-015","reasoning","A parallelogram has fixed base. Its height increases by 25%. How does its area change?",["It increases by 25%","It doubles","It increases by 50%","It stays unchanged"],0,"With base fixed, area is directly proportional to height.","A=bh."),
q("ac9m7m01-t-016","higher-order","Triangle A has base 18 cm and height 8 cm. Triangle B has base 12 cm. What height gives Triangle B the same area?",["12 cm","8 cm","9 cm","6 cm"],0,"Triangle A area=72 cm². For B, 72=1/2×12×h=6h, so h=12 cm.","Find the target area first." )];
window.quizQuestions=window.skillrTestQuestions;