"use strict";
const q=(n,skill,question,answers,correct,explanation,hint)=>({id:`ac9s7i02-t-${String(n).padStart(3,"0")}`,curriculumCode:"AC9S7I02",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers,correct,explanation,structuredExplanation:{summary:explanation,hint},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
q(1,"plan critique","A method says: “Put a plant near a lamp, add some water and measure growth later.” What is the biggest problem?",["It lacks specific quantities, distances, timing, controls and measurement rules needed for reproducibility","It uses a plant","It has only one verb","It should begin with the conclusion"],0,"The method is too vague for another investigator to repeat consistently.","Identify missing operational detail."),
q(2,"variables","Students test how ramp height affects trolley travel time over 1 m. Which pair is correct?",["IV: ramp height; DV: travel time","IV: travel time; DV: ramp height","IV: trolley; DV: ruler","IV: 1 m; DV: ramp material"],0,"Ramp height is deliberately changed and travel time is measured.","Separate changed from measured."),
q(3,"confound","A class compares two fertilisers but also gives one group twice as much water. Why is the conclusion weakened?",["Water amount is a confounding variable that could affect plant growth","Water becomes the dependent variable","The fertiliser cannot be an IV","Repeats automatically remove the problem"],0,"Changing water with fertiliser prevents a clear attribution of growth differences.","Look for a second factor that changed."),
q(4,"risk control","A beaker of hot water must be moved. Which risk control is best?",["Use tongs or heat-resistant gloves, keep the route clear and allow cooling when possible","Carry it quickly with bare hands","Say “be careful”","Fill it to the brim"],0,"Specific controls should reduce exposure to the identified scald/burn hazard.","Match hazard, exposure and control."),
q(5,"assumption","A field study assumes soil moisture is similar at all sites but never checks it. Why does this matter?",["If moisture differs, it may explain biological differences attributed to another factor","Assumptions cannot affect results","Soil moisture is always constant","The assumption proves the method is fair"],0,"Unverified assumptions can hide confounding factors.","Ask what happens if the assumption is false."),
q(6,"Country/Place","Students find a possible stone artefact during a survey. What is the most appropriate action?",["Leave it in place, avoid publishing sensitive location details, and seek guidance from appropriate Custodians/site authorities","Collect it for the school collection","Wash it and measure it immediately","Post its coordinates online"],0,"Heritage material and locations require appropriate cultural and site authority; students should not disturb or remove them.","Respect Country/Place protocols."),
q(7,"ethics","A student proposes stressing animals to test a hypothesis when a non-harmful observation could answer the same question. What should happen?",["Use the less harmful method","Use the harmful method because experiments are stronger","Increase the sample","Hide the procedure"],0,"Ethical planning minimises unnecessary harm where a safer method can answer the question.","Choose proportionate methods."),
q(8,"repeats","Three trials give 12.1, 12.0 and 18.7 s. What is the best immediate response?",["Check the 18.7 s trial for method or recording issues and repeat if appropriate while retaining the raw value","Delete 18.7 automatically","Average only the two closest results","Change the hypothesis"],0,"An unusual repeat should be investigated rather than silently removed.","Preserve raw data and check anomalies."),
q(9,"sampling","A biodiversity survey samples only beside the path because it is convenient. What is the likely problem?",["Selection bias may make the sample unrepresentative","The path becomes the dependent variable","Convenience sampling always improves validity","No problem if enough species are found"],0,"Sampling locations should follow a defensible rule rather than convenience alone.","Ask whether the sample represents the study area."),
q(10,"method-data match","A hypothesis predicts that increasing temperature speeds dissolving. Which measurement plan best tests it?",["Measure dissolving time for equal sugar masses at several controlled water temperatures with repeats","Record water colour once","Compare different sugars at different temperatures","Ask students which cup looks fastest"],0,"The plan must vary temperature and measure dissolving time while controlling relevant factors.","Match variables to the hypothesis."),
q(11,"systematic bias","A thermometer reads 2°C high at every temperature. Why do repeats not solve the problem?",["Repeats may be consistent but the same systematic offset remains","Repeats automatically calibrate instruments","The error becomes random","Temperature no longer matters"],0,"Systematic error shifts all readings in one direction and is not removed by repetition.","Distinguish precision from accuracy."),
q(12,"pilot","A planned temperature range melts the plastic containers. What should a pilot study lead to?",["Revise the range or equipment before the full investigation","Continue because the original plan must not change","Ignore the damage if data were collected","Remove safety from the report"],0,"Piloting should expose feasibility and safety problems so the method can be revised.","Plans can improve before full testing."),
q(13,"human participants","A class survey asks sensitive questions and records names. Which change is most important?",["Obtain appropriate consent, minimise unnecessary personal data and protect privacy","Use a larger font","Ask more sensitive questions","Publish all responses for transparency"],0,"Human investigations must protect participants and personal information.","Think consent and privacy."),
q(14,"complete method","Which detail is essential if another group must reproduce a light-intensity experiment?",["The lamp distances, exposure time, measurement method, controls and repeats","The author’s favourite result","A decorative diagram only","The final conclusion"],0,"Reproducibility depends on operational details, not just the aim.","What would another group need to repeat it?"),
q(15,"validity","An investigation asks whether salt concentration affects density, but students measure only colour. What is wrong?",["The measured outcome does not test the stated question","Colour is always an IV","The study has too many repeats","The hypothesis is proven"],0,"A valid method measures an outcome relevant to the question or hypothesis.","Check alignment between question and evidence."),
q(16,"synthesis","Which statement best describes planning a strong Year 7 investigation?",["Scientific validity, reproducibility, safety, ethics, assumptions and Country/Place responsibilities should be considered together","Only the number of trials matters","Safety and ethics are added after data collection","A detailed method guarantees a correct hypothesis"],0,"Strong planning integrates evidence needs with reproducibility and responsible practice.","Look for the complete planning framework.")
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
