"use strict";
const Q=[
["results discussion","A report presents a scatter plot with R² = 0.89. Which placement is best?",["Present the numerical result in Results, then interpret what the relationship means and its limitations in Discussion","Put everything only in the Introduction","Mention R² only in the Conclusion","Hide the value because statistics confuse readers"],0,"Results present the statistical evidence; Discussion interprets its meaning, limits and relevance.","Separate evidence from interpretation."],
["audience adaptation","A public infographic and a specialist report use the same dataset. Which difference is most appropriate?",["The infographic uses simpler language and visual summaries while preserving the same scientific meaning","The infographic changes inconvenient values","The specialist report removes uncertainty","The public version omits all evidence"],0,"Audience adaptation changes presentation, not the underlying evidence.","Same science, different communication."],
["misleading scale","A climate infographic uses a very narrow y-axis to make a small change appear dramatic. What is the main issue?",["The visual design may distort the perceived magnitude of the effect","The data values themselves have changed","Narrow scales are always forbidden","The graph has become a qualitative model"],0,"Axis choices can create misleading visual impressions even when numerical values are unchanged.","Design can distort interpretation."],
["trend transparency","A graph displays a smooth trend line but no raw data points. What is lost?",["Transparency about scatter, anomalies and how closely observations support the fitted trend","The ability to label axes","The ability to calculate a mean","All scientific credibility automatically"],0,"Raw observations help readers judge variation and model fit rather than seeing only a simplified trend.","Show the evidence behind the summary."],
["uncertainty language","Which wording best communicates a result with meaningful uncertainty?",["The evidence suggests X is likely under these conditions, although the estimate remains uncertain","The experiment proves X forever","X definitely occurs in every case","Uncertainty means no conclusion can be made"],0,"Scientific language should communicate both the direction of evidence and its limits.","Avoid both overclaiming and unnecessary dismissal."],
["outlier transparency","A report omits two outliers because they weaken the preferred conclusion but gives no reason. What is the main problem?",["Selective reporting reduces transparency and may bias the argument","Outliers must always be included in every calculation","The graph will necessarily be inaccurate","The discussion becomes too long"],0,"Data exclusions need scientific justification and transparent reporting.","Unexplained deletion is a red flag."],
["source credibility","A climate infographic cites a reputable scientific agency but misquotes its data. Which matters most?",["The actual accuracy of how the evidence is represented, not merely the prestige of the source","The source name alone guarantees correctness","The infographic remains valid because the agency is reputable","Only the colour scheme needs changing"],0,"Credible sourcing does not excuse incorrect transcription or interpretation.","Good source + bad use = bad communication."],
["multimodal evidence","A climate performance uses real footage, local stories and numerical projections. What makes it scientifically strong?",["The narrative and visuals support, rather than replace, accurately represented evidence","Emotional impact is enough by itself","Statistics can be simplified until they support the message","Footage proves future projections"],0,"Multimodal communication can engage audiences while still requiring evidence integrity.","Engagement and evidence should work together."],
["comic accuracy","A Big Bang comic shows galaxies exploding outward from a central point in pre-existing space. Why is this risky?",["The visual may create a misleading model of cosmic expansion even if it is easy to understand","Comics cannot explain astronomy","Simple visuals are always inaccurate","The problem is only that there are too many galaxies"],0,"Simplified visuals should avoid introducing misconceptions about the science.","Simplify without changing the model."],
["analogy evaluation","A science communicator uses a balloon analogy for cosmic expansion. What should accompany it?",["A note about what the analogy captures and where it breaks down","A claim that the universe literally behaves exactly like a balloon","No explanation because analogies are self-evident","Removal of all scientific terminology"],0,"Explicit limits prevent audiences from overextending a useful analogy.","State analogy limits."],
["campaign comparison","A speed-limit campaign reports 27% fewer crashes after a change to 40 km/h zones. What additional information most strengthens the argument?",["Comparable before-and-after periods, exposure/traffic context and possible confounding changes","A larger slogan","More photographs of damaged cars","A celebrity quote"],0,"Context helps readers judge whether the observed difference plausibly relates to the policy rather than other changes.","Evidence needs comparison context."],
["testimonials","A campaign uses only testimonials from crash survivors. What is the main limitation?",["Testimonials are compelling but are weak evidence for estimating the overall effect of speed limits","Testimonials are unethical by definition","Personal stories can never be used in communication","Testimonials provide better causal evidence than population data"],0,"Anecdotes can engage audiences but cannot replace systematic evidence for population-level claims.","Stories support; data establish patterns."],
["QR transparency","An infographic links by QR code to raw data and methods. What does this primarily improve?",["Transparency and traceability","Statistical significance","The underlying sample size","The accuracy of every measurement"],0,"Providing source access lets readers inspect methods and evidence beyond the summary.","Traceability, not automatic correctness."],
["visual encoding","An infographic uses different-sized icons to represent quantities, but icon area is not proportional to the values. What is the risk?",["Readers may misjudge relative magnitudes because the visual encoding is inconsistent with the data","The data become categorical","The text becomes too technical","The icons automatically improve accessibility"],0,"Visual elements representing quantity should encode magnitude honestly.","Visual size should match numerical meaning."],
["content selection","A report includes an impressive graph that is unrelated to the research question. What is the best editorial decision?",["Remove it unless it directly supports a necessary point in the argument","Keep it because all data increase credibility","Move it to Results even if irrelevant","Use it as the conclusion"],0,"Scientific texts should select evidence for relevance, not decorative impact.","Relevance beats volume."],
["final communication","Which final product best demonstrates AC9S10I08?",["A text whose content, language, evidence, visuals and digital features are deliberately selected for a defined purpose and audience without sacrificing scientific accuracy","The longest possible report","A highly technical text for every audience","A visually attractive product with minimal evidence"],0,"Effective scientific communication is purposeful, audience-aware and evidence-faithful.","Purpose + audience + evidence + accuracy."]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s10i08-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I08",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));