"use strict";
const q=(id,question,answers,correct,explanation,hint)=>({id,type:"single",question,answers,correct,explanation,hint});
window.quizQuestions=[
q("ac9s7h03-t01","A regional council considers building a desalination plant. Trial data show reliable water production, high electricity demand and measurable brine impacts near the outlet. Which conclusion is strongest?",["The plant can improve water security, but approval should depend on managing energy use, marine impacts and cost","The plant should be approved because it produces water","The plant should be rejected because every technology has impacts","Only construction cost matters"],0,"A strong evaluation weighs intended benefit against multiple evidence-based trade-offs.","Use more than one lens."),
q("ac9s7h03-t02","A cultivated-meat factory uses renewable electricity but is currently expensive to operate. Which comparison is most relevant?",["Potential environmental benefit versus economic affordability and scale","Animal taxonomy versus astronomy","Only taste versus colour","Geology versus genetics"],0,"The response may reduce some environmental pressures while still facing economic barriers.","Identify the competing lenses."),
q("ac9s7h03-t03","A proposed pest-control organism greatly reduces an invasive species but also reduces a native insect population. What is the strongest next step?",["Measure the non-target effect further and compare whether safeguards or alternative controls can reduce harm","Release more immediately because target control worked","Ignore the native insect because it was not the target","Stop all pest management permanently"],0,"Scientific evaluation includes unintended effects and possible redesign.","Effectiveness is not the only criterion."),
q("ac9s7h03-t04","A pharmaceutical product is developed using publicly documented First Nations medicinal knowledge, but no community was consulted. Which issue remains even if the medicine works?",["Consent, attribution and fair benefit-sharing may still be unresolved","Scientific efficacy makes all knowledge governance irrelevant","Public documentation automatically removes cultural ownership","Only product colour matters"],0,"Scientific effectiveness does not erase ethical responsibilities around knowledge use.","Separate efficacy from rights."),
q("ac9s7h03-t05","A renewable-energy project would cut emissions by 40% but disturb habitat used by a threatened species. Which recommendation is best?",["Redesign siting using ecological surveys and proceed only if habitat risk can be reduced to an acceptable level","Approve immediately because emissions fall","Reject all renewable projects","Ignore the species because climate benefits are larger"],0,"A strong judgement seeks to retain benefits while reducing identified harms.","A conditional recommendation can be strongest."),
q("ac9s7h03-t06","Two communities receive the same flood-risk evidence. One prefers a costly levee; the other prefers relocation. Why can both decisions be reasonable?",["They may weigh cost, place attachment, risk tolerance and long-term consequences differently","Scientific evidence must be different even if the data are identical","Only one community can understand science","Evidence has no role in decisions"],0,"Shared evidence can support different choices when values and trade-offs differ.","Facts do not automatically set priorities."),
q("ac9s7h03-t07","A council compares two water strategies: Option A is cheaper but vulnerable to drought; Option B costs more but provides reliable supply with higher energy use. Which additional evidence is most useful?",["Long-term reliability, emissions, ecosystem impacts, household affordability and maintenance cost","The colour of each facility","The number of letters in each option name","Only the initial construction date"],0,"Good evaluation uses evidence across relevant environmental, social and economic criteria.","Think whole-of-life consequences."),
q("ac9s7h03-t08","A proposal claims, 'This technology is scientifically proven, so using it is ethically correct.' What is wrong with the claim?",["Evidence about effectiveness does not by itself determine fairness, rights or acceptable harm","Scientific testing is irrelevant to ethics","Anything effective is unethical","Ethics only concerns cost"],0,"Scientific and ethical questions overlap but are not identical.","Does it work versus should it be used?"),
q("ac9s7h03-t09","An aviation company tests a wing that cuts fuel burn by 7% but increases noise near airports by 3 dB. Which statement is most balanced?",["The design has an environmental/economic benefit and a possible social cost that should be evaluated together","The fuel saving proves the design should be adopted everywhere","Noise data are irrelevant because aviation is technical","Any increase in noise makes the design scientifically invalid"],0,"Trade-offs across lenses should be compared rather than reduced to one metric.","Name both benefit and cost."),
q("ac9s7h03-t10","A government bans a toxic industrial chemical after strong evidence of long-term health effects but substitutes a more expensive alternative. Which lenses are clearly involved?",["Ethical/health protection and economic cost","Only astronomy","Only taxonomy","Only geology"],0,"Protecting people from harm and paying more for alternatives involve different considerations.","Look for harm and cost."),
q("ac9s7h03-t11","A new recycling process recovers 95% of a valuable metal but produces hazardous sludge. What would make the evaluation incomplete?",["Reporting only the recovery rate and ignoring waste treatment, cost and worker/community risk","Including the recovery rate","Comparing treatment options","Measuring sludge toxicity"],0,"A high technical success rate does not capture all consequences.","Check unintended outputs."),
q("ac9s7h03-t12","A cross-cultural fire-management program lowers average fuel load and increases some native plant recruitment after three years. What is the strongest conclusion?",["The measured outcomes support the program in that context, but longer-term monitoring and cultural governance still matter","The program is proven best for all Australian landscapes","Scientific monitoring is no longer needed","The results remove the need for local consent elsewhere"],0,"Evidence can support a response locally without justifying universal transfer or ignoring governance.","Avoid overgeneralising beyond the study."),
q("ac9s7h03-t13","A report says a project creates 500 jobs. Which additional question best tests whether the economic case is complete?",["What are the long-term operating, clean-up and opportunity costs, and who receives the benefits?","What colour are the uniforms?","Which species has the longest name?","What phase is the Moon?"],0,"Job creation is only one part of an economic evaluation.","Look for hidden or delayed costs and distribution."),
q("ac9s7h03-t14","Why can uncertainty justify staged implementation rather than immediate full rollout?",["A smaller trial can gather evidence about real-world effects while limiting potential harm","Uncertainty means evidence should be ignored","Staging guarantees success","Full rollout always costs less"],0,"Staged implementation is a risk-management response to incomplete evidence.","Use uncertainty to guide safeguards."),
q("ac9s7h03-t15","Which statement best evaluates a science-informed response to a contemporary issue?",["A good decision connects evidence about likely outcomes with ethical, environmental, social and economic trade-offs","The scientifically newest option is always best","The cheapest option is always best","The option with the most public support is always scientifically correct"],0,"The code requires evidence plus multiple consequence lenses.","Do not collapse evaluation into one criterion."),
q("ac9s7h03-t16","A student must recommend one of two coastal-protection methods. What is the strongest final paragraph?",["State the preferred option, cite evidence, identify key trade-offs and specify any conditions or monitoring needed","Choose an option without evidence","List both options but avoid a judgement","Pick the option used by the largest city"],0,"A defensible conclusion is evidence-based, balanced and explicit about criteria and safeguards.","Recommendation + evidence + trade-offs + conditions.")
];
