"use strict";
window.skillrPracticeQuestions = [
  ["You cannot find your hat at school. What could you ask your teacher?",["Where is my hat?","My hat is blue.","I like hats."],0,"A — This is a relevant question that asks for the information you need."],
  ["You want to know your friend's name. What could you ask?",["My name is Sam.","What is your name?","I have a friend."],1,"B — This question asks your friend for their name."],
  ["You do not know where to put your schoolbag. What could you ask?",["Where should I put my bag?","This is my bag.","I like my bag."],0,"A — This is a useful question for the school situation."],
  ["You want to know what game your friend is playing. What could you say?",["That game is red.","What game are you playing?","I have a game."],1,"B — This asks your friend for the information you want."],
  ["Your teacher gives you a new activity. You do not know what to do. What could you ask?",["What do I do first?","I have a pencil.","This is easy."],0,"A — This question helps you find out what to do."],
  ["You want to know when lunch starts. What could you ask?",["Where is my lunchbox?","When is lunchtime?","I have an apple."],1,"B — This question asks about the time of lunch."],
  ["Your friend has a new book. You want to know what it is about. What could you ask?",["What is your book about?","Give me the book.","My book is bigger."],0,"A — This is a friendly, relevant question about the book."],
  ["You do not know where the bathroom is at a shop. What is a good question?",["I have to go.","Excuse me, where is the bathroom?","Bathroom!"],1,"B — This is a clear and polite question to an unfamiliar adult."],
  ["Your teacher is holding a picture you cannot see clearly. What could you ask?",["Can you show me the picture, please?","That is a picture.","Pictures are fun."],0,"A — This is a polite request that suits talking to a teacher."],
  ["You want to know why your friend is laughing. What could you ask?",["Stop laughing.","Why are you laughing?","I can laugh too."],1,"B — This is a relevant question to your friend."],
  ["You need a pencil from your teacher. What is the best thing to say?",["Pencil!","Give me one.","Can I please have a pencil?"],2,"C — This is a clear, polite request to a teacher."],
  ["Your friend has the glue. You need it next. What could you say?",["Can I use the glue when you're finished?","That's mine now.","Give it!"],0,"A — This friendly request suits talking to a classmate."],
  ["You need help tying your shoelace. What could you say to Dad?",["My shoes are blue.","Dad, can you help me tie my shoelace?","Shoes!"],1,"B — This clearly asks a parent for help."],
  ["You would like to join your friend's game. What could you say?",["Go away.","I'm playing now.","Can I play too?"],2,"C — This is a friendly request between friends."],
  ["You want some water at home. What could you say?",["Mum, can I have some water, please?","Water now!","I see water."],0,"A — This is a clear and polite request to a family member."],
  ["Your teacher is talking to another child. You need help. What should you do?",["Shout, ‘HELP ME!’","Wait, then ask, ‘Can you help me, please?’","Grab the teacher."],1,"B — Waiting and asking politely suits the school situation."],
  ["You want your brother to pass you a crayon. What could you say?",["Can you pass me the crayon, please?","That's a crayon.","I don't like crayons."],0,"A — This is a clear request to a sibling."],
  ["You are at a shop and would like an apple. What could you say?",["Apple!","Give me that!","Can I please have an apple?"],2,"C — This polite request suits talking to a shopkeeper."],
  ["You cannot open your lunchbox. What could you say to your teacher?",["Can you please help me open this?","Lunchboxes are hard.","Open!"],0,"A — This clearly and politely asks the teacher for help."],
  ["Your friend has put a bag where you need to sit. What could you say?",["MOVE!","Could you please move your bag a little?","You're sitting there."],1,"B — This is a friendly request that explains what you need."],
  ["Which sentence tells what you think?",["Where is the book?","I think this book is funny.","Can I have the book?"],1,"B — ‘I think’ tells your opinion."],
  ["Your teacher asks which picture you like best. What could you say?",["I like the beach picture best.","Where is the picture?","Give me the picture."],0,"A — This expresses your opinion about the pictures."],
  ["Your dad asks what you thought of a story. What could you say?",["Where is the story?","I thought the story was exciting.","Read it!"],1,"B — This tells your opinion about the story."],
  ["Which sentence is an opinion?",["I think red is the best colour.","What colour is it?","Please give me the red pencil."],0,"A — This tells what someone thinks about a colour."],
  ["Your friend asks, ‘Do you like my drawing?’ What could you say?",["I like the big rainbow.","Give me the drawing.","Where is your pencil?"],0,"A — This gives a relevant opinion about the drawing."],
  ["The teacher asks which playground activity you enjoy. What could you say?",["Where is the playground?","I like the swings best.","Can I have a pencil?"],1,"B — This answers the teacher by giving your opinion."],
  ["Which child is giving an opinion?",["Ben: ‘Can I have some milk?’","Ava: ‘Where is my cup?’","Leo: ‘I think strawberries taste great.’"],2,"C — Leo is telling what he thinks about strawberries."],
  ["Your parent asks which shirt you prefer. What could you say?",["I like the green one better.","Where are my shoes?","Give me a shirt."],0,"A — This clearly expresses your preference."],
  ["You need help from your teacher. Which is the better choice?",["Hey! Do this!","Excuse me, can you help me, please?","You!"],1,"B — This respectful request suits the teacher–student relationship."],
  ["You are buying a muffin from a shopkeeper. What could you say?",["Give me that one!","Can I please have that muffin?","Muffin!"],1,"B — This polite request suits a customer speaking to a shopkeeper."],
  ["You want your friend to come and play. What could you say?",["Would you like to play with me?","You must play.","Go away."],0,"A — This is a friendly invitation between friends."],
  ["Your teacher asks you to put away the blocks. What is a suitable response?",["No! You do it!","Okay, I'll put them away.","Blocks!"],1,"B — This response suits a student speaking to a teacher."],
  ["A shopkeeper says, ‘Hello. How can I help you?’ What could you say?",["I would like some bananas, please.","Bananas! Now!","Go away."],0,"A — This is clear and polite language for a customer."],
  ["Your friend accidentally takes your pencil. What could you say?",["You're bad!","I think that's my pencil. Can I have it back, please?","Give it NOW!"],1,"B — This calmly explains the problem and makes a friendly request."],
  ["Your teacher asks, ‘Which story would you like to hear?’ What could you say?",["I would like the dinosaur story, please.","Story!","You choose because I said so."],0,"A — This gives a clear choice in a way that suits talking to a teacher."],
  ["Max says to his teacher, ‘Give me the scissors!’ Which is a better way to ask?",["Scissors!","Can I please have the scissors?","I want them now!"],1,"B — This changes the command into a polite school request."],
  ["Ella wants to play with Mia. Ella says, ‘Move! I'm playing!’ What could she say instead?",["Can I play with you?","Move faster!","That's my game now."],0,"A — This is a friendly way to ask to join a game."],
  ["Noah cannot find his classroom. He sees a teacher. What should he say?",["ROOM!","You! Come here!","Excuse me, can you help me find my classroom?"],2,"C — This is a clear and respectful request to a teacher."],
  ["Zara wants her sister's blue crayon. Which is the best choice?",["Give it!","Can I use the blue crayon when you're finished?","That's mine."],1,"B — This request suits talking to a sibling and taking turns."],
  ["You want a shopkeeper to help you find the milk. Which is the best choice?",["Where's milk?","You need to find milk.","Excuse me, can you please show me where the milk is?"],2,"C — This polite question suits talking to a shopkeeper." ]
].map((q,i)=>({id:`ac9efla01-p${String(i+1).padStart(2,"0")}`,curriculumCode:"AC9EFLA01",bank:"practice",sourceType:"Multiple choice",question:q[0],explanation:q[3],printable:true,type:"single",answers:q[1],correct:q[2]}));
window.quizQuestions = window.skillrPracticeQuestions;
