"use strict";
const Q=[
["display purpose","The same numerical dataset could be shown as a dot plot or histogram. When is the dot plot usually more informative?",["When the dataset is small enough that individual values and clusters should remain visible","Whenever the data are continuous, regardless of sample size","When exact category percentages are the only goal","When the values occur over several years"],0,"Dot plots retain individual observations, while histograms group values into intervals and are often more useful for larger datasets.","Choose based on what detail must remain visible."],
["histogram bins","The same continuous dataset looks unimodal with 10-unit bins but irregular with 2-unit bins. What does this show?",["Histogram appearance can depend on bin width, so the chosen grouping should be justified","One of the datasets must be wrong","Narrower bins are always more accurate","Histograms cannot show distribution shape"],0,"Bin choices can reveal or obscure features, especially with limited data; interpretation should consider the grouping.","The display construction can affect apparent shape."],
["centre display","A teacher wants students to see both individual values and how one outlier affects the distribution of 18 scores. Which is a strong choice?",["Dot plot, accompanied by appropriate centre/spread summaries","Pie chart","Stacked area chart","Map"],0,"A dot plot preserves all 18 observations, including the outlier, and numerical summaries support interpretation.","Small numerical sample + individual values."],
["ordinal display","A survey has responses Strongly disagree through Strongly agree. Why is an ordered bar chart preferable to alphabetically ordering the labels?",["It preserves the meaningful ordinal progression of the response scale","Alphabetical labels change the frequencies","Bar charts require numerical x-values","Ordinal data must be converted to means"],0,"The category order carries information and should be retained in the visualisation.","Order is part of ordinal data."],
["time vs distribution","A researcher has hourly speeds for one month. Which pair of displays answers two different useful questions?",["A line graph for when speeds changed and a histogram for the overall speed distribution","Two pie charts","A stem-and-leaf and a map with no time information","A bar chart with hours in random order and a pictograph"],0,"Time-series and distribution displays reveal complementary features of the same measurements.","One display need not answer every question."],
["icon area","An infographic represents 100 people with a square of side 2 cm and 200 people with a square of side 4 cm. Why is this misleading if viewers perceive area?",["The second square has four times the area even though the value is only twice as large","The second square has only twice the area","Squares cannot encode quantities","The first square should have side 1 cm"],0,"Doubling side length quadruples area, exaggerating a twofold quantity difference.","Linear scaling of 2 produces area scaling of 4."],
["pictograph partials","One icon represents 20 students. A category contains 50 students. Which representation is accurate?",["2.5 equally sized icons, with the half-icon convention made clear","3 full icons because pictographs cannot use fractions","2 full icons because only complete groups count","One icon enlarged 2.5 times in both height and width"],0,"A clearly defined half icon can represent 10 students; enlarging area would distort the scale.","Keep unit icons proportional."],
["stacked comparison","Two schools use 100% stacked bars to compare subject choices. What information is easiest to compare?",["The proportion in each subject within each school","The total number of students in each school","Exact individual student responses","The distribution of student ages"],0,"100% stacked bars normalise totals and emphasise composition, but hide absolute group sizes unless supplied separately.","100% bars show composition, not totals."],
["stacked limitation","School A has 200 students and School B has 800. Both 100% stacked bars show 25% choosing art. What cannot be read from the bars alone?",["That 50 students in A and 200 in B chose art","That the art proportion is 25% in each school","That the compositions can be compared","That art is one quarter of each school"],0,"Normalised bars omit absolute totals unless sample sizes are also provided.","Equal percentages can represent different counts."],
["area chart","When is a stacked area chart especially useful?",["Showing how a total and its components change continuously through time","Comparing exact values of many unrelated categories at one instant","Displaying individual observations in a small sample","Showing the association between two quantitative variables"],0,"Stacked area charts emphasise changing totals and composition over time.","Think composition + time."],
["area limitation","Why can middle bands in a stacked area chart be hard to compare precisely?",["They do not share a common zero baseline, so their thickness must be judged between two moving boundaries","Area charts contain no numerical information","Time cannot appear on an area chart","Only the bottom category can change"],0,"Only the bottom series shares a fixed baseline; middle components are harder to compare accurately.","Common baselines improve comparison."],
["AI visualisation","An AI tool chooses a pie chart for 25 temperature readings over time. What is the best critique?",["A time-series line graph would preserve temporal order and change more clearly","Pie charts are never valid displays","Temperature cannot be graphed","The AI should calculate a median instead"],0,"The key structure is change through time, which a pie chart does not represent naturally.","Match display to the question and variable structure."],
["AI distortion","An AI-generated bar chart automatically starts at 98 to compare values 99 and 100. What should a student do?",["Recognise that the truncated baseline can exaggerate the bar-length difference and choose a more honest scale","Accept it because automated charts are objective","Delete the smaller value","Convert the data to a pie chart"],0,"Automated visualisation choices still require statistical judgement; a truncated bar baseline can strongly distort magnitude.","AI output still needs critique."],
["visual accessibility","A graph distinguishes four groups only by red, green, blue and orange colours. Which refinement improves accessibility without changing data?",["Add labels, symbols or patterns so groups are not distinguished by colour alone","Add more colours","Remove the legend","Use 3D effects"],0,"Redundant visual cues make a display usable for more viewers and improve interpretation in grayscale or with colour-vision differences.","Do not rely on colour alone."],
["context choice","A council wants the public to compare exact annual water-use values for three sectors and also see the trend over 10 years. Which presentation is strongest?",["A clearly labelled line graph plus an accessible table of exact values","A single decorative pictograph","A pie chart for all 30 observations","A histogram with years mixed together"],0,"The graph reveals temporal patterns while the table supplies exact values; together they match both purposes.","Choose displays for the audience's tasks."],
["final judgement","Which principle best captures AC9M9ST04 display choice?",["Choose and justify a display based on data type, context, audience and the comparison or pattern that needs to remain visible","Always use the graph with the most visual effects","Use histograms for every numerical dataset","A display is appropriate whenever software can generate it"],0,"No single display is universally best; appropriateness depends on the statistical purpose and context.","Purpose drives representation." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9m9st04-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9M9ST04",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));