"use strict";
const AC9S7I01_EXPLAIN={"reasoned predictions":"A reasoned prediction is made before testing and uses relevant scientific knowledge or a model to justify the expected outcome.","hypotheses":"A hypothesis proposes a testable relationship or explanation that evidence can support or challenge.","variables and fair testing":"The independent variable is changed, the dependent variable is measured, and relevant controlled variables are kept consistent for a fair comparison.","scientific models":"Scientific models are simplified representations that help explain, predict and develop testable questions about systems.","investigable questions":"Investigable questions are answerable through systematic observations, measurements, experiments or appropriate evidence, and must be clear and feasible.","testing relationships":"A strong relationship question identifies measurable variables so evidence can reveal a pattern or effect."};
const AC9S7I01_HINT={"reasoned predictions":"Look for an expected result plus a scientific reason.","hypotheses":"Look for a testable relationship and scientific reasoning.","variables and fair testing":"Separate what changes, what is measured and what stays the same.","scientific models":"Ask what relationship or mechanism the model helps represent.","investigable questions":"Ask whether systematic evidence can answer the question.","testing relationships":"Look for two measurable variables."};
const q=(n,skill,question,answers,correct)=>({id:`ac9s7i01-t-${String(n).padStart(3,"0")}`,curriculumCode:"AC9S7I01",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers,correct,explanation:`${answers[correct]} ${AC9S7I01_EXPLAIN[skill]}\nHint: ${AC9S7I01_HINT[skill]}`,structuredExplanation:{summary:`${answers[correct]} ${AC9S7I01_EXPLAIN[skill]}`,hint:AC9S7I01_HINT[skill]},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
q(25,"reasoned predictions","Why do reasoned predictions help scientists plan investigations?",["They avoid experiments","They encourage random guessing","They identify an expected pattern that can be compared with evidence","They replace hypotheses"],2),
q(26,"hypotheses","A hypothesis must include:",["A joke","A testable statement with reasoning","A random guess","A personal opinion"],1),
q(27,"hypotheses","Which is the strongest hypothesis?",["If I heat water, it will boil because boiling is fun.","If water temperature increases, sugar dissolving rate will increase within the tested range because particles move faster.","If sugar dissolves, it tastes sweet because sugar is tasty.","If water is cold, it is cold because cold is cold."],1),
q(28,"hypotheses","The independent variable is:",["What you measure","What you deliberately change","What you keep the same","What you ignore"],1),
q(29,"hypotheses","The dependent variable is:",["What you deliberately change","What you measure as the response","What you ignore","What you keep the same"],1),
q(30,"hypotheses","Which hypothesis best tests the effect of parachute surface area on air resistance?",["If parachute area decreases, descent time will decrease because there is less air resistance.","If parachute area decreases, it looks smaller because it is smaller.","If parachute area decreases, it becomes colourful.","If parachute area decreases, it always becomes lighter."],0),
q(31,"variables and fair testing","Controlled variables are:",["What you change","What you measure","Factors you keep the same","Factors you ignore"],2),
q(32,"variables and fair testing","A scientific hypothesis must be:",["Testable","Impossible","Opinion-based","Unmeasurable"],0),
q(33,"variables and fair testing","Which variable changes in ‘How does water temperature affect dissolving rate?’",["Amount of sugar","Water temperature","Type of beaker","Colour of water"],1),
q(34,"variables and fair testing","Which variable is measured in ‘How does water temperature affect dissolving rate?’",["Water temperature","Dissolving rate","Beaker size","Water colour"],1),
q(35,"variables and fair testing","Why should a hypothesis include scientific reasoning?",["To make it longer","To explain why the predicted relationship is expected","To confuse readers","To make it funny"],1),
q(36,"scientific models","Why do scientists use models?",["To simplify selected features of complex systems so they can explain and predict patterns","To make ideas confusing","To avoid collecting evidence","To replace observations"],0),
q(37,"investigable questions","Which is the best question for a classroom investigation?",["How does water temperature affect the time taken for a fixed mass of sugar to dissolve?","Why do stars shine?","How old is the universe?","Why do planets orbit?"],0),
q(38,"reasoned predictions","What distinguishes a reasoned prediction from a guess?",["It is based on feelings","It uses relevant scientific knowledge to justify the expected outcome","It is always correct","It is written after the results"],1),
q(39,"hypotheses","Which statement is NOT a hypothesis?",["If salt concentration increases, ice may melt faster because dissolved salt lowers the freezing point.","If temperature increases, balloon volume will increase because gas particles move faster.","Balloons are fun to play with.","If light intensity increases within a suitable range, plant growth may increase because photosynthesis requires light."],2),
q(40,"testing relationships","Which question most clearly tests a relationship between two variables?",["How does heating affect balloon volume?","Why do balloons exist?","Are balloons colourful?","Which balloon is nicest?"],0)
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
