"use strict";
const q=[
["ac9s8u02-t-001","plant-diagram","A stem cross-section shows xylem toward the inside and phloem toward the outside. Which interpretation best links structure and function?",["Xylem transports water and also contributes to support because its walls are strengthened","Phloem must be outside because it absorbs light","Xylem is inside so it can produce sugars","Phloem forms the waterproof surface of the stem"],0,"Xylem transports water and mineral ions, and lignified walls also strengthen the stem."],
["ac9s8u02-t-002","leaf-diagram","A leaf cross-section shows a dense palisade layer below the upper epidermis and a spongy layer with air spaces below it. Why is this arrangement useful?",["Palisade cells capture light efficiently while spongy air spaces support gas diffusion","The palisade layer prevents all water movement","Spongy mesophyll transports blood","The epidermis performs most photosynthesis"],0,"The arrangement links light capture near the surface with internal gas movement through air spaces."],
["ac9s8u02-t-003","transpiration-reasoning","A plant's transpiration rate is 4 mL/h in still humid air and 14 mL/h in moving dry air. Which explanation best fits the data?",["Moving dry air maintains a steeper water-vapour gradient from leaf to air","Wind closes every stoma permanently","Dry air stops xylem flow","Humidity increases evaporation from leaf surfaces"],0,"Dry moving air removes water vapour near the leaf, maintaining a strong gradient for diffusion."],
["ac9s8u02-t-004","xylem-disruption","A plant has moist soil but begins to wilt after air bubbles block many xylem vessels. What does this show?",["Water availability alone is not enough; water must also be transported to leaves","Phloem normally carries all water upward","Leaves wilt only when roots are dry","Xylem is needed mainly for sugar storage"],0,"The plant may have water available in soil, but blocked xylem prevents effective delivery to leaves."],
["ac9s8u02-t-005","phloem-disruption","A ring of bark containing phloem is removed from a tree trunk while xylem remains intact. Which change is most likely above the ring?",["Sugars accumulate because downward phloem transport is interrupted","Water instantly stops reaching leaves","Gas exchange in stomata stops immediately","Mineral ions accumulate because phloem carries them upward"],0,"Removing phloem interrupts transport of sugars from leaves to sinks below the damaged region."],
["ac9s8u02-t-006","exercise-systems","During exercise, breathing rate and heart rate both increase. Why is this coordinated response useful?",["It increases oxygen uptake and delivery to respiring muscles while increasing carbon dioxide removal","It allows the lungs to pump blood","It allows muscles to stop using glucose","It decreases blood flow to active tissues"],0,"Respiratory and circulatory systems work together to meet increased demands of cellular respiration."],
["ac9s8u02-t-007","alveoli-structure","Two lung models have the same total volume. Model A has one large air chamber; Model B has many tiny air sacs with thin walls. Which model better represents efficient gas exchange and why?",["Model B, because many small sacs create greater surface area and short diffusion distances","Model A, because one chamber has less surface area","Model A, because thicker walls increase diffusion","Both are equally effective regardless of surface area"],0,"Many small thin-walled sacs provide a large exchange area and short diffusion path."],
["ac9s8u02-t-008","circulation-data","A student's heart rate rises from 72 to 144 beats/min during intense exercise. If stroke volume also rises, what is the most likely effect?",["More blood can be delivered to working tissues each minute","Less oxygen reaches muscles","Capillaries become thicker","Blood stops returning through veins"],0,"Higher heart rate together with greater stroke volume increases cardiac output and tissue blood supply."],
["ac9s8u02-t-009","artery-disorder","An artery becomes narrower and less elastic. Which chain of effects is most scientifically reasonable?",["Higher resistance to flow → reduced tissue supply and greater workload on the heart","Lower resistance → less pressure needed from the heart","More alveolar surface area → faster gas exchange","More phloem transport → faster circulation"],0,"Narrowing increases resistance and can reduce flow while requiring the heart to work harder."],
["ac9s8u02-t-010","villi-disruption","A disease damages most villi in the small intestine but leaves digestive enzymes working normally. Which outcome is most likely?",["Nutrient absorption falls because the exchange surface area is reduced","Protein digestion stops completely","Gas exchange in the lungs falls directly","The heart can no longer contract"],0,"Even if digestion occurs, damaged villi reduce the surface area available for nutrient absorption."],
["ac9s8u02-t-011","artificial-organ","A dialysis machine removes urea and excess water from blood. Which statement best evaluates it as an artificial organ system support?",["It replaces selected kidney functions but does not reproduce every role of living kidneys","It permanently repairs all kidney tissue","It performs gas exchange like alveoli","It controls movement by replacing nerves"],0,"Dialysis augments or replaces some filtration and fluid-balance functions, not all kidney functions."],
["ac9s8u02-t-012","model-limit","A 2D diagram shows the digestive organs clearly but makes them appear to lie in one flat plane. What is the most important limitation?",["It may misrepresent the three-dimensional positions and spatial relationships of organs","It cannot show labels","It proves organs do not overlap","It makes every organ the wrong colour only"],0,"A 2D representation can clarify connections but cannot fully show depth and spatial arrangement."],
["ac9s8u02-t-013","plant-animal-analogy","Which comparison best identifies a functional similarity between plant vascular tissue and the human circulatory system?",["Both transport materials between different parts of the organism","Both use a heart to generate pressure","Both carry blood through arteries","Both use stomata for exchange"],0,"Although structures differ, both systems distribute essential materials around a multicellular organism."],
["ac9s8u02-t-014","guard-cells","On a hot dry afternoon, many stomata close. Which trade-off best explains this response?",["Water loss decreases, but carbon dioxide entry and photosynthesis may also decrease","Water loss increases and photosynthesis always increases","Xylem stops functioning permanently","Phloem begins carrying oxygen instead of sugars"],0,"Closing stomata conserves water but also limits carbon dioxide diffusion into the leaf."],
["ac9s8u02-t-015","structure-function-chain","A tendon connecting a muscle to a bone is badly torn. The muscle cells still contract normally. Why is movement weakened?",["Force produced by the muscle is not transferred effectively to the bone","The bone can no longer carry oxygen","The muscle loses all mitochondria immediately","The joint stops producing blood cells"],0,"Tendons transmit force from contracting muscles to bones, producing movement at joints."],
["ac9s8u02-t-016","system-survival","A blockage reduces blood flow to part of the brain. Why can damage occur quickly even though the blockage is local?",["Brain cells depend on continuous delivery of oxygen and glucose through the circulatory system","Brain cells make their own blood when supply falls","Only the blocked vessel is affected because organs work independently","The digestive system immediately replaces the missing blood"],0,"A local circulatory failure can rapidly affect organ function because cells depend on transported resources for survival."]
];
window.skillrTestQuestions=q.map(([id,skill,question,answers,correct,summary])=>({id,curriculumCode:"AC9S8U02",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation:summary+"\nHint: Trace the evidence from structure to function, then to the effect on the organ system or organism.",structuredExplanation:{summary,hint:"Trace the evidence from structure to function, then to the effect on the organ system or organism."},qualitySchema:"production-v2"}));
if(window.quizConfig){window.quizConfig.maxQuestions=8;window.quizConfig.questionCycle=true;}
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;