export const test=[
['After watching a pond for five minutes, which sentence most clearly reports what the group found?',['Four snails were beside the pond.','I think snails will come later.','Snails are my favourite.','Maybe it will rain.'],0,'The sentence reports a direct observation from the pond watch.','Choose what the group actually noticed.','🐌'],
['Which report is most precise?',['We counted 7 ants under the log.','There were loads of ants.','Ants were everywhere maybe.','The log was interesting.'],0,'A specific count communicates the evidence clearly.','Use the number.','🐜'],
['Why show a tally chart while speaking?',['It lets listeners see the evidence being explained.','It makes the result automatically correct.','It replaces observation.','It is only decoration.'],0,'The visual can support the spoken explanation with the recorded data.','Words and visuals can work together.'],
['Which question best asks for evidence?',['How many birds did you count?','Do you like birds?','Which colour is nicest?','Was recess fun?'],0,'The question asks for the recorded observation.','Ask about the investigation.','🐦'],
['Which response shows respectful science discussion?',['Can you show me the count that supports your idea?','Your idea is stupid.','Only I can be right.','Stop talking.'],0,'The first response challenges the idea by asking for evidence, not by attacking the person.','Return to evidence.'],
['A child says, “The plant is happiest in sun.” Which follow-up is strongest?',['What did you observe that makes you think that?','Is happiness green?','Do you like sunny days?','Should we just agree?'],0,'The question asks the child to connect the idea to evidence.','What supports the claim?','🌱'],
['Which poster element is most important for sharing counts?',['a clear chart with labels','decorative stars only','a joke box','a list of names only'],0,'A labelled chart makes the numerical observations understandable.','Show the evidence.'],
['Which sentence clearly marks an idea rather than a direct observation?',['I think the shade may help the soil stay damp.','The soil felt damp.','We counted 4 worms.','The leaf had holes.'],0,'“I think” signals an interpretation or idea.','Direct observations do not need guessing.'],
['A report says “Our prediction matched.” What should come next?',['the result showing how it matched','an unrelated photo','a favourite-colour vote','a different experiment'],0,'The comparison should be supported by the observed result.','Evidence follows the claim.'],
['Which sentence overclaims?',['We saw more bees on yellow flowers today.','Yellow had 5 visits and white had 2.','Bees always choose yellow flowers.','The yellow count was higher.'],2,'Today’s observation cannot prove what all bees always do.','Watch for absolute words.','🐝'],
['Why listen to another group’s observation?',['It may add evidence or a detail you missed.','Other groups cannot observe science.','Listening changes the data.','Only your group matters.'],0,'Other observers may contribute useful information.','Science can be collaborative.'],
['Which phrase best begins a prediction when sharing?',['I think…','I saw…','The result was…','We counted…'],0,'“I think” can introduce an expectation before the result.','Expectation language.'],
['What should you do if a classmate asks what “lots” means in your report?',['Give the actual count if you recorded one.','Say it means whatever you want.','Change the topic.','Tell them not to ask.'],0,'A specific count makes the shared observation clearer.','Replace vague quantity with evidence.'],
['Which statement combines evidence and an idea carefully?',['We counted 6 worms in damp soil and 1 in dry soil, so worms may be easier to find in damp soil here.','Worms always live only in damp soil.','Damp soil creates worms.','The counts do not matter.'],0,'The first statement uses the observation while keeping the interpretation appropriately cautious.','Evidence + “may”.','🪱'],
['Which way best shares change over time?',['dated pictures in order','one random picture','an unrelated story','a blank chart'],0,'Ordered dated records show how the observation changed over time.','Sequence the evidence.','🌱'],
['Which closing is strongest?',['Our result did not support the prediction, and we want to test the idea again with another fair observation.','We were wrong so science failed.','We will hide the result.','Our prediction is still correct because we like it.'],0,'The conclusion reports the evidence honestly and proposes a sensible next step.','Unexpected results can lead to new tests.']
];