export const test=[
['At the beach, two small channels carry water across sand. Which question could a child investigate by watching them?',['Which channel carries water farther before it soaks in?','Why is the ocean beautiful?','Which channel is happiest?','Is sand the best material?'],0,'The first question asks about an observable distance that can be compared.','Choose what can be watched or measured.','🏖️💧'],
['Before placing two leaves in sunny and shady spots, which sentence is a prediction?',['The sunny leaf dried first.','The leaves are green.','I think the sunny leaf will dry faster.','The shade is beside the fence.'],2,'The prediction states what is expected before the result is known.','Look for the future result.','☀️🍃 | 🌳🍃'],
['A child predicts a wet sock will dry faster outside because washing on the line dries quickly at home. Why is this a useful reason?',['It uses a relevant past experience about drying.','It proves the sock must dry first.','It describes the sock colour.','It is only a favourite choice.'],0,'The reason links the prediction to something the child has observed before.','Which reason connects to drying?','🧦☀️'],
['A class asks, “Which paper bridge holds more blocks?” Which evidence answers the question?',['The colour of each paper bridge.','How many blocks each bridge holds before bending.','Which bridge looks nicest.','The names of the children who built them.'],1,'The number of blocks supported directly answers which bridge holds more.','Measure the outcome named in the question.','🌉'],
['Which question is focused enough to investigate with two cups of water?',['What happens to water?','Is water useful?','Which cup of water cools faster: the metal cup or the plastic cup?','Why are cups different?'],2,'The question identifies two conditions and one observable outcome to compare.','What could you measure or notice?','🥤'],
['Before putting two toy boats in water, which prediction matches “Which boat stays afloat longer?”',['The boats are different colours.','I think the foil boat will stay afloat longer than the paper boat.','The bowl is round.','Foil feels smooth.'],1,'The prediction addresses the same outcome: how long each boat stays afloat.','Question and prediction should match.','⛵'],
['A child says, “The bigger ball will bounce higher because bigger things are better.” What should be improved?',['The ball colour.','The reason, because “better” is not relevant evidence about bouncing.','The word “ball”.','Nothing; the reason is scientific.'],1,'A useful reason should connect to bouncing through prior observation or a relevant physical feature.','Does “better” explain bounce height?','🏀'],
['The class wants to know which patch of garden has more worms. Which plan gives useful evidence?',['Count worms in both patches for the same search time.','Look only in the patch expected to have more.','Choose the patch with darker soil without counting.','Ask which patch children prefer.'],0,'Counting in both places under comparable conditions provides evidence for the question.','Both places need the same kind of observation.','🪱'],
['Which sentence is an observation made after a shadow investigation?',['I think the shadow will be longer later.','The shadow measured 42 cm at 3 pm.','The shadow might move.','I predict the afternoon shadow will change.'],1,'The measurement reports what was observed at a specific time.','Which result has already been recorded?','☀️'],
['Question: “Which material absorbs the most water?” Which prediction is too vague to test clearly?',['The sponge will absorb more drops than the foil.','The cotton cloth will soak up the most water.','The paper towel will be the best one.','The plastic sheet will absorb the least.'],2,'“Best” does not identify the observable outcome unless it is defined.','Best at what?','💧'],
['A child asks, “Will the ice melt faster on the bench or in the fridge?” What makes this a science question?',['It asks about an observable result that can be compared.','It contains the word “ice”.','It has more than five words.','It asks for a favourite place.'],0,'Melting can be observed and the two locations can be compared.','Could evidence answer it?','🧊'],
['A prediction says, “More birds will visit the feeder with seed.” What observation would test it?',['Count bird visits to the seed feeder and the comparison feeder.','Count the letters in “bird”.','Record the feeder colours only.','Ask which feeder looks better.'],0,'Visit counts from both feeders directly test the prediction.','Observe the thing predicted.','🐦'],
['A child predicted a paper towel would absorb more because it felt thicker than the other towel. What does “because it felt thicker” provide?',['a relevant experience-based reason','the final observation','a new science question','proof that the prediction is correct'],0,'The thickness observation gives a reason for the expected result, but does not guarantee it.','Reason is not proof.','▤'],
['Which sequence makes sense for a simple investigation?',['Observe result → invent question → change prediction','Ask question → make prediction → collect observations','Choose favourite answer → measure → ask question','Record conclusion → make prediction → start question'],1,'A question guides the investigation, a prediction is made before testing, then observations are collected.','What must happen before seeing the result?'],
['A child asks, “Which ramp makes the car travel farther?” Which prediction answers it exactly?',['The wooden ramp is brown.','I think the steeper ramp will let the car travel farther.','Cars have wheels.','The car may make a sound.'],1,'The prediction states which ramp is expected to produce the greater travel distance.','Match the compared outcome.','🚗'],
['After seeing that a prediction did not match the result, what should the child do?',['Change the recorded result to fit the prediction.','Keep the observation and use it to think about what happened.','Erase the prediction.','Say the test failed because predictions must be correct.'],1,'Evidence is recorded honestly whether or not it supports the prediction.','Unexpected results can still teach us.']
];