"use strict";
// 20260906-y1-original-v1 - generated from the canonical Year 1 bank.
window.skillrPracticeQuestions = [
  {
    "id": "AC9M1N04-P01",
    "questionId": "P01",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "A ten-frame has 8 filled spaces and 2 empty spaces. Fill the empty spaces. How many counters are there now?",
    "explanation": "Eight and two make ten. All 10 spaces are filled.",
    "skill": "Complete a ten-frame",
    "responseType": "mcq",
    "difficulty": 1,
    "cognitiveDemand": "recognise",
    "visualModel": {
      "type": "grid",
      "rows": [
        [
          "●",
          "●",
          "●",
          "●",
          "●"
        ],
        [
          "●",
          "●",
          "●",
          "○",
          "○"
        ]
      ],
      "caption": "● filled; ○ empty."
    },
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "10",
      "8",
      "12"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P02",
    "questionId": "P02",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Work out 13 − 3.",
    "explanation": "Thirteen is 10 and 3. Taking away the 3 leaves 10.",
    "skill": "Subtract the ones",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "9",
      "10",
      "16"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P03",
    "questionId": "P03",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "The whole is 10. One part is 6. What is the other part?",
    "explanation": "Six and four make ten. The missing part is 4.",
    "skill": "Find a missing part",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "16",
      "4",
      "6"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P04",
    "questionId": "P04",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "To work out 9 + 5, first make 10.\n9 + 1 + __ = 14\nWrite the missing number.",
    "explanation": "Split 5 into 1 and 4. Nine and one make ten, then add 4.",
    "skill": "Complete a make-ten strategy",
    "responseType": "short_answer",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "Accept 4 or four.",
    "printable": true,
    "type": "text",
    "correct": "4",
    "acceptedAnswers": [
      "4",
      "four"
    ],
    "answerFormat": "plain"
  },
  {
    "id": "AC9M1N04-P05",
    "questionId": "P05",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "For 3 + 12, start at 12 and count on 3. Which numbers do you say?",
    "explanation": "Make three counting steps after 12: 13, 14, 15. So 3 + 12 = 15.",
    "skill": "Select a count-on sequence",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "13, 14, 15",
      "12, 13, 14",
      "14, 15, 16"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P06",
    "questionId": "P06",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "You know 7 + 5 = 12. What is 12 − 7?",
    "explanation": "The parts of 12 are 7 and 5. Removing the 7 leaves 5.",
    "skill": "Use a related addition fact",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "5",
      "7",
      "19"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P07",
    "questionId": "P07",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "You know 6 + 6 = 12. What is 6 + 7?",
    "explanation": "Seven is one more than six. So 6 + 7 is one more than 12.",
    "skill": "Use a near double",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "12",
      "14",
      "13"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P08",
    "questionId": "P08",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Draw 14 counters. Cross out 6. Write how many are left.",
    "explanation": "Fourteen take away six leaves eight. You can remove 4 to reach 10, then remove 2 more.",
    "skill": "Make a subtraction model",
    "responseType": "short_answer",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "Accept a drawing with 14 counters, 6 crossed out and 8 remaining, and an answer of 8.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "8",
    "modelAnswer": "8"
  },
  {
    "id": "AC9M1N04-P09",
    "questionId": "P09",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "On a number line, start at 8. Jump forward 2, then forward 3. Where do you land?",
    "explanation": "Eight plus two reaches ten. Three more reaches thirteen.",
    "skill": "Read split number-line jumps",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "11",
      "13",
      "10"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P10",
    "questionId": "P10",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Which addition has the same answer as 4 + 9?",
    "explanation": "Swapping the two parts does not change their total. Both additions make 13.",
    "skill": "Recognise turn-around addition",
    "responseType": "mcq",
    "difficulty": 1,
    "cognitiveDemand": "recognise",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "9 + 5",
      "9 + 4",
      "9 − 4"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P11",
    "questionId": "P11",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "There are 15 counters. Cover 5 of them. How many can you still see?",
    "explanation": "Fifteen minus five equals ten. The other ten counters stay uncovered.",
    "skill": "Find an uncovered part",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "5",
      "20",
      "10"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P12",
    "questionId": "P12",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Use 8 + 2 = 10 to work out 8 + 3. Write the answer and tell how the known fact helps.",
    "explanation": "Three is one more than two. So 8 + 3 is one more than 8 + 2.",
    "skill": "Explain a one-more strategy",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "Accept 11 with words or a model showing that 3 is one more than 2, or that one more is added to 10.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "11; add one more to 10.",
    "modelAnswer": "11; add one more to 10."
  },
  {
    "id": "AC9M1N04-P13",
    "questionId": "P13",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "17 − __ = 10\nWhich number is missing?",
    "explanation": "Seventeen has 10 and 7. Take away the 7 to leave 10.",
    "skill": "Find a missing amount removed",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "7",
      "10",
      "3"
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P14",
    "questionId": "P14",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "For 8 + 5, which way of splitting 5 helps you make 10 first?",
    "explanation": "Eight needs two to make ten. The other three brings the total to thirteen.",
    "skill": "Choose a helpful partition",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "4 and 1",
      "5 and 0",
      "2 and 3"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P15",
    "questionId": "P15",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Which number-line move shows 16 − 4?",
    "explanation": "Subtraction takes away from the starting number. Four steps back from 16 reaches 12.",
    "skill": "Choose a subtraction number-line model",
    "responseType": "mcq",
    "difficulty": 1,
    "cognitiveDemand": "recognise",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "Start at 16 and move forward 4.",
      "Start at 4 and move back 16.",
      "Start at 16 and move back 4."
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P16",
    "questionId": "P16",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Use 11, 3 and 14 to write an addition equation.",
    "explanation": "The two parts, 11 and 3, join to make the whole, 14.",
    "skill": "Create an addition equation",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "create",
    "visualModel": null,
    "acceptanceNote": "Accept 11 + 3 = 14 or 3 + 11 = 14; reversed equality forms are also valid.",
    "printable": true,
    "type": "text",
    "correct": "11 + 3 = 14",
    "acceptedAnswers": [
      "11+3=14",
      "3+11=14",
      "14=11+3",
      "14=3+11"
    ],
    "answerFormat": "equation"
  },
  {
    "id": "AC9M1N04-P17",
    "questionId": "P17",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "To work out 14 − 5, first take away 4 to reach 10. What should you do next?",
    "explanation": "Five is four and one. After taking away four, take away one more to get nine.",
    "skill": "Complete a bridge-through-ten strategy",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "Take away 1.",
      "Add 1.",
      "Take away 5."
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P18",
    "questionId": "P18",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Choose an easy pair to add first.\n4 + 6 + 3 = ?",
    "explanation": "Four and six make ten. Add the last three to make thirteen.",
    "skill": "Group addends to make ten",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "10",
      "13",
      "12"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P19",
    "questionId": "P19",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "For 8 + 4, Sam starts at 8 and says “9, 10, 11”. What is missing?",
    "explanation": "Sam has counted on only three. One more step reaches 12.",
    "skill": "Diagnose a count-on error",
    "responseType": "mcq",
    "difficulty": 3,
    "cognitiveDemand": "reason",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "One more counting step.",
      "Four more counting steps.",
      "A step backwards."
    ],
    "correct": 0
  },
  {
    "id": "AC9M1N04-P20",
    "questionId": "P20",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "The whole is 16. Its parts are 10 and 6. Write two different subtraction equations.",
    "explanation": "Subtract either part from the whole to find the other part.",
    "skill": "Create related subtraction facts",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "create",
    "visualModel": null,
    "acceptanceNote": "Accept both 16 − 10 = 6 and 16 − 6 = 10, in either order or with reversed equality.",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "correct": "16 − 10 = 6; 16 − 6 = 10",
    "modelAnswer": "16 − 10 = 6; 16 − 6 = 10"
  },
  {
    "id": "AC9M1N04-P21",
    "questionId": "P21",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Which calculation also has the answer 7?",
    "explanation": "Twelve take away five leaves seven. Counting up from 5 to 12 is another way to check.",
    "skill": "Match a subtraction result",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "12 + 5",
      "12 − 7",
      "12 − 5"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P22",
    "questionId": "P22",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "A card says __ + 4 = 15. Which number belongs in the gap?",
    "explanation": "Eleven and four make fifteen. You can find the missing part with 15 − 4.",
    "skill": "Find a missing addend",
    "responseType": "mcq",
    "difficulty": 2,
    "cognitiveDemand": "apply",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "19",
      "9",
      "11"
    ],
    "correct": 2
  },
  {
    "id": "AC9M1N04-P23",
    "questionId": "P23",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "18 − 18 = ?",
    "explanation": "Taking away all eighteen leaves none. None is written as zero.",
    "skill": "Subtract the whole",
    "responseType": "mcq",
    "difficulty": 1,
    "cognitiveDemand": "recognise",
    "visualModel": null,
    "acceptanceNote": "",
    "printable": true,
    "type": "single",
    "answers": [
      "18",
      "0",
      "1"
    ],
    "correct": 1
  },
  {
    "id": "AC9M1N04-P24",
    "questionId": "P24",
    "curriculumCode": "AC9M1N04",
    "bank": "practice",
    "bankVersion": "20260906-y1-original-v1",
    "question": "Make 18 from two different numbers. Both numbers must be greater than 0. Write an addition equation.",
    "explanation": "The two chosen parts must total 18. Ten and eight are one possible pair.",
    "skill": "Create a constrained number pair",
    "responseType": "short_answer",
    "difficulty": 3,
    "cognitiveDemand": "create",
    "visualModel": null,
    "acceptanceNote": "Accept any two different positive whole numbers totalling 18, such as 1 + 17, 2 + 16, 3 + 15, 4 + 14, 5 + 13, 6 + 12, 7 + 11 or 8 + 10, in either order.",
    "printable": true,
    "type": "text",
    "correct": "10 + 8 = 18",
    "acceptedAnswers": [
      "1+17=18",
      "2+16=18",
      "3+15=18",
      "4+14=18",
      "5+13=18",
      "6+12=18",
      "7+11=18",
      "8+10=18",
      "10+8=18",
      "11+7=18",
      "12+6=18",
      "13+5=18",
      "14+4=18",
      "15+3=18",
      "16+2=18",
      "17+1=18",
      "18=1+17",
      "18=2+16",
      "18=3+15",
      "18=4+14",
      "18=5+13",
      "18=6+12",
      "18=7+11",
      "18=8+10",
      "18=10+8",
      "18=11+7",
      "18=12+6",
      "18=13+5",
      "18=14+4",
      "18=15+3",
      "18=16+2",
      "18=17+1"
    ],
    "answerFormat": "equation"
  }
];
