"use strict";
window.skillrTestQuestions = [
{id:"AC9M1M03-T01",questionId:"T01",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"Which duration is longest?",explanation:"A year is longer than a week or an hour.",skill:"compare named durations",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["1 hour","1 year","1 week"],correct:1},
{id:"AC9M1M03-T02",questionId:"T02",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"The plan is: paint, let the paint dry, display the picture. What happens just after painting?",explanation:"Letting the paint dry is the next event in the given sequence.",skill:"locate next event",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["Let the paint dry","Display the picture","Start painting again"],correct:0},
{id:"AC9M1M03-T03",questionId:"T03",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"The days go Tuesday, Wednesday, Thursday, Friday. A visit is on Thursday. Which day is just before the visit?",explanation:"Wednesday is immediately before Thursday.",skill:"locate prior weekday",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["Tuesday","Friday","Wednesday"],correct:2},
{id:"AC9M1M03-T04",questionId:"T04",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A calendar lists October, November, December. Which month comes between October and December?",explanation:"November follows October and comes before December.",skill:"complete month sequence",responseType:"short_answer",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"Accept November.",printable:true,type:"text",correct:"November",acceptedAnswers:["November"],answerFormat:"plain"},
{id:"AC9M1M03-T05",questionId:"T05",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A game lasts 1 hour. A trip lasts 1 week. Which lasts less time?",explanation:"An hour is a shorter duration than a week.",skill:"compare event durations",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["They last the same time.","The trip","The game"],correct:2},
{id:"AC9M1M03-T06",questionId:"T06",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A child measures the wait from one birthday to the next in hours. Which unit would describe this wait more simply?",explanation:"The wait from one birthday to the next is one year.",skill:"improve time-unit choice",responseType:"mcq",difficulty:3,cognitiveDemand:"reason",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["Years","Hours","Days"],correct:0},
{id:"AC9M1M03-T07",questionId:"T07",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"Use this calendar row.\nMonday: 15\nTuesday: 16\nWednesday: 17\nThursday: 18\nFriday: 19\nThe trip is on Thursday. What is its date?",explanation:"The Thursday column shows the date 18.",skill:"read date from calendar weekday",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:{type:"table",headers:["Monday","Tuesday","Wednesday","Thursday","Friday"],rows:[["15","16","17","18","19"]]},acceptanceNote:"",printable:true,type:"single",answers:["The 18th","The 17th","The 19th"],correct:0},
{id:"AC9M1M03-T08",questionId:"T08",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"Put these durations in order from longest to shortest: 1 day, 1 year, 1 month.",explanation:"A year contains months, and a month is much longer than one day.",skill:"order time units",responseType:"short_answer",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"Accept year, month, day in this order.",printable:true,type:"text",correct:"1 year, 1 month, 1 day",acceptedAnswers:["1 year 1 month 1 day","year month day","one year one month one day"],answerFormat:"word-sequence"},
{id:"AC9M1M03-T09",questionId:"T09",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"In the usual Australian four-season calendar, which season comes after autumn?",explanation:"Winter follows autumn in the usual Australian four-season cycle.",skill:"season sequence",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["Spring","Winter","Summer"],correct:1},
{id:"AC9M1M03-T10",questionId:"T10",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A puppet show lasts 2 hours. A music show lasts 1 hour. Which statement is true?",explanation:"Two hours is a longer duration than one hour.",skill:"compare same-unit durations",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["The music show lasts longer.","The shows last equally long.","The puppet show lasts longer."],correct:2},
{id:"AC9M1M03-T11",questionId:"T11",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"The months go December, then January in the new year. Which month comes after December?",explanation:"The month sequence starts again with January after December.",skill:"month year rollover",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["November","October","January"],correct:2},
{id:"AC9M1M03-T12",questionId:"T12",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A club meets for 1 hour before lunch and 2 hours after lunch. Do not count lunchtime. How many hours does the club meet?",explanation:"One hour and two hours make three hours of club time.",skill:"combine separate durations",responseType:"short_answer",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"Accept 3 or three hours.",printable:true,type:"text",correct:"3 hours",acceptedAnswers:["3","three","3 hours","three hours"],answerFormat:"plain"},
{id:"AC9M1M03-T13",questionId:"T13",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"A week has 7 days. A holiday lasts 7 days. A child calls this ‘one month’. Which name matches the duration?",explanation:"Seven days make one week.",skill:"correct calendar duration label",responseType:"mcq",difficulty:3,cognitiveDemand:"reason",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["One hour","One week","One year"],correct:1},
{id:"AC9M1M03-T14",questionId:"T14",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"The months go February, March, April. The sports day is in April. The picnic is in February. Which happens first?",explanation:"February comes before April.",skill:"order calendar events",responseType:"mcq",difficulty:2,cognitiveDemand:"apply",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["They happen in the same month.","The picnic","The sports day"],correct:1},
{id:"AC9M1M03-T15",questionId:"T15",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"Which pair describes a shorter time followed by a longer time?",explanation:"One hour is shorter than one day. The other pairs go from longer to shorter.",skill:"identify increasing duration pair",responseType:"mcq",difficulty:3,cognitiveDemand:"reason",visualModel:null,acceptanceNote:"",printable:true,type:"single",answers:["1 hour, then 1 day","1 year, then 1 month","1 week, then 1 day"],correct:0},
{id:"AC9M1M03-T16",questionId:"T16",curriculumCode:"AC9M1M03",bank:"test",bankVersion:"20260911-gateway-v2",question:"Plan a usual school day with these events: go home after school, arrive at school, eat lunch at school. Write them in order.",explanation:"Arriving comes first, lunch is during school, and going home is after school.",skill:"create daily sequence",responseType:"short_answer",difficulty:3,cognitiveDemand:"create",visualModel:null,acceptanceNote:"Accept arrive, lunch, go home in this order.",printable:true,type:"self-check",gradingMode:"adult-review",correct:"Arrive at school, eat lunch at school, go home after school",modelAnswer:"Arrive at school, eat lunch at school, go home after school"}
];