"""Original LE05 models and specific composing/editing tasks."""
import json
from pathlib import Path
items=[]
def base(b,q):
 n=sum(x['bank']==b for x in items)+1
 return dict(id=f'AC9E3LE05-{b[0].upper()}-{n:03d}',subject='english',year_level='Year 3',curriculum_code='AC9E3LE05',bank=b,skill='Create and edit imaginative texts',question=q,audio_prompt=q,visual={'type':'none'},source={'creator':'SkillrHub original model text'})
def mc(b,t,ask,c,w,why):
 x=base(b,t+'\n\n'+ask);p=sum(a['bank']==b and a.get('grading_mode')!='adult-review' for a in items)%4;opts=w[:];opts.insert(p,c);x.update(answers=[{'text':s,'is_correct':j==p} for j,s in enumerate(opts)],correct_index=p,explanation={'summary':why,'hint':'Keep the intended event while making the requested change.'});items.append(x)
def task(b,t,ask,model,note):
 x=base(b,'Model: '+t+'\n\n'+ask);x.update(grading_mode='adult-review',answers=[],correct_index=None,model_answer=model,acceptance_note=note+' Check both the new writing and the requested revision. Other original solutions are welcome when they meet the stated constraints.',response_instructions='Write your own short version. Reread it, make the requested edit, and show or describe what you changed. An adult checks the writing and revision.',completion_label='My writing and edit are on paper; an adult still needs to check them.',explanation={'summary':model,'hint':'Use the model as a starting point, then make your own meaningful change.'});items.append(x)
mc('practice','Draft: The fox went quickly across the clearing.','Which revision makes the movement more precise without changing the event?','The fox dashed across the clearing.',['The fox slept across the clearing.','The fox never reached the clearing.','The clearing turned into a fox.'],'Dashed conveys quick movement; the alternatives replace the event or meaning.')
mc('practice','Draft events: (1) The child thanked the helper. (2) The kite became stuck. (3) The helper freed the kite.','Which order creates a clear problem and solution?','2, 3, 1.',['1, 2, 3.','3, 1, 2.','2, 1, 3.'],'The stuck kite creates the problem, freeing it solves it, and thanks follows the help.')
mc('practice','Model: A mouse hid a seed beneath a leaf. / New setting: a snowy field.','Which adaptation makes the hiding place fit the new setting?','The mouse tucked the seed beneath a drift of snow.',['The mouse tucked the seed beneath the same leaf in the same warm garden.','The seed became an ocean with no mouse.','The mouse forgot that the story had a seed.'],'The revision preserves the hiding action and changes the immediate setting detail to snow.')
mc('practice','Draft: “I am excited,” said Luca. / Aim: show excitement through action.','Which revision meets the aim?','Luca bounced on his toes and grinned at the unopened parcel.',['Luca was excited, very excited.','Luca was not in the story.','Luca quietly described the weather forecast.'],'The action and expression convey the intended excitement rather than only repeating its label.')
mc('practice','Draft: First the boat drifted out. Next it reached the island. ___, the friends stepped onto the sand.','Which word most clearly marks the final event?','Finally.',['Yesterday.','Before.','Never.'],'Finally signals the last event in this stated sequence.')
mc('practice','Model: “Can you help?” asked the bird. The rabbit nodded. / Adaptation aim: keep the request for help but use a robot and a child.','Which opening preserves that idea?','“Can you help?” asked the robot. The child nodded.',['The robot shouted goodbye and left without speaking to anyone.','The child found no robot and went home.','The bird and rabbit stayed exactly as they were.'],'The roles change while the help request and response remain.')
mc('practice','Draft: The room was spooky. / Revision aim: add a sound detail that supports this mood.','Which addition fits?','A slow scrape came from behind the locked cupboard.',['Sunshine warmed the picnic blanket outside.','The room was very spooky and spooky again.','The room had been measured last Tuesday.'],'The unexplained scraping sound develops the intended atmosphere.')
mc('practice','Draft: Poppy found the key. Poppy opened the box. Poppy smiled at the tiny bell inside.','Which edit reduces repeated names while keeping the meaning clear?','Poppy found the key. She opened the box and smiled at the tiny bell inside.',['She found it. It opened her. They smiled.','Poppy found no key and left the box shut.','The bell smiled at a key that found Poppy.'],'She clearly refers to Poppy and the sequence is retained.')
mc('practice','Story problem: The bridge is broken and the friends need to cross a narrow stream.','Which ending resolves that problem?','They found a safe shallow crossing with their guide and reached the other side.',['The friends described the broken bridge again and stopped.','A new unrelated character ordered a cake.','The stream had a name, but nobody crossed.'],'The ending supplies a crossing and arrival, rather than only repeating or abandoning the problem.')
mc('practice','Draft: The rain made a noise on the roof. / Aim: imitate the sound in words.','Which revision does that?','Tap-tap! Rain drummed on the roof.',['The rain was wet on the roof.','The roof had four corners.','The rain fell during the day.'],'Tap-tap directly imitates a repeated sound and drummed adds a sound-related verb.')
mc('practice','Model: The little boat waited for the tide. / Revision aim: tell the same moment from the boat’s viewpoint.','Which version changes the viewpoint as requested?','I waited for the tide to lift me.',['The little boat waited for the tide.','They built a new boat last winter.','The sailor forgot the name of the sea.'],'I makes the boat the first-person speaker while keeping its wait.')
mc('practice','Draft: In the morning, the friends packed. Later, they set off. In the evening, they reached the hut. / Edit: replace “Later” with “Before they packed”.','Why should that edit be reconsidered?','It reverses the intended order of packing and setting off.',['It changes the friends into animals.','It removes every time word.','It makes the hut disappear.'],'Before they packed places departure before packing, contradicting the original sequence.')
practice='''A snail carried a letter across the garden.|Write three sentences about a different small creature delivering something. Then edit one movement verb to make the journey more precise.|A beetle carried a ribbon to the gate. It crawled beneath a twig and delivered the ribbon to a waiting ant. I changed went to crawled.|Require a changed creature/object, a delivery sequence and a identified meaningful movement-verb revision.
The lantern went out just as Ada reached the cave.|Create a short opening by moving this problem to a different setting. Then replace one setting detail that no longer fits.|The torch went out as Ada reached the attic. Dust lay on the boxes beside her. I changed cave wall to stacked boxes.|Look for the same loss-of-light problem in a coherent new setting and an edited detail that fits it.
“I will try again,” said the small kite.|Write a three-line poem in which a different object keeps trying. Then improve one repeated word or phrase so the determination is clear.|The little wheel rolled back. “Once more,” it said. “Once more, up the track.” I replaced again with once more in both lines.|Accept different objects and wording; require an intentional repeated pattern and a stated revision.
Tom was nervous before the curtain rose.|Write two sentences showing the feeling through action or speech without using nervous. Then revise one vague action.|Tom twisted the corner of his sleeve. “Will you stand beside me?” he whispered. I changed moved his hands to twisted the corner of his sleeve.|Judge whether the supplied context and actions plausibly show the intended feeling; do not require one universal body signal.
A bird found a shiny button and thought it was a coin.|Adapt the mistaken-object idea into a short story with a different character and object. Then edit the ending to reveal the mistake clearly.|A mouse found a foil circle and thought it was a tiny plate. When it unwrapped, the mouse discovered a chocolate wrapper. I added the wrapper reveal.|Require a coherent mistaken identity and a clear reveal, not just renamed characters.
The friends heard a sound behind the door.|Write three sentences that build curiosity before the door opens. Then edit out a sentence that gives the answer away too soon.|A soft tapping came from the cupboard. Jo held the handle still. Then a small paw slid beneath the door. I removed There was a kitten inside from the opening.|Accept different reveals; require a deliberate delay and an identifiable deleted or moved clue.
The rabbit solved the problem alone.|Rewrite a short scene so two characters solve a problem together. Then edit one sentence to show how each contributes.|The rabbit could not reach the apple. The duck steadied a basket while the rabbit climbed onto it. I added the duck’s job so both help.|Require a supplied problem, complementary contributions and a revision clarifying one role.
Cold wind crossed the empty yard.|Create a warm, welcoming version of this setting in two or three sentences. Then replace a word that still belongs to the cold mood.|Warm light filled the yard. Friends waved from a table under the tree. I changed shivered to smiled to fit the welcome.|Look for coherent changes in atmosphere, not an isolated adjective that conflicts with the rest.
A small boat crossed the pond and returned home.|Adapt this journey into a beginning, problem and solution. Then revise a time connection so the order is clear.|A toy boat left the shore. A twig blocked its path, but a ripple carried it free. At last it returned. I changed then to at last in the ending.|Require a recognisable journey with an obstacle/resolution and a purposeful sequencing edit.
The spoon sang in the soup.|Write two playful lines about an ordinary object doing something impossible. Then replace one dull verb with a more vivid one.|The teapot danced across the tray. It twirled until the cups cried, “Stay!” I replaced moved with twirled.|Accept any coherent playful object/action and a meaningful verb improvement; rhyme is optional.
Mira lost her map but noticed footprints.|Continue the model for three sentences, using the footprints to affect the plot. Then edit a detail so the clue is useful.|The prints led to the camp’s water barrel. Mira followed them and found her map on the lid. I changed marks to bootprints leading towards camp.|Require the clue to help shape events; the map’s recovery can differ if the logic is clear.
The giant frightened everyone with his loud footsteps.|Write a scene revealing that the giant is trying to help. Then edit one action to make that intention clearer.|The giant lifted a fallen branch from the road. “Can the little carts pass now?” he asked. I changed waved his arms to lifted the branch.|Look for a helpful action that changes the first impression; avoid relying only on He was kind.
The rain tapped on the roof.|Write three lines that use a sound-word pattern for a different weather event. Then read it aloud and edit one awkward part of the pattern.|Whoosh went the wind, whoosh through the tree. Whoosh past the gate, then away from me. I removed a long phrase to keep the repeated beat.|Require an original weather sound pattern and a specific revision after reading; exact metre is not required.
A child opened a box and found a feather.|Write two different possible final sentences: one ordinary and one surprising. Then improve one ending so it connects to the feather.|Ordinary: She added it to her nature display. Surprising: The feather lifted her chair towards the ceiling. I added feather to show what caused the lift.|Require both endings to relate to the found object; surprise need not follow the example.
The old clock refused to tick.|Create a short conversation between the clock and another object. Then edit the dialogue so the speakers are clear.|“I need a rest,” said the clock. “I can keep watch,” replied the lamp. I added replied the lamp to identify the second speaker.|Check an imaginative exchange and a concrete speaker-clarity edit; no exact punctuation penalty should replace content assessment.
A little seed dreamed of seeing the sky.|Retell this idea from the seed’s first-person viewpoint. Then check and edit any viewpoint word that changes by accident.|I pushed against the soil. At last I saw a strip of blue. I changed the seed saw to I saw so the voice stayed the same.|Require consistent first person and an identified check/revision; a different growth event is acceptable.
The team found a locked gate beside the park.|Move the scene to a make-believe setting and add one feature that affects what happens. Then edit a detail to keep the new setting consistent.|The team found a cloud gate above the town. A gust moved its lock out of reach. I replaced gravel path with a ribbon of cloud.|Require a new setting feature with a plot consequence, not only a place-name swap.
The dog ran after the ball.|Write a short scene that shows how the dog moves on a slippery surface. Then change one general verb to fit that surface.|The dog skidded across the wet tiles and scrambled for balance. The ball rolled beneath a chair. I changed ran to skidded.|Accept plausible different movement and an actual revision; avoid unsafe instructions, as this is a fictional scene.'''
for line in practice.splitlines():task('practice',*line.split('|'))
more='''A traveller followed a red ribbon through the forest.|Create a short journey using a different trail to guide the character. Then revise a sentence to show why the trail can be followed.|Lena followed chalk arrows through the old courtyard. Each arrow pointed to the next arch. I added the direction detail to make the trail useful.|Require a changed guide, a coherent journey and a revision establishing how the clue works.
The puppet wanted to dance but its string was tangled.|Write a problem-solving scene with a helper. Then edit the solution so it addresses the tangled string rather than an unrelated problem.|The puppet asked the toy maker for help. She loosened the knot and the puppet turned in a circle. I changed she painted its shoes to she loosened the knot.|Require a solution connected to the stated obstacle, with a specific repair to the draft.
A child found a tiny crown beneath a bench.|Write an opening that could lead into a mystery. Then remove or change one detail that explains the mystery too early.|The crown was no bigger than a button. Beside it lay three tiny footprints. I removed the fairy dropped it so the owner stays unknown.|Accept different clues and possible owners; require a deliberate decision about withheld information.
The sun was bright. The path was long. The friends walked.|Rewrite this as a short scene where the weather affects the journey. Then edit a link between cause and action.|The bright sun heated the long path, so the friends rested under a tree. Later they continued. I added so to link the heat and the rest.|Require a plausible connection between setting and action, not only extra adjectives.
A dragon guarded a mountain of treasure.|Adapt the character’s goal so it protects something unexpected. Then revise one detail that still refers to treasure.|The dragon guarded a tiny seedling from cold winds. It curled its tail around the pot. I changed gold coins to fallen leaves near the pot.|Require a changed goal reflected in actions and a consistency edit.
“Come here,” said Ben. “Look at this,” said Ben.|Create a two-person conversation about a discovery. Then edit a repeated speaker tag or unclear pronoun.|“Come here,” Ben called. “A blue egg!” whispered Jo. I added Jo’s name so the second voice is clear.|Require two distinguishable speakers, a discovery and a meaningful clarity edit.
The fox crept towards the basket.|Write a scene that first seems sneaky but turns out to be helpful. Then add a clue that makes the ending believable.|The fox crept near the basket to avoid waking the chicks. He covered them with a leaf. I added the sleeping chicks before the helpful act.|Require a coherent change of interpretation and an earlier supporting clue, not a completely unrelated twist.
The kite rose. The string snapped. The child watched it drift away.|Change the ending so the problem is resolved through an action already introduced. Then edit the opening to include that useful action or object.|The child had brought a long pole. When the kite caught in a low branch, she used the pole to reach it. I added the pole at the beginning.|Accept safe fictional alternatives; require setup that supports the chosen resolution.
A quiet pond reflected the trees.|Create two sentences showing this place becoming lively. Then revise one sound or movement detail to sharpen the change.|Ducks splashed into the quiet pond. Ripples shook the reflected branches. I changed moved to shook to make the change clearer.|Require a contrast from still to active and an explicit detail revision.
The mouse wrote a note to the moon.|Write the moon’s reply in two or three sentences. Then edit the reply so it answers something from your mouse’s note.|Mouse asks for light on the path. Moon replies, “I will shine above the gate tonight.” I added the gate to connect the reply to the request.|The learner supplies a brief request and related reply; check the link, not agreement with this request.
A character reaches a fork with two paths.|Write a short choice and consequence. Then edit the consequence so it follows from the chosen path.|Moss chose the muddy path to the pond. Mud slowed his steps, so he arrived after the ducks. I replaced an unrelated snowstorm with muddy steps.|Require a meaningful connection between choice and outcome, with a stated edit.
The toy train carried one passenger around the room.|Change the story’s scale so the room feels enormous to a tiny passenger. Then revise a plain object description to fit that viewpoint.|To the tiny passenger, the chair legs were towers. The train curved around a mountain of cushions. I changed chair to towering chair legs.|Require consistent scale through at least one image and an identified descriptive revision.
A character says, “I am disappointed.”|Write two sentences that show the feeling after a specific event. Then replace a vague word such as did, went or said where useful.|After the game was cancelled, Pia folded the team banner and sighed. “Maybe next week,” she murmured. I changed said to murmured.|Require event-linked feeling and a meaningful revision; do not demand a single physical signal or verb.
An old shoe floated down a stream.|Turn the shoe into a boat for a small character. Then edit a setting detail so it creates a challenge for the boat.|An ant climbed into the shoe. A twig jammed it beside a stone, so she pushed with a leaf stem. I changed smooth water to water circling the stone.|Require adapted object use, a setting-based obstacle and revision; different solutions are acceptable.
A story begins with a missing bell and ends with a celebration.|Write the middle in three sentences so the ending makes sense. Then edit a time word to clarify the sequence.|The friends searched the shed. Next, they found the bell beneath a scarf. At last they rang it to begin the party. I changed first to at last in the final sentence.|Require discovery or another logical link to the celebration and a purposeful sequencing edit.
The stars blinked above a sleeping town.|Write a short poem that gives a different natural thing a human-like action. Then edit one line so the image stays consistent.|The river hummed beneath the bridge. It rocked the reeds to sleep. I removed a line about a roaring engine to keep the gentle river image.|Accept different moods and nature images; require a deliberate consistency revision.
A child brings a carefully wrapped parcel to a friend.|Write two sentences building anticipation and a third revealing a surprising but suitable gift. Then edit one clue to prepare the reader.|The box rustled and smelled of mint. Kai opened it to find a small herb plant. I added the mint smell before the reveal.|Require a reveal with an earlier compatible clue, not any particular gift.
Two characters argue over a map.|Write an ending where they find a way to use the map together. Then edit one line of dialogue so it helps reach that solution.|“You follow the symbols and I will read the place names,” said Ria. Together they found the path. I changed Give it to me to the shared-job suggestion.|Require a cooperative resolution and a dialogue revision that contributes to it.'''
for line in more.splitlines():task('practice',*line.split('|'))
mc('test','Draft: The child said the secret very quietly.','Which revision preserves the meaning with a more precise verb?','The child whispered the secret.',['The child shouted the secret.','The child forgot every secret.','The secret became a child.'],'Whispered conveys quiet speech while retaining the event.')
mc('test','Model: A lost hedgehog followed a lantern home. / Adaptation: a lost robot in a space station.','Which detail fits the new setting while preserving the guiding-light idea?','The robot followed the corridor’s green guide lights.',['The hedgehog followed the same lantern through the same hedge.','The robot stayed lost because the writer forgot the guide.','The space station was removed from the story.'],'Corridor guide lights suit the new setting and keep the guiding role.')
mc('test','Draft events: (1) The rope held the raft steady. (2) A wave pushed the raft away. (3) The sailor threw a rope to the jetty.','Which order gives a clear cause, response and outcome?','2, 3, 1.',['1, 2, 3.','3, 1, 2.','2, 1, 3.'],'The wave creates the problem, throwing the rope responds to it, and the rope then steadies the raft.')
mc('test','Draft: The room was peaceful. A soft lamp glowed. Everyone screamed and smashed chairs for no explained reason.','Which edit best preserves a peaceful scene?','Replace the final sentence with a quiet action that fits the mood.',['Add more unexplained screaming.','Keep all sentences and say the mood never changes.','Remove the lamp but keep all the violent noise.'],'The unexplained loud action conflicts with the stated calm scene; a fitting action restores consistency.')
tests='''A small bird waits for a storm to pass before leaving its nest.|Adapt this into a three-sentence story about a different character waiting for a different obstacle to pass. Then edit one setting detail to fit your change.|A toy car waited for a puddle to drain from the path. When the water shrank, it rolled towards the shed. I changed branches to paving stones.|Require a changed character/obstacle, a coherent wait and a fitting revision.
The door clicked shut behind the explorer.|Write a short continuation with a problem and a possible solution. Then edit one action so it contributes to the solution.|The explorer could not reach the handle. She stacked two firm boxes and climbed high enough. I replaced looking at the ceiling with checking the boxes.|Accept a coherent fictional solution and a meaningful action edit; no need to match this physical setup.
A lost scarf became a blanket for a tiny creature.|Create a different helpful use for an ordinary lost object. Then revise one description to show how the creature uses it.|A dropped cup became a shelter for a beetle. It rested beneath the rim during rain. I added the rim detail to show the shelter.|Require an adapted object use and supporting description, not only changing names.
A character is proud after finishing a difficult task.|Show this in two or three sentences through actions or speech. Then revise a sentence that only labels the feeling.|Nell set the finished model on the table. “It stands by itself now,” she said, smiling. I replaced She was proud with her words and action.|Require an achievement and plausible expressive detail; different actions are valid.
A boat leaves shore, faces a problem and returns.|Write your own three-part version. Then edit a time connection so the reader can follow the journey.|The boat left at dawn. Later a branch blocked the channel, so it turned back. By evening it reached its starting shore. I added by evening to mark the return.|Require beginning/problem/return and a stated sequence revision; the problem need not match the model.
An umbrella complains that nobody takes it outside.|Write a reply from its owner that changes what happens next. Then edit the dialogue to make both speakers clear.|“The rain has started,” said Jo. “Then let’s go!” replied the umbrella. I named Jo in the first tag so the voices are clear.|Require an imaginative exchange that affects the event and speaker clarification.
A silent street becomes noisy when an unusual visitor arrives.|Create a short scene and include one sound imitation. Then edit a general sound word to make it more specific.|Clang! A walking saucepan stepped into the empty street. Its lid rattled with every step. I replaced noise with clang.|Require a changed soundscape, an original visitor and a sound-word revision.
Two friends find a clue inside a hollow tree.|Write a mystery opening that keeps the answer unknown. Then revise a clue so it is specific enough to be interesting.|A blue thread hung from a tiny brass hook. Beside it lay a note with half a name. I changed something blue to a blue thread.|Require a specific clue and a purposeful detail edit; the mystery need not be solved.
A character who usually works alone needs help.|Create a scene where asking another character changes the outcome. Then edit a line so the request is clear.|The mouse could not move the lid. “Could you lift this side?” she asked the frog. Together they opened the box. I made the request name the needed action.|Require a clear help request, contribution and outcome, with a revision.
A bright garden is the model setting.|Rewrite it as a quiet evening setting in two or three sentences. Then remove or change a detail that conflicts with evening.|The last light lay across the path. Crickets began their song beneath the leaves. I changed midday glare to the last light.|Require consistent evening detail and an identified revision; no particular animal is mandatory.
A story ends with a child finding the missing key.|Write an opening that plants a useful clue, then write the ending. Edit the clue or ending so they connect.|Opening: A silver glint showed beneath the mat. Ending: Jo lifted the mat and found the key. I changed glint in a distant window to beneath the mat.|Require a clear setup/payoff relationship, not the exact hiding place.
The moon watches a traveller going home.|Retell the moment in the traveller’s first-person voice. Then edit any word that accidentally changes the viewpoint.|I followed the pale path towards my door. Above me, the moon shone through the clouds. I changed the traveller followed to I followed.|Require a consistent first-person retelling and a stated viewpoint check/edit.'''
for line in tests.splitlines():task('test',*line.split('|'))
assert len(items)==64,len(items)
assert sum(x['bank']=='practice' for x in items)==48
Path(__file__).with_name('ac9e3le05.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
print('LE05: 64 original tasks; 48 composing/editing responses and 16 applied revision checks.')
