"""Original evidence-grounded LE03 literary interpretation tasks."""
import json
from pathlib import Path
items=[]
def base(b,t,q):
 n=sum(x['bank']==b for x in items)+1
 return dict(id=f'AC9E3LE03-{b[0].upper()}-{n:03d}',subject='english',year_level='Year 3',curriculum_code='AC9E3LE03',bank=b,skill='Character, setting and narrative mood',question=t+'\n\n'+q,audio_prompt=t+'\n\n'+q,visual={'type':'none'},source={'creator':'SkillrHub original literary text and illustration'})
def mc(b,t,q,c,w,e,visual=None):
 x=base(b,t,q);p=sum(a['bank']==b and a.get('grading_mode')!='adult-review' for a in items)%4;o=w[:];o.insert(p,c);x.update(answers=[{'text':s,'is_correct':i==p} for i,s in enumerate(o)],correct_index=p,explanation={'summary':e,'hint':'Find the particular words or visible details that support your interpretation.'});
 if visual:x['visual']=visual
 items.append(x)
def discuss(b,t,q,m,n,visual=None):
 x=base(b,t,q);x.update(grading_mode='adult-review',answers=[],correct_index=None,model_answer=m,acceptance_note=n+' Accept another plausible interpretation when it is supported by the supplied words or illustration. Do not require the model wording.',response_instructions='Explain your idea and point to the words or picture details that support it. An adult checks your reasoning.',completion_label='I have explained my interpretation aloud or on paper; an adult still needs to check it.',explanation={'summary':m,'hint':'Connect a specific detail with its effect on the reader.'});
 if visual:x['visual']=visual
 items.append(x)
# Every row supplies a different literary situation, not names swapped into one passage.
practice='''Mina slipped her last biscuit into the younger child's lunchbox. “You can have mine,” she said.|What does Mina's action suggest in this moment?|She is generous towards the younger child.|She is trying to hide the lunchbox.;She wants both biscuits for herself.;She has forgotten where her biscuit is.|She gives away her own remaining biscuit, supporting generosity in this situation.
The gate creaked. Beyond it, weeds covered the path and every window was dark.|Which mood do these setting details most strongly support?|An uneasy, deserted feeling.|A busy celebration.;A cosy welcome.;An exciting race.|The creaking gate, overgrown path and dark windows combine to suggest an uneasy deserted place.
“Just one more try,” said Ben. He rebuilt the fallen tower for the fourth time.|Which description is supported by Ben's words and action?|He is determined to keep trying.|He has never built anything before.;He wants someone else to do all the work.;He thinks the tower is already finished.|His repeated rebuilding and request for another try show persistence, not guaranteed success.
The room had felt tense while everyone searched. Then the missing hamster poked its nose out of a slipper, and laughter filled the room.|How does this event change the mood?|From worry to relief and amusement.|From peace to anger.;From joy to disappointment.;From boredom to loneliness.|The search is tense, but the safe discovery brings laughter and relief.
Saffron light lay across the quilt. A kettle hummed and Nan made room beside her.|Which pair of details helps create a welcoming setting?|The warm light and Nan making room.|The quilt's exact price and the kettle's age.;The room's darkness and an empty chair.;The sound of thunder and a locked door.|The gentle light and invitation to sit support welcome; the other pairs are not supplied.
“I don't need help,” said Ravi, but he held out the tangled string towards Jo.|What do the words and action together suggest?|Ravi may want help despite what he says.|Jo has already cut the string.;Ravi has finished untangling it.;The string belongs to a stranger.|Holding the tangled string towards Jo suggests a possible wish for help; it does not prove the reason for his words.
The little boat rocked softly beside the reeds. No engine broke the stillness.|Which word choice most contributes to a peaceful mood?|“rocked softly”.|“little boat” alone.;“beside” alone.;“engine” alone.|Softly describes gentle movement, reinforced by the stillness and absence of engine noise.
Tess checked the address twice and wrapped the glass bird in another layer of paper.|What does this show about Tess's approach to sending the parcel?|She is taking care with it.|She knows it cannot break.;She wants to send it to the wrong house.;She has decided to throw it away.|Checking the address and adding protective wrapping show care, without proving the parcel will arrive safely.
A bell rang from the empty tower. Lila stopped halfway across the square. Nobody had been inside all day.|What makes the event mysterious?|A sound comes from a place described as empty.|The square has a name.;Lila knows exactly who rang it.;The tower has no bell.|The unexplained ringing conflicts with the apparent emptiness; the text has not revealed its cause.
Omar saved a seat and waved when the new pupil entered. “Over here—there's space for you.”|How is Omar portrayed through dialogue and action?|As welcoming the new pupil.|As refusing to share a seat.;As pretending not to see anyone.;As asking the new pupil to leave.|His wave, saved seat and invitation all support a welcoming action.
The rain finally stopped. One patch of blue opened above the flooded garden, and Ada began planning where to plant again.|Which mood is suggested by the ending?|Hope after a difficult time.|Certainty that every plant has recovered.;Anger at a friend.;Fear of planting anything again.|The clearing sky and Ada's future plan suggest hope, but do not prove the garden has recovered.
“That's my mistake,” said Finn. He rubbed out the wrong total and began again.|Which interpretation has direct support?|Finn accepts responsibility for this error.|Finn never makes mistakes.;Someone else did the calculation.;Finn refuses to correct the work.|He names the error as his own and corrects it; the text does not establish a lifelong trait.'''
for row in practice.splitlines():
 t,q,c,w,e=row.split('|');mc('practice',t,q,c,w.split(';'),e)
# 28 distinct discussion passages plus eight image-linked tasks = 48 Practice.
rows='''The corridor smelled of fresh paint. All the classroom doors were shut, and I could hear only my own shoes.|Explain how two details could make this school setting feel unfamiliar or lonely.|The shut doors and sound of only the narrator's shoes suggest few people are nearby, which could feel lonely.|Require two supplied details linked to the proposed mood; fresh paint alone does not prove loneliness.
“I'll hold the ladder while you climb,” said Sal. She kept both hands on it until her brother stepped down.|How do the words and action portray Sal in this scene?|Her promise and continued grip portray her as supporting her brother carefully.|Require the promise and continued action; do not require claims about all of Sal's behaviour.
At first the audience whispered and shuffled. When the tiny puppet bowed, everyone fell silent and leaned forward.|Explain how the event changes the atmosphere.|The bow draws attention, changing a restless atmosphere into an expectant one.|Connect the before-and-after audience details to the shift; silence need not mean fear.
The orchard branches bowed with fruit. Beneath them, fallen apples gave off a sweet smell.|How does the language help you imagine this setting? Explain the effect of one sight and one smell detail.|The bending branches suggest abundant fruit, and the sweet smell makes the orchard feel vivid and ripe.|Require the visible abundance and stated smell; do not infer a season or location as certain.
Jia pulled a chair beside the lonely visitor. She asked about the visitor's journey and waited for the answer.|What do Jia's choices reveal here? Support your idea with two details.|Moving close and asking then waiting suggest that Jia wants to include and listen to the visitor.|Require two actions and a plausible interpretation, not a claim based on the name.
The tunnel swallowed the last daylight. Ahead, water dripped somewhere beyond the torch beam.|Explain how the setting creates suspense without telling us that a monster is present.|The disappearing daylight and unseen dripping leave part of the tunnel unknown, creating suspense. No monster is stated.|Require uncertainty grounded in the supplied setting; reject an invented monster as a fact.
“Easy,” muttered Cal. Then he read the instructions a third time before touching the controls.|How might the contrast between speech and action affect your view of Cal?|His words sound confident, but rereading suggests he may be cautious or less certain than he sounds.|Accept caution or uncertainty; rereading does not prove dishonesty or inability.
A hundred paper stars shimmered above the hall. Music spilled through the doorway as the guests arrived.|Choose a mood and explain how two details in the language support it.|A festive mood is supported by the shimmering decorations, music and arriving guests.|Require at least two supplied details; different supported celebratory words are valid.
The fox offered to carry the basket. Each time the rabbit looked away, the fox lifted its lid and sniffed.|Explain what the repeated action makes you wonder about the fox.|It makes me wonder whether the fox is interested in the basket's contents rather than only helping, because it peeks when unseen.|Require an inference framed as possible; theft has not occurred in the passage.
The kite dropped into the mud. For a moment nobody spoke. Then Mum said, “We still have paper at home.”|How does the final line affect the mood after the accident?|It offers a way to try again, bringing some hope after the disappointed silence.|Connect the silence and replacement materials; do not claim a new kite has already been made.
Beyond the station, the rails glittered into the distance. “Imagine how far they go,” whispered Kit.|How do setting and dialogue work together to suggest a sense of possibility?|The rails stretch away, and Kit imagines their reach, making the distance seem full of possibilities.|Require the distance and Kit's words, not an invented destination.
The giant folded the torn blanket into a pillow for the mouse. “Is that soft enough?” he asked.|Explain how this action changes an expectation a reader might have about a giant.|Although a reader might expect roughness from a giant, the careful pillow and question portray this giant as considerate.|No requirement to share that expectation; accept direct discussion of considerate portrayal with both details.
Steam curled from the soup. Outside, hail rattled against the glass, but inside our toes began to thaw.|Compare the mood inside and outside using the words provided.|Outside feels harsh because hail rattles; inside feels comforting because of hot soup and warming toes.|Require contrasting supplied sensory evidence, not claims that hail is always dangerous.
Every time the door opened, Bea looked up. She had kept Dad's slice of cake on a separate plate.|What might Bea be waiting for? Explain the clues and what remains uncertain.|She may be waiting for Dad: she watches the door and saves his cake. We do not know when he will arrive.|Require a qualified inference and both clues; no unsupported reason for Dad's absence.
The market traders called across the lane. Bags rustled, wheels rattled and a dog barked beneath a stall.|How do the sound details portray the market's atmosphere?|The many overlapping sounds make it seem busy and lively.|Require at least two specific sounds; readers may find it overwhelming if they explain why.
The captain's voice shook, but she stepped forward. “We need to help them,” she said.|Can a character seem worried and brave in the same scene? Use this passage.|Yes. The shaking voice can suggest worry, while stepping forward to help suggests courage despite it.|Require both sides of the portrayal; a shaking voice alone is not proof of one emotion.
We expected a dusty cupboard. Behind the door stood a garden full of glowing blue leaves.|Explain how the revealed setting changes the reader's expectations and mood.|The ordinary cupboard expectation becomes a magical garden, creating surprise or wonder.|Require contrast between expected and revealed settings; no need to invent why the leaves glow.
“Take the short path,” said Ren. Then Ren noticed the broken railing and led everyone along the longer route.|What does the changed decision suggest about Ren here?|Ren responds to a possible safety concern instead of insisting on the first plan.|Require the broken railing as the reason supported by sequence; do not claim an accident occurred.
The clock ticked above the unopened envelope. Mara reached towards it, stopped, and tucked her hands under her legs.|Explain how the actions and sound can build tension.|The hesitation delays opening the envelope, while the ticking makes the waiting noticeable.|Require hesitation and waiting; the envelope's contents are unknown.
The old dog shuffled to the gate. At the sound of Sam's whistle, it lifted its head and hurried down the path.|How does the change in movement affect the portrayal of the dog?|The shift from shuffling to hurrying suggests the whistle interests or excites the dog.|Require the two movements and trigger; do not assume a specific history with Sam.
Petals floated across the empty pond like tiny boats. The breeze barely stirred the willow.|Explain how the comparison and movement create a mood.|The boat-like petals and barely moving willow create a gentle, peaceful scene.|Require the comparison and slow movement; accept another supported gentle mood.
“I won!” shouted Leo. Then he saw Mei's broken wheel, put down the trophy and helped lift her cart.|How does the final action add to the first impression of Leo?|He is excited about winning, but helping Mei also shows concern for her problem.|Require both the excited speech and help; neither action establishes his entire personality.
The map ended at the cliff. Below us, fog hid the sea, and the path behind had vanished into cloud.|Explain how the setting can make the journey feel uncertain.|The map gives no next route, while fog and cloud hide the surroundings, leaving the travellers unsure where to go.|Require the limited route information and visibility; no invented fall or storm.
A knock interrupted the argument. The neighbours entered carrying the missing puppy, and both sisters ran to meet it.|How does the new event redirect the scene's mood?|The puppy's return shifts attention away from the argument towards a shared welcome, suggesting relief or excitement.|Require the interrupted argument and shared approach; the argument's cause is not stated.
Nora polished the little medal, placed it in its box and opened the box again just to look.|What might the repeated careful attention suggest? Explain without inventing how the medal was earned.|The medal seems important to Nora because she cares for it and looks at it again. The passage does not say how she got it.|Require attention to the object; do not assume victory, age or a particular competition.
The wind tugged at our coats as the ferry pulled away. On the pier, Gran's scarf grew smaller and smaller.|How does the setting help convey a farewell? Give a supported possible mood.|The ferry increases the distance from Gran, and her shrinking scarf makes the separation visible. This could create sadness.|Accept sadness, wistfulness or another supported response; wind alone is not evidence of grief.
“I've never planted one,” said Arlo. He watched the demonstration, then copied each step slowly.|How do speech and action portray Arlo as a learner?|He admits inexperience and pays attention before trying carefully.|Require admission and observed copying; do not equate slowness with low ability.
The last candle went out. Then a row of lanterns flickered on along the path, leading us towards home.|Describe how the sequence could change the mood.|The darkness may briefly feel uncertain, but the guiding lanterns bring reassurance or hope.|Require the light loss and new guidance; do not claim a particular person lit the lanterns.'''
for row in rows.splitlines():discuss('practice',*row.split('|'))
tests='''“You go first,” said Imani, moving her painting aside so her friend had room.|Which interpretation is supported here?|Imani makes space for her friend.|Imani has thrown away the painting.;Imani refuses to share the table.;Imani wants her friend to stop painting.|Her words and movement both show making room for the friend.
The empty swing tapped the fence. Mist blurred the houses at the far end of the street.|Which mood do the setting details most strongly support?|A quiet, slightly eerie mood.|A crowded, cheerful festival.;A noisy sporting contest.;A hot, bright afternoon.|The empty moving swing and obscuring mist support an eerie quietness; no danger is proved.
Eli's shoulders dropped when the model collapsed. Then his sister brought glue and said, “Let's mend it together.”|How does the new event affect the mood?|It introduces hope after disappointment.|It proves the model is already fixed.;It changes delight into anger.;It makes help impossible.|The offer and materials make repair possible, changing the disappointed moment without guaranteeing success.
“I can carry it,” said Pip. Pip took two steps, stopped, and asked, “Could you take this end?”|What does Pip's final question show?|Pip recognises that help would be useful.|Pip has already reached the destination.;Pip refuses every offer of help.;Pip has forgotten what is being carried.|The request revises the initial attempt to carry it alone; it does not prove why the load is difficult.'''
for row in tests.splitlines():
 t,q,c,w,e=row.split('|');mc('test',t,q,c,w.split(';'),e)
tr='''The bakery windows glowed through the drizzle. As the door opened, warm cinnamon air wrapped around us.|How does the language make the bakery seem inviting against the outdoor setting?|The drizzle contrasts with glowing windows and warm scented air, making inside seem comforting.|Require the indoor/outdoor contrast and at least two sensory details.
“My turn?” asked the dragon softly. It waited outside the game circle instead of pushing in.|How is this dragon portrayed? Use both speech and action.|The soft request and waiting portray the dragon as polite or considerate in this scene.|Require the request and waiting; do not assume all dragons act this way.
The branch snapped beneath the basket. Before it fell far, a passing gardener caught it and set it safely down.|Explain how the event changes the tension.|The snapping branch creates concern about a fall; the catch and safe landing bring relief.|Require the problem and resolution; no contents or injuries are stated.
The snow muffled our footsteps. Even the village bell sounded far away.|How do the sound descriptions affect the atmosphere?|Muffled steps and a distant-sounding bell create a hushed, quiet atmosphere.|Accept calm or lonely when linked to the same evidence; do not require one personal mood word.'''
for row in tr.splitlines():discuss('test',*row.split('|'))
# Eight original illustration scenes, each examined through two different reasoning tasks.
scenes=[
('practice','p1','A person leans towards a hut with an arm raised near the face. Rain slants past bent trees; the hut window glows.','“Nearly there,” said Wren, heading towards the hut.','How do Wren’s words and pictured posture portray the effort of reaching the hut?','Nearly there suggests Wren is continuing towards the destination. The forward lean and raised arm suggest effort in the rain.','Require the words and visible posture; do not claim Wren has reached the hut or that the door is unlocked.','Which visible details support a tense journey towards possible comfort? Explain both parts.','The leaning trees and rain suggest rough weather; the lit window offers a hopeful destination.','Require weather evidence and the lit window, not an invented person inside.'),
('practice','p2','A moon hangs above a pond with reeds and a reflection on the water.','We paused beside the pond and let the evening settle around us.','How do the words and picture together create a still moment?','Paused and settle suggest slowing down; the moonlit pond supports the quiet evening setting.','Require one supplied phrase and one visible setting detail.','Would adding a loudly racing motorboat keep the same mood? Explain using the scene.','It would probably change the still mood by introducing loud fast movement into the paused pond scene.','Require comparison with the given still moment; no boat is currently present.'),
('practice','p3','An empty theatre stage has closed curtains and a spotlight on the floor.','Behind the curtain, Nia took one last breath. The show was about to begin.','Explain how the illustration and the final sentence build anticipation.','The closed curtain hides what is coming, while the spotlight and words about the start prepare us for a performance.','Require the hidden stage and approaching start; Nia is not visible.','What can we tell about Nia, and what can we not tell from the picture?','The words place Nia behind the curtain preparing for the start. The picture does not show Nia’s face, so it cannot prove a facial expression.','Require separation of supplied words and unseen expression; a possible feeling must be qualified.'),
('practice','p4','A sunny garden has an open gate, flowers and a path. A smiling person extends an arm towards the gate.','“Come and see what has grown,” called the gardener.','How do the invitation and illustrated gesture portray the gardener?','The invitation and arm extended towards the open gate portray the gardener as welcoming a visitor.','Require the invitation and visible gesture; the passage identifies the gardener, not the clothing.','Which illustrated feature would you change to make entry seem less welcoming, and why?','I could close the gate across the path, making the invitation to enter feel less clear.','Require a specific change to an actual feature and a plausible mood effect; other reasoned edits are valid.'),
('test','t1','A cabin stands in snow with chimney smoke and a footprint trail. A person carrying a bag faces the cabin.','At last, the traveller saw the cabin.','What does the illustration add that might make this arrival feel hopeful?','Smoke from the chimney suggests a fire may be inside, offering possible warmth in the snowy setting.','Require smoke and snow; smoke suggests warmth but does not prove somebody will welcome the traveller.','What does the picture add about the traveller, and does it prove who made the footprints?','The traveller carries a bag and faces the cabin. The trail shows that someone or something has passed along the snow, but does not identify who made the footprints.','Require a visible traveller detail and recognition that the maker of the tracks is uncertain; do not assume the traveller made them.'),
('test','t2','Tall bookcases surround a lamp and an open book in a library.','I found a small circle of light among all those shelves.','Explain how the picture helps you understand the phrase “a small circle of light”.','The lamp lights the reading place while tall shelves surround it, making one small area stand out.','Require the lamp and surrounding shelves; not a magical literal circle unless visible.','What mood could this reading place create? Support your interpretation with two picture details.','The lamp and open book could make it feel quiet and inviting for reading, even among the tall shelves.','Accept cosy, thoughtful or imposing if two visible details genuinely support the response.'),
('test','t3','A boat is tied to a post by a stretched rope beside waves on a windy shore.','The little boat pulled against its rope. “Hold on,” whispered the sailor.','How do language and illustration make this moment feel tense?','Pulled against and hold on suggest strain, while the stretched rope and waves show the boat being held in rough water.','Require one phrase and one visible detail; no broken rope is shown.','Which idea has evidence: the rope may be tested by the water, or the boat is already safely indoors? Explain.','The rope may be tested because it is stretched while waves surround the boat. Nothing shows the boat indoors.','Require the rope/wave evidence and distinguish a possibility from an event already occurring.'),
('test','t4','An empty party space has chairs, drooping bunting and one balloon.','The last guest had gone. Only a balloon kept us company.','How do the words and image show that the lively event is over?','The words say the last guest left; the empty chairs and remaining decorations show the space after the gathering.','Require both text and visible detail.','Could this ending feel peaceful to one reader and lonely to another? Explain with evidence.','The empty chairs and absence of guests could feel lonely, while the end of activity could feel peaceful. The balloon is the only company mentioned.','Accept both explained responses; do not claim every reader must feel the same way.')]
names=dict(p1='p1-storm-hut',p2='p2-moon-pond',p3='p3-theatre',p4='p4-garden',t1='t1-snow-cabin',t2='t2-library',t3='t3-windy-shore',t4='t4-after-party')
for b,s,alt,t,q,m,n,q2,m2,n2 in scenes:
 v={'type':'svg','asset_path':f'/assets/assessment-visuals/year3/english/le03/{names[s]}.svg#scene','alt_text':alt}
 discuss(b,t,q,m,n,v);discuss(b,t,q2,m2,n2,v)
assert len(items)==64,len(items)
assert sum(x['bank']=='practice' for x in items)==48
assert len({x['question'] for x in items})==64
Path(__file__).with_name('ac9e3le03.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
print('LE03: 64 evidence-grounded tasks, including 16 tasks on 8 original illustrations.')
