"""LY06 original complete writing processes and applied editing checks."""
import json
from pathlib import Path
items=[]
def base(b,q):
 n=sum(x['bank']==b for x in items)+1
 return dict(id=f'AC9E3LY06-{b[0].upper()}-{n:03d}',subject='english',year_level='Year 3',curriculum_code='AC9E3LY06',bank=b,skill='Plan, create, edit and publish texts',question=q,audio_prompt=q,visual={'type':'none'})
def mc(b,t,q,c,w,e):
 x=base(b,t+'\n\n'+q);p=sum(a['bank']==b and a.get('grading_mode')!='adult-review' for a in items)%4;o=w.split(';');o.insert(p,c);x.update(answers=[{'text':s,'is_correct':j==p} for j,s in enumerate(o)],correct_index=p,explanation={'summary':e,'hint':'Check the purpose, meaning and specific edit requested.'});items.append(x)
def create(b,title,brief,focus,model,criteria):
 q=title+'\n\n'+brief+'\n\nPlan your main ideas. Draft two short paragraphs and the requested visual. '+focus+' If that feature is already correct, refine its wording or layout to make it clearer. Check tense, topic words, spelling and sentence punctuation. Make at least one useful edit, then produce a neat final version and share it with a partner, adult or class.'
 x=base(b,q);x.update(grading_mode='adult-review',answers=[],correct_index=None,model_answer=model,acceptance_note=criteria+' Inspect the plan, two-paragraph draft, actual visual, identifiable edit and final shared version. Check mostly consistent tense, suitable topic vocabulary, high-frequency and regular spelling, and sentence punctuation. Accept other original solutions that meet the brief. A completion statement alone is not the writing or visual.',response_instructions='Make the text and visual on paper or with a familiar writing tool. Keep your plan and draft so an adult can check the edit and finished work. Sharing with one person counts as publishing.',completion_label='My plan, draft, visual, edit and final shared copy are ready for an adult to check.',explanation={'summary':model,'hint':'Make each paragraph develop one part of your purpose, and make the visual help your reader.'});items.append(x)
a='''Draft: Yesterday we walk to the creek. We watched a small boat pass.|Which edit makes the first sentence fit the past-time account?|Yesterday we walked to the creek.|Yesterday we will walk to the creek.;Tomorrow we walk to the creek.;Yesterday we walking to the creek.|Walked matches yesterday and the following past-tense watched.
Notes: Our class library has picture books, poems and short novels. Pupils can borrow one book each week.|Which opening best fits a paragraph using these notes?|Our class library offers several kinds of books to borrow.|All buildings have walls.;Poems are the only books in our library.;Nobody borrows our books.|It covers the book range and borrowing, without narrowing or contradicting the notes.
Opinion: We should label the art trays. Reason: Labels would help us find materials quickly.|Which example supports that reason?|A tray marked Brushes would show where to look for a brush.|The trays were bought last year.;Some artists paint landscapes.;Brushes can have wooden handles.|The example shows a label helping someone locate a needed item.
A story draft has a problem, then an unrelated list of lunch foods, then the solution to the problem.|Which edit most improves the story's focus?|Remove or connect the unrelated list so the problem and solution remain clear.|Add more unrelated lists.;Remove the problem and keep only the lunch list.;Replace every character name with a number.|Removing or meaningfully connecting the digression helps the intended sequence.
A poster says “Plant swap, Saturday” but gives no place. Its purpose is to help neighbours attend.|Which addition best meets that missing need?|The location of the plant swap.|The writer's favourite colour.;A list of every tree in the country.;A longer word for Saturday.|A location supplies where to attend; unrelated detail does not.
Draft: The boat went across the pond quickly.|Which change makes the movement more precise while retaining the meaning?|The boat sped across the pond.|The boat stayed beside the pond.;The pond vanished.;The boat sank before moving.|Sped conveys quick movement rather than replacing the event.
An informative page has a paragraph about seed planting and a paragraph about watering. A drawing labels the seed's depth.|Where should the drawing go to help the reader most directly?|Beside the planting paragraph.|Inside an unrelated story on the next page.;Over the words so they cannot be read.;In place of every instruction.|The labelled depth relates to planting and should remain readable beside that explanation.
Draft: The children carryed the boxes to the hall.|Which edit corrects the regular past-tense spelling?|The children carried the boxes to the hall.|The children carryied the boxes to the hall.;The children carryd the boxes to the hall.;The children carrieed the boxes to the hall.|Carry changes the final y after a consonant to i before adding ed: carried.
Opinion draft: I prefer the shaded reading corner because it is cooler. For example, the wall thermometer there showed a lower reading at lunchtime than the sunny bench.|What makes the example relevant?|It gives a specific observation connected to the cooler-place reason.|It proves everyone has the same preference.;It changes the topic to painting.;It shows the corner is always colder everywhere.|The observation supports this reason in this situation without making a universal claim.
Story draft: First the bird dropped a ribbon. Next a mouse found it. Finally the mouse tied it to a gift.|Which choice keeps the event order clear?|Keep the first, next and finally connections.|Replace finally with before the bird dropped it.;Remove the middle event and say the mouse never found a ribbon.;Say all three events happened before the first event.|The existing time words match the stated sequence.
Draft title: How to care for our class pencils. Body: Return pencils to the pot. Tell an adult if a point breaks.|Which visual would directly help this text?|A drawing of the labelled pencil pot with an arrow showing where pencils go.|A picture of an unrelated mountain.;A pattern covering the instructions.;A blank frame labelled picture.|The pot and return arrow make the stated action easier to understand.
A writer has finished a draft, but notices that paragraph two repeats paragraph one word for word.|What is a useful next step before sharing?|Revise the second paragraph to develop a different relevant idea.|Share the repeated draft because editing is never needed.;Erase the title but keep the duplicate paragraphs.;Add a third copy of the same paragraph.|Revision should add relevant development rather than duplicate content.'''
for r in a.splitlines():mc('practice',*r.split('|'))
# Twelve distinct briefs per purpose. Every product includes words and a purposeful learner-made visual.
p='''A lost mitten's journey|Write an imaginative story for a younger class about a mitten that wants to return to its owner. Paragraph one introduces the loss; paragraph two shows an attempted solution and outcome. Add a small route drawing.|Edit one movement verb and check that your route matches the written journey.|Possible plan: playground→bench→classroom. Draft could show the mitten riding on a trolley, then being found. Change went to rolled where appropriate; the route marks those actual places.|Require a coherent loss/solution, matching route and precise verb edit; the object may speak in this fiction.
The door under the desk|Write a story opening and ending about finding a tiny door under a classroom desk. Use paragraph one for discovery and paragraph two for what happens next. Draw and label one important door detail.|Edit a clue so it connects with the later event.|A silver keyhole can be planted as a clue; later a paper key might open the door. Label that keyhole and revise a vague opening detail to connect the ending.|Require connected discovery/outcome, a relevant labelled detail and clue revision, not a particular fantasy rule.
A dragon at the bakery|Create a gentle story where a dragon helps solve a bakery problem. Put the problem in one paragraph and the help in another. Add a drawing with a caption showing the solution.|Edit one line of dialogue so the speaker is clear.|A dragon might hold a heavy oven door while the baker carries a tray. The caption explains the help; an added said the baker tag clarifies a request.|Require a coherent fictional problem/help sequence, caption and clear-speaker edit.
The windy performance|Write a story about an outdoor puppet show interrupted by wind. Use one paragraph for the interruption and one for the characters' response. Draw a before-and-after pair of pictures.|Edit a time connection so the order is easy to follow.|The wind lifts the backdrop; the performers move behind a sheltered wall. Before/after drawings match those events; adding afterwards clarifies the move.|Require problem, response, matched two-panel visual and sequence edit.
The shy new robot|Write about a robot joining a game for the first time. Show feelings through words or actions in paragraph one, then a change in paragraph two. Draw a scene and give it a fitting caption.|Edit one sentence that only labels a feeling by adding a supporting action.|The robot might wait at the edge and ask softly, then join when invited. Replace It was happy with a specific wave or spoken response; caption the joining scene.|Require a supported feeling change, a specific action edit and relevant caption; no universal emotion gesture required.
A bottle full of stars|Write a fantasy about finding a bottle of tiny stars. Explain the discovery and then a choice about what to do with them. Add a labelled drawing of the bottle.|Edit one description so the reader can picture a feature that matters later.|A loose cork might matter when stars escape; revise nice bottle to a bottle with a wobbling cork and label it.|Require discovery, consequential choice, meaningful description and matching labels.
The wrong parcel|Create a story about two parcels getting mixed up. Use one paragraph for the mistake and one for a fair solution. Draw both parcel labels.|Edit the names or pronouns so readers can follow who receives each parcel.|Jo's ribbon box goes to Ren; Ren's puzzle goes to Jo. They exchange them. Clear labels and replacing an unclear it with the parcel name support the solution.|Require understandable mix-up/resolution, distinct labels and reference-clarity edit.
The talking pond|Write a story where a pond asks visitors for help with one problem. Explain the request in one paragraph and the response in another. Add a picture with a speech bubble.|Edit the pond's request to say exactly what help is needed.|The pond might ask visitors to collect a dropped bag from the path with an adult's help. The bubble states the request; revise Help! to a specific action.|Require an imaginative speaker, specific problem/response and matching speech bubble; safe alternatives welcomed.
A night in the toy cupboard|Tell a story of two toys working together after the classroom closes. Give each a useful role. Add a drawing showing the two roles.|Edit one repeated noun using a pronoun only where the meaning remains clear.|A crane lifts a fallen block while a toy truck carries it away. The drawing shows both jobs; replace the crane with it where no other singular object could confuse the reference.|Require cooperative sequence, distinct roles and a justified clear-reference edit.
The missing final page|Write a story about a character finding a book whose last page is missing. Show the problem and a creative response. Draw the character's invented final-page illustration.|Edit the ending so it connects with something established in paragraph one.|The character might create an ending using a key mentioned earlier. Revise a disconnected ending to use that clue; the visual shows the invented resolution.|Require setup/response connection and a final-page visual consistent with the new ending.
A surprise inside the shell|Create a story where a shell contains an unexpected sound. Show discovery and its effect on a character. Add a picture and words that imitate the sound.|Edit a general sound word into a more specific one.|A tiny ding-ding might lead the character to imagine a bell garden. Replace noise with ding-ding and connect the picture to the imagined setting.|Require a coherent discovery/effect, sound-language revision and purposeful sound/image combination.
The little bridge builder|Write a story about a small creature finding a way across a gap. Give the obstacle and solution separate paragraphs. Draw the finished crossing with labels.|Edit one setting detail so the solution fits the size and place described.|A beetle may place a twig across a narrow crack. Change a wide river to a narrow crack if that makes the twig solution coherent; label twig and crossing.|Require obstacle/solution consistency, labelled visual and a setting revision that improves plausibility within fiction.
Borrowing a class game|Write an informative guide for new pupils. Use these facts: write your name on the loan sheet; borrow one game; return all pieces on Friday. Put borrowing and returning in separate paragraphs. Draw a simple return checklist.|Edit one sentence so the Friday deadline is unambiguous.|A plan groups name/one game under borrowing and pieces/Friday under returning. A checklist lists game and pieces; revise return later to return on Friday.|Require all supplied facts, two clear groups, checklist and deadline edit; do not invent fines.
Our seed tray display|Write an informative display using these project notes: seeds planted Monday; watered when the soil felt dry; first shoots seen Friday. Separate what was done from what was observed. Draw a labelled before-and-after diagram.|Edit any sentence that presents the project's result as a rule for every seed.|The account says our seeds first sprouted on Friday, not all seeds sprout in four days. Labels identify soil/seeds and shoots; revise the universal statement if drafted.|Require all project facts, action/observation distinction and bounded wording; if no overclaim was drafted, refine a sentence to make the project scope explicit.
Finding classroom materials|Write a guide for a new pupil. Facts: scissors in the red tray, glue in the blue tray, paper on the lower shelf. Group tools and paper into two paragraphs. Draw a labelled shelf or tray plan.|Edit one location phrase to make it more precise.|The guide names each supplied location. A labelled drawing helps find them; revise over there to on the lower shelf.|Require accurate supplied locations, useful grouping, matching plan and location edit; colour labels also written for clarity.
Making a paper bookmark|Write instructions from these steps: cut a card strip with adult help if needed; decorate it; write your name; place it between pages. Use one paragraph for making and one for using. Draw the finished bookmark and label the name area.|Edit a time word or instruction so the sequence cannot be mistaken.|First cut, then decorate/name; the second paragraph explains use. Replace before cutting with after cutting if needed, or add then to clarify a step.|Require all stages in coherent order, clear use, label and sequencing revision.
Our weather observation|Write an informative report from these notes: Monday was cloudy at lunchtime; Tuesday was sunny at lunchtime; both observations were made from the same window. Use a paragraph for observations and one for the comparison. Draw two labelled weather panels.|Edit a sentence to keep it about the observed times, not the whole days.|The report says cloudy at lunchtime on Monday and sunny at lunchtime Tuesday; revise Monday was cloudy all day to the observed lunchtime claim.|Require accurate limited data, comparison, day labels and scope edit.
Welcoming library visitors|Write an information card. Facts: the reading room is upstairs; the lift is beside reception; staff at reception can help. Explain the room in one paragraph and how to get help/access it in another. Draw a simple labelled direction diagram.|Edit a vague reference such as there into a named place.|A card names upstairs and reception, with the lift beside reception. Replacing ask there with ask staff at reception improves clarity.|Require supplied access/help information, accurate labels and location-reference edit; no invented stairs requirement.
How our puppet works|Invent a simple paper puppet and explain it to a partner. State its parts in paragraph one and how to move it in paragraph two. Draw and label those parts.|Edit one topic word so it names the part precisely.|A paper puppet may have a card body and stick handle. Change thing to handle and show the same labelled handle in the drawing.|Require coherent invented design, parts/use relationship, specific vocabulary and matching labels.
A class survey report|Use these results: 8 pupils chose drawing club, 6 chose chess and 4 chose gardening. Write one paragraph reporting results and another comparing them. Draw a labelled display of the three counts.|Edit a comparison to match the numbers exactly.|Drawing has the most choices and gardening the fewest; a labelled bar or dot display shows 8,6,4. Correct any claim that chess has the most, or refine more to two more than chess.|Require all three counts, correct comparison, matching display and meaningful numerical wording edit.
A model town guide|Invent a tiny model town with a park, library and bridge. Write a paragraph introducing the places and another explaining one route. Draw a map matching that route.|Edit a direction so a partner can follow it on your map.|A route may go from library past park to bridge. Revise go that way to follow the path past the park; map and text must agree.|Require three places, a followable route, matching map and direction edit; invented town facts are allowed.
Looking after shared paints|Write an informative reminder from these rules: close lids after use; rinse brushes in the water pot; put dry brushes bristles-up. Group paint care and brush care in separate paragraphs. Draw one labelled care action.|Edit a pronoun that could refer to the wrong item.|Replace put them upright with put dry brushes bristles-up if needed; the drawing shows brushes, not paint pots, in that position.|Require all rules, grouped care, matching action visual and clear-reference revision.
The class collection|Invent a collection of ordinary safe objects, such as buttons or postcards. Describe two useful groups in two paragraphs. Draw and label one example from each group.|Edit a broad word into a precise feature word.|Buttons could be grouped by two holes/four holes; replace different buttons with two-hole buttons. The two drawings show the grouping rule.|Require consistent grouping, two labelled examples and feature-vocabulary edit; no hidden factual expertise required.
An event information sheet|Use these details: class display on Friday at 2 pm in the hall; families may look at models and ask pupils questions. Write a paragraph for when/where and another for what visitors can do. Add a clear information box.|Edit the layout so the date, time and place are easy to find.|The final sheet presents Friday, 2 pm and hall in a box, with paragraphs explaining the display. Move buried details into the box while keeping the body consistent.|Require all supplied details, readable box and a purposeful layout edit; do not invent booking or cost.
Labels for the toy boxes|Write a persuasive note asking the class to label toy boxes. In paragraph one give your opinion and reason; in paragraph two give a specific example and request. Draw a sample label.|Edit a merely related sentence so it supports your stated reason.|If the reason is finding toys quickly, an example is a Blocks label showing where to return blocks. Replace toys are colourful with that relevant example.|Require opinion, supporting reason/example, request, useful label and relevance edit.
Choose a quiet reading spot|Persuade a partner to try one reading spot you know or invent. Explain your opinion and reason, then a specific example and invitation. Draw a plan highlighting the useful feature.|Edit a claim such as everyone likes it into a fairer statement.|I prefer the corner because it is away from the game area; the plan shows that separation. Revise everyone loves it to it may suit readers who want quiet.|Require consistent purpose, relevant spatial visual and qualified preference claim.
A class games afternoon|Write a persuasive proposal for a short class games afternoon. Explain a benefit, then an example of a manageable activity and a polite request. Add a small proposed schedule.|Edit the schedule or text so their times and activities agree.|The proposal might suggest a ten-minute word game followed by a ten-minute puzzle. Align the paragraph and schedule if they disagree.|Require opinion/benefit/example/request and a matching feasible fictional schedule, not guaranteed approval.
Use both sides of scrap paper|Persuade classmates to use the blank sides of suitable scrap paper for drafts. Explain why, then show an example and a request. Draw a before-and-after paper example.|Edit an overstatement such as all paper is reusable into a suitable limited claim.|Blank backs of non-private practice sheets can be used for drafts. Revise all paper to paper with a clean blank side; drawing shows writing on one side and blank space on the other.|Require relevant resource-use reason, example, request and bounded wording; no universal environmental calculation.
A visitor question box|Propose a question box for the class display. Explain how it could help visitors, then give an example question and request. Draw a labelled box and note.|Edit a general benefit into a specific one.|Visitors who do not want to interrupt can leave a question; a sample note asks how a model was built. Replace it is good with that practical benefit.|Require opinion, specific benefit/example, request and visual that supports the proposed use.
Choose a class story|Recommend an invented or familiar suitable story for shared reading. Explain one reason, then give a specific example from the story and invite others to try it. Draw a small recommendation card.|Edit the example so it actually supports your reason.|If the reason is a surprising ending, describe the relevant surprise without claiming everyone will enjoy it. The card names the story and reason.|Require genuine alignment between reason and story example; adult may confirm familiar-story details or accept clearly invented story.
Protect the model display|Write a polite persuasive sign asking visitors to look without touching fragile models. Explain the reason in one paragraph and an example/alternative in another. Add a helpful symbol and caption.|Edit a harsh command into wording suited to welcoming visitors.|Please look closely without touching; ask a pupil for a closer explanation. A hand-stop symbol with words supports the request; replace Don't you dare with please.|Require understandable request, fragility reason, appropriate alternative, captioned symbol and tone edit.
A shared puzzle shelf|Propose a shelf for unfinished puzzles. Explain the problem it would solve, then a specific example and request. Draw a labelled shelf layout.|Edit the example so it shows the stated benefit.|A half-finished puzzle could stay flat between sessions rather than being packed away. Show a labelled space and revise an unrelated comment about puzzle colours.|Require problem/benefit/example/request, relevant layout and supporting-detail edit.
Welcome a new club member|Write a persuasive invitation to an invented school club. Explain what a newcomer can enjoy, then give a specific activity example and invitation. Add a small activity illustration with a caption.|Edit any promise that guarantees every person will enjoy it.|A drawing club invitation describes trying a pattern postcard. Change you will love everything to you can try an activity and see what you enjoy.|Require honest invitation, relevant example, caption and fair promise wording.
Vote for a garden sign|Recommend one of two designs you invent for a class garden sign. Explain a useful design feature, then give an example of how it helps. Draw both options and mark your choice.|Edit the reason so it explains usefulness rather than only saying best.|Large plant labels help visitors identify beds from the path; two drawings show label sizes. Replace it is best with the readability reason.|Require two visible designs, one justified choice, useful example and specific reason edit; aesthetic preferences valid if explained.
Keep a clear walkway|Write a persuasive reminder to keep bags off a classroom walkway. Explain the reason, then suggest a specific alternative place agreed with an adult. Draw a simple layout showing the clear path.|Edit a direction so the alternative location is clear.|A class could agree on a bag shelf; the diagram labels the shelf and open route. Replace put them away with put bags on the agreed shelf.|Require reason, specific agreed or explicitly proposed alternative, matching layout and direction edit.
Try a partner revision check|Persuade a classmate to exchange drafts for one helpful comment. Explain a benefit, then give an example of useful feedback and a polite request. Draw a small feedback card.|Edit a vague example into an actionable comment.|Instead of make it better, the feedback card might say Add where the event happens. The note explains how a reader can notice missing detail.|Require a relevant benefit, specific constructive example, request and card matching the advice.'''
for r in p.splitlines():create('practice',*r.split('|'))
b='''Draft: Last night the stars sparkle above our tent. We heard an owl.|Which revision keeps the account in past tense?|Last night the stars sparkled above our tent.|Last night the stars will sparkle above our tent.;Tomorrow the stars sparkle above our tent.;Last night the stars sparkling above our tent.|Sparkled matches last night and heard.
Opinion: Our class should have a repair box for torn book covers. Reason: A repair box would keep useful materials together.|Which example directly supports the reason?|Tape and spare card could be kept in the same labelled box.|Books can have exciting plots.;Some covers are green.;The classroom has windows.|The example shows the proposed grouping of repair materials.
A guide tells readers to meet at the east gate, but its map arrow points to the west gate.|What should the writer do before sharing?|Check the intended gate and make the map and words agree.|Keep the mismatch because pictures do not matter.;Remove every place name but keep the wrong arrow.;Add an unrelated photograph.|Multimodal instructions must give a consistent destination.
Draft: We stoped beside the creek.|Which edit fixes the spelling?|We stopped beside the creek.|We stoppped beside the creek.;We stopid beside the creek.;We stopd beside the creek.|Stop doubles its final consonant before ed in stopped.'''
for r in b.splitlines():mc('test',*r.split('|'))
t='''The umbrella that floated away|Create a story about an umbrella drifting to an unexpected place. Give the departure and arrival separate paragraphs. Draw its route with two labelled landmarks.|Edit one transition so the journey order is clear.|The umbrella might lift from a bench and land beside a greenhouse; a later or finally connection clarifies the arrival and matches the route.|Require coherent departure/arrival, two matching landmarks and a useful transition edit.
A tiny visitor in the music room|Write a story where a tiny visitor changes a rehearsal. Explain the arrival and then the response. Add a picture with a speech bubble that matters to the event.|Edit a speaker reference so readers know who says the bubble's words.|A mouse might ask for a quieter drumbeat; the musician responds. Naming the mouse clarifies the request, and the image shows the exchange.|Require connected events, meaningful speech bubble and clear speaker edit.
The forgotten promise|Write a story about a character remembering a promise just in time. Introduce the promise and later action in separate paragraphs. Draw a reminder object with a caption.|Edit a detail so the reminder connects clearly to the promise.|A ribbon tied to a basket might remind a character to return borrowed tools; revise an unrelated object into that meaningful reminder.|Require a stated promise, connected reminder/action, caption and detail revision.
The garden after dark|Create a fantasy about something ordinary in a garden changing after dark. Explain the change and its consequence in two paragraphs. Draw a before-and-after pair.|Edit a description so both paragraphs use the same transformed object consistently.|A watering can might become a tiny fountain; revise a later accidental teapot reference to watering can, with matching two-panel art.|Require consistent transformation/consequence, matched visuals and a meaningful consistency edit.
A class museum label|Invent a class-made model and write an informative label page. Explain what the model shows in one paragraph and how it was made in another. Draw and label two important parts.|Edit a vague material or part word into a precise one.|A model bridge may use cardboard supports and a paper deck; replace stuff with cardboard and label the supports and deck.|Require model purpose/making distinction, two accurate parts and precise vocabulary edit; no outside factual claims required.
A borrowed sports kit guide|Use these facts: collect the kit from the office; count four cones and two balls; return it to the office after the session. Write collection and return paragraphs. Add a checklist.|Edit the checklist and prose so the quantities match.|Both text and checklist show four cones/two balls and the office return. Correct any mismatch or revise a vague equipment reference into those counts.|Require all facts, accurate checklist, clear grouping and quantity-clarity edit.
Our shade observations|Use these notes: the bench was in shade at nine; at twelve it was in sun; both observations were on Wednesday. Report the observations, then compare them. Draw two labelled panels.|Edit a claim that goes beyond the two observations.|The report states only the two Wednesday times; revise the bench is always sunny to it was sunny at twelve on Wednesday.|Require both observations, correct comparison, time labels and scope edit; if draft already bounded, improve a time-specific sentence.
A map for a model island|Invent an island with a landing place, shelter and lookout. Write an introduction and a route paragraph. Draw a labelled map matching the route.|Edit one direction after checking it against your map.|A route might go from landing to shelter then lookout; change an incorrect left/right or unclear place reference to match the actual drawing.|Require all places, coherent route, labelled map and map-text direction edit.
A place for finished artwork|Write a persuasive proposal for one agreed display space. Explain a benefit, then an example of how work could be arranged and a polite request. Draw the proposed layout.|Edit a vague benefit into a reader-focused reason.|A labelled row could help visitors find each artist's work. Replace it looks good with that specific benefit and show labels in the layout.|Require opinion, reason/example/request, useful layout and specific benefit edit.
Try a story exchange|Invite classmates to exchange short original stories. Explain a benefit, then give an example of a helpful response and an invitation. Draw a response card.|Edit a comment that judges the writer into a useful comment about the text.|Replace you are bad at endings with Add what happens after the door opens. The card offers text-focused advice and the invitation explains learning from readers.|Require purpose, supportive specific example, invitation, card and constructive-feedback edit.
A clearer lunchtime notice|Propose improving an invented lunchtime notice. Explain the problem with the first version and why your version helps. Draw both versions with words and visual features.|Edit one layout feature so key information is easier to find.|A revised notice puts the place under a clear heading and keeps the illustration beside the words. Explain how this helps readers find where to go.|Require visible before/after notices, specific benefit, two-paragraph explanation and purposeful layout revision.
Save a place for quiet games|Write a persuasive suggestion for a quiet-game space alongside active play. Give a reason, then a specific activity example and request. Draw a plan showing both spaces.|Edit an unfair claim about other people's preferences into a fairer statement.|Some pupils may enjoy a word puzzle while others prefer active games. Replace nobody likes running with some people want a quiet option; map shows both areas.|Require relevant reason/example/request, both spaces and fairer preference wording.'''
for r in t.splitlines():create('test',*r.split('|'))
assert len(items)==64,len(items)
assert sum(x['bank']=='practice' for x in items)==48
Path(__file__).with_name('ac9e3ly06.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
print('LY06: 64 applied editing and complete writing-process tasks.')
