"""Original LY02 conversations; no cycling of a small prompt bank."""
import json
from pathlib import Path
items=[]
code='AC9E3LY02'
def base(bank,q):
 n=sum(x['bank']==bank for x in items)+1
 return dict(id=f'{code}-{bank[0].upper()}-{n:03d}',subject='english',year_level='Year 3',curriculum_code=code,bank=bank,skill='Contributing to conversations and discussions',question=q,audio_prompt=q,visual={'type':'none'})
def mc(bank,context,ask,answer,wrong,reason):
 x=base(bank,context+'\n\n'+ask);n=sum(i['bank']==bank and i.get('grading_mode')!='adult-review' for i in items);p=n%4;opts=wrong[:];opts.insert(p,answer)
 x.update(answers=[{'text':t,'is_correct':j==p} for j,t in enumerate(opts)],correct_index=p,explanation={'summary':reason,'hint':'Link the reply to what the other speaker actually said.'});items.append(x)
def task(bank,context,ask,model,note):
 q=context+'\n\n'+ask+' Work with a partner or adult: listen to their reply and take another turn that connects with it.'
 x=base(bank,q);x.update(grading_mode='adult-review',answers=[],correct_index=None,model_answer=model,acceptance_note=note+' Observe the spoken exchange. Written planning alone does not show listening or turn-taking; do not require eye contact or a particular accent.',response_instructions='Ask someone to read the other speaker’s part, or discuss the supplied situation together. Speak, listen, then respond. Type a brief record or tick the box after the exchange. An adult checks the interaction.',completion_label='We completed the conversation; an adult still needs to check it.',explanation={'summary':model,'hint':'Listen for one idea you can respond to before taking your next turn.'});items.append(x)
mc('practice','Mina says, “The reading corner is too dark for me to see small print.”','Which reply contributes a relevant idea?','Could we move a lamp nearer the books?',['I like books with dragons.','Our classroom has twenty chairs.','You should talk about something else.'],'The lamp idea responds to Mina’s stated problem with seeing print.')
mc('practice','Taj says, “Put the finished models over there.” He does not point.','What would clarify the instruction?','Which table should the models go on?',['Are the models finished?','Why do you like models?','Can I tell you about my lunch?'],'The destination is missing; asking which table resolves that uncertainty.')
mc('practice','Two children begin speaking at the same time during a small-group discussion.','Which response helps both ideas be heard?','You go first; I’ll share my idea after yours.',['I’ll speak louder until you stop.','Neither of us should say anything today.','Your idea cannot be useful.'],'Offering an order allows each speaker a turn without dismissing either idea.')
mc('practice','Nico says, “I prefer the longer path because it has shade.”','Which reply disagrees while giving a relevant reason?','I prefer the shorter path because we only have ten minutes.',['That is a silly preference.','I also like shade.','The path has a name.'],'The reply offers a different choice and explains the time constraint without insulting Nico.')
mc('practice','Sana says, “I can bring the paper, but I cannot bring glue.”','Which response shows that the listener noticed both parts?','Thanks for the paper. I can bring the glue.',['Thanks for bringing the glue.','So we do not have any paper.','You said you can bring everything.'],'The reply keeps Sana’s offer and limitation accurate and fills the remaining need.')
mc('practice','The group is choosing a class pet name. Ali has not spoken yet.','Which invitation leaves Ali free to contribute or pass?','Ali, would you like to suggest a name?',['Ali must choose our name right now.','Ali agrees with me because he is quiet.','We know Ali has no ideas.'],'An invitation makes room for participation without treating silence as agreement.')
mc('practice','“I think the seedlings need more water,” says Rosa. “The soil feels dry.”','Which question asks Rosa to add useful information?','When did we last water them?',['What colour is your schoolbag?','Do you want to change your name?','Why are you talking?'],'The watering history is relevant to deciding whether the dry seedlings need water.')
mc('practice','Ben is explaining a game. You did not hear how a player earns a point.','Which response helps you take part correctly?','Could you repeat how we earn a point?',['I will guess and start playing.','Your game has no rules.','I did not hear anything you said, so stop.'],'The request identifies the specific information that needs repeating.')
mc('practice','“We could share the jobs,” says Ava. “I’ll collect the leaves.”','Which reply builds on Ava’s suggestion?','I’ll label the bags so we can keep the leaves sorted.',['Leaves grow on many trees.','I will change the topic to sport.','Nobody should have a job.'],'The reply adds a complementary job to the shared collection plan.')
mc('practice','A classmate says, “My model fell apart on the way to school.”','Which opening acknowledges the experience before offering help?','That sounds frustrating. Would you like help rebuilding it?',['My model is much better than yours.','Models can be made from cardboard.','You must not care about your model.'],'The reply acknowledges the problem without inventing blame, then offers help.')
mc('practice','Lee says, “We should meet after lunch.” You need to know where.','Which question asks only for the missing detail?','Where shall we meet after lunch?',['Should we meet before lunch instead?','Why do people eat lunch?','What did you have for lunch yesterday?'],'The question retains the agreed time and asks for the missing place.')
mc('practice','“The green team has four votes and the blue team has three,” says Pat.','Which reply shares the information accurately?','Green has one more vote than blue.',['Blue has more votes than green.','Every person voted for green.','The teams have equal votes.'],'Four is one more than three; the reply keeps the reported comparison accurate.')
practice='''The group wants a quiet indoor game for a rainy lunch.|Suggest a suitable game and explain how it can stay quiet.|We could play a picture-matching game and speak softly when we take turns.|Accept a workable indoor idea, a reason linked to quiet and a response to the partner’s suggestion.
A partner says the classroom book basket is hard to search because everything is mixed.|Offer one sorting idea, then find out whether the partner thinks it would help.|We could put stories and information books in different sections. Would that help you find a book?|Look for a relevant sorting idea and a genuine opportunity for the partner to respond.
Your partner suggests a class picnic on Friday. The supplied calendar says a school assembly is on Friday.|Share that information politely and discuss another time.|Friday has an assembly. Could we look at Thursday instead?|Require the Friday conflict to be reported accurately; another workable time can be suggested without claiming it is booked.
A classmate says, “I lost my place while reading the instructions.”|Offer a way to resume and ask which step they last completed.|Which step did you finish? We can find the next one together.|Listen to the completed step before proposing the next action; do not assume the whole task needs restarting.
Two friends want the same paintbrush for different parts of a poster.|Help them discuss a fair way to share it.|Could one person finish the outline while the other colours with a different brush, then swap?|Accept a practical turn-taking arrangement that considers both users; the partner may suggest another fair plan.
A partner describes finding a small feather near the oval.|Ask a question that helps them share more about what they observed.|What did it look like, and where near the oval did you find it?|Accept one focused observation question followed by a related response; do not claim to identify the bird without evidence.
Your group has paper and string but no tape for a hanging decoration.|Share the limitation and suggest a way to connect the pieces.|We have no tape. Could we make holes and tie the pieces with string?|Look for use of the supplied materials and consideration of the partner’s alternative.
A partner prefers a mystery story; you prefer a funny story.|Explain your preference without deciding that their preference is wrong.|I enjoy funny stories because they make me laugh. What do you enjoy about mysteries?|Accept either real preference with a reason and respectful interest in the partner’s different view.
The group agrees to put heavy books at the bottom of a display. You have an idea for the top.|Add your idea in a way that connects to the agreement.|With the heavy books below, we could put the light signs on top.|Require connection to the existing plan; accept different sensible top-display ideas.
A partner says, “I think the bus leaves at nine, but I am not sure.”|Respond without turning their uncertain guess into a fact.|Let’s check the timetable before we tell everyone it leaves at nine.|Look for preserving uncertainty and suggesting a way to confirm the information.
You are explaining a drawing to a partner who cannot see it clearly.|Describe its main parts, then ask what needs explaining further.|My drawing has a house beside a large tree, with a path between them. Which part should I describe more?|The learner can draw or imagine an original picture; assess clear description and adjustment after the listener’s question.
A classmate says a new student may not know where the library is.|Offer a welcoming action and invite another idea.|I could walk with them to the library. Is there another place we should show them?|Accept a relevant welcoming action and a response that builds on the partner’s contribution.
You and a partner have different ideas for the final line of a shared poem.|Take turns reading the lines and discuss how each ending sounds.|Let’s hear your ending first, then mine. I like how yours repeats the rain sound.|Ask the pair to invent short endings; assess hearing both and referring to an actual feature rather than voting before listening.
A partner says, “The box is too heavy for me to carry alone.”|Respond to the problem and agree on a safe next step.|Let’s ask an adult to help us move it.|Accept seeking appropriate help or leaving the heavy box in place; do not require lifting it during the task.
Your group must choose two activities from drawing, skipping and reading.|Explain your choice, then respond to a different choice from your partner.|I would choose drawing and reading for an indoor session. Which two would you choose?|Accept any two with a reason; assess willingness to hear and respond to another combination.
A speaker pauses to think during a group discussion.|Practise leaving them time, then ask a gentle question if they want help.|Take your time. Would it help to tell us what happened first?|Observe allowing time rather than taking over; the partner can say they do not need help.
A partner proposes putting all collected leaves in one bag. Your task is to compare leaves from two places.|Explain why keeping the groups separate could help.|If we use two labelled bags, we can tell which leaves came from each place.|Require a reason linked to the two-place comparison, and a turn that responds to the partner’s reaction.
Your partner has just described how they made a paper boat.|Tell them one step you understood and ask about a step you need explained.|I understood folding the paper in half. Could you show me how you made the pointed end?|The partner supplies a real or simple invented sequence; assess accurate reference to it, not memorisation of this model.
The group plans to leave finished paintings on a table, but that table is needed for lunch.|Explain the conflict and discuss another drying place.|We need that table for lunch. Could we use the spare shelf for the paintings?|Accept a relevant alternative and consideration of space; do not assert that an unmentioned shelf is certainly available.
A friend describes feeling nervous before speaking to the class.|Ask what support they would find useful instead of assuming.|Would you like to practise with me, or would another kind of help be better?|Observe listening to the person’s choice and responding respectfully; no demand to disclose a real upsetting experience.
Your group is discussing how to reduce paper waste.|Contribute one action and explain how it uses less paper.|We could draw on both sides of a sheet when the back is blank.|Accept a specific usable action and a linked reason, followed by a response to the partner’s idea.
A partner says that every book in the library is a story. You can see a book about how bridges are built.|Use that example to add information politely.|Some books give information. This bridge book explains how bridges are built.|Require the information-book example and respectful correction rather than a personal criticism.
You hear two suggested meeting places: the classroom door and the oval gate.|Help the pair settle on one clear meeting place.|Which place shall we both use? Let’s say the agreed place again before we go.|The role-play should finish with one mutually understood place; either location can be chosen.
A partner asks for feedback on a sign that says only “Tomorrow!”.|Explain what extra information a reader would need.|The sign needs to say what happens tomorrow and where it will happen.|Accept relevant missing information; assess giving useful feedback instead of simply calling the sign bad.
Your group is choosing a way to thank the school gardener.|Offer an idea and respond when a partner suggests a different one.|We could write a shared card. Your drawing idea could go on its cover.|Accept combining ideas or politely choosing with reasons; do not require agreement if the learner explains their view.
A partner says, “I want to use the big one,” while pointing at several boxes.|Ask a clear question before choosing a box for them.|Do you mean the tall box or the wide box?|Require clarification of the ambiguous object; the partner must answer and the learner confirm the choice.
You have just heard a partner suggest adding labels to a model.|Acknowledge the idea and add a useful detail.|Labels would help. We could draw a line from each label to the correct part.|Accept a contribution that extends the labelling idea; repeating it alone is not the whole task.
Your group has five minutes left to finish a poster.|Share the time limit and discuss which unfinished part matters most.|We have five minutes. Shall we finish the title first so people know what the poster is about?|Accept a reasoned priority; assess negotiation after the partner identifies another unfinished part.
A partner is telling a story about an imaginary trip and you want to share a similar idea.|Wait for a suitable pause, then connect your contribution to theirs.|Your story about the train reminds me of an idea for a journey through a mountain.|Observe an appropriate turn and a clear connection; the learner may invent an experience rather than claim a real trip.
The group disagrees about whether to practise the song once or twice.|Help compare the reasons before making a plan.|Why do you prefer one practice? I think two might help with the ending we missed.|The partner should provide a reason; assess considering it rather than automatically accepting or dismissing it.
A classmate uses a word you do not understand while explaining a game.|Ask for its meaning, then use the explanation to continue the discussion.|What does “swap” mean in this game? So we exchange our cards after that turn?|Use an actual unfamiliar or role-played word; look for clarification and a related follow-up showing understanding.
Your group needs someone to introduce a display and someone to answer questions.|Discuss how to divide the roles while considering each person’s preference.|Would you rather introduce it or answer questions? I could introduce it if you prefer questions.|Accept a mutually understood allocation; do not assign a role by assuming silence means consent.
A partner reports that the first seed sprouted yesterday and another sprouted today.|Share what this tells the group without adding unobserved facts.|Two seeds have sprouted on different days. We can keep watching the others.|Require accuracy about the two observations; do not claim all seeds will sprout tomorrow.
Your class is discussing what makes a useful book recommendation.|Recommend a real or invented book using a reason another reader could use.|This funny animal story has short chapters, so it could suit someone who wants a quick read.|Assess a stated feature and reader-related reason, plus listening to the partner’s question; invented titles are allowed.
A partner suggests starting a group presentation with a question.|Try a possible opening question and ask whether it suits the topic you choose together.|For our plant display, we could ask, “What does a seed need to grow?” Does that fit our topic?|Let the pair choose the topic; assess relevance and revision after feedback, not agreement with the model topic.
At the end of a discussion, your group has agreed on a title and two jobs.|State the agreement and ask the partner to check it.|We agreed on “Our Garden”. You will draw the plants and I will write the labels. Have I got that right?|The pair supplies its own agreement; require an accurate closing check of the title and roles.'''
for line in practice.splitlines():task('practice',*line.split('|'))
mc('test','“We have enough cups, but we still need water,” says Jo.','Which reply responds to the remaining need?','I can fill the jug with water.',['I will bring more cups instead.','So we do not have any cups.','You said everything was ready.'],'The reply addresses water while retaining the information that cups are already available.')
mc('test','Your partner says, “The new route is shorter, but the steps may be difficult for our trolley.”','Which question helps the group consider that concern?','Is there a ramp on that route?',['What colour is the trolley?','Why do routes have names?','Can we stop talking about the steps?'],'A ramp is relevant to moving the trolley past a change in level.')
mc('test','A group is discussing a poster title. You want to suggest a different title.','Which response shares your idea respectfully?','Could we try “Save Our Shade”? It tells readers why the trees matter.',['My title wins because I said so.','Your title is ridiculous.','We must stop hearing everyone else’s ideas.'],'The suggestion gives a relevant reason and leaves room for discussion.')
mc('test','“The practice starts at two, not three,” says the organiser.','Which reply checks the correction accurately?','So we should arrive for a two o’clock start?',['So the start is still three o’clock?','So practice has been cancelled?','So there are two different practices?'],'The reply repeats the corrected time as a check without inventing extra events.')
tests='''Your partner suggests carrying lunch outside. The supplied notice says rain is expected at lunchtime.|Share the notice’s information and discuss a workable lunch plan.|The notice says rain is expected at lunch. Should we plan an indoor place?|Keep expected rain as a forecast, not a certainty; assess a relevant plan and response.
A group has collected ten pictures but can display only six.|Discuss a fair way to select pictures and respond to the partner’s suggestion.|We could choose pictures that show six different parts of the project.|Accept a reasoned selection method and consideration of the other idea; no need to select actual pictures.
A partner says, “I did not understand why the character went back.”|Ask which part they mean and discuss an explanation using a short story you tell each other.|Which return do you mean? In our story, she returned because she had left her map behind.|The pair supplies the story detail; assess clarification and an explanation grounded in that detail.
Two people want to introduce a class performance.|Discuss a way both can contribute without speaking over each other.|One could welcome the audience, then the other could name the performance.|Accept shared or negotiated roles with a clear speaking order; observe listening to preferences.
Your partner suggests making every sign tiny to save paper.|Explain one possible reading difficulty and consider a compromise.|Tiny writing may be hard to read from a distance. Could we use short messages in larger letters?|Require the visibility concern and a relevant adjustment; accept another workable compromise.
A friend says the class activity was “not what I expected”.|Ask an open question that helps them explain, then respond to what they tell you.|What was different from what you expected? I see—you thought we would work outdoors.|The follow-up must fit the partner’s actual answer; do not assume the activity was disliked.
Your group is planning how to welcome families to a classroom display.|Suggest information visitors will need and ask your partner to add something.|We should tell them where to start. What else will help them find their way?|Assess a useful visitor need, invitation and connected response; avoid judging accent or eye contact.
A partner proposes using a shared object while another group is already using it.|Discuss how to ask about a later turn.|We could ask when they will finish and arrange our turn after that.|Accept courteous negotiation and a practical alternative while waiting; do not require taking the object.
You and your partner have different endings for an invented animal story.|Explain one strength of your ending and listen for a strength in theirs.|My ending solves the lost-key problem. Yours gives the animals another adventure.|Both endings must be supplied in the role-play; assess specific reference to each, not declaring a winner.
The group planned three jobs, but one member is away.|Help revise the plan without assuming the absent person can do the work.|Let’s list the jobs we still need. Could we each take one extra small part?|Accept a feasible revised allocation or asking for help, with reference to the actual remaining jobs.
A partner gives two reasons for choosing a shady place to read.|Respond to one reason and ask about the other if it is unclear.|I agree the shade could make the page easier to see. Could you explain your other reason?|Require the response to match reasons the partner actually supplied; assess selective listening and clarification.
Your group has finished discussing a short activity but has not checked everyone understands the plan.|Give a short summary, then invite a correction or question.|We will make the labels first and place them after lunch. Is anything different from what you understood?|The pair agrees its own plan first; assess an accurate summary and a real chance to correct it.'''
for line in tests.splitlines():task('test',*line.split('|'))
assert len(items)==64,len(items)
assert sum(i['bank']=='practice' for i in items)==48
Path(__file__).with_name('ac9e3ly02.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
print('LY02: 64 original tasks, including 48 observed interactions and 16 selected-response checks.')
