"""LY07: original supported presentation tasks, with observed delivery."""
import json
from pathlib import Path
items=[]
def base(b,q):
 n=sum(x['bank']==b for x in items)+1
 return dict(id=f'AC9E3LY07-{b[0].upper()}-{n:03d}',subject='english',year_level='Year 3',curriculum_code='AC9E3LY07',bank=b,skill='Plan, rehearse and deliver presentations',question=q,audio_prompt=q,visual={'type':'none'})
def mc(b,text,ask,c,w,why):
 x=base(b,text+'\n\n'+ask);p=sum(y['bank']==b and y.get('grading_mode')!='adult-review' for y in items)%4;opts=w[:];opts.insert(p,c)
 x.update(answers=[{'text':v,'is_correct':i==p} for i,v in enumerate(opts)],correct_index=p,explanation={'summary':why,'hint':'Use the stated purpose, audience and details.'});items.append(x)
def talk(b,purpose,brief,visual,voice,model,note):
 q=f'{purpose} presentation. {brief}\n\nPlan a clear opening, a developed middle and a closing. Create your short talk in your own words. {visual} Rehearse aloud, make one useful improvement, then deliver the talk with your visual to an adult listener. {voice}'
 x=base(b,q);x.update(grading_mode='adult-review',answers=[],correct_index=None,model_answer=model,acceptance_note=note+' The adult must hear the delivered talk and see the visual, not only read a script or completion statement. Check the plan, a rehearsal improvement, clear structure, relevant elaboration and precise words. Voice should suit the purpose and listening space; do not require an accent, eye contact, fixed pitch pattern or words-per-minute target. Accept other successful presentations.',response_instructions='Use paper for a plan and simple visual. Rehearse, improve and present to an adult. You may record your plan or the listener’s observations here.',completion_label='I have delivered my talk with a visual; an adult still needs to check it.',explanation={'summary':model,'hint':'Make your key idea easy to follow, add a useful detail and use the visual when it helps.'});items.append(x)
mc('practice','Talk notes: explain a board game; introduce the goal; describe the turns; show how the game ends.','Which order will help a new player follow the explanation?','Goal, turns, ending.',['Ending, unrelated joke, goal.','Turns with no explanation of the goal.','Repeat the title and leave out the rules.'],'The sequence gives the listener a purpose before the process.')
mc('practice','Opinion: Our class should label the storage boxes. Detail: New students cannot easily find the glue and rulers.','Which sentence develops the reason?','Labels would show newcomers where the supplies belong.',['The boxes are in our classroom.','Some rulers are longer than others.','I saw a blue box yesterday.'],'The sentence explains how labels address the stated difficulty.')
mc('practice','Story plan: Mira finds a wet map, dries it, then uses it to find a lost toy.','Which detail would best explain why she dries it?','The wet paper has stuck together and hides part of the route.',['Mira likes three different fruits.','The toy has never been lost.','A map is made of paper.'],'The detail connects the problem to Mira’s next action.')
mc('practice','An informative talk compares a bridge before and after a repair. The speaker has both pictures.','How can the visual best support the comparison?','Show them together and point out the changed part while explaining it.',['Hide both until everyone has left.','Show an unrelated beach picture.','Point to a picture without explaining what changed.'],'The audience can connect spoken details to the visible difference.')
mc('practice','Rehearsal feedback: “I missed the three steps because they came very quickly.”','Which change directly addresses the feedback?','Slow at each step and pause briefly before the next one.',['Say the title more loudly but rush the steps.','Remove the middle of the explanation.','Speak every word at exactly the same speed.'],'Grouping and pacing the steps make the sequence easier to follow.')
mc('practice','A speaker is explaining a model boat. The notes say: “This thing keeps that bit upright.”','Which wording is more precise?','The mast holds the sail upright.',['The stuff holds the thing.','This part does something there.','The object is an object.'],'Mast and sail identify the relevant parts.')
mc('practice','A story has a quiet secret followed by a sudden discovery.','Which voice choice can help make the contrast clear?','Use a softer secretive tone, then a more surprised tone that remains comfortable to hear.',['Shout the whole story as loudly as possible.','Make both parts impossible to hear.','Use the same stressed word in every sentence.'],'Tone and pitch can express meaning; maximum volume is unnecessary.')
mc('practice','A talk gives two reasons for choosing a reading corner. It ends: “And my shoe is green.”','Which closing fits the purpose?','Those are my reasons for choosing that reading corner.',['Now forget the reasons I gave.','My shoe is still green.','There is no reason to choose anywhere.'],'The closing returns to the supported opinion.')
mc('practice','A speaker rehearses with a labelled drawing. The labels cannot be read from the listener’s chair.','What is a useful improvement?','Make the labels larger and check them from the listener’s position.',['Add more tiny labels until the page is full.','Turn the drawing away from the listener.','Speak faster so the labels do not matter.'],'The change addresses the observed visual-access problem.')
mc('practice','Notes for a talk about a made-up park: two paths; pond beside the wide path; picnic area at the end.','Which opening states the topic clearly?','I will show you how the paths in my park lead to its main places.',['Yesterday was Tuesday.','The end is the beginning.','Here are several things, whatever they are.'],'It prepares listeners for the planned park explanation.')
mc('practice','The speaker’s voice is clear to a partner at the same table. The next talk is to three listeners farther away in a quiet room.','What should the speaker check?','Whether all three can hear comfortably, and adjust volume if needed.',['Whether the voice is always as loud as possible.','Whether every sentence uses a new accent.','Whether the listeners can read the speaker’s private notes.'],'Audibility depends on the space and listeners.')
mc('practice','A learner has written a complete script but has not tried saying it aloud.','Which next step provides rehearsal evidence?','Say the talk aloud with the visual, notice a difficulty and improve it.',['Write “rehearsed” at the top without speaking.','Choose a title colour and call it delivered.','Ask someone to read the script silently instead.'],'Rehearsal involves trying the presentation, not merely labelling a script.')
P='''Informative|Explain your invented seed library using these notes: borrow a seed packet; grow a plant; return new seeds later. Explain what the borrow and return stages mean.|Draw three labelled stages.|Pause between the stages.|A clear talk introduces the seed library, explains the cycle using packet and seeds, and closes with how it continues.|Check the full cycle, rather than only a list of gardening words.
Informative|Explain a paper maze you design. Include its entrance, one decision point and its exit.|Draw a simple maze and point to the route while speaking.|Keep the directions slow enough to follow.|The speaker identifies the entrance, describes a turn at the decision point and explains where the exit lies.|Check matching map and directions; the route must actually lead to the shown exit.
Informative|Explain how your class could organise a lost-property table: clothing on one side, containers on the other, and a sign asking owners to collect items.|Sketch the table layout with labels.|Use an audible, helpful tone.|The talk introduces the table, explains both groups and the collection sign, and summarises where to look.|Check precise placement words and a reason for grouping.
Informative|Present a pretend survey: six learners chose drawing, four chose puzzles and two chose building. Describe the results without claiming the survey represents everyone.|Make a simple labelled bar drawing or tally chart.|Pause after each number.|The talk states that twelve learners answered and describes drawing as the largest group in this sample.|Check accurate supplied numbers and an explanation of what the visual shows.
Informative|Explain a toy vehicle you invent. Name three parts and explain the job of each.|Draw and label the three parts.|Emphasise the part names without shouting.|An example explains wheels for moving, a tray for carrying and a handle for pulling.|Check functions match the learner’s actual design; alternative designs are welcome.
Informative|Teach a partner a two-step paper-folding action you already know. Explain how the paper should face before the first fold.|Make a before-and-after sketch.|Leave time for the listener to imagine each action.|The speaker introduces the starting position, explains both folds precisely and shows the result.|Check sequence and clear words such as edge, corner and fold; no particular model is compulsory.
Informative|Explain a made-up classroom book exchange. Notes: bring one book; choose a different book; record the title on a shared list.|Draw a three-part process card.|Use a steady explanatory pace.|The talk explains what to bring, how to exchange and why the title is recorded.|Check all supplied steps with a useful detail about one step.
Informative|Describe a pretend weather chart: Monday dry, Tuesday rainy, Wednesday rainy. Explain what stayed the same and what changed.|Draw the three-day chart with a key.|Stress the day names clearly.|The speaker contrasts Monday with the next two days and explains the symbols used.|Check observations from the supplied chart, not invented forecasts.
Informative|Explain a storage invention for three art tools. Choose where a brush, pencil and ruler will go and why.|Draw labelled compartments.|Use precise tool names and pause when changing compartments.|The speaker names the tools and links each compartment to its use or size.|Check the layout and reasons agree.
Informative|Guide a visitor around an imaginary mini museum with a model boat, an old key and a rock display. Decide an order and describe one interesting made-up display detail.|Make a floor plan with three labels.|Use a welcoming tone that is easy to hear.|The talk introduces the museum, follows a route and adds a detail for a display before closing.|Check the invented detail is presented as part of this imaginary museum, not a researched historical fact.
Informative|Explain how two designs for a bookmark differ: one has a ribbon and one has a folded corner. Include how each marks a page.|Draw both designs side by side.|Pause when moving from one design to the other.|The speaker identifies the shared purpose and clearly explains the different features.|Check a real comparison, rather than describing only one design.
Informative|Explain a team’s pretend clean-up plan: collect paper first, put reusable pieces in a tray, then put other paper in the labelled bin.|Draw a flow diagram with arrows.|Use clear sequence words at a measured pace.|The presentation explains the order and distinguishes reusable pieces from the other paper.|Check the words and arrows show the same sequence.
Opinion|Recommend a name for a class reading group. Give two reasons linked to the group’s purpose.|Design a name sign with one supporting symbol.|Use an enthusiastic but comfortable tone.|A learner might recommend Page Explorers because members discover stories and share discoveries.|Check two distinct reasons; the chosen name need not match the example.
Opinion|Choose between a wall display and a table display for paper models. Explain your preference using visibility and available space.|Sketch your preferred arrangement.|Pause after your opinion so the audience can identify it.|The talk states a preference and develops reasons about seeing the models and fitting them in the room.|Check reasons support the chosen arrangement, not merely mention displays.
Opinion|Recommend one game for a rainy lunchtime. Explain how it would include a newcomer and use the available table space.|Draw its setup.|Use a friendly, inviting tone.|A learner may recommend a simple matching game, explain a turn and show seats around it.|Check inclusion and space are addressed through relevant details.
Opinion|Suggest whether a pretend school garden sign should use words only or words with a drawing. Explain your choice for younger visitors.|Create your proposed sign.|Keep key reasons clear with short pauses.|The learner connects the sign’s features with the intended visitors’ understanding.|Accept either choice when reasons and the actual sign fit the stated audience.
Opinion|Recommend a class mascot you invent. Explain how two features represent what the class values.|Draw and label the mascot.|Use pitch to highlight the main feature naturally.|The speaker connects features such as a helping hand and a book with helpfulness and learning.|Check two explained connections, not only a description of appearance.
Opinion|Choose a place for a quiet reading area on an invented classroom map. Give a reason about noise and a reason about access.|Draw the map and mark the area.|Use a calm, clear tone suited to the proposal.|The learner identifies the location and explains why it is quiet yet reachable.|Check that the map provides enough detail to support both reasons.
Opinion|Recommend an ending for a class story: finding the lost hat or discovering it became a bird’s nest. Explain which fits a funny story better and why.|Draw your ending.|Use an expressive but understandable voice.|The speaker chooses an ending and develops a reason about humour with a specific event.|Accept either ending if the explanation makes its humour plausible.
Opinion|Choose an activity to welcome a new class member: a partner tour or a question circle. Give two reasons about helping that person settle in.|Make a small plan card.|Use a reassuring tone.|The talk explains the chosen activity and why its details could help someone new.|Check reasons centre on the newcomer, not only the speaker’s enjoyment.
Opinion|Recommend whether a pretend puzzle club should meet at one large table or several small tables. Explain how people would share materials and talk.|Sketch the arrangement.|Pause between your reasons.|The speaker links the table choice to collaboration and access to pieces.|Accept either layout with coherent reasons.
Opinion|Choose a cover for a class recipe collection. Explain how the title and picture would help someone recognise its purpose.|Design the cover.|Make the title clear without rushing it.|The speaker shows the cover and explains the connection between its features and recipes.|Check the actual cover supports the claims.
Opinion|Recommend an order for a classroom talent show with a poem, a magic trick and a group song. Give two reasons for your order.|Draw an order card.|Use a lively tone and clear transitions.|The speaker gives an order and explains how its opening and closing would work for the audience.|No single order is correct; check supporting reasons and all three acts.
Opinion|Suggest one improvement to a pretend playground notice that says only “Games here”. Explain what a visitor still needs to know.|Create an improved notice.|Slow down when explaining the new information.|The learner might add a starting time and location detail and explain why these help visitors.|Require a concrete improvement and its benefit.
Story|Tell a story about a tiny robot that mistakes a lunchbox for a house. Include how it discovers the mistake and what it does next.|Draw three story moments.|Vary tone between the mistake and the discovery.|A coherent story uses an opening, clue, discovery and outcome, with details that make the mistake understandable.|Check the discovery follows a clue, rather than an unrelated ending.
Story|Tell a story in which a lost button becomes useful during a journey. Establish who carries it and how it helps.|Draw the button at the beginning and at the useful moment.|Pause before revealing its use.|The button is introduced early and later solves a specific problem.|Check setup and payoff are connected.
Story|Tell a story set in a library after the books begin whispering. Explain what one character wants and how the whispering affects that goal.|Draw the key setting detail.|Use a softer storytelling tone that remains audible.|The talk makes the setting matter to a clear goal and resolution.|Check a complete event sequence and understandable delivery, not merely spooky noises.
Story|Tell a story about two friends building a shelter for a toy before pretend rain arrives. Give them different useful ideas.|Draw the shelter and its two important features.|Change tone to distinguish the friends without imitating accents.|The story shows each idea contributing to the finished shelter.|Check both characters affect the outcome.
Story|Tell a story beginning with an empty envelope and ending with a thank-you message. Explain how the envelope becomes important.|Draw the envelope in two stages.|Use a brief pause at the turning point.|The talk connects the opening object with a specific helpful event and the closing message.|Require a clear causal link, not just two unrelated mentions.
Story|Tell a story about a boat made from a leaf in an imaginary world. Include an obstacle that suits its small size.|Draw the boat beside the obstacle.|Adjust pace to make the obstacle clear.|The story uses small scale consistently and gives a plausible imaginary solution.|Check the visual helps listeners understand the scale.
Story|Tell a story in which a character follows a trail of blue footprints. Decide who made them and provide a clue before the reveal.|Draw the trail and clue.|Pause before revealing the maker.|The trail leads through a sequence and the earlier clue supports the ending.|Check the reveal uses supplied story evidence.
Story|Tell a story about a shy dragon preparing a surprise for a friend. Show the feeling through an action as well as words.|Draw the surprise.|Use tone to show the change from worry to the ending feeling.|The speaker develops a goal, an emotional action and a connected outcome.|Accept different endings; assess coherence and expressive clarity.
Story|Tell a story where a windy day changes a picnic plan. Include a choice that solves the new problem.|Draw the original and changed plan.|Slow briefly at the decision.|The wind causes an obstacle and the character’s choice responds to it.|Check the setting causes a meaningful event.
Story|Tell a story about a message delivered to the wrong imaginary animal. Explain the misunderstanding and how it is repaired.|Draw the message’s route.|Make each change of speaker clear.|The listener can follow the mistaken recipient and the action that puts it right.|Check the repair addresses the actual misunderstanding.
Story|Tell a story about a quiet bell that rings only when someone tells the truth. Include one clear test of the bell.|Draw the bell and test.|Vary pitch naturally to mark surprise.|The story establishes the rule, tests it and gives an outcome consistent with it.|Check the fantasy rule stays consistent.
Story|Tell a story in which a character returns to a familiar place and notices one surprising change. Explain the cause of that change.|Draw before and after scenes.|Use a pause between the familiar detail and surprise.|The opening establishes the place and the later explanation accounts for the change.|Check the ending explains the chosen surprise.
'''
for line in P.strip().splitlines():talk('practice',*line.split('|'))
mc('test','Opinion talk: “Our model bridge should have a wider base.” Reason: the narrow base tipped during a test.','Which detail best develops the reason?','A wider base could help the model stand more steadily.',['The model has a name written on it.','We used the table yesterday.','The bridge looks like a bridge.'],'The detail links the proposed change to the observed problem.')
mc('test','A story speaker says the ending before explaining who lost the parcel. The listener is confused.','Which rehearsal change best addresses the problem?','Introduce the character and missing parcel before the search and ending.',['Speak the confusing order more loudly.','Remove every character from the story.','Show an unrelated picture instead of explaining.'],'A clear sequence gives the listener needed context.')
mc('test','An informative talk points to three parts of a drawing, but the speaker repeatedly says “this thing”.','What would improve precision?','Name each part while pointing to its matching label.',['Point faster without naming anything.','Use a new vague word for every part.','Hide the drawing for the whole talk.'],'Matching specific names and labels connects spoken and visual information.')
mc('test','Rehearsal: a listener hears the opening clearly, but the speaker becomes inaudible while facing the visual.','What should the speaker practise?','Keeping the explanation audible while showing the visual.',['Removing all the useful details.','Shouting every word at maximum volume.','Delivering only a silent drawing.'],'The problem is audibility during visual use, not lack of a picture.')
T='''Informative|Explain a pretend reading challenge: choose three books, record one idea from each, then share a favourite idea. Add a helpful detail for a new participant.|Create a three-step card.|Pause at the step changes.|The delivered talk explains the full process and develops one step clearly.|Check the added detail supports the stated process.
Informative|Describe an invented pet-care robot using a wheel, a water tray and a sensor. Explain what each part does in your design.|Draw labelled parts.|Use the part names clearly and at a comfortable pace.|The speaker explains functions and uses the drawing to support them.|Check this is presented as an invention, not a claim about real animal-care advice.
Informative|Present pretend collection results: seven smooth stones, five rough stones and three striped stones. Explain the groups and compare their sizes.|Make a labelled chart.|Pause between groups and the comparison.|The talk accurately compares the supplied counts and explains its labels.|Check the numbers and largest/smallest comparisons.
Informative|Explain a miniature town you design with a station, park and library. Describe a route linking all three.|Draw and label the route.|Use clear location words and a followable pace.|The talk introduces the town and follows the route shown on the map.|Check the spoken order agrees with the drawing.
Opinion|Recommend a title for a class collection of funny stories. Give two reasons about how it prepares a reader.|Design a cover using the title.|Use an inviting tone and emphasise the title.|The speaker links the title and design to the humour of the collection.|Accept any suitable title with two developed reasons.
Opinion|Choose between a shelf and a hanging display for lightweight paper birds. Explain how visitors could see the birds and how the space would be used.|Sketch the display.|Separate your two reasons with a short pause.|The talk makes the choice clear and supports it with visibility and space details.|Check the actual design fits both reasons.
Opinion|Recommend one of two activities for an imaginary club: making puzzles or telling stories. Explain how it would help members work together.|Draw a scene of the activity.|Use a confident, respectful tone.|The speaker supports the preference with a specific example of collaboration.|Accept either option; require reasons rather than unsupported enthusiasm.
Opinion|Propose a clearer sign for a pretend classroom lending box currently labelled “Stuff”. Explain two useful changes.|Make the new sign.|Slow down when identifying each change.|The talk names useful information added and explains how borrowers benefit.|Check two concrete changes and their purposes.
Story|Tell a story about a paper kite that delivers a message to the wrong window. Explain how the right reader eventually gets it.|Draw the route and turning point.|Make the change of direction clear through a pause.|The story links the wrong delivery, a repair action and a resolved ending.|Check causal order and the visual route.
Story|Tell a story in which a character cannot cross a tiny stream until an earlier object becomes useful. Introduce that object naturally.|Draw the crossing solution.|Pause before revealing the solution.|The talk sets up an object that later solves the obstacle.|Check the object is introduced before it is needed.
Story|Tell a story about a shop where every hat changes the weather in a miniature garden. Use one rule consistently from problem to ending.|Draw the important hat and garden.|Use expressive tone without losing clarity.|The speaker establishes and follows the fantasy rule with a connected resolution.|Check consistency, structure and developed details.
Story|Tell a story about two friends who interpret a mysterious sound differently. Let a clue lead them to its real source.|Draw the clue.|Use voice changes to distinguish their ideas.|The talk develops two interpretations and resolves them using the clue.|Check the reveal follows from the story, not an unrelated surprise.
'''
for line in T.strip().splitlines():talk('test',*line.split('|'))
assert len(items)==64
assert sum(x['bank']=='practice' for x in items)==48
Path(__file__).with_name('ac9e3ly07.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
