"use strict";
window.skillrTestQuestions = [
  {
    "id": "ac9e1ly09-er5-t-001",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Three phonemes: /j/ /a/ /m/. The initial sound in jam is treated as one phoneme in the taught segmentation.",
    "acceptanceNote": "Three phonemes: /j/ /a/ /m/. The initial sound in jam is treated as one phoneme in the taught segmentation.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'jam'. Ask the child to say every sound separately.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'jam'. Ask the child to say every sound separately.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 1,
    "correct": "Three phonemes: /j/ /a/ /m/. The initial sound in jam is treated as one phoneme in the taught segmentation.",
    "explanation": "Three phonemes: /j/ /a/ /m/. The initial sound in jam is treated as one phoneme in the taught segmentation.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Three phonemes: /j/ /a/ /m/. The initial sound in jam is treated as one phoneme in the taught segmentation.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-002",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Three phonemes: /w/ /e/ /b/. All sounds should be included in order without substituting letter names.",
    "acceptanceNote": "Three phonemes: /w/ /e/ /b/. All sounds should be included in order without substituting letter names.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'web'. Ask for the separate sounds in order, using one counter each.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'web'. Ask for the separate sounds in order, using one counter each.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 2,
    "correct": "Three phonemes: /w/ /e/ /b/. All sounds should be included in order without substituting letter names.",
    "explanation": "Three phonemes: /w/ /e/ /b/. All sounds should be included in order without substituting letter names.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Three phonemes: /w/ /e/ /b/. All sounds should be included in order without substituting letter names.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-003",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Three phonemes: /ch/ /i/ /n/. Ch is one speech sound in chin, despite being written with two letters.",
    "acceptanceNote": "Three phonemes: /ch/ /i/ /n/. Ch is one speech sound in chin, despite being written with two letters.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'chin'. Ask the child to segment the word and count its sounds.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'chin'. Ask the child to segment the word and count its sounds.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 3,
    "correct": "Three phonemes: /ch/ /i/ /n/. Ch is one speech sound in chin, despite being written with two letters.",
    "explanation": "Three phonemes: /ch/ /i/ /n/. Ch is one speech sound in chin, despite being written with two letters.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Three phonemes: /ch/ /i/ /n/. Ch is one speech sound in chin, despite being written with two letters.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-004",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Three phonemes: /th/ /i/ /n/. Use the unvoiced th heard in thin as one sound, not a t sound followed by h.",
    "acceptanceNote": "Three phonemes: /th/ /i/ /n/. Use the unvoiced th heard in thin as one sound, not a t sound followed by h.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'thin'. Ask the child to say the separate sounds.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'thin'. Ask the child to say the separate sounds.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 4,
    "correct": "Three phonemes: /th/ /i/ /n/. Use the unvoiced th heard in thin as one sound, not a t sound followed by h.",
    "explanation": "Three phonemes: /th/ /i/ /n/. Use the unvoiced th heard in thin as one sound, not a t sound followed by h.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Three phonemes: /th/ /i/ /n/. Use the unvoiced th heard in thin as one sound, not a t sound followed by h.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-005",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /s/ /t/ /e/ /p/. Both initial consonants need their own sound and counter.",
    "acceptanceNote": "Four phonemes: /s/ /t/ /e/ /p/. Both initial consonants need their own sound and counter.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'step'. Ask the child to segment the whole word, keeping the initial sounds separate.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'step'. Ask the child to segment the whole word, keeping the initial sounds separate.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 5,
    "correct": "Four phonemes: /s/ /t/ /e/ /p/. Both initial consonants need their own sound and counter.",
    "explanation": "Four phonemes: /s/ /t/ /e/ /p/. Both initial consonants need their own sound and counter.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /s/ /t/ /e/ /p/. Both initial consonants need their own sound and counter.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-006",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /p/ /l/ /u/ /g/. Check that the beginning /l/ remains present when the word is segmented.",
    "acceptanceNote": "Four phonemes: /p/ /l/ /u/ /g/. Check that the beginning /l/ remains present when the word is segmented.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'plug'. Ask for all the sounds in order.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'plug'. Ask for all the sounds in order.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 6,
    "correct": "Four phonemes: /p/ /l/ /u/ /g/. Check that the beginning /l/ remains present when the word is segmented.",
    "explanation": "Four phonemes: /p/ /l/ /u/ /g/. Check that the beginning /l/ remains present when the word is segmented.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /p/ /l/ /u/ /g/. Check that the beginning /l/ remains present when the word is segmented.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-007",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /b/ /e/ /l/ /t/. Both /l/ and /t/ should be heard at the end.",
    "acceptanceNote": "Four phonemes: /b/ /e/ /l/ /t/. Both /l/ and /t/ should be heard at the end.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'belt'. Ask the child to separate the sounds, including the ending.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'belt'. Ask the child to separate the sounds, including the ending.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 7,
    "correct": "Four phonemes: /b/ /e/ /l/ /t/. Both /l/ and /t/ should be heard at the end.",
    "explanation": "Four phonemes: /b/ /e/ /l/ /t/. Both /l/ and /t/ should be heard at the end.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /b/ /e/ /l/ /t/. Both /l/ and /t/ should be heard at the end.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-008",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /l/ /a/ /m/ /p/. The final /p/ counts separately from /m/.",
    "acceptanceNote": "Four phonemes: /l/ /a/ /m/ /p/. The final /p/ counts separately from /m/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'lamp'. Ask the child to move a counter for each spoken sound.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'lamp'. Ask the child to move a counter for each spoken sound.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 8,
    "correct": "Four phonemes: /l/ /a/ /m/ /p/. The final /p/ counts separately from /m/.",
    "explanation": "Four phonemes: /l/ /a/ /m/ /p/. The final /p/ counts separately from /m/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /l/ /a/ /m/ /p/. The final /p/ counts separately from /m/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-009",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /k/ /l/ /a/ /p/. The beginning cluster has two sounds rather than one combined count.",
    "acceptanceNote": "Four phonemes: /k/ /l/ /a/ /p/. The beginning cluster has two sounds rather than one combined count.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'clap'. Ask the child to say every sound slowly.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'clap'. Ask the child to say every sound slowly.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 9,
    "correct": "Four phonemes: /k/ /l/ /a/ /p/. The beginning cluster has two sounds rather than one combined count.",
    "explanation": "Four phonemes: /k/ /l/ /a/ /p/. The beginning cluster has two sounds rather than one combined count.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /k/ /l/ /a/ /p/. The beginning cluster has two sounds rather than one combined count.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-010",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /d/ /e/ /s/ /k/. The last two sounds are /s/ /k/ in that order.",
    "acceptanceNote": "Four phonemes: /d/ /e/ /s/ /k/. The last two sounds are /s/ /k/ in that order.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'desk'. Ask the child to segment the word and repeat just the last two sounds.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'desk'. Ask the child to segment the word and repeat just the last two sounds.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 10,
    "correct": "Four phonemes: /d/ /e/ /s/ /k/. The last two sounds are /s/ /k/ in that order.",
    "explanation": "Four phonemes: /d/ /e/ /s/ /k/. The last two sounds are /s/ /k/ in that order.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /d/ /e/ /s/ /k/. The last two sounds are /s/ /k/ in that order.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-011",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Top: /t/ /o/ /p/ (3). Stomp: /s/ /t/ /o/ /m/ /p/ (5). Check both full sequences, including /s/ and /m/ in stomp.",
    "acceptanceNote": "Top: /t/ /o/ /p/ (3). Stomp: /s/ /t/ /o/ /m/ /p/ (5). Check both full sequences, including /s/ and /m/ in stomp.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'top' and then 'stomp'. Ask the child to segment both words with counters.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'top' and then 'stomp'. Ask the child to segment both words with counters.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 11,
    "correct": "Top: /t/ /o/ /p/ (3). Stomp: /s/ /t/ /o/ /m/ /p/ (5). Check both full sequences, including /s/ and /m/ in stomp.",
    "explanation": "Top: /t/ /o/ /p/ (3). Stomp: /s/ /t/ /o/ /m/ /p/ (5). Check both full sequences, including /s/ and /m/ in stomp.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Top: /t/ /o/ /p/ (3). Stomp: /s/ /t/ /o/ /m/ /p/ (5). Check both full sequences, including /s/ and /m/ in stomp.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-012",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /g/ /l/ /a/ /d/. The missing sound is /l/ after the initial /g/.",
    "acceptanceNote": "Four phonemes: /g/ /l/ /a/ /d/. The missing sound is /l/ after the initial /g/.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'glad'. A puppet says only /g/ /a/ /d/. Ask the child to say all the sounds and identify what was missed.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'glad'. A puppet says only /g/ /a/ /d/. Ask the child to say all the sounds and identify what was missed.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 12,
    "correct": "Four phonemes: /g/ /l/ /a/ /d/. The missing sound is /l/ after the initial /g/.",
    "explanation": "Four phonemes: /g/ /l/ /a/ /d/. The missing sound is /l/ after the initial /g/.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /g/ /l/ /a/ /d/. The missing sound is /l/ after the initial /g/.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-013",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Five phonemes: /s/ /t/ /r/ /i/ /ng/. Separate the three initial sounds while keeping the final ng as one phoneme.",
    "acceptanceNote": "Five phonemes: /s/ /t/ /r/ /i/ /ng/. Separate the three initial sounds while keeping the final ng as one phoneme.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'string'. Ask the child to say all the sounds and count them.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'string'. Ask the child to say all the sounds and count them.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 13,
    "correct": "Five phonemes: /s/ /t/ /r/ /i/ /ng/. Separate the three initial sounds while keeping the final ng as one phoneme.",
    "explanation": "Five phonemes: /s/ /t/ /r/ /i/ /ng/. Separate the three initial sounds while keeping the final ng as one phoneme.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Five phonemes: /s/ /t/ /r/ /i/ /ng/. Separate the three initial sounds while keeping the final ng as one phoneme.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-014",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Five phonemes: /s/ /p/ /e/ /n/ /t/. Check both initial and final cluster sounds are represented.",
    "acceptanceNote": "Five phonemes: /s/ /p/ /e/ /n/ /t/. Check both initial and final cluster sounds are represented.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'spent'. Ask the child to segment it, checking the sounds at both ends.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'spent'. Ask the child to segment it, checking the sounds at both ends.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 14,
    "correct": "Five phonemes: /s/ /p/ /e/ /n/ /t/. Check both initial and final cluster sounds are represented.",
    "explanation": "Five phonemes: /s/ /p/ /e/ /n/ /t/. Check both initial and final cluster sounds are represented.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Five phonemes: /s/ /p/ /e/ /n/ /t/. Check both initial and final cluster sounds are represented.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-015",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Wing: /w/ /i/ /ng/ (3). Wind, as in blowing air: /w/ /i/ /n/ /d/ (4). Say wind with its short vowel to avoid the other pronunciation.",
    "acceptanceNote": "Wing: /w/ /i/ /ng/ (3). Wind, as in blowing air: /w/ /i/ /n/ /d/ (4). Say wind with its short vowel to avoid the other pronunciation.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'wing' and 'wind'. Ask the child to segment each and compare the number of sounds.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'wing' and 'wind'. Ask the child to segment each and compare the number of sounds.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 15,
    "correct": "Wing: /w/ /i/ /ng/ (3). Wind, as in blowing air: /w/ /i/ /n/ /d/ (4). Say wind with its short vowel to avoid the other pronunciation.",
    "explanation": "Wing: /w/ /i/ /ng/ (3). Wind, as in blowing air: /w/ /i/ /n/ /d/ (4). Say wind with its short vowel to avoid the other pronunciation.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Wing: /w/ /i/ /ng/ (3). Wind, as in blowing air: /w/ /i/ /n/ /d/ (4). Say wind with its short vowel to avoid the other pronunciation.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9e1ly09-er5-t-016",
    "curriculumCode": "AC9E1LY09",
    "bank": "test",
    "skill": "segmenting spoken phonemes including clusters",
    "printable": true,
    "type": "self-check",
    "gradingMode": "adult-review",
    "responseType": "short_answer",
    "modelAnswer": "Four phonemes: /s/ /m/ /e/ /l/. The final /l/ is one sound even though the written word has two l letters; do not show the spelling first.",
    "acceptanceNote": "Four phonemes: /s/ /m/ /e/ /l/. The final /l/ is one sound even though the written word has two l letters; do not show the spelling first.",
    "responseInstructions": "Complete the spoken task with a grown-up, who will check the response. Do not use letter names in place of speech sounds.",
    "completionLabel": "I have completed the task with a grown-up.",
    "question": "Grown-up: keep the screen out of the child's view. Say 'smell'. Ask for every sound, then ask whether its ending needs one counter or two.",
    "audioPrompt": "Grown-up: keep the screen out of the child's view. Say 'smell'. Ask for every sound, then ask whether its ending needs one counter or two.",
    "visual": "",
    "visualHtml": "",
    "visualMeta": {
      "type": "none",
      "alt_text": ""
    },
    "answers": [],
    "difficulty": 3,
    "difficultyTier": "independent",
    "sequencePriority": 16,
    "correct": "Four phonemes: /s/ /m/ /e/ /l/. The final /l/ is one sound even though the written word has two l letters; do not show the spelling first.",
    "explanation": "Four phonemes: /s/ /m/ /e/ /l/. The final /l/ is one sound even though the written word has two l letters; do not show the spelling first.\nHint: Complete the task before comparing your response with the guidance.",
    "structuredExplanation": {
      "summary": "Four phonemes: /s/ /m/ /e/ /l/. The final /l/ is one sound even though the written word has two l letters; do not show the spelling first.",
      "hint": "Complete the task before comparing your response with the guidance."
    },
    "qualitySchema": "production-v1"
  }
];
window.skillrExamQuestions = window.skillrTestQuestions;
window.quizQuestions = window.skillrTestQuestions;
