"use strict";
const Q=[
["calibration reasoning","A sensor gives tightly clustered readings that are all 4 units above a certified reference. Which change most directly improves accuracy?",["Recalibrate or correct the sensor using appropriate reference standards","Take 100 more readings without changing the setup","Report more decimal places","Average the readings twice"],0,"The dominant problem is systematic bias; repeats do not remove a consistent offset.","Fix systematic bias at its source."],
["calibration range","A balance is accurate near 10 g but increasingly biased near 200 g. What does this show?",["A single zero check may be insufficient; calibration should cover the relevant measurement range","The balance is perfectly calibrated because it reads zero correctly","Random error always increases with mass","The sample size is too small"],0,"Instrument response can vary across its range, so calibration checks should reflect the values used in the investigation.","Check standards across the working range."],
["resolution vs accuracy","Sensor A displays 4.237 V; Sensor B displays 4.24 V and has recently been verified against a standard. Which statement is justified?",["Sensor A has finer displayed resolution, but Sensor B may still be more accurate","Sensor A must be more accurate because it shows more digits","Sensor B must be less precise in every experiment","Neither sensor can be calibrated"],0,"Displayed resolution and measurement accuracy are different properties.","More digits ≠ more accurate."],
["instrument selection","A force sensor has a range of 0–10 N, but expected forces are 8–25 N. What is the best decision?",["Select a sensor whose calibrated range includes the expected forces","Use the 0–10 N sensor and treat values above 10 N as exact","Record all values above 10 N as 10 N","Increase the number of repeats instead"],0,"Measurements outside an instrument's usable range can saturate or be invalid; the equipment must suit the expected values.","Range matters as much as resolution."],
["precision analysis","Two groups measure the same reference length. Group A: 50.1, 50.2, 50.1 mm. Group B: 49.2, 50.9, 50.0 mm. The reference is 50.0 mm. Which comparison is best?",["Group A is more precise; both groups require analysis of accuracy using their central estimates and uncertainty","Group B is more precise because one value equals 50.0","Both groups have identical precision","Precision cannot be assessed from repeated data"],0,"Group A has much smaller spread. Accuracy should not be judged from one convenient reading alone.","Compare spread separately from closeness to reference."],
["human error","A student repeatedly starts a stopwatch late by roughly the same amount. Why might simply increasing trials fail to solve the problem?",["The delay may create a systematic bias that persists across repeats","Repeats always make timing worse","Human reaction time cannot affect timing","The mean removes every type of error"],0,"If the reaction delay is consistently directional, averaging more trials can retain the bias.","Repeats do not guarantee removal of bias."],
["sample bias","A school estimates average student reaction time using 200 volunteers from the athletics squad. What is the main concern?",["The sample may be large but unrepresentative of the whole school","Two hundred observations are always too few","Digital timers cannot be used with athletes","A mean cannot be calculated from reaction times"],0,"Sample size and representativeness are separate; a large biased sample can still give a biased estimate.","Large ≠ representative."],
["sample size","Which change most directly reduces uncertainty in an estimate of a population mean, assuming sampling remains representative?",["Increase the number of independent observations","Add more decimal places to each recorded value","Use the same participant repeatedly and call each reading a new person","Delete values far from the current mean"],0,"More independent representative observations generally reduce random sampling uncertainty.","Independent and representative matter."],
["outlier decision","An outlier is traced to a confirmed data-entry error: 7.2 was typed as 72. What is the best action?",["Correct the transcription using the original record and document the correction","Keep 72 because data can never be corrected","Delete the entire experiment","Replace 72 with the group mean"],0,"A documented transcription error can be corrected from the original source; arbitrary replacement is inappropriate.","Use traceable raw records."],
["digital logging","A temperature logger records every second, producing 3,600 readings in an hour. Why does this not automatically mean the investigation is strong?",["Many readings can still be biased or irrelevant if the sensor is miscalibrated or the design is poor","Large datasets are always invalid","Automatic data cannot be graphed","Continuous measurements cannot be replicated"],0,"Data quantity cannot compensate for systematic bias, poor validity or an unsuitable design.","Big data can still be bad data."],
["data processing","A graphing program automatically fits a straight line to curved data. What should the student do?",["Check whether the model is appropriate rather than accepting the software output automatically","Use the line because software cannot be wrong","Delete points until the line fits","Round all values to whole numbers"],0,"Digital analysis tools execute chosen procedures; students still need to evaluate whether the model suits the data.","Software output needs scientific judgement."],
["replicability","Another group cannot reproduce an experiment because the original report says only 'measure temperature carefully'. Which missing information is most important?",["Instrument type/range, calibration procedure, measurement timing and relevant method details","The colour of the laboratory walls","The researcher's favourite graph type","The conclusion written by the first group"],0,"Operational detail about measurement is needed for meaningful replication.","Specify how measurements were actually made."],
["significant reporting","A sensor's uncertainty is about ±0.5 °C. Which report is least defensible?",["23.47291 °C presented as though every displayed digit were meaningful","23.5 °C with uncertainty information","A mean reported to precision consistent with the measurement uncertainty","Raw readings retained for checking"],0,"Reporting many unsupported digits implies precision the measurement system does not possess.","Match reported digits to justified precision."],
["independent data","A data logger samples the same slowly changing sensor 100 times per second. Are all 100 readings equivalent to 100 independent experimental replicates?",["No; frequent measurements from the same trial can be strongly related and are not necessarily independent replicates","Yes; every stored number is a separate experiment","Yes, provided the file is large enough","No, because digital measurements are never useful"],0,"Sampling frequency and independent replication are different concepts.","Many time points ≠ many independent experiments."],
["measurement system","Which investigation gives the strongest measurement evidence?",["A suitable calibrated sensor, documented resolution/range, repeated or appropriately sampled measurements, raw-data preservation and uncertainty considered in analysis","The sensor with the most decimal places and no calibration check","One carefully chosen reading that matches the prediction","A very large dataset collected with an overloaded sensor"],0,"Measurement quality depends on instrument suitability, calibration, sampling, transparency and analysis together.","Judge the full measurement chain."],
["conclusion strength","Two groups obtain different means but their uncertainty ranges overlap substantially. What is the best initial interpretation?",["The apparent difference may not be well resolved by the measurements, so variability and uncertainty should be considered before claiming a real difference","The group with the larger mean is automatically correct","One group must have fabricated data","Overlapping uncertainty proves the values are identical"],0,"Differences should be interpreted in light of measurement variability and uncertainty rather than means alone.","Compare differences with uncertainty." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s10i03-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I03",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));