"use strict";
const Q=[
["homology evidence","Three vertebrates share the same forelimb bone arrangement, but DNA similarity is also high. Why is using both datasets stronger than using anatomy alone?",["Independent lines of evidence can converge on the same evolutionary explanation","DNA automatically proves every anatomical feature has the same function","Anatomy becomes unnecessary once DNA is available","Two datasets remove all uncertainty"],0,"Converging evidence from different methods strengthens an explanation because agreement is less likely to be due to one source of error or ambiguity.","Independent evidence is stronger than one line alone."],
["fossil inference","A fossil appears in a younger rock layer than expected for its species. Which explanation should be considered before declaring the evolutionary timeline wrong?",["Reworking of older material, dating uncertainty or disturbance of the layer","The fossil must be fake","All surrounding dates should be discarded","Species never overlap in time"],0,"Geological context and dating uncertainty can create apparent anomalies that require investigation.","Check context before rewriting the model."],
["distribution causation","Species abundance decreases as distance from water increases, but vegetation cover also decreases with distance. What is the strongest conclusion?",["The pattern is real, but water availability and vegetation are confounded and further analysis is needed","Distance from water is proven to be the only cause","Vegetation cannot influence abundance","There is no relationship because two variables change"],0,"When predictors co-vary, observational data alone cannot cleanly separate their effects.","Confounding limits causal claims."],
["distribution anomaly","A species is absent from one apparently suitable site but present at all similar nearby sites. Which response is strongest?",["Investigate detection effort, recent disturbance, dispersal barriers and local conditions before treating the absence as meaningful","Delete the site","Assume the species avoids that site for genetic reasons","Conclude the habitat model is completely wrong"],0,"Unexpected absences can reflect sampling, history or unmeasured local factors.","Anomaly → investigate plausible alternatives."],
["time-space data","Fossils of a species occur progressively farther south in younger layers. What does the combined pattern most directly show?",["A shift in the species' geographic distribution through time","That temperature caused the shift","That every individual migrated south","That the species evolved into a new species"],0,"The evidence demonstrates a spatial shift over time; explaining its cause needs additional data.","Describe the pattern before assigning cause."],
["climate evidence","CO₂ rises, global temperature rises, and climate models that include greenhouse forcing match observed warming better than models excluding it. What does the combined evidence support more strongly than correlation alone?",["A causal role for greenhouse forcing in the observed warming","That CO₂ is the only climate influence","That models are exact copies of reality","That every year must be warmer than the previous year"],0,"Mechanistic models plus observations provide stronger causal support than a simple two-variable correlation.","Mechanism + observation strengthens causation."],
["independent records","Surface thermometers, satellites and ocean measurements all indicate warming. Why is agreement important?",["Different measurement systems showing a consistent trend reduce the chance that one instrument type explains the whole pattern","It proves every individual measurement is accurate","It removes natural variability","It means uncertainty no longer needs reporting"],0,"Independent datasets can corroborate a broad trend even though each still has uncertainties.","Convergence across methods matters."],
["climate anomaly","A single exceptionally cool year occurs during a 30-year warming trend. What is the most appropriate interpretation?",["Short-term variability can produce individual departures without erasing the long-term trend","The warming trend is disproven","The cool year must be deleted","Climate trends require every year to move in the same direction"],0,"Long-term trends describe overall direction and can include short-term fluctuations.","Trend and variability can coexist."],
["rate change","CO₂ concentration rises by 10 ppm per decade early in a record and 20 ppm per decade later. What changed?",["The rate of increase became greater","CO₂ began decreasing","The concentration doubled every decade","The trend became constant"],0,"A larger increase per equal time interval means the rate of change has increased.","Compare slopes, not just values."],
["motion slopes","On a speed-time graph, the line becomes progressively steeper. What does that indicate?",["Acceleration is increasing","Speed is constant","Acceleration is zero","Distance is decreasing"],0,"The slope of a speed-time graph represents acceleration, so an increasing slope means increasing acceleration.","Slope of speed-time = acceleration."],
["motion representation","A table shows speeds every 5 s, while a sensor graph shows speed every 0.1 s. The graph reveals a brief speed drop absent from the table. Why?",["The graph uses finer temporal sampling and can reveal short-lived changes missed by sparse tabulation","Graphs alter the underlying motion","Tables are always inaccurate","The speed drop must be an artefact"],0,"Different sampling resolution can make representations reveal different features of the same process.","Representation depends on sampling density."],
["motion anomaly","A speed sensor produces one spike to 100 m/s during otherwise smooth motion. Video evidence shows no corresponding change. What is the best conclusion?",["The spike is likely a measurement artefact and should be investigated and documented","The object definitely reached 100 m/s","The video must be wrong","All sensor data should be discarded"],0,"Conflicting independent evidence can help identify a likely measurement anomaly.","Cross-check anomalies with other evidence."],
["prediction limits","A speed-time trend is linear from 0–5 s. Why might predicting the speed at 60 s by extending the line be risky?",["The relationship may not remain linear far beyond the observed range","Linear graphs can never be used for prediction","Speed cannot be predicted from time","Extrapolation always gives zero"],0,"Extrapolation assumes the observed relationship continues outside the measured range, which may not be valid.","Interpolation is safer than distant extrapolation."],
["representation conflict","A table and graph appear to tell different stories about the same dataset. What should be checked first?",["Whether the graph uses the same data, correct axes, scale and transformation as the table","Which representation looks more convincing","Whether the table should be deleted","Whether the graph has enough colours"],0,"Differences can arise from scaling, transformations or plotting mistakes rather than the data themselves.","Trace both representations back to the same raw data."],
["anomaly explanation","An anomalous data point persists across repeated measurements with different instruments. What becomes more plausible?",["It may reflect a real feature requiring scientific explanation rather than a simple measurement mistake","It should still be deleted automatically","Both instruments must have identical faults","The surrounding trend must be false"],0,"Replication across independent measurements makes a real phenomenon more plausible.","Persistent anomalies can be informative."],
["evidence synthesis","Two datasets support a relationship, one shows no clear pattern, and one has a possible anomaly. What is the strongest conclusion style?",["Describe the overall evidence, explain inconsistencies and state how strongly the combined data support the relationship","Claim unanimous support","Discard the dataset with no pattern","Average all datasets into one number regardless of type"],0,"Scientific synthesis should represent both supporting and conflicting evidence transparently.","Strong conclusions acknowledge mixed evidence." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s10i05-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S10I05",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));