"use strict";
const q=(n,skill,question,answers,correct,explanation,hint)=>({id:`ac9s7i05-t-${String(n).padStart(3,"0")}`,curriculumCode:"AC9S7I05",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers,correct,explanation,structuredExplanation:{summary:explanation,hint},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
q(1,"trend","A stream temperature dataset across six months is 14, 15, 17, 19, 20 and 21°C. What is the best description?",["An overall increasing trend","A decreasing trend","A cyclic pattern","No trend"],0,"The values increase overall through the measured period.","Describe the overall direction, not just one point."),
q(2,"anomaly","Repeated reaction times are 31.2, 31.0, 30.9, 46.5 and 31.1 s. What should happen first?",["Investigate the 46.5 s value for recording, method or instrument issues","Delete 46.5 immediately","Change it to 31.0","Ignore all other values"],0,"Anomalies should be checked before exclusion.","Check first, decide second."),
q(3,"relationship","At constant speed, masses of 5, 10 and 15 kg have kinetic energies of 10, 20 and 30 J. What relationship is suggested?",["Kinetic energy increases directly with mass under these conditions","Kinetic energy decreases as mass increases","No relationship is present","Mass is caused by kinetic energy"],0,"Equal increases in mass correspond to proportional increases in kinetic energy.","Use the controlled comparison."),
q(4,"causation","A city with more trees also has lower summer temperatures. Which conclusion is safest from this observational relationship alone?",["Tree cover is associated with lower temperature, but causation needs further evidence","Trees definitely caused all cooling","Lower temperature caused trees to appear","No relationship exists"],0,"Observational association does not by itself prove causation.","Use association language unless design supports cause."),
q(5,"mean range","Trial results are 8, 9, 10 and 21. Which statement is best?",["The mean is affected strongly by the high value, so spread and the anomaly should be discussed","The mean tells the whole story","21 should always be deleted","Range is zero"],0,"An unusual value can distort the mean, so analysis should include variation and anomaly checks.","Do not rely on the mean alone."),
q(6,"cyclic pattern","A predator population rises shortly after prey numbers rise, then falls after prey numbers fall, and the sequence repeats. What pattern is this?",["A cyclic predator–prey relationship with a lag","A constant trend","No relationship","A single anomaly"],0,"Repeated rises and falls with delay indicate a cycle and linked populations.","Look for repetition plus time lag."),
q(7,"conflicting data","Two monitoring teams report different rainfall trends for the same region. What is the strongest next step?",["Compare time periods, locations, instruments and data quality before judging the conflict","Choose the dataset with more dramatic values","Average them without checking","Assume both are useless"],0,"Conflicting evidence should be investigated for methodological or contextual differences.","Compare methods before conclusions."),
q(8,"prediction","A plant-growth trend is roughly linear across 5–20°C. Which prediction is most defensible?",["A cautious estimate within or near the tested range","A guaranteed value at 100°C","A claim that temperature is the only cause","A prediction with no uncertainty"],0,"Predictions are strongest where they stay close to the observed range.","Prefer bounded interpolation over extreme extrapolation."),
q(9,"group comparison","Treatment A has mean 12 cm, Treatment B 16 cm, but the ranges overlap. What is the best interpretation?",["B is higher on average, but individual values overlap and variation should be acknowledged","Every B plant is taller than every A plant","The means are meaningless","The treatments are identical"],0,"Mean differences can coexist with overlapping individual values.","Use both centre and spread."),
q(10,"anomaly cause","A strange reading occurs exactly when a sensor shows a low-battery warning. What is a reasonable interpretation?",["Instrument malfunction is a plausible explanation that should be checked","The value proves a new scientific law","All other values must be wrong","Battery status cannot affect measurements"],0,"Context can identify plausible causes of anomalous data.","Link the anomaly to evidence about measurement conditions."),
q(11,"evidence statement","Which analysis statement is strongest?",["As salinity increased from 0 to 30 g/L, germination fell from 92% to 41%, showing a negative relationship across the tested range.","The graph went down.","Salt is bad.","Salinity always prevents germination."],0,"Strong analysis names variables, direction, values and the tested range without overgeneralising.","Use quantitative evidence and bounded wording."),
q(12,"raw data","Why should raw repeated measurements be kept after calculating a mean?",["They show spread, anomalies and possible recording issues that the mean can hide","The mean is never useful","Raw data replace all graphs","Only the largest repeat matters"],0,"Raw data preserve information about variation and data quality.","Keep original evidence visible."),
q(13,"no trend","Measurements vary around the same level with no overall rise or fall. What is the best conclusion?",["No clear overall trend is evident, although there is normal variation","The data are perfectly constant","A strong increasing trend exists","Every point is anomalous"],0,"No trend does not require identical values.","Separate overall direction from small variation."),
q(14,"sample size","Why is a trend from 40 observations usually more convincing than the same trend from 3 observations, all else equal?",["The larger sample is less likely to be dominated by unusual values and may better represent normal variation","Larger samples remove systematic error","More observations prove causation","Three observations cannot be graphed"],0,"Larger samples can strengthen confidence by representing variability better.","Sample size helps reliability, not every form of error."),
q(15,"exclusion","When is excluding an outlier most justified?",["When a documented measurement or recording failure explains it and the exclusion is reported transparently","Whenever it weakens the hypothesis","Whenever it is the highest value","Always before averaging"],0,"Outlier exclusion requires an evidence-based reason, not convenience.","Justify exclusions with method evidence."),
q(16,"synthesis","Which sequence best represents sound data analysis?",["Check data quality → describe pattern/trend/relationship → support with values → investigate anomalies → qualify conclusion","Choose conclusion first → remove conflicting data → calculate later","Find one high value → call it a trend","Average everything → assume causation"],0,"Strong analysis moves from checked evidence to a qualified interpretation.","Evidence first, conclusion second.")
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
