"use strict";
const Q=(id,n,s,q,a,c,e)=>({id,curriculumCode:"AC9M10ST05",bank:"test",section:s,sourceNumber:n,skill:s,printable:true,type:"single",question:q,answers:a,correct:c,explanation:e,structuredExplanation:{summary:e,hint:"Judge the evidence, the design, and whether the inference goes beyond what the data support."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q("ac9m10st05-t-001",25,"Confounding","A study finds a strong positive association between training hours and performance. Which is the most important limitation?",["Training may not be the only factor affecting performance","Training hours are numerical","Performance was measured","The graph has two axes"],0,"Other variables such as experience, coaching or fitness may influence performance."),
Q("ac9m10st05-t-002",26,"Confounding","A study finds more screen time is associated with less sleep. Which variable could plausibly confound this relationship?",["Caffeine use","Whether phones exist","Whether people sleep","The colour of the graph"],0,"Caffeine use could be related to both screen habits and sleep duration."),
Q("ac9m10st05-t-003",27,"Causation","Income and number of subscriptions are positively associated. Which conclusion is justified?",["Higher income is associated with more subscriptions in this sample","Income causes subscriptions","Subscriptions cause income","The variables cannot be compared"],0,"Observational association does not establish causation."),
Q("ac9m10st05-t-004",28,"Inference","Reading time and vocabulary score have a strong positive association. Which statement is safest?",["Students who read more tended to have higher vocabulary scores","Reading guarantees a high vocabulary score","Vocabulary definitely causes reading","There is no relationship"],0,"The data support an association, not a guaranteed causal effect."),
Q("ac9m10st05-t-005",29,"Prediction","A line of fit was built from gaming times between 1 and 5 hours. Predicting homework completion at 3.5 hours is:",["Interpolation","Extrapolation","Impossible because 3.5 is not an integer","A causal conclusion"],0,"3.5 lies within the observed range."),
Q("ac9m10st05-t-006",30,"Prediction","The same model is used to predict homework completion at 12 hours of gaming. Why should this be treated cautiously?",["It is extrapolation far beyond the observed range","It uses a numerical variable","The line must pass through every point","Predictions are always exact"],0,"Relationships may not continue outside the observed range."),
Q("ac9m10st05-t-007",31,"Outliers","A scatterplot shows a strong positive trend except for one point far below the others. What should the investigator do first?",["Check whether the point is a recording or genuine unusual observation","Delete it automatically","Move it onto the trend line","Ignore all other data"],0,"Outliers should be investigated before any decision about handling them."),
Q("ac9m10st05-t-008",32,"Reliability","Two studies examine sleep and mood. Study A uses 12 volunteers from one sports team; Study B uses 250 randomly selected students across the school. Which is generally more suitable for school-wide conclusions?",["Study B","Study A","Both are equally representative","Neither because bivariate studies need exactly 100 people"],0,"The larger, broadly sampled study is more likely to represent the school population."),
Q("ac9m10st05-t-009",33,"Data quality","Students self-report their daily screen time from memory for the previous six months. What is a likely limitation?",["Recall error","The variables become categorical","A scatterplot cannot be drawn","The sample automatically becomes random"],0,"Long-term recall can produce inaccurate measurements."),
Q("ac9m10st05-t-010",34,"Experimental design","A researcher wants stronger evidence that a training program affects performance. Which design would improve causal evidence most?",["Randomly assign comparable participants to training and control conditions where ethical and practical","Ask only the best performers","Use a larger font on the scatterplot","Remove all low scores"],0,"Random assignment helps balance confounding variables and supports causal inference."),
Q("ac9m10st05-t-011",35,"Reporting","A report states: 'r = 0.82, therefore training causes better performance.' What is wrong?",["A strong correlation does not by itself prove causation","0.82 means no association","Correlation can only be negative","r must equal exactly 1 to be reported"],0,"Correlation measures linear association, not cause-and-effect."),
Q("ac9m10st05-t-012",36,"Model evaluation","A line of fit consistently overpredicts low x-values and underpredicts high x-values. What does this suggest?",["A straight-line model may not fit the pattern well","The data must have no association","The sample is automatically biased","The variables must be categorical"],0,"A systematic residual pattern suggests the relationship may be nonlinear."),
Q("ac9m10st05-t-013",37,"Comparing investigations","Study A reports a strong association but does not state how the sample was chosen. Study B reports a moderate association and clearly describes a random sample and limitations. Which report is easier to evaluate critically?",["Study B","Study A","Both equally, because sampling does not matter","Neither, because association cannot be reported"],0,"Transparent methods and limitations allow readers to judge validity and generalisability."),
Q("ac9m10st05-t-014",38,"Ethics","A school collects students' mental-wellbeing scores and social-media use. Which reporting practice is most appropriate?",["Report aggregated results and protect individual privacy","Publish every student's name and score","Remove inconvenient responses","Claim causation from any correlation"],0,"Sensitive data should be handled and reported in ways that protect privacy."),
Q("ac9m10st05-t-015",39,"Conclusion quality","A sample shows a negative association between stress and sleep. Which conclusion best matches the evidence?",["In this sample, higher stress tended to occur with less sleep; other factors may also be involved","Stress definitely causes sleep loss in everyone","Sleep loss is the only cause of stress","The relationship will remain identical in every population"],0,"The first conclusion accurately describes the observed association and its limitations."),
Q("ac9m10st05-t-016",40,"Reporting","Which set of elements makes the strongest final report for a bivariate investigation?",["Question, sampling/data method, scatterplot and analysis, conclusion, limitations and relevant context","Only the correlation coefficient","Only a graph and title","Only the conclusion"],0,"A complete report explains the question, method, evidence, interpretation and limitations.")];
window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
