"use strict";
const Q=[
["multi-step efficiency","A device receives 2400 J. It transfers 300 J as sound and 420 J as thermal energy to the surroundings. The rest is useful. What is its efficiency?",["70%","30%","82.5%","55%"],0,"Useful = 2400−300−420 = 1680 J. Efficiency = 1680/2400 ×100 = 70%.","Account for all unwanted outputs first."],
["compare devices","Two machines each deliver 600 J of useful output. Machine A is 75% efficient; Machine B is 60% efficient. Which needs less input energy?",["Machine A: 800 J","Machine B: 1000 J","Both need 600 J","Cannot be determined"],0,"A needs 600/0.75=800 J; B needs 600/0.60=1000 J.","For the same useful output, higher efficiency needs less input."],
["sankey inference","A Sankey diagram shows 1200 J input. The useful arrow is twice as wide as the unwanted-output arrow. Assuming only these two outputs, what is the useful energy?",["800 J","600 J","400 J","900 J"],0,"The ratio useful:unwanted is 2:1, so useful is 2/3 of 1200 J = 800 J.","Split the total in the width ratio."],
["conservation check","A student's energy diagram shows 1500 J input, 900 J useful output, 500 J thermal output and 200 J sound output. What is the best evaluation?",["The diagram violates the accounting because outputs total 1600 J, greater than the stated input","The efficiency is 60%, so the diagram must be valid","Energy can be created as sound","The input should be ignored"],0,"900+500+200=1600 J, which exceeds 1500 J input. The boundary or measurements are inconsistent.","Add every output and compare with input."],
["efficiency improvement","A pump originally uses 5.0 MJ to deliver 3.0 MJ of useful energy. After redesign it still delivers 3.0 MJ but is 75% efficient. How much input energy is saved?",["1.0 MJ","0.75 MJ","1.5 MJ","2.0 MJ"],0,"Original input =5.0 MJ. New input=3.0/0.75=4.0 MJ. Saving=1.0 MJ.","Find the new input from efficiency."],
["appliance cost","Two refrigerators use 180 kWh and 260 kWh per year. Electricity costs $0.30 per kWh. Approximately how much less does the efficient fridge cost to run per year?",["$24","$80","$54","$18"],0,"Energy saving=80 kWh; cost saving=80×$0.30=$24.","Energy saved × unit price."],
["useful definition","A speaker converts electrical energy into sound and thermal energy. Which output counts as useful when the speaker is being used to play music?",["Sound energy","All thermal energy","Both outputs are equally useful by definition","Neither, because energy changes form"],0,"For a speaker used to produce music, sound is the intended output; heating is generally an unwanted transfer.","Purpose defines useful output."],
["context dependence","The same thermal output from an electric device is 'waste' in one situation but useful in another. Which example best demonstrates this?",["Heat from a computer is unwanted, while heat from a room heater is intended","Sound from a speaker is always waste","Light from a lamp is always waste","Mechanical energy can never be useful"],0,"Usefulness depends on the system purpose, not on the energy form alone.","Same form, different purpose."],
["power and energy","A motor takes 500 W of electrical power and delivers 350 W of mechanical power for 20 s. What useful energy is delivered?",["7000 J","350 J","10,000 J","17.5 J"],0,"Useful energy = power × time = 350×20 = 7000 J.","E = P×t."],
["power efficiency","For the motor in the previous scenario, what is its efficiency?",["70%","30%","143%","17.5%"],0,"350/500 ×100 = 70%.","Power ratios can be used when measured over the same interval."],
["two-stage system","An energy system has two stages: Stage 1 is 80% efficient and Stage 2 is 75% efficient. If 1000 J enters Stage 1, how much useful energy leaves Stage 2?",["600 J","775 J","800 J","750 J"],0,"After Stage 1: 800 J. After Stage 2: 0.75×800 = 600 J.","Multiply successive efficiency fractions."],
["overall efficiency","What is the overall efficiency of the two-stage system with efficiencies 80% then 75%?",["60%","77.5%","155%","5%"],0,"Overall efficiency =0.80×0.75=0.60=60%.","Successive efficiencies multiply, not add."],
["renewables misconception","A solar panel is 20% efficient. Which statement is scientifically correct?",["About 20% of the incident solar energy counted at the system boundary becomes the chosen useful electrical output","80% of the input energy is destroyed","The panel is environmentally worse than any 40%-efficient system","Low conversion efficiency means conservation of energy fails"],0,"The remaining energy is reflected, transmitted or transferred mainly as thermal energy; it is not destroyed.","Efficiency alone does not determine environmental impact."],
["sports boundary","An athlete uses 5000 J of chemical energy, and 1200 J becomes external mechanical work. Why might calling the remaining 3800 J simply 'wasted' be oversimplified?",["Some energy supports essential body processes and thermal regulation even if it is not counted as external mechanical work","Human bodies do not conserve energy","Chemical energy disappears inside muscles","Mechanical work can exceed chemical input"],0,"The label useful/wasted depends on the defined purpose and boundary; physiological energy transfers may serve other functions.","Be careful with system purpose in biological examples."],
["measurement uncertainty","A device is measured as 102% efficient. What is the best scientific interpretation?",["Measurement uncertainty, missing inputs or an incorrect system boundary should be investigated","The device creates energy","The law of conservation works only below 100%","102% is normal for efficient machines"],0,"A measured value slightly above 100% signals measurement/accounting issues because useful output cannot exceed total energy input.","Above 100% means check the measurement model."],
["design reasoning","Which redesign most directly improves the efficiency of a motor if the intended output is mechanical motion?",["Reduce unwanted heating and friction while maintaining mechanical output","Increase sound production","Add a decorative light using extra energy","Redefine heat as useful without changing the motor's purpose"],0,"Efficiency improves when a larger fraction of input reaches the intended output, often by reducing frictional and resistive losses.","Improve the fraction reaching the desired pathway." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s9u05-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S9U05",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));