"use strict";
window.skillrPracticeQuestions = [
  {
    "id": "ac9m5sp01-p-001",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A net has 2 congruent triangles and 3 rectangles. Which solid can it form?",
    "audioPrompt": "A net has 2 congruent triangles and 3 rectangles. Which solid can it form?",
    "answers": ["triangular prism", "square pyramid", "cube"],
    "correct": 0,
    "explanation": "A triangular prism has two triangular bases and three rectangular side faces.",
    "structuredExplanation": {"summary": "A triangular prism has two triangular bases and three rectangular side faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-002",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A net has 1 square and 4 triangles joined around the square. Which solid can it form?",
    "audioPrompt": "A net has 1 square and 4 triangles joined around the square. Which solid can it form?",
    "answers": ["square-based pyramid", "triangular prism", "rectangular prism"],
    "correct": 0,
    "explanation": "A square-based pyramid has one square base and four triangular faces.",
    "structuredExplanation": {"summary": "A square-based pyramid has one square base and four triangular faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-003",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which face set matches a cube?",
    "audioPrompt": "Which face set matches a cube?",
    "answers": ["6 equal squares", "2 triangles and 3 rectangles", "1 square and 4 triangles"],
    "correct": 0,
    "explanation": "A cube has six equal square faces.",
    "structuredExplanation": {"summary": "A cube has six equal square faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-004",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A prism net has 2 congruent pentagons. How many rectangular side faces should it have?",
    "audioPrompt": "A prism net has 2 congruent pentagons. How many rectangular side faces should it have?",
    "answers": ["5", "2", "7"],
    "correct": 0,
    "explanation": "A pentagonal prism has one rectangular side face for each side of the pentagonal base.",
    "structuredExplanation": {"summary": "A pentagonal prism has one rectangular side face for each side of the pentagonal base.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-005",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A triangular prism net has 3 rectangles. What do these become?",
    "audioPrompt": "A triangular prism net has 3 rectangles. What do these become?",
    "answers": ["side faces", "triangular bases", "vertices"],
    "correct": 0,
    "explanation": "The rectangles wrap around to form the side faces.",
    "structuredExplanation": {"summary": "The rectangles wrap around to form the side faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-006",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which solid has exactly one base and triangular faces meeting at an apex?",
    "audioPrompt": "Which solid has exactly one base and triangular faces meeting at an apex?",
    "answers": ["pyramid", "prism", "cube"],
    "correct": 0,
    "explanation": "A pyramid has one base and triangular lateral faces meeting at an apex.",
    "structuredExplanation": {"summary": "A pyramid has one base and triangular lateral faces meeting at an apex.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-007",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which solid has two congruent parallel bases?",
    "audioPrompt": "Which solid has two congruent parallel bases?",
    "answers": ["prism", "pyramid", "cube"],
    "correct": 0,
    "explanation": "Prisms are defined by two congruent parallel bases.",
    "structuredExplanation": {"summary": "Prisms are defined by two congruent parallel bases.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-008",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A valid rectangular-prism net contains how many faces in total?",
    "audioPrompt": "A valid rectangular-prism net contains how many faces in total?",
    "answers": ["6", "5", "8"],
    "correct": 0,
    "explanation": "A rectangular prism has six rectangular faces.",
    "structuredExplanation": {"summary": "A rectangular prism has six rectangular faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-009",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A valid triangular-pyramid net contains how many triangular faces?",
    "audioPrompt": "A valid triangular-pyramid net contains how many triangular faces?",
    "answers": ["4", "3", "5"],
    "correct": 0,
    "explanation": "A triangular pyramid has four triangular faces.",
    "structuredExplanation": {"summary": "A triangular pyramid has four triangular faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-010",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which net could make a hexagonal prism?",
    "audioPrompt": "Which net could make a hexagonal prism?",
    "answers": ["2 hexagons and 6 rectangles", "1 hexagon and 6 triangles", "6 squares"],
    "correct": 0,
    "explanation": "A hexagonal prism has two hexagonal bases and six rectangular side faces.",
    "structuredExplanation": {"summary": "A hexagonal prism has two hexagonal bases and six rectangular side faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-011",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which statement about a valid net is true?",
    "audioPrompt": "Which statement about a valid net is true?",
    "answers": ["Faces must be connected so they fold without overlap or gaps.", "Only the number of faces matters.", "The net must always look symmetrical."],
    "correct": 0,
    "explanation": "A valid net requires the correct faces arranged so folding closes the solid without overlap or gaps.",
    "structuredExplanation": {"summary": "A valid net requires the correct faces arranged so folding closes the solid without overlap or gaps.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-012",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A net is rotated on the page. What happens to the solid it can make?",
    "audioPrompt": "A net is rotated on the page. What happens to the solid it can make?",
    "answers": ["Nothing; rotation of the drawing does not change the net structure.", "It becomes a different solid.", "It cannot be folded."],
    "correct": 0,
    "explanation": "Orientation on the page is not a property of the net.",
    "structuredExplanation": {"summary": "Orientation on the page is not a property of the net.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-013",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which face is a base of a square-based pyramid?",
    "audioPrompt": "Which face is a base of a square-based pyramid?",
    "answers": ["the square", "any triangle", "an edge"],
    "correct": 0,
    "explanation": "The square is the single base; the triangles meet at the apex.",
    "structuredExplanation": {"summary": "The square is the single base; the triangles meet at the apex.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-014",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A prism has two triangular bases. What type of prism is it?",
    "audioPrompt": "A prism has two triangular bases. What type of prism is it?",
    "answers": ["triangular prism", "square prism", "triangular pyramid"],
    "correct": 0,
    "explanation": "Prisms are named by the shape of their bases.",
    "structuredExplanation": {"summary": "Prisms are named by the shape of their bases.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-015",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "A cube net has six squares. Is that alone enough to prove it is valid?",
    "audioPrompt": "A cube net has six squares. Is that alone enough to prove it is valid?",
    "answers": ["No, the arrangement must also fold correctly.", "Yes, any six squares form a cube.", "Only if the squares are different sizes."],
    "correct": 0,
    "explanation": "Correct face count is necessary but adjacency also matters.",
    "structuredExplanation": {"summary": "Correct face count is necessary but adjacency also matters.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-016",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "recognise/apply",
    "printable": true,
    "type": "single",
    "question": "Which feature distinguishes a triangular prism from a triangular pyramid?",
    "audioPrompt": "Which feature distinguishes a triangular prism from a triangular pyramid?",
    "answers": ["The prism has two triangular bases and rectangular side faces.", "The prism has one triangular base only.", "The pyramid has rectangular side faces."],
    "correct": 0,
    "explanation": "A triangular prism has two triangular bases joined by rectangles.",
    "structuredExplanation": {"summary": "A triangular prism has two triangular bases joined by rectangles.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-017",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A proposed cube net has six squares, but two faces would fold onto the same position. Why is it invalid?",
    "audioPrompt": "A proposed cube net has six squares, but two faces would fold onto the same position. Why is it invalid?",
    "answers": ["Faces would overlap instead of forming six different cube faces.", "A cube needs only five faces.", "Squares cannot be adjacent."],
    "correct": 0,
    "explanation": "A valid net must fold so each face occupies a different face of the solid.",
    "structuredExplanation": {"summary": "A valid net must fold so each face occupies a different face of the solid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-018",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A net has 2 equal pentagons and only 4 rectangles. Why can it not form a pentagonal prism?",
    "audioPrompt": "A net has 2 equal pentagons and only 4 rectangles. Why can it not form a pentagonal prism?",
    "answers": ["It needs 5 rectangular side faces.", "It needs 3 pentagons.", "It has too many faces."],
    "correct": 0,
    "explanation": "Each side of a pentagonal base needs one rectangular lateral face.",
    "structuredExplanation": {"summary": "Each side of a pentagonal base needs one rectangular lateral face.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-019",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A student chooses a square-pyramid net because it has five faces. What else must be checked?",
    "audioPrompt": "A student chooses a square-pyramid net because it has five faces. What else must be checked?",
    "answers": ["One face is a square and the four others are triangles arranged to meet at an apex.", "All five faces are squares.", "There are two equal square bases."],
    "correct": 0,
    "explanation": "Face types and adjacency, not just count, determine the solid.",
    "structuredExplanation": {"summary": "Face types and adjacency, not just count, determine the solid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-020",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "Two nets have the same six square faces. One folds to a cube and one does not. What explains the difference?",
    "audioPrompt": "Two nets have the same six square faces. One folds to a cube and one does not. What explains the difference?",
    "answers": ["The way the squares are connected.", "The colour of the squares.", "The direction the page is held."],
    "correct": 0,
    "explanation": "Different adjacencies can make one arrangement valid and another invalid.",
    "structuredExplanation": {"summary": "Different adjacencies can make one arrangement valid and another invalid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-021",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A triangular-prism net has its two triangles attached to opposite ends of a strip of three rectangles. What must be checked when folding?",
    "audioPrompt": "A triangular-prism net has its two triangles attached to opposite ends of a strip of three rectangles. What must be checked when folding?",
    "answers": ["The triangles close the two ends without overlapping side faces.", "The triangles become adjacent bases.", "The rectangles become triangles."],
    "correct": 0,
    "explanation": "The two congruent triangles must cap the prism at opposite ends.",
    "structuredExplanation": {"summary": "The two congruent triangles must cap the prism at opposite ends.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-022",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A net has one hexagon with six triangles around it. Which family is most likely?",
    "audioPrompt": "A net has one hexagon with six triangles around it. Which family is most likely?",
    "answers": ["hexagonal pyramid", "hexagonal prism", "cube"],
    "correct": 0,
    "explanation": "One polygonal base with triangles around it is a pyramid structure.",
    "structuredExplanation": {"summary": "One polygonal base with triangles around it is a pyramid structure.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-023",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A net has two congruent hexagons joined by a belt of rectangles. Which family is it?",
    "audioPrompt": "A net has two congruent hexagons joined by a belt of rectangles. Which family is it?",
    "answers": ["hexagonal prism", "hexagonal pyramid", "triangular prism"],
    "correct": 0,
    "explanation": "Two congruent polygonal bases with rectangular sides define a prism.",
    "structuredExplanation": {"summary": "Two congruent polygonal bases with rectangular sides define a prism.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-024",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A student rejects a valid net because it is upside down compared with the textbook. What misconception is shown?",
    "audioPrompt": "A student rejects a valid net because it is upside down compared with the textbook. What misconception is shown?",
    "answers": ["Net orientation on the page does not affect foldability.", "Every net must have a top face at the top.", "Only symmetrical nets are valid."],
    "correct": 0,
    "explanation": "Rotating or reflecting the drawing does not change adjacency.",
    "structuredExplanation": {"summary": "Rotating or reflecting the drawing does not change adjacency.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-025",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A cube net has a row of four squares with one square attached above the second and one below the second. Why can it work?",
    "audioPrompt": "A cube net has a row of four squares with one square attached above the second and one below the second. Why can it work?",
    "answers": ["The attached squares can fold to opposite faces while the strip wraps around.", "The row stays flat.", "All six squares become one face."],
    "correct": 0,
    "explanation": "The strip wraps around four side faces and the attachments close the remaining two.",
    "structuredExplanation": {"summary": "The strip wraps around four side faces and the attachments close the remaining two.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-026",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A net has the right face types for a triangular prism but one triangle is attached in a way that would overlap the other end. What should be concluded?",
    "audioPrompt": "A net has the right face types for a triangular prism but one triangle is attached in a way that would overlap the other end. What should be concluded?",
    "answers": ["The net is invalid because adjacency matters.", "It is valid because face inventory is enough.", "It forms a cube."],
    "correct": 0,
    "explanation": "Correct faces are not sufficient if folding creates overlap.",
    "structuredExplanation": {"summary": "Correct faces are not sufficient if folding creates overlap.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-027",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "Which evidence best proves two faces of a cube net will be opposite after folding?",
    "audioPrompt": "Which evidence best proves two faces of a cube net will be opposite after folding?",
    "answers": ["Tracking their positions through the folds.", "They have the same colour.", "They are far apart on the page."],
    "correct": 0,
    "explanation": "Opposite-face relationships come from the fold sequence, not page distance alone.",
    "structuredExplanation": {"summary": "Opposite-face relationships come from the fold sequence, not page distance alone.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-028",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "Why can a rectangular-prism net include rectangles of different sizes?",
    "audioPrompt": "Why can a rectangular-prism net include rectangles of different sizes?",
    "answers": ["Different pairs of opposite faces can have different dimensions.", "All prism faces must be squares.", "Only the bases can be rectangles."],
    "correct": 0,
    "explanation": "A rectangular prism generally has three pairs of congruent rectangles.",
    "structuredExplanation": {"summary": "A rectangular prism generally has three pairs of congruent rectangles.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-029",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A pentagonal-prism net is shown with 2 pentagons and 5 rectangles. What additional check is needed?",
    "audioPrompt": "A pentagonal-prism net is shown with 2 pentagons and 5 rectangles. What additional check is needed?",
    "answers": ["The rectangles and bases must be connected in a foldable arrangement.", "Nothing; face count guarantees validity.", "The pentagons must touch each other directly."],
    "correct": 0,
    "explanation": "Adjacency must allow the strip to wrap and the bases to close the ends.",
    "structuredExplanation": {"summary": "Adjacency must allow the strip to wrap and the bases to close the ends.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-030",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A pyramid net has four triangular side faces. What determines whether it is square-based or another pyramid?",
    "audioPrompt": "A pyramid net has four triangular side faces. What determines whether it is square-based or another pyramid?",
    "answers": ["The shape of the base.", "The colour of the triangles.", "The length of the net on the page."],
    "correct": 0,
    "explanation": "Pyramids are named by their base shape.",
    "structuredExplanation": {"summary": "Pyramids are named by their base shape.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-031",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "A student says a net with two congruent triangles must be a triangular prism. Why is that incomplete?",
    "audioPrompt": "A student says a net with two congruent triangles must be a triangular prism. Why is that incomplete?",
    "answers": ["The remaining faces and their connections also matter.", "Two triangles always make a prism.", "Prisms have only triangular faces."],
    "correct": 0,
    "explanation": "The full face inventory and adjacency must match the target solid.",
    "structuredExplanation": {"summary": "The full face inventory and adjacency must match the target solid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-032",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "reasoning",
    "printable": true,
    "type": "single",
    "question": "Which check is most useful after counting the correct faces in a net?",
    "audioPrompt": "Which check is most useful after counting the correct faces in a net?",
    "answers": ["Mentally fold and test which edges meet.", "Count the colours.", "Measure the page border."],
    "correct": 0,
    "explanation": "After face inventory, folding/adjacency is the key validity check.",
    "structuredExplanation": {"summary": "After face inventory, folding/adjacency is the key validity check.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-033",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A box designer removes one square from a valid cube net. What is the minimum change needed to restore a possible cube net?",
    "audioPrompt": "A box designer removes one square from a valid cube net. What is the minimum change needed to restore a possible cube net?",
    "answers": ["Add one square in a position that folds to the missing face without overlap.", "Add a triangle anywhere.", "Stretch one existing square."],
    "correct": 0,
    "explanation": "A cube needs six square faces arranged so all six positions close without overlap.",
    "structuredExplanation": {"summary": "A cube needs six square faces arranged so all six positions close without overlap.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-034",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net for a triangular prism is missing one side face. It currently has 2 triangles and 2 rectangles. What must be added?",
    "audioPrompt": "A net for a triangular prism is missing one side face. It currently has 2 triangles and 2 rectangles. What must be added?",
    "answers": ["1 rectangle", "1 triangle", "2 squares"],
    "correct": 0,
    "explanation": "A triangular prism needs three rectangular side faces.",
    "structuredExplanation": {"summary": "A triangular prism needs three rectangular side faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-035",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net for a pentagonal prism is missing one base. It has 1 pentagon and 5 rectangles. What must be added?",
    "audioPrompt": "A net for a pentagonal prism is missing one base. It has 1 pentagon and 5 rectangles. What must be added?",
    "answers": ["1 congruent pentagon", "1 rectangle", "5 triangles"],
    "correct": 0,
    "explanation": "A prism requires two congruent bases.",
    "structuredExplanation": {"summary": "A prism requires two congruent bases.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-036",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A labelled cube net has faces A and B known to fold onto opposite sides. Which statement must be true?",
    "audioPrompt": "A labelled cube net has faces A and B known to fold onto opposite sides. Which statement must be true?",
    "answers": ["A and B cannot share an edge on the finished cube.", "A and B must overlap.", "A and B become the same face."],
    "correct": 0,
    "explanation": "Opposite cube faces do not share an edge.",
    "structuredExplanation": {"summary": "Opposite cube faces do not share an edge.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-037",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A packaging net has one square and four triangles, but two triangles would overlap when folded. What is the best repair?",
    "audioPrompt": "A packaging net has one square and four triangles, but two triangles would overlap when folded. What is the best repair?",
    "answers": ["Change the attachment of a triangle so all four meet around the apex without overlap.", "Add a second square base.", "Replace the triangles with rectangles."],
    "correct": 0,
    "explanation": "The face types are right for a square pyramid; the connections need repair.",
    "structuredExplanation": {"summary": "The face types are right for a square pyramid; the connections need repair.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-038",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A prism has 8 faces in total and two congruent polygonal bases. How many sides does each base have?",
    "audioPrompt": "A prism has 8 faces in total and two congruent polygonal bases. How many sides does each base have?",
    "answers": ["6", "5", "4"],
    "correct": 0,
    "explanation": "A prism with n-sided bases has n rectangular side faces plus 2 bases, so n + 2 = 8 gives n = 6.",
    "structuredExplanation": {"summary": "A prism with n-sided bases has n rectangular side faces plus 2 bases, so n + 2 = 8 gives n = 6.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-039",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A prism net has 2 congruent octagons. How many rectangular side faces are needed?",
    "audioPrompt": "A prism net has 2 congruent octagons. How many rectangular side faces are needed?",
    "answers": ["8", "6", "10"],
    "correct": 0,
    "explanation": "One rectangle corresponds to each side of the octagonal base.",
    "structuredExplanation": {"summary": "One rectangle corresponds to each side of the octagonal base.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-040",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A pyramid has one pentagonal base. How many triangular side faces should its net contain?",
    "audioPrompt": "A pyramid has one pentagonal base. How many triangular side faces should its net contain?",
    "answers": ["5", "2", "10"],
    "correct": 0,
    "explanation": "One triangular face meets each side of the pentagonal base.",
    "structuredExplanation": {"summary": "One triangular face meets each side of the pentagonal base.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-041",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net has 2 squares and 4 rectangles. Which solid could it make if the squares are congruent bases?",
    "audioPrompt": "A net has 2 squares and 4 rectangles. Which solid could it make if the squares are congruent bases?",
    "answers": ["square prism", "square pyramid", "cube only"],
    "correct": 0,
    "explanation": "Two square bases with four rectangular lateral faces form a square prism.",
    "structuredExplanation": {"summary": "Two square bases with four rectangular lateral faces form a square prism.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-042",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net includes all correct faces for a cube. To decide whether two labelled faces become adjacent, what reasoning is required?",
    "audioPrompt": "A net includes all correct faces for a cube. To decide whether two labelled faces become adjacent, what reasoning is required?",
    "answers": ["Track shared edges through the fold sequence.", "Compare their colours.", "Count only the faces between them on the page."],
    "correct": 0,
    "explanation": "Adjacency in the 3D object must be inferred from folding.",
    "structuredExplanation": {"summary": "Adjacency in the 3D object must be inferred from folding.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-043",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A builder wants two marked faces to be opposite on a cube. Which design test is strongest?",
    "audioPrompt": "A builder wants two marked faces to be opposite on a cube. Which design test is strongest?",
    "answers": ["Fold mentally or with a model and check they never share an edge.", "Place them farthest apart in the flat drawing.", "Colour them differently."],
    "correct": 0,
    "explanation": "Flat distance is unreliable; folding determines opposite faces.",
    "structuredExplanation": {"summary": "Flat distance is unreliable; folding determines opposite faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-044",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net is reflected like a mirror image on the page. If the original net was valid, what can usually be said about the reflected arrangement?",
    "audioPrompt": "A net is reflected like a mirror image on the page. If the original net was valid, what can usually be said about the reflected arrangement?",
    "answers": ["It remains a valid net with the same adjacency pattern mirrored.", "It must form a different solid.", "It loses one face."],
    "correct": 0,
    "explanation": "Mirroring the flat layout preserves the connectivity needed to fold the same solid.",
    "structuredExplanation": {"summary": "Mirroring the flat layout preserves the connectivity needed to fold the same solid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-045",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A student designs a net with two congruent triangles and three quadrilaterals, but one quadrilateral is not a rectangle. Can it still be a right triangular-prism net in this Year 5 model?",
    "audioPrompt": "A student designs a net with two congruent triangles and three quadrilaterals, but one quadrilateral is not a rectangle. Can it still be a right triangular-prism net in this Year 5 model?",
    "answers": ["No; the standard right-prism side faces should be rectangles.", "Yes; any quadrilateral works.", "Only the triangles matter."],
    "correct": 0,
    "explanation": "The standard triangular-prism nets studied use rectangular side faces.",
    "structuredExplanation": {"summary": "The standard triangular-prism nets studied use rectangular side faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-046",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A solid has one hexagonal base and six triangular faces meeting at one vertex. What would its net look like?",
    "audioPrompt": "A solid has one hexagonal base and six triangular faces meeting at one vertex. What would its net look like?",
    "answers": ["one hexagon with six triangles attached around it", "two hexagons with six rectangles", "six squares in a strip"],
    "correct": 0,
    "explanation": "That face structure is a hexagonal pyramid.",
    "structuredExplanation": {"summary": "That face structure is a hexagonal pyramid.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-047",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "A net for a cube is cut into two disconnected pieces. Why is it not a single usable net?",
    "audioPrompt": "A net for a cube is cut into two disconnected pieces. Why is it not a single usable net?",
    "answers": ["A net must be connected so the faces fold together as one surface.", "Disconnected pieces always make two cubes.", "A cube cannot have square faces."],
    "correct": 0,
    "explanation": "A net is one connected arrangement of all faces.",
    "structuredExplanation": {"summary": "A net is one connected arrangement of all faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  },
  {
    "id": "ac9m5sp01-p-048",
    "curriculumCode": "AC9M5SP01",
    "bank": "practice",
    "skill": "transfer/challenge",
    "printable": true,
    "type": "single",
    "question": "Which design challenge tests the highest spatial reasoning?",
    "audioPrompt": "Which design challenge tests the highest spatial reasoning?",
    "answers": ["Choose where to attach a missing face so the completed net folds without overlap and gives a required opposite-face relationship.", "Name a cube from six squares.", "Count the faces of a square pyramid."],
    "correct": 0,
    "explanation": "Repairing a net under folding constraints requires tracking adjacency and opposite faces.",
    "structuredExplanation": {"summary": "Repairing a net under folding constraints requires tracking adjacency and opposite faces.", "hint": "Use the defining features and check your reasoning before choosing."},
    "qualitySchema": "production-v1"
  }
];
