import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {LA_ITEMS} from './year3_english_items_la.mjs';import {LE_LY_ITEMS} from './year3_english_items_le_ly.mjs';
const R=path.resolve(import.meta.dirname,'..'),c={window:{}};vm.createContext(c);for(const f of ['assets/year3-subject-data-base.js','assets/year3-english-data-la1.js','assets/year3-english-data-la2.js','assets/year3-english-data-la3a.js','assets/year3-english-data-la3b.js','assets/year3-english-data-le.js','assets/year3-english-data-ly1.js','assets/year3-english-data-ly2.js','assets/year3-english-student-facing.js'])vm.runInContext(fs.readFileSync(path.join(R,f),'utf8'),c,{filename:f});
const U=c.window.SkillrYear3EnglishData,C=Object.keys(U).sort(),S={...LA_ITEMS,...LE_LY_ITEMS},stages=['recognise','explain','discriminate','apply'];
const norm=x=>String(x).replace(/\s+/g,' ').trim().toLowerCase();
function answers(correct,wrong,ci){const a=[...wrong];a.splice(ci,0,correct);return a.map((text,j)=>({text,is_correct:j===ci}));}
function item(code,u,s,i,stage,question,correct,wrong,summary,hint){const ci=(i+C.indexOf(code))%3;return{id:`${code}-P-${String(i+1).padStart(3,'0')}`,subject:'english',year_level:'Year 3',curriculum_code:code,bank:'practice',stage,skill:u.title,question,audio_prompt:question,answers:answers(correct,wrong,ci),correct_index:ci,explanation:{summary,hint}};}
for(const code of C){const src=S[code];if(!src||src.length!==40)throw Error(`${code}: expected 40 authored source items`);const u=U[code],practice=[];
for(let i=0;i<10;i++){const s=src[i];practice.push(item(code,u,s,i,'recognise',s.question,s.correct,s.wrong,s.summary,s.hint));}
for(let i=0;i<10;i++){const s=src[10+i],q=`Why is “${s.correct}” the best answer here? ${s.question}`;practice.push(item(code,u,s,10+i,'explain',q,s.summary,[`Because “${s.wrong[0]}” sounds familiar.`,`Because the longest-looking option should always be chosen.`],s.summary,s.hint));}
for(let i=0;i<10;i++){const s=src[i],q=`A student chooses “${s.wrong[0]}” for this task: ${s.question} What should they check?`;practice.push(item(code,u,s,20+i,'discriminate',q,s.hint,[`Keep the answer because it uses a familiar word.`,`Ignore the example and choose the remaining option.`],`${s.hint} ${s.summary}`,'Use the exact clue in the example to repair the mix-up.'));}
for(let i=0;i<10;i++){const s=src[14+i];practice.push(item(code,u,s,30+i,'apply',s.question,s.correct,s.wrong,s.summary,s.hint));}
if(new Set(practice.map(x=>norm(x.question))).size!==40)throw Error(`${code}: duplicate practice prompts`);
const test=src.slice(24,40).map((s,i)=>{const ci=(i+C.indexOf(code)+1)%3;return{id:`${code}-T-${String(i+1).padStart(3,'0')}`,subject:'english',year_level:'Year 3',curriculum_code:code,bank:'test',stage:i<8?'verify':'apply',skill:u.title,question:s.question,audio_prompt:s.question,answers:answers(s.correct,s.wrong,ci),correct_index:ci,explanation:{summary:s.summary,hint:s.hint}}});
const pQ=new Set(practice.map(x=>norm(x.question)));if(test.some(x=>pQ.has(norm(x.question))))throw Error(`${code}: Practice/Test prompt overlap`);
const out=path.join(R,'assets/assessment-banks/year3/english',`${code.toLowerCase()}.json`);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify([...practice,...test],null,2)+'\n');}
console.log(`Year 3 English rebuilt: ${C.length} codes, ${C.length*40} practice, ${C.length*16} separate test.`);
