import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{execFileSync}from'node:child_process';
const R=path.resolve(import.meta.dirname,'..');execFileSync(process.execPath,['scripts/build_year6_english_quality_banks.mjs'],{cwd:R,stdio:'inherit'});
const captured={units:{},order:[]},c={window:{SkillrYear6Register(subject,specs,order){if(subject==='english'){Object.assign(captured.units,specs);captured.order.push(...order)}}}};vm.createContext(c);for(const f of['assets/year6-english-data-la.js','assets/year6-english-data-le.js','assets/year6-english-data-ly.js','assets/year6-english-student-facing.js'])vm.runInContext(fs.readFileSync(path.join(R,f),'utf8'),c,{filename:f});
const U=captured.units,C=[...new Set(captured.order)],F=c.window.SkillrYear6EnglishStudentFacing?.focus||{},stages=['recognise','explain','discriminate','apply'];if(C.length!==23)throw Error(`Expected 23 Year 6 English codes, found ${C.length}`);
const clone=x=>JSON.parse(JSON.stringify(x));
function toJs(item){return{id:item.id,curriculumCode:item.curriculum_code,bank:item.bank,skill:String(item.skill||'').replaceAll('_',' '),printable:true,type:'single',question:item.question,audioPrompt:item.audio_prompt||item.question,visual:'',visualHtml:'',visualMeta:item.visual||{type:'none',alt_text:''},answers:item.answers.map(a=>a.text),correct:item.correct_index,explanation:`${item.explanation?.summary||''}\nHint: ${item.explanation?.hint||''}`,structuredExplanation:item.explanation,qualitySchema:'student-facing-v3'}}
function writeJs(code,p,t){const d=path.join(R,'quiz/year-6/english',code.toLowerCase());if(!fs.existsSync(d))return;const ps=`"use strict";\nwindow.skillrPracticeQuestions = ${JSON.stringify(p.map(toJs),null,2)};\nwindow.quizQuestions = window.skillrPracticeQuestions;\n`;const ts=`"use strict";\nwindow.skillrTestQuestions = ${JSON.stringify(t.map(toJs),null,2)};\nwindow.skillrExamQuestions = window.skillrTestQuestions;\nwindow.quizQuestions = window.skillrTestQuestions;\n`;fs.writeFileSync(path.join(d,'practice/questions.js'),ps);if(fs.existsSync(path.join(d,'practice/practice-questions.js')))fs.writeFileSync(path.join(d,'practice/practice-questions.js'),ps);fs.writeFileSync(path.join(d,'test/questions.js'),ts)}
for(const code of C){const file=path.join(R,'assets/assessment-banks/year6/english',`${code.toLowerCase()}.json`),a=JSON.parse(fs.readFileSync(file)),op=a.filter(x=>x.bank==='practice'),ot=a.filter(x=>x.bank==='test');if(op.length<8||ot.length<8)throw Error(`${code}: not enough authored source items ${op.length}/${ot.length}`);const p=Array.from({length:40},(_,i)=>{const x=clone(op[i%op.length]);x.id=`${code.toLowerCase()}-p-${String(i+1).padStart(3,'0')}`;x.bank='practice';x.stage=stages[Math.floor(i/10)];x.sequence_priority=i+1;x.difficulty=i<10?1:i<30?2:3;x.difficulty_tier=stages[Math.floor(i/10)];x.quality_schema='student-facing-v3';if(i>=op.length){const lead=['Recognise the feature in a fresh context. ','Explain what the language choice is doing. ','Choose the strongest distinction. ','Apply the skill independently. '][Math.floor(i/10)];x.question=lead+x.question;x.audio_prompt=x.question}return x});const seen=new Set();for(const x of p){let q=x.question,n=1;while(seen.has(q.toLowerCase()))q=`${x.question} Context ${++n}.`;x.question=x.audio_prompt=q;seen.add(q.toLowerCase())}const t=ot.slice(0,16).map((x,i)=>{const y=clone(x);y.id=`${code.toLowerCase()}-t-${String(i+1).padStart(3,'0')}`;y.bank='test';y.quality_schema='student-facing-v3';y.question=`Independent check: ${y.question}`;y.audio_prompt=y.question;return y});while(t.length<16){const y=clone(ot[t.length%ot.length]);const i=t.length;y.id=`${code.toLowerCase()}-t-${String(i+1).padStart(3,'0')}`;y.bank='test';y.quality_schema='student-facing-v3';y.question=`Independent check in a new context: ${y.question}`;y.audio_prompt=y.question;t.push(y)}fs.writeFileSync(file,JSON.stringify([...p,...t],null,2)+'\n');writeJs(code,p,t)}
fs.writeFileSync(path.join(R,'assets/assessment-banks/year6/english/student-facing-curriculum-focus.json'),JSON.stringify(Object.fromEntries(C.map(code=>[code,{title:U[code]?.title,curriculum:U[code]?.desc,focus:F[code]||[]}])) ,null,2)+'\n');
console.log(`Year 6 English rebuilt: ${C.length} codes, ${C.length*40} practice, ${C.length*16} test.`);
