#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const ROOT = path.resolve(import.meta.dirname, "..");
const read = (file) => fs.readFileSync(path.join(ROOT,file),"utf8");
const write = (file,content) => { const full=path.join(ROOT,file); fs.mkdirSync(path.dirname(full),{recursive:true}); fs.writeFileSync(full,content); };
const esc = (value="") => String(value ?? "").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const strip = (value="") => String(value ?? "").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const context = vm.createContext({window:{}});
for (const file of ["assets/year2-english-data.js","assets/year2-english-student-facing.js"]) new vm.Script(read(file),{filename:file}).runInContext(context);
const units = context.window.SkillrYear2EnglishData || {};
const codes = Object.keys(units).filter((code)=>/^AC9E2(?:LA|LE|LY)\d{2}$/.test(code)).sort();
if (codes.length !== 27) throw new Error(`Expected 27 Year 2 English codes, found ${codes.length}`);

function findTopicDir(code) {
  const root=path.join(ROOT,"year2","english");
  const hits=fs.readdirSync(root,{withFileTypes:true}).filter((entry)=>entry.isDirectory()&&entry.name.toLowerCase().startsWith(`${code.toLowerCase()}-`));
  if(hits.length!==1) throw new Error(`${code}: expected one topic directory, found ${hits.length}`);
  return path.join("year2","english",hits[0].name);
}
function preserveDetails(html,pattern){const details=[...html.matchAll(/<details\b[\s\S]*?<\/details>/gi)].map((m)=>m[0]);return details.find((block)=>pattern.test(strip(block)))||"";}
function list(items,mapper=(item)=>esc(item)){return `<ul>${(items||[]).map((item)=>`<li>${mapper(item)}</li>`).join("")}</ul>`;}
function topicBody(code,unit,existing){
  const focus=unit.studentFacingFocus||[];
  const activities=(unit.activities||[]).map((a)=>`<li><strong>${esc(a.title)}</strong> — ${esc(a.text)}${a.visual_html||a.visual?`<div class="english-card-row"><span>${esc(strip(a.visual_html||a.visual))}</span></div>`:""}</li>`).join("");
  const mistakes=(unit.mistakes||[]).map(([name,fix])=>`<li><strong>${esc(name)}</strong> — ${esc(fix)}</li>`).join("");
  const quick=list(unit.quick||[]);
  const mastery=list(unit.mastery||[],(item)=>esc(/^I can\b/i.test(item)?item:`I can ${String(item).replace(/[.]$/,"").replace(/^./,(c)=>c.toLowerCase())}.`));
  const curriculum=preserveDetails(existing,/Curriculum Coverage.*Elaborations|Australian Curriculum elaborations/i);
  const equivalents=preserveDetails(existing,/Curriculum equivalents/i);
  return `<header class="curriculum-hero"><p class="curriculum-eyebrow">${code} • Year 2 English</p><h1>${esc(unit.title)}</h1><p class="curriculum-hero__lead">${esc(unit.childGoal||unit.learn)}</p><div class="topic-action-row"><a class="primary" href="#topic-guide">Topic Guide</a><a href="teacher-slides/">Classroom View</a><a href="/quiz/year-2/english/${code.toLowerCase()}/worksheet/">Printable Worksheet</a><a href="/quiz/year-2/english/${code.toLowerCase()}/practice/">40-question Practice</a><a href="/quiz/year-2/english/${code.toLowerCase()}/test/">Test</a></div><button class="report-issue-button" type="button" data-report-issue>Report issue</button></header>
<main class="curriculum-layout"><div id="topic-guide">
<details class="curriculum-topic-section" open><summary><strong>What this skill means</strong></summary><div class="curriculum-detail-body"><p><strong>Learning goal:</strong> ${esc(unit.childGoal||unit.learn)}</p>${focus.length?list(focus):`<p>${esc(unit.desc)}</p>`}<h3>Steps to use</h3><p><strong>${esc(unit.routine)}</strong></p></div></details>
<details class="curriculum-topic-section"><summary><strong>See it, then try it</strong></summary><div class="curriculum-detail-body"><h3>${esc(unit.model_title)}</h3>${unit.model_html||""}<article class="curriculum-worked-example"><h3>Worked example</h3><p>${esc(unit.solved_example||unit.modelNote||unit.learn)}</p></article><h3>${esc(unit.apply_title)}</h3>${unit.apply_html||""}</div></details>
<details class="curriculum-topic-section"><summary><strong>Try these</strong></summary><div class="curriculum-detail-body"><ol>${activities}</ol></div></details>
<details class="curriculum-topic-section"><summary><strong>Common mix-ups</strong></summary><div class="curriculum-detail-body"><ul>${mistakes}</ul></div></details>
<details class="curriculum-topic-section"><summary><strong>Check your understanding</strong></summary><div class="curriculum-detail-body"><h3>Quick checks</h3>${quick}<h3>I am ready when I can</h3>${mastery}</div></details>
${curriculum}${equivalents}
<details class="curriculum-topic-section"><summary><strong>Resources</strong></summary><div class="curriculum-detail-body"><div class="curriculum-link-row"><a class="curriculum-button primary" href="teacher-slides/">Open Classroom View</a><a class="curriculum-button" href="/quiz/year-2/english/${code.toLowerCase()}/worksheet/">Printable Worksheet</a><a class="curriculum-button" href="/quiz/year-2/english/${code.toLowerCase()}/practice/">40-question Practice</a><a class="curriculum-button" href="/quiz/year-2/english/${code.toLowerCase()}/test/">Test</a></div></div></details>
</div><aside class="curriculum-sidebar"><section class="curriculum-panel"><h2>Classroom display</h2><p>Open the fixed SkillrHub display for whole-class modelling and guided practice.</p><a class="curriculum-button primary" href="teacher-slides/">Classroom View</a></section><section class="curriculum-panel"><h2>Curriculum code</h2><p><strong>${code}</strong><br>Year 2 English</p></section></aside></main>`;
}
function replacePage(code,unit,topicDir){
  const file=path.join(topicDir,"index.html"); let html=read(file); const body=topicBody(code,unit,html);
  html=html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(code)} ${esc(unit.title)} | Year 2 English</title>`)
    .replace(/<meta name="description"[^>]*>/i,`<meta name="description" content="${esc(code)} Year 2 English: ${esc(unit.childGoal||unit.desc)} Includes a topic guide, classroom display, printable worksheet and 40-question practice.">`)
    .replace(/<header class="curriculum-hero">[\s\S]*?<\/header>\s*<main class="curriculum-layout">[\s\S]*?<\/main>/i,body)
    .replace(/<script\b[^>]*src=["'][^"']*year2-english-render\.js[^"']*["'][^>]*><\/script>\s*/gi,"");
  write(file,html);
}
function wrap(text,width=58,max=5){const words=strip(text).split(" ").filter(Boolean),lines=[];let line="";for(const word of words){const c=line?`${line} ${word}`:word;if(c.length>width&&line){lines.push(line);line=word;}else line=c;}if(line)lines.push(line);if(lines.length>max){const r=lines.slice(0,max);r[max-1]=`${r[max-1].replace(/[.…]+$/,"")}…`;return r;}return lines;}
function svgText(lines,x,y,size,gap,weight="400",fill="#203047"){return lines.map((line,index)=>`<text x="${x}" y="${y+index*gap}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}">${esc(line)}</text>`).join("");}
function slideSvg(code,title,kicker,body,index,total){const titleLines=wrap(title,43,2),bodyLines=wrap(body,70,10);return `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900" role="img" aria-labelledby="t d"><title id="t">${esc(code)} — ${esc(title)}</title><desc id="d">${esc(body)}</desc><rect width="1600" height="900" fill="#f8fafc"/><g opacity=".05" fill="#2457d6" font-family="Arial" font-size="34" font-weight="700"><text x="120" y="310" transform="rotate(-18 120 310)">SkillrHub • skillrhub.com</text><text x="720" y="590" transform="rotate(-18 720 590)">SkillrHub • skillrhub.com</text></g><rect width="1600" height="98" fill="#173968"/><text x="88" y="63" fill="#fff" font-family="Arial" font-size="31" font-weight="700">SkillrHub • Year 2 English</text><text x="1485" y="63" text-anchor="end" fill="#fff" font-family="Arial" font-size="25">${index} / ${total}</text><text x="92" y="150" fill="#2457d6" font-family="Arial" font-size="23" font-weight="700">${esc(kicker)}</text>${svgText(titleLines,92,215,47,55,"700","#173968")}<rect x="92" y="345" width="1416" height="405" rx="26" fill="#fff" stroke="#d8e2ef" stroke-width="3"/>${svgText(bodyLines,135,405,30,42,"400","#203047")}<rect y="835" width="1600" height="65" fill="#173968"/><text x="70" y="877" fill="#fff" font-family="Arial" font-size="26" font-weight="700">${esc(code)} • Classroom View • skillrhub.com</text></svg>\n`;}
function viewer(code,unit,count){const figures=Array.from({length:count},(_,i)=>`<figure class="fixed-slide-viewer__slide" data-slide${i?" hidden":""}><img src="slide-${String(i+1).padStart(2,"0")}.svg" alt="${code} classroom slide ${i+1} of ${count}" draggable="false"></figure>`).join("");return `<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${esc(code)} ${esc(unit.title)} Classroom View | SkillrHub</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/assets/teacher-slide-viewer.css?v=1"></head><body oncontextmenu="return false"><nav class="main-nav"><a href="../">Topic Guide</a></nav><main style="padding:clamp(12px,3vw,32px)"><h1>${esc(unit.title)}</h1><p>${esc(code)} • Year 2 English • fixed classroom display</p><section class="fixed-slide-viewer" data-fixed-slide-viewer tabindex="0"><div class="fixed-slide-viewer__stage">${figures}</div><div class="fixed-slide-viewer__controls"><button type="button" data-slide-previous>Previous</button><span class="fixed-slide-viewer__counter" data-slide-counter>1 / ${count}</span><button type="button" data-slide-next>Next</button><button type="button" data-slide-fullscreen>Fullscreen</button></div></section></main><script src="/assets/teacher-slide-viewer.js?v=1"></script><script>document.addEventListener('dragstart',e=>e.preventDefault());</script></body></html>\n`;}
function makeSlides(code,unit,topicDir){const dir=path.join(topicDir,"teacher-slides"),full=path.join(ROOT,dir);fs.mkdirSync(full,{recursive:true});for(const file of fs.readdirSync(full)) if(/^slide-\d+\.(?:png|jpe?g|webp|svg)$/i.test(file)) fs.rmSync(path.join(full,file));const focus=(unit.studentFacingFocus||[]).join(" "),activities=(unit.activities||[]).map((a)=>`${a.title}: ${a.text}`).join(" "),mistakes=(unit.mistakes||[]).map(([name,fix])=>`${name}. Try instead: ${fix}`).join(" "),checks=(unit.quick||[]).join(" ");const slides=[[unit.childGoal||unit.learn,"Learning goal",focus||unit.desc],[unit.model_title,"See it",strip(unit.model_html)],["Worked example","Think it through",unit.solved_example||unit.learn],[unit.apply_title,"Apply the idea",strip(unit.apply_html)],["Try these","Guided and independent practice",activities],["Common mix-ups and quick check","Check your understanding",`${mistakes} ${checks}`]];slides.forEach(([title,kicker,body],index)=>write(path.join(dir,`slide-${String(index+1).padStart(2,"0")}.svg`),slideSvg(code,title,kicker,body,index+1,slides.length)));write(path.join(dir,"index.html"),viewer(code,unit,slides.length));}
for(const code of codes){const unit=units[code],topicDir=findTopicDir(code);replacePage(code,unit,topicDir);makeSlides(code,unit,topicDir);}console.log(`Rebuilt ${codes.length} static Year 2 English topic guides and fixed classroom displays.`);
