import fs from 'node:fs';import path from 'node:path';
import A from './year10_english_actual/ac9e10la01_a.mjs';import B from './year10_english_actual/ac9e10la01_b.mjs';import C from './year10_english_actual/ac9e10la01_c.mjs';import D from './year10_english_actual/ac9e10la01_d.mjs';
const root=process.cwd(),code='AC9E10LA01',low=code.toLowerCase(),rows=[...A,...B,...C,...D];
const ps=rows.filter(r=>r[0]==='p'),ts=rows.filter(r=>r[0]==='t');if(ps.length!==40||ts.length!==16)throw new Error(`count ${ps.length}/${ts.length}`);
const make=(r,i)=>{const [bank,stage,q,opts,correct,summary,hint]=r;return {id:`${low}-${bank}-${String(i+1).padStart(3,'0')}`,curriculum_code:code,year_level:'Year 10',subject:'english',bank:bank==='p'?'practice':'test',skill:'language alignment and audience positioning',question:q,audio_prompt:q,visual:{type:'none',alt_text:''},answers:opts.map((text,j)=>({text,is_correct:j===correct})),correct_index:correct,explanation:{summary,hint},...(bank==='p'?{stage}:{}),difficulty:bank==='p'?(i<10?1:i<30?2:3):3,difficulty_tier:bank==='p'?stage:'independent',sequence_priority:i+1,quality_schema:'skillr-actual-v6'};};
const practice=ps.map(make),test=ts.map(make),all=[...practice,...test];
const norm=s=>s.toLowerCase().replace(/[“”‘’'".,!?;:—–()-]/g,' ').replace(/\s+/g,' ').trim();if(new Set(all.map(x=>norm(x.question))).size!==56)throw new Error('duplicate stems');if(test.some(t=>practice.some(p=>norm(p.question)===norm(t.question))))throw new Error('practice/test overlap');
for(const x of all){if(x.answers.length!==4||x.answers.filter(a=>a.is_correct).length!==1||!x.answers[x.correct_index].is_correct)throw new Error(`answer integrity ${x.id}`);if(/A Year 10 student|curriculum descriptor|teacher|rubric|learning intention|success criteria/i.test(x.question))throw new Error(`banned wording ${x.id}`);}
fs.writeFileSync(path.join(root,'assets','assessment-banks','year10','english',`${low}.json`),JSON.stringify(all,null,2)+'\n');
const live=x=>({id:x.id,curriculumCode:code,bank:x.bank,skill:x.skill,printable:true,type:'single',question:x.question,audioPrompt:x.question,visual:'',visualHtml:'',visualMeta:{type:'none',alt_text:''},answers:x.answers.map(a=>a.text),correct:x.correct_index,explanation:`${x.explanation.summary}\nHint: ${x.explanation.hint}`,structuredExplanation:x.explanation,...(x.stage?{stage:x.stage}:{}),difficulty:x.difficulty,difficultyTier:x.difficulty_tier,sequencePriority:x.sequence_priority,qualitySchema:x.quality_schema});
const ptxt='"use strict";\nwindow.skillrPracticeQuestions = '+JSON.stringify(practice.map(live),null,2)+';\n';const ttxt='"use strict";\nwindow.skillrTestQuestions = '+JSON.stringify(test.map(live),null,2)+';\n';const base=path.join(root,'quiz','year-10','english',low);fs.writeFileSync(path.join(base,'practice','questions.js'),ptxt);fs.writeFileSync(path.join(base,'practice','practice-questions.js'),ptxt);fs.writeFileSync(path.join(base,'test','questions.js'),ttxt);console.log('AC9E10LA01 PASS: 40 authored practice / 16 fresh test; live banks updated; Classroom View untouched.');