import fs from 'node:fs';
import path from 'node:path';

// One-off production authoring pass for AC9E10LA01.
// Every prompt, option set, answer and explanation below is authored for this bank.
const ROOT=process.cwd();
const code='AC9E10LA01';
const skill='language that aligns, includes, distances and positions audiences';
const P=[
['recognise','A Canberra youth climate speech begins, “Of course, none of us wants another summer of smoke.” What does “of course” mainly do?',['It treats agreement as already shared','It gives a precise source','It introduces an opposing view','It marks a change of speaker'],0,'“Of course” presents the claim as something reasonable people already accept, encouraging listeners to align with the speaker.','Notice whether the wording invites debate or assumes common ground.'],
['recognise','In a school captain speech, the speaker says, “We can make lunchtime clubs easier to join.” Which word most directly involves the audience with the speaker?',['can','lunchtime','we','easier'],2,'“We” places speaker and audience inside the same group and frames the action as shared.','Look for the pronoun that joins people together.'],
['recognise','A council flyer says, “You deserve a safer walk home from the station.” Which feature most directly addresses the reader?',['second-person pronoun','technical vocabulary','passive voice','quotation'],0,'The second-person pronoun “you” addresses the reader directly and makes the issue personal.','Which word points straight at the person reading?'],
['recognise','During a radio interview about regional sport, a guest says, “As every local knows, Saturday footy is more than a game.” Which phrase signals a shared assumption?',['Saturday footy','more than a game','As every local knows','during the interview'],2,'“As every local knows” assumes a common local understanding instead of proving the point from scratch.','Find the phrase that presumes the audience already agrees or knows something.'],
['recognise','A campaign poster reads, “Real Australians look out for their neighbours.” What is the main positioning move?',['It defines belonging through a claimed shared value','It supplies statistical evidence','It avoids making any judgement','It explains a historical cause'],0,'The poster links being a “real Australian” with one approved behaviour, pressuring readers to accept that value as part of belonging.','Ask what identity the sentence attaches to the preferred behaviour.'],
['recognise','A student editorial says, “People like us do not leave teammates behind.” Which wording creates an in-group?',['leave teammates','do not','People like us','behind'],2,'“People like us” divides people into an implied in-group and others, using belonging to support the claim.','Look for words that classify the writer and reader as the same kind of people.'],
['recognise','An online safety video says, “You already know how quickly one screenshot can travel.” What does “already know” assume?',['The viewer shares the speaker’s knowledge','The viewer has read a cited report','The viewer disagrees with the speaker','The viewer needs a definition of screenshot'],0,'“Already know” treats the point as familiar shared knowledge and reduces distance between speaker and viewer.','Is the speaker teaching new information or presuming familiarity?'],
['recognise','At a community forum, a speaker says, “We renters are the ones living with these decisions.” How is “we renters” functioning?',['It builds solidarity around a shared group identity','It removes the speaker from the issue','It makes the statement completely neutral','It identifies an expert source'],0,'“We renters” names a shared identity and positions the speaker alongside the group affected by the decisions.','Track who is included inside “we”.'],
['recognise','A road-safety ad says, “Any responsible driver would slow down here.” Which phrase pressures the audience to align?',['slow down','would','here','Any responsible driver'],3,'“Any responsible driver” ties agreement to a desirable identity, making disagreement risk seeming irresponsible.','Which words attach the preferred action to a positive identity?'],
['recognise','A principal writes, “Some families may prefer the old timetable, but our community has always adapted when students benefit.” Which phrase appeals most clearly to shared history?',['Some families','may prefer','our community has always adapted','students benefit'],2,'“Our community has always adapted” invokes a collective past to make the proposed response seem consistent with group identity.','Look for the wording that turns past behaviour into a shared tradition.'],
['explain','A tourism ad says, “You know that feeling when the coast finally appears beyond the hills.” Why is “You know that feeling” effective for its intended audience?',['It invites readers to recognise a supposedly shared experience','It proves everyone has visited the coast','It creates distance through formal language','It replaces imagery with factual detail'],0,'The phrase assumes familiarity and invites readers to mentally join the experience, creating alignment without needing to prove that everyone shares it.','Think about how presumed familiarity can create connection.'],
['explain','A speech supporting a new skate park says, “We have all watched young people make do with the cracked court behind the shops.” How does “we have all watched” strengthen the argument?',['It frames the problem as common knowledge the audience shares','It identifies exactly who collected the evidence','It makes the claim less certain','It separates the speaker from local residents'],0,'The phrase treats the problem as collectively witnessed, making denial harder and positioning the audience beside the speaker.','What happens when a claim is presented as something everyone present has seen?'],
['explain','A charity appeal states, “Imagine if your postcode decided whether help arrived in time.” What is the effect of “your postcode”?',['It personalises an unequal situation for the reader','It turns the sentence into a technical definition','It removes emotion from the issue','It signals that only postal workers are addressed'],0,'Second-person “your” transfers an abstract inequality into the reader’s imagined life, increasing personal involvement.','Compare “a postcode” with “your postcode”.'],
['explain','A columnist writes, “Naturally, parents want schools to prepare students for real life.” Why can “Naturally” be persuasive?',['It presents the claim as self-evident and makes disagreement seem unusual','It gives the claim a numerical basis','It shows the writer is uncertain','It introduces a direct quotation'],0,'“Naturally” frames the proposition as obvious, encouraging readers to accept it before considering what “real life” should mean.','Ask whether the adverb opens the claim to debate or closes debate down.'],
['explain','At an awards night, the host says, “This is what our town does: we show up for one another.” How do “our” and “we” work together?',['They create a collective identity based on mutual support','They identify two opposing groups','They make the statement impersonal','They show the host is quoting a law'],0,'Both pronouns include speaker and audience in one community and connect membership with the value of helping others.','Follow the group created by the possessive and personal pronouns.'],
['explain','A sports brand ad declares, “If you call yourself a competitor, you finish the session.” Why might this wording influence an athlete?',['It links the desired action to an identity the audience may value','It gives a balanced account of recovery needs','It proves finishing is medically safe','It avoids placing pressure on the audience'],0,'The conditional wording makes “competitor” status depend on finishing, using identity and belonging as pressure.','What identity might the audience want to claim?'],
['explain','A local petition says, “No Canberran should accept a lake choked with litter.” How does “Canberran” contribute to persuasion?',['It connects the environmental stance with local identity','It supplies evidence about litter levels','It limits the claim to tourists','It removes judgement from the sentence'],0,'Naming the local identity suggests that caring about the lake is part of belonging to Canberra.','Consider why the writer names a community rather than simply saying “no one”.'],
['explain','A podcast host says, “As you can imagine, finding a rental after twenty rejected applications changes how you read every listing.” What does “As you can imagine” ask the listener to do?',['Adopt the speaker’s perspective by treating the experience as imaginable','Check a formal citation','Reject the speaker’s personal experience','Focus only on the number twenty'],0,'The phrase recruits the listener into the viewpoint by assuming they can picture the emotional effect.','What mental action is the listener invited to perform?'],
['explain','A graduation speech says, “We are not just the class that finished during disruptions; we are the class that kept turning up.” How does the repeated “we are” shape the audience?',['It builds a shared identity around resilience','It distances graduates from the speaker','It makes the speech sound like a scientific report','It attributes the claim to an outside authority'],0,'Repeated “we are” defines the group collectively and replaces a passive identity with a valued one based on persistence.','Notice how repetition can define who a group believes itself to be.'],
['explain','A commentary argues, “Surely we can agree that a public library should remain public.” Why is “Surely we can agree” more than a neutral introduction?',['It presumes consensus and makes dissent feel harder to voice','It signals that the writer has no position','It provides a counterexample','It turns the claim into a question of grammar'],0,'“Surely” plus inclusive “we” frames agreement as expected, applying social pressure before the claim is examined.','Consider what disagreeing would imply after the writer says agreement is expected.'],
['discriminate','Which sentence uses inclusive language without implying that disagreement makes someone a worse person?',['“Let’s compare both transport options before we decide.”','“Any decent person would support the rail plan.”','“Real locals know the rail plan is right.”','“Obviously, only selfish people oppose the rail plan.”'],0,'“Let’s compare” includes speaker and audience in a shared process without attaching moral worth or group authenticity to one conclusion.','Separate genuine inclusion from identity pressure.'],
['discriminate','Which statement best distinguishes “we” in the two sentences: “We surveyed 300 commuters” and “We all want streets where children are safe”?',['The first identifies the research team; the second invites the audience into a shared value','Both uses automatically include every reader','The first is emotional and the second is purely factual','There is no meaningful difference'],0,'Pronoun meaning depends on context: the first “we” refers to specific researchers, while the second is rhetorically inclusive.','Do not assume every “we” has the same referent.'],
['discriminate','A writer says, “Obviously, the festival should stay in the city centre.” Which analysis is strongest?',['“Obviously” presents the opinion as self-evident, potentially discouraging readers from questioning it','“Obviously” proves the festival location is correct','“Obviously” is persuasive only because it is a long word','“Obviously” has no effect because readers can ignore it'],0,'The adverb positions the claim as beyond reasonable dispute; that can align some readers while alienating others.','Analyse what the word asks readers to assume, not whether the claim is true.'],
['discriminate','Which sentence most clearly marginalises people outside a preferred group?',['“People who actually care about this town will vote yes.”','“Residents can vote after reading both proposals.”','“Our survey includes renters and homeowners.”','“You can submit feedback online or at the library.”'],0,'The first sentence makes caring about the town conditional on voting one way, casting opponents as less legitimate members of the community.','Look for a sentence that makes belonging depend on agreement.'],
['discriminate','A campaign uses the line “You’re one of us.” Which interpretation is most careful?',['It can create belonging, but its effect depends on who “us” includes and excludes','It is always inclusive because it contains “you”','It is always hostile because it contains a group pronoun','It has no positioning effect unless it contains statistics'],0,'The line invites the reader into a group, but analysis must also ask how that group is defined and who remains outside it.','Inclusive for whom? That question often matters.'],
['discriminate','Which revision reduces pressure from assumed agreement while keeping the claim?',['“The evidence suggests later trading hours may benefit some businesses.”','“Of course later trading hours benefit everyone.”','“As any sensible owner knows, later trading is essential.”','“We all understand that later trading is the only answer.”'],0,'The revision states a qualified evidence-based claim instead of treating agreement as obvious or tying it to intelligence.','Choose wording that leaves room for evaluation.'],
['discriminate','A speaker says, “As Australians, we give everyone a fair go.” Which analysis avoids overclaiming?',['The phrase appeals to a familiar national value to encourage alignment, though audiences may interpret that value differently','The sentence proves all Australians behave fairly','The phrase has exactly the same effect on every Australian listener','The national reference is irrelevant because no statistic follows'],0,'The statement invokes a cultural value as shared identity; a careful analysis recognises that audiences can accept, question or redefine that appeal.','Analyse the positioning move without pretending all audiences respond identically.'],
['discriminate','Which sentence uses direct address mainly to create responsibility rather than friendliness?',['“Your decision tonight will determine whether the shelter opens this winter.”','“You’ll love the new mural near the oval.”','“You know that warm feeling after a good meal.”','“You and I have laughed about this before.”'],0,'“Your decision” assigns the audience a consequential role, making responsibility the main effect of direct address.','Ask what the “you” is being made responsible for.'],
['discriminate','A reviewer writes, “We all know sequels are usually disappointing.” What is the weakness in saying this simply “creates community”?',['The phrase also suppresses difference by presenting a debatable opinion as shared knowledge','Community language can never be persuasive','The sentence contains no pronouns','The claim is objective because it uses “we”'],0,'The inclusive pronoun may create solidarity, but “all know” also pressures readers to accept a contestable judgement.','Strong analysis can identify connection and pressure at the same time.'],
['discriminate','Which analysis best explains the difference between “Some residents oppose the change” and “Even our neighbours oppose the change”?',['The second invokes closeness and shared identity, making the opposition feel more socially significant','The second is more accurate because it says “our”','The first is emotional while the second contains no positioning','Both are identical because they report opposition'],0,'“Our neighbours” creates a relationship with the group and “even” marks their opposition as noteworthy, adding positioning absent from the neutral description.','Look beyond the event reported to how the people are framed.'],
['apply','You are editing a student speech arguing for shaded bus stops. Which opening builds shared concern without claiming everyone already agrees?',['“Many of us have waited through a 35-degree afternoon; let’s look at what shade could change.”','“Obviously, every sensible person supports shaded stops.”','“Real Canberrans demand shade immediately.”','“You would have to be careless to oppose this plan.”'],0,'The first opening uses a plausible shared experience and inclusive invitation while leaving the proposal open to consideration.','Aim for connection without turning disagreement into a character flaw.'],
['apply','A community group wants renters and homeowners to feel equally included in a housing forum. Which line is most suitable?',['“Whether you rent, own or live with family, your experience of housing belongs in this conversation.”','“Homeowners like us know what the suburb needs.”','“Responsible residents protect property values first.”','“Obviously, renters understand the problem best.”'],0,'The first line explicitly names different housing situations and gives each a legitimate place in the discussion.','Choose language that widens rather than narrows membership.'],
['apply','A health campaign wants teenagers to question risky driving without shaming them. Which wording best fits?',['“Before you get in, ask whether the driver is ready to get everyone home safely.”','“Only idiots get into a car with a tired driver.”','“Good teenagers never make risky choices.”','“Everyone knows smart people refuse every late-night lift.”'],0,'The first line uses direct address and a practical question to create agency without defining people by a mistake.','Look for responsibility without insult or identity policing.'],
['apply','A student is revising “We all know phones destroy concentration” for a balanced persuasive article. Which revision is strongest?',['“Many students