import fs from 'node:fs';
import path from 'node:path';
const ROOT=path.resolve(import.meta.dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'assets','year8-10-english-curriculum-focus.json'),'utf8'));
const CODES=manifest.years['8'];
const DIR=path.join(ROOT,'assets','assessment-banks','year8','english');
const QUIZ=path.join(ROOT,'quiz','year-8','english');
const pctx=['a school podcast script','a community-news article','a library book-club discussion','a student council speech','a science-expo explanation','a museum caption','a local-sport profile','a school newsletter','a youth radio segment','a bushwalking safety page','a review of an Australian novel','a documentary storyboard','a class debate','a community-festival webpage','a wildlife-centre brochure','a historical display','a persuasive letter to council','a school assembly address','a digital magazine feature','a public-transport campaign','a theatre-program note','a coastal-care poster','a short-story workshop','a media-literacy lesson','a local-history podcast','a school website update','a graphic-novel discussion','a charity campaign','a sports-club announcement','a sustainability report','an exhibition review','a class anthology','a youth forum post','a tourism information page','a spoken presentation','a feature article','a film-review discussion','a community survey summary','a reading-journal entry','a school production program'];
const tctx=['a regional newspaper feature','an independent book review','a public-library exhibition','a council youth consultation','an environmental campaign video','a cultural-festival program','a national-park information panel','a radio interview transcript','a digital news explainer','a theatre review','a community-history website','a sports documentary','a literary magazine extract','a public-service announcement','an online museum exhibit','a youth conference presentation'];
const traps=['Do not stop at naming the feature. Ask what meaning it creates here.','Avoid absolute rules. The effect depends on the words, context, audience and purpose.','Check the whole example before choosing; one familiar term can be a distractor.','A strong answer connects a specific feature with a specific effect, not a vague judgement.','Do not assume that longer or more formal language is automatically stronger.','Separate what the text actually shows from what a reader merely prefers.'];
const misconceptions=['The feature has one fixed effect in every text, regardless of audience or purpose.','Naming the feature is enough; evidence from the text is unnecessary.','The most formal or complicated wording is automatically the best choice.','One isolated word proves the whole interpretation without needing context.','The feature changes only surface style and cannot shape meaning.','Any interpretation is equally strong even when it lacks supporting evidence.','Using more of the feature will always improve a text.','Audience and purpose do not matter once the feature has been identified.'];
const pStems={recognise:[(c,t)=>`In ${c}, which option is the clearest example of ${t}?`,(c,t)=>`Which choice in ${c} most clearly demonstrates ${t}?`,(c,t)=>`While reading ${c}, which option would you identify as ${t}?`,(c,t)=>`Which feature choice best matches ${t} in ${c}?`,(c,t)=>`For ${c}, which option gives the strongest evidence of ${t}?`,(c,t)=>`Which choice best represents ${t} in ${c}?`,(c,t)=>`A reader is looking for ${t} in ${c}. Which option should they choose?`,(c,t)=>`Which example from ${c} most accurately shows ${t}?`,(c,t)=>`Which option belongs under the heading “${t}” for ${c}?`,(c,t)=>`Which choice is the best match for ${t} in ${c}?`],explain:[(c,t)=>`In ${c}, which explanation best shows how ${t} shapes meaning?`,(c,t)=>`Which option best explains the effect of ${t} in ${c}?`,(c,t)=>`Which response connects ${t} to audience or purpose in ${c}?`,(c,t)=>`A reader is explaining ${t} in ${c}. Which comment is most precise?`,(c,t)=>`Which explanation goes beyond naming ${t} and shows what it does in ${c}?`,(c,t)=>`How does ${t} matter in ${c}? Choose the strongest explanation.`,(c,t)=>`Which statement best accounts for the effect of ${t} in ${c}?`,(c,t)=>`Which explanation of ${t} is best supported by ${c}?`,(c,t)=>`Which response most clearly links ${t} with meaning in ${c}?`,(c,t)=>`For ${c}, which statement gives the most useful explanation of ${t}?`],discriminate:[(c,t)=>`Which interpretation of ${t} in ${c} is the most careful and accurate?`,(c,t)=>`Several claims are made about ${t} in ${c}. Which one avoids an overgeneralisation?`,(c,t)=>`Which response distinguishes a sound analysis of ${t} from a superficial one in ${c}?`,(c,t)=>`Which statement about ${t} in ${c} can actually be supported?`,(c,t)=>`Which option avoids confusing the feature with its effect when discussing ${t} in ${c}?`,(c,t)=>`Which reading of ${t} in ${c} uses context rather than assumption?`,(c,t)=>`Which response gives the strongest judgement about ${t} in ${c}?`,(c,t)=>`Which claim about ${t} in ${c} is precise enough to defend?`,(c,t)=>`Which option avoids treating ${t} as a rule that works identically everywhere?`,(c,t)=>`Which interpretation of ${t} best fits the evidence in ${c}?`],apply:[(c,t)=>`You are revising ${c}. Which choice applies ${t} most effectively?`,(c,t)=>`Which change would make the strongest use of ${t} in ${c}?`,(c,t)=>`To improve ${c}, which option best applies ${t}?`,(c,t)=>`Which choice uses ${t} deliberately in ${c}?`,(c,t)=>`Which revision to ${c} shows the most purposeful use of ${t}?`,(c,t)=>`Which option transfers an understanding of ${t} to ${c} successfully?`,(c,t)=>`For ${c}, which choice uses ${t} in a way that suits audience and purpose?`,(c,t)=>`Which decision would strengthen ${c} by applying ${t} rather than just naming it?`,(c,t)=>`Which option is the best practical use of ${t} in ${c}?`,(c,t)=>`A writer is improving ${c}. Which choice shows confident control of ${t}?`]};
const tStems=[(c,t)=>`In ${c}, which interpretation of ${t} is best supported?`,(c,t)=>`Which choice applies an accurate understanding of ${t} to ${c}?`,(c,t)=>`Which explanation of ${t} best fits ${c}?`,(c,t)=>`Which option gives the strongest analysis of ${t} in ${c}?`,(c,t)=>`Which choice would use ${t} most effectively in ${c}?`,(c,t)=>`Which statement about ${t} can be defended in ${c}?`,(c,t)=>`Which response shows the most precise understanding of ${t} in ${c}?`,(c,t)=>`Which revision would best control ${t} in ${c}?`];
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
function coreHint(x){let h=norm(x.explanation?.hint);for(const t of traps)if(h.startsWith(t)){h=norm(h.slice(t.length));break;}return h||norm(x.explanation?.summary).replace(/ This is the strongest choice because[\s\S]*$/,'');}
function toQuiz(items,code,bank){const data=items.map(x=>({id:x.id,curriculumCode:code,bank:x.bank,skill:x.skill,printable:true,type:'single',question:x.question,audioPrompt:x.audio_prompt,visual:'',visualHtml:'',visualMeta:x.visual,answers:x.answers.map(a=>a.text),correct:x.correct_index,explanation:x.explanation.summary,hint:x.explanation.hint,stage:x.stage,difficulty:x.difficulty,difficultyTier:x.difficulty_tier,sequencePriority:x.sequence_priority}));return `"use strict";\nwindow.${bank==='practice'?'skillrPracticeQuestions':'skillrTestQuestions'} = ${JSON.stringify(data,null,2)};\n`;}
for(const code of CODES){const file=path.join(DIR,`${code.toLowerCase()}.json`);const items=JSON.parse(fs.readFileSync(file,'utf8'));const concepts=[...new Set(items.map(coreHint).filter(x=>x.length>20))];for(const x of items){const i=Number(x.id.match(/(\d+)$/)?.[1]||1)-1;const topic=x.skill;const bank=x.bank;const stage=x.stage;const ctx=bank==='practice'?pctx[i]:tctx[i];x.question=bank==='practice'?pStems[stage][i%10](ctx,topic):tStems[i%8](ctx,topic);x.audio_prompt=x.question;const correct=coreHint(x);const wrong=[];for(let j=1;j<concepts.length&&wrong.length<3;j++){const c=concepts[(concepts.indexOf(correct)+j+Math.max(0,i))%concepts.length];if(c&&c!==correct&&!wrong.includes(c))wrong.push(c);}for(let j=0;wrong.length<3;j++){const m=misconceptions[(i+j)%misconceptions.length];if(!wrong.includes(m)&&m!==correct)wrong.push(m);}const ci=(i+(bank==='test'?1:0))%4;x.answers=wrong.slice(0,3).map(text=>({text,is_correct:false}));x.answers.splice(ci,0,{text:correct,is_correct:true});x.correct_index=ci;x.explanation.summary=`${correct} This answer works because it connects the language or text choice with the meaning it creates in context.`;x.explanation.hint=`${traps[i%traps.length]} ${correct}`;}
fs.writeFileSync(file,JSON.stringify(items,null,2)+'\n');const p=items.filter(x=>x.bank==='practice'),t=items.filter(x=>x.bank==='test');const q=path.join(QUIZ,code.toLowerCase());fs.writeFileSync(path.join(q,'practice','questions.js'),toQuiz(p,code,'practice'));if(fs.existsSync(path.join(q,'practice','practice-questions.js')))fs.writeFileSync(path.join(q,'practice','practice-questions.js'),toQuiz(p,code,'practice'));fs.writeFileSync(path.join(q,'test','questions.js'),toQuiz(t,code,'test'));}
console.log(`Year 8 English refinement complete for ${CODES.length} codes.`);
