const assert = require('node:assert/strict');
const {filterProducts, paginate} = require('../assets/print-and-go-search.js');
const products = require('../data/print-and-go-products.json');
assert.equal(filterProducts(products, 'AC9m3m04').length, 6);
assert.equal(filterProducts(products, 'YEAR 3 clocks').length, 6);
assert.equal(filterProducts(products, 'time', {year: 4}).length, 0);
assert.equal(filterProducts(products, 'time', {year: 3, subject: 'maths'}).length, 9);
assert.equal(filterProducts(products, 'time', {subject: 'english'}).length, 0);
assert.equal(filterProducts(products, 'fractions').length, 4);
assert.equal(filterProducts(products, 'Year 4 equivalent fractions').length, 1);
assert.equal(filterProducts(products, 'Year 5 decimals').length, 1);
assert.equal(filterProducts(products, '  ').length, products.filter(p => p.available).length);
const slide = {...products.find(product => product.id === 'year-3-time-practice'), resourceType: 'teaching-slides'};
assert.equal(filterProducts([slide], 'time').length, 1);
assert.equal(filterProducts([slide], 'time', {resourceType: 'teaching-slides'}).length, 1);
assert.equal(filterProducts(products, 'time', {resourceType: 'teaching-slides'}).length, 4);
assert.equal(filterProducts(products, 'sample', {resourceType: 'teaching-slides'}).length, 1);
assert.equal(products.length, 24);
assert.equal(new Set(products.map(product => product.tptUrl)).size, 24);
const fractionsSlides = products.find(product => product.id === 'year-3-fractions-slides');
const fractionsBundle = products.find(product => product.id === 'year-3-fractions-bundle');
assert.equal(fractionsSlides.price, '6.99');
assert.equal(fractionsSlides.curriculumCodes.join(','), 'AC9M3N02');
assert.match(fractionsSlides.tptUrl, /17594445$/);
assert.equal(fractionsBundle.price, '8.38');
assert.equal(fractionsBundle.listPrice, '10.48');
assert.match(fractionsBundle.tptUrl, /17594471$/);
assert.equal(products.filter(product => product.year === 1).length, 7);
assert.equal(filterProducts([{...products[0], available: false}], '').length, 0);
const many = Array.from({length: 1001}, (_, id) => ({...products[0], id}));
assert.equal(paginate(many).items.length, 24);
assert.equal(paginate(many, 2).items[0].id, 24);
assert.equal(paginate(many, 99).page, 42);
assert.equal(paginate(many, 42).items.length, 17);
assert.equal(paginate([], 2).page, 1);
console.log('Print catalogue search and pagination tests passed.');
