#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const codes=[...Array.from({length:7},(_,i)=>`AC9S9U0${i+1}`),...Array.from({length:4},(_,i)=>`AC9S9H0${i+1}`),...Array.from({length:8},(_,i)=>`AC9S9I0${i+1}`)];
const problems=[];
function load(file,kind){if(!fs.existsSync(file)){problems.push(`${file}: missing`);return[];}const src=fs.readFileSync(file,'utf8');const context={window:{}};vm.createContext(context);try{vm.runInContext(src,context,{filename:file});}catch(e){problems.push(`${file}: parse/runtime error ${e.message}`);return[];}return kind==='practice'?context.window.skillrPracticeQuestions||context.window.quizQuestions||[]:context.window.skillrTestQuestions||context.window.skillrExamQuestions||context.window.quizQuestions||[];}
function sectionRank(s){const m=String(s||'').match(/Section\s+([A-Z])/i);return m?m[1].toUpperCase().charCodeAt(0)-64:99;}
let practiceTotal=0,testTotal=0;
for(const code of codes){const slug=code.toLowerCase();const root=path.join('quiz','year-9','science',slug);const practice=load(path.join(root,'practice','questions.js'),'practice');const test=load(path.join(root,'test','questions.js'),'test');practiceTotal+=practice.length;testTotal+=test.length;if(practice.length!==24)problems.push(`${code}: Practice has ${practice.length}, expected 24`);if(test.length!==16)problems.push(`${code}: Test has ${test.length}, expected 16`);const all=[...practice,...test];const ids=new Set(),questions=new Set();let prevSource=-Infinity,prevSection=0;for(const [i,q] of all.entries()){if(q.curriculumCode!==code)problems.push(`${code} item ${i+1}: curriculumCode mismatch ${q.curriculumCode}`);if(ids.has(q.id))problems.push(`${code}: duplicate id ${q.id}`);ids.add(q.id);const norm=String(q.question||'').toLowerCase().replace(/\s+/g,' ').trim();if(!norm)problems.push(`${code} item ${i+1}: empty question`);if(questions.has(norm))problems.push(`${code}: duplicate question stem ${q.question}`);questions.add(norm);if(!Array.isArray(q.answers)||q.answers.length<3)problems.push(`${q.id}: insufficient answers`);if(!Number.isInteger(q.correct)||q.correct<0||q.correct>=q.answers?.length)problems.push(`${q.id}: invalid correct answer index`);if(!q.structuredExplanation?.summary||!q.structuredExplanation?.hint)problems.push(`${q.id}: missing summary/hint`);if(!Number.isFinite(q.sourceNumber))problems.push(`${q.id}: missing numeric sourceNumber`);else if(q.sourceNumber<=prevSource)problems.push(`${q.id}: sourceNumber ${q.sourceNumber} is not progressively ordered after ${prevSource}`);else prevSource=q.sourceNumber;const rank=sectionRank(q.section);if(rank<prevSection)problems.push(`${q.id}: section ordering regresses from rank ${prevSection} to ${rank}`);prevSection=Math.max(prevSection,rank);}
 if(practice.at(-1)?.sourceNumber>=test.at(0)?.sourceNumber)problems.push(`${code}: Test source ordering does not progress after Practice`);
}
if(practiceTotal!==456)problems.push(`Year 9 Science Practice total ${practiceTotal}, expected 456`);if(testTotal!==304)problems.push(`Year 9 Science Test total ${testTotal}, expected 304`);
if(problems.length){console.error('Year 9 Science question-bank quality/progression FAILED:\n');problems.forEach(p=>console.error(`- ${p}`));process.exit(1);}console.log(`Year 9 Science question banks PASS: ${practiceTotal} Practice + ${testTotal} Test questions; 24/16 per code, unique stems, valid answers/explanations and progressive source/section ordering.`);
