const metadata = {
  code: 'AC9S6I01', year: 6, subject: 'Science', strand: 'Science inquiry',
  title: 'Investigable questions and reasoned predictions',
  descriptor: 'Pose investigable questions to identify patterns and test relationships, and make reasoned predictions.',
  learningIntention: 'We are learning to pose questions that evidence can answer and to predict outcomes using scientific reasons.',
  successCriteria: ['identify variables that can be changed, measured or observed','match a question to available materials, methods and data','write an if–then–because prediction supported by prior evidence'],
  boundary: 'Questions must be safe, ethical and answerable with available observations or measurements. A prediction is not a guess: its reason must use relevant knowledge or evidence.'
};

const q = (skill,stage,question,answers,correct,explanation,hint) => ({skill,stage,question,answers,correct,explanation,hint});
const practice = [
q('investigable questions','foundation','Which question can a class answer by timing four paper helicopters with blade lengths of 4, 6, 8 and 10 cm?',['Why are helicopters useful?','How does blade length affect a paper helicopter’s fall time?','Are paper helicopters beautiful?','Who invented the best helicopter?'],1,'Blade length can be changed and fall time measured.','Look for one change and one measurable outcome.'),
q('measurable outcomes','foundation','Which outcome makes the question “How does water temperature affect ___?” investigable with a stopwatch?',['how happy sugar feels','the time for 5 g of sugar to dissolve','whether warm water is nicer','the world’s best drink'],1,'Dissolving time is measurable with the listed tool.','What can a stopwatch record?'),
q('variables','foundation','A student changes ramp height and measures toy-car travel distance. What is changed?',['car travel distance','ramp height','ruler length','number written in the table'],1,'Ramp height is deliberately varied.','Find the factor selected by the investigator.'),
q('variables','foundation','In the ramp investigation, what is measured?',['ramp height','toy-car colour','travel distance','student height'],2,'Travel distance is the recorded outcome.','Find the result that responds to the change.'),
q('controls','core','To test how ramp height affects car distance, which factor should stay the same?',['ramp height','distance travelled','the toy car used','the final pattern'],2,'Using the same car prevents car design from confusing the relationship.','A control is kept constant.'),
q('question frames','foundation','Which question has the clearest scientific structure?',['What happens to plants?','How does daily light duration affect bean-plant height after 14 days?','Are plants good?','Can I grow something?'],1,'It names a changed variable, measurable outcome and time period.','Choose the most precise question.'),
q('vague questions','core','What is the best rewrite of “Does exercise help?” for a class investigation?',['Is exercise awesome?','How does two minutes of star jumps affect pulse rate measured immediately afterwards?','Why do athletes exist?','Does everybody like sport?'],1,'The rewrite defines the activity, duration and measurable response.','Replace “help” with an observable outcome.'),
q('materials match','core','Available materials are three soil types, identical pots, bean seeds, water and a ruler. Which question fits?',['How does soil type affect bean seedling height?','How does fertiliser brand affect flowers?','How does pot colour affect soil temperature?','How does music affect germination?'],0,'Only soil type and seedling height match the available materials and ruler.','Do not introduce an unavailable factor.'),
q('materials match','core','A method tests pure water and soapy water by counting equal-sized drops held on a coin. Which question can it answer?',['Does washing-up liquid clean coins?','How does soap in water affect the number of drops a coin can hold?','Does coin age affect mass?','Which soap smells best?'],1,'The method compares the two liquids and counts drops.','Match both the comparison and outcome.'),
q('unavailable comparison','core','The coin method never tests washing-up liquid by itself. Why can it not answer “Does washing-up liquid hold more drops than pure water?”',['The coin is too small','That comparison was not included','Drops cannot be counted','Water has no properties'],1,'Evidence cannot support a comparison that was never tested.','Check exactly which liquids were used.'),
q('pattern questions','core','Temperatures are recorded at the same place every hour from 8 am to 4 pm. Which question seeks a pattern?',['How does temperature change across the school day?','What causes all weather?','Is summer better?','Will every future day be identical?'],0,'The ordered measurements can reveal a time pattern.','Use the sequence already in the data.'),
q('relationship questions','core','Students measure leaf width and length for 30 leaves. Which question tests a relationship?',['Are leaves green?','Do longer leaves tend to be wider?','Why do trees look nice?','Which leaf is the luckiest?'],1,'Paired length and width data can show whether two measured features vary together.','Look for two variables in paired data.'),
q('yes-no wording','core','Which statement about yes/no questions is correct?',['Every yes/no question is unscientific','A yes/no question can be investigable if evidence can decide it','Yes/no questions never use measurements','Wording alone guarantees a fair test'],1,'Investigability depends on obtainable evidence, not grammar alone.','Judge the evidence needed.'),
q('unsafe questions','core','Which proposed class question should be rejected for safety?',['How does paper type affect absorption of 5 mL water?','How does tasting unknown mushrooms affect heart rate?','How does shade affect playground temperature?','How does salt amount affect ice-melting time?'],1,'Unknown mushrooms must not be tasted because they may be poisonous.','Safety limits what may be investigated.'),
q('ethical limits','core','Why is “How long can a pet fish survive without oxygen?” unsuitable?',['Time cannot be measured','It deliberately risks serious harm to an animal','Fish never need oxygen','Questions about animals have no answers'],1,'An investigation must not cause avoidable animal harm.','Ethical limits matter as well as measurability.'),
q('unmeasurable wording','core','What is missing from “Which bridge model is better?”',['a personal opinion','a defined measure such as maximum load','a famous bridge name','a second adjective'],1,'“Better” needs an agreed observable criterion.','Ask: better at what, measured how?'),
q('unmeasurable wording','core','Which revision makes “Which fabric is warmest?” measurable?',['Which fabric is cutest?','Which fabric keeps 100 mL of warm water at the highest temperature after 10 minutes?','Which fabric would I buy?','Why is wool warm?'],1,'The revision defines a system, measurement and time.','Operationally define “warmest”.'),
q('predictions','foundation','Which is a complete reasoned prediction?',['I guess the long blade wins','If blade length increases, then fall time will increase because larger blades experience more air resistance','The fall time will change because it changes','Helicopters are interesting'],1,'It states direction and connects it to relevant science.','Use if, then and a genuine because.'),
q('prediction reasons','core','Which “because” clause adds scientific reasoning rather than repeating the outcome?',['because it will dissolve faster','because warmer particles move faster and collide with the sugar more often','because my prediction says so','because warm water is warm'],1,'Particle motion provides a mechanism for the prediction.','A reason explains why.'),
q('directional predictions','core','Past trials show evaporation took 90, 70 and 52 minutes as fan speed increased. What is the best prediction for a higher speed?',['Evaporation will probably take less than 52 minutes because the pattern shows faster airflow shortens drying time','It must take exactly 51 minutes','It will take longer because fans are loud','No prediction can use past data'],0,'The prediction extends the observed direction without claiming an unjustified exact value.','Use the trend cautiously.'),
q('prediction limits','application','Three plant trials suggest more light increased growth. Why should a prediction for 24-hour light be cautious?',['Predictions are forbidden','The new light duration lies beyond the tested range and other limits may appear','Plants cannot be measured','Three results prove every possible case'],1,'Extrapolation beyond observed conditions is uncertain.','Is the new condition inside the evidence range?'),
q('multiple changed variables','core','A student changes both water temperature and sugar grain size. What is the main problem?',['There are too many measurements','The effect of each changed factor cannot be separated','Sugar cannot dissolve','Two students must conduct it'],1,'Two simultaneous changes confound the relationship.','Could you tell which change caused the outcome?'),
q('fair comparison','core','Which plan best tests detergent concentration against pepper movement?',['Change detergent concentration and plate size','Use equal water and pepper, change only concentration, and measure cleared-circle diameter','Use different pepper amounts and guess movement','Compare detergent today with no detergent next month outdoors'],1,'It changes one factor and measures a defined outcome while controlling key conditions.','Choose the clearest comparison.'),
q('controls','application','Why include a no-detergent plate in the pepper investigation?',['To make the table longer','To show what happens without the tested factor','To prove every prediction correct','To replace repeated trials'],1,'The control provides a baseline for comparison.','It reveals the normal outcome.'),
q('observations','foundation','Which is an observation rather than an explanation?',['The cleared circle measured 42 mm','Detergent reduced surface tension','The pepper moved because forces changed','Soap molecules caused the effect'],0,'A measured value reports what was detected without explaining cause.','Select the direct measurement.'),
q('data match','core','A table contains only seed germination counts for 10°C, 20°C and 30°C. Which question can it answer?',['How does temperature affect the number of seeds germinating?','How does temperature affect seedling height?','Which fertiliser produces flowers?','Why do all seeds die?'],0,'The table contains temperature and germination count, not height or fertiliser data.','Name only variables present.'),
q('data limits','application','A graph shows noise level and bird count at four parks. Which claim is supported?',['Noise definitely causes every difference in bird count','The data can show an association between noise level and bird count','Noise has no relationship to animals anywhere','All parks contain identical habitats'],1,'Observational paired data can identify a relationship but not prove causation.','Distinguish association from cause.'),
q('question-method alignment','application','A method weighs wet towels, hangs them in sun or shade for 30 minutes, then weighs them again. Which outcome belongs in the question?',['change in towel mass','colour of the clothesline','air pressure next year','student preference'],0,'Mass loss is the measured evidence for drying.','Use what is recorded before and after.'),
q('method limits','application','Students ask whether salt affects boiling point but their thermometer reads only to the nearest 10°C. What is the strongest concern?',['Salt is unavailable','The instrument may be too coarse to detect a small difference','Temperature is not measurable','Boiling is always unsafe at school'],1,'Low resolution may hide the relationship sought.','Can the tool detect the expected change?'),
q('available methods','application','Which question is answerable using a balance, four sponge types and equal 20 mL water samples?',['Which sponge absorbs the greatest mass of water?','Which sponge brand has the best advertisement?','Why was sponge invented?','How long will every sponge last?'],0,'The balance can compare water mass absorbed by the available sponges.','Match equipment to measurement.'),
q('operational definitions','application','For “Does music affect concentration?”, which outcome is most clearly defined?',['concentration feels good','number of correct symbol matches in two minutes','whether music is popular','student intelligence'],1,'A fixed task score and time operationally define concentration for this test.','Choose an observable proxy.'),
q('sampling patterns','application','A class wants a playground temperature pattern. Which sampling plan is most useful?',['One reading at one shaded spot','Readings at fixed times and named locations over several days','Ask one student which day felt hottest','Measure classroom light once'],1,'Repeated, systematic measurements can reveal time and location patterns.','Patterns need comparable observations.'),
q('reasoned prediction','application','Dark and light cans receive equal sunlight. Which prediction is best supported by knowledge of radiation?',['If colour is darker, then the water will warm faster because dark surfaces absorb more radiant energy','Both must finish at exactly 100°C','Light cans will disappear','Colour cannot relate to heating'],0,'The direction is linked to a relevant energy-transfer principle.','Connect the change to known science.'),
q('reasoned prediction','application','A wider parachute is compared with a narrower one of equal material and load. What is reasonable?',['The wider parachute will fall more slowly because its larger area produces more air resistance','The wider one will fall faster because it looks bigger','Both times must be identical','The result depends only on colour'],0,'Greater area is expected to increase drag and fall time.','Use area and air resistance.'),
q('prior evidence','application','Which evidence most usefully supports a prediction about a new paper towel?',['An advertisement says it is amazing','Earlier equal-volume tests of similar towels','Its packet uses blue ink','A friend prefers its name'],1,'Comparable prior measurements are relevant evidence.','Prefer evidence produced under similar conditions.'),
q('prediction versus result','core','When should a prediction be written?',['After changing the results','Before collecting the test results','Only if it is guaranteed correct','Instead of recording data'],1,'A prediction states the expected outcome before testing.','Predictions precede evidence collection.'),
q('incorrect predictions','core','An evidence-based prediction is not supported by results. What should students do?',['Delete the results','Report the result and reconsider the reasoning','Claim the prediction was correct','Repeat until one preferred result appears'],1,'Science uses results to revise ideas; predictions need not be correct.','Evidence has priority over expectation.'),
q('limitations','application','A question asks how rain affects soil erosion, but all trials use a single rainfall rate. What can the evidence show?',['How erosion changes with rainfall rate','Erosion under that one tested rate only','Every natural storm outcome','That rainfall never matters'],1,'No relationship with rate can be tested when rate is not varied.','What range was actually compared?'),
q('question refinement','application','Improve “What makes ice melt?” for the available lamps placed 10, 20 and 30 cm away.',['How does lamp distance affect the time for an equal ice cube to melt?','Does ice exist?','Why is light useful?','Which lamp is prettiest?'],0,'The revised question matches the changed distance and timed melting.','Use the actual distances and measured outcome.'),
q('question refinement','challenge','Students can record sound level but may not disturb nesting birds. Which safe question fits?',['How does recorded sound level vary with distance from a speaker in an empty oval?','How much noise makes birds abandon nests?','Can we touch every nest?','Which bird fears loud bangs most?'],0,'The oval investigation measures sound safely without disturbing wildlife.','Redesign around safety and available measurement.'),
q('cause and pattern','challenge','Monthly rainfall and frog-call counts rise together. Which new question could test a possible relationship without claiming cause?',['Is higher rainfall associated with more frog calls recorded each month?','Does rain force every frog to call?','Are frogs happier in rain?','Why is nature perfect?'],0,'“Associated with” matches observational pattern data and avoids premature causation.','Phrase an observable relationship.'),
q('binary outcomes','application','Which yes/no question is investigable as written?',['Is science fun?','Does adding 5 g of salt change the melting time of a 20 g ice cube under fixed conditions?','Is blue the best colour?','Are plants important?'],1,'The salt condition and measurable melting time make evidence capable of deciding the question.','Yes/no is acceptable when variables are clear.'),
q('scale limits','challenge','A class has a 30 cm ruler. Why is “How does a tree grow over 50 years?” not feasible for their lesson?',['Trees have no height','The required timescale and access exceed available methods','Rulers cannot measure length','Long questions are invalid'],1,'An investigable classroom question must fit available time and access.','Consider practical scale.'),
q('precision in questions','challenge','Which wording avoids an undefined comparison?',['Does compost make plants much better?','How does 0, 10 or 20 g of compost affect mean seedling height after 21 days?','Is compost magical?','What is the nicest plant?'],1,'Quantities, outcome and duration define the comparison precisely.','Look for amounts, measure and time.'),
q('evidence reasoning','challenge','A prior investigation found black paper reached 46°C and white paper 37°C in equal sunlight. Which new prediction uses that evidence responsibly?',['A grey surface may reach a temperature between black and white under the same conditions because its absorption is likely intermediate','Grey will be exactly 41.5°C everywhere','All grey objects are warmer than all black objects','Colour never affects heating'],0,'It makes a cautious directional prediction under matched conditions without false precision.','Avoid claiming an exact value beyond the data.'),
q('data adequacy','challenge','Students ask whether ball material affects bounce height, but record only the starting height. What is missing?',['the measured bounce height for each material','the students’ birthdays','a colour preference','the price of the ruler'],0,'The outcome needed to answer the question was not collected.','What dependent evidence is required?'),
q('confounding','challenge','Red seeds are placed in sun and blue seeds in shade; germination differs. Why is the relationship unclear?',['Germination cannot be counted','Seed colour/type and light condition both changed','Sunlight has no energy','The groups have names'],1,'Because two factors differ, the observed outcome cannot be attributed to either one alone.','Find both changes.'),
q('integrated judgement','challenge','Which proposal is most scientifically defensible for Year 6?',['Ask a measurable, safe question; change one factor; record the relevant outcome; predict using evidence and acknowledge limits','Choose an exciting question even if no data can answer it','Write the result first and design evidence to match','Change many factors to guarantee a dramatic pattern'],0,'Sound inquiry aligns question, variables, evidence, reasoning, safety and limitations.','Choose the complete evidence-led process.')
];

const test = [
q('materials match','foundation','A tray contains identical cups, sand, clay, equal water volumes and a timer. Which question is directly testable?',['How does soil type affect the time water takes to drain?','Which soil is most valuable?','How does fertiliser affect leaf colour?','Why are deserts dry?'],0,'The materials allow soil type to change and drainage time to be measured.','Match the question to every listed resource.'),
q('variables','core','Students vary torch distance and record solar-cell voltage. Which pair is correct?',['changed: voltage; measured: distance','changed: distance; measured: voltage','changed: torch colour; measured: time','changed: cell type; measured: mass'],1,'Torch distance is varied and voltage is the response recorded.','Separate the chosen factor from the outcome.'),
q('question quality','core','Which question is least investigable?',['How does fin area affect model-rocket flight distance?','Which rocket design is coolest?','How does load mass affect cart speed?','Does salt amount affect water conductivity?'],1,'“Coolest” is an undefined subjective judgement.','Find the outcome with no agreed measurement.'),
q('method alignment','core','A method measures candle mass before and after burning for 2, 4 and 6 minutes. What relationship can be tested?',['burning time and mass lost','wick colour and flame height','room size and oxygen level','candle cost and popularity'],0,'Only time and mass change are systematically recorded.','Use the variables in the method.'),
q('unsafe investigation','application','Which question requires redesign rather than classroom testing?',['How does water depth affect a cork’s floating height?','How does inhaling increasing amounts of smoke affect breathing rate?','How does string length affect pendulum period?','How does insulation type affect cooling?'],1,'Deliberately inhaling smoke is unsafe.','Reject intentional harmful exposure.'),
q('control factors','application','To ask how salt concentration affects egg floating height, what should remain constant?',['salt concentration','floating height','water volume and egg used','the predicted direction'],2,'Water volume and egg properties could otherwise affect the outcome.','Keep other influential conditions steady.'),
q('pattern inference','application','Shadow lengths at noon were 82, 65, 49 and 38 cm across four dates approaching summer. Which prediction is justified for the next similar date?',['The noon shadow may be shorter than 38 cm because the recorded pattern decreases','It must be exactly 37 cm','The shadow will vanish forever','Dates cannot be related to measurements'],0,'It extends the observed pattern cautiously rather than claiming certainty.','Use direction without false precision.'),
q('reasoned prediction','application','Which prediction best suits testing water flow through coarse and fine gravel?',['If gravel pieces are coarser, then water will pass through faster because larger gaps provide wider pathways','Coarse gravel wins because it is coarse','Fine gravel will be prettier','Both must take one second'],0,'The reason links particle spacing to flow rate.','Choose a mechanism, not repetition.'),
q('data limits','application','A class records battery life for one brand only. Can the data answer which of three brands lasts longest?',['Yes, because one number is enough','No, because the other brands were not tested','Yes, if the first brand is famous','No, because time cannot be measured'],1,'A comparative question needs evidence for every compared brand.','Check whether all groups appear.'),
q('operational measure','application','Which measurement best tests whether one shoe sole is “grippier” than another?',['the force needed to start each weighted shoe sliding on the same surface','the sole colour','the owner’s favourite shoe','the number of letters in the brand'],0,'Starting-force measurement defines grip in an observable, comparable way.','Turn “grippy” into measurable resistance.'),
q('association and cause','challenge','Towns with more streetlights also report fewer moths. What may students conclude from these data alone?',['Streetlights certainly caused the difference','There is an observed association, but other factors may explain it','Moths caused streetlights','Every town will follow the same pattern'],1,'Observational data identify association but do not isolate cause.','Avoid a causal claim from paired observations.'),
q('confounded plans','challenge','Plan A changes fan speed only. Plan B changes fan speed and towel size. Both measure drying time. Which judgement is correct?',['Plan B isolates fan speed better','Plan A better tests the fan-speed relationship','Both are equally valid because both use timers','Neither can measure time'],1,'Plan A avoids towel size confounding the effect of fan speed.','Which plan changes just the target factor?'),
q('prediction evidence','challenge','A student predicts magnets work better when cold “because I like winter”. What is the best improvement?',['Keep the outcome but replace the reason with relevant prior magnetic evidence or scientific knowledge','Add an exclamation mark','Call the guess a law','Remove all measurements'],0,'A reasoned prediction requires relevant evidence, not preference.','Repair the because clause.'),
q('question limits','challenge','A sensor records creek turbidity weekly for six weeks. Which question exceeds the evidence?',['How did turbidity vary across the six weeks?','Was turbidity associated with recorded rainfall during those weeks?','What will turbidity be on every day for the next century?','Which week had the highest turbidity?'],2,'Six weeks of data cannot justify exact daily forecasts for a century.','Compare the claim’s scale with the dataset.'),
q('question revision','challenge','Students ask, “Are lunch boxes good?” Which revision best fits drop-test equipment and a balance?',['How does lunch-box material affect the mass of modelling clay lost after a 1 m drop?','Which lunch box looks friendly?','Who buys lunch boxes?','Are drops good?'],0,'It defines material as the comparison and mass lost as the damage measure.','Use the equipment to define “good”.'),
q('inquiry synthesis','challenge','Which conclusion about questions and predictions is correct?',['Any answerable question is safe to test','A strong question aligns variables, methods and evidence; a strong prediction adds a justified expected relationship','Predictions must state exact numbers','A fair test can answer questions about unmeasured outcomes'],1,'Alignment and evidence-based reasoning are central, with safety and limitations also required.','Choose the statement that joins question, evidence and reasoning.')
];

const worksheet = [
{question:'Rewrite “What makes a paper plane good?” as an investigable question using flight distance as the outcome and wing length as the changed variable.',modelAnswer:'How does wing length affect the distance a paper plane travels when paper type, launch height and launch method stay the same?'},
{question:'A class has cups, equal soil samples, 50 mL water portions and a stopwatch. Write one question the materials can answer and identify both variables.',modelAnswer:'Question: How does soil type affect the time for 50 mL of water to drain? Changed variable: soil type. Measured variable: drainage time.'},
{question:'Explain why “Which drink tastes best?” is not suitable as a simple physical-science fair test, then make it measurable without asking anyone to taste.',modelAnswer:'“Best” is subjective and tasting may introduce safety issues. A measurable revision is: How does drink type affect pH measured with indicator paper?'},
{question:'Write an if–then–because prediction for blade length and paper-helicopter fall time.',modelAnswer:'If blade length increases, then fall time will increase because the larger blade area produces greater air resistance.'},
{question:'A plant investigation changes pot size and water amount together. Explain the problem and repair the question.',modelAnswer:'The effects cannot be separated because two variables change. Hold water amount constant and ask: How does pot size affect seedling height after 21 days?'},
{question:'Temperatures at 9 am, noon and 3 pm were measured for five days. Write (a) a pattern question and (b) a prediction that does not claim certainty.',modelAnswer:'(a) How does temperature typically change from 9 am to 3 pm? (b) If the same pattern continues, tomorrow’s noon temperature will probably exceed its 9 am temperature because that occurred on most recorded days.'},
{question:'A method compares pure and soapy water drops on a coin. Explain why it cannot answer whether washing-up liquid alone holds more drops than water.',modelAnswer:'Washing-up liquid alone was not one of the tested conditions, so the required comparison has no evidence.'},
{question:'Redesign the unsafe question “How much smoke can a person breathe before coughing?” as a safe investigation about airborne particles.',modelAnswer:'How does location affect the number of naturally settling ambient particles collected on identical covered sticky cards that are uncovered for the same time? Do not create dust or smoke; use passive collection, a sealed model or supplied data.'},
{question:'Define a measurable outcome for “Which insulation is best?” using identical jars of warm water.',modelAnswer:'Measure the temperature decrease of equal warm-water volumes in identical jars after 20 minutes; the best insulator has the smallest decrease.'},
{question:'Data show taller plants also had more leaves. State what can be concluded and one limitation.',modelAnswer:'The data show an association between height and leaf count. They do not prove that height causes leaves because age, light or other variables may affect both.'},
{question:'A ruler measures only whole centimetres, but expected growth over two days is 1–2 mm. Explain the limitation and improve the method.',modelAnswer:'The ruler lacks resolution to detect the expected change. Use a millimetre ruler or extend the duration while controlling other conditions.'},
{question:'Design a complete question and prediction for testing how salt amount affects ice melting time. Include quantities, controls and a scientific reason.',modelAnswer:'Question: How does 0, 2 or 4 g of salt affect the time for identical 20 g ice cubes to melt at the same room temperature? Prediction: If salt amount increases, melting time will decrease because dissolved salt lowers water’s freezing point. Keep cube mass, container and location constant.'}
];

const topic = {
sections:[
{heading:'What makes a question investigable?',content:'An investigable question can be answered with safe observations or measurements using available time, equipment and materials. A useful frame is: How does [variable changed] affect [variable measured] when [important controls] stay the same?'},
{heading:'Patterns and relationships',content:'A pattern describes how observations repeat or change across time, place or categories. A relationship asks how two measured variables vary together. A relationship in observational data is an association; it does not by itself prove that one variable caused the other.'},
{heading:'Match question, method and data',content:'Every named comparison must be tested and every claimed outcome must be measured. A method comparing pure and soapy water cannot answer a question about an untested liquid. A table of germination counts cannot answer a question about unrecorded seedling height.'},
{heading:'Make vague words measurable',content:'Replace words such as better, stronger, warmer or healthier with an operational measure: maximum load, force, temperature change or growth over a stated time. Include quantities and units when they make the test reproducible.'},
{heading:'Reasoned predictions',content:'Use: If [change], then [expected direction], because [relevant evidence or scientific mechanism]. The reason must explain the expected link rather than repeat the “then” clause. Predictions are written before results and may be revised when evidence disagrees.'},
{heading:'Fair comparisons and confounding',content:'Changing one target factor while keeping other influential conditions constant helps isolate a relationship. If two factors change together, the outcome is confounded: evidence cannot show which factor mattered.'},
{heading:'Safety, ethics and feasibility',content:'A measurable question may still be unsuitable if it risks harm, disturbs wildlife, requires an unrealistic timescale or exceeds available instruments. Redesign the question or use safe existing data rather than forcing a test.'},
{heading:'Limits and careful claims',content:'Instrument resolution, narrow ranges, small samples and missing comparison groups restrict what evidence can show. Predict cautiously beyond tested conditions and never turn an association into a causal claim without a design that isolates cause.'},
{heading:'Important questions and answers',content:'Q: Must an investigable question avoid yes/no wording? A: No; evidence and measurement matter more than grammar. Q: Must a prediction be correct? A: No; it must be justified before testing. Q: Can every scientific question be tested in class? A: No; safety, ethics, scale and equipment impose limits.'},
{heading:'Assessment and mastery',content:'Name the changed and measured variables, check that materials and data match the question, identify unavailable comparisons or confounders precisely, and justify predictions with an evidence-based mechanism. State what the evidence cannot establish.'}
],
vocabulary:[
{term:'investigable question',meaning:'a question answerable through safe, feasible observation or measurement'},
{term:'variable',meaning:'a factor that can change or be measured'},
{term:'changed variable',meaning:'the factor deliberately varied to test a relationship'},
{term:'measured variable',meaning:'the outcome observed or measured in response'},
{term:'controlled variable',meaning:'an influential condition deliberately kept the same'},
{term:'pattern',meaning:'a repeated or directional feature in observations or data'},
{term:'relationship',meaning:'a way in which two measured variables vary together'},
{term:'prediction',meaning:'a justified statement of the expected outcome made before testing'},
{term:'confounding variable',meaning:'an extra changing factor that prevents a clear interpretation'},
{term:'operational measure',meaning:'a precise observable way to represent an idea such as strength or warmth'}
],
steps:['Identify the phenomenon and the evidence that could answer a question.','Name one variable to change or compare and one outcome to measure or observe.','Check that available materials, time and instruments can produce the required evidence.','Remove unsafe, unethical, subjective or unrealistic elements and define vague terms.','Use prior observations or scientific knowledge to write an if–then–because prediction.','After collecting evidence, describe patterns carefully and acknowledge limits.']
};

const slides = [
{title:'Curriculum',kicker:'AC9S6I01',body:[metadata.descriptor]},
{title:'Learning intention',body:[metadata.learningIntention,...metadata.successCriteria]},
{title:'An investigable question',body:[topic.sections[0].content,'Frame: How does [changed variable] affect [measured variable] when [controls] stay the same?']},
{title:'Patterns and relationships',body:[topic.sections[1].content,'Sort: time pattern / category pattern / measured relationship.']},
{title:'Question, method and data must align',body:[topic.sections[2].content,'Check: Was every comparison tested? Was every outcome recorded?']},
{title:'Turn vague words into measures',body:[topic.sections[3].content,'Rewrite “Which bridge is best?” using maximum load before bending.']},
{title:'Predict with a reason',body:[topic.sections[4].content,'If ___, then ___, because ___. The because clause must explain why.']},
{title:'One clear comparison',body:[topic.sections[5].content,'Spot the confounder: different towel sizes are tested at different fan speeds.']},
{title:'Safety, ethics and feasibility',body:[topic.sections[6].content,'Redesign: “How much smoke can a person breathe?”']},
{title:'Limits and careful claims',body:[topic.sections[7].content,'Association is evidence of a relationship, not automatic proof of cause.']},
{title:'Important questions and answers',body:[topic.sections[8].content]},
{title:'Exit ticket',body:['Write an investigable question about paper-helicopter blade length.','Label the changed, measured and two controlled variables.','Add an if–then–because prediction and one practical limitation.']}
];

const misconceptions = [
{claim:'Every question can be tested.',correction:'Questions may be subjective, unsafe, unethical, too broad or impossible with available time and equipment.'},
{claim:'A prediction is a random guess.',correction:'A scientific prediction uses observations, prior data or accepted scientific knowledge to justify an expected outcome.'},
{claim:'Changing more variables makes a stronger test.',correction:'Changing multiple influential factors confounds the result and weakens the conclusion about each relationship.'},
{claim:'A yes/no question is automatically invalid.',correction:'Yes/no wording can be investigable when clear evidence can decide between the alternatives.'},
{claim:'A pattern proves cause.',correction:'An observed relationship may be an association caused by another factor; causal claims require an appropriate controlled design.'}
];
const importantQA = [
{question:'What is the quickest test for an investigable question?',answer:'Ask what will change or be compared, what will be measured, and whether the required evidence can be collected safely with available methods.'},
{question:'Does a prediction need an exact number?',answer:'No. A justified direction is often stronger than false precision, especially when evidence is limited.'},
{question:'What if the prediction is wrong?',answer:'Report the result honestly and use it to revise the explanation or plan another investigation.'},
{question:'Can paired data prove cause?',answer:'Not usually. Paired observations can reveal an association; a fair comparison is needed to isolate a possible cause.'}
];
const assessmentHints = ['Use the frame “How does ___ affect ___ when ___ stays the same?”','Name the missing measurement or unavailable comparison precisely.','Match each question to the actual equipment, procedure and recorded data.','In predictions, make the because clause explain the expected relationship.','Distinguish an observed association from a demonstrated causal effect.','State relevant safety, ethical, scale, sampling or instrument limitations.'];

if (practice.length !== 48) throw new Error(`AC9S6I01 practice count ${practice.length}; expected 48`);
if (test.length !== 16) throw new Error(`AC9S6I01 test count ${test.length}; expected 16`);
if (worksheet.length !== 12) throw new Error(`AC9S6I01 worksheet count ${worksheet.length}; expected 12`);
for (const [name,bank] of [['practice',practice],['test',test]]) bank.forEach((item,i)=>{if(item.answers.length!==4)throw new Error(`${name} ${i+1}: expected four answers`);if(!Number.isInteger(item.correct)||item.correct<0||item.correct>3)throw new Error(`${name} ${i+1}: invalid correct index`);});

export default {code:metadata.code,descriptor:metadata.descriptor,title:metadata.title,learningIntention:metadata.learningIntention,successCriteria:metadata.successCriteria,vocabulary:topic.vocabulary.map(({term,meaning})=>({term,definition:meaning})),steps:topic.steps,topicSections:topic.sections.map(({heading,content})=>({heading,body:content})),misconceptions,importantQA,assessmentHints,exitTicket:'Write a safe investigable question with named variables, add a justified prediction, and identify one limit on the evidence.',masteryEvidence:'The student poses safe, feasible questions aligned to available methods and data; identifies patterns and relationships without overstating cause; and makes directional predictions supported by relevant evidence or scientific mechanisms.',practice,test,worksheet,slides};
