const metadata = {
  code: 'AC9S6H02',
  title: 'Scientific knowledge in community decisions',
  descriptor: 'Investigate how scientific knowledge is used by individuals and communities to identify problems, consider responses and make decisions.',
  learningIntention: 'We are learning to use scientific evidence, community priorities and explicit criteria to make and review defensible decisions.',
  successCriteria: [
    'separate scientific evidence from opinions, values and assumptions',
    'compare realistic responses using benefits, limitations, stakeholders and uncertainty',
    'justify a decision with relevant evidence and propose monitoring that could trigger revision'
  ]
};

const q = (skill, stage, question, answers, correct, explanation, hint) => ({skill, stage, question, answers, correct, explanation, hint});

const practice = [
  q('identify the problem','foundation','A town creek repeatedly turns green in summer. Which statement defines the problem most usefully?',['The creek is ugly','Algal growth may be reducing water quality each summer','People dislike green','The council should install a fountain'],1,'This statement identifies an observable condition and its possible consequence without jumping to a solution.','Choose the statement that can guide evidence collection.'),
  q('relevant evidence','foundation','Which measurement is most relevant when investigating fish deaths after an algal bloom?',['Dissolved oxygen in the water','Number of benches beside the creek','Colour of the council logo','Distance to the library'],0,'Dissolved oxygen directly relates to whether fish can respire.','Ask which measurement tests the suspected cause.'),
  q('evidence and opinion','foundation','Which is scientific evidence rather than an opinion?',['The wetland looks nicer','Weekly tests found nitrate levels fell from 8 to 3 mg/L','Everyone should love frogs','The project feels worthwhile'],1,'A recorded measurement from repeated tests is evidence; the other statements express preferences.','Look for measured, checkable information.'),
  q('stakeholders','foundation','A council is considering closing a beach while turtle nests hatch. Who is an affected stakeholder?',['Local swimmers and turtle-conservation workers','Only the mayor','Only people who agree with closure','Nobody until a decision is made'],0,'Both groups are affected or have relevant interests and should be considered.','A stakeholder can be affected even when they disagree.'),
  q('criteria','foundation','For a new drinking-water treatment, which is a scientific criterion?',['Amount of bacteria removed','Most fashionable colour','Councillor popularity','Catchiest project name'],0,'Bacteria removal is measurable and relates directly to safe water.','Choose a measurable sign of effectiveness.'),
  q('options','foundation','A school wants to reduce lunchtime waste. Which pair gives two genuine response options?',['Compost food scraps or change canteen packaging','Measure waste or notice waste','Agree or be correct','Students or teachers'],0,'Both are actions that could respond to the defined problem.','Options are possible actions, not groups or observations.'),
  q('benefit and limitation','foundation','Solar panels reduce grid electricity use but generate less power on cloudy days. The cloudy-day statement is a:',['limitation','stakeholder','measurement unit','personal insult'],0,'It describes a condition that restricts the option’s performance.','A limitation shows where an option may not fully meet a need.'),
  q('decision chain','foundation','What should normally happen before a community selects a response?',['Compare evidence and stakeholder criteria','Hide all uncertainty','Choose the first suggestion','Measure success after no action'],0,'Evidence and criteria are needed to compare responses transparently.','A justified choice follows investigation and comparison.'),
  q('science and values','core','Science predicts a dam would provide reliable water but flood a cultural site. What does science alone NOT decide?',['How much the community should value protecting the site','The predicted flooded area','Likely water storage','Changes to river flow'],0,'The importance assigned to cultural protection is a value judgement informed by affected communities.','Separate predicted effects from priorities.'),
  q('relevance','core','A town compares desalination and water recycling. Which fact is least relevant?',['Energy used per kilolitre','Salt disposal effects','Amount of reliable water produced','The architect’s favourite sport'],3,'The favourite sport does not inform any reasonable criterion for the water decision.','Not every true fact is decision evidence.'),
  q('stakeholder requirements','core','Before choosing a reef-protection plan, why identify fishing, tourism and Traditional Owner requirements?',['Different groups may be affected differently and hold relevant knowledge','The largest group must automatically win','Scientific data becomes unnecessary','It guarantees complete agreement'],0,'Identifying requirements reveals effects, knowledge and priorities that a single viewpoint can miss.','Stakeholder consultation informs comparison; it does not guarantee consensus.'),
  q('trade-offs','core','Option A removes 90% of litter but costs $80,000; B removes 70% and costs $25,000. What is the genuine trade-off?',['Effectiveness versus cost','Evidence versus guessing','Water versus air','Truth versus opinion'],0,'A performs better on litter removal while B performs better on cost.','Name the criteria on which the options differ.'),
  q('uncertainty','core','A habitat survey covered one dry month only. What is the soundest conclusion?',['Results are useful but may not represent wetter seasons','The data prove every season is identical','No decision is possible','The survey is an opinion'],0,'The evidence can inform a provisional decision, but limited seasonal sampling creates uncertainty.','State the limitation without discarding all evidence.'),
  q('monitoring','core','A town installs wildlife crossings. Which monitoring best tests success?',['Compare animal-collision rates before and after installation over similar periods','Count ribbon-cutting guests','Ask whether the sign looks attractive','Measure road length once'],0,'Before-and-after collision data directly test the intended outcome.','Match the measure to the success criterion.'),
  q('adaptive decisions','core','Monitoring shows a new bin system has not reduced landfill after six months. What should decision-makers do?',['Review implementation and evidence, then revise the response','Delete the measurements','Claim success anyway','Never change an announced decision'],0,'Responsible decisions are revised when monitored outcomes fail to meet criteria.','Evidence after implementation is part of the decision chain.'),
  q('risk','core','A bushfire response has a low chance of harming a rare plant but the harm would be severe. Why still consider it?',['Risk includes both likelihood and consequence','Only common effects matter','Rare plants are not stakeholders','Low likelihood means zero risk'],0,'A low-probability event can remain important when its consequences are serious.','Risk is not likelihood alone.'),
  q('criteria match','core','Residents require a flood warning to reach every household within five minutes. Which evidence best tests this criterion?',['Delivery-time and coverage results from a town-wide trial','Total number of words in the warning','Cost of the mayor’s phone','Colour preferences from one resident'],0,'A coverage and timing trial measures both parts of the stated requirement.','Translate the requirement into measurable evidence.'),
  q('best-supported claim','core','Three trials found shade sails lowered playground surface temperature by 9–12°C. Which claim is best supported?',['Shade sails can substantially reduce surface temperature under tested conditions','Shade sails prevent every heat illness','All playgrounds cool by exactly 10°C','Shade sails are the cheapest possible response'],0,'The claim matches the measurements and appropriately limits itself to tested conditions.','Do not claim more than the evidence shows.'),
  q('fairness','core','Two water restrictions save the same volume, but one prevents households without gardens from receiving rebates. Which extra criterion is most relevant?',['Equity','Font size','Novelty','Popularity of the scientist'],0,'Equity examines whether benefits and burdens are distributed fairly.','Ask who gains, pays or misses out.'),
  q('individual decisions','core','A family uses air-quality readings to decide when a child with asthma exercises outdoors. How is science being used?',['Evidence about particulate levels informs a personal risk decision','A value judgement creates the readings','The sensor makes the decision for them','One reading proves future air quality'],0,'Measurements inform the family’s choice, alongside the child’s needs and medical advice.','Science informs rather than mechanically dictates.'),
  q('community knowledge','core','Why might fishers’ long-term observations be considered with formal estuary surveys?',['They may reveal seasonal patterns and changes missed by short surveys','Observations always replace measurements','Only local knowledge contains values','It ensures the preferred option wins'],0,'Long experience can add relevant evidence, which can be checked alongside systematic surveys.','Different evidence sources can complement one another.'),
  q('decision matrix','application','A wetland option scores high for habitat and flood control but medium for cost. A concrete drain scores high for cost but low for habitat. If habitat and flood control are priority criteria, which choice is better supported?',['Wetland','Concrete drain','Either, because criteria never matter','Neither, because scores are opinions only'],0,'The wetland performs best on the explicitly prioritised criteria, though its cost limitation should be acknowledged.','Apply the stated priorities, not your own.'),
  q('data interpretation','application','Bins sent 120 kg to landfill before a trial and 72 kg after it. Which statement is accurate?',['Landfill waste decreased by 48 kg, or 40%','It decreased by 48%','It increased by 40%','The trial removed all waste'],0,'The decrease is 48 kg; 48 divided by 120 equals 0.40 or 40%.','Calculate change relative to the original amount.'),
  q('causal caution','application','A creek cleared after a litter trap was installed, but heavy rain also stopped. What should the council report?',['The trap may have helped, but weather is a competing explanation','The trap certainly caused all improvement','Rain can never affect creeks','No observation should be reported'],0,'A responsible report acknowledges another factor that could explain the change.','Correlation after an action does not automatically establish cause.'),
  q('compare evidence quality','application','Which evidence gives strongest support for choosing a mosquito-control response?',['Repeated local trials measuring mosquito numbers and non-target species','A single anonymous comment','A poster made by the supplier','One photograph from another climate'],0,'Repeated local measurements address effectiveness and unintended ecological effects.','Prefer relevant, systematic and repeatable evidence.'),
  q('opportunity cost','application','A council can fund either a small pilot across two suburbs or immediate town-wide installation. What is a benefit of the pilot?',['It can test effectiveness and reveal problems before larger spending','It guarantees the final program works','It removes the need for monitoring','It includes every stakeholder automatically'],0,'A pilot reduces uncertainty and supports revision before full-scale commitment.','Small trials can inform larger decisions.'),
  q('unintended effects','application','A bright night-lighting program reduces falls but disrupts moth activity. What should the review do?',['Weigh safety gains against ecological harm and test lower-impact lighting','Ignore moth data because falls matter','Remove all lighting immediately without comparison','Declare that science failed'],0,'The new evidence reveals a trade-off and supports investigating an adjusted response.','An unintended effect should enter the comparison.'),
  q('thresholds','application','A town will revise its water plan if reservoir levels remain below 35% for eight weeks. Why state this threshold in advance?',['It links monitoring evidence to a transparent action','It ensures rainfall occurs','It makes uncertainty disappear','It prevents any later discussion'],0,'A trigger makes the adaptive response clear and evidence based.','A monitoring plan needs a rule for acting on results.'),
  q('stakeholder representation','application','At a meeting, one shop owner supports closing a street to cars. Which conclusion is justified?',['That owner’s view is evidence of one perspective, not all businesses','Every business supports closure','Business impacts need no further evidence','The scientific data are now irrelevant'],0,'One participant cannot represent a diverse stakeholder group without broader consultation.','Avoid treating one voice as an entire community.'),
  q('conflicting criteria','application','A cooling centre is highly effective but difficult to reach without a car. Which modification best addresses the limitation?',['Add free shuttle routes from heat-vulnerable neighbourhoods','Stop measuring attendance','Advertise only to drivers','Lower the indoor temperature further'],0,'Transport improves equitable access while retaining the effective cooling response.','Target the criterion on which the option is weak.'),
  q('source interests','application','A company selling filters reports its product removes 99% of particles. What is the best next step?',['Check methods and seek independent testing under local conditions','Reject the result only because a company produced it','Buy immediately','Replace the percentage with opinions'],0,'Commercial interest does not automatically invalidate evidence, but methods and independent replication matter.','Evaluate evidence quality and possible bias.'),
  q('evidence update','application','New surveys find a threatened frog breeding in the proposed construction area. What should planners do?',['Add the evidence to the criteria comparison and reconsider options','Ignore it because planning began earlier','Assume one frog represents every species','Cancel without investigating impacts'],0,'Decisions should be revisited when relevant new evidence changes likely consequences.','A defensible process can change direction.'),
  q('precaution','application','A chemical may seriously damage a wetland, but evidence is incomplete. Which response best manages uncertainty?',['Limit use, gather more evidence and monitor for harm','Assume no evidence means no risk','Ban every chemical everywhere forever','Stop all investigation'],0,'Proportionate precaution reduces possible serious harm while improving the evidence base.','Uncertainty can justify careful, revisable action.'),
  q('multi-criteria reasoning','application','A recycling plant cuts landfill by 60% but increases truck noise near homes. A complete recommendation should:',['cite landfill evidence, acknowledge noise impacts and propose mitigation or comparison','mention only the 60% benefit','ask residents to ignore measurements','choose solely by cheapest price'],0,'Good reasoning connects evidence to multiple criteria and addresses the real trade-off.','Include both benefit and limitation.'),
  q('quantitative comparison','application','Filter A removes 95 of 100 samples but costs $50 each; B removes 88 and costs $12. Which statement is defensible?',['A is more effective; B is cheaper; priorities determine the recommendation','A is best under every criterion','B is scientifically false','The results contain no trade-off'],0,'The data show opposing strengths, so the decision depends on stated criteria and constraints.','Compare each option on more than one criterion.'),
  q('decision transparency','application','Why publish the criteria and evidence used in a council decision?',['People can understand, question and review the reasoning','It makes every person agree','It turns opinions into measurements','It hides uncertainty'],0,'Transparency allows scrutiny even when reasonable people value criteria differently.','A decision can be accountable without unanimous agreement.'),
  q('baseline','application','A revegetation team wants to know whether native bird numbers improve. What must it collect before planting?',['A baseline bird survey using a consistent method','Only the final survey','The names of every volunteer','A prediction with no counts'],0,'A baseline enables a meaningful before-and-after comparison.','You need to know the starting condition.'),
  q('monitoring design','application','Which monitoring plan best detects a long-term change in beach erosion?',['Measure fixed transects each season for several years','Take one photo on opening day','Ask one visitor annually','Measure different places with different methods each time'],0,'Repeated measures at fixed locations and comparable times reveal trends reliably.','Consistency over time matters.'),
  q('limitations','challenge','A survey of 12 volunteers found strong support for wind turbines. What is the largest evidence limitation?',['The small self-selected sample may not represent the community','Wind cannot be measured','Support is always scientific evidence','Twelve responses prove opposition'],0,'People who volunteer may differ from others, and twelve is a limited sample.','Consider sample size and selection.'),
  q('weighting criteria','challenge','Why can two communities use the same scientific evidence yet choose different flood responses?',['They may reasonably weight cost, heritage, safety and habitat differently','Scientific measurements change when discussed','Only one community understands science','Evidence has no role in either choice'],0,'Evidence describes likely effects; community priorities influence how criteria are weighted.','Same facts do not require identical values.'),
  q('compound uncertainty','challenge','A model predicts 20–35 cm sea-level rise locally, depending on emissions and currents. Which use is soundest?',['Plan across the plausible range and update as observations improve','Use exactly 27.5 cm as certain','Ignore the model because it gives a range','Prepare only for the lowest value'],0,'Scenario planning respects quantified uncertainty and supports revision.','A range communicates information, not failure.'),
  q('ethical evidence use','challenge','A trial improves average access to clean water but the remotest households receive none. What should the decision report?',['Both the average improvement and the unequal distribution','Only the average because it is numerical','Only one satisfied household','No result until access is perfect'],0,'Average outcomes can conceal inequity, so disaggregated effects are decision-relevant.','Ask who benefits, not only how much overall.'),
  q('systems effects','challenge','Removing foxes increases shorebird nests, but rabbit numbers also rise. What response is strongest?',['Continue targeted monitoring and adapt control to both outcomes','Call the program an unqualified success','Ignore rabbits because they were not the first target','Return to the original plan without data'],0,'Ecosystem responses interact; adaptive management considers intended and unintended outcomes.','Complex systems require monitoring beyond one measure.'),
  q('recommendation quality','challenge','Which recommendation is most defensible?',['Trial Option C for one year because it met safety and cost criteria in local tests; monitor injury rates and revise if rates exceed the baseline','Choose C because everyone knows it is best','Choose C forever because one test succeeded','Choose C because its name sounds safe'],0,'It connects local evidence to criteria, limits the claim and includes review.','Look for evidence, trade-offs and monitoring.'),
  q('decision revision','challenge','When does changing a science-informed decision show strength rather than failure?',['When relevant new evidence shows criteria are not being met','Whenever criticism appears online','When records are destroyed','Only when the cheapest option changes'],0,'Updating a choice in response to relevant monitored evidence is rational and accountable.','Adaptive decisions are designed to learn.'),
  q('evidence synthesis','challenge','Water tests favour Option X, habitat surveys favour Y, and both datasets use sound methods. What should the team do?',['Explain the conflicting criteria and seek an option or weighting that addresses both','Discard whichever study was completed second','Average option names','Claim the evidence agrees'],0,'Sound evidence can support different criteria; synthesis makes the trade-off explicit.','Conflict may be between goals, not data quality.'),
  q('problem framing','challenge','Residents say a river problem is “not enough clean water for people and ecosystems,” rather than simply “low dam storage.” Why is the broader frame useful?',['It allows responses beyond building storage and recognises ecological needs','It guarantees a dam will be rejected','It removes the need for measurements','It makes every issue equally important'],0,'Problem framing shapes which evidence, stakeholders and options enter the decision.','A narrow problem can hide causes or affected groups.'),
  q('integrated judgement','challenge','Which sequence represents a robust science-informed community decision?',['Define problem, gather evidence, identify stakeholders and criteria, compare responses, decide, monitor and revise','Vote, find evidence, hide limits, stop measuring','Pick cheapest, announce, redefine problem','Ask one expert, copy a solution, guarantee success'],0,'The sequence integrates investigation, participation, transparent comparison and adaptive review.','Use the full decision chain.')
];

const test = [
  q('novel water context','test','A remote community compares rain tanks and a bore. Tests show the bore is reliable but slightly saline; rainfall is clean but seasonal. Which conclusion is strongest?',['The bore and tanks have complementary benefits and limitations worth comparing against health, reliability and cost criteria','Rain tanks are always best','Salinity proves the bore has no possible use','Reliability is the only community value'],0,'The evidence identifies a genuine reliability–quality trade-off and supports a multi-criteria comparison.','Do not turn one strength into an automatic decision.'),
  q('quantitative habitat evidence','test','After fencing a dune, native seedling survival rises from 30% to 66%. What is the percentage-point increase?',['36 percentage points','120 percentage points','46 percentage points','96 percentage points'],0,'66 minus 30 equals a 36-percentage-point increase.','Percentage points are found by subtraction.'),
  q('evidence relevance','test','A town is choosing cooler road surfaces. Which data most directly address heat reduction?',['Surface temperatures of trial sections measured at the same times','Residents’ favourite road names','Number of workers’ uniforms','Age of the council building'],0,'Comparable surface-temperature measurements test the intended effect.','Match the data to the criterion.'),
  q('stakeholder conflict','test','A marine reserve may increase fish populations but initially restrict commercial catches. What must a justified decision include?',['Ecological projections, fishing impacts, affected groups and possible transition measures','Only the projected fish increase','Only the loudest speaker','A promise of no trade-offs'],0,'The decision should connect scientific outcomes to stakeholder effects and responses.','Include who bears short-term costs.'),
  q('uncertainty response','test','A fire-risk map is based on ten years of data but recent vegetation has changed. What is the best use?',['Use it provisionally, update vegetation inputs and monitor predictions','Treat every boundary as permanent','Ignore all historical data','Let residents redraw it by preference'],0,'The map remains evidence, but changed conditions require updating and checking.','Useful evidence can still have limits.'),
  q('values versus evidence','test','Which statement is a value judgement in a river decision?',['Protecting ceremonial access should receive the highest priority','Water temperature rose 2°C downstream','Three fish species declined','The wetland stores 40 ML during floods'],0,'“Should receive the highest priority” assigns importance rather than reporting an observation.','Look for a statement about what ought to matter most.'),
  q('monitoring trigger','test','A trial bus reduces private trips by only 4%, below its 15% target. What action best follows the stated criterion?',['Investigate barriers and revise or replace the trial','Report that every target was met','Lower the recorded baseline','Stop collecting passenger data'],0,'The monitored outcome misses the success criterion, so review and adaptation are warranted.','Compare outcome with the pre-set target.'),
  q('equity','test','A heat-warning app reaches 92% of residents but not many older people without smartphones. Which conclusion is most complete?',['High overall reach masks an access gap that needs another warning channel','The app fully succeeds for everyone','Older people are not stakeholders','92% means no improvement is possible'],0,'Disaggregated evidence reveals an equity limitation hidden by the average.','Ask which group is missed.'),
  q('risk comparison','test','Option P has a 1-in-100 chance of severe contamination; Q has a 1-in-5 chance of a minor taste change. Why is frequency alone insufficient?',['Consequences as well as likelihood determine risk','Only severe outcomes have likelihood','Taste cannot be observed','All risks are equal'],0,'Risk comparison must consider how likely and how serious each outcome is.','Use both dimensions of risk.'),
  q('source evaluation','test','An independent university and a supplier report different battery lifetimes. What should a school do?',['Compare test conditions and methods, then conduct or seek a relevant independent trial','Accept the supplier automatically','Average the organisations’ ages','Reject all battery evidence'],0,'Method differences may explain results; relevant verification is more useful than judging by label alone.','Inspect how the evidence was produced.'),
  q('pilot evidence','test','A compost trial succeeds in one small school with daily staff supervision. What limits transfer to a large public festival?',['Scale, participant behaviour and supervision differ','Compost cannot work outdoors','One success proves every context','Festivals create no organic waste'],0,'Contextual differences create uncertainty about whether the effect will transfer.','Compare conditions, not just outcomes.'),
  q('trade-off mitigation','test','A seawall protects houses but narrows a nesting beach. Which response best addresses both criteria?',['Compare setback, dune restoration and redesigned protection using flood and habitat evidence','Build the tallest wall without study','Protect nests but ignore houses','Choose by coin toss'],0,'Alternative or combined designs can be compared against both safety and habitat needs.','Seek responses that reduce the trade-off.'),
  q('causal inference','test','Asthma presentations fall after low-emission buses begin, while weather and pollen also change. What can be claimed?',['The fall is encouraging, but more comparison is needed before attributing it to buses','The buses certainly caused the entire fall','Pollen never affects asthma','Health records are opinions'],0,'Other changing variables mean the association alone does not prove causation.','Identify plausible competing explanations.'),
  q('adaptive management','test','Mangrove planting survives well at two sites but fails at a wave-exposed third site. What should managers do?',['Use site evidence to modify species, placement or protection at the third site','Declare all planting useless','Copy the first method unchanged forever','Remove the successful sites'],0,'Local monitoring supports a targeted revision rather than an all-or-nothing conclusion.','Adapt to the condition linked to failure.'),
  q('transparent recommendation','test','Which council statement best demonstrates accountable reasoning?',['We selected B because local trials met water-quality and budget thresholds; habitat effects remain uncertain, so quarterly surveys will guide review','B is obviously perfect','Experts chose B, so questions are unnecessary','B won the quickest show of hands'],0,'The statement names evidence, criteria, uncertainty and monitoring.','Accountable reasoning can be inspected later.'),
  q('full decision chain','test','A community has defined coastal erosion and gathered shoreline data. What is the strongest next sequence?',['Identify affected groups and criteria, compare feasible responses, decide transparently, then monitor','Announce one response and stop measuring','Collect unrelated facts indefinitely','Ask one group to decide for all'],0,'The remaining stages ensure inclusive comparison, action and review.','Continue the evidence-to-action chain.')
];

const worksheet = [
  {question:'A park pond has frequent fish deaths. Write a precise problem statement and name three measurements that would help investigate it.',modelAnswer:'Problem: fish deaths recur in the pond, possibly because water conditions become unsuitable. Measure dissolved oxygen, water temperature and nutrient concentration at consistent locations and times.'},
  {question:'Classify each statement as evidence, opinion or value: “Noise averaged 68 dB”; “the turbines look awful”; “protecting sleep should be prioritised.” Explain.',modelAnswer:'68 dB is measured evidence; “look awful” is personal opinion; “should be prioritised” assigns importance and is a value judgement.'},
  {question:'For a proposed wetland restoration, identify four stakeholders and one likely requirement for each.',modelAnswer:'Traditional Owners—protect cultural values; nearby residents—limit flooding; farmers—maintain workable water access; native species/ecologists—improve habitat and water quality.'},
  {question:'Compare two school cooling options: shade trees cost $12,000 and cool after several years; shade sails cost $20,000 and cool immediately. Give one benefit, one limitation and one uncertainty for each.',modelAnswer:'Trees: benefit habitat/long-term cooling; limitation slow growth; uncertainty survival. Sails: benefit immediate reliable shade; limitation higher cost; uncertainty maintenance life.'},
  {question:'Create a decision matrix with criteria effectiveness, cost, equity and environmental impact for rain tanks, recycled water and stricter restrictions.',modelAnswer:'A defensible matrix uses evidence-based ratings: tanks medium effectiveness/high household cost/uneven access/low impact; recycling high effectiveness/high infrastructure cost/broad access/energy impact; restrictions variable effectiveness/low infrastructure cost/possible unequal burdens/low physical impact. Ratings require local evidence.'},
  {question:'A litter trap collects 240 kg in month 1 and 150 kg in month 2. Give two possible explanations and evidence needed to distinguish them.',modelAnswer:'Possibilities include less litter entering the creek or lower rainfall/flow carrying less litter. Compare upstream litter surveys, rainfall, flow and trap efficiency across both months.'},
  {question:'Recommend a response to a beach-lighting problem where brighter lights improve safety but disorient hatchling turtles.',modelAnswer:'Use shielded, low-intensity, long-wavelength amber or red lighting on necessary paths, subject to local wildlife guidance. Trial it, measure falls and hatchling direction, consult beach users and turtle experts, and revise if either safety or wildlife thresholds fail.'},
  {question:'Explain why uncertainty does not mean a community must postpone every decision. Include an example.',modelAnswer:'Evidence can support a proportionate provisional response while limits are stated. For example, during uncertain algal risk, issue temporary warnings, collect toxin tests and change access rules as results arrive.'},
  {question:'Design monitoring for a new wildlife crossing, including baseline, success measure, timing and revision trigger.',modelAnswer:'Record two years of collisions and camera detections before construction; monitor monthly afterward for two comparable years. Success is at least 50% fewer collisions without displacement nearby; revise fencing or placement if the first-year reduction is under 25%.'},
  {question:'Two groups use the same flood map: residents favour levees while conservationists favour wetland restoration. Explain how both can reason from the map yet disagree.',modelAnswer:'The map supplies shared hazard evidence, but groups may weight immediate property protection, cost, habitat and long-term resilience differently. Their reasons should be compared openly rather than calling one view unscientific.'},
  {question:'Critique: “The cheapest waste option is scientifically best.” Replace it with a defensible statement.',modelAnswer:'Cost is one criterion. The best-supported decision compares verified waste reduction, contamination, emissions, feasibility, equity and cost, acknowledges uncertainty and monitors actual outcomes.'},
  {question:'Write a six-step recommendation for a town considering desalination, ending with a monitoring and revision rule.',modelAnswer:'Define water-security need; measure demand and supply; consult households, Traditional Owners, industry and marine experts; compare desalination with recycling/conservation on reliability, cost, energy, equity and marine effects; select the best-supported mix; monitor energy, water quality and marine indicators, revising operations when agreed thresholds are exceeded.'}
];

const topicSections = [
  {heading:'Science informs decisions; it does not choose values',body:'Scientific knowledge can explain causes, measure present conditions and estimate likely consequences. Individuals and communities must also decide what they value, what risks are acceptable and how benefits and burdens should be shared.'},
  {heading:'The decision chain',body:'Define the problem → gather relevant evidence → identify affected groups and criteria → compare feasible responses → justify a choice → monitor outcomes → revise when evidence changes. Skipping a stage makes reasoning harder to check.'},
  {heading:'Evidence, opinion and values',body:'Evidence is observable or measurable and should be checked for relevance and quality. Opinions express personal judgements. Values state what ought to be protected or prioritised. Values belong in community decisions, but should not be disguised as measurements.'},
  {heading:'Stakeholders and criteria',body:'A stakeholder is affected by, can affect or holds relevant knowledge about a decision. Translate needs into criteria such as effectiveness, safety, cost, equity, cultural protection, habitat impact, time and reliability. One person never automatically represents a whole group.'},
  {heading:'Options and trade-offs',body:'Compare more than one realistic response. A benefit is an advantage against a criterion; a limitation is a condition or drawback. A trade-off occurs when an option performs better on one criterion but worse on another. Combined or modified responses may reduce a trade-off.'},
  {heading:'Uncertainty and risk',body:'Uncertainty is an honest limit in data or prediction, not proof that nothing is known. Risk considers both likelihood and consequence. Use ranges, pilots, precaution and scenarios to act proportionately while learning more.'},
  {heading:'Monitoring and revision',body:'Set a baseline, measurable success indicators, a timetable and evidence thresholds that trigger action. Monitoring checks intended and unintended effects. Changing a response because relevant evidence changed is adaptive management, not failure.'},
  {heading:'A strong recommendation',body:'State the response, connect specific evidence to priority criteria, acknowledge stakeholder effects and a genuine limitation, describe uncertainty, and give a monitoring-and-revision plan. Never claim that science guarantees one morally correct answer.'},
  {heading:'Common reasoning traps',body:'Cheapest is not automatically best; a true fact is not automatically relevant; popularity is not evidence of effectiveness; one stakeholder is not the whole community; uncertainty does not erase evidence; and a short-term benefit may have long-term or indirect costs.'},
  {heading:'Important questions and answers',body:'Q: Can communities disagree while using the same evidence? A: Yes, because they may weight criteria differently. Q: When is evidence strong? A: When methods are relevant, systematic and transparent. Q: Why monitor? A: To test success, detect unintended effects and guide revision.'}
];

const vocabulary = [
  {term:'stakeholder',definition:'a person, group or living system affected by, able to affect or holding relevant knowledge about a decision'},
  {term:'criterion',definition:'a standard used to judge how well an option meets a need'},
  {term:'trade-off',definition:'a balance in which gaining on one criterion involves a cost on another'},
  {term:'uncertainty',definition:'a recognised limit in data, knowledge or prediction'},
  {term:'risk',definition:'a combination of how likely an outcome is and how serious its consequences are'},
  {term:'baseline',definition:'a starting measurement used for later comparison'},
  {term:'monitoring',definition:'repeated collection of evidence to check outcomes over time'},
  {term:'adaptive management',definition:'acting, monitoring, learning and revising a response as evidence develops'}
];

const slides = [
  {title:'Curriculum',kicker:'AC9S6H02',body:[metadata.descriptor]},
  {title:'Learning intention',body:[metadata.learningIntention,...metadata.successCriteria]},
  {title:'What science contributes',body:['Science can identify causes, measure conditions and predict likely effects.','Communities also weigh culture, fairness, cost and acceptable risk. Science informs; it does not choose values.']},
  {title:'Follow the decision chain',body:['Define problem → gather evidence → identify stakeholders and criteria → compare responses → decide → monitor → revise.','Quick check: Which stage prevents us from choosing a solution too early?']},
  {title:'Evidence, opinion or value?',body:['Evidence: “Nitrate measured 8 mg/L.”','Opinion: “The creek looks horrible.”','Value: “Safe habitat should be prioritised.”','Sort three statements from a local issue and justify each label.']},
  {title:'Stakeholders and criteria',body:['Ask: Who is affected? Who holds relevant knowledge? Who carries cost or risk?','Turn needs into criteria: effectiveness, safety, equity, cost, culture, habitat, time and reliability.']},
  {title:'Compare options and trade-offs',body:['Use the same criteria for every feasible response.','Name a benefit and a limitation; then explain the real trade-off. Consider whether a combined option reduces it.']},
  {title:'Uncertainty is information',body:['A range, small sample or changed condition limits confidence—it does not make evidence worthless.','Use pilots, precaution, scenarios and further measurements. Risk = likelihood plus consequence.']},
  {title:'Monitor and adapt',body:['Record a baseline, success measure, timetable and trigger for revision.','Monitor unintended effects as well as the target outcome. A changed decision can show learning.']},
  {title:'Important questions and answers',body:[topicSections[9].body]},
  {title:'Build a recommendation',body:['I recommend ___ because evidence ___ meets criteria ___.','It benefits ___ but is limited by ___. Uncertainty remains about ___.','Monitor ___; revise if ___.']},
  {title:'Exit ticket',body:['A school wants to reduce heat using trees or shade sails.','Choose priority criteria, recommend one response, acknowledge a trade-off and write one monitoring trigger.']}
];

const misconceptions = [
  {claim:'Science tells a community the single correct choice.',correction:'Science informs likely effects and uncertainty; communities also make transparent value judgements and weight criteria.'},
  {claim:'The cheapest option is automatically best.',correction:'Cost is one criterion alongside effectiveness, safety, equity, culture and environmental impacts.'},
  {claim:'Uncertainty means evidence should be ignored.',correction:'State the limit, act proportionately, gather more evidence and monitor outcomes.'},
  {claim:'One stakeholder speaks for the whole community.',correction:'Stakeholder groups can contain different needs and perspectives; use broad, respectful consultation.'},
  {claim:'Once announced, a decision should never change.',correction:'Monitoring may show failure or unintended effects; evidence-based revision is responsible adaptive management.'}
];

const importantQA = [
  {question:'Can two communities use the same evidence and decide differently?',answer:'Yes. They may assign different transparent weights to cost, equity, culture, habitat, safety or time.'},
  {question:'Is an opinion useless?',answer:'No. Preferences and values matter, but they should be identified honestly and considered alongside scientific evidence.'},
  {question:'What makes monitoring useful?',answer:'A baseline, consistent measures, a timetable, success criteria and a pre-agreed trigger for review.'},
  {question:'What must every strong recommendation acknowledge?',answer:'At least one genuine limitation or uncertainty, as well as the evidence and criteria supporting the choice.'}
];

const assessmentHints = [
  'Define the problem before proposing a response.',
  'Name the evidence and explain which criterion it supports.',
  'Distinguish measurements from opinions and value priorities.',
  'Include multiple affected groups without assuming one voice represents all.',
  'Compare options using the same criteria and state a genuine trade-off.',
  'Finish with a measurable monitoring and revision rule.'
];

if (practice.length !== 48) throw new Error(`AC9S6H02 practice count ${practice.length}; expected 48`);
if (test.length !== 16) throw new Error(`AC9S6H02 test count ${test.length}; expected 16`);
if (worksheet.length !== 12) throw new Error(`AC9S6H02 worksheet count ${worksheet.length}; expected 12`);
for (const [bankName, bank] of [['practice', practice], ['test', test]]) bank.forEach((item, index) => {
  if (item.answers.length !== 4) throw new Error(`${bankName} ${index + 1}: expected four answers`);
  if (!Number.isInteger(item.correct) || item.correct < 0 || item.correct > 3) throw new Error(`${bankName} ${index + 1}: invalid correct index`);
});

export default {
  code: metadata.code,
  descriptor: metadata.descriptor,
  title: metadata.title,
  learningIntention: metadata.learningIntention,
  successCriteria: metadata.successCriteria,
  vocabulary,
  steps: ['Define the problem precisely.','Gather relevant, trustworthy scientific evidence.','Identify stakeholders and convert needs into criteria.','Compare feasible responses using the same criteria.','Justify a choice while acknowledging trade-offs and uncertainty.','Monitor intended and unintended outcomes, then revise when thresholds are crossed.'],
  topicSections,
  misconceptions,
  importantQA,
  assessmentHints,
  exitTicket: 'Recommend either trees or shade sails for a hot schoolyard. Cite evidence, name priority criteria, acknowledge a trade-off and state a monitoring trigger.',
  masteryEvidence: 'The student distinguishes evidence from values, compares feasible responses against explicit stakeholder criteria, justifies a decision with relevant evidence and uncertainty, and designs monitoring that can lead to revision.',
  practice,
  test,
  worksheet,
  slides
};
