const metadata = {
  code: 'AC9S6I02',
  title: 'Plan and conduct repeatable investigations',
  descriptor: 'plan and conduct repeatable investigations to answer questions including, as appropriate, deciding the variables to be changed, measured and controlled in fair tests; describing potential risks; planning for the safe use of equipment and materials; and identifying required permissions to conduct investigations on Country/Place',
  learningIntention: 'We are learning to plan safe, fair and repeatable investigations that can answer a scientific question.',
  successCriteria: [
    'identify the changed, measured and controlled variables in a fair test',
    'write enough method, measurement and repetition detail for another group to repeat an investigation',
    'distinguish validity, reliability, measurement resolution and repeat-measurement precision when evaluating a plan',
    'identify risks, safe controls and required permissions, including respectful work on Country/Place'
  ]
};

const q = (skill, stage, question, answers, correct, explanation, hint) => ({skill, stage, question, answers, correct, explanation, hint});

const practice = [
  q('variables','foundation','A class changes the length of a paper helicopter blade and measures its fall time. What is the changed variable?',['fall time','blade length','drop height','paper type'],1,'Blade length is deliberately changed. Fall time is the measured outcome, while height and paper type should be controlled.','Ask what the investigator deliberately alters.'),
  q('variables','foundation','Students test whether water temperature affects how quickly sugar dissolves. What is the measured variable?',['water temperature','type of sugar','time taken to dissolve','volume of water'],2,'The outcome recorded is the time taken for the sugar to dissolve; water temperature is the changed variable.','Find the observation or number collected as the outcome.'),
  q('controls','foundation','When testing how ramp height affects toy-car distance, which factor should be controlled?',['ramp height','distance travelled','the toy car used','the final conclusion'],2,'Using the same car prevents car mass or wheel condition from providing another explanation for distance changes.','Choose a factor that could affect the result but is not being tested.'),
  q('fair tests','foundation','Which plan is a fair test of fertiliser amount on bean growth?',['Change fertiliser and pot size together.','Use equal plants and light, vary fertiliser, then measure growth.','Give every plant a different soil and fertiliser.','Measure one fertilised plant without comparison.'],1,'Only this plan changes fertiliser while holding other influential conditions constant and measuring an outcome.','A fair comparison changes one test factor.'),
  q('equipment','foundation','Which instrument and unit best measure 35 mL of water?',['ruler in centimetres','measuring cylinder in millilitres','balance in grams','thermometer in degrees Celsius'],1,'A measuring cylinder is designed to measure liquid volume, and millilitres suit this quantity.','Match the instrument to the physical quantity.'),
  q('resolution','foundation','Which ruler reading is justified when the ruler has millimetre divisions?',['about 8 cm','8 cm','8.3 cm','8.34729 cm'],2,'A millimetre-scale ruler supports a reading to the nearest millimetre, written here as 8.3 cm. Extra digits would claim detail beyond the instrument’s resolution.','Use all, but not more than, the instrument’s scale allows.'),
  q('repeatability','foundation','Which method detail most helps another group repeat a seed-germination test?',['Watch the seeds for a while.','Add some water when needed.','Add 10 mL water daily for 7 days.','Try to keep things similar.'],2,'The exact volume, frequency and duration tell another group what to reproduce.','Look for quantities and timing.'),
  q('repetitions','foundation','Why test three paper bridges of each design instead of one?',['to guarantee identical results','to check whether a pattern is consistent despite variation','to change more variables','to make the ruler more precise'],1,'Repeated trials reveal natural variation and show whether the same overall pattern recurs; exact equality is not required.','Repetition supports confidence in a pattern.'),
  q('reliability','foundation','Three trials give 12.1 s, 12.0 s and 12.2 s. What do they suggest?',['The measurements form a consistent pattern.','The test is automatically valid.','The stopwatch measures to infinite precision.','No control variables are needed.'],0,'The close repeated results support reliability, but they do not by themselves prove the comparison was fair or unbiased.','Consistency across repeats concerns reliability.'),
  q('validity','foundation','A student compares two detergents but uses hot water for one and cold water for the other. What is the main problem?',['low precision only','a confounding water-temperature difference','too many repeated trials','the table needs colour'],1,'Water temperature may affect cleaning, so the result cannot be attributed confidently to detergent type. This weakens validity.','Look for a second factor changing with the tested factor.'),
  q('safety','foundation','A class warms water in a beaker. Which control best reduces burn risk?',['Taste the water first.','Use heatproof mats and teacher-supervised handling.','Fill the beaker to the rim.','Carry it quickly with bare hands.'],1,'A heatproof surface and supervised handling directly reduce contact with hot glass and water.','A safety control should act on the identified hazard.'),
  q('risk','foundation','In “wet floor may cause someone to slip”, what is the hazard?',['the wet floor','the possible injury','the results table','the permission form'],0,'The wet floor is the source of harm; slipping and injury are possible consequences.','A hazard is the thing or situation that can cause harm.'),
  q('permissions','foundation','Students want to collect leaves from a culturally sensitive site on Country. What should happen first?',['Collect quickly before anyone notices.','Seek guidance and required permission from the relevant Traditional Owners or land council.','Assume school permission covers every site.','Post the location publicly.'],1,'Permission and cultural guidance must be sought before fieldwork; school approval alone may not authorise access or collection.','Respectful fieldwork begins before entering or collecting.'),
  q('Country/Place','foundation','Which fieldwork action best respects Country/Place?',['Remove specimens because science is always exempt.','Follow permission conditions and avoid restricted or culturally sensitive locations.','Share exact locations of sensitive species online.','Move cultural material to photograph it.'],1,'Following the conditions set by the relevant custodians protects cultural knowledge, sites and living systems.','Permission includes conditions, not just a yes/no response.'),
  q('method order','core','Which sequence is most sensible for a ramp investigation?',['measure distance → release car → set ramp','set ramp → place car at marked start → release without push → measure distance','release car → choose ramp height → find ruler','write conclusion → run first trial → choose question'],1,'Setting the conditions before a consistent release and measurement creates an ordered, reproducible procedure.','Conditions must be ready before the trial begins.'),
  q('tables','core','Which heading correctly records pendulum timing data?',['Time','Result things','Time for 10 swings (s)','Pendulum good/bad'],2,'A useful heading names the measured quantity, the defined event and the unit.','A table heading needs quantity and unit.'),
  q('tables','core','A fair test uses three light levels and three trials at each. Which table structure is best?',['one row called results','rows for light level and columns for Trial 1, Trial 2, Trial 3 and mean growth (mm)','a paragraph with no units','columns for student names only'],1,'This structure records the changed condition, repeated measured values, units and a summary value without mixing variables.','The table should show conditions and every repeat.'),
  q('control group','core','Plants receive 0 g, 2 g and 4 g of fertiliser. Which is the comparison control?',['the 0 g group','the 4 g group','the tallest plant','the final mean'],0,'The 0 g group provides a baseline showing growth without the treatment.','A control group usually lacks the tested treatment.'),
  q('controls','core','In a test of salt concentration on ice-melting time, which set should stay the same?',['salt concentration and melting time','ice-cube size, room temperature and container','melting time and conclusion','salt concentration and number of trials'],1,'These factors could influence melting but are not the factor being tested, so controlling them improves validity.','Keep other influential conditions consistent.'),
  q('variables','core','A wooden car has light or heavy wheels of equal diameter. Students time three runs down the same ramp. What is the dependent variable?',['wheel mass','wheel diameter','travel time down the ramp','number of wheel types'],2,'Travel time is measured in response to changing wheel mass. Equal diameter is a control.','Dependent means measured outcome.'),
  q('repeatable methods','core','“Put a plant near a window and water it regularly.” What is the most important repair?',['Add exact plant type, position, water volume, schedule and measurement method.','Use more adjectives.','Remove all measurements.','Say the plant should grow well.'],0,'Specified materials, quantities, timing and measurements allow another investigator to reproduce the procedure.','Replace vague words with operational details.'),
  q('reliability','core','Which change most directly improves the reliability of bounce-height data?',['Use five drops at each height and compare the mean and spread.','Change the ball and surface together.','Round every value to the nearest metre.','Remove unexpected readings without checking.'],0,'Multiple trials reveal variation and make the recurring pattern more dependable. Means and spread should be inspected together.','Think repeated evidence, not a fairer variable choice.'),
  q('validity','core','Which change most directly improves validity when comparing absorbency of paper towels?',['Use equal-sized sheets and equal water volumes.','Write readings with more decimal places.','Repeat an unfair method ten times.','Draw a colourful graph.'],0,'Equal area and water volume remove competing explanations, so differences can be linked to towel type.','Validity asks whether the method tests the intended relationship.'),
  q('resolution','core','Which change improves measurement resolution?',['Replace a ruler marked every centimetre with one marked every millimetre.','Repeat the same biased test.','Add another changed variable.','Ask a different scientific question.'],0,'Finer scale divisions improve resolution because the instrument can display smaller increments. Precision instead concerns how closely repeated measurements agree.','Resolution concerns the smallest readable increment.'),
  q('accuracy','core','A balance shows 5.0 g when a certified 10.0 g mass is placed on it. Repeating gives 5.0 g each time. Which judgement is best?',['reliable-looking but inaccurate because of systematic error','valid and accurate','imprecise because values match','unrepeatable because there are repeats'],0,'The readings are consistent but far from the accepted value, indicating a systematic calibration error.','Consistent does not always mean correct.'),
  q('repetitions','core','Results are 14 cm, 15 cm, 44 cm, 14 cm and 15 cm. What should students do first?',['Delete 44 cm immediately.','Check the procedure and equipment, then repeat that condition and record what happened.','Average only the two smallest results.','Claim every future result is 20.4 cm.'],1,'The unusual value should be investigated, not silently removed. A procedural check and additional trial can reveal error or genuine variation.','Treat anomalies transparently.'),
  q('means','core','A toy car takes 4.2 s, 4.4 s and 4.3 s. What is the mean?',['4.0 s','4.3 s','4.9 s','12.9 s'],1,'The sum is 12.9 s; dividing by 3 trials gives 4.3 s. A mean summarises repeats but does not prove fairness.','Add the trials and divide by their number.'),
  q('safety','core','A soil investigation may contain mould. Which plan is safest?',['Sniff samples closely.','Wear gloves, avoid inhaling material, wash hands and follow teacher instructions.','Taste soil to identify it.','Shake dry samples near faces.'],1,'These controls reduce skin contact, inhalation and accidental transfer while preserving the investigation.','Match controls to biological exposure routes.'),
  q('permissions','core','A council allows observations in a reserve but not specimen collection. What may students do?',['Collect small samples anyway.','Observe and record without collecting.','Transfer plants to school.','Assume a science project overrides the condition.'],1,'Permission is conditional. Students may conduct the authorised observation only and must not extend it to collection.','Stay within the exact scope granted.'),
  q('digital tools','core','When is a digital temperature probe especially useful?',['when continuous readings at equal intervals are needed','when no measurements are required','to eliminate every possible error','to replace risk assessment'],0,'A probe can log repeated measurements consistently over time, but it still requires calibration, safe use and a sound plan.','Choose a tool for the data needed.'),
  q('investigation approaches','core','Which approach best studies bird species visiting a wetland without disturbing them?',['controlled feeding experiment without permission','field observations from an approved location using a tally','remove nests for laboratory testing','change the wetland water level'],1,'Permission-based observation can answer a frequency question while minimising disturbance.','Match the method to the question and ethical limits.'),
  q('plan critique','application','Plan: test light on seedlings by placing one in sun and one in a dark cupboard; water only the sunny plant. Best critique?',['It lacks a title.','Water availability is confounded with light, weakening validity.','There are too many repetitions.','Plant growth cannot be measured.'],1,'Because both light and water change, any growth difference has two possible causes. Both plants need the same water schedule.','Identify any second factor that changes.'),
  q('plan critique','application','Plan: measure evaporation from wide and narrow dishes but add 50 mL to one and 100 mL to the other. Best improvement?',['Use equal starting volumes and control location and time.','Use different liquids as well.','Measure only once by eye.','Rename the dishes A and B.'],0,'Equal volume and shared environmental conditions isolate dish width as the changed variable.','Control conditions that also influence evaporation.'),
  q('repeatability','application','Which release instruction is most repeatable for a toy car?',['Give it a little push.','Release the front axle from the 30 cm mark without pushing.','Start somewhere near the top.','Ask each student to choose a method.'],1,'A marked starting position and no-push release define exactly how motion begins, reducing operator variation.','Operationalise position and action.'),
  q('measurement','application','Students measure leaf length. Which method is most consistent?',['Measure from the leaf base to tip along the midrib to the nearest millimetre.','Measure whichever part looks longest in any unit.','Estimate each leaf from across the room.','Include the stem for some leaves only.'],0,'Defining endpoints, alignment and resolution gives every observer the same measurement rule.','State where measurement begins and ends.'),
  q('risk assessment','application','What is the best risk statement for using scissors?',['Scissors are dangerous.','Sharp blades could cut fingers; cut away from the body and carry scissors closed, under supervision.','Be careful.','The experiment has zero risk.'],1,'It links the hazard and possible harm to specific control actions instead of using vague caution.','Risk planning names hazard, harm and control.'),
  q('Country/Place','application','A class wants to photograph a culturally sensitive rock site. Which plan is appropriate?',['Seek guidance and permission before visiting or photographing, and obey restrictions on recording or sharing.','Photograph secretly but omit student names.','Assume public access means unrestricted photography.','Move objects for a clearer image.'],0,'Access does not automatically grant recording or publication rights. Relevant custodians determine culturally appropriate conditions.','Separate physical access from cultural permission.'),
  q('reliability vs validity','application','An unfair test is repeated 20 times and gives very similar results. Which statement is correct?',['The pattern may be reliable, but the test remains invalid for the intended comparison.','Repetition automatically makes it valid.','It is precise, so controls do not matter.','Similar results prove cause and effect.'],0,'Repetition can show consistency, but cannot repair a systematic confound that prevents the question being answered fairly.','Different quality terms answer different questions.'),
  q('resolution vs precision','application','A sensor records to 0.01°C, but repeated readings fluctuate widely. What is true?',['The instrument has fine resolution, but the repeated measurements have poor precision.','Fine resolution guarantees close agreement.','The test is valid because decimals appear.','Wide variation improves precision.'],0,'The display has fine resolution, but the wide spread means the repeated measurements have poor precision and may also indicate uncontrolled conditions.','Small displayed increments and close repeat agreement are different properties.'),
  q('tables','application','Which table entry is scientifically best?',['warm, quick','Trial 2: 18.4 s','pretty fast','approximately some seconds'],1,'A labelled trial with a numerical value and unit is usable evidence. Qualitative phrases are too vague for this timing question.','Record raw data with units.'),
  q('sampling','application','Students compare soil moisture at two sites. Which plan is strongest?',['Take one reading from a chosen wet-looking patch.','Use the same calibrated probe at several randomly selected points at each permitted site.','Use different instruments and depths at each site.','Collect soil without checking permission.'],1,'Multiple unbiased locations and consistent equipment and depth produce a fairer, more representative comparison.','Consider representation, consistency and permission.'),
  q('control group','application','Students test whether detergent scatters pepper on water. What is the strongest control?',['water and pepper touched with a clean, detergent-free swab','a second bowl with twice as much detergent','a bowl with no pepper','a different experiment tomorrow'],0,'The no-detergent condition shows whether touching alone causes movement, isolating detergent as the tested factor.','The control removes the treatment while keeping the action.'),
  q('method detail','application','A method says “Record growth each day.” Which addition best improves repeatability?',['Measure stem height from soil level to highest growing point at 3 pm, to nearest millimetre.','Record it properly.','Use any method that seems right.','Write whether the plant looks nice.'],0,'It fixes the feature, endpoints, time and resolution so different investigators can collect comparable data.','Define exactly what, when and how.'),
  q('permissions','application','Who should advise a school about work at a culturally sensitive location on traditional Lands?',['the first website search result','the relevant First Nations Australian Traditional Owners or land council, alongside site managers as required','any student from another region','only the equipment supplier'],1,'Authority and knowledge are place-specific; relevant Traditional Owners or land councils must guide culturally safe access and practice.','Country/Place permission is locally grounded.'),
  q('causal claims','challenge','A valid repeated test finds plants under blue light grew more than plants under red light. Which conclusion is appropriately cautious?',['Blue light caused all plants everywhere to grow faster.','Under these tested conditions, the blue-light group had greater mean growth; further trials could test whether the pattern generalises.','Red light never supports growth.','The tallest single plant proves the rule.'],1,'The conclusion matches the scope of the evidence and recognises that replication is needed before broad generalisation.','Do not claim beyond the tested conditions.'),
  q('integrated design','challenge','Which plan best tests whether parachute area affects fall time?',['Vary area; keep material, mass and drop height constant; release consistently; time at least five trials per area.','Vary area, mass and height once each.','Use one parachute and predict its time.','Drop different designs outdoors in changing wind.'],0,'This isolates area, defines important controls and uses consistent repeated measurement, supporting validity and reliability.','Look for one changed variable, controls and repeats.'),
  q('plan critique','challenge','Two groups time the same pendulum. Group A times one swing; Group B times 10 swings and divides by 10, repeating five times. Why is B usually stronger?',['Timing more swings reduces the proportional effect of reaction-time error and repeats reveal variation.','Division makes any answer correct.','Group B changes gravity.','One swing cannot occur.'],0,'A longer timing interval makes a similar start/stop delay a smaller fraction of the result, while repeats allow consistency checks.','Consider human reaction time relative to total interval.'),
  q('integrated judgement','challenge','Which statement best summarises a high-quality Year 6 investigation?',['It uses detailed, safe and permitted procedures, changes one test variable where appropriate, measures consistently, controls alternatives and repeats enough to examine a pattern.','It always produces exactly identical numbers.','It includes many variables to save time.','It needs no limitations if digital tools are used.'],0,'Quality combines answerable design, repeatability, safety, permissions, validity, precision and reliability; exact results are neither expected nor sufficient.','Choose the complete, non-absolute principle.')
];

const test = [
  q('variables','assessment','A student changes the number of rubber bands powering a model car and records the distance travelled. Which pair is correct?',['changed: distance; measured: rubber bands','changed: rubber-band number; measured: distance','changed: car; measured: floor','changed: distance; measured: floor type'],1,'Rubber-band number is deliberately varied and distance travelled is the response measured.','Identify intervention then outcome.'),
  q('controls','assessment','To test water depth on water temperature after 20 minutes in sunlight, what must be controlled?',['water depth','final temperature','container material and starting temperature','the pattern in the graph'],2,'Container material and starting temperature could affect heating and must remain consistent while depth changes.','Remove competing explanations.'),
  q('repeatability','assessment','Which instruction makes a paper-plane test most repeatable?',['Throw it normally.','The same thrower launches from behind a taped line using the marked grip; measure nose-to-line distance in metres.','Let everyone invent a throw.','Measure wherever the plane seems to land.'],1,'The launch position, operator, grip and measurement endpoints are defined, allowing close replication.','Look for operational detail.'),
  q('risk','assessment','Students test electrical conductors using low-voltage cells. Which plan is safest?',['Use mains electricity for clearer results.','Use intact low-voltage equipment, avoid short circuits and disconnect cells if wires heat.','Touch hot wires to check temperature.','Test liquids next to unprotected devices.'],1,'Low voltage, equipment checks and a response to heating address electrical and burn risks appropriately.','Avoid mains power and specify controls.'),
  q('permissions','assessment','Permission is granted to count animals on a shoreline but forbids entering nesting zones. What should the method state?',['Observe from authorised areas and use distance tools without entering restricted zones.','Enter briefly if few people are watching.','Collect one egg for accuracy.','Treat permission as optional after arrival.'],0,'A valid method must comply with the exact permission conditions and minimise disturbance.','Permission conditions belong in the procedure.'),
  q('resolution','assessment','A cylinder has 1 mL divisions. Which recorded volume is defensible?',['42 mL','42.0000 mL','about half a litre','42 kg'],0,'The unit and recorded detail align with the instrument scale; extra decimal places would imply unsupported resolution.','Match the recorded detail to the scale resolution.'),
  q('reliability','assessment','Repeated mass readings are 25.2 g, 25.1 g, 25.2 g and 25.1 g. What can be concluded directly?',['The readings are consistent.','The balance is certainly accurate.','The investigation is certainly valid.','The sample has no uncertainty.'],0,'The narrow range supports consistency, but accuracy and validity require separate evidence.','Only infer what repeats show.'),
  q('validity','assessment','Students compare dissolving rates using powdered sugar in warm water and sugar cubes in cold water. What is the flaw?',['Two influential variables change together.','There are too many controls.','Time cannot be measured.','Sugar cannot dissolve.'],0,'Sugar form and water temperature are both altered, so the cause of any rate difference is unclear.','Find the confounding variables.'),
  q('data tables','assessment','Which headings suit a test of fan speed on evaporation?',['Fan setting | Trial 1 mass lost (g) | Trial 2 mass lost (g) | Trial 3 mass lost (g) | Mean (g)','Fast | Slow | Nice','Student | Opinion | Colour','Water | Result | Done'],0,'These headings name the changed condition, repeats, measured quantity and units, and allow a mean to be calculated.','Choose complete quantitative headings.'),
  q('means','assessment','Drop times are 2.6 s, 2.8 s, 2.7 s and 2.7 s. What is the mean?',['2.7 s','5.4 s','10.8 s','2.6 s'],0,'The total 10.8 s divided by four trials is 2.7 s.','Sum then divide by four.'),
  q('anomalies','assessment','Plant heights are 61, 60, 18, 62 and 61 mm. What is the best response?',['Hide 18 mm.','Check for recording or procedural error, repeat if possible, and report any justified treatment of the anomaly.','Change 18 to 60 without checking.','Conclude the mean is impossible.'],1,'Transparent investigation and additional evidence are preferable to automatic deletion or alteration.','Investigate unusual data.'),
  q('approaches','assessment','Which investigation is best answered with repeated field observations rather than changing a variable?',['How many pollinator visits occur at two permitted garden sites?','How does ramp angle affect speed?','How does salt mass affect melting?','How does blade length affect fall time?'],0,'Visit frequency at existing sites can be observed systematically without manipulating the environment; the others suit fair tests.','Decide whether manipulation is necessary.'),
  q('Country/Place','assessment','Why may school and park-manager approval still be insufficient for research at a culturally sensitive site on Country?',['Relevant Traditional Owners may hold cultural authority and set conditions for access, recording or sharing.','Science removes cultural responsibilities.','All public land permits specimen removal.','Student projects need no local guidance.'],0,'Ethical fieldwork recognises place-specific cultural authority and seeks the relevant guidance and permissions.','Administrative access and cultural permission can differ.'),
  q('plan critique','assessment','Plan A repeats an unfair test six times. Plan B fairly controls variables but runs once. Which judgement is best?',['A is valid and B is reliable.','A may be consistent but invalid; B may be valid in design but needs repeats for reliability.','Both are automatically perfect.','Neither can ever be improved.'],1,'Fairness supports validity; repetitions support reliability. Each plan addresses only one of these needs.','Separate validity from reliability.'),
  q('measurement','assessment','To compare cooling rates, which procedure gives the strongest measurements?',['Record temperature with the same calibrated probe every minute for 15 minutes from equal starting temperatures.','Touch each cup occasionally.','Use different thermometers at unknown times.','Write hot or cold once.'],0,'Consistent equipment, intervals, duration and starting conditions provide repeatable quantitative data.','Look for calibrated equipment and fixed timing.'),
  q('integrated design','assessment','Which investigation plan is strongest?',['Question, variable table, equipment quantities, risk controls, permissions, numbered steps, units, repeated trials and prepared results table','A prediction and one observation only','Many changes with no controls','A detailed conclusion written before data collection'],0,'A complete plan connects the question to fair procedures, safety, lawful and respectful access, reproducible measurement and organised repeated data.','Select the plan that covers the whole inquiry.')
];

const worksheet = [
  {question:'Plan a fair test of how paper-helicopter blade length affects fall time. State the changed, measured and three controlled variables.',modelAnswer:'Change blade length; measure fall time in seconds. Control paper type, helicopter mass/design apart from blade length, drop height and release method.'},
  {question:'Rewrite “Drop each helicopter and see what happens” as a repeatable three-step method.',modelAnswer:'Mark a 2.0 m drop height. Hold each helicopter at the mark and release without pushing. Time from release to first floor contact with the same stopwatch; repeat five times for each blade length.'},
  {question:'Create suitable table headings for three blade lengths, five trials and a mean.',modelAnswer:'Blade length (cm) | Fall time Trial 1 (s) | Trial 2 (s) | Trial 3 (s) | Trial 4 (s) | Trial 5 (s) | Mean fall time (s).'},
  {question:'Explain why repeating an unfair test does not make it valid.',modelAnswer:'Repeats may show a consistent pattern, but if another variable changes systematically, the effect still cannot be attributed to the intended changed variable.'},
  {question:'Distinguish reliability, validity, precision and resolution in one sentence each.',modelAnswer:'Reliability is whether a pattern is supported consistently when an investigation is repeated. Validity is whether the method fairly answers the intended question. Precision is how closely repeated measurements agree. Resolution is the smallest increment an instrument can detect or display.'},
  {question:'A car travels 82, 80, 81, 117 and 81 cm. Describe a scientifically responsible response.',modelAnswer:'Check whether 117 cm resulted from a recording, release or equipment problem; repeat the condition; retain and report raw data, and only exclude the value with a stated evidence-based reason.'},
  {question:'Write a hazard–harm–control statement for heating water in glassware.',modelAnswer:'Hot water and glass can cause burns or cuts; use intact heatproof glassware on a heatproof mat, wear eye protection and have teacher-supervised handling and cooling.'},
  {question:'Explain what permissions may be needed before ecological observations at a culturally sensitive location on Country/Place.',modelAnswer:'Seek school and site-manager approval plus guidance and required permission from the relevant Traditional Owners or land council. Follow conditions about access, sensitive areas, collecting, photography, data and sharing.'},
  {question:'Critique this plan: “Put one bean plant in sunlight with 50 mL water daily and one in darkness with 10 mL weekly; compare height after a month.”',modelAnswer:'Both light and water change, so the comparison is confounded. Give equivalent plants the same measured water, soil, pot and temperature conditions, change only light, use several plants per condition and measure consistently.'},
  {question:'Choose appropriate equipment, units and resolution for measuring 20 mL water, seedling height and water temperature.',modelAnswer:'Use a measuring cylinder in mL at its scale resolution; a millimetre ruler for height recorded in mm; and a suitable thermometer or probe in °C at its displayed resolution.'},
  {question:'Design a no-treatment control for testing detergent on pepper floating on water and explain its purpose.',modelAnswer:'Touch an identical water-and-pepper dish with an equally handled clean swab containing no detergent. It shows whether touching or the swab, rather than detergent, moves the pepper.'},
  {question:'Write a brief investigation checklist another Year 6 student could use before collecting data.',modelAnswer:'Confirm question and prediction; label changed, measured and controlled variables; list exact equipment; gain permissions; assess risks and controls; number detailed steps; state units and measurement rules; plan at least three repeats; prepare a labelled results table.'}
];

const topicSections = [
  {heading:'The planning chain',body:'A strong investigation links an answerable question to a prediction, variables, permissions, risk controls, equipment, numbered method, measurements, repetitions, table and evidence-based conclusion.'},
  {heading:'Variables and fair tests',body:'The independent variable is deliberately changed; the dependent variable is measured; controlled variables are other factors kept consistent. A control group provides a baseline without the treatment where appropriate.'},
  {heading:'Make the method repeatable',body:'State materials and quantities, exact setup, ordered actions, timing, measurement endpoints, units, instrument resolution and number of trials. “Do it again” cannot repair a vague method.'},
  {heading:'Measure and record well',body:'Choose equipment suited to the quantity and record only the detail its scale or display supports. Prepare table headings with the changed condition, trial numbers, measured quantity and unit before collecting data.'},
  {heading:'Reliability, validity, precision and resolution',body:'Reliability concerns whether a pattern is supported when an investigation is repeated; validity concerns whether the design fairly answers the question; precision concerns close agreement among repeated measurements; resolution is the smallest increment an instrument detects or displays. More repeats reveal spread but do not fix a confound.'},
  {heading:'Repetitions and unusual results',body:'Use at least three trials where practical, calculate a useful mean and inspect spread. Investigate anomalies, repeat if possible and document decisions instead of silently deleting inconvenient values.'},
  {heading:'Risk and safe practice',body:'Identify the hazard, possible harm and specific control. Use age-appropriate equipment, supervision and protective measures. Stop when conditions differ from the approved safe plan.'},
  {heading:'Permissions on Country/Place',body:'Before fieldwork, seek required administrative and cultural permissions. Consult relevant Traditional Owners or land councils and follow guidance about sensitive locations, access, collecting, photography, data and sharing.'},
  {heading:'Choosing an approach',body:'Fair tests suit causal questions; systematic field observations suit patterns in place; research supplies existing evidence; digital tools support data collection; simulations explore unsafe or inaccessible systems. Each approach has limits.'},
  {heading:'Plan critique',body:'Ask: Can the question be answered? Is one factor changed? Are alternatives controlled? Are equipment, units and steps explicit? Are repeats sufficient? Are safety and permissions addressed? Does the table capture the needed evidence?'}
];

const vocabulary = [
  {term:'independent variable',definition:'the factor deliberately changed in a fair test'},
  {term:'dependent variable',definition:'the outcome measured or observed'},
  {term:'controlled variable',definition:'another factor kept consistent so it does not confound the test'},
  {term:'validity',definition:'how well a method fairly tests the intended question'},
  {term:'reliability',definition:'how consistently a pattern appears across repeated evidence'},
  {term:'precision',definition:'how closely repeated measurements agree with one another'},
  {term:'resolution',definition:'the smallest increment an instrument can detect or display'},
  {term:'hazard',definition:'a source or situation with potential to cause harm'},
  {term:'risk control',definition:'an action that reduces the likelihood or consequence of harm'},
  {term:'confounding variable',definition:'an uncontrolled factor that changes alongside the tested factor'},
  {term:'control group',definition:'a baseline condition without the tested treatment'}
];

const misconceptions = [
  {claim:'The controlled variable is the result.',correction:'The dependent variable is measured; controlled variables are other influential conditions kept consistent.'},
  {claim:'All variables must be identical.',correction:'The independent variable must change deliberately; the other influential conditions should remain consistent.'},
  {claim:'Repeatable means every result is exactly the same.',correction:'Small variation is expected. Repeatability means enough detail to reproduce the method and examine whether a consistent pattern occurs.'},
  {claim:'Repeating a test makes it valid.',correction:'Repeats support reliability but cannot repair a confound or systematically unfair comparison.'},
  {claim:'Public access removes the need for permission on Country/Place.',correction:'Access, collecting, recording and sharing may require separate administrative and culturally informed permissions.'}
];

const importantQA = [
  {question:'How many repetitions are enough?',answer:'Use at least three where practical, and more when natural variation or measurement uncertainty is substantial.'},
  {question:'Does a precise instrument guarantee a good test?',answer:'No. Fine resolution does not guarantee valid design, accurate calibration or reliable results.'},
  {question:'Should an unusual result be deleted?',answer:'Not automatically. Check, repeat and document a defensible evidence-based decision.'},
  {question:'Who can give cultural guidance for fieldwork on Country/Place?',answer:'The relevant Traditional Owners or land council; authority and appropriate practice are specific to place.'}
];

const steps = ['Write the answerable investigation question.','Identify changed, measured and controlled variables.','Seek permissions and assess hazards, harms and controls.','List equipment with quantities and suitable measuring resolution.','Write an ordered method with exact setup, timing, units and repetitions.','Prepare a labelled table, conduct consistently and record raw data.','Check means, spread and anomalies; evaluate reliability, validity and limitations.'];

const slides = [
  {title:'Curriculum',kicker:'AC9S6I02',body:[metadata.descriptor]},
  {title:'Learning intention',body:[metadata.learningIntention,...metadata.successCriteria]},
  {title:'The investigation plan',body:[topicSections[0].body,'Question → variables → permissions and safety → method → data → evaluation.']},
  {title:'Fair-test variables',body:[topicSections[1].body,'Quick check: In a ramp-height test, name the changed, measured and two controlled variables.']},
  {title:'Write a repeatable method',body:[topicSections[2].body,'Replace “some”, “regularly” and “carefully” with quantities, intervals and observable actions.']},
  {title:'Equipment, units and tables',body:[topicSections[3].body,'Heading frame: Condition (unit) | Trial 1 outcome (unit) | Trial 2 | Trial 3 | Mean.']},
  {title:'Four quality ideas',body:[topicSections[4].body,'Reliable = repeat-supported pattern; valid = fair answer; precise = close repeat agreement; resolution = smallest detectable or displayed increment.']},
  {title:'Repeats and anomalies',body:[topicSections[5].body,'Never hide a surprising value: check → repeat → document → justify.']},
  {title:'Risk and safe conduct',body:[topicSections[6].body,'Frame: Hazard could cause harm; reduce risk by specific control.']},
  {title:'Permissions on Country/Place',body:[topicSections[7].body,'Permission may separately cover entry, collection, photography, sensitive knowledge and publication.']},
  {title:'Important questions and answers',body:importantQA.map(({question,answer}) => `${question} ${answer}`)},
  {title:'Exit ticket',body:['Plan a test of paper-helicopter blade length.','State variables, one risk control, equipment and units, exact release method and number of trials.','Explain separately how your plan supports validity and reliability.']}
];

if (practice.length !== 48) throw new Error(`AC9S6I02 practice count ${practice.length}; expected 48`);
if (test.length !== 16) throw new Error(`AC9S6I02 test count ${test.length}; expected 16`);
if (worksheet.length !== 12) throw new Error(`AC9S6I02 worksheet count ${worksheet.length}; expected 12`);
for (const [bankName, bank] of [['practice', practice], ['test', test]]) bank.forEach((item,index) => {
  if (item.answers.length !== 4) throw new Error(`${bankName} ${index + 1}: expected four answers`);
  if (!Number.isInteger(item.correct) || item.correct < 0 || item.correct > 3) throw new Error(`${bankName} ${index + 1}: invalid correct index`);
});

export default {
  code: metadata.code,
  descriptor: metadata.descriptor,
  title: metadata.title,
  learningIntention: metadata.learningIntention,
  successCriteria: metadata.successCriteria,
  vocabulary,
  steps,
  topicSections,
  misconceptions,
  importantQA,
  assessmentHints: ['Name the changed, measured and controlled variables precisely.','Use quantities, units, timing and measurement endpoints in methods.','Separate comments about validity, reliability, precision and instrument resolution.','Link every risk control to a stated hazard and possible harm.','State and follow required permissions before work on Country/Place.','Use repeats and means without hiding spread or unexplained anomalies.'],
  exitTicket: 'Plan a safe paper-helicopter investigation with variables, controls, units, repetitions and enough procedural detail for another group to repeat it.',
  masteryEvidence: 'The student plans a safe, permitted, fair and repeatable investigation, records suitable measurements and evaluates validity, reliability, repeat-measurement precision and instrument resolution as distinct qualities.',
  practice,
  test,
  worksheet,
  slides
};
