export const YEAR8_SCIENCE_I_CONCEPTS = {
  AC9S8I01: [
    { evidence: "Seedlings under brighter lamps appear taller, but the lamps also produce different amounts of heat", question: "Which question is most directly testable in a controlled investigation?", correct: "How does measured light intensity affect seedling height when temperature and plant type are controlled?", wrong: ["Why do plants like some lamps better than others?", "Are bright lamps always best for every living thing?"], summary: "A testable question names a measurable changed variable, response variable and controlled system.", hint: "Look for one measured cause, one measured response and stated controls." },
    { evidence: "A student notices that sugar dissolves faster in one warm beaker than in one cold beaker", question: "Which prediction is testable without claiming more than the observation supports?", correct: "If water temperature increases, the time for a fixed mass of sugar to dissolve will decrease", wrong: ["Warm water always makes every substance disappear", "The warm beaker proves heat is the only factor that affects dissolving"], summary: "A prediction states a measurable expected pattern without treating one observation as proof.", hint: "Choose an outcome that could be measured and compared." },
    { evidence: "Solar-panel output rises as a lamp is moved closer", question: "Which hypothesis includes a scientific reason?", correct: "Reducing lamp distance will increase output because more light energy reaches each area of the panel", wrong: ["The closest lamp will win because closer is better", "Output will change, although there is no need to state how or why"], summary: "A hypothesis links variables with a reason that can be tested.", hint: "Find the response direction and the scientific mechanism." },
    { evidence: "Woodlice gather in the damp half of a choice chamber", question: "Which follow-up question separates moisture from light?", correct: "When both halves have equal light, how does surface moisture affect the number of woodlice in each half?", wrong: ["Do woodlice prefer nice places?", "Why did all woodlice evolve to hate light?"], summary: "A useful follow-up isolates the variable of interest from a possible confounding variable.", hint: "Hold light constant and vary moisture." },
    { evidence: "A local creek has fewer aquatic insects downstream from a building site than upstream", question: "Which question can the class investigate without assuming the cause?", correct: "How do turbidity and aquatic-insect counts compare at matched upstream and downstream sites?", wrong: ["How badly did the building company destroy the creek?", "Why are downstream insects weaker than upstream insects?"], summary: "Investigable questions measure a pattern before assigning an untested cause.", hint: "Avoid wording that decides the conclusion in advance." },
    { evidence: "Dark-coloured cans cool more quickly in an initial trial, but their starting temperatures differed", question: "Which revised question supports a fair test?", correct: "How does can surface colour affect cooling time when volume, material and starting temperature are kept constant?", wrong: ["Which can looks coolest after lunch?", "Do dark colours cause all objects to become cold?"], summary: "The revised question identifies the independent variable, dependent variable and important controls.", hint: "Make starting temperature equal before comparing colour." },
    { evidence: "Ten students who sleep longer tend to score higher on a reaction-time test", question: "Which prediction fits a correlation study?", correct: "In a larger similar sample, longer reported sleep may be associated with faster reaction times", wrong: ["Making any student sleep longer will certainly improve every test score", "Reaction time controls how many hours a person sleeps"], summary: "A correlational prediction describes an association, not proven causation.", hint: "Use cautious language because sleep was observed, not assigned." },
    { evidence: "Shells collected near a river mouth vary in thickness", question: "Which descriptive question is appropriate when no variable will be deliberately changed?", correct: "How does shell thickness vary among sampling locations along the river mouth?", wrong: ["What chemical definitely caused every thin shell?", "How can we force shells to become identical?"], summary: "Descriptive investigations can map variation without requiring a manipulated variable.", hint: "Ask what varies across clearly defined locations." },
    { evidence: "A battery-powered car travels different distances on rough and smooth tracks", question: "Which operational definition makes the outcome measurable?", correct: "Measure distance from the start line to the front axle when the car stops", wrong: ["Judge whether each run looks successful", "Record which track feels more difficult"], summary: "An operational definition states exactly how a variable will be measured.", hint: "Choose a rule another group could apply in the same way." },
    { evidence: "Three brands of paper towel absorb different amounts in an informal demonstration", question: "Which question is specific enough to test?", correct: "How many millilitres of water does one 20 by 20 centimetre sheet of each brand absorb before dripping?", wrong: ["Which paper towel is the best?", "Why is the advertised brand scientifically superior?"], summary: "A precise question defines the samples, measurement and endpoint.", hint: "Look for fixed sheet size and a measurable absorption rule." },
  ],
  AC9S8I02: [
    { evidence: "A class will test how pendulum length affects period", question: "Which plan gives a reproducible independent variable?", correct: "Measure pivot-to-centre-of-bob lengths of 20, 40, 60 and 80 centimetres", wrong: ["Use short, medium and long strings chosen by each group", "Change the string length and bob mass together"], summary: "A reproducible plan defines exact values and changes one intended variable.", hint: "Choose measured lengths that another class can copy." },
    { evidence: "Students compare dissolving time at four water temperatures", question: "Which control is most important for a fair comparison?", correct: "Use the same solute mass, particle size, water volume and stirring method each time", wrong: ["Use a different solute at each temperature", "Stop timing each trial when the observer expects it to finish"], summary: "Controls prevent other factors from explaining differences in dissolving time.", hint: "Keep everything except water temperature consistent." },
    { evidence: "A method says, ‘Heat the liquid and record what happens’", question: "Which revision makes the method repeatable?", correct: "State the liquid volume, heating power, time intervals, measurements and stopping point", wrong: ["Add more scientific words without adding quantities", "Let each group decide its own endpoint after heating"], summary: "Repeatable methods specify quantities, equipment, timing and endpoints.", hint: "Ask whether another group could reproduce each action." },
    { evidence: "A lamp used in a solar-cell test becomes hot enough to burn skin", question: "Which risk assessment is complete?", correct: "Hot lamp could burn skin; use a guard, allow cooling and switch off before adjustment", wrong: ["Lamp: medium risk", "Be careful because laboratory equipment can be dangerous"], summary: "A risk assessment links a hazard to harm and a practical control.", hint: "Find hazard, consequence and control in one response." },
    { evidence: "Students propose collecting biological material from a culturally significant site", question: "What must the plan include before sampling?", correct: "Seek guidance and permission from the appropriate custodians and follow place-specific protocols", wrong: ["Collect first because school science automatically has permission", "Avoid recording the source so cultural responsibilities do not apply"], summary: "Authority and Country or Place protocols shape whether and how sampling may occur.", hint: "Scientific interest does not replace permission." },
    { evidence: "A group repeats one uncontrolled trial ten times", question: "Which evaluation of the plan is correct?", correct: "Repetition estimates variation, but it cannot repair a systematic unfairness in the method", wrong: ["Ten repeats automatically make every variable controlled", "Repeats are unnecessary whenever the first result matches the prediction"], summary: "Replication improves evidence about variation but does not remove confounding variables.", hint: "Separate consistency from fairness." },
    { evidence: "To compare insulation, students use cups with different sizes and lids", question: "Which redesign isolates insulation material?", correct: "Use identical lidded cups, equal water volumes and starting temperatures, changing only the insulation", wrong: ["Use more hot water in the cup with thinner insulation", "Remove every lid so evaporation differs between trials"], summary: "A fair design changes insulation while controlling container and water conditions.", hint: "Only insulation should differ." },
    { evidence: "A field survey may disturb nesting birds", question: "Which method reduces ethical impact while answering the question?", correct: "Observe from a set distance for fixed periods and stop if birds show disturbance", wrong: ["Approach nests closely so counts are easier", "Move eggs briefly because no animal is being killed"], summary: "Ethical methods minimise disturbance and include clear stopping rules.", hint: "Choose non-invasive observations and a welfare trigger." },
    { evidence: "A student assumes lamp distance is a measure of light intensity", question: "How should this assumption be handled?", correct: "Record the assumption and, if possible, measure intensity with a light sensor at each distance", wrong: ["Hide the assumption because plans should appear certain", "Treat distance and intensity as identical under all conditions"], summary: "Plans state important assumptions and test them where practical.", hint: "Replace a proxy with a direct measurement if possible." },
    { evidence: "A class has time for twelve plant pots to compare two fertilisers", question: "Which allocation best reduces position bias?", correct: "Randomly assign six similar pots to each treatment and rotate their bench positions", wrong: ["Put one treatment beside the window and the other beside the door", "Let students choose treatments after seeing plant size"], summary: "Random allocation and balanced positions reduce systematic differences between groups.", hint: "Prevent starting condition or location from favouring a treatment." },
  ],
  AC9S8I03: [
    { evidence: "A measuring cylinder has marks every 1 millilitre and the meniscus is halfway between 36 and 37", question: "Which record is justified?", correct: "36.5 mL, read at eye level from the bottom of the meniscus", wrong: ["36.5000 mL because more decimals mean greater precision", "About 40 mL because scale marks are optional"], summary: "The reading and digits should match the scale resolution and correct meniscus method.", hint: "Estimate only one sensible digit beyond the graduations." },
    { evidence: "A leaf is about 6 centimetres long", question: "Which instrument is most suitable?", correct: "A millimetre ruler with a range longer than the leaf", wrong: ["A 50-metre tape marked every metre", "A micrometer designed for very small thicknesses"], summary: "Instrument range and resolution must suit the size and required precision.", hint: "Choose an instrument that spans the leaf and gives useful detail." },
    { evidence: "A digital balance displays 12.34 grams for the same object several times", question: "What can be concluded from the display alone?", correct: "Its resolution is 0.01 g, but calibration is needed before claiming accuracy", wrong: ["The mass is certainly accurate because the display is digital", "The last two digits prove the balance has no uncertainty"], summary: "Resolution describes display detail; accuracy also depends on calibration and method.", hint: "Do not confuse decimal places with closeness to the true value." },
    { evidence: "Timing one pendulum swing gives values that vary with reaction time", question: "Which method improves the timing precision?", correct: "Time 20 swings and divide by 20, repeating the measurement", wrong: ["Round each single-swing time to the nearest whole second", "Start timing before release and stop whenever convenient"], summary: "Timing many cycles reduces the relative effect of start-stop reaction time.", hint: "Make the measured interval much longer than the timing delay." },
    { evidence: "Temperatures are recorded as 21.4, 22, 23.17 and 24 degrees Celsius with the same thermometer", question: "What should be corrected?", correct: "Use consistent precision justified by the thermometer's graduations", wrong: ["Remove all units to make the table shorter", "Add five decimal places to every value regardless of the scale"], summary: "Measurements from one instrument should use consistent, justified precision and units.", hint: "Check whether the number of digits matches the instrument." },
    { evidence: "A thermometer range is minus 10 to 110 degrees Celsius, but a furnace is near 600 degrees Celsius", question: "Why is this thermometer unsuitable?", correct: "The expected value exceeds its range and could damage the instrument or give no valid reading", wrong: ["Its range is too wide to measure any temperature", "All thermometers can measure any temperature if held longer"], summary: "An instrument must safely include the expected measurement within its range.", hint: "Compare 600 degrees with the instrument maximum." },
    { evidence: "A student views a ruler from an angle and records an object endpoint", question: "Which procedure reduces parallax error?", correct: "Place the scale beside the object and view the endpoint perpendicular to the ruler", wrong: ["View from a steeper angle so the marks look farther apart", "Take extra decimal places from the angled view"], summary: "A perpendicular line of sight reduces apparent displacement against a scale.", hint: "Align the eye directly above the reading." },
    { evidence: "A pH strip changes to a colour between the chart values 6 and 7", question: "Which report is honest?", correct: "The pH is approximately between 6 and 7, limited by the colour scale", wrong: ["The pH is exactly 6.500 because the colour looked halfway", "The pH must be neutral because it is near 7"], summary: "Reported precision cannot exceed what the comparison scale can resolve.", hint: "Use approximate language for a coarse colour match." },
    { evidence: "Five mass readings are 8.42, 8.41, 8.43, 8.42 and 9.87 grams", question: "What should happen before calculating a final value?", correct: "Check the 9.87 g reading, the balance and the sample, then document whether it is repeated or retained", wrong: ["Delete 9.87 immediately because it spoils the average", "Average only the two readings that are exactly equal"], summary: "An unusual measurement is investigated transparently before treatment.", hint: "Check for a recording, equipment or sample change." },
    { evidence: "Students must measure 25.0 millilitres accurately for a solution", question: "Which equipment is best?", correct: "A calibrated 25.0 mL volumetric pipette used correctly", wrong: ["A 250 mL beaker with marks every 50 mL", "A drinking cup filled to an estimated line"], summary: "Volumetric equipment gives suitable precision for a specified liquid volume.", hint: "Choose the equipment designed to deliver that exact volume." },
  ],
  AC9S8I04: [
    { evidence: "Water temperature is measured every minute while a beaker cools", question: "Which representation best reveals change over time?", correct: "A line graph with time on the horizontal axis and temperature with units on the vertical axis", wrong: ["A pie chart showing each temperature as a share of the total", "An unlabelled picture of the beaker"], summary: "A line graph clearly shows how a continuous measurement changes with time.", hint: "Time is the independent variable and belongs on the horizontal axis." },
    { evidence: "A survey records the number of students choosing four transport types", question: "Which display supports category comparison?", correct: "A bar graph with separated bars and a labelled frequency axis", wrong: ["A continuous line joining transport categories in arbitrary order", "A scatter plot requiring two numerical variables"], summary: "Separated bars compare frequencies across distinct categories.", hint: "The transport types are categories, not a continuous scale." },
    { evidence: "Plant height is compared with fertiliser concentration across 30 pots", question: "Which representation best shows their relationship?", correct: "A scatter plot of concentration against height, with a trend line if justified", wrong: ["A pie chart of all heights added together", "A decorative drawing of the tallest plant only"], summary: "A scatter plot reveals association between two numerical variables.", hint: "Both variables are measured numbers." },
    { evidence: "A graph starts its vertical axis at 98 and makes a rise from 99 to 100 look enormous", question: "How should the graph be presented responsibly?", correct: "Clearly mark the truncated axis and explain the small absolute difference", wrong: ["Hide the axis labels so viewers focus on the shape", "Claim the quantity doubled because the bar looks twice as tall"], summary: "Truncated axes require clear signalling because they visually magnify differences.", hint: "Compare the visual change with the actual values." },
    { evidence: "A table lists distance in one column and power output in another", question: "Which heading pair makes the data interpretable?", correct: "Distance from lamp (cm) and power output (mW)", wrong: ["Input and result, with no units", "Centimetres and milliwatts, with no variable names"], summary: "Table headings identify both the measured variable and its unit.", hint: "A reader needs to know what was measured and how it was measured." },
    { evidence: "A particle model shows gas particles as coloured circles with arrows", question: "Which note states a useful limitation?", correct: "The arrows show motion direction, but particle size, spacing and speed are not necessarily to scale", wrong: ["The diagram proves gas particles are coloured circles", "Because it is simplified, the model has no scientific use"], summary: "Models can reveal a relationship while simplifying scale and appearance.", hint: "State what the model helps show and what it does not reproduce literally." },
    { evidence: "Rainfall across a catchment is recorded at 20 mapped stations", question: "Which representation best reveals spatial variation?", correct: "A map using a labelled colour scale or proportional symbols at station locations", wrong: ["An alphabetical list that removes every location", "A pie chart that combines all stations into one total"], summary: "A mapped display preserves location and shows spatial patterns.", hint: "Choose a representation that keeps geographic position." },
    { evidence: "Two classes have the same mean test result but very different spreads", question: "Which display reveals the difference hidden by the mean?", correct: "Side-by-side dot plots or box plots on the same scale", wrong: ["One bar for each class mean only", "Two unrelated diagrams with different unlabelled scales"], summary: "Distribution plots show spread and clustering that a mean alone conceals.", hint: "The display must show individual values or distribution summaries." },
    { evidence: "A graph has points at uneven time intervals of 0, 1, 5 and 20 minutes", question: "How should positions on the time axis be spaced?", correct: "In proportion to the actual time intervals", wrong: ["Equally spaced because there are four readings", "Placed in order of result size rather than time"], summary: "A numerical axis uses a consistent scale so distance represents quantity.", hint: "The gap from 5 to 20 minutes should be larger than from 0 to 1." },
    { evidence: "A complex ecosystem diagram includes every species and hides the energy pathway under study", question: "Which revision improves the model for this purpose?", correct: "Retain the relevant organisms and labelled energy-flow arrows, and state what was omitted", wrong: ["Add more decorative organisms until no pathway is visible", "Remove arrow directions because all species exchange energy equally"], summary: "A purposeful model highlights the target relationship and discloses simplifications.", hint: "Select detail according to the question the model must answer." },
  ],
  AC9S8I05: [
    { evidence: "Solar-cell power generally rises from 20 to 100 light units, except one low result at 80 units", question: "Which analysis is most defensible?", correct: "Report the overall positive relationship and investigate the anomalous 80-unit result", wrong: ["Delete the low result without mentioning it", "Say there is no pattern because one point differs"], summary: "Analysis reports the main trend while examining rather than hiding anomalies.", hint: "Describe both the broad direction and the unusual point." },
    { evidence: "Ice-melt times are 12, 13, 12, 14 and 37 minutes under the same condition", question: "What is the best next step?", correct: "Check the 37-minute trial for a procedural or recording difference and repeat if justified", wrong: ["Remove 37 solely because it changes the mean", "Conclude that all melt times are random"], summary: "An outlier prompts a documented check before exclusion or repetition.", hint: "Look for a specific reason the unusual trial differed." },
    { evidence: "Cities with more firefighters often have greater fire damage", question: "Why does this correlation not show that firefighters cause damage?", correct: "Larger fires can cause both more damage and deployment of more firefighters", wrong: ["Any positive correlation proves the first variable causes the second", "Fire damage cannot be measured numerically"], summary: "A third factor can explain why two variables change together.", hint: "Ask what might cause both observed quantities to increase." },
    { evidence: "Plant growth rises from 0 to 4 grams of fertiliser, then falls at 8 grams", question: "Which statement describes the pattern?", correct: "Growth increases to an apparent optimum, then decreases at the highest dose", wrong: ["More fertiliser always produces more growth", "Fertiliser has no relationship with growth because the trend is not a straight line"], summary: "Scientific relationships may be curved and include an optimum rather than a constant trend.", hint: "Describe what happens before and after the peak." },
    { evidence: "A treatment group averages 18 cm and a control group 17 cm, but both range from 10 to 25 cm", question: "What limits a strong conclusion?", correct: "The difference in means is small compared with the overlapping variation", wrong: ["Any one-centimetre mean difference proves the treatment works", "Ranges should be ignored whenever means are available"], summary: "Group difference should be interpreted alongside spread and overlap.", hint: "Compare the mean gap with variation within each group." },
    { evidence: "Every fifth quadrat along one path contains fewer weeds toward the shaded end", question: "Which conclusion stays within the evidence?", correct: "Along this path, weed abundance decreased as shade increased", wrong: ["Shade is proven to kill every weed species everywhere", "The data show weeds caused the trees to grow"], summary: "A conclusion should match the sampled location, variables and observational design.", hint: "Avoid extending one transect to all habitats or claiming causation." },
    { evidence: "Reaction time improves over five repeated attempts with the same participants", question: "Which alternative explanation should be considered?", correct: "Participants may improve through practice rather than because of the intended treatment", wrong: ["Repeated measurements can never show a trend", "The last result is automatically the only valid result"], summary: "Practice effects can create a time trend unrelated to the treatment.", hint: "Consider what participants learn during repeated trials." },
    { evidence: "Bacterial colony counts are 42, 39 and 45 for control plates, and 3, 5 and 4 for treated plates", question: "Which pattern is supported?", correct: "Treated plates consistently have far fewer colonies under the tested conditions", wrong: ["The treatment eliminates every bacterium in all environments", "The groups are equivalent because neither set has identical repeats"], summary: "The repeated values support a large group difference while the conclusion remains conditional.", hint: "Compare the ranges, then limit the claim to this test." },
    { evidence: "Monthly temperature and electricity use rise together in summer but separate in winter", question: "Which analysis is useful?", correct: "Describe the seasonal relationship and test other influences such as heating type and daylight", wrong: ["Fit one causal claim to every month regardless of the changed pattern", "Discard winter because it conflicts with the summer relationship"], summary: "Changing patterns can signal additional variables or mechanisms.", hint: "Use the conflicting season to refine the explanation." },
    { evidence: "A graph appears to show a steep increase, but the vertical scale covers only 50.0 to 50.5", question: "What should the analyst do?", correct: "Quantify the actual change and consider whether it is meaningful relative to uncertainty", wrong: ["Describe the increase as huge because the line is steep", "Ignore axis values and use only the line angle"], summary: "Trend size depends on numerical scale and measurement uncertainty, not visual steepness alone.", hint: "Read the values before judging the effect." },
  ],
  AC9S8I06: [
    { evidence: "A lamp-heating test claims light intensity alone changed solar output, but cell temperature also rose", question: "How should the conclusion be revised?", correct: "State that output rose under the combined conditions and repeat while monitoring or controlling temperature", wrong: ["Keep the causal claim because the result matched the prediction", "Call the issue human error without explaining its effect"], summary: "A confounding variable narrows the supported claim and guides a specific follow-up.", hint: "Name the uncontrolled variable and how to test its influence." },
    { evidence: "A balance reads every standard mass 0.50 grams too high", question: "What type of problem is this and what is its effect?", correct: "A systematic calibration error shifts all mass readings upward", wrong: ["Random error makes values equally likely to be high or low", "The repeated offset increases confidence that the readings are accurate"], summary: "A consistent calibration offset is systematic and biases every measurement in one direction.", hint: "The same error direction occurs each time." },
    { evidence: "Two well-controlled studies report opposite effects of the same material", question: "What is the strongest evaluation?", correct: "Compare methods, samples and uncertainty, then seek replication before choosing a broad conclusion", wrong: ["Keep only the study that matches the preferred claim", "Average the written conclusions without examining evidence"], summary: "Conflicting evidence should be investigated through study quality, context and replication.", hint: "Look for reasons the studies could differ before resolving the conflict." },
    { evidence: "A medicine trial includes six volunteers with no comparison group", question: "Which limitation most affects the claim that the medicine caused improvement?", correct: "Without a suitable comparison group, recovery or placebo effects cannot be separated from treatment effect", wrong: ["Six volunteers guarantee the result applies to everyone", "The medicine name is not technical enough"], summary: "A comparison group helps distinguish treatment effects from other causes of change.", hint: "Ask what would have happened without the treatment." },
    { evidence: "A temperature probe gives closely grouped readings that are all two degrees above a calibrated reference", question: "How should its performance be described?", correct: "It is precise in these repeats but inaccurate because of a systematic offset", wrong: ["It is accurate because the readings agree with one another", "It is neither precise nor accurate because digital probes cannot be calibrated"], summary: "Precision is repeatability; accuracy is closeness to an accepted value.", hint: "Separate agreement among readings from agreement with the reference." },
    { evidence: "A class concludes a fertiliser has no effect because p equals 0.08 in a small noisy sample", question: "Which evaluation is appropriately cautious?", correct: "The study did not provide strong evidence of an effect, but uncertainty and low power mean no effect was not proven", wrong: ["The result proves the fertiliser can never affect plants", "A p-value states the percentage of plants that responded"], summary: "Failure to find strong evidence is not proof that an effect is absent.", hint: "Distinguish ‘not detected’ from ‘does not exist’." },
    { evidence: "A method measures water loss only on one unusually windy afternoon", question: "Which improvement addresses representativeness?", correct: "Repeat across multiple days and conditions using the same defined method", wrong: ["Record the windy result to more decimal places", "Repeat the calculation on the same single reading"], summary: "Sampling across relevant conditions tests whether a result represents the wider pattern.", hint: "Gather new observations, not extra arithmetic on one observation." },
    { evidence: "An insulation study uses a thermometer touching the metal cup wall", question: "Which specific error and improvement are relevant?", correct: "Wall contact may measure cup temperature; suspend the probe centrally at a fixed depth", wrong: ["Human error occurred, so replace every student", "Use a brighter-coloured thermometer to improve accuracy"], summary: "Evaluation identifies the mechanism of error and a targeted procedural correction.", hint: "Consider what the probe is actually touching." },
    { evidence: "A model accurately predicts low-speed motion but fails near very high speeds", question: "Which conclusion about the model is sound?", correct: "It remains useful within its tested domain, but its limits must be stated and another model may be needed outside it", wrong: ["One failure makes every earlier prediction worthless", "A successful model must be a literal copy of reality"], summary: "Models are evaluated against purpose, domain and known limitations.", hint: "A limitation can restrict use without removing all value." },
    { evidence: "A study finds microplastic particles in all five sampled fish from one estuary", question: "Which unanswered question is the best next step?", correct: "How do particle levels vary among species, seasons and multiple estuaries using larger samples?", wrong: ["Why do all fish in the world contain exactly the same amount?", "How can the five results be used to avoid further sampling?"], summary: "A follow-up targets sample size, variation and generalisability revealed by the first study.", hint: "Test whether the local finding holds across more organisms and places." },
  ],
  AC9S8I07: [
    { evidence: "Repeated controlled tests show Battery A lasts 18 to 21 hours and Battery B lasts 11 to 14 hours under one fixed load", question: "Which argument is best supported?", correct: "Battery A lasted longer under the tested load because every measured A result exceeded every B result", wrong: ["Battery A is the best battery for every device and temperature", "An advertisement calling A long-lasting is enough evidence"], summary: "A sound argument links a limited claim to relevant repeated evidence.", hint: "Keep the claim within the tested load and observed data." },
    { evidence: "A social-media post and a peer-reviewed field study make opposing claims about frog decline", question: "Which evidence should carry more weight and why?", correct: "The field study, if its methods and data are transparent and relevant to the population", wrong: ["The post because it has more likes", "Whichever source uses the strongest emotional language"], summary: "Source quality depends on relevant expertise, transparent methods and inspectable evidence.", hint: "Popularity is not a measure of scientific reliability." },
    { evidence: "A report states that a creek warmed by 2 degrees and dissolved oxygen fell", question: "Which sentence supplies reasoning rather than merely repeating evidence?", correct: "Warmer water can hold less dissolved oxygen, so the measured warming provides a mechanism for the decline", wrong: ["The creek warmed by 2 degrees and oxygen fell", "A scientist said the creek had changed"], summary: "Reasoning explains how evidence supports the claim through a scientific mechanism.", hint: "Look for the link between temperature and oxygen capacity." },
    { evidence: "Four company-funded studies support a product, while two independent studies find smaller effects", question: "How should an argument use these sources?", correct: "Compare methods and results and disclose funding as a possible influence, without rejecting studies solely for funding", wrong: ["Count sources and accept four against two", "Discard every funded study without reading its method"], summary: "Evidence evaluation considers method, consistency and conflicts of interest rather than simple source counts.", hint: "Funding matters, but it is not a substitute for evaluating evidence." },
    { evidence: "A claim about national water quality is supported by one sample from one tap", question: "What is wrong with the evidence?", correct: "The sample is too narrow to represent water sources across the nation", wrong: ["Tap water can never be measured scientifically", "One precise reading automatically represents every location"], summary: "Evidence must be representative of the population named in the claim.", hint: "Compare the size of the claim with the sampling scope." },
    { evidence: "A student copies a graph from a research organisation into an argument", question: "Which use is ethically and scientifically responsible?", correct: "Cite the source, preserve scale and labels, and explain how the data bear on the claim", wrong: ["Remove the source so the argument appears original", "Crop out inconvenient values while keeping the organisation's name"], summary: "Responsible argument uses transparent attribution and preserves the meaning of evidence.", hint: "Readers should be able to trace and interpret the original data." },
    { evidence: "A proposal cites culturally governed ecological knowledge shared for a limited local purpose", question: "What must the argument do?", correct: "Follow the knowledge holders' permissions, attribution and limits on use", wrong: ["Publish all details because scientific arguments require unrestricted access", "Remove attribution so the knowledge becomes public data"], summary: "Cultural knowledge is used according to authority, protocol and agreed purpose.", hint: "Permission to hear information is not automatic permission to republish it." },
    { evidence: "A pesticide reduces one pest species but monitoring also finds fewer pollinators", question: "Which argument addresses the full evidence?", correct: "It may control the pest, but decisions should also weigh the observed pollinator impact and uncertainty", wrong: ["The pest result proves there are no ecological costs", "The pollinator data should be omitted because they weaken the recommendation"], summary: "Strong arguments address relevant counterevidence instead of selecting only supportive results.", hint: "Include both the intended benefit and the measured trade-off." },
    { evidence: "Two sources quote the same original study as if they were independent evidence", question: "How should this be evaluated?", correct: "Trace both citations to the original study and count the evidence once while assessing that study's quality", wrong: ["Treat each quotation as a separate replication", "Assume repetition across websites proves the claim"], summary: "Multiple reports of one study do not provide independent corroboration.", hint: "Follow the citation chain to the underlying data." },
    { evidence: "A nutrition study observes that tea drinkers have lower disease rates but does not control diet or income", question: "Which claim is justified?", correct: "Tea drinking was associated with lower rates in this sample, but confounding factors prevent a causal conclusion", wrong: ["Tea certainly prevents the disease in every person", "The association is useless because observational evidence can never inform a question"], summary: "An evidence-based argument distinguishes observed association from demonstrated causation.", hint: "State the pattern and the key limitation together." },
  ],
  AC9S8I08: [
    { evidence: "A laboratory report must allow another class to repeat an investigation", question: "Which method sentence is most suitable?", correct: "Heat 100 mL of water at 200 W and record temperature every 30 seconds for 5 minutes", wrong: ["We heated some water for a while and it got hotter", "The amazing water experiment worked perfectly"], summary: "A reproducible report uses precise quantities, units and sequence.", hint: "Choose details another investigator can follow." },
    { evidence: "A bushfire-smoke alert is written for the general public", question: "Which message preserves accuracy and supports action?", correct: "Particle levels are high today; people with breathing conditions should follow health advice and limit strenuous outdoor activity", wrong: ["The air is poison and everyone who goes outside will become ill", "PM2.5 exceeded the threshold, with no explanation or action"], summary: "Public communication combines accurate risk language with clear, audience-relevant action.", hint: "Avoid both exaggeration and unexplained technical shorthand." },
    { evidence: "A graph shows a small uncertain increase in sea temperature", question: "Which caption communicates the result honestly?", correct: "Mean temperature increased slightly; error bars overlap, so the size of the change remains uncertain", wrong: ["Ocean temperature has definitely surged", "The graph proves temperature did not change because uncertainty exists"], summary: "A scientific caption states the pattern and its uncertainty without overclaiming.", hint: "Mention both the direction and what the error bars limit." },
    { evidence: "The same result must appear in a journal-style report and a Year 5 classroom poster", question: "What should change between the texts?", correct: "Vocabulary, detail and structure may change, while the data relationship and conclusion remain accurate", wrong: ["Remove evidence from the poster because younger readers need only opinions", "Change the conclusion so each audience hears what it prefers"], summary: "Audience adaptation changes presentation, not the scientific meaning.", hint: "Simplify expression while preserving evidence and conclusion." },
    { evidence: "A student writes, ‘The solution was heated by us’ in every sentence because passive voice sounds scientific", question: "Which revision principle is best?", correct: "Choose active or passive voice according to clarity and whether the actor or process is the focus", wrong: ["Passive voice is compulsory in every scientific sentence", "Active voice makes any scientific statement false"], summary: "Scientific voice is selected for clarity and purpose, not as a prestige rule.", hint: "Ask what the reader needs to focus on." },
    { evidence: "An infographic compares household energy sources", question: "Which visual feature improves interpretation rather than decoration?", correct: "Bars using a common zero baseline, labelled units and a cited data year", wrong: ["Three-dimensional icons whose volume exaggerates small differences", "Colours with no legend and values from unlabelled years"], summary: "Effective visuals use honest scale, labels and source context.", hint: "Readers should compare values without visual distortion." },
    { evidence: "A 20-second oral briefing reports a water test", question: "Which structure suits the purpose?", correct: "Lead with the key finding, give one supporting value and state the practical implication and limitation", wrong: ["Read every raw measurement without naming the finding", "Give the recommendation but hide the evidence and uncertainty"], summary: "A short briefing prioritises a finding, essential evidence and responsible qualification.", hint: "Keep the evidence-to-action chain visible." },
    { evidence: "A website animation shows how particles move when a solid melts", question: "Which accessibility addition is most useful?", correct: "Provide a text description of particle arrangement and motion, plus controls usable by keyboard", wrong: ["Rely on colour alone to show every change", "Autoplay rapidly because all users interpret motion the same way"], summary: "Accessible science communication provides equivalent meaning and usable controls.", hint: "Ensure the scientific relationship is available without sight or a mouse." },
    { evidence: "A news headline says, ‘Study proves screens destroy sleep,’ but the study found a modest association", question: "Which headline is accurate?", correct: "Study finds an association between greater screen use and shorter sleep in the surveyed group", wrong: ["Screens certainly destroy sleep for everyone", "Study finds nothing because an association is not causation"], summary: "A headline should match the study design, effect and sampled population.", hint: "Replace causal certainty with the observed association." },
    { evidence: "A report includes a table copied from another study", question: "What makes its use transparent?", correct: "Give a clear source, retain headings and units, and explain why the table is relevant", wrong: ["Remove the citation and present the data as newly collected", "Keep the citation but alter units without noting the conversion"], summary: "Transparent communication lets readers trace evidence and interpret it in context.", hint: "Preserve provenance, meaning and measurement conventions." },
  ],
};

// Additional contexts complete separate 24-item Practice and 16-item Test banks.
// Each row is a different scientific problem, not a change of setting applied to one stem.
const EXTENSIONS = {
  AC9S8I01: [
    ["crickets chirp at different rates on warm and cool nights", "How does air temperature affect chirps per minute in one cricket species?", "Higher temperature will be associated with more chirps per minute within the tested range", "Do crickets sing better when they feel happy?", "Warm nights prove every insect makes more sound"],
    ["bread develops mould at different rates in sealed bags", "How does storage temperature affect the percentage of bread surface covered by mould after five days?", "Bread stored warmer will develop greater mould coverage if moisture and bread type are controlled", "Which bread looks most disgusting?", "Temperature is the only possible cause of mould anywhere"],
    ["magnets lift different numbers of identical paper clips", "How does the number of wire coils around an iron nail affect the clips lifted at fixed current?", "More coils will increase the electromagnet's lifting capacity within the tested range", "Why is electricity magnetic?", "More coils always create unlimited magnetic force"],
    ["coastal rocks host different numbers of barnacles", "How does height above the low-tide mark relate to barnacle density on similar rock surfaces?", "Barnacle density may decrease with longer exposure to air higher on the shore", "Why do barnacles choose the nicest rocks?", "Height alone certainly controls every shore organism"],
    ["tablets fizz for different times when broken up", "How does tablet surface area affect reaction time in water at fixed temperature?", "Crushed tablets will react in less time because more surface contacts the water", "Do smashed tablets become stronger chemicals?", "Crushing changes the tablet into a new substance before water is added"],
    ["sound level falls farther from a speaker", "How does measured distance from one speaker affect sound level in decibels at fixed volume?", "Sound level will decrease as distance increases in the tested room", "Where does sound disappear?", "Distance changes the speaker's electrical power"],
    ["apples brown after being cut", "How does lemon-juice concentration affect browned surface area after 30 minutes?", "Higher lemon-juice concentration will reduce browning within the tested range", "Why do apples dislike lemons?", "Lemon juice prevents every kind of food decay"],
    ["water drains through soils at different rates", "How does soil particle composition affect drainage time for 100 millilitres of water?", "Sand-rich soil will drain faster than clay-rich soil under matched packing", "Which soil is the best?", "Fast drainage proves a soil supports the most plant growth"],
    ["rubber bands stretch by different amounts under loads", "How does applied force affect extension of one rubber band below its elastic limit?", "Extension will increase as applied force increases below the elastic limit", "Why are rubber bands stretchy?", "Any force will stretch the band forever by the same amount"],
    ["pond-water clarity differs among three sites", "How do turbidity and nearby ground cover vary among defined pond-edge sites?", "Sites with more exposed soil may have higher turbidity after rain", "Which pond site is healthiest?", "Cloudy water proves pollution came from one named source"],
    ["antacid brands neutralise acid differently", "How does antacid brand affect the mass needed to reach pH 7 in the same acid volume?", "Brands may require different masses because their active ingredients and amounts differ", "Which brand is medically best?", "The fastest brand cures every stomach condition"],
    ["metal spoons feel colder than wooden spoons in one room", "How does spoon material affect the rate of heat transfer from a warm hand?", "Metal will transfer thermal energy from the hand faster than wood", "Why is metal naturally colder?", "Touch can measure exact spoon temperature"],
    ["yeast balloons inflate by different amounts", "How does sugar concentration affect gas volume produced by yeast in 20 minutes?", "Gas production will change with sugar concentration and may peak within the tested range", "Does yeast enjoy sweet food?", "Doubling sugar must always double gas production"],
    ["shadows change length through the day", "How does solar elevation relate to the length of one vertical object's shadow?", "Shadow length will decrease as solar elevation increases", "Why does the Sun move around the pole?", "A shorter shadow proves the object became shorter"],
    ["bike stopping distances differ", "How does starting speed affect stopping distance on the same dry surface with one braking method?", "Higher starting speed will increase stopping distance", "Which rider is safest?", "Stopping distance depends only on rider confidence"],
    ["duckweed fronds multiply under coloured lights", "How does light wavelength affect change in duckweed frond number over seven days?", "Growth may differ among wavelengths because pigments absorb wavelengths differently", "Which colour makes plants happy?", "Green light must produce most growth because plants look green"],
    ["steel wool gains mass while rusting", "How does exposure to salt solution affect mass change of equal steel-wool samples?", "Salt exposure will increase the rate of rust-related mass change", "Why does metal get old?", "Rusting removes all matter from steel"],
    ["balls rebound to different heights", "How does ball material affect rebound height from a fixed drop height?", "More elastic materials will return a greater fraction of the drop height", "Which ball is the most fun?", "A high rebound proves gravity is weaker for that ball"],
    ["pulse rates change after exercise", "How does exercise duration affect recovery time to resting pulse for the same participant?", "Longer exercise may increase recovery time under matched intensity", "Why does exercise make hearts healthy?", "Pulse rate alone measures every aspect of fitness"],
    ["saltwater samples conduct electricity differently", "How does salt concentration affect current at fixed voltage and electrode spacing?", "Current will increase with salt concentration within the tested range", "Does salty water contain electricity?", "Salt creates electrical energy from nothing"],
    ["compost bins reach different temperatures", "How does the ratio of green to brown material affect peak compost temperature?", "A balanced material ratio may produce a higher peak through microbial activity", "Which compost smells nicest?", "Heat proves the material is burning with a flame"],
    ["paper helicopters fall at different speeds", "How does rotor length affect descent time from a fixed height?", "Longer rotors may increase descent time by increasing air resistance", "Why do paper helicopters want to fly?", "A longer rotor reduces the force of gravity"],
    ["water evaporates from dishes of different widths", "How does exposed surface area affect mass lost in one hour at fixed temperature?", "Greater exposed area will increase evaporation rate", "Where does missing water go forever?", "Wide dishes make water chemically decompose"],
    ["lichens differ between roadside and park trees", "How does distance from a busy road relate to lichen coverage on the same tree species?", "Lichen coverage may increase farther from traffic, but other site factors must be considered", "Do lichens dislike cars?", "A roadside pattern proves one pollutant caused all differences"],
    ["springs extend under added masses", "How does hanging mass affect spring extension before permanent deformation?", "Extension will increase with mass within the spring's elastic range", "Which spring is strongest?", "Every added mass permanently stretches the spring"],
    ["soap changes the number of drops held on a coin", "How does detergent concentration affect the number of drops a coin holds before spilling?", "More detergent will reduce the drop count by lowering surface tension", "Why does soap make water slippery?", "Detergent removes gravity from water"],
    ["mealworms choose between dark and light chambers", "How does light level affect mealworm distribution when moisture and temperature are equal?", "More mealworms will occupy the darker chamber if they prefer lower light", "Are mealworms afraid of light?", "One choice proves every mealworm always behaves identically"],
    ["insulated bottles cool at different rates", "How does insulation thickness affect temperature decrease over 40 minutes?", "Thicker insulation will reduce the temperature decrease within the tested range", "Which bottle keeps drinks best forever?", "Insulation produces thermal energy"],
    ["seeds germinate differently in saline water", "How does salt concentration affect germination percentage after seven days?", "Germination percentage will decrease as salinity rises for this seed type", "Why do seeds hate salt?", "Salt prevents every plant species from germinating"],
    ["toy cars roll down ramps at different angles", "How does ramp angle affect travel time over a fixed distance?", "Increasing ramp angle will reduce travel time within the tested range", "Which ramp is fastest?", "Steeper ramps increase the car's mass"],
  ],
};

const STUDIES = [
  ["water temperature and sugar dissolving time", "water temperature", "dissolving time", "sugar mass, grain size, water volume and stirring"],
  ["ramp angle and toy-car travel time", "ramp angle", "travel time", "car, surface, distance and release method"],
  ["light intensity and pondweed bubble rate", "light intensity", "bubbles per minute", "pondweed length, water and temperature"],
  ["soil type and bean-seedling height", "soil type", "height after 14 days", "seed variety, water, pot and light"],
  ["wire length and electrical current", "wire length", "current", "wire material, thickness, voltage and temperature"],
  ["exercise duration and pulse recovery", "exercise duration", "recovery time", "participant, intensity and measurement method"],
  ["salt concentration and egg buoyancy", "salt concentration", "floating height", "egg, water volume, container and temperature"],
  ["insulation material and cooling", "insulation material", "temperature loss", "cup, water volume, starting temperature and time"],
  ["surface area and evaporation", "exposed surface area", "mass of water lost", "water volume, temperature, airflow and time"],
  ["pH and amylase activity", "pH", "time to digest starch", "enzyme amount, starch concentration and temperature"],
  ["drop height and crater diameter", "drop height", "crater diameter", "ball, sand depth and release position"],
  ["fertiliser concentration and duckweed growth", "fertiliser concentration", "change in frond number", "starting fronds, light, water and time"],
  ["blade length and paper-turbine rotation", "blade length", "rotations per minute", "paper, blade number, fan distance and airflow"],
  ["detergent concentration and surface tension", "detergent concentration", "drops held on a coin", "dropper, coin, drop height and water volume"],
  ["sound frequency and perceived pitch", "speaker frequency", "reported pitch", "volume, speaker, room and listener procedure"],
  ["acid concentration and reaction rate", "acid concentration", "gas volume per minute", "carbonate mass, surface area and temperature"],
  ["shade cover and soil moisture", "percentage shade cover", "soil moisture after six hours", "soil mass, container, starting water and airflow"],
  ["magnet distance and force", "magnet separation", "force reading", "magnets, alignment and measurement device"],
  ["water depth and wave speed", "water depth", "wave travel time", "tray, wave source, distance and water temperature"],
  ["antibiotic concentration and inhibition zone", "antibiotic concentration", "inhibition-zone diameter", "bacterial strain, agar, disc size and incubation"],
  ["fruit ripeness and vitamin C", "ripeness stage", "titration volume", "fruit variety, sample mass and extraction method"],
  ["roof colour and model-house temperature", "roof colour", "inside temperature rise", "house model, lamp distance, material and time"],
  ["salinity and seed germination", "salt concentration", "germination percentage", "seed type, seed number, temperature and time"],
  ["load and bridge deflection", "applied load", "bridge deflection", "bridge design, material, span and load position"],
  ["wind speed and transpiration", "wind speed", "plant mass loss", "plant species, leaf area, light, temperature and time"],
  ["particle size and dissolving", "solute particle size", "dissolving time", "solute mass, water volume, temperature and stirring"],
  ["string length and pendulum period", "string length", "period", "bob mass, release angle and timing method"],
  ["battery temperature and motor speed", "battery temperature", "motor rotations per minute", "battery type, motor, circuit and load"],
  ["stream velocity and sediment size", "stream velocity", "largest transported grain", "channel width, water depth and sediment mixture"],
  ["leaf area and photosynthesis", "leaf area exposed", "oxygen production rate", "plant species, light intensity, carbon dioxide and temperature"],
];

const generated = {
  AC9S8I02: ([study, x, y, controls], i) => ({ evidence: `A team plans a study of ${study}, but its draft changes several conditions`, question: `Which method decision makes study ${i + 11} fair and reproducible?`, correct: `Set measured values for ${x}, measure ${y} consistently, and hold ${controls} constant`, wrong: [`Change ${x} and ${controls} together, then attribute the result to ${x}`, `Let each group choose how to measure ${y} after seeing its results`], summary: `A reproducible ${study} plan defines the test, measurement and relevant controls.`, hint: `Only ${x} should explain a change in ${y}.` }),
  AC9S8I03: ([study, x, y], i) => ({ evidence: `In study ${i + 11} of ${study}, the expected ${y} spans a known range`, question: `How should the team obtain useful ${y} measurements?`, correct: `Choose a calibrated instrument whose range and resolution suit ${y}, then record values with units and justified precision`, wrong: [`Use any instrument and add extra decimal places to its ${y} readings`, `Estimate ${y} by sight because repeated estimates guarantee accuracy`], summary: `Useful ${y} data require suitable range, resolution, technique, units and precision.`, hint: `Match the instrument to the size and detail required for ${y}.` }),
  AC9S8I04: ([study, x, y], i) => ({ evidence: `Study ${i + 11} records paired numerical values for ${x} and ${y}`, question: `Which representation will most clearly reveal the relationship?`, correct: `Plot ${x} on a labelled horizontal axis and ${y} on a labelled vertical axis using honest scales and units`, wrong: [`Combine all ${x} and ${y} values into one decorative pie chart`, `Plot ${y} without labels and adjust the scale to make the preferred result look large`], summary: `A scatter or line graph can reveal the measured relationship between ${x} and ${y}.`, hint: `Put the changed or explanatory variable, ${x}, on the horizontal axis.` }),
  AC9S8I05: ([study, x, y], i) => ({ evidence: `Results from study ${i + 11} show an overall ${x}-${y} pattern with one point away from the trend`, question: `Which analysis treats the full data set responsibly?`, correct: `Describe the direction and size of the ${x}-${y} pattern, identify the unusual point, and check a scientific or procedural explanation`, wrong: [`Delete the unusual ${y} value without reporting it`, `Claim ${x} certainly causes ${y} because most points follow a pattern`], summary: `Analysis of ${study} includes trend, variation, anomalies and limits on causal claims.`, hint: `Report the main pattern and investigate the point that differs.` }),
  AC9S8I06: ([study, x, y, controls], i) => ({ evidence: `A conclusion from study ${i + 11} says ${x} alone caused ${y}, although ${controls} were not all controlled`, question: `Which evaluation best tests the claim?`, correct: `Identify how an uncontrolled condition could affect ${y}, narrow the conclusion, and repeat while controlling or measuring it`, wrong: [`Accept the claim because its wording sounds confident`, `Label every limitation human error without linking it to ${y}`], summary: `Evaluation links a specific limitation in ${study} to its effect and a targeted improvement.`, hint: `Name which uncontrolled condition could also change ${y}.` }),
  AC9S8I07: ([study, x, y, controls], i) => ({ evidence: `A source claims a universal rule about ${study} from a small test with poorly reported ${controls}`, question: `Which argument uses this evidence appropriately?`, correct: `Report the observed ${x}-${y} relationship only for the tested conditions and seek transparent, independent evidence before generalising`, wrong: [`Call the rule universal because one source reported it`, `Reject all ${study} evidence because this one source has limitations`], summary: `An evidence-based argument matches the scope of a ${study} claim to source quality and tested conditions.`, hint: `Limit the claim and evaluate the evidence rather than choosing certainty or dismissal.` }),
  AC9S8I08: ([study, x, y], i) => ({ evidence: `A team must communicate results from study ${i + 11} to students and laboratory researchers`, question: `Which communication choice preserves the science for both audiences?`, correct: `Adapt vocabulary and detail, but keep the measured ${x}-${y} relationship, units, uncertainty and source consistent`, wrong: [`Remove the ${y} evidence for students and give only an opinion`, `Change the ${x}-${y} conclusion to suit what each audience wants to hear`], summary: `Communication of ${study} can change form while preserving evidence, meaning and uncertainty.`, hint: `Audience affects expression, not the scientific result.` }),
};

for (const [code, make] of Object.entries(generated)) {
  EXTENSIONS[code] = STUDIES.map((study, index) => {
    const item = make(study, index);
    const label = study[0];
    item.question = `${item.question} Use the ${label} evidence.`;
    item.correct = `For ${label}: ${item.correct}`;
    item.wrong = item.wrong.map((choice) => `For ${label}: ${choice}`);
    item.summary = `${item.summary} This conclusion concerns ${label}.`;
    item.hint = `${item.hint} Apply this to ${label}.`;
    return item;
  });
}

const skillText = {
  AC9S8I01: ["The question identifies measurable variables and avoids assuming its conclusion.", "Check that the cause and response can both be measured."],
  AC9S8I02: ["The plan defines a fair, reproducible method and its responsibilities.", "Check the changed variable, measurement, controls and risks."],
  AC9S8I03: ["The measurement method matches the quantity, range and justified precision.", "Check instrument range, resolution, units and reading method."],
  AC9S8I04: ["The representation matches the data type and reveals the target relationship honestly.", "Check axes, units, scale and the purpose of the display."],
  AC9S8I05: ["The analysis describes pattern, variation and anomalies without exceeding the evidence.", "Use all results and distinguish association from causation."],
  AC9S8I06: ["The evaluation links a specific limitation to confidence and a useful improvement.", "Name the error mechanism and its likely effect."],
  AC9S8I07: ["The argument links a scoped claim to relevant, credible evidence and explicit reasoning.", "Check source quality, representativeness and competing evidence."],
  AC9S8I08: ["The communication fits purpose and audience while preserving scientific meaning.", "Keep evidence, units, uncertainty and attribution accurate."],
};

for (const [code, rows] of Object.entries(EXTENSIONS)) {
  const [summary, hint] = skillText[code];
  YEAR8_SCIENCE_I_CONCEPTS[code].push(...rows.map((row, index) => {
    if (!Array.isArray(row)) return row;
    const [evidence, question, correct, wrongA, wrongB] = row;
    return { evidence, question, correct, wrong: [wrongA, wrongB], summary: `${summary} Context ${index + 11}: ${evidence}.`, hint: `${hint} Focus on ${evidence}.` };
  }));
}

export default YEAR8_SCIENCE_I_CONCEPTS;
