const metadata = {
  code: 'AC9S6H01',
  descriptor: 'examine why advances in science are often the result of collaboration or build on the work of others',
  title: 'How collaboration advances science',
  learningIntention: 'We are learning to explain how shared evidence, specialised roles, checking and earlier work help scientific knowledge advance.',
  successCriteria: [
    'distinguish genuine scientific collaboration from simply completing tasks beside other people',
    'identify how a specific contribution enables a team to check, extend or apply scientific knowledge',
    'use evidence from case studies, timelines and datasets to explain how an advance built on earlier work',
    'explain why independent checking can increase confidence without guaranteeing that a conclusion is correct'
  ]
};

const q = (skill, stage, question, answers, correct, explanation, hint) => ({skill, stage, question, answers, correct, explanation, hint});

const practice = [
  q('shared question','foundation','Four students each grow a different plant but never compare results. What would turn their activity into scientific collaboration?',['Decorating four separate posters','Agreeing on one question and combining comparable measurements','Using four different rulers','Finishing at the same time'],1,'Collaboration requires contributions to a shared scientific question; comparable measurements can be pooled and analysed.','Look for a shared purpose and connected evidence.'),
  q('specialised roles','foundation','A wetland team includes a botanist, water chemist and mapping specialist. Why can this combination help?',['Every person repeats an identical job','Different expertise connects plant, water and location evidence','The largest team must be correct','Specialists do not need to share results'],1,'The specialists examine different parts of the same system and combine evidence into a fuller explanation.','Ask what each expertise adds.'),
  q('shared data','foundation','Schools across Australia measure local rainfall using the same procedure. What is the main benefit?',['It removes all measurement error','It provides observations from many places that can be compared','It proves rainfall is identical everywhere','It lets schools skip recording units'],1,'A common method produces a larger, geographically varied dataset that researchers can compare.','Think about coverage.'),
  q('peer checking','foundation','Before publishing, another scientist checks a team’s methods and reasoning. What is this most likely to do?',['Guarantee the claim forever','Help identify weaknesses or missing evidence','Replace the original observations','Turn opinion into a vote'],1,'Review can reveal problems and prompt revision, although it cannot guarantee perfect conclusions.','Checking improves reliability, not certainty.'),
  q('prior work','foundation','An engineer improves a sensor using a circuit described in an earlier paper. Which statement is accurate?',['Only the new engineer deserves credit','The advance builds on a published contribution','The older circuit becomes worthless','Using prior work prevents innovation'],1,'The earlier circuit provides a tested starting point that the engineer extends.','Find the foundation for the new work.'),
  q('replication','foundation','A second laboratory repeats an experiment and obtains a similar pattern. Why does this matter?',['Agreement proves no future result can differ','Independent evidence increases confidence the pattern is reproducible','The first laboratory must delete its results','Two laboratories create a majority vote'],1,'A comparable result from an independent team suggests the finding is not limited to one setup or group.','Focus on reproducibility.'),
  q('role matching','foundation','Which team member is best placed to design software that finds habitat change in thousands of satellite images?',['Computer scientist','Marine diver','Glassblower','Veterinarian'],0,'A computer scientist can create algorithms to process a large image dataset efficiently.','Match expertise to data processing.'),
  q('role matching','foundation','Who would best test whether a remote sensor remains accurate after months outdoors?',['Reliability engineer','Illustrator','Tour guide','Historian'],0,'A reliability engineer can plan durability and calibration tests for equipment.','Which role tests equipment performance?'),
  q('collaboration mechanism','core','Ecologists describe animal needs while engineers design tracking collars. What connects their contributions?',['A shared goal of collecting useful movement data safely','The team members use identical qualifications','The collars make ecology unnecessary','Each group publishes unrelated conclusions'],0,'The ecological requirements guide an engineering solution for the shared investigation.','Find the scientific goal joining the roles.'),
  q('traditional knowledge','core','A restoration project combines long-held First Nations ecological knowledge with current soil measurements. What is the strongest explanation?',['Only recent instruments count as knowledge','Different knowledge and evidence can inform where and how restoration is tested','Traditional knowledge removes the need to monitor outcomes','The project is collaborative only if everyone uses the same method'],1,'Respectfully combining accumulated place-based knowledge with measurements can guide and test restoration actions.','Look for respectful integration plus checking.'),
  q('Antarctic research','core','Why might Antarctic plant research require teams from several countries?',['One nation is unable to ask questions','Shared stations, expertise and long-term observations increase coverage','International teams never disagree','Cold weather automatically validates results'],1,'International collaboration can pool access, instruments, expertise and observations across time and place.','Consider resources and coverage.'),
  q('space science','core','An astronomer compares a new telescope image with star positions catalogued centuries ago. The catalogue is important because it:',['provides earlier observations against which change can be examined','makes the new telescope unnecessary','proves every old interpretation correct','was created by one famous person'],0,'Recorded earlier observations provide a baseline that new evidence can check and extend.','What can a baseline enable?'),
  q('incremental advance','core','Which timeline best represents an advance that builds on others’ work?',['Question → guess → award','Early model → new observations → revised model → spacecraft evidence','Vote → final truth → no further tests','Invention → erase all earlier records'],1,'Scientific ideas often develop through successive models, observations and improved tools.','Choose cumulative evidence and revision.'),
  q('scientific consensus','core','What does scientific consensus mean?',['The most senior scientist wins a vote','A judgement supported by a substantial body of assessed evidence','Every scientist has exactly the same opinion','A conclusion that can never change'],1,'Consensus is grounded in converging evidence and critical evaluation, not popularity or permanence.','Evidence matters more than headcount.'),
  q('shared methods','core','Three teams test river phosphate levels. Why should they agree on sampling depth and units?',['To make results meaningfully comparable','To ensure all numbers are equal','To remove the need for repeats','To make the river cleaner immediately'],0,'Consistent sampling conditions and units allow datasets to be combined and compared fairly.','Think comparability.'),
  q('data quality','core','One school reports water temperature without a time of day. What should the network do?',['Invent the missing time','Flag the limitation before combining the record','Assume it was measured at noon','Discard the entire project'],1,'Missing context affects comparison, so the limitation should be identified rather than hidden or guessed.','Treat incomplete evidence honestly.'),
  q('claim review revision','core','Which sequence best shows collaborative quality control?',['Publish → collect data → ask a question','Make claim → colleagues examine evidence → team revises explanation','Vote → select evidence → ignore objections','Copy conclusion → remove methods → announce certainty'],1,'Evidence-based criticism can lead a team to refine a claim before or after publication.','Look for checking followed by improvement.'),
  q('constructive critique','core','A reviewer notices that all soil samples came from shaded sites. What is the most useful response?',['Reject science as impossible','Recommend sampling sunny sites before generalising','Ask the team to vote again','Change the graph colour'],1,'Broader sampling tests whether the claimed pattern applies beyond shaded sites.','Address the evidence gap.'),
  q('detergent case','core','Researchers link high phosphate runoff with algal blooms. Which next collaboration could help apply the finding?',['Chemists and manufacturers develop and test lower-phosphate detergents','Astronomers rename the algae','Stores hide ingredient information','Scientists stop measuring waterways'],0,'Scientists and manufacturers can translate environmental evidence into an alternative product and test its effects.','Who can turn evidence into a practical change?'),
  q('remote sensing','core','Why do ecologists collaborate with engineers on remote-sensing tools?',['Ecologists provide habitat questions while engineers develop ways to collect measurements at scale','Engineering opinions replace ecological evidence','Remote sensing needs no ground checks','Both roles always perform the same task'],0,'Ecological knowledge defines meaningful measurements; engineering expertise helps build reliable collection tools.','Connect scientific needs with tool design.'),
  q('computer analysis','core','A program detects rapid vegetation loss in aerial images. Why should ecologists still inspect sample locations?',['To check whether the detected pattern matches conditions on the ground','Because computers cannot store images','To make every result different','To replace the program with opinions'],0,'Ground observations help validate whether an algorithm’s classifications represent real habitat change.','Digital patterns need validation.'),
  q('ISS collaboration','core','Which example best demonstrates collaboration on the International Space Station?',['Countries contribute modules, crews and experiments that operate as one program','Each astronaut runs an unrelated private project','One country withholds all procedures','The crew chooses results by applause'],0,'Integrated equipment, people and investigations contribute to a shared research platform.','Look for interdependent contributions.'),
  q('limitations','core','What is one limitation of a large research team?',['Communication and data standards must be carefully coordinated','More expertise always reduces available evidence','Collaboration prevents checking','Every member must reach the same result'],0,'Large teams can offer breadth but require agreed methods, clear roles and effective communication.','Benefits can create coordination needs.'),
  q('individual and team','core','Which task could one scientist reasonably begin alone but later strengthen through collaboration?',['Recording a local observation, then asking specialists to test explanations','Declaring a universal law from one glance','Refusing to share methods','Selecting an answer by popularity'],0,'Individual observation can start an inquiry, while additional expertise and checking strengthen the explanation.','Science may begin individually and advance collectively.'),
  q('credit and contribution','application','A paper lists a field team, data analyst and instrument designer. Why is naming contributions valuable?',['It shows how different work supported the conclusion','It proves the first name did all the science','It ranks people by intelligence','It removes responsibility for errors'],0,'Contribution statements make the collaborative pathway and responsibilities visible.','Trace who enabled what.'),
  q('timeline reasoning','application','A timeline shows: 1609 telescopic observations; 1687 mathematical model; 1846 prediction and observation of Neptune. What does it illustrate?',['Later advances used earlier observations and models','Only the final observer contributed','Mathematics cannot support science','Old evidence was erased'],0,'New predictions and observations were possible because earlier tools, records and mathematical ideas accumulated.','Connect steps across time.'),
  q('conflicting evidence','application','Two teams obtain different results for seed growth. What is the most scientific collaborative response?',['Compare methods and conditions, then repeat targeted tests','Choose the friendliest team','Average the conclusions without examining data','Keep only the expected result'],0,'Differences can reveal variables or errors; comparing methods guides informative replication.','Investigate why, rather than vote.'),
  q('shared dataset','application','Team A measures 12 plants in shade; Team B measures 12 in sun using the same method. Together, the data mainly allow researchers to:',['compare growth under two light conditions','claim light is the only factor in every habitat','ignore sample sizes','prove every plant grows equally'],0,'Comparable groups provide evidence for a light-condition comparison, with conclusions limited to the study.','State only what the design supports.'),
  q('evidence table','application','Three sensor designs must record hourly and work below 0°C. Results: P hourly/−10°C; Q daily/−20°C; R hourly/5°C. Which meets both requirements?',['P only','Q only','R only','Q and R'],0,'Only P satisfies both the recording-frequency and temperature criteria.','Check every requirement, not just one.'),
  q('engineering comparison','application','A team shares test data showing Prototype X is accurate but fragile and Y is slightly less accurate but durable. What should happen next?',['Use the shared evidence to refine a design for both criteria','Declare both perfect','Hide the weakness of X','Select by logo colour'],0,'Comparison reveals complementary strengths and guides a targeted improvement.','Evidence should shape revision.'),
  q('replication limit','application','Four laboratories repeat a result successfully. Which conclusion is best?',['Confidence increases, but further evidence could still revise the explanation','The claim is now impossible to challenge','The laboratories formed a winning majority','All experimental uncertainty is zero'],0,'Repeated independent agreement strengthens confidence without making knowledge absolute.','Avoid “proven forever”.'),
  q('publication','application','Why do detailed methods help later scientists?',['They allow others to evaluate, repeat and adapt the investigation','They hide mistakes','They make all contexts identical','They replace data'],0,'Transparent methods enable checking and provide a practical foundation for extensions.','Could another team understand what was done?'),
  q('negative result','application','A team reports that a proposed filter did not reduce phosphate. How can this still advance science?',['It identifies an ineffective approach and informs the next design','Unsuccessful tests contain no evidence','The result should be deleted','It proves filtration is impossible'],0,'A well-designed negative result can prevent needless repetition and guide improved explanations or designs.','Not all useful evidence confirms a prediction.'),
  q('specialisation','application','A microbiologist identifies organisms while a statistician tests whether differences are larger than expected variation. Why are both roles useful?',['Identification and quantitative analysis answer connected parts of the question','Statistics replaces observations','Only one role may contribute to science','They guarantee the hypothesis'],0,'The roles contribute complementary evidence and reasoning to the shared investigation.','Name each distinct contribution.'),
  q('shared instruments','application','Several countries book time on one powerful telescope. What scientific benefit can sharing provide?',['More research questions can use equipment too costly for one small team','The telescope removes the need for expertise','All observations become identical','Countries no longer need to communicate'],0,'Shared infrastructure expands access and enables teams to contribute different investigations and expertise.','Consider scarce equipment.'),
  q('citizen science','application','Hundreds of volunteers photograph flowering dates while scientists verify samples and analyse patterns. Why is this collaboration?',['Public observations expand coverage and scientific checking supports data quality','Volunteers automatically prove the explanation','Scientists contribute nothing','Photos replace dates and locations'],0,'The groups make linked contributions to one question: broad collection, verification and analysis.','Trace how roles combine.'),
  q('ethical collaboration','application','Before using First Nations ecological knowledge, what should a research team do?',['Work through respectful partnerships, permission and appropriate recognition','Publish it without consultation','Treat it as freely owned data','Remove information about Country'],0,'Ethical collaboration respects knowledge holders, agreed protocols, attribution and control.','Collaboration includes relationships and permission.'),
  q('model revision','application','A new spacecraft measurement conflicts with part of an older planetary model. What should scientists do?',['Examine measurement quality and revise the model if evidence supports change','Discard all earlier astronomy','Ignore the spacecraft to protect consensus','Vote on which result is nicer'],0,'New evidence is checked against prior evidence; supported parts may remain while inadequate parts are revised.','Revision need not erase every earlier contribution.'),
  q('communication','application','A chemist uses “ppm” while community samplers record “mg/L”. What must the team clarify before combining data?',['Whether the units are equivalent under the relevant conditions and how to convert them','Which abbreviation looks more scientific','Which team has more members','Whether to remove labels'],0,'Unit meaning and conversions must be explicit for valid comparison.','Shared data need shared measurement language.'),
  q('uncertainty','application','Why should collaborators report uncertainty with measurements?',['It shows the limits of precision and supports fair comparison','It makes weak evidence look certain','It guarantees identical readings','It prevents later analysis'],0,'Uncertainty helps others interpret differences and decide whether apparent patterns are meaningful.','Honest limits strengthen shared interpretation.'),
  q('causal caution','challenge','Satellite images show tree loss while field teams find fewer nesting birds. What further collaboration best tests a causal explanation?',['Ecologists, analysts and field teams compare multiple sites and alternative factors','A single person guesses the cause','The team counts only the site with the largest decline','Members vote that trees caused everything'],0,'Multiple expertise and sites can test whether habitat loss, rather than another factor, explains the bird pattern.','Correlation needs targeted evidence.'),
  q('collaboration judgement','challenge','Which project is least collaborative scientifically?',['Three specialists integrate results to answer one question','Schools follow a common protocol and pool data','Four people conduct unrelated tests and never exchange evidence','A later team repeats and extends a published method'],2,'Working at the same time is not enough when evidence and purposes are unconnected.','Find parallel work without a shared scientific contribution.'),
  q('advance attribution','challenge','A modern forecast uses old weather records, a satellite network and a new computer model. Which explanation is strongest?',['The advance depends on accumulated records, shared observations and improved analysis','Only the computer programmer contributed','Old records are irrelevant once satellites exist','More technology guarantees accuracy'],0,'The forecast emerges from complementary contributions across time, tools and teams.','Account for all parts of the evidence chain.'),
  q('consensus change','challenge','Why can an evidence-based consensus later change?',['New reliable evidence or better explanations may alter the balance of support','Consensus is merely a temporary popularity contest','Scientists forget previous evidence','A single unsupported claim automatically replaces it'],0,'Scientific judgements remain open to revision when stronger assessed evidence emerges.','Change should be evidence-driven.'),
  q('failure analysis','challenge','An international experiment fails because clocks were not synchronised. What lesson best follows?',['Shared protocols must include precise coordination across sites','International research cannot work','Each site should hide its times','Specialised roles are unnecessary'],0,'Distributed work depends on clear standards, timing and communication so contributions remain comparable.','Identify the coordination failure.'),
  q('integrated reasoning','challenge','Which statement best explains why collaboration often—not always—advances science?',['It can combine expertise, evidence and checking, but quality still depends on sound methods and communication','Any group conclusion is correct','Individuals cannot make observations','Collaboration eliminates uncertainty'],0,'Collaboration provides powerful mechanisms, yet it does not replace rigorous methods or critical review.','Choose a qualified explanation.'),
  q('specific contribution','challenge','A data analyst finds a seasonal pattern that field researchers had not noticed. How did the analyst enable an advance?',['By applying specialised analysis to shared observations, creating a claim the field team can test','By making the field evidence unnecessary','By proving the pattern without checking','By taking ownership of every observation'],0,'Specialised analysis revealed a testable relationship within evidence collected by collaborators.','Name contribution and next scientific use.'),
  q('evidence synthesis','challenge','Two historical studies provide opposite claims, but a new team discovers they sampled different seasons. What is the advance?',['The team explains the disagreement by linking results to sampling conditions','Both earlier studies become worthless','The newest team wins by date','Season can be ignored after publication'],0,'Comparing methods can reconcile apparent conflict and produce a more precise explanation.','Earlier work may become clearer, not useless.')
];

const test = [
  q('specialised roles','foundation','A reef project assigns divers to survey coral, chemists to test water and modellers to predict recovery. Why is this effective collaboration?',['The connected roles supply different evidence for one recovery question','Every member conducts the same test','The prediction replaces surveys','More roles guarantee success'],0,'Each specialist contributes evidence or analysis needed for the shared question.','Connect roles to one purpose.'),
  q('prior findings','foundation','A vaccine storage box uses insulation described in an earlier engineering report. This shows that:',['a new application can build on published design knowledge','the earlier designers did not contribute','reports prevent improvement','only medical workers do science'],0,'The new team applies an earlier tested idea to a different practical problem.','Identify what the report provides.'),
  q('shared observations','core','Island groups use identical tide gauges and upload monthly readings. Why is the network stronger than one gauge?',['It captures patterns across more locations and permits comparison','It makes tides equal on every island','It removes calibration needs','It guarantees a causal explanation'],0,'Coordinated observations broaden geographic evidence while retaining comparability.','Think breadth plus common method.'),
  q('peer response','core','Reviewers say a study’s sample is too small. Which response best advances the work?',['Collect additional representative samples and report whether the pattern remains','Remove the sample size from the report','Ask reviewers to vote for acceptance','Repeat the same calculation only'],0,'New representative evidence directly tests whether the result is stable.','Respond to the stated limitation.'),
  q('incremental timeline','core','Timeline: hand lens observations → microscope images → DNA comparisons. What does the sequence demonstrate?',['New tools let scientists extend and recheck earlier classification evidence','Each tool makes all previous observations false','Only DNA users collaborate','Scientific questions never change'],0,'Successive tools add evidence and can refine classifications built from earlier observations.','Look for extension, not erasure.'),
  q('replication','core','A remote team follows published instructions but does not reproduce a battery result. What is the best next action?',['Compare materials, temperatures and procedures with the original team','Declare one team dishonest immediately','Average a success and failure into certainty','Stop sharing methods'],0,'Method comparison may identify conditions responsible for the different outcomes and guide new tests.','Investigate sources of difference.'),
  q('data table','application','Sensors must last 30 days and transmit every hour. A lasts 45 days/6-hourly; B lasts 32 days/hourly; C lasts 20 days/hourly. Which satisfies both?',['A','B','C','A and C'],1,'B alone meets both duration and transmission-frequency requirements.','Test both criteria.'),
  q('Antarctic science','application','Teams at two Antarctic stations find different moss growth rates. Which collaboration would add the most useful evidence?',['Use matched measurements of light, temperature and moisture at both stations','Select the faster growth as correct','Combine rates without location data','Let station leaders vote'],0,'Matched environmental measurements help explain why growth differs between locations.','Compare relevant abiotic factors.'),
  q('remote sensing','application','Engineers improve a drone camera after ecologists explain that leaf colour distinguishes stressed plants. What enabled the advance?',['Ecological knowledge defined a useful signal for the engineering design','The engineers replaced field science','Leaf colour guarantees the cause of stress','Both groups performed identical work'],0,'The ecologists supplied a biological requirement that engineers translated into a better sensing tool.','Name the link between contributions.'),
  q('restorative ecology','application','A project uses cultural burning knowledge, vegetation surveys and fire-behaviour models. Which claim is most appropriate?',['Different knowledge holders and specialists can jointly guide, test and monitor restoration','Only the computer model deserves recognition','Cultural knowledge cannot be connected to measurements','Combining approaches guarantees no harm'],0,'Respectful partnership can connect accumulated knowledge, current evidence and monitoring without promising certainty.','Look for integration and qualification.'),
  q('ISS program','application','One country supplies a laboratory module, another a robotic arm and several provide crews. Why is the program collaborative?',['The contributions are interdependent within a shared station and research program','Each contribution answers an unrelated question','Hardware alone guarantees discoveries','Countries must have identical expertise'],0,'Different contributions work together in one operating research system.','Interdependence matters.'),
  q('phosphate response','application','Water scientists identify phosphate-driven blooms; chemists formulate an alternative detergent; councils monitor waterways. What does this show?',['Evidence, product development and monitoring form connected contributions','The first discovery made monitoring unnecessary','Councils created the chemical explanation by voting','The alternative cannot have trade-offs'],0,'Different groups turn a finding into action and check outcomes over time.','Trace discovery → application → checking.'),
  q('publication value','challenge','A century-old paper contains inaccurate conclusions but careful raw observations. How may it still contribute?',['Later researchers can reanalyse the observations using improved explanations','Every part must be discarded','Age makes evidence automatically reliable','The old conclusion overrides new data'],0,'Useful observations may remain a foundation even when their original interpretation is revised.','Separate data from interpretation.'),
  q('team bias','challenge','All five collaborators calibrated instruments using the same faulty reference. Why may agreement be misleading?',['A shared systematic error can affect every result','Five readings always remove error','Collaboration converts faulty data into consensus','Calibration never affects evidence'],0,'Common procedures can transmit the same bias across a team, showing why independent checks matter.','Shared work can also share a flaw.'),
  q('consensus evidence','challenge','Twenty scientists endorse a claim, but only two have relevant data and those data conflict. What should determine the judgement?',['The quality and consistency of the evidence, not the number endorsing it','The largest show of hands','The senior scientist’s preference','The earliest claim'],0,'Scientific consensus is earned through assessed evidence rather than simple popularity.','Do not confuse agreement with evidence.'),
  q('overall explanation','challenge','A student says, “Teams advance science because more people means the answer is right.” Which correction is best?',['Teams can combine expertise and independently check evidence, but rigorous methods—not team size—support a conclusion','The statement is correct for teams over ten','Only lone scientists can avoid errors','Teamwork removes the need to publish methods'],0,'Specific collaborative mechanisms can strengthen science, while numbers alone do not establish correctness.','Replace the vague claim with mechanisms and a limit.')
];

const worksheet = [
  {question:'A habitat project uses an ecologist, an engineer and a computer scientist. Describe one distinct contribution from each and explain how the three contributions connect.',modelAnswer:'The ecologist identifies meaningful habitat indicators, the engineer designs a sensor to collect them, and the computer scientist analyses the large dataset. Their linked work turns an ecological question into reliable measurements and patterns that can be checked.'},
  {question:'Explain why four students doing unrelated experiments at one table are not necessarily collaborating scientifically.',modelAnswer:'Physical proximity is not enough. Their work becomes scientific collaboration when their questions, methods, evidence or explanations make connected contributions to a shared investigation or advance.'},
  {question:'Write the sequence claim → review → revision as a realistic example about seed germination.',modelAnswer:'Claim: warmer seeds germinate faster. Review: a classmate notices moisture was not controlled. Revision: the team repeats the test with equal water and narrows its claim to the tested temperature range.'},
  {question:'A second laboratory repeats a published test and finds the same pattern. Explain what this adds and what it does not prove.',modelAnswer:'Independent replication increases confidence that the pattern is reproducible and not peculiar to one laboratory. It does not prove the explanation permanently or remove all uncertainty and possible bias.'},
  {question:'Create a four-event timeline showing how knowledge of one space object could advance through earlier observation, a model, improved equipment and a later mission.',modelAnswer:'Early observers record its position → mathematicians model its orbit → engineers build a sharper telescope → a spacecraft measures its surface and revises details of the model.'},
  {question:'Three schools share water-quality data, but one records phosphate in different units. State the problem and a scientifically responsible response.',modelAnswer:'The values cannot be compared directly until units and any required conversions are checked. The network should verify the method, convert correctly if valid, and label any remaining limitation.'},
  {question:'Explain how contemporary restoration can build respectfully on First Nations ecological knowledge.',modelAnswer:'Researchers should form partnerships with knowledge holders, seek permission, follow cultural protocols, recognise ownership and contribution, and connect agreed place-based knowledge with monitoring rather than extracting or claiming it.'},
  {question:'A satellite algorithm indicates habitat loss. Design one collaborative check involving a field ecologist and data specialist.',modelAnswer:'The data specialist selects a representative sample of changed and unchanged image locations. The ecologist surveys those sites. Together they compare ground conditions with classifications and revise the algorithm if errors form a pattern.'},
  {question:'A detergent change is followed by fewer algal blooms. Name two groups whose work could contribute and one reason continued monitoring is needed.',modelAnswer:'Chemists may design lower-phosphate formulations and freshwater scientists may measure nutrients and algae. Monitoring is needed because weather, farming runoff or other factors may also change bloom frequency.'},
  {question:'Compare one advantage and one challenge of international Antarctic collaboration.',modelAnswer:'It can pool stations, instruments, expertise and observations across wide places and long periods. It also requires careful coordination of methods, units, timing, data access and communication.'},
  {question:'Respond to: “The newest scientific study makes every earlier study worthless.”',modelAnswer:'New work often depends on earlier questions, methods, tools and records. It may correct an old explanation while retaining useful observations or revealing the conditions under which the earlier result applies.'},
  {question:'Using a shared-data example, explain why collaboration can strengthen science without guaranteeing correctness.',modelAnswer:'Schools using one rainfall protocol can provide a broader dataset and check unusual readings. However, all schools could share a faulty gauge design or miss the same variable, so calibration, transparent methods and independent review remain necessary.'}
];

const vocabulary = [
  {term:'collaboration',definition:'connected contributions by people working toward a shared scientific question or advance'},
  {term:'specialisation',definition:'developing expertise in a particular field, method or task'},
  {term:'replication',definition:'independently repeating an investigation to see whether a result is reproducible'},
  {term:'peer review',definition:'evaluation of scientific work by other people with relevant expertise'},
  {term:'consensus',definition:'a broad scientific judgement supported by an assessed body of evidence'},
  {term:'dataset',definition:'an organised collection of observations or measurements'},
  {term:'protocol',definition:'an agreed detailed method that supports consistent work'},
  {term:'baseline',definition:'an earlier measurement or record used for later comparison'},
  {term:'interdisciplinary',definition:'combining knowledge and methods from different fields'},
  {term:'systematic error',definition:'a consistent measurement bias caused by a method or instrument'}
];

const steps = [
  'State the shared scientific question, problem or improvement.',
  'Identify each person’s, community’s or earlier study’s specific contribution.',
  'Explain how the contributions connect through evidence, expertise, tools or methods.',
  'Show how sharing, review or replication enables checking or extension.',
  'Use the available data or timeline rather than assuming that a team must be correct.',
  'Name limitations, shared biases or coordination needs and describe a sensible next check.'
];

const topicSections = [
  {heading:'What scientific collaboration really means',body:'Collaboration is more than people working near one another. Participants contribute to a shared question or advance, exchange evidence and make connected decisions. One investigator may begin an observation, but a wider team can add expertise, locations, equipment and critical checking.'},
  {heading:'Four ways collaboration enables advances',body:'Teams can divide specialist roles, pool observations into larger datasets, check and repeat one another’s work, and build on published evidence or tools. Strong explanations name the contribution and the result it enabled: for example, ecological knowledge defines what a sensor should detect, while engineering makes detection possible at scale.'},
  {heading:'Science accumulates across time',body:'Later science rarely begins from nothing. Recorded observations become baselines; models organise evidence; new instruments test predictions; later teams revise and apply what came before. Revision does not make every earlier contribution worthless—data or methods may remain useful even when an explanation changes.'},
  {heading:'Checking evidence, not counting votes',body:'Peer review can expose gaps, and independent replication tests reproducibility. Scientific consensus rests on the quality and convergence of evidence, not a show of hands. Agreement raises confidence only when methods are sound; shared instruments or protocols can also spread the same systematic error.'},
  {heading:'Collaboration in place and at scale',body:'Antarctic research pools stations and long-term records; remote sensing connects ecologists, engineers and computer scientists; space research combines international modules, missions and historical observations. Restorative ecology can connect current measurements with First Nations ecological knowledge through respectful partnership, permission and recognition.'},
  {heading:'From finding to practical advance',body:'Applying knowledge may require further collaboration. Evidence linking phosphate to algal blooms can guide chemists and manufacturers to change detergent formulations, while freshwater scientists and communities monitor outcomes. Continued checking matters because other environmental factors may influence the result.'}
];

const misconceptions = [
  {claim:'Important advances are made by one brilliant scientist working alone.',correction:'Individuals contribute, but advances often rely on earlier records, teams, technicians, communities, instruments and later checking.'},
  {claim:'A later study makes earlier work worthless.',correction:'Later work may correct an interpretation while retaining useful observations, tools, questions or methods.'},
  {claim:'Scientific consensus is simply a majority vote.',correction:'Consensus is an evidence-based judgement formed through scrutiny of the quality, consistency and limits of many findings.'},
  {claim:'Every collaborator performs the same task.',correction:'Complementary specialist roles are often the reason collaboration can answer a complex question.'},
  {claim:'If several teams agree, the conclusion is guaranteed.',correction:'Agreement strengthens confidence, but teams may share a bias and new evidence can still support revision.'}
];

const importantQA = [
  {question:'Can one person still make a scientific advance?',answer:'Yes. The point is not that individuals are incapable, but that their work commonly uses earlier knowledge and gains strength when others check, extend or apply it.'},
  {question:'Why is independent replication valuable?',answer:'It tests whether a result can be produced beyond one team’s particular people, equipment and habits, reducing some sources of team-specific bias.'},
  {question:'Does collaboration guarantee that a claim is correct?',answer:'No. It can improve coverage, expertise and checking, but sound methods, transparent evidence and attention to shared errors remain essential.'},
  {question:'How should I explain a contribution?',answer:'Use a cause-and-effect statement: who contributed what, and how that contribution enabled evidence to be gathered, checked, extended or applied.'}
];

const assessmentHints = [
  'Name the specific contribution rather than writing only “they worked together”.',
  'Connect each role to the shared scientific question or improvement.',
  'In a timeline, distinguish the earlier foundation from the later extension.',
  'Use every criterion when comparing designs or shared data.',
  'Explain that replication increases confidence rather than proving a claim forever.',
  'Distinguish evidence-based consensus from popularity or authority.',
  'Include a limitation such as shared bias, inconsistent methods or incomplete coverage when evaluating collaboration.'
];

const slides = [
  {title:'Curriculum',kicker:'AC9S6H01',body:[metadata.descriptor]},
  {title:'Learning intention',body:[metadata.learningIntention,...metadata.successCriteria]},
  {title:'Collaboration has a shared purpose',body:[topicSections[0].body,'Quick check: What would connect four separate plant tests into one collaborative investigation?']},
  {title:'Four mechanisms',body:[topicSections[1].body,'Roles • shared data • checking and replication • building on prior work']},
  {title:'Building across time',body:[topicSections[2].body,'Model: earlier observation → model → improved tool → new evidence → revision.']},
  {title:'Evidence, review and replication',body:[topicSections[3].body,'Important: greater confidence is not permanent proof.']},
  {title:'Curriculum case studies',body:[topicSections[4].body,'Explain the connection between contributions in one case.']},
  {title:'From evidence to application',body:[topicSections[5].body,'Trace: phosphate evidence → detergent redesign → waterway monitoring.']},
  {title:'Misconceptions to repair',body:misconceptions.map(item => `${item.claim} → ${item.correction}`)},
  {title:'Important questions and answers',body:importantQA.map(item => `${item.question} ${item.answer}`)},
  {title:'Assessment review',body:['Name the shared goal.','Identify each specific contribution.','Explain how it enabled checking, extension or application.','Qualify the conclusion and identify a useful next check.']},
  {title:'Exit ticket',body:['Describe a scientific advance involving an earlier contribution and a later team.','Explain exactly how one contribution enabled the next.','State one reason the final conclusion should remain open to checking.']}
];

if (practice.length !== 48) throw new Error(`AC9S6H01 practice count ${practice.length}; expected 48`);
if (test.length !== 16) throw new Error(`AC9S6H01 test count ${test.length}; expected 16`);
if (worksheet.length !== 12) throw new Error(`AC9S6H01 worksheet count ${worksheet.length}; expected 12`);
for (const [name, bank] of [['practice', practice], ['test', test]]) bank.forEach((item, index) => {
  if (item.answers.length !== 4 || new Set(item.answers).size !== 4) throw new Error(`${name} ${index + 1}: four distinct options required`);
  if (!Number.isInteger(item.correct) || item.correct < 0 || item.correct > 3) throw new Error(`${name} ${index + 1}: invalid correct index`);
});

export default {
  code: metadata.code,
  descriptor: metadata.descriptor,
  title: metadata.title,
  learningIntention: metadata.learningIntention,
  successCriteria: metadata.successCriteria,
  vocabulary,
  steps,
  topicSections,
  misconceptions,
  importantQA,
  assessmentHints,
  exitTicket: 'Describe an advance involving earlier work and a later team. Name a specific contribution, explain how it enabled the next step, and state why the conclusion remains open to checking.',
  masteryEvidence: 'The student uses an unfamiliar case, timeline or dataset to identify connected contributions, explains how expertise, shared evidence, review or replication enabled an advance, and evaluates confidence without treating collaboration as a guarantee.',
  practice,
  test,
  worksheet,
  slides
};
