"use strict";
const q=[
["ac9s8u02-p-001","organisation","Which sequence shows increasing levels of organisation in a multicellular organism?",["Cell → tissue → organ → organ system","Cell → organ → tissue → organ system","Tissue → cell → organ → organ system","Organ system → organ → tissue → cell"],0,"Similar specialised cells form tissues; tissues form organs; organs work together in organ systems."],
["ac9s8u02-p-002","xylem","Which plant tissue transports water and mineral ions from the roots toward the leaves?",["Phloem","Xylem","Epidermis","Palisade mesophyll"],1,"Xylem transports water and dissolved mineral ions through the plant."],
["ac9s8u02-p-003","phloem","Which plant tissue transports dissolved sugars from sources such as leaves to other parts of the plant?",["Xylem","Phloem","Cortex","Epidermis"],1,"Phloem transports dissolved sugars and other organic substances between plant organs."],
["ac9s8u02-p-004","root-hair","Root hair cells have long projections. How does this structure support their function?",["It increases surface area for absorbing water and mineral ions","It increases light absorption for photosynthesis","It reduces contact with soil particles","It stores sugars produced by leaves"],0,"The long projection increases contact with soil, giving a larger surface area for absorption."],
["ac9s8u02-p-005","palisade","Why do palisade mesophyll cells contain many chloroplasts?",["They absorb most of the light used for photosynthesis","They transport water from roots","They open and close stomata","They form the waterproof leaf surface"],0,"Palisade cells are positioned near the upper leaf surface and contain many chloroplasts for photosynthesis."],
["ac9s8u02-p-006","stomata","What is the main function of stomata in a leaf?",["Control gas exchange and water loss","Transport sugars through the stem","Anchor the plant in soil","Produce new xylem vessels"],0,"Stomata are pores that allow carbon dioxide and oxygen exchange while also affecting water loss."],
["ac9s8u02-p-007","xylem-structure","Which feature makes xylem vessels well suited to water transport?",["They form long hollow tubes with strengthened walls","They contain many chloroplasts","They have valves that prevent backflow","They are covered in cilia"],0,"Mature xylem vessels form continuous hollow pathways, and lignified walls provide support."],
["ac9s8u02-p-008","leaf-structure","A broad, thin leaf is well suited to photosynthesis mainly because it:",["Provides a large light-capturing area and short diffusion distances","Prevents all water loss","Stores most of the plant's minerals","Keeps chloroplasts away from light"],0,"A broad surface captures light, while a thin leaf reduces diffusion distance for gases."],
["ac9s8u02-p-009","artery","Which feature helps arteries withstand the pressure produced by the heart?",["Thick elastic muscular walls","Walls one cell thick","Large numbers of stomata","Very wide pores between cells"],0,"Arteries have thick, elastic and muscular walls that withstand and smooth high-pressure blood flow."],
["ac9s8u02-p-010","capillary","Why are capillary walls only about one cell thick?",["To provide a short diffusion distance between blood and tissues","To generate high blood pressure","To stop substances leaving the blood","To pump blood back to the heart"],0,"Thin capillary walls allow efficient exchange over a short diffusion distance."],
["ac9s8u02-p-011","heart","Why is the wall of the left ventricle thicker than the walls of the atria?",["It must generate enough pressure to pump blood around the body","It stores more oxygen than the atria","It filters wastes from the blood","It receives blood directly from the lungs"],0,"The left ventricle needs a powerful contraction to drive systemic circulation."],
["ac9s8u02-p-012","alveoli","Which structure is the main site of gas exchange in human lungs?",["Trachea","Bronchi","Alveoli","Diaphragm"],2,"Alveoli provide the thin, moist exchange surface where oxygen and carbon dioxide diffuse."],
["ac9s8u02-p-013","alveoli-surface","How does having millions of small alveoli improve gas exchange?",["It creates a very large surface area","It prevents blood reaching the lungs","It increases diffusion distance","It stores oxygen permanently"],0,"Many small alveoli create a large total surface area for diffusion."],
["ac9s8u02-p-014","trachea","Why are C-shaped cartilage rings useful in the trachea?",["They help keep the airway open while allowing some flexibility","They carry oxygen in the blood","They absorb nutrients from food","They increase the surface area of alveoli"],0,"Cartilage supports the trachea so it does not collapse during breathing."],
["ac9s8u02-p-015","cilia","What is the main role of cilia lining parts of the respiratory tract?",["Move mucus and trapped particles toward the throat","Pump oxygen into capillaries","Produce red blood cells","Increase the pressure of inhaled air"],0,"Cilia move mucus containing trapped particles away from the lungs."],
["ac9s8u02-p-016","transpiration-data","A plant loses water at these rates: sunny 12 mL/h, cloudy 5 mL/h, windy 15 mL/h, humid 3 mL/h. Under which condition is transpiration highest?",["Sunny","Cloudy","Windy","Humid"],2,"The greatest measured rate is 15 mL/h under windy conditions."],
["ac9s8u02-p-017","humidity","Why is transpiration usually lower when the air is very humid?",["The water-vapour gradient between leaf and air is smaller","Xylem reverses direction","Roots stop absorbing water completely","Stomata turn into phloem"],0,"Humid air reduces the difference in water-vapour concentration between the leaf and surroundings."],
["ac9s8u02-p-018","exercise-data","Heart rate rises from 70 beats/min at rest to 150 beats/min while running. What is the best explanation?",["Working muscles require faster delivery of oxygen and nutrients and removal of wastes","The heart begins producing glucose","The lungs stop exchanging gases","Blood vessels stop carrying carbon dioxide"],0,"Exercise increases cellular respiration, so circulation must deliver resources and remove wastes faster."],
["ac9s8u02-p-019","systems-working","Which organ system works most directly with the circulatory system to supply oxygen during exercise?",["Respiratory system","Digestive system","Integumentary system","Reproductive system"],0,"The respiratory system exchanges gases and the circulatory system transports them."],
["ac9s8u02-p-020","gas-gradient","Air in an alveolus has a higher oxygen concentration than the blood entering nearby capillaries. What happens?",["Oxygen diffuses from the alveolus into the blood","Oxygen diffuses from blood into the alveolus","Oxygen is pumped across by cartilage","No oxygen movement occurs"],0,"Oxygen diffuses down its concentration gradient from alveolar air into blood."],
["ac9s8u02-p-021","disorder-artery","Hardening and narrowing of arteries can reduce oxygen delivery to tissues because it:",["Restricts blood flow through the vessel","Turns arteries into veins","Increases the number of capillaries immediately","Stops the lungs taking in air"],0,"Narrower, less elastic arteries can reduce blood flow and place greater strain on circulation."],
["ac9s8u02-p-022","alveoli-damage","Damage that destroys alveolar walls is likely to reduce gas exchange mainly because it:",["Reduces available surface area","Makes arteries thicker","Increases the number of chloroplasts","Stops digestion in the stomach"],0,"Loss of alveolar walls reduces the surface available for diffusion."],
["ac9s8u02-p-023","phloem-block","If phloem in a stem is badly damaged, which transport process is most directly reduced?",["Movement of dissolved sugars from leaves to other organs","Movement of oxygen through alveoli","Movement of water through xylem only","Movement of blood through arteries"],0,"Phloem carries dissolved sugars from sources such as leaves to sinks such as roots and growing tissues."],
["ac9s8u02-p-024","dialysis","Which statement best describes what a dialysis machine can do?",["Perform some blood-filtering functions of damaged kidneys","Replace every function of the kidneys permanently","Pump blood around the body like a heart","Exchange oxygen and carbon dioxide like lungs"],0,"Dialysis removes selected wastes and excess water from blood, replacing some but not all kidney functions."]
];
window.skillrPracticeQuestions=q.map(([id,skill,question,answers,correct,summary])=>({id,curriculumCode:"AC9S8U02",bank:"practice",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation:summary+"\nHint: Identify the structure, then connect its feature to the function of the tissue, organ or system.",structuredExplanation:{summary,hint:"Identify the structure, then connect its feature to the function of the tissue, organ or system."},qualitySchema:"production-v2"}));
window.quizQuestions=window.skillrPracticeQuestions;