"use strict";
window.skillrTestQuestions = [
["t-001","organ transplantation ethics","A transplant policy gives extra priority to patients who can privately pay for follow-up care. Which evaluation is strongest?",["The policy may create inequitable access unrelated to medical need","The policy is fair because follow-up care has costs","Economic factors should always override medical urgency"],0,"Economic realities matter, but transplant allocation must also be evaluated for fairness and equitable access."],
["t-002","organ transplantation ethics","Two patients have similar urgency, but one has a much higher predicted chance of transplant success. Why is this still an ethical dilemma?",["Allocation must balance fairness with likely benefit from a scarce organ","The prediction automatically determines who is more deserving","Ethics are irrelevant once success probabilities are known"],0,"Scarcity creates tension between competing ethical principles such as fairness and maximising benefit."],
["t-003","organoids and animal research","A pharmaceutical company shifts early drug screening from animals to organoids. Which claim is most defensible?",["Animal use may decrease, but later whole-organism testing may still be needed for some questions","Organoids remove every ethical issue in biomedical research","Any result from an organoid is more accurate than an animal result"],0,"Organoids can reduce animal use but remain models with limitations."],
["t-004","organoids and animal research","A laboratory reports lower animal use and lower facility costs after adopting organoids, but organoid cultures require expensive specialist equipment. What is the best conclusion?",["The response has ethical and possible economic benefits, but costs must be compared across the whole system","Organoids are economically superior because animal use fell","The equipment cost makes the ethical benefit irrelevant"],0,"Evaluation should weigh multiple considerations rather than rely on a single benefit or cost."],
["t-005","plate-boundary communities","An earthquake early-warning system sends an alert 12 seconds before strong shaking reaches a city. Which impact is realistic?",["Trains may slow, machinery may stop and people may take protective action","Buildings become earthquake-proof for 12 seconds","Scientists can now predict future earthquakes days in advance"],0,"Short warning times can still support protective actions even though they do not predict earthquakes before they begin."],
["t-006","plate-boundary communities","A low-income community cannot afford to retrofit every building at once. Which strategy best addresses scientific and social considerations?",["Prioritise the most vulnerable structures and high-occupancy buildings using risk evidence","Retrofit only the newest buildings because they are easiest","Delay all upgrades until every building can be upgraded together"],0,"Risk-based prioritisation can use scientific evidence while recognising limited resources and social vulnerability."],
["t-007","plate-boundary communities","Why should evacuation drills be evaluated alongside tsunami-warning technology?",["A warning only reduces risk if people can receive, understand and act on it","Drills improve the accuracy of ocean sensors","Community behaviour has no effect on warning-system success"],0,"Technology and community response work together to determine social impact."],
["t-008","low-emission vehicles","A region switches rapidly to electric vehicles but generates most electricity from coal. Which conclusion is most appropriate?",["Tailpipe pollution will fall, but total greenhouse benefits depend on electricity generation and vehicle life cycle","Electric vehicles will have zero emissions overall","The switch cannot reduce any fossil-fuel use"],0,"Environmental impacts should be assessed across the full energy system rather than only at the vehicle exhaust."],
["t-009","low-emission vehicles","Hydrogen vehicles produce water at the point of use, but the hydrogen is made using fossil fuels. Why does production method matter?",["It affects the total greenhouse emissions associated with the fuel","Hydrogen made from fossil fuels cannot power a vehicle","Water emissions make the production method irrelevant"],0,"Life-cycle impacts depend on how hydrogen is produced as well as how it is used."],
["t-010","low-emission vehicles","A government subsidy makes electric cars more affordable but mainly benefits households able to buy new cars. Which consideration does this raise?",["Social equity in who can access the benefits of the scientific response","Whether batteries contain electrical energy","Whether petrol is a fossil fuel"],0,"Policies supporting scientific responses can distribute benefits unevenly across society."],
["t-011","biodegradable materials","A biodegradable package breaks down in industrial composting but persists for years in landfill. What is the best evaluation?",["Its sustainability benefit depends on whether appropriate waste-processing infrastructure exists","The material is not biodegradable under any conditions","Landfill disposal makes all packaging equally sustainable"],0,"A material's real-world impact depends on disposal conditions and systems."],
["t-012","biodegradable materials","A company replaces plastic with a plant-based package that uses more water and energy to manufacture. What should researchers compare?",["Full life-cycle impacts, including production, use and disposal","Only how quickly the package decomposes","Only the amount of plastic avoided"],0,"A full environmental evaluation considers trade-offs across the life cycle."],
["t-013","evaluating scientific responses","Which statement best reflects AC9S8H03?",["A scientific response should be judged by evidence of benefits, risks, trade-offs and impacts on different groups","A response is successful if it is scientifically possible","The cheapest response is always the best response"],0,"Contemporary responses should be examined across ethical, environmental, social and economic dimensions."],
["t-014","evaluating scientific responses","A technology reduces environmental harm but creates a new ethical concern. What is the best next step?",["Compare the seriousness of both effects and consider whether the design or policy can be improved","Reject the technology immediately because any ethical issue is unacceptable","Ignore the ethical concern because environmental benefit is measurable"],0,"Evaluation involves weighing competing considerations and exploring refinements."],
["t-015","evaluating evidence","Which evidence is strongest when deciding whether a scientific response has improved society?",["Measured outcomes over time together with evidence about who benefits, who bears costs and unintended effects","Advertising claims from the technology developer","A single positive user testimonial"],0,"Strong evaluation uses multiple relevant evidence sources, not promotional or anecdotal claims alone."],
["t-016","synthesis","Which scenario best demonstrates a balanced evaluation of a scientific response?",["Electric buses reduce local pollution, but researchers also examine battery production, electricity sources, cost and access","Electric buses are accepted because they are newer than diesel buses","Electric buses are rejected because batteries require mined materials"],0,"Balanced evaluation considers both benefits and limitations across multiple dimensions."]
].map(([id,skill,question,answers,correct,explanation])=>({id:`ac9s8h03-${id}`,curriculumCode:"AC9S8H03",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation,structuredExplanation:{summary:explanation,hint:"Look for the strongest conclusion that weighs evidence, trade-offs and impacts rather than treating the response as all-good or all-bad."},qualitySchema:"production-v2"}));