"use strict";
const Q=[
["balancing reasoning","A student balances H₂ + O₂ → H₂O by changing H₂O to H₂O₂. Why is this invalid?",["Changing the subscript changes water into a different substance rather than changing particle numbers","H₂O₂ contains too few atoms","Subscripts may only be changed on reactants","Balanced equations must contain equal numbers of molecules"],0,"Chemical formulas identify substances; balancing must use coefficients without changing those identities.","Change coefficients, not formulas."],
["particle conservation","Before a reaction there are 4 X₂ molecules and 2 Y₂ molecules. The only product is X₂Y. What is the greatest number of X₂Y particles that can form while conserving atoms?",["4","2","6","8"],0,"There are 8 X atoms and 4 Y atoms. Four X₂Y particles use all 8 X and all 4 Y atoms.","Count total atoms, then build products."],
["limiting reactant","For 2H₂ + O₂ → 2H₂O, a container has 5 H₂ molecules and 3 O₂ molecules. After reaction goes as far as possible, what remains?",["1 H₂ and 1 O₂, with 4 H₂O formed","No reactants, with 8 H₂O formed","1 O₂ only, with 5 H₂O formed","1 H₂ only, with 6 H₂O formed"],0,"Two reaction sets use 4 H₂ and 2 O₂ to make 4 H₂O, leaving 1 H₂ and 1 O₂.","Whole particles react in the 2:1 ratio."],
["closed vs open","A reaction produces a gas. In setup A the flask is sealed; in setup B it is open. Which result best supports conservation of mass?",["A keeps the same total mass; B may show a lower measured mass because gas leaves","Both must show lower mass because gas has no mass","A gains mass because pressure increases","B proves atoms are destroyed"],0,"The sealed system retains gaseous products, while an open measured system can lose matter across its boundary.","System boundaries explain apparent mass changes."],
["mass evidence","A sealed reaction starts at 125.4 g and ends at 125.1 g. What is the strongest first conclusion?",["The small difference may reflect measurement uncertainty, leakage or experimental error and should be investigated","Conservation of mass is disproved","0.3 g of atoms were destroyed","Every chemical reaction loses some mass"],0,"Experimental measurements have uncertainty; a discrepancy should prompt method evaluation before rejecting a well-supported conservation law.","Distinguish theory from measurement quality."],
["combustion mass","A candle becomes lighter while burning in an open room. Why does this not show that mass is destroyed?",["Gaseous products disperse into the surroundings, so the candle alone is not a closed system","Flames convert mass entirely into light","Oxygen has zero mass","Combustion is exempt from conservation laws"],0,"Carbon dioxide, water vapour and other products leave the candle; the relevant system must include the surrounding reactant oxygen and products.","The candle is only part of the reacting system."],
["precipitation","Two clear solutions with total mass 95.0 g are mixed in a sealed container and a solid precipitate forms. What total mass should the container and contents have afterwards?",["95.0 g","More than 95.0 g because solids are heavier","Less than 95.0 g because ions disappear","It cannot be predicted from conservation"],0,"Formation of a solid rearranges ions/atoms but does not create matter in the closed system.","Change of state/appearance does not create mass."],
["equation inference","Which equation is balanced?",["2Al + 3Cl₂ → 2AlCl₃","Al + Cl₂ → AlCl₃","3Al + Cl₂ → 3AlCl₃","2Al + Cl₂ → 2AlCl₃"],0,"The balanced form contains 2 Al atoms and 6 Cl atoms on both sides.","Count Al and Cl separately."],
["mass ratio","Carbon and oxygen react to form only carbon dioxide. If 12 g of carbon reacts completely with 32 g of oxygen, how much carbon dioxide forms?",["44 g","20 g","32 g","384 g"],0,"With only one product in a closed accounting, conservation gives 12 + 32 = 44 g.","Add reactant masses."],
["incomplete accounting","A reaction starts with 50 g of reactants and 42 g of solid product is collected. Which conclusion is justified?",["The missing 8 g may be in another product or may have left the measured system; more information is needed","Exactly 8 g of atoms were destroyed","The reaction cannot be chemical","The solid must actually weigh 50 g"],0,"Mass conservation applies to all products and matter crossing the system boundary, not just one collected product.","Account for every product and boundary transfer."],
["extraction choice","Why can iron oxide be reduced using carbon-based chemistry while aluminium oxide generally requires electrolysis?",["Aluminium is more reactive, so its oxide is harder to reduce chemically with carbon","Iron contains no oxygen","Electrolysis only works on aluminium","Carbon cannot react at high temperatures"],0,"Relative metal reactivity influences whether carbon reduction is feasible.","More reactive metals are harder to extract from compounds."],
["green chemistry tradeoff","Process A gives 95% yield but produces a toxic stoichiometric by-product. Process B gives 90% yield with a reusable catalyst and little hazardous waste. Which evaluation is strongest?",["Yield alone is insufficient; Process B may be greener because waste, hazard and catalyst use also matter","Process A is automatically greener because 95 > 90","Process B violates conservation because it produces less waste","Catalysts always make a process perfectly green"],0,"Green chemistry evaluates multiple dimensions, including waste prevention, hazards, energy and resource efficiency—not yield alone.","Sustainability is multi-factor."],
["atom economy reasoning","Two balanced routes make the same desired product. Route 1 sends 80% of reactant atom mass into the desired product; Route 2 sends 45%. Which has higher atom economy?",["Route 1","Route 2","They are equal because both conserve mass","Atom economy cannot compare balanced reactions"],0,"Atom economy measures how much reactant material becomes the desired product rather than by-products.","Conservation includes waste too; atom economy distinguishes usefulness."],
["catalyst misconception","A catalyst increases the rate of a reaction. Which statement remains true?",["It changes the reaction pathway but does not allow more atoms to appear in the products than were present in the reactants","It creates extra product atoms","It changes the balanced equation's atom counts","It removes the need for conservation of mass"],0,"Catalysts affect rate/pathway, not elemental atom conservation.","Rate and mass conservation are separate ideas."],
["representation","A particle model and balanced equation disagree: the equation conserves 6 oxygen atoms but the diagram shows only 5 in the products. What should be concluded?",["The diagram is inconsistent with the balanced equation and must be corrected","The equation must be wrong because diagrams are always more accurate","One oxygen atom was converted into energy","Chemical diagrams do not need to conserve atoms"],0,"All valid representations of the same reaction should conserve the same atoms.","Cross-check representations atom by atom."],
["whole-system reasoning","A metal oxide is heated with carbon and produces metal plus carbon dioxide. Which statement best demonstrates conservation of mass?",["The total atoms and mass of metal, carbon and oxygen across all reactants equal those across all products in a closed system","The metal product alone must have the same mass as the metal oxide","Carbon dioxide has no effect because it is a gas","The product masses need only be approximately equal to each other"],0,"Conservation applies to the entire reacting system and every product, including gases.","Track all elements and all products." ]
];
window.skillrTestQuestions=Q.map((q,i)=>({id:`ac9s9u07-t-${String(i+1).padStart(3,"0")}`,curriculumCode:"AC9S9U07",bank:"test",skill:q[0],printable:true,type:"single",question:q[1],audioPrompt:q[1],visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers:q[2],correct:q[3],explanation:q[4],hint:q[5]}));