"use strict";
const Q=(id,n,s,q,a,c,e)=>({id,curriculumCode:"AC9M10M04",bank:"test",section:s,sourceNumber:n,skill:s,printable:true,type:"single",question:q,answers:a,correct:c,explanation:e,structuredExplanation:{summary:e,hint:"Track whether the measurement is overestimated, underestimated, or affected by random/systematic error."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q("ac9m10m04-t-001",25,"Error propagation","If the radius used to calculate A=πr² is overestimated, the calculated circle area will be:",["Too small","Too large","Exact","Random"],1,"Area increases with r², so overestimating radius overestimates area."),
Q("ac9m10m04-t-002",26,"Error propagation","Speed is calculated using v=d/t. If distance is correct but time is underestimated, the calculated speed will be:",["Too small","Too large","Exact","Random"],1,"Dividing by a time that is too small makes the calculated speed too large."),
Q("ac9m10m04-t-003",27,"Error propagation","Speed is calculated using v=d/t. If time is correct but distance is underestimated, the calculated speed will be:",["Too small","Too large","Exact","Random"],0,"A distance that is too small gives a speed that is too small."),
Q("ac9m10m04-t-004",28,"Error propagation","Distance and time both have small independent measurement uncertainties. Compared with using only one uncertain quantity, the calculated speed generally has:",["Uncertainty contributed by both measurements","No uncertainty","Exactly zero error","A necessarily negative error"],0,"Because speed depends on both distance and time, both measurement uncertainties contribute to the uncertainty in speed."),
Q("ac9m10m04-t-005",29,"Relative error","A scale has uncertainty ±0.5 g and measures 10 g. What is the relative uncertainty?",["0.5%","1%","5%","10%"],2,"0.5/10=0.05=5%."),
Q("ac9m10m04-t-006",30,"Relative error","A scale has uncertainty ±0.5 g and measures 100 g. What is the relative uncertainty?",["0.5%","1%","5%","10%"],0,"0.5/100=0.005=0.5%."),
Q("ac9m10m04-t-007",31,"Real-world errors","A builder's cutting setup makes every piece of wood 2 mm too short. This is mainly:",["Random error","Systematic error","No impact","Zero error"],1,"A consistent -2 mm bias is systematic."),
Q("ac9m10m04-t-008",32,"Real-world errors","A blood-pressure device consistently reads 5 units too high. This is:",["Random error","Systematic error","No impact","Zero error"],1,"A constant positive offset is systematic."),
Q("ac9m10m04-t-009",33,"Real-world errors","A GPS reading fluctuates unpredictably by about ±3 m around the true position. This is mainly:",["Random error","Systematic error","No impact","Zero error"],0,"Unpredictable fluctuations about the true value are random error."),
Q("ac9m10m04-t-010",34,"Real-world errors","A speed camera is incorrectly calibrated so that every reading is biased in the same direction. This produces:",["Random error","Systematic error","No error","Zero error"],1,"Incorrect calibration can produce a consistent systematic bias."),
Q("ac9m10m04-t-011",35,"Real-world errors","A thermometer consistently reads 2°C too low. Its readings are:",["Too low","Too high","Exact","Randomly high and low"],0,"A -2°C calibration bias makes all readings too low."),
Q("ac9m10m04-t-012",36,"Real-world errors","A student reads an analogue scale from above rather than straight on. This can cause:",["Parallax error","Zero error","No error","Only rounding error"],0,"Viewing a scale at an angle can shift the apparent reading due to parallax."),
Q("ac9m10m04-t-013",37,"Real-world errors","A tape measure has stretched so each marked metre is actually 1.01 m long. If a true 1.01 m length spans one marked metre on the tape, the tape will report the length as:",["1.00 m, so the reading is too short","1.02 m, so the reading is too long","Exactly 1.01 m","Random"],0,"Because each marked unit is physically too long, the stretched tape under-reports true lengths."),
Q("ac9m10m04-t-014",38,"Relative error","A scale with uncertainty ±1 g measures 50 g. What is the relative uncertainty?",["1%","2%","5%","10%"],1,"1/50=0.02=2%."),
Q("ac9m10m04-t-015",39,"Relative error","A scale with uncertainty ±1 g measures 200 g. What is the relative uncertainty?",["0.5%","1%","2%","5%"],0,"1/200=0.005=0.5%."),
Q("ac9m10m04-t-016",40,"Definitions","A measurement error that consistently shifts results in one direction is called:",["Random error","Systematic error","Parallax error","Zero error"],1,"A consistent directional bias is systematic error.")];
window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
