"use strict";
const T=(id,skill,question,answers,correct,explanation,hint)=>({id:`ac9e5la06-t-${String(id).padStart(3,"0")}`,curriculumCode:"AC9E5LA06",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,visual:"",visualHtml:"",answers,correct,explanation:`${explanation}\nHint: ${hint}`,structuredExplanation:{summary:explanation,hint},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
T(1,"head noun","What is the head noun in ‘the two enormous coastal cliffs’?",["two","coastal","cliffs"],2,"‘Cliffs’ is the central noun.","Remove modifiers until the core remains."),
T(2,"modifier","Which word gives size information in ‘a tiny blue beetle’?",["tiny","blue","beetle"],0,"‘Tiny’ describes size.","Ask what kind of information each modifier adds."),
T(3,"noun group","Which is a complete expanded noun group?",["the cracked clay bowl on the shelf","cracked quickly","because the bowl fell"],0,"The group centres on ‘bowl’ and includes description and a qualifier.","Find a noun plus purposeful expansion."),
T(4,"adjective order","Which order is most natural?",["a wooden old box","an old wooden box","a box wooden old"],1,"Age generally precedes material.","Use conventional adjective order."),
T(5,"precision","Which best replaces ‘the animal’ in a field report?",["the awesome animal","the small nocturnal marsupial","the thing"],1,"The second is precise and neutral.","Prefer identifying scientific detail."),
T(6,"qualifier","Which part qualifies the noun after it? ‘the old bridge across the river’",["the old","bridge","across the river"],2,"The prepositional phrase adds location information after the head noun.","Look after the noun."),
T(7,"avoid overload","Which noun group is most effective?",["the huge giant enormous massive tree","the towering gum tree beside the oval","tree tree"],1,"It gives purposeful type and location detail without repetition.","More modifiers are not automatically better."),
T(8,"revision","Which revision best expands ‘The bird landed’?",["The bright green parrot with the red beak landed.","The bird bird landed.","The amazing wonderful bird landed."],0,"The expansion gives observable identifying details.","Add precision rather than vague praise."),
T(9,"effect","Why might a writer use ‘the abandoned cottage beyond the fence’ instead of ‘the cottage’?",["To create a more specific image and possible mood.","To remove the head noun.","To make it a complex sentence."],0,"The modifiers and qualifier shape how readers imagine the setting.","Connect noun-group choice to reader effect."),
T(10,"purpose","Which noun group best suits a science report?",["the fabulous rock","the porous volcanic rock sample","the coolest rock ever"],1,"The group uses precise technical description.","Match language to text purpose."),
T(11,"possession","Which group includes ownership?",["the teacher’s annotated copy","the annotated copy","an interesting copy"],0,"‘Teacher’s’ is possessive.","Ask whose?"),
T(12,"quantity","Which word gives quantity in ‘several narrow channels’?",["several","narrow","channels"],0,"‘Several’ tells how many in a general way.","Find the number/quantity element."),
T(13,"transfer","Which group best distinguishes one bicycle in a rack?",["the bicycle","the red mountain bike with the bent front mudguard","the nice bike"],1,"Specific colour, type and distinctive feature identify the item.","Use details that separate it from others."),
T(14,"cohesion","After a text has clearly introduced ‘the endangered eastern quoll’, which later reference can be suitable when there is no ambiguity?",["the animal","the endangered eastern quoll every time with all details repeated","something"],0,"A shorter noun group can maintain cohesion once the referent is established.","Expand only as much as the reader needs."),
T(15,"misconception","Why is ‘the wonderful amazing fantastic brilliant show’ weak?",["It piles up similar evaluations instead of adding precise information.","Adjectives are forbidden.","The word ‘show’ is not a noun."],0,"Repeated vague praise adds little useful description.","Each modifier should contribute a distinct purpose."),
T(16,"concept","Which statement best describes expanded noun groups?",["They add purposeful information around a head noun to identify, describe or classify more precisely.","They are any long sentence.","They must contain exactly three adjectives."],0,"Expansion can use several kinds of modifiers and qualifiers, not a fixed adjective count.","Focus on the head noun and useful added information.")
];window.skillrExamQuestions=window.skillrTestQuestions;window.quizQuestions=window.skillrTestQuestions;
