"use strict";
const Q=(id,n,section,question,answers,correct,explanation)=>({id:`ac9s10u03-t-${String(id).padStart(3,"0")}`,curriculumCode:"AC9S10U03",bank:"test",section,sourceNumber:n,skill:section,printable:true,type:"single",question,answers,correct,explanation,structuredExplanation:{summary:explanation,hint:"Use the evidence and mechanism in the scenario; eliminate options that overstate what the evidence proves."},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
Q(1,25,"Interpreting spectra","A galaxy has the same identifiable spectral pattern as a nearby comparison galaxy, but every line is shifted farther toward red wavelengths. Which conclusion is best supported?",["It is chemically unrelated to every other galaxy","It is receding faster relative to us","It must be closer to Earth","Its stars emit no short-wavelength light"],1,"A larger redshift generally indicates greater recession in the cosmological context."),
Q(2,26,"Evaluating evidence","Suppose astronomers had found no CMB anywhere in the sky. Which claim would be most directly weakened?",["Stars contain hydrogen","Gravity acts between masses","The universe passed through a hot, dense early state","Earth orbits the Sun"],2,"A relic thermal background is a major prediction and line of evidence for a hot early universe."),
Q(3,27,"Light travel time","Why does seeing distant galaxies also mean seeing the universe in the past?",["Light travels at a finite speed","Galaxies stop changing once observed","Time runs backward beyond the Milky Way","Telescopes create older images"],0,"Light from distant objects takes time to reach us, so we observe them as they were when that light was emitted."),
Q(4,28,"Evaluating models","Two models both explain galaxy redshifts, but only Model X correctly predicts the observed CMB spectrum and light-element abundances. Which model is better supported?",["Model Y, because one observation is enough","Both must be equally correct","Neither can be compared scientifically","Model X, because it explains multiple independent observations"],3,"A model that successfully accounts for multiple independent lines of evidence has stronger empirical support."),
Q(5,29,"Model interpretation","A student says, 'The Big Bang happened at one point in already-existing empty space, so there must be a centre of the universe.' What is the best correction?",["The centre is Earth","The model describes expansion of space itself, so it does not require a centre within space","The centre is the Milky Way","The centre is the largest black hole"],1,"Standard cosmology does not model expansion as matter exploding from a location into surrounding empty space."),
Q(6,30,"Accelerated expansion","Which observation best distinguishes accelerated expansion from simple constant-rate expansion?",["The Sun rises each day","The CMB has microwave wavelengths","Distant standard candles are dimmer/farther than expected from a non-accelerating model","Stars contain helium"],2,"Distance-redshift observations of standard candles helped reveal that cosmic expansion is accelerating."),
Q(7,31,"Element abundance","A universe contains 75% hydrogen and 25% helium by mass in its ordinary matter, with very little lithium. Why is this pattern important?",["It is broadly consistent with predictions of early-universe nucleosynthesis","It proves all elements formed in modern stars","It shows galaxies are not expanding","It means the universe is only 4.5 billion years old"],0,"The observed primordial light-element proportions broadly match Big Bang nucleosynthesis predictions."),
Q(8,32,"CMB","If the universe expands, why does the CMB shift from much shorter wavelengths in the past to microwaves today?",["Gravity converts all photons into matter","Microwaves travel faster than visible light","Stars absorb all shorter wavelengths","Expansion stretches photon wavelengths"],3,"Cosmic expansion stretches wavelengths, redshifting relic radiation into the microwave range."),
Q(9,33,"Light travel time","A telescope detects a galaxy whose light has taken 10 billion years to reach Earth. Which statement is correct?",["We see its exact present state","We see the galaxy as it was roughly 10 billion years ago","The galaxy must be 10 billion light-years away in every cosmological distance definition","The light travelled instantaneously"],1,"Lookback time means we observe the source at an earlier stage in cosmic history."),
Q(10,34,"Model limits","Which claim is outside what the Big Bang model currently explains with confidence?",["That the universe was hotter and denser in the past","That cosmic expansion has occurred","What, if anything, caused the earliest cosmic state described by the model","That light-element abundances carry information about the early universe"],2,"The Big Bang model describes cosmic evolution from an early hot, dense state; the ultimate cause or earliest quantum-gravity regime remains unresolved."),
Q(11,35,"Redshift","A scientist compares two galaxy spectra. Galaxy X has z=0.01 and Galaxy Y has z=0.05. At these small redshifts, which is the best inference?",["Galaxy Y has the greater recession speed","Galaxy X has the greater recession speed","Both must be approaching Earth","Redshift cannot contain motion information"],0,"At small redshift, larger z corresponds approximately to larger recession speed."),
Q(12,36,"CMB","Why are small CMB anisotropies compatible with a universe that is highly uniform on large scales?",["They show the CMB is actually produced by stars","They prove physical constants varied randomly everywhere","They mean galaxies existed before the CMB","They are tiny departures from an almost uniform background and seeded later structure"],3,"The CMB is extremely uniform overall, with small fluctuations that trace early density differences."),
Q(13,37,"Spectroscopy","Which observation would be strongest evidence that a star contains hydrogen?",["The star is bright","Hydrogen's characteristic absorption or emission lines appear in its spectrum","The star appears red","The star is far from Earth"],1,"Elements have characteristic spectral line patterns."),
Q(14,38,"Cosmic components","A student says 'dark matter and dark energy are the same because both are invisible.' Which distinction is best?",["Dark energy forms stars; dark matter forms atoms","Dark matter emits microwaves; dark energy emits visible light","Dark matter clusters gravitationally; dark energy is associated with accelerated cosmic expansion","They are identical terms used by different astronomers"],2,"Dark matter and dark energy are distinct inferred components with different cosmological roles."),
Q(15,39,"Nature of science","Why can scientific models of the universe change even when they are strongly supported?",["New evidence can refine parameters, expose limitations or favour a better model","Scientific theories are only guesses","Old evidence becomes automatically false","Models must change every year"],0,"Scientific models are evidence-based but remain open to refinement when new observations or improved theories become available."),
Q(16,40,"Synthesis","Which conclusion best combines redshift, CMB and light-element evidence?",["The universe has always been static and cold","All matter formed recently inside the Milky Way","Earth occupies the centre of cosmic expansion","The universe has expanded and cooled from a much hotter, denser early state"],3,"These independent lines of evidence converge on an expanding universe with a hot, dense early history.")
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
