"use strict";
const q=(n,skill,question,answers,correct,explanation,hint)=>({id:`ac9s7u01-t-${String(n).padStart(3,"0")}`,curriculumCode:"AC9S7U01",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,visual:"",visualHtml:"",visualMeta:{type:"none",alt_text:""},answers,correct,explanation,structuredExplanation:{summary:explanation,hint},qualitySchema:"production-v1"});
window.skillrTestQuestions=[
q(1,"key construction","Four unfamiliar animals differ in feathers, fur and number of legs. Which first couplet makes the strongest start to a dichotomous key?",["Has feathers / does not have feathers","Looks friendly / does not look friendly","Lives nearby / lives far away","Is large / is small"],0,"Feathers are an observable, repeatable feature and the two choices are mutually exclusive.","A strong couplet uses one clearly observable characteristic."),
q(2,"key critique","A key uses the pair ‘body length above 10 cm / body length below 15 cm’. Why is this invalid?",["Specimens from 11–14 cm fit both choices","Length can never be used in a key","A key must use colour first","Both choices must describe different body parts"],0,"Overlapping ranges make the couplet ambiguous because some specimens satisfy both statements.","Every specimen must fit exactly one branch."),
q(3,"use a key","A key says: 1a wings present → 2; 1b wings absent → 3. A specimen has wings. What should the user do next?",["Go to step 2","Go to step 3","Choose whichever step seems likely","Identify it immediately without more evidence"],0,"Dichotomous keys are followed sequentially according to the observed feature.","Follow the direction attached to the matching statement."),
q(4,"repair a key","A five-organism key identifies four organisms but has no route for the fifth. What is the best response?",["Revise a suitable couplet and retest every pathway","Declare the fifth organism unclassifiable","Add a third choice to every couplet","Remove one of the original organisms"],0,"A complete key must provide one unambiguous route for every organism it is designed to identify.","A repair must preserve the two-choice structure and completeness."),
q(5,"feature selection","Students classify four local leaves. Which feature is most useful in a key?",["Margin smooth or toothed","Looks healthy or unhealthy","Found in a nice place or an unpleasant place","Large or small with no measurement boundary"],0,"Leaf margin is observable and can be defined clearly, unlike subjective descriptions.","Prefer stable, measurable or clearly observable traits."),
q(6,"classification evidence","Two organisms live in the same wetland but one has jointed legs and an exoskeleton while the other has a backbone. What is the best conclusion?",["Habitat alone does not show that they belong to the same major classification group","They must be closely classified because they share a habitat","They must be the same species","Structural evidence should be ignored"],0,"Shared habitat can occur in distantly classified organisms; structural evidence is more diagnostic here.","Separate ecological location from biological classification evidence."),
q(7,"scientific names","Why is a scientific name more useful than a common name when scientists in different countries discuss one species?",["It follows an agreed naming convention that reduces ambiguity","It proves the organism’s habitat","It never changes under any circumstances","It replaces the need to observe features"],0,"Standard scientific naming supports consistent international communication.","Think about what happens when one organism has several local common names."),
q(8,"naming format","Which typed scientific name follows standard binomial formatting?",["*Canis lupus*","*canis Lupus*","CANIS LUPUS","lupus Canis"],0,"The genus begins with a capital letter, the species epithet is lowercase, and both are italicised when typed.","Check order, capitals and italics."),
q(9,"changing classification","Microscopy reveals a previously unseen cell feature that strongly separates two organisms placed in the same group. What should scientists do?",["Reconsider the grouping using the new evidence","Ignore the observation because classifications cannot change","Keep the grouping solely because the organisms have similar colours","Replace both scientific names with common names"],0,"Scientific classifications can be revised when stronger evidence changes understanding of relationships.","Classification is evidence-based, not permanently fixed."),
q(10,"classification purpose","A student says classification is just memorising kingdom names. Which response best matches AC9S7U01?",["Classification also organises biodiversity and provides tools for identifying and comparing organisms","The student is correct because keys are unrelated","Classification is only used for extinct organisms","Classification is mainly a spelling system"],0,"The curriculum focus includes the purpose of classification and practical use and development of classification tools.","The descriptor goes beyond taxonomy recall."),
q(11,"key design alternatives","Two students build different dichotomous keys that both identify the same six organisms correctly. Which statement is best?",["Both can be valid if every couplet is clear, mutually exclusive and leads to one identification","Only the key with the same order as the textbook can be valid","A valid key must begin with kingdom","Different keys prove one student guessed"],0,"There can be multiple valid key structures for the same organism set.","Judge the logic of the choices, not whether the order is identical."),
q(12,"field identification","A specimen reaches ‘beetle’ in a key, but the student then notices it lacks a feature required by that identification. What should the student do?",["Recheck the observations and pathway through the key","Ignore the mismatch because the final answer cannot be questioned","Change the specimen description","Assume the key proves it is a beetle"],0,"Identification should remain consistent with observed evidence; a mismatch requires checking the observations or key pathway.","A key supports reasoning; it does not override contradictory evidence."),
q(13,"First Nations knowledge","Which statement is appropriate when comparing classification knowledge systems in Australia?",["First Nations classification knowledge is diverse, place-based and connected to particular Peoples and purposes","There is one identical First Nations classification hierarchy across Australia","All First Nations systems use Latin binomial names","One system should automatically be ranked as scientifically inferior"],0,"First Nations knowledges are diverse and culturally and geographically situated.","Avoid treating many Peoples and Countries/Places as one uniform system."),
q(14,"source responsibility","A class wants to include a local First Nations classification example. What is the most responsible approach?",["Use an appropriately sourced example connected to the relevant People and Country/Place","Invent a generic example that sounds traditional","Combine examples from different communities without attribution","Assume all publicly visible cultural knowledge is unrestricted"],0,"Specific cultural knowledge should be represented with appropriate source, context and authority.","Place and provenance matter."),
q(15,"unfamiliar transfer","A new organism has six jointed legs, an exoskeleton and antennae. Which evidence is most useful for placing it in a broad biological group?",["Its structural characteristics","The colour of the container it was found in","Whether students like it","The day of the week it was collected"],0,"Classification should use relevant biological characteristics; jointed appendages and an exoskeleton are informative structural evidence.","Choose biological evidence that reliably distinguishes groups."),
q(16,"synthesis","Which task best demonstrates full understanding of AC9S7U01?",["Use observable evidence to classify unfamiliar organisms, follow a dichotomous key, then construct and test a valid key","Recite seven taxonomic ranks only","Memorise common names for ten animals","Sort organisms by personal preference"],0,"The code requires understanding the role of classification and using and developing classification tools, especially dichotomous keys.","Look for purpose, use and construction of a classification tool."),
];
window.skillrExamQuestions=window.skillrTestQuestions;
window.quizQuestions=window.skillrTestQuestions;
