"use strict";
const q=(id,question,answers,correct,explanation)=>({id,type:"single",question,answers,correct,explanation});
window.quizQuestions=[
q("ac9e7la01-t01","In a group chat, Noor writes 'Legend! You saved us.' In a formal thank-you note, she writes 'I greatly appreciate your assistance.' What does the contrast show?",["She changes register to suit audience and context.","She changes the factual meaning completely.","Formal writing cannot express identity.","Only the group-chat message has a social purpose."],0,"Different registers can express the same core meaning while presenting identity differently for different audiences."),
q("ac9e7la01-t02","A character repeatedly calls classmates 'team' instead of 'guys' or their names. What effect can this have?",["It removes all relationship meaning.","It can construct a cooperative group identity.","It proves the character is a sports coach.","It makes the language automatically formal."],1,"A recurring collective address term can position others as members of a shared group."),
q("ac9e7la01-t03","Which line most strongly suggests a character is trying to distance themself from a group?",["We're in this together.","Our plan is nearly ready.","That's their problem, not mine.","Let's hear everyone's idea."],2,"The contrast between 'their' and 'mine' marks separation rather than shared identity."),
q("ac9e7la01-t04","A speaker who normally says 'yeah' and 'nah' begins using 'certainly' and 'I disagree respectfully' during a debate. What is the best interpretation?",["The speaker has forgotten their normal vocabulary.","The speaker's identity has disappeared.","The speaker is changing facts.","The speaker is adopting a more formal debate persona."],3,"Register shifts can be strategic, helping speakers present themselves differently in different settings."),
q("ac9e7la01-t05","Which language choice most clearly constructs a caring older-sibling identity?",["I'll wait with you until you're ready.","You are objectively younger than me.","A sibling is a family member.","The bus arrives at eight."],0,"The supportive promise reveals a relationship-based identity through action and tone."),
q("ac9e7la01-t06","A character says, 'Around here, we always back each other.' Which feature most strongly creates community identity?",["The adverb 'always' only.","The inclusive pronoun 'we' combined with a shared value.","The present tense.","The word 'here' by itself."],1,"Inclusive pronouns plus a statement of shared values construct group belonging."),
q("ac9e7la01-t07","A writer wants a character to sound like an outsider trying to fit into a friendship group. Which choice would best show this?",["The character speaks exactly like the group from the beginning.","The character never speaks.","The character tries the group's slang but uses one expression awkwardly.","The character uses only stage directions."],2,"Partial or awkward adoption of group language can reveal a developing but uncertain social identity."),
q("ac9e7la01-t08","Which explanation best describes why a person might use different vocabulary at home, with friends and at school?",["They have three unrelated identities.","One setting must use incorrect language.","Vocabulary never has social meaning.","People adapt language to relationships and contexts while expressing different aspects of identity."],3,"Language variation across contexts is normal and can express different aspects of a person's social identity."),
q("ac9e7la01-t09","A character says, 'I'm the one who checks every detail before we submit.' What does this line primarily construct?",["A careful, responsible personal identity.","A distant social relationship.","An informal regional identity.","A completely neutral voice."],0,"The self-description positions the character as careful and responsible."),
q("ac9e7la01-t10","Two friends use a private nickname for each other that no one else understands. What can the nickname signal?",["A formal workplace hierarchy.","Shared history and closeness within the friendship.","That the friendship is fictional.","That nicknames have no identity function."],1,"Private forms of address often signal familiarity, shared experience and belonging."),
q("ac9e7la01-t11","A student writes, 'As a volunteer at the shelter, I've seen how patient these animals can be.' Which part most directly establishes social identity?",["The adjective 'patient'.", "The contraction 'I've'.", "The role statement 'As a volunteer at the shelter'.", "The plural noun 'animals'."],2,"Naming a social role explicitly positions the speaker in relation to a community or activity."),
q("ac9e7la01-t12","A character changes from calling another character 'Professor Chen' to 'Lena' near the end of a story. What could this shift suggest?",["The professor changed jobs.","The character forgot the surname.","The story became less grammatical.","The relationship has become more familiar or personally close."],3,"Moving from title plus surname to first name can reduce social distance."),
q("ac9e7la01-t13","Which sentence most clearly uses language to claim membership in a group?",["We robotics kids practically live in the workshop during competition week.","Robotics is an extracurricular activity.","Some students use workshops.","The competition occurs annually."],0,"The inclusive 'we' and group label explicitly claim membership and shared experience."),
q("ac9e7la01-t14","Why might an author contrast a character's polished public speech with their very casual private speech?",["To show that one version must be false.","To reveal how the character presents different aspects of identity in different contexts.","To prove casual speech has no grammar.","To remove complexity from the character."],1,"Contrasting registers can reveal how identity is performed differently across social situations."),
q("ac9e7la01-t15","A character responds to criticism with, 'I hear your point, but I don't agree.' What social persona does this language most strongly construct?",["Aggressive and dismissive.","Uncertain and confused.","Respectful but assertive.","Playful and sarcastic."],2,"The line acknowledges another view while maintaining a clear position, creating a respectful but assertive persona."),
q("ac9e7la01-t16","A student says, 'The way someone speaks tells you exactly who they are.' Which response is most accurate?",["Correct; one sentence reveals a person's complete identity.","Correct; language never changes with context.","Incorrect; language has no connection with identity.","Incorrect; language can signal identity, but people adapt language across contexts and cannot be reduced to one speech style."],3,"Language is an important identity resource, but identity is complex and context-dependent.")
];
