"use strict";
window.skillrTestQuestions = [
["t-001","causal reasoning","Drop-height data show indentation depth rises from 2 mm to 5 mm to 9 mm as height increases, while mass and surface are controlled. Which conclusion is strongest?",["Greater drop height caused deeper indentation under these tested conditions","The data only show correlation because controlled experiments cannot support causal claims","Mass must have changed even though it was controlled"],0,"A controlled manipulation of height with a measured response can support a causal conclusion within the tested conditions."],
["t-002","correlation","Study time and test scores show a positive correlation across a year group. What additional evidence would strengthen a causal claim?",["A controlled study accounting for prior achievement and other relevant factors","A larger scatter plot with the same uncontrolled data","One student who studied longer and scored higher"],0,"Potential confounding variables must be considered before moving from correlation to causation."],
["t-003","anomaly","A wind-turbine data set rises steadily with wind speed except one low point at 14 m/s. Maintenance logs show a temporary fault at that time. How should the point be treated?",["Retain and annotate it as an explained anomaly rather than silently deleting it","Delete it because anomalies should never appear in final data","Use it to reject the overall trend"],0,"An explained anomaly can remain in the record with context about its cause."],
["t-004","mean and outlier","Data are 5, 6, 6, 7 and 31. Which summary best represents the typical result?",["The median, because the extreme value strongly affects the mean","The mean, because it is always the best measure","The maximum, because it captures the full range"],0,"For a data set with a strong outlier, the median can better represent the centre."],
["t-005","median","Reaction times are 8.2, 7.9, 15.0, 8.1 and 8.0 s. What is the median?",["8.1 s","9.44 s","15.0 s"],0,"Sorting gives 7.9, 8.0, 8.1, 8.2, 15.0, so the middle value is 8.1 s."],
["t-006","spreadsheet anomaly","Daily solar output is normally 28–35 kWh. One clear day records 0 kWh, while weather logs show full sun. What should be checked first?",["Sensor, inverter and data-logging records for that day","Whether all clear days should be removed from the data","Whether the yearly mean should replace the zero automatically"],0,"A value inconsistent with both the broader pattern and external conditions should trigger investigation of measurement or equipment issues."],
["t-007","short-term pattern","Solar output falls for four consecutive overcast days and then returns to its previous range. Which interpretation is best?",["A temporary pattern linked to weather rather than an isolated random anomaly","A permanent decline in panel efficiency","Four unrelated outliers that should each be deleted"],0,"Several consecutive values associated with a known condition form a short-term trend."],
["t-008","trendline","A battery-output graph contains small fluctuations but an overall downward trend over 100 cycles. Why use a trendline?",["To summarise the overall decline without pretending every point follows it exactly","To remove all fluctuations from the original data","To guarantee an exact prediction for cycle 150"],0,"Trendlines summarise overall relationships while raw variation remains important."],
["t-009","battery comparison","Battery A retains 92% of initial output after 100 cycles; Battery B retains 76%. What conclusion is justified?",["Battery A showed slower performance decline under the tested conditions","Battery A will always last longer in every use case","Battery B must contain less chemical energy at the start"],0,"The comparison supports a statement about observed degradation, not every possible condition or starting energy."],
["t-010","battery anomaly","A battery's output is 20% higher for one cycle immediately after cooling, then returns to the previous trend. Which explanation is most reasonable to investigate?",["A temporary temperature effect on battery performance","Permanent chemical improvement caused by one cooling event","A change in the unit used for every previous cycle"],0,"A one-cycle departure associated with changed temperature suggests a temporary environmental effect."],
["t-011","reaction plateau","Temperature change rises as reactant A is increased, then levels off while reactant B stays fixed. What does the plateau most likely indicate?",["Reactant B has become limiting, so extra A produces little additional change","The relationship must be invalid because scientific trends cannot plateau","The thermometer can no longer measure high temperatures"],0,"A plateau commonly indicates another factor has become limiting."],
["t-012","reaction anomaly","Three repeated trials give temperature changes of 8.4°C, 8.6°C and 3.1°C. What is the best next step?",["Check the third trial for heat loss, mixing or measurement problems and repeat if appropriate","Average the three immediately and ignore the discrepancy","Delete 3.1°C solely because it is the lowest value"],0,"A large discrepancy should be investigated before deciding how to treat the result."],
["t-013","non-linear trend","A graph rises steeply at low reactant proportions but gradually flattens at higher proportions. Which description is best?",["A positive but non-linear relationship with diminishing increase","A negative linear relationship","No relationship because the slope changes"],0,"A changing slope indicates a non-linear relationship even though the overall direction remains positive."],
["t-014","multiple evidence sources","A student claims a low solar-output day was caused by cloud. The weather log shows clear skies, but maintenance records show an inverter shutdown. Which conclusion is strongest?",["The maintenance evidence better explains the anomaly than cloud cover","The original cloud explanation should be kept because it was proposed first","The anomaly has no possible explanation because the sources disagree"],0,"When analysing anomalies, compare explanations against relevant independent evidence."],
["t-015","statistics choice","A data set has a tightly clustered group plus two extreme high values. Which analysis approach is strongest?",["Report the distribution, identify the extremes and compare mean with median","Use only the mean and ignore the shape of the data","Remove the two largest values before examining them"],0,"Good analysis considers both central tendency and the influence of anomalies."],
["t-016","synthesis","Which statement best captures AC9S8I05?",["Use numerical and visual evidence to describe patterns and relationships, then investigate anomalies before drawing conclusions","Find a trend and remove any data that does not fit it","Calculate an average and treat it as the complete analysis"],0,"The descriptor requires pattern, trend and relationship analysis together with anomaly identification and evaluation."]
].map(([id,skill,question,answers,correct,explanation])=>({id:`ac9s8i05-${id}`,curriculumCode:"AC9S8I05",bank:"test",skill,printable:true,type:"single",question,audioPrompt:question,answers,correct,explanation,structuredExplanation:{summary:explanation,hint:"Use the whole data pattern, appropriate statistics and independent evidence before deciding what an unusual value means."},qualitySchema:"production-v2"}));